### ISSUE TITLE
no rule for make target "winpthreads"

### ISSUE THREAD

**Issue by fAntel** [mxe/mxe#1008]
Hello
I try compile mxe with the following settings.mk:
> JOBS := 1
> MXE_TARGETS := x86_64-w64-mingw32.static i686-w64-mingw32.static
> LOCAL_PKG_LIST := winpthreads pcre zlib lzo bzip2 cunit
> .DEFAULT local-pkg-list:
> local-pkg-list: $(LOCAL_PKG_LIST)

And I had got error: "make: no rule for make target "winpthreads"". I use Gentoo and I have all pre-required packages. Where can I get _winpthreads_ or why this error may occur?

**Comment by saiarcot895** [comment]
With #958, the building of winpthreads is done within gcc.

**Comment by TimothyGu** [comment]
We used to have a separate `winpthreads` package; then that package got folded into `gcc`. Feel free to remove `winpthreads` from the list.

Also, I don't think you understand what the `LOCAL_PKG_LIST` variable is used for. If that's the case, here's what it means:

```make
# The three lines below makes `make` build these "local
# packages" instead of all packages.
```

(that explanation was added later)
