### ISSUE TITLE
download gmp failed

### ISSUE THREAD

**Issue by benlucchesi** [mxe/mxe#1010]
Hi,

I'm trying to use mxe to build ffmpeg. here's what I'm getting when I run: make ffmpeg

Download failed or wrong checksum of package gmp!
------------------------------------------------------------
  1600K .......... .......... .......... .......... .......... 86%  312K 1s
  1650K .......... .......... .......... .......... .......... 89%  375K 1s
  1700K .......... .......... .......... .......... .......... 91%  548K 1s
  1750K .......... .......... .......... .......... .......... 94%  336K 0s
  1800K .......... .......... .......... .......... .......... 97%  384K 0s
  1850K .......... .......... .......... .......... .......... 99%  395K 0s
  1900K ....                                                  100%  142K=6.8s
2015-11-25 16:34:56 (282 KB/s) - written to stdout [1950316/1950316]
------------------------------------------------------------
[log]      /Users/benlucchesi/mxe/log/gmp-download

make: *** [download-only-gmp] Error 1

the log/gmp-download shows the same information.

I'm totally new to this, so any help figuring this out would be great.

thanks

**Comment by TimothyGu** [comment]
Try rerunning the command. The download works just fine here.

**Comment by benlucchesi** [comment]
Thanks for trying Timothy. Unfortunately its still not working for me.

with respect to the requirements, I installed required software with brew
instead of macports or rudix. when I run make it isn't complaining about
requirements anymore, however, could this be impacting the commands being
called from the make file? From what I can tell the use of sed, wget, etc
all look pretty straight forward.

**Comment by benlucchesi** [comment]
also... this is what I get when I run make build-requirements

 make build-requirements

[using autodetected 6 job(s)]

make[1]: *** No rule to make target `autoconf'.  Stop.

make: *** [build-requirements] Error 2

**Comment by tonytheodore** [comment]
The OSX requirements need an update, `build-requirements` is going away and in the mean time you'll also need to install `gsed` and `coreutils`.

The checksum failure could be related to `gsed` - do other packages download correctly?

**Comment by tonytheodore** [comment]
> The OSX requirements need an update

See https://github.com/mxe/mxe/commit/cdb7e99dd692025819f4b6cd63791e52f09d1db7 and the [updated version](http://mxe.cc/#requirements-macos).

Do you have a list of the homebrew packages? It would be a good to add them to the docs.

**Comment by benlucchesi** [comment]
Here's the list of brew formula installed. gsed was installed as part of
gnu-sed.

autoconf
automake
cmake
libtool
gnu-sed
gettext  (installs autopoint)
     export PATH=${PATH}:/usr/local/opt/gettext/bin
p7zip
wget
gdk-pixbuf
intltool
Xz
coreutils

Also, I found the problem. The default version of openssl that is installed
on the mac is "OpenSSL 0.9.8zg 14 July 2015". To solve the problem I added
the open ssl from brew to my path /usr/local/Cellar/openssl/1.0.2d_1/bin/.
The version installed by brew is OpenSSL 1.0.2d 9 Jul 2015 and things
appear to be building fine. This makes sense because the checksum was
failing!

thanks!

-ben

**Comment by tonytheodore** [comment]
> Here's the list of brew formula installed

Thanks! https://github.com/mxe/mxe/commit/85f9305ab4efa0a39dcfb423ea7470b43e217303

> To solve the problem I added the open ssl from brew to my path /usr/local/Cellar/openssl/1.0.2d_1/bin/.

isn't there an `openssl` in `/usr/local/bin`? It seems strange that it wouldn't install there.

**Comment by benlucchesi** [comment]
Yes, openssl is in /usr/local/bin, but its too old. Per the requirements
documentation:

OpenSSL <https://www.openssl.org/>-dev≥ 1.01
/usr/local/bin is only 0.9.8.

After putting the newer version from the cellar packages in my path,
everything started working. Definitely worth adding to the documentation.


so I'm getting ffmpeg to build, and its bombing out when building lame.

Failed to build package lame for target i686-w64-mingw32.static!

configure.in:376: warning: macro 'AM_ICONV' not found in library

configure.in:376: error: possibly undefined macro: AM_ICONV

      If this token and others are legitimate, please use m4_pattern_allow.

      See the Autoconf documentation.

autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit
status: 1

make[1]: *** [build-only-lame_i686-w64-mingw32.static] Error 1

any ideas?

**Comment by tonytheodore** [comment]
> Yes, openssl is in /usr/local/bin, but its too old

The one in `/usr/bin` is too old, but `/usr/local/bin` should be the one from homebrew, right? Is `/usr/local/bin` earlier in your `$PATH`?

> configure.in:376: error: possibly undefined macro: AM_ICONV

You likely have versions of things installed in different locations - the version checks are not sufficient to ensure everything is working together. Can you make a `gist` of the full log?

**Comment by benlucchesi** [comment]
/usr/local/bin doesn't symlink to the openssl in the /usr/local/Cellar/....
I think /usr/local/bin/openssl comes with OSX. I added a path to the cellar
location and it fixed the build issue.

Here's the gist for lame_i686-w64-mingw32.static

https://gist.github.com/benlucchesi/13f8a680512145c1de6b

**Comment by tonytheodore** [comment]
> /usr/local/bin doesn't symlink to the openssl in the /usr/local/Cellar/....

It should, have you got homebrew set up correctly? `/usr/bin/openssl` comes with OSX, `/usr/local/` is empty and only has things you've installed (though maybe indirectly).

You can try the recently merged experimental replacement (#935) for `build-requirements`:

```
make libtool MXE_PLUGIN_DIRS=plugins/native
```

**Comment by benlucchesi** [comment]
Sorry... I misread where openssl was originating from. I was in /usr/bin
and it is an older version. the version that was in the cellar wasn't
symlinked to /usr/local/bin/... not sure why.

As for the machine setup, its a fresh install of OSX 10.11 with virtually
nothing on it but xcode, brew, and whatever is needed for mxe.

running:

make libtool MXE_PLUGIN_DIRS=plugins/native

returned with:

Bens-MacBook-Pro:mxe benlucchesi$ make libtool
MXE_PLUGIN_DIRS=plugins/native

[using autodetected 6 job(s)]

[download]  m4

[no-build]  m4                     i686-w64-mingw32.static


[download]  autoconf


[no-build]  autoconf               i686-w64-mingw32.static


[download]  automake


[no-build]  automake               i686-w64-mingw32.static


[download]  libtool


[no-build]  libtool                i686-w64-mingw32.static

**Comment by tonytheodore** [comment]
Very strange, I'm running out of ideas. Can you try:
```
make libtool MXE_PLUGIN_DIRS=plugins/native MXE_TARGETS=`./ext/config.guess`
```

**Comment by benlucchesi** [comment]
ok, I finally got it!

in order to correctly build with the libs in gettext, I needed for symlink
them to usr/local/lib
   brew list gettext --force

-ben
