### ISSUE TITLE
muparserx is broken on Wheezy

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1012]
https://gist.github.com/starius/468deaedd3bf94b454bb
Commit 19d0acd474e39fbc2c2f7f136f9abaafdfcdc337

**Comment by tonytheodore** [comment]
> CMake Error at CMakeLists.txt:22 (add_compile_options):
  Unknown CMake command "add_compile_options".

First appears in [cmake 2.8.12](https://cmake.org/cmake/help/v2.8.12/cmake.html#command:add_compile_options). Time to build our own.

**Comment by tonytheodore** [comment]
Was the build in https://github.com/mxe/mxe/issues/962#issuecomment-160554097 on Wheezy?

**Comment by starius** [comment]
Yes, https://github.com/mxe/mxe/issues/962#issuecomment-160554097 was on Wheezy.

**Comment by tonytheodore** [comment]
Great! Didn't want to hijack that thread.
