### ISSUE TITLE
Empty freetype package?

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1018]
Latest [`build-pkg` log](https://gist.github.com/starius/9191afe744b83821674a) has lots of:

```
... depends on empty item i686-w64-mingw32.static~freetype
```

both `freetype` and `harbuzz` were recently updated and this package shouldn't be empty.

**Comment by starius** [comment]
Package freetype doesn't create new files except `i686-w64-mingw32.static/installed/freetype`, that is why `build-pkg` doesn't see it.

```
[build-pkg] Item x86_64-w64-mingw32.shared~freetype changes usr/x86_64-w64-mingw32.shared/bin/libfreetype-6.dll, created by x86_64-w64-mingw32.shared~freetype-bootstrap
```

Modified files are owned by the package which created them.

```patch
commit d81574063677937e7b76bc5354bfafa4230cdba6
Author: build-pkg <build-pkg@mxe>
Date:   Sun Nov 29 09:50:06 2015 +0100

    Build i686-w64-mingw32.static~freetype

 i686-w64-mingw32.static/bin/freetype-config        |    2 +-
 i686-w64-mingw32.static/lib/libfreetype.a          |  Bin 3313770 -> 3331018 bytes
 i686-w64-mingw32.static/lib/libfreetype.la         |    4 ++--
 i686-w64-mingw32.static/lib/pkgconfig/freetype2.pc |    2 +-
 4 files changed, 4 insertions(+), 4 deletions(-)
```

Installing deb package `freetype` install right files (modified by `freetype`). The same files are installed when installing `freetype-bootstrap`.

I have found no such warnings about package `harfbuzz`. It is not reported to be empty.

**Comment by tonytheodore** [comment]
> Installing deb package freetype install right files (modified by freetype). The same files are installed when installing freetype-bootstrap..

Thanks, it makes sense now. I vaguely thought each package installed it's own version but now realise that's not possible without a lot of checkout complexity and it shouldn't happen anyway.

There's no easy solution to this circular dependency, `ld` has [the options](https://sourceware.org/binutils/docs/ld/Options.html#Options) `--start-group ... --end-group` to repeatedly search but these don't work with `pkgconf`.

I'll leave this open for the time being.
