### ISSUE TITLE
libxml2 fails to build for shared configuration

### ISSUE THREAD

**Issue by MrMagne** [mxe/mxe#1022]
Hello,
MXE fails to build libxml2 for target i686-w64-mingw32.shared and x86_64-w64-mingw32.shared (build works for static).
Here is the problematic part of the log
```
.libs/xmlIO.o: In function `xmlGzfileOpen_real':
/pathto/mxe/tmp-libxml2-i686-w64-mingw32.shared/libxml2-2.9.2/xmlIO.c:1167: undefined reference to `gzdopen'
.libs/xmlIO.o: In function `_xmlParserInputBufferCreateFilename':
/pathto/mxe/tmp-libxml2-i686-w64-mingw32.shared/libxml2-2.9.2/xmlIO.c:2670: undefined reference to `gzdirect'
.libs/xmlIO.o: In function `xmlZMemBuffAppend':
/pathto/mxe/tmp-libxml2-i686-w64-mingw32.shared/libxml2-2.9.2/xmlIO.c:1717: undefined reference to `deflate'
/pathto/mxe/tmp-libxml2-i686-w64-mingw32.shared/libxml2-2.9.2/xmlIO.c:1729: undefined reference to `crc32'
.libs/xmlIO.o: In function `xmlZMemBuffGetContent':
/pathto/mxe/tmp-libxml2-i686-w64-mingw32.shared/libxml2-2.9.2/xmlIO.c:1758: undefined reference to `deflate'
.libs/xmlIO.o:xmlIO.c:(.data+0x4): undefined reference to `gzopen'
.libs/nanohttp.o: In function `xmlNanoHTTPFreeCtxt':
/pathto/mxe/tmp-libxml2-i686-w64-mingw32.shared/libxml2-2.9.2/nanohttp.c:432: undefined reference to `inflateEnd'
.libs/nanohttp.o: In function `xmlNanoHTTPRead':
/pathto/mxe/tmp-libxml2-i686-w64-mingw32.shared/libxml2-2.9.2/nanohttp.c:1292: undefined reference to `inflate'
.libs/nanohttp.o: In function `xmlNanoHTTPScanAnswer':
/pathto/mxe/tmp-libxml2-i686-w64-mingw32.shared/libxml2-2.9.2/nanohttp.c:829: undefined reference to `inflateInit2_'

**Comment by tonytheodore** [comment]
Could you make a gist of the full log? It could be missing a zlib dependency.

**Comment by MrMagne** [comment]
Here it is, it seems to properly find zlib.
https://gist.github.com/MrMagne/7bb72dc644a417f22117
Does libxml2 build works for you in shared configuration ?

**Comment by tonytheodore** [comment]
> checking for gzread in -lz... no

I'm guessing that's the culprit, https://github.com/mxe/mxe/commit/068e20243d2b531c032f04fcff07bd613594d9ce should fix it. Or just run `make zlib` this time to continue your build.

> Does libxml2 build works for you in shared configuration ?

Yes, though I don't build it directly, so `zlib` is usually built first.

**Comment by MrMagne** [comment]
Still not working, log still says
> checking for gzread in -lz... no

**Comment by tonytheodore** [comment]
Strange, it's working here with or without `zlib`.

There should be a file:
```
/pathto/mxe/tmp-libxml2-i686-w64-mingw32.shared/libxml2-2.9.2/config.log
```
Can you post that also? I'm not sure why it isn't in the normal log.

**Comment by MrMagne** [comment]
I made some other tests and that file has been overwritten.
The problem seems to be in the configure.ac script, line 395. They add a -L/lib on the command line of the compilation command to test the presence of gzread. When reproducing that test manually I get the same link error, but it works fine if I remove the -L/lib arg. I tried a patch to remove this line but then it fails with recipe for target 'aclocal.m4'... still investigating...

Here is the patch:
```
diff --git a/configure.ac b/configure.ac
index 14ac0a8..8d3b173 100644
--- a/configure.ac
+++ b/configure.ac
@@ -392,7 +392,6 @@ if test "$with_zlib" = "no"; then
 else
     AC_CHECK_HEADERS(zlib.h,
         [SAVE_LDFLAGS="${LDFLAGS}"
-	 LDFLAGS="-L${Z_DIR}/lib"
 	AC_CHECK_LIB(z, gzread,[
 	    AC_DEFINE([HAVE_LIBZ], [1], [Have compression library])
 	    WITH_ZLIB=1

**Comment by tonytheodore** [comment]
We don't really want to `autoreconf` for such a change, if you can regenerate the `config.log` it would be helpful.

Also, check the values of `LD_LIBRARY_PATH` and `ACLOCAL_PATH` - these can be problematic.

**Comment by MrMagne** [comment]
I didn't provide the patch to integrate it, just to share what I was testing :)
I managed to build not using the previous patch but adding an argument to the configure command in the makefile (build is OK for the 4 configurations).
```
diff --git a/src/libxml2.mk b/src/libxml2.mk
index 14a4dc9..47408af 100644
--- a/src/libxml2.mk
+++ b/src/libxml2.mk
@@ -22,6 +22,7 @@ define $(PKG)_BUILD
     $(SED) -i 's,`uname`,MinGW,g' '$(1)/xml2-config.in'
     cd '$(1)' && ./configure \
         $(MXE_CONFIGURE_OPTS) \
+        --with-zlib='$(PREFIX)/$(TARGET)/lib' \
         --without-debug \
         --without-python \
         --without-threads

**Comment by tonytheodore** [comment]
Perfect, thanks! https://github.com/mxe/mxe/commit/c0b12c17f894a4596db450c562c2968191917bc9

**Comment by MrMagne** [comment]
...and realizing it is probably not the right path for zlib, because they add a trailing '/lib' to it. I guess the problem was with an empty path it was using /lib which is a symplink to /usr/lib on archlinux, and thus contains a libz.a and libz.so that was probably confusing the linker. If the path is wrong, the linker uses the standard path and finds the right zlib...
Correct solution might be `--with-zlib='$(PREFIX)/$(TARGET)'` but both are working :)
