### ISSUE TITLE
build-pkg: not recognized library

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1041]
```
[build-pkg] File usr/i686-w64-mingw32.static/lib/libruntimeobject.a (i686-w64-mingw32.static~gcc): not recognized library
```

This file is an [implicit linker script](https://sourceware.org/binutils/docs/ld/Implicit-Linker-Scripts.html#Implicit-Linker-Scripts), just a text file that `ld` can interpret:

```
$ cat usr/i686-w64-mingw32.static/lib/libruntimeobject.a
INPUT(libapi-ms-win-core-winrt-string-l1-1-0.a)
INPUT(libapi-ms-win-core-winrt-l1-1-0.a)
```

This specific file is probably not relevant (references to `winrt`) but should `build-pkg` try to detect these generally or maybe have a whitelist?

**Comment by starius** [comment]
Can we use the following rule for the whitelist:
  * name matches `*.a` and
  * `file` produces "ASCII text"

?

**Comment by tonytheodore** [comment]
Maybe a manual whitelist would be better? There are cases like `QtBootstrap.a` that are possibly required for native tools like `qmake` (and are effectively cross-target specific). Some of the `nsis` components may fall into this also.

Don't spend time on it yet, it may be these can be configured away.
