### ISSUE TITLE
Providing hosting for the public GitHub mirror 

### ISSUE THREAD

**Issue by TimothyGu** [mxe/mxe#1047]
Hi all,

[Some of our packages](http://sprunge.us/CcPD) use the service provided by @mirror for a stable, GitHub mirror. Unfortunately, recently their service has stopped: mirror/mirror#18. In that ticket I have already offered to mirror all but the 10 largest repos on my personal capacity. However, because @mirror has been very important to us and we have a DigitalOcean VPS that is pretty much idling, I think it might be a good idea for us to provide mirrors for at least some of the repos.

Currently, our server has 32G available:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        40G  5.5G   32G  15% /
```

According to @mirror maintainer, the total storage needed for all the repos is about 34GB.

If we don't count the single largest repo dd-wrt, then the total is at most 23GB.

If we don't count the two largest repos dd-wrt and cygwin, then the total is at most 17GB.

This server is funded by @tonytheodore and originally dedicated for mirroring the source packages, which is quite wasteful of the 2 CPUs and 2GB of RAM. I used to test MXE on that server also, but since my hiatus I have not done any testing on it. Plus, a full MXE installation probably should not take that much anyway.

What do you guys think?

**Comment by tonytheodore** [comment]
Thanks for looking into this, it's a very useful service and we'd like to keep it going.

I've resized the machine so it's now got 52GB available and we should be able to mirror the lot and run single target builds.

It may also pay to do a periodic sweep for projects that already have github mirrors:
https://github.com/LibreOffice/core
https://github.com/apache/openoffice
https://github.com/qtproject/qt
https://github.com/boostorg/boost

I wonder if some script could search the api and identify potential matches?

**Comment by TimothyGu** [comment]
> I wonder if some script could search the api and identify potential matches?

The most difficult part of this isn't finding potential matches, but rather finding "official" matches. The ones you listed are all quite official-looking, but when looking at something like libdvdnav with many forks & tarball-dump "repos" on GitHub, the experience is quite painful. And that's why I usually tend to prefer mirror/* since they can be guaranteed to be a mirror of the official repository.

**Comment by tonytheodore** [comment]
Good point! Even https://github.com/LibreOffice doesn't appear to be an official mirror on closer inspection.

**Comment by starius** [comment]
Does mirroring mean just a HTTP-server with tarballs? I have enough free space on my servers (redjohn.tk, elric.ga) and can give someone write access to host all projects.

**Comment by tonytheodore** [comment]
This isn't for tarballs per-se, the mirror does [repository clones](https://github.com/mirror/mirror/blob/master/mirror.sh) and pushes them to GitHub. The main reason we use this is to get repeatable checksums for repo downloads.

**Comment by starius** [comment]
Why does it need disk space? It can clone and push a repo, then delete it.

**Comment by tonytheodore** [comment]
Then you'd use ~2TB in bandwidth a month if you did it once a day.

**Comment by starius** [comment]
You can save some bandwidth by `git clone --depth 1 github && git pull upstread && git push github`.

**Comment by tonytheodore** [comment]
Yes, but then it wouldn't have the commit that a package may be using and have to fall back to the cdn. 

Also have to consider that other people have their own reasons for using it, avoiding cvs/svn or using the api may be some but I don't really know.

**Comment by tonytheodore** [comment]
Sorry, misread the commands - the commits would still be on the remote so that would be a good way to save space and bandwidth.

**Comment by TimothyGu** [comment]
@starius some repos use SVN and/or CVS whose bridges to Git need the full repo for metadata.

I already have access to the server for more than a year so no thanks :)

**Comment by tonytheodore** [comment]
For reference, keys are here: `https://github.com/<user>.keys` or `https://api.github.com/users/<user>/keys`

Should we call the digital ocean server `mirror.mxe.cc`?

**Comment by TimothyGu** [comment]
Server has been set up to mirror most of the repos now. Backup Git packs are available at http://mirror.mxe.cc/.

**Comment by tonytheodore** [comment]
Thanks @TimothyGu, this seems to be working nicely for the past few months.
