### ISSUE TITLE
miniupnpc.mk: missing header bsdqueue.h

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1051]
mxe/usr/i686-w64-mingw32.shared/include/miniupnpc/upnpreplyparse.h:12:22: fatal error: bsdqueue.h: No such file or directory

**Comment by starius** [comment]
They code of the header is as follows:

```c
// usr/i686-w64-mingw32.shared/include/miniupnpc/upnpreplyparse.h
#if defined(NO_SYS_QUEUE_H) || defined(_WIN32) || defined(__HAIKU__)
#include "bsdqueue.h"
#else
#include <sys/queue.h>
#endif
```

Can you provide a code sample and a compilation command, please?

**Comment by pavelvat** [comment]
>Can you provide a code sample and a compilation command, please?

Just line:
```
 #include <miniupnpc/upnpcommands.h> 
```

bsdqueue.h is present in miniupnpc-1.9.tar.gz tarball.

**Comment by starius** [comment]
bsdqueue.h was installed in [the commit](https://github.com/mxe/mxe/commit/7696a567bf17c9c35cf162cef5905eadc99c9083#diff-dc8b3ccacb32256bdd48c52e856390f1R35):
```diff
+# We can build the whole package, but only make libminiupnpc.a. Rest makes little sense.
+define $(PKG)_BUILD
+    cd '$(1)' && $(SH) ./updateminiupnpcstrings.sh
+    $(MAKE) -C '$(1)' -f Makefile.mingw -j '$(JOBS)' \
+        CC='$(TARGET)-gcc' \
+        AR='$(TARGET)-ar' \
+        RANLIB='$(TARGET)-ranlib' \
+        DLLWRAP='$(TARGET)-dllwrap' \
+        init libminiupnpc.a miniupnpc.dll
+    $(INSTALL) -d '$(PREFIX)/$(TARGET)/lib'
+    $(INSTALL) -m644 '$(1)/libminiupnpc.a' '$(PREFIX)/$(TARGET)/lib/'
+    $(INSTALL) -m644 '$(1)/miniupnpc.lib' '$(PREFIX)/$(TARGET)/lib/'
+    $(INSTALL) -d '$(PREFIX)/$(TARGET)/bin'
+    $(INSTALL) -m755 '$(1)/miniupnpc.dll' '$(PREFIX)/$(TARGET)/bin/'
+    $(INSTALL) -d '$(PREFIX)/$(TARGET)/include'
+    $(INSTALL) -d '$(PREFIX)/$(TARGET)/include/miniupnpc'
+    $(INSTALL) -m644 '$(1)/bsdqueue.h' '$(PREFIX)/$(TARGET)/include/'
+    $(INSTALL) -m644 '$(1)/declspec.h' '$(PREFIX)/$(TARGET)/include/miniupnpc/'
+    $(INSTALL) -m644 '$(1)/igd_desc_parse.h' '$(PREFIX)/$(TARGET)/include/miniupnpc/'
+    $(INSTALL) -m644 '$(1)/miniupnpc.h' '$(PREFIX)/$(TARGET)/include/miniupnpc/'
+    $(INSTALL) -m644 '$(1)/miniupnpctypes.h' '$(PREFIX)/$(TARGET)/include/miniupnpc/'
+    $(INSTALL) -m644 '$(1)/miniwget.h' '$(PREFIX)/$(TARGET)/include/miniupnpc/'
+    $(INSTALL) -m644 '$(1)/portlistingparse.h' '$(PREFIX)/$(TARGET)/include/miniupnpc/'
+    $(INSTALL) -m644 '$(1)/upnpcommands.h' '$(PREFIX)/$(TARGET)/include/miniupnpc/'
+    $(INSTALL) -m644 '$(1)/upnperrors.h' '$(PREFIX)/$(TARGET)/include/miniupnpc/'
+    $(INSTALL) -m644 '$(1)/upnpreplyparse.h' '$(PREFIX)/$(TARGET)/include/miniupnpc/'
+endef
```

But it was lost in [the subsequent commit](https://github.com/mxe/mxe/commit/eb20723302ed656122ce326129c1347e03b0460d) (switch to cmake).

`CMakeLists.txt` installs the following headers:
```cmake
install (FILES
  miniupnpc.h
  miniwget.h
  upnpcommands.h
  igd_desc_parse.h
  upnpreplyparse.h
  upnperrors.h
  declspec.h
  DESTINATION include/miniupnpc
)
```

Some headers used to be installed manually in [the initial commit](https://github.com/mxe/mxe/commit/7696a567bf17c9c35cf162cef5905eadc99c9083) are not installed by cmake:

  * bsdqueue.h
  * miniupnpctypes.h
  * portlistingparse.h

By the way there are also 6 header files not installed even in the initial commit:

  * codelength.h
  * minisoap.h
  * connecthostport.h
  * minissdpc.h
  * minixml.h
  * receivedata.h

We should do the following:

  * remove file `src/miniupnpc-build-1.patch` which is not used anymore
  * add 3 (or 9) files listed above to `CMakeLists.txt`
  * report this problem to upstream

**Comment by BioMike** [comment]
I was the person that did the initial commit for this package. I'm not sure why the cmake build was added to this package, because I thought it was too experimental for this version. The 2 headers (miniupnpctypes.h and portlistingparse.h) are installed in the current miniupnpc github HEAD, bsdqueue.h is not more needed and removed in commit https://github.com/miniupnp/miniupnp/commit/a80c87fb8dc926635f634d64c255e5244497b551 . As for the 6 other header files, I think they are only needed at build time of miniupnpc and should not be used in your project.

**Comment by starius** [comment]
> Updating to the latest non-release version should solve this issue.

I would prefer not to use non-release version if it is possible.

I have removed unused patch miniupnpc-build-1.patch and added a patch adding bsdqueue.h, miniupnpctypes.h and portlistingparse.h to installation list of CMake. I am building it now, then I am going to check compilation of ` #include <miniupnpc/upnpcommands.h>` and make a pull request.
