### ISSUE TITLE
Native lua depends on readline

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1060]
Either add to requirements or enable the native build for the readline/termcap packages.

**Comment by starius** [comment]
Or disable readline. We can comment out `#define LUA_USE_READLINE` in file [luaconf.h](http://www.lua.org/source/5.3/luaconf.h.html) or build lua with `make generic` instread of `make linux` / `make macosx`.

**Comment by starius** [comment]
We can't use generic lua as native lua, as it lacks io.popen which is needed for luarocks.
