### ISSUE TITLE
patch-tool-mxe doesn't work with plugins

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1063]
```
$ MXE_PLUGIN_DIRS=plugins/apps/ ./tools/patch-tool-mxe init tor             
grep: /home/mxe/mxe/src/tor.mk: No such file or directory
grep: /home/mxe/mxe/src/tor.mk: No such file or directory
grep: /home/mxe/mxe/src/tor.mk: No such file or directory
Error: /home/mxe/mxe/gits/ already exists. Cancelling init.
```

**Comment by tonytheodore** [comment]
It also won't work with the standardisation of GitHub packages (next iteration of #1002) as that removes the elements `grep` searches.

It's probably time to switch this over to `make` targets - are you working on that or do you want me to look at it?

**Comment by starius** [comment]
I started to work at Makefile based tool and its unfinished version can be found here (the file was saved from the /tmp !): https://gist.github.com/starius/6c9fd3453754725d1cd2

Then I switched to `patch-tool-mxe` and abandoned that work. After #1016, `patch-tool-mxe` is almost ideal.

Nevertheless I would prefer the Makefile based tool.

**Comment by starius** [comment]
It also doesn't work with calculated version, e.g. for `freeimage`:
```
$(PKG)_FILE     := FreeImage$(subst .,,$($(PKG)_VERSION)).zip
```

```
$ ./tools/patch-tool-mxe init freeimage
Checking for cached FreeImage$(subst .,,3.15.4).zip
./tools/patch-tool-mxe: line 57: [: /mxe/pkg/FreeImage$(subst: binary operator expected
Unpacking archive...
unzip:  cannot find or open /mxe/pkg/FreeImage$(subst, /mxe/pkg/FreeImage$(subst.zip or /mxe/pkg/FreeImage$(subst.ZIP.
Initializing repo and adding all as first commit
./tools/patch-tool-mxe: line 76: cd: /mxe/gits/FreeImage: No such file or directory
Creating 'dist' tag for distribution tarball state
fatal: tag 'dist' already exists
Repository ready in /mxe/gits/FreeImage
```
