### ISSUE TITLE
MXE produce wrong executables for EiskaltDC++ in some cases

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1065]
Build rules:
1)in MXE(for i686-w64-mingw32.shared and x86_64-w64-mingw32.shared): ```make zlib bzip2 libiconv gettext openssl pcre boost qt5```
2)git clone https://github.com/eiskaltdcpp/eiskaltdcpp.git
3)create files in build directory:
variables.sh - https://gist.github.com/pavelvat/009e52249a41133ad720
install.sh - https://gist.github.com/pavelvat/87153221bd2463023007
configure.sh - https://gist.github.com/pavelvat/1af9cf37d529bf41d87e
4)edit variables BUILD_TYPE, GCC_VARIANT, MXE_DIR, SOURCES_DIR in file variables.sh.
5)run ./configure.sh
6)run make -j4
7)run ./install.sh

Program tested on Windows 7 (64-bit) and Windows XP.

```
MXE GCC 4.9:
i686-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Release):
Windows XP: program successfully run, program successfully exit.
Windows  7: program successfully run, program successfully exit.

i686-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Debug):
Windows XP: program successfully run, program successfully exit.
Windows  7: program successfully run, program successfully exit.

x86_64-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Release):
Windows  7: crashes on launch (appear process WerFault.exe in taskmgr.exe and process eiskaltdcpp-qt.exe dissapear after 5 seconds).

x86_64-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Debug):
Windows  7: crashes on launch (appear process WerFault.exe in taskmgr.exe and process eiskaltdcpp-qt.exe dissapear after 5 seconds).



MXE GCC 5.2:
i686-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Release):
Windows XP: program successfully run, program successfully exit.
Windows  7: crashes on launch (appear process WerFault.exe in taskmgr.exe and process eiskaltdcpp-qt.exe dissapear after 5 seconds).

i686-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Debug):
Windows XP: program successfully run, program successfully exit.
Windows  7: program successfully run, program successfully exit.

x86_64-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Release):
Windows  7: program successfully run, program successfully exit.

x86_64-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Debug):
Windows  7: crashes on launch (appear process WerFault.exe in taskmgr.exe and process eiskaltdcpp-qt.exe dissapear after 5 seconds).
```

So MXE GCC 4.9 produce wrong executables for EiskaltDC++ 64 bit, MXE GCC 5.2 produce wrong executables for EiskaltDC++ 32-bit.
Problem with wrong executables for EiskaltDC++ 64-bit is very old (also present for MXE GCC 4.* in 2014 year)

**Comment by starius** [comment]
Maybe there are bugs in GCC (like [this one](https://github.com/mxe/mxe/issues/964)).
GCC 4.9 is also not ideal.

Does it work under `wine`? Can you run it under a debugger or valgrind?

For #964 I used a binary search + `printf` to find that bug in my program (actually in gcc). Add `printf("test\n");` in the beginning of `main`, compile, run. Check `test` in console output. Depending on the result add new `printf` below or above. And so on. I found that bug in 5 or 6 steps. Then try to remove all code which doesn't affect the bug to create a minimal bug example.

**Comment by pavelvat** [comment]
>Maybe there are bugs in GCC

Maybe...

>Does it work under wine?

All above variants builds of EiskaltDC++ is working fine in wine, so wine is absolutely useless for testing for this reason.

>Can you run it under a debugger or valgrind?

Yes. But bug in MXE (some variants above builds of EiskaltDC++ works fine).

>Can you build it statically?

Staticaly builds has the same problems.

>Add printf("test\n"); in the beginning of main, compile, run. Check test in console output. Depending on the result add new printf below or above.

This bug in MXE, not in EiskaltDC++.

**Comment by starius** [comment]
>> Can you run it under a debugger or valgrind?

> Yes. But bug in MXE

I mean running exe file produced by MXE under a debugger to locate lines of code causing a crash.

>  (some variants above builds of EiskaltDC++ works fine).

It still doesn't mean that the bug is caused by MXE not by EiskaltDC++. For example, the following code (not from EiskaltDC++) works pretty fine in release mode and crashes in debug mode:

```c
assert(0);
```

> This bug in MXE, not in EiskaltDC++.

It can be a bug in EiskaltDC++ which is suppressed in other compilers / toolchains. Or two bugs in both MXE and EiskaltDC++. Or in gcc.

**Anyway to fix this bug we have to narrow the search to a particular lines of code using a debugger or binary search**.

**Comment by pavelvat** [comment]
I have tested all crashes builds above on GDB from http://sourceforge.net/projects/mingw-w64/ (32-bit and 64-bit).

direct link to installer:
http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download

In result, all builds "MXE GCC 4.9" of EiskaltDC++ is working fine under GDB. The build "MXE GCC 5.2 i686-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Release)" crashes under GDB with "no stack": https://gist.github.com/pavelvat/0ef87ccd4da66b34aa70 
The build "MXE GCC 5.2 x86_64-w64-mingw32.shared (-DCMAKE_BUILD_TYPE=Debug)" crashes with backtrace: https://gist.github.com/pavelvat/bf4963f4470b0f1ad4fb

**Comment by starius** [comment]
The backtrace is a good starting point. Can you isolate this error? Please, create a small crashing program calling `dcpp::getDownloadsPath` or `dcpp::Text::fromT`.

**Comment by pavelvat** [comment]
This is a bug of EiskaltDC ++: in function getDownloadsPath occur incorrect converting text (garbage instead of download path) and this leads in some cases to crash. Very strange that builds of EiskaltDC++ produce with MXE GCC 4.9 is working fine under GDB and crashes without GDB.

**Comment by starius** [comment]
> Very strange that builds of EiskaltDC++ produce with MXE GCC 4.9 is working fine under GDB and crashes without GDB.

gdb and other debugging tools often change what "undefined behaviour" is resolved to.

**Comment by UniqueFool** [comment]
I am also currently trying to build some libs for mxe, and while the build succeeds, I am seeing segfaults at run-time (that don't show up otherwise), and I was hoping that we could at some kind of library to more easily dump/obtain a backtrace to see if the problem is compiler/code generation related or not.
Any ideas ?
