### ISSUE TITLE
inaccuracy in description README.md

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1066]
https://github.com/mxe/mxe/blob/master/README.md

```
Host Triplet:
    i686-w64-mingw32
    x86_64-w64-mingw32
```

>Triplet

**Comment by starius** [comment]
Please, can you explain in more details what is wrong with it?

**Comment by pavelvat** [comment]
triplet - three, not two.

**Comment by starius** [comment]
>  Autoconf-generated configure scripts can make decisions based on a canonical name for the system type, or target *triplet*, which has the form: ‘cpu-vendor-os’, where os can be ‘system’ or ‘kernel-system’

https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Specifying-Target-Triplets.html

By the way it should replaced with "Host Triplet**s**"

**Comment by tonytheodore** [comment]
Should we also note the threading variants or wait till they are more stable?

**Comment by starius** [comment]
> Should we also note the threading variants or wait till they are more stable?

+1 for noting the threading variants

**Comment by tonytheodore** [comment]
Is #1073 sufficient?

**Comment by pavelvat** [comment]
>Is #1073 sufficient?

Yes.

**Comment by tonytheodore** [comment]
Cool! I'll describe the threading variants in greater detail when we do the exception handling variants.
