### ISSUE TITLE
armadillo download URL does not work

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1075]
```
$ wget http://downloads.sourceforge.net/project/arma/armadillo-4.550.1.tar.gz
--2015-12-16 11:48:38--  http://downloads.sourceforge.net/project/arma/armadillo-4.550.1.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-16 11:48:39 ERROR 404: Not Found.
```

Version 4.550.1 seems to be removed from sourceforge and from [the official armadillo website](http://arma.sourceforge.net/download.html).

Maybe it is time for update?

**Comment by tonytheodore** [comment]
Updates are the next chunk of work after getting all broken packages fixed. In the same way it's easier to keep everything building (and add new features) when it's already building - it's easier to keep everything updated when it's already up-to-date.

If we can chip away the the ones that don't have a lot of downstream deps:

```
$ make show-deps-armadillo
armadillo upstream dependencies:
 pkgconf binutils mingw-w64 gcc blas bzip2 expat zlib boost cblas lapack

armadillo downstream dependents:
 gdal openscenegraph
```
it would be great.

**Comment by starius** [comment]
I don't understand you thoughts about armadillo. Can you explain the idea?

**Comment by tonytheodore** [comment]
It's roundabout way of saying - yes, it's always time for an update ;)
