### ISSUE TITLE
agg download URL and agg web-site are down

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1077]
```
--2015-12-16 19:53:05--  http://www.antigrain.com/agg-2.5.tar.gz
Resolving www.antigrain.com (www.antigrain.com)... 74.208.58.200
Connecting to www.antigrain.com (www.antigrain.com)|74.208.58.200|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-16 19:53:06 ERROR 404: Not Found.
```
http://antigrain.com/

**Comment by TimothyGu** [comment]
See also https://github.com/mxe/mxe/issues/386#issuecomment-58490336

**Comment by starius** [comment]
I have sent a notification to the author of agg, Maxim Shemanarev.

**Comment by TimothyGu** [comment]
@starius seems like he passed away two years ago: https://rsdn.ru/forum/life/5377743.flat

**Comment by starius** [comment]
RIP.

We should find a person who [fixed](https://github.com/mxe/mxe/issues/386#issuecomment-58490336) the site in 2014 and ask him/her to do it again.

**Comment by starius** [comment]
I have [emailed](http://sourceforge.net/p/vector-agg/mailman/vector-agg-general/thread/CAFC_Vt7zePVmcbuyr-7XA5XQq4wdjb2kyjFAxRRno_a4K4QE-w%40mail.gmail.com/#msg34712257) to agg maillist.
