### ISSUE TITLE
Use YYYY-MM-DD (or YYYYMMDD) date format in directory names

### ISSUE THREAD

**Issue by vog** [mxe/mxe#1086]
For naming files and directories, we should follow the international date format YYYY-MM-DD (or maybe the shorter variant YYYYMMDD), as that means these are sorted chronologically out of the box.

I'm not sure which parts of MXE do have this issue, but I just noticed the chaotic order of folders in:

http://pkg.mxe.cc/releases/

    repos-12Dec2015/
    repos-15Dec2015/
    repos-16Dec2015/
    repos-28Aug2015/

Using the international date format, these would appear as:

    repos_2015-08-28/
    repos_2015-12-12/
    repos_2015-12-15/
    repos_2015-12-16/

Or maybe even shorter:

    2015-08-28/
    2015-12-12/
    2015-12-15/
    2015-12-16/

**Comment by starius** [comment]
This names were given manually. I renamed these directories on the server to
```
2015-08-28/
2015-12-12/
2015-12-15/
2015-12-16/
```
See http://pkg.mxe.cc/releases/

The following URL still works as it was [mentioned](http://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-12/msg00013.html) in the mailing list:
http://pkg.mxe.cc/releases/repos-16Dec2015/
It is a mirror of http://pkg.mxe.cc/releases/2015-12-16/
