### ISSUE TITLE
Add gist command line tool to requirements?

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1088]
From https://github.com/mxe/mxe/pull/1081#issuecomment-165923060, I wonder if we should add:

https://github.com/defunkt/gist

to the requirements and add a note to any error messages to encourage people to post full logs in the first case.

**Comment by starius** [comment]
IMHO, we must **not** upload any logs automatically to respect user's privacy. MXE works without uploading anything to external servers (e.g., Gist servers). So this tool is not a requirement of MXE.

Although we can simplify logs uploading by printing information about `gist` tool and the uploading command (like `gist -d "MXE command 'make yyy', commit xxx" log/foo.log`) in the error message.
