### ISSUE TITLE
use lzma in opencv

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1092]
`opencv` has optional dependency `lzma`. We already have [the patch](https://github.com/mxe/mxe/blob/c26f3225fba8ffe9dd54db759d4680a1314d350f/src/opencv-1-fixes.patch#L85) finding `lzma`, but `lzma` is not a dependency of `opencv` and is not found ([log](https://gist.github.com/starius/02441864e60453c4b6ff#file-opencv_i686-w64-mingw32-static-L786)).

By the way, can we fix CMake warnings about CMP0045?

**Comment by tonytheodore** [comment]
> By the way, can we fix CMake warnings about CMP0045?

If [setting it in the toolchain file is sufficient](https://github.com/mxe/mxe/issues/971), then yes. I haven't tested it yet. I'll probably bump the native cmake version to the latest (after fixing some known breakages) so we can double-down on such things.

**Comment by tonytheodore** [comment]
liblzma is actually installed by xz (https://github.com/mxe/mxe/issues/1481) and has since been added to opencv deps.

CMake warning policies are set in `/src/cmake/conf/target-cmake.in`.
