### ISSUE TITLE
add git commit hash to logs

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1095]
Currently, the commit hash is not logged.

For example [this log](http://pkg.mxe.cc/releases/2015-12-16/log/20151216_091144/pkgconf_i686-w64-mingw32.static) was built from commit 8aa5ccc123b429c59b453b7be2fce9ef3bea678a, but I can't find this commit hash in the log.

**Comment by tonytheodore** [comment]
Something like this?
```
$ git log --pretty=format:"%h - %s [%ar] [%D]" -1
c26f322 - libass: remove obsolete --disable-enca option [2 days ago] [HEAD -> master, tonytheodore/master, origin/master, origin/gh-pages, origin/HEAD]
```

**Comment by starius** [comment]
Yes, but with %H instead of %h.
