### ISSUE TITLE
git tags for every packaging release

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1096]
Following on from https://github.com/mxe/mxe/issues/962#issuecomment-164300594 and https://github.com/mxe/mxe/issues/962#issuecomment-164300594, shall we create git tags for every packaging release?

I propose to add the following tags:
`build-2015-08-28` for d95da7e22a24ab477f29ae95f4e2573a0792a5df
`build-2015-12-16` for 8aa5ccc123b429c59b453b7be2fce9ef3bea678a

**Comment by tonytheodore** [comment]
That format looks good and will be easy to work with.

**Comment by starius** [comment]
Tags `build-2015-08-28` and `build-2015-12-16` were added: https://github.com/mxe/mxe/tags

**Comment by starius** [comment]
By the way, Travis CI failed with these two tags: https://travis-ci.org/mxe/mxe/builds/98404206
Probably we should update the push condition.
