### ISSUE TITLE
armadillo no longer requires boost?

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1102]
@ChristianFrisson, I was looking at [updating armadillo](https://github.com/tonytheodore/mxe/commit/da2aea394812792e52f65bae16940cbf96d6ccd1) and noticed that it doesn't seem to require `boost` any longer. In fact, a quick search implies they're more like [independent alternatives](http://arma.sourceforge.net/faq.html#related).

Do you still use this package? It seems we can drop the boost dependency and add `openblas` support.

**Comment by ChristianFrisson** [comment]
I still use armadillo but indirectly and outside mxe. I've contacted one of the armadillo authors for more clues about the drop of boost as dependency. openblas seems indeed to be a good third party replacement.

**Comment by ChristianFrisson** [comment]
I have received confirmation that boost is no longer needed as dependency.

**Comment by tonytheodore** [comment]
Thanks, boost has been removed but openblas needs some more thought.
