### ISSUE TITLE
small fix after boost update

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1104]
add to boost-1-fixes.patch fix for "std::sprintf" (remove the prefix "std::")
https://svn.boost.org/trac/boost/ticket/11872

**Comment by starius** [comment]
This error is caused by `usr/i686-w64-mingw32.shared/include/libintl.h` (installed by `gettext`), which contains the following code:

```
    359 #if !(defined sprintf && defined _GL_STDIO_H) /* don't override gnulib */
    360 #undef sprintf
    361 #define sprintf libintl_sprintf
    362 extern int sprintf (char *, const char *, ...);
    363 #endif
    364 #if !(defined vsprintf && defined _GL_STDIO_H) /* don't override gnulib */
    365 #undef vsprintf
    366 #define vsprintf libintl_vsprintf
    367 extern int vsprintf (char *, const char *, va_list);
    368 #endif
```

So `sprintf` is replaced with `libintl_sprintf` and `std::sprintf` is replaced with `std::libintl_sprintf`. This can result in error in any package using `std::sprintf`. I think, we should patch `gettext`, not `boost`.

**Comment by pavelvat** [comment]
Currently boost-1-fixes.patch contain my patch: https://github.com/boostorg/interprocess/pull/23 
This patch is not necessary, because BOOST_USE_WINDOWS_H not defined:
```
#ifdef BOOST_USE_WINDOWS_H
#include <windows.h>

#  if defined(BOOST_INTERPROCESS_BOOTSTAMP_IS_LASTBOOTUPTIME)
#  include <Wbemidl.h>
#  include <Objbase.h>
#  endif

#include <Shlobj.h>
#endif
```
so case sensitivity for headers is irrelevant. Previously pull https://github.com/boostorg/interprocess/pull/15 is obsolete for boost-1.60.

**Comment by starius** [comment]
@pavelvat, please create a pull request to remove patch "Fixed case sensetive for linux mingw" from src/boost-1-fixes.patch.

**Comment by pavelvat** [comment]
@starius, I do not think it should be done (next version of boost will include this patch). In any case, you can remove the patch without my pull request. This patch was needed to boost-1.57, and may be will be needed in future versions of boost.

**Comment by starius** [comment]
usr/i686-w64-mingw32.shared/include/libintl.h:

```
 84    The redirection happens by default through macros in C, so that &gettext
 85    is independent of the compilation unit, but through inline functions in
 86    C++, in order not to interfere with the name mangling of class fields or
 87    class methods called 'gettext'.  */
 88 
 89 /* The user can define _INTL_REDIRECT_INLINE or _INTL_REDIRECT_MACROS.
 90    If he doesn't, we choose the method.  A third possible method is
 91    _INTL_REDIRECT_ASM, supported only by GCC.  */
```

In C++, inline function should be used instead of a macro.

Unfortunately, inline functions option was not implemented for printf-like functions, maybe because of variable number of arguments of `printf`. Though it can be implemented with templates and overloading:

```c++
#if !(defined sprintf && defined _GL_STDIO_H) /* don't override gnulib */
# ifdef _INTL_REDIRECT_INLINE

    inline int sprintf(char *__buffer, const char *__format) {
        return libintl_sprintf(__buffer, __format);
    }

    template<typename __T1>
    inline int sprintf(char *__buffer, const char *__format,
        __T1 __value1
    ) {
        return libintl_sprintf(__buffer, __format,
            __value1);
    }

    template<typename __T1, template __T2>
    inline int sprintf(char *__buffer, const char *__format,
            __T1 __value1,
            __T1 __value2
    ) {
        return libintl_sprintf(__buffer, __format,
            __value1,
            __value2);
    }

    // TODO up to 9 values

# else
#   undef sprintf
#   define sprintf libintl_sprintf
    extern int sprintf (char *, const char *, ...);
# endif
#endif
```

If C++11 is enabled, Variadic Templates can be used instead.

What do you think about this trick?

**Comment by starius** [comment]
> I do not think it should be done (next version of boost will include this patch)

It worth removing unneeded patches ASAP to facilitate updates.

> This patch was needed to boost-1.57, and may be will be needed in future versions of boost.

IMHO, that patch is unlikely to be needed in future.

**Comment by starius** [comment]
See https://github.com/mxe/mxe/pull/1107

**Comment by pavelvat** [comment]
>What do you think about this trick?

It is not universal.

**Comment by starius** [comment]
Do you mean it would not work for a function with >= 10 arguments without C++11? `boost::bind` works in the same way without C++11. At least it works better than `#define`.

**Comment by pavelvat** [comment]
>Do you mean it would not work for a function with >= 10 arguments

yes

**Comment by starius** [comment]
Is there a better solution?

**Comment by pavelvat** [comment]
>Is there a better solution?

I don not know.

**Comment by starius** [comment]
I am not sure which workaround is worse: removing "std" from [dozens of lines](https://gist.github.com/06dea919911808baf6a2) where boost uses it with printf-like functions, or implementing dozens of overloaded functions in libintl.h.

By the way boost doesn't have gettext in its list of dependencies. It looks as an [undeclared dependency](https://github.com/mxe/mxe/issues/1111). Can you break compilation of `usr/i686-w64-mingw32.shared/include/libintl.h` to track how boost includes it, please?

**Comment by pavelvat** [comment]
>Can you break compilation of usr/i686-w64-mingw32.shared/include/libintl.h to track how boost includes it, please?

I don't understand what you want. I think that will be easier to patch boost.

**Comment by starius** [comment]
I want to understand why boost included `libintl.h` which is not its dependency.

**Comment by pavelvat** [comment]
@starius qBittorrent now also use ""std::sprintf":
https://github.com/qbittorrent/qBittorrent/commit/41fe85b6248436a1da024e1f9088f045b004acbb#diff-496371d520ec39864ce4039446fd830fR524
https://github.com/qbittorrent/qBittorrent/pull/4844

**Comment by starius** [comment]
So, we should fix it in libintl.h instead of fixing boost, qbittorrent and all other projects using libintl.h.
