### ISSUE TITLE
Problems with Archlinux

### ISSUE THREAD

**Issue by suizokukan** [mxe/mxe#1108]
# my configuration :
* an up to date Archlinux (`Linux archsuizokukan 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`)
* alure is installed (a `$pacman -Ss alure` returns `community/alure 1.2-4 [installed]`)
* a fresh installation of mxe : `git clone https://github.com/mxe/mxe`, `cd mxe`, then `make MXE_TARGETS='x86_64-w64-mingw32.static'`

# the error :
`make MXE_TARGETS='x86_64-w64-mingw32.static'` compiles a lot of stuff (mxe-conf, gcc... zlib, ...) and exits returning the following message :
> Failed to build package alure for target x86_64-w64-mingw32.static!

# the logs from log/alure_x86_64-w64-mingw32.static :
> [ 92%] Building CXX object CMakeFiles/ALURE32-static.dir/src/codec_mpg123.obj
> /home/suizokukan/mxe20151229/usr/bin/x86_64-w64-mingw32.static-g++   -DDYNLOAD=1 -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_WIN32 -DAL_LIBTYPE_STATIC -DALURE_STATIC_LIBRARY -O3 -DNDEBUG @CMakeFiles/ALURE32-static.dir/includes_CXX.rsp   -Wextra -Wall -funswitch-loops  -DALURE_STATIC_LIBRARY -o CMakeFiles/ALURE32-static.dir/src/codec_mpg123.obj -c /home/suizokukan/mxe20151229/tmp-alure-x86_64-w64-mingw32.static/alure-1.2/src/codec_mpg123.cpp
> /home/suizokukan/mxe20151229/tmp-alure-x86_64-w64-mingw32.static/alure-1.2/src/codec_mpg123.cpp:33:20: fatal error: mpg123.h: No such file or directory
> #include <mpg123.h>

Any help would be appreciated !

**Comment by starius** [comment]
1. Please upload full logs of packages `mpg123` and `alure` to [Gist](https://gist.github.com/) and post the link.
2. Please provide the output of
    * `find usr/* -name mpg123.h`
    * `find usr/* -name '*mpg123*'`

**Comment by suizokukan** [comment]
Hi, thanks for your answer.

* `$find usr/* -name mpg123.h` : no file
* `$find usr/* -name '*mpg123*'` : no file
* log of package alure (alure.x86_64-w64-mingw32.static) : https://gist.github.com/suizokukan/8d9156f830992af5a0c3: 
* there's no log for the package mpg123 : `$find log/ -name "*mpg*"` returns nothing.

**Comment by starius** [comment]
Package `mpg123` should be added to `alure`'s dependencies. Could you test my pull request #1110, please?

**Comment by suizokukan** [comment]
I tried #1110 (namely, `$(PKG)_DEPS     := gcc flac libsndfile mpg123 ogg openal vorbis` in src/alure.mk) :

mpg123 was correctly compiled but now, there's an error about a missing file, namely `fluidsynth.h` .
details here : https://gist.github.com/suizokukan/c8c02be3beefcda06bb9

Naively, I tried to fix src/alure.mk this way : `$(PKG)_DEPS     := gcc flac libsndfile mpg123 fluidsynth ogg openal vorbis` ... but I got the following error : 

> make: ***  Aucune règle pour fabriquer la cible « /home/suizokukan/mxe/usr/x86_64-w64-mingw32.static/installed/fluidsynth »
(id est : make: *** No rule to create the target /home/suizokukan/mxe/usr/x86_64-w64-mingw32.static/installed/fluidsynth)

**Comment by starius** [comment]
> Naively, I tried to fix src/alure.mk this way : $(PKG)_DEPS := gcc flac libsndfile mpg123 fluidsynth ogg openal vorbis

Members of this list are package names, not headers. You can find the list of MXE packages in file `index.html` ([mxe.cc](http://mxe.cc/) site) of in `src/*.mk` files.

The error with FluidSynth seems to be unrelated to the first one.

The error message is as follows:

```
/home/suizokukan/mxe/tmp-alure-x86_64-w64-mingw32.static/alure-1.2/src/codec_fluidsynth.cpp:36:24:
fatal error: fluidsynth.h: No such file or directory
 #include <fluidsynth.h>
                        ^
compilation terminated.
```

CMake thinks that it found fluidsynth:

```
-- checking for module 'fluidsynth>=1.1.1'
--   found fluidsynth, version 1.1.6
```

1. Do you have fluidsynth 1.1.6 installed in your host system?
2. Do you need MXE to build alure with fluidsynth support?

`alure` has the following option:

```
OPTION(FLUIDSYNTH "FluidSynth support (for MID)" ON)
```

Can we just pass `-DFLUIDSYNTH=OFF` to cmake? Could you test if it works after adding this option in `src/alure.mk`?

```diff
diff --git a/src/alure.mk b/src/alure.mk
index dec64a8..e526516 100644
--- a/src/alure.mk
+++ b/src/alure.mk
@@ -22,6 +22,7 @@ define $(PKG)_BUILD
         -DBUILD_STATIC=ON \
         -DBUILD_SHARED=OFF \
         -DBUILD_EXAMPLES=OFF \
+        -DFLUIDSYNTH=OFF \
         -DCMAKE_C_FLAGS="-DAL_LIBTYPE_STATIC -DALURE_STATIC_LIBRARY" \
         -DCMAKE_CXX_FLAGS="-DAL_LIBTYPE_STATIC -DALURE_STATIC_LIBRARY" \
         -DCMAKE_TOOLCHAIN_FILE='$(CMAKE_TOOLCHAIN_FILE)' \
```

**Comment by suizokukan** [comment]
* FluidSynth is installed on my system : `$pacman -Ss` returns : `extra/fluidsynth 1.1.6-4 [installé]`
* I don't need MXE to build alure with fluidsynth support.

I tried to build with mpg123 and without FluidSynth. Now, I get an error about the lapack library, already installed on my system (lapack 3.6.0-2 installed).
details here : https://gist.github.com/suizokukan/e5fe6e85f7af65c3b99b

**Comment by tonytheodore** [comment]
> CMake thinks that it found fluidsynth:

from the log:
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
```
this could be the same as #1023.

**Comment by starius** [comment]
@suizokukan, there was [the error with lapack](https://github.com/mxe/mxe/issues/1114), fixed in https://github.com/mxe/mxe/issues/1115
Is the problem with `lapack` fixed for you after https://github.com/mxe/mxe/issues/1115?

**Comment by suizokukan** [comment]
With the very last commit (f9d83fe44b52eefe9f2453bcdcca5feaf3d651f6, including preceding suggestions) and + `-DFLUIDSYNTH=OFF \` in src/alure.mk (see starius' suggestion above), the build is ok (including `alure` and `lapack`) ... until the `jack` package (already installed on my system : extra/jack 0.124.1-6 [installed]).

Error message : 

> Failed to build package jack for target x86_64-w64-mingw32.static!
> ------------------------------------------------------------
>   File "/home/suizokukan/mxe_zz/tmp-jack-x86_64-w64-mingw32.static/jack-1.9.10/.waf3-1.6.11-30618c54883417962c38f5d395f83584/waflib/Build.py", line 162, in store
    cPickle.dump(data,f)
> AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'

details : https://gist.github.com/suizokukan/094777b74ce33b5e008a

**Comment by starius** [comment]
@suizokukan, I have committed `-DFLUIDSYNTH=OFF` and [fixed jack](https://github.com/mxe/mxe/commit/3ecfb20f826ac6ac18d217c78c0d341b42567e55). Can you rebuild from commit 94b36dc353e4a0dc1088f25c959769e9616fd865, please?

**Comment by suizokukan** [comment]
Tried 94b36dc353e4a0dc1088f25c959769e9616fd865 : `jack` is now ok but I got the following error :

> Failed to build package aubio for target x86_64-w64-mingw32.static!
> ------------------------------------------------------------
>    except Errors.WafError ,e:
>                         ^
> SyntaxError: invalid syntax

details here : https://gist.github.com/suizokukan/035f913fbad39938598d

**Comment by starius** [comment]
Python 3 has different syntax of `except`:
```python
except Errors.WafError as e:
```
This syntax works also in Python 2.6 and Python 2.7.

I'll try to patch it.

**Comment by starius** [comment]
@suizokukan, please test pull request https://github.com/mxe/mxe/pull/1124

**Comment by suizokukan** [comment]
Tried 94b36dc353e4a0dc1088f25c959769e9616fd865 + pull request #1124 . I got the following error message :

> Failed to build package aubio for target x86_64-w64-mingw32.static!
> ------------------------------------------------------------
>  File "/home/suizokukan/mxe_z/tmp-aubio-x86_64-w64-mingw32.static/aubio-0.4.2/waflib/Utils.py", line 310, in h_list
>    m.update(str(lst))
> TypeError: Unicode-objects must be encoded before hashing

details here : https://gist.github.com/suizokukan/f471d1b9d34822cb07e1

These errors are due to the differences between Python2 and Python3 : I'm not sure about what's going on here but why don't you simply change the shebang line in .py headers ? By example, in `mxe/tmp-aubio-x86_64-w64-mingw32.static/aubio-0.4.2/waf` I read `#!/usr/bin/env python` . On my system (Archlinux), `python` will call by default a Python3 interpreter. What about a shebang line like `#!/usr/bin/env python2` to avoid this problem ?

**Comment by tonytheodore** [comment]
> What about a shebang line like #!/usr/bin/env python2 to avoid this problem ?

That would be a nice solution if we knew that `python2` was going to be present. It's there on Debian Jessie and Wheezy, but not OS X.

**Comment by starius** [comment]
`waf` is declared to be compatible with Python 2.7-3.4. I hope upgrading `aubio` to latest `waf` solve the problem.

**Comment by tonytheodore** [comment]
@suizokukan what version of python do you have? The only other package that may have issues is `nsis`.

**Comment by suizokukan** [comment]
Python 3.5.1 on my ArchLinux.

**Comment by starius** [comment]
@suizokukan, @tonytheodore I have added package `waf` and changed `aubio` and `jack` to use waf installed by this package rather than their own waf. Please test pull request https://github.com/mxe/mxe/pull/1129

**Comment by suizokukan** [comment]
Tried to build 0731545422fba26ea0c87f9f3f1f6f811413e42b + pull request #1129; everything was fine until the `aubio` package :

> Failed to build package aubio for target x86_64-w64-mingw32.static!
> ------------------------------------------------------------
> 'x86_64-w64-mingw32.static-gcc' -W -Wall -Werror -ansi -pedantic './src/aubio-test.c' -o '/home/suizokukan/mxe_z/usr/x86_64-w64-mingw32.static/bin/test-aubio.exe' `'x86_64-w64-mingw32.static-pkg-config' aubio --cflags --libs`
> /home/suizokukan/mxe_z/usr/bin/x86_64-w64-mingw32.static-ld: cannot find -ljack
> collect2: error: ld returned 1 exit status

details : https://gist.github.com/suizokukan/38167d7c7822dc95c1b8

**Comment by starius** [comment]
The reason is that `*.dll.a` files are installed to bin instead of lib. My [hotfix](https://github.com/mxe/mxe/blob/b4acd5ae7871ac84626cd4225f21130867905437/src/jack-1-fixes.patch#L120) for this was broken in the pull request. I'll investigate it tomorrow.

**Comment by TimothyGu** [comment]
@suizokukan can you paste the contents of `/home/suizokukan/mxe/usr/x86_64-w64-mingw32.static/lib/pkgconfig/aubio.pc`? [My patch](https://github.com/mxe/mxe/blob/master/src/aubio-1-fixes.patch#L143-L144) was supposed to take care of this issue.

**Comment by TimothyGu** [comment]
Furthermore, for some reason aubio is building a shared library too even though it shouldn't be… something fishy going on here. I'll take a look.

**Comment by tonytheodore** [comment]
Based on [earlier suggestion regarding shebang](https://github.com/mxe/mxe/issues/1108#issuecomment-168479394), we could simply use a `python` wrapper script that invokes:
```
python2 || python2.7 || python2.6 ...
```
It may be a better than trying to understand the intricacies of `waf`.

**Comment by suizokukan** [comment]
@tonytheodore : (/home/suizokukan/mxe/usr/x86_64-w64-mingw32.static/lib/pkgconfig/aubio.pc) https://gist.github.com/suizokukan/e08d1c25ad6582306b7f .

**Comment by suizokukan** [comment]
Sorry, I meant : 
@TimothyGu : (/home/suizokukan/mxe/usr/x86_64-w64-mingw32.static/lib/pkgconfig/aubio.pc) https://gist.github.com/suizokukan/e08d1c25ad6582306b7f .

**Comment by TimothyGu** [comment]
Please try merging #1139 as well.

**Comment by suizokukan** [comment]
989ea9ad3d642c2b928672ae24abd69e3b293e47 + #1139 failed : 
(details : https://gist.github.com/suizokukan/f4e0cb5d0be19d9a92d6)

> Traceback (most recent call last):
>   File "./waf", line 164, in <module>
>     from waflib import Scripting
>   File "/home/suizokukan/mxe/tmp-aubio-x86_64-w64-mingw32.static/aubio-0.4.2/waflib/Scripting.py", line 99
>     except Errors.WafError ,e:
>                            ^
> SyntaxError: invalid syntax

**Comment by starius** [comment]
@suizokukan, please try updated https://github.com/mxe/mxe/pull/1129 with #1139

**Comment by suizokukan** [comment]
tried cb8a7deb8fe5259b89ad2e5a986b477fa5808162 + #1129 + #1139 : 

> Failed to build package libgda for target x86_64-w64-mingw32.static!
> ------------------------------------------------------------
> Makefile:619 : la recette pour la cible « all-recursive » a échouée
> make[2]: *** [all-recursive] Erreur 1

details : https://gist.github.com/suizokukan/fc135c2bbc20667aa597

**Comment by TimothyGu** [comment]
Okay, at least aubio is working now.

**Comment by starius** [comment]
libgda error is similar to https://github.com/mxe/mxe/issues/1112
It should be fixed by the following patch: https://github.com/LuaAndC/mxe/commit/6b75550dd4f22273e87114e20c9778fb1e69d47e
@suizokukan, please try it.

Alternatively it can be fixed by updating libgda to latest version (5.2.3), but it [fails to build](https://gist.github.com/a75daed34d18fa849bac), because it has new extra dependency: itstool.

**Comment by suizokukan** [comment]
Ok, I will try 50d60a20b90c248307d27d597652e2dbd7e43381 +  #1139 + LuaAndC@6b75550 .

**Comment by suizokukan** [comment]
50d60a2 + #1139 + LuaAndC@6b75550 failed :

> Failed to build package aubio for target x86_64-w64-mingw32.static!
> ------------------------------------------------------------
>     except Errors.WafError ,e:
>                            ^
> SyntaxError: invalid syntax

details : https://gist.github.com/suizokukan/1a8bfaf99e1b5fa1f8c9

This is the same error as before (line #99 in waf/Scripting.py, see above); this error should be fixed by #1129 (see Starius' message above : "please try updated #1129 with #1139"). 50d60a2 included #1129 and I added #1139 : I don't understand what's going on but I didn't check the patches/fixes' details.

I'm trying 50d60a2 + LuaAndC@6b75550 (without #1139)... still processing but aubio is ok.

**Comment by starius** [comment]
The error is in file "/home/suizokukan/mxe/tmp-aubio-x86_64-w64-mingw32.static/aubio-0.4.2/waflib/Scripting.py" which [should be removed](https://github.com/mxe/mxe/pull/1129/files#diff-46d8d522c7b88f53cad02bf038404415R20) by https://github.com/mxe/mxe/pull/1129

**Comment by starius** [comment]
@TimothyGu, #1139 seems to break aubio.

**Comment by starius** [comment]
@suizokukan, you can rename this issue to something more general like "Problems on ArchLinux".

**Comment by TimothyGu** [comment]
@starius logs available?

**Comment by starius** [comment]
@TimothyGu, https://github.com/mxe/mxe/issues/1108#issuecomment-169802058

**Comment by tonytheodore** [comment]
Probably better to close this and continue with more appropriate `python3/waf` and `newer perl` issues.

**Comment by suizokukan** [comment]
@tonytheodore : ok, let's close this thread.
