### ISSUE TITLE
Any CI recommendations?

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1142]
I've got some machines sitting idle and would like to set up some continuous build system, most likely [buildbot](http://buildbot.net/) at the moment (but that's entirely based on liking the name and being written in python).

Any recommendations or preferences?

**Comment by starius** [comment]
I have no experience with setting up CI locally, but I like Travis-like systems as a user. Travis CI is opensource.

Comparison of opensource CI systems:
https://opensource.com/business/15/7/six-continuous-integration-tools

There is an article about setting up Travis-like CI locally using docker: http://phptest.club/t/roboci-run-travisci-builds-locally/170

**Comment by TimothyGu** [comment]
I like Travis as well, but it might be a bit overkill for what we need. buildbot sounds like a solid solution and I know that a lot of high-profile projects use it.

**Comment by tonytheodore** [comment]
Thanks, I didn't realise Travis was open source, though there's a fair amount of overhead to getting started.

I stumbled across [GitLab CI](https://about.gitlab.com/gitlab-ci/) which looks pretty interesting.

**Comment by UniqueFool** [comment]
Jenkins

**Comment by tonytheodore** [comment]
#1238 and #1392 look promising. It's better to find ways of working within resource constraints.
