### ISSUE TITLE
commit b4decd3: incorrect linking with libaspell-15.dll

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1143]
after b4decd3 on launch application EiskaltDC++ has error: https://github.com/mxe/mxe/pull/1127#issuecomment-169441880 file is missing libdl.dll.a
Build of EiskalDC++ with -DUSE_ASPELL=OFF is working fine.

**Comment by TimothyGu** [comment]
Huh, libdl.dll.a doesn't contain anything important; it only contains the entry points to the real library, which is libdl.dll.

**Comment by pavelvat** [comment]
>Are you building static or shared target?

shared

**Comment by starius** [comment]
I thought, *.dll.a are needed at build time and *.dll at run time. How can the application complain about *.dll.a at run time?

**Comment by pavelvat** [comment]
>I thought, *.dll.a are needed at build time and *.dll at run time.

It is right.

>How can the application complain about *.dll.a at run time?

Yes, it is very strange. I am copying libdl.dll.a to execution directory and Windows say that libdl.dll.a is not correct dll file.

**Comment by starius** [comment]
> Windows say that libdl.dll.a is not correct dll file.

Indeed, libdl.dll.a is not correct dll file.

Have you tried to copy libdl.dll instead of libdl.dll.a?

**Comment by pavelvat** [comment]
>Have you tried to copy libdl.dll instead of libdl.dll.a?

Of course. But libdl.dll is not required.

**Comment by pavelvat** [comment]
I can't reproduce this bug on Debian Sid and clean build MXE.
Now for target i686-w64-mingw32.shared occur SIGSEGV on exit from program:
http://pastebin.com/cwTKYrXk
For build with -DUSE_ASPELL=OFF don't occur SIGSEGV on exit from program.

**Comment by pavelvat** [comment]
I reproduce this bug for target i686-w64-mingw32.shared on clean installation of Ubuntu 14.04 and clean build of MXE.

**Comment by starius** [comment]
> Now for target i686-w64-mingw32.shared occur SIGSEGV on exit from program:

It may be a bug in the software. Have you run it under Valgrind (maybe in Linux, if there are problems in Windows)?

> I reproduce this bug for target i686-w64-mingw32.shared on clean installation of Ubuntu 14.04 and clean build of MXE.

Are you speaking about dynamic linking error or SIGSEGV?

**Comment by pavelvat** [comment]
>Are you speaking about dynamic linking error or SIGSEGV?

about dynamic linking. 

copydlldeps.py output:
```
Missing dll files: mpr.dll, crypt32.dll, opengl32.dll, iphlpapi.dll, winmm.dll, gdi32.dll, dnsapi.dll, advapi32.dll, kernel32.dll, msvcrt.dll, libdl.dll.a, shell32.dll, ole32.dll, ws2_32.dll, user32.dll
```

**Comment by tonytheodore** [comment]
I can reproduce the missing `libdl.dll.a` by trying to run the installed `aspell.exe`.

**Comment by pavelvat** [comment]
The package mingw-w64-aspell from MINGW-packages has much more patches:
https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-aspell

**Comment by tonytheodore** [comment]
They appear to be the same as: https://aur.archlinux.org/cgit/aur.git/tree/?h=mingw-w64-aspell and only the `-no-undefined` fixes the the missing `libdl.dll.a` (same can be achieved without a patch using `LDFLAGS`).

The `SIGSEGV` is caused by `pthreads` detection which can be forcibly disabled.

Should we add the other patches or wait to see if they're relevant?

**Comment by tonytheodore** [comment]
> Should we add the other patches or wait to see if they're relevant?

Added in #1210.
