### ISSUE TITLE
Failed linking to boost on i686 using binary MXE distribution

### ISSUE THREAD

**Issue by ooxi** [mxe/mxe#1155]
Using the binary amd64 MXE distribution to build [violetland](https://github.com/ooxi/violetland) works like a charm but i686 fail with a linking error

    /usr/lib/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.3/../../../../i686-w64-mingw32.static/lib/../lib/libboost_filesystem-mt.a(operations.o): duplicate section `.rdata$_ZTSN5boost6detail17sp_counted_impl_pINS_10filesystem6detail11dir_itr_impEEE[__ZTSN5boost6detail17sp_counted_impl_pINS_10filesystem6detail11dir_itr_impEEE]' has different size

I tried to compile tag [0.5](https://github.com/ooxi/violetland/tree/0.5) using the following command after having installed `mxe-i686-w64-mingw32.static-gcc cmake mxe-i686-w64-mingw32.static-gettext mxe-i686-w64-mingw32.static-sdl mxe-i686-w64-mingw32.static-sdl-ttf mxe-i686-w64-mingw32.static-sdl-mixer mxe-i686-w64-mingw32.static-sdl-image mxe-i686-w64-mingw32.static-boost`

    /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-cmake . && make install

**Comment by starius** [comment]
I'm trying to build violetland 0.5 with my local MXE.
Getting the following error: https://gist.github.com/476e661040307cd91e02
The following path is added to CMAKE_MODULE_PATH: lib/fcitx/cmake
But there is no lib/fcitx/cmake in the tree.

**Comment by ooxi** [comment]
Sorry I failed to tell you you have to `git submodule init && git submodule update` first

**Comment by starius** [comment]
Thank you! Now I can reproduce the linking error.

**Comment by ooxi** [comment]
Thanks for your support! Just wanted to let you know MXE is really great and I used your [battleship example](https://github.com/zer0main/battleship/blob/master/.travis.yml) to enable an [automatic Windows build on Travis CI](https://github.com/ooxi/violetland).

**Comment by starius** [comment]
It is not an error, it is a warning. The binary violetland.exe was created.

This warning is [told](http://stackoverflow.com/a/16426755) to be ignored in similar situation (boost, Windows).

Build results: http://elric.ga/mxe/violetland.zip

Something seems to be wrong with fonts. I extract the zip file on Windows XP machine and invoked start.cmd and get the following picture:

![violetland in Windows XP](http://i.imgur.com/2PHACGn.png)

**Comment by ooxi** [comment]
You are right. I was so irritated by the message that I didn't even check whether or not the build succeeded.

Thanks again!
