### ISSUE TITLE
SOURCE_DIR and BUILD_DIR variables

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1159]
I'd like to add target-specific variables so that package rules look like:

```sh
cd $(BUILD_DIR) && $(SOURCE_DIR)/configure \
    $(MXE_CONFIGURE_OPTS) \
    ...
make -C $(BUILD_DIR) ...

# or

cd $(BUILD_DIR) && $(TARGET)-cmake \
    ... \
    $(SOURCE_DIR)
make -C $(BUILD_DIR) ...

```

This is partly a cosmetic change but it's also to allow building directly from local repositories (especially debugging in `gits` directory down the track without having to export/unpack/patch).

Any thoughts (especially about naming)?

**Comment by starius** [comment]
Looks good.

I didn't know `./configure` can build not in source directory.

**Comment by tonytheodore** [comment]
I think many packages can build out-of-source, some [recommend or require it](https://gcc.gnu.org/install/configure.html):

>First, we highly recommend that GCC be built into a separate directory from the sources which does not reside within the source tree. This is how we generally build GCC; building where srcdir == objdir should still work, but doesn't get extensive testing; building where objdir is a subdirectory of srcdir is unsupported.

Any preference for BUILD_DIR, BLD_DIR, BLDDIR, OBJ_DIR, WRK_DIR, ...?

**Comment by starius** [comment]
SOURCE_DIR and BUILD_DIR are nice.
