### ISSUE TITLE
fix packages for gcc 5.3

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1166]
Following on from https://github.com/mxe/mxe/issues/964#issuecomment-170358288 , the following packages failed to compile with gcc 5.3.0:

libical: https://gist.github.com/c1dbf9714263ff4dcc8c
~~libieee1284: https://gist.github.com/b2f3d510014903930c01~~

Commit 51219d14b85178ce8b23241291b8769737973e7b
Version of gcc was changed to 5.3.0 in `plugins/gcc52/gcc52-overlay.mk`.
Build command: `make MXE_PLUGIN_DIRS=plugins/gcc52 -j 3`

**Comment by tonytheodore** [comment]
libieee1284 doesn't seem related to `gcc` but `automake` version. It this the first time it's tested on wheezy?

**Comment by starius** [comment]
@tonytheodore, you're right. See https://github.com/mxe/mxe/issues/1170

**Comment by tonytheodore** [comment]
Could be an ordering issue, lots of warnings but no errors https://gist.github.com/tonytheodore/3bbeae762dccb1a3e659

**Comment by tonytheodore** [comment]
I installed `dlfcn-win32` and the build still succeeds.

**Comment by tonytheodore** [comment]
Did you update `isl` also?

**Comment by starius** [comment]
I hadn't updated `isl` when reporting this issue. But I've updated it now, because I cloned you branch `gcc5`.

**Comment by tonytheodore** [comment]
I built again with previous `isl` and all packages installed and can't replicate the issue.

**Comment by starius** [comment]
I built it successfully with old isl too. Probably it is an ordering issue.

**Comment by tonytheodore** [comment]
gcc is now at 5.4 #1541 without build failures.
