### ISSUE TITLE
make test via emulator (qemu?)

### ISSUE THREAD

**Issue by UniqueFool** [mxe/mxe#1167]
has there been any discussion to support running the equivalent of "make test" by running the corresponding binaries in some kind of emulator like qemu ?

there's been some talk about doing CI: https://github.com/mxe/mxe/issues/1142

So I was wondering if there are any major showstoppers that would prevent mxe from using something like qemu to run library-specific tests as some kind of sanity check/regression testing.

Personally, I don't have access to a Windows system without having to re-boot, but I would still like to run "make test" for important libraries that my projects are using, including the test suite of the project itself.

Ideally, I am thinking in terms of some kind of "make test" equivalent that could optionally be executed prior to building  software that requires the underlying packages.

The thinking here is that I can hopefully more easily determine where a segfault is occurring, i.e. if it's in any of the dependencies or higher level code

**Comment by tonytheodore** [comment]
I think there's no inherent showstoppers other than nobody had the time to look at it yet.

I haven't used `qemu` but from what I understand it would be hard to integrate with a project's test suite - `wine` would be more suitable in that case so we could run the tests as part of the build.

I'm not sure how to go about running tests on an ad-hoc basis.

**Comment by UniqueFool** [comment]
at least with cmake, it isn't unheard of to be used in conjunction with an emulator by wrapping the call to the compiled executable, e.g.: https://cmake.org/pipermail/cmake/2011-February/043076.html

"make test" is often a supported target by most build systems - running tests as part of the normal/full build would require some way to 1) copy the binaries to the VM/emulator and 2) invoke the test program

**Comment by TimothyGu** [comment]
Personally I have some experiences [using qemu for a CI](http://fatebeta.ffmpeg.org/history/x86-haiku-gcc-4.8). If we were to use qemu, there are a very important question we have to get through first.

Does qemu support Windows (since Windows obviously doesn't support qemu)?

If it does, just as @UniqueFool said, we will need ways to

1. tell the vm what to do
   1. is the build process the same for every build (then we can use an auto-run script; that's what I use)
   2. or do we need a method to pass messages in (e.g. run test-sdf1231ad.exe and return the exit code)
2. pass files in
   1. network (easier to setup; that's what I use since I don't need anything beyond the Git tree and an rsync directory)?
   2. shared file system (probably faster)?

**Comment by UniqueFool** [comment]
indeed, a typical unit test will be "headless", i.e. only require a windows environment (shell) to run a program and return an errorlevel - so qemu might add to much overhead compared to running the whole thing via wine.
with WINE, there's at least not the need to transfer any files.
so maybe WINE already is the best option here ?

Assuming that is the case, it would be interesting to see if "make test" could be "wrapped" in a holistic fashion to optionally use wine for running the corresponding unit tests - with the added requirement that "wine" would need to be installed obviously.

PS: Yes, qemu runs on Windows.

**Comment by starius** [comment]
Sometimes wine is enough. See how [luarocks plugin](https://github.com/mxe/mxe/tree/master/plugins/luarocks) is tested.

I think the best possible test of MXE would be a collection of downstream projects which can be automatically built and tested (it doesn't matter how exactly: in wine, in Windows, in virtual machine). It can be done by adding downstream projects to `plugins/apps`. Any package (or its following packages) should be used in one of downstream projects. We can even introduce coverage as a percentage of packages used in at least one downstream projects. Then we can guarantee that all packages in MXE are usable and there are no dead broken packages. It is a better purpose than testing all packages by themselves. In brief, **integration tests > unit tests**.

**Comment by UniqueFool** [comment]
I just found out that wine now also supports OpenCL, referring to: https://github.com/mxe/mxe/issues/1161

Beginning with wine 1.6: https://bugs.launchpad.net/ubuntu/+source/wine1.6/+bug/1297315

Some systems may need a workaround apparently: http://xuancong84.blogspot.sg/2015/03/installing-conflicting-packages-on.html
