### ISSUE TITLE
libgomp questions (OpenMP support)

### ISSUE THREAD

**Issue by UniqueFool** [mxe/mxe#1169]
grep'ing through the src directory, I see libgomp being used/referenced in a few places - does that mean that we can generally assume OpenMP support to be working for the mxe compiler ?

http://bisqwit.iki.fi/story/howto/openmp/
https://computing.llnl.gov/tutorials/openMP/

**Comment by TimothyGu** [comment]
Generally, yes, but last time we checked, the support for it was not [complete](https://github.com/mxe/mxe/issues/331#issuecomment-35810803).

**Comment by UniqueFool** [comment]
thank you, the inclusion of the validation suite was a good idea!

**Comment by tonytheodore** [comment]
I've added a note in docs https://github.com/mxe/mxe/commit/a449841274217582a15c11f560944853c910b30b.

Support may be better than the tests indicate, the batch file test runner isn't a very good substitute for the perl one. This could be improved greatly with #1167.

**Comment by UniqueFool** [comment]
Thank you, FWIW, the gcc wiki lists a number of OpenMP related validation suites: https://gcc.gnu.org/wiki/openmp
