### ISSUE TITLE
libieee1284 fails to build in Wheezy

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1170]
@s09bQ5, libieee1284 fails to build in Debian Wheezy.
Build log: https://gist.github.com/a9bf3d7ab554614d1dcc
Commit 77a96085cf90110b8589cae50ab0f9ad93b6ba54

**Comment by s09bQ5** [comment]
The build fails because patch < 2.7 (Wheezy has 2.6.1) can't handle the rename done in the patch.
Shortening the patch by using the rename feature of git was requested by @TimothyGu in #1131.

**Comment by TimothyGu** [comment]
I believe that it's time we drop Wheezy support completely. Historically, Debian oldstable has always been a pain to support and therefore unsupported:

> Only the latest Debian stable series is supported.
> http://mxe.cc/#requirements-debian

Wheezy was the stable for a long time, and we generally have pretty good support for it. But now, the times have changed; more specifically, we have to sacrifice 577 lines' worth of readability for a 3-year-old operating system, that people who actually care about bleeding-edge software offered in MXE *probably* do not use.

**Comment by starius** [comment]
I think we can fully drop Wheezy support when Jessie becomes oldstable.

**Comment by tonytheodore** [comment]
Is there a backport for `patch` on Wheezy? Better still, could we name the patch in a way that triggers the patch workflow and apply it with `git am`?

**Comment by starius** [comment]
> Is there a backport for patch on Wheezy?

No

> Better still, could we name the patch in a way that triggers the patch workflow and apply it with git am?

I thought about it. On the one hand, you are right, one patch format is easier for us to maintain and develop new features. On the other hand, strict requirements for patches would increase MXE entry threshold decreasing the number of contributions we get. Probably some contributors are not familiar with git patches, but they still can create patches manually using `diff` tool or other tool. If we switch to git patches, we should at least provide a converter from existing format to git patch format.

**Comment by tonytheodore** [comment]
> I believe that it's time we drop Wheezy support completely.

@TimothyGu, Wheezy support is still required to build packages, especially for Travis CI which uses a version of `libc` prior to Jessie. See https://github.com/mxe/mxe/issues/1177#issuecomment-173752040.

The latest version of patch (2.7.5) is now being built for Wheezy (#1194) and I think it is safe to revert #1171.

**Comment by starius** [comment]
Oops, I've reverted #1171 with GitHub "revert" button in #1171. It created a branch "revert-1171-no-renaming-patches" in main MXE repo and pushed the commit directly to "master". I think, branch "revert-1171-no-renaming-patches" can be deleted.

**Comment by tonytheodore** [comment]
Thanks, that has tricked me before, it certainly doesn't do what it claims - "Create a new pull request to revert these changes".

Branch is now deleted.
