### ISSUE TITLE
Rebase before merge?

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1174]
Does anyone know if there's a way to disable GitHub's `merge` button? I'd like to reduce merge commits but my searching so far leads to browser extensions or complicated workflows.

**Comment by starius** [comment]
I would rename a pull request to "[WIP]: ..." to tell others not to merge it.

You can protect `master` branch in Github to prevent not tested (in CI) or not fast-forward pull-requests, but it will be too inconvenient.
