### ISSUE TITLE
gdk-pixbuf is broken

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1177]
Log: https://gist.github.com/a4d92b7e235306e36fa2
Debian Wheezy
Commit c9df66b1645f543f6644dfea6cda48c931dddcda + [changes in build-pkg](https://github.com/mxe/mxe/compare/master...LuaAndC:build-pkg-only-deps2)

**Comment by tonytheodore** [comment]
Can you try:

```
make libtool gettext MXE_PLUGIN_DIRS=plugins/native
```

for this and #1178?

**Comment by starius** [comment]
`make libtool gettext gdk-pixbuf icu4c MXE_PLUGIN_DIRS=plugins/native` succeeded for target `i686-w64-mingw32.static`. (`i686-w64-mingw32.static` is also broken without building native tools.)

**Comment by starius** [comment]
Is `MXE_PLUGIN_DIRS=plugins/native` needed for Wheezy builds?

**Comment by tonytheodore** [comment]
It would seem the best way to extend support for Wheezy rather than [changing individual packages](https://github.com/mxe/mxe/issues/1170#issuecomment-170798279), especially if no backports are available.

**Comment by starius** [comment]
Can we set `MXE_PLUGIN_DIRS=plugins/native` on Wheezy automatically?

**Comment by tonytheodore** [comment]
We could, but it would then build unnecessary packages (coreutils, sed, make, etc.) and may not play nice with `build-pkg` (i.e. `make libtool` installs multiple packages). It will be easier once #516 and #961 are implemented.

In the mean time, we should [update the docs to reflect Debian Jessie](https://github.com/mxe/mxe/issues/593#issuecomment-166735801) and note other steps for Wheezy. We could also steer Wheezy users towards http://pkg.mxe.cc and/or provide our own "backports" there.

**Comment by starius** [comment]
> We could also steer Wheezy users towards http://pkg.mxe.cc and/or provide our own "backports" there.

I build packages for http://pkg.mxe.cc on Wheezy machine, that is why I'm asking. I don't know how to build next release. One option is to fix all problems with Wheezy and the other is to build on Jessie. The latter would make packages unusable for Wheezy and probably for Travis, as it uses Ubuntu with libc6 version in between Wheezy and Jessie.

**Comment by tonytheodore** [comment]
#1194 should work with no changes to `build-pkg` or any existing logic.
