### ISSUE TITLE
icu4c is broken

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1178]
Log: https://gist.github.com/8f8693ee4761ed40ffc4
Debian Wheezy
Commit c9df66b1645f543f6644dfea6cda48c931dddcda + [changes in build-pkg](https://github.com/mxe/mxe/compare/master...LuaAndC:build-pkg-only-deps2)

**Comment by tonytheodore** [comment]
Fixed in https://github.com/mxe/mxe/pull/1194
