### ISSUE TITLE
wget is broken

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1181]
Log: https://gist.github.com/7ae7b09e9f7defb7c6e7
Debian Wheezy
Commit c9df66b1645f543f6644dfea6cda48c931dddcda + [changes in build-pkg](https://github.com/mxe/mxe/compare/master...LuaAndC:build-pkg-only-deps2)

**Comment by mabrand** [comment]
Building wget works for me. Just did a fresh build at commit 4f2f9bf8064a0ad8733a2297d5a0cbcad7f35d3f.

**Comment by starius** [comment]
I rebuilt `wget` for commit 4f2f9bf8064a0ad8733a2297d5a0cbcad7f35d3f without build-pkg and it fails with the same error. Maybe it fails on Debian Wheezy only.

The error message is "undefined reference to `libintl_dgettext'". It may be related to https://github.com/mxe/mxe/issues/1104

**Comment by tonytheodore** [comment]
Reproduce with `make gnutls && make wget`. `gnutls` is missing `libidn` dependency #1183.

**Comment by starius** [comment]
> Reproduce with `make gnutls && make wget`

Why `make gnutls` was needed? (`wget` depends on `gnutls`.)

**Comment by tonytheodore** [comment]
I see, `make wget -j1` also fails so the bug is actually in the way `wget` sets libs for `libidn`. If `wget` switched to `openssl` this would probably re-appear.
