### ISSUE TITLE
Failed to build xerces x86_64

### ISSUE THREAD

**Issue by TurBoss** [mxe/mxe#1187]
Hi

Latest version from git fails to build xerces.static for x86_64 (didn't test in i686)

here is the log

I'm sorry if is something obvious but I'm not an expert

thx.

here is the log http://dpaste.com/034KKP3

**Comment by starius** [comment]
> x86_64-w64-mingw32.static-ranlib: .libs/libxerces-c.a: No space left on device

Probably this is the reason of the failure.

**Comment by TurBoss** [comment]
few
