### ISSUE TITLE
Failed to build package mxe-conf for target x86_64-unknown-linux-gnu!

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1199]
http://pastebin.com/wdFCUpkz

**Comment by starius** [comment]
Does it work after applying the following patch:

```diff
diff --git a/src/mxe-conf.mk b/src/mxe-conf.mk
index cd12357..2d34bf0 100644
--- a/src/mxe-conf.mk
+++ b/src/mxe-conf.mk
@@ -109,7 +109,7 @@ define $(PKG)_BUILD_$(BUILD)
 
     #create readonly directory to force wine to fail
     mkdir -p "$$WINEPREFIX"
-    [ -f "$$WINEPREFIX/.gitkeep"] || touch "$$WINEPREFIX/.gitkeep"
+    [ -f "$$WINEPREFIX/.gitkeep" ] || touch "$$WINEPREFIX/.gitkeep"
     chmod 0555 "$$WINEPREFIX"
 
     #create script "wine" in a directory which is in PATH

```

?

**Comment by pavelvat** [comment]
No. 
http://pastebin.com/Xrhkq3BW

**Comment by starius** [comment]
The error message has changed:

Before:

```
[ -f "$WINEPREFIX/.gitkeep"] || touch "$WINEPREFIX/.gitkeep"
bash: line 0: [: missing `]'
touch: cannot touch '/home/pavel/builds/mxe/usr/readonly/.gitkeep': Permission denied
```

After:

```
[ -f "$WINEPREFIX/.gitkeep" ] || touch "$WINEPREFIX/.gitkeep"
touch: cannot touch '/home/pavel/builds/mxe/usr/readonly/.gitkeep': Permission denied
```

**Comment by starius** [comment]
The error occurred because the directory already exists but it is read-only, so a file can't be touched inside the directory. The check `[ -f "$WINEPREFIX/.gitkeep" ]` was introduced exactly to prevent such error, but it didn't work. I don't know why. We can replace this line with
```
-touch "$$WINEPREFIX/.gitkeep"
```
 as a workaround, until we understand this error. Does this workaround work for you?

**Comment by pavelvat** [comment]
>Does this workaround work for you?

Yes.

**Comment by starius** [comment]
I think it has failed because this directory had already been created but without that file inside. The file has been added recently. It should not occur in a clean directory.

I have added `chmod 755` before `touch` in https://github.com/mxe/mxe/pull/1202
Does it work for you?

**Comment by pavelvat** [comment]
> Does it work for you?

Yes.
