### ISSUE TITLE
libzip include zipconf.h ends up in a wrong place

### ISSUE THREAD

**Issue by gyunaev** [mxe/mxe#1200]
When libzip is built, one of its headers gets stored in {target}/lib/include/libzip/zipconf.h instead of {target}/include/libzip/zipconf.h. Thus any app using libzip does not compile.

**Comment by tonytheodore** [comment]
I'd suggest using `pkg-config` to set the correct include directories. The rationale for installing under `{target}/lib/include/libzip` might be that the `zipconf.h` header is not arch-independent.

**Comment by gyunaev** [comment]
Makes sense. Thank you Tony! And thank you again for the great project, I use it quite extensively for building Karaoke Lyric Editor and Kchmviewer.

BTW, is -shared Qt5 build considered stable now?

**Comment by tonytheodore** [comment]
Qt5 shared should be considered stable, perhaps even mature. One of the main motivations for shared support in the first place was `webkit` and it is now on the verge of being deprecated.
