### ISSUE TITLE
How to add icon to generated executable

### ISSUE THREAD

**Issue by ooxi** [mxe/mxe#1201]
Hi,

I was wondering what's the best way to add an icon to an executable generated via MXE? One way is using windres & link the generated file with gcc (as described on [stackoverflow](http://stackoverflow.com/a/708382/2534648)) but I cannot find windres as MXE package.

Another way would be running [Resource hacker in wine](http://stackoverflow.com/a/23375444/2534648) and adding the icon after the executable was generated. But that would include running non free code and wine.

What's your recommendation? I think there should be a straight way to add an icon to cross compiled executables since icons are very common on Windows.

-- ooxi

**Comment by starius** [comment]
MXE does have windres:
```
$ find usr/ -name '*windres'
usr/bin/i686-w64-mingw32.shared-windres
usr/bin/x86_64-w64-mingw32.shared-windres
usr/bin/i686-w64-mingw32.static-windres
usr/bin/x86_64-w64-mingw32.static-windres
```

Package `binutils`.

**Comment by ooxi** [comment]
> Package `binutils`.

That's the explanation, I was looking for a dedicated package :-) I'll try adding an icon to an executable and will come back when trouble arises.

**Comment by TimothyGu** [comment]
I know FFmpeg uses windres to add versioning information to its libraries and programs, so I don't expect too many troubles with icons.

**Comment by starius** [comment]
How to add icon using CMake:

0. Use MXE wrapper for CMake. It sets variables `CMAKE_RC_COMPILER` and `CMAKE_RC_COMPILE_OBJECT`.
1. Create .rc file. See http://stackoverflow.com/a/708382/2534648
2. Add the .rc file to sources list of `add_executable` command.

I [managed to add icon](https://github.com/npge/npge/pull/91) to Windows executables of my tool NPG-explorer.

**Comment by ooxi** [comment]
Thanks @starius! When posting this question I did not realize that CMake is capable of automatically using the resource compiler much less that MXE already configured CMake in the correct way.
