### ISSUE TITLE
ffmpeg version ends up as MXE's HEAD hash

### ISSUE THREAD

**Issue by avih** [mxe/mxe#1219]
Not sure if a bug, so for now let it just be a question.

I patched `src/ffmpeg.mk` to use git-master instead of 2.8.4 like so:

```shell
$(PKG)_VERSION  := a655bc834479024ff4d60d0b8ecca290e73eb96c
$(PKG)_CHECKSUM := 430eaca969898e2428a3901d5923abb1683ae200bf149e6ac24a4528b0c5fa27
$(PKG)_SUBDIR   := FFmpeg-$($(PKG)_VERSION)
$(PKG)_FILE     := FFmpeg-$($(PKG)_VERSION).tar.gz
$(PKG)_URL      := https://github.com/FFmpeg/FFmpeg/archive/$($(PKG)_VERSION).tar.gz
```

(and also removed `libvo-aacenc` which was removed in ffmpeg 2.9), and it builds an works fine, but the revision which ffmpeg reports is of MXE HEAD hash (which is the commit which contains this change to `ffmpeg.mk`), instead of something which starts with `a655bc..` - which is the revision it downloads.

Any idea what I might be doing wrong or how to make it use an ffmpeg version rather than an MXE version?

FWIW, I checked how ffmpeg generates its version - it's in `version.sh` which checks git HEAD and then I _think_ writes it to `ffversion.h` at build time. And apparently this ends up finding the MXE HEAD hash.

Also, as far as I can tell, the downloaded archive does not contain the hash in any of its files. So I guess getting MXE's hash is better than nothing, but still, I think it would have been better, if possible, to use the version from `$(PKG)_VERSION`.

**Comment by TimothyGu** [comment]
You could apply a patch like this:

```diff
From 94025e64c83646d8f7715816637ac9ebd74e1640 Mon Sep 17 00:00:00 2001
From: Timothy Gu <timothygu99@gmail.com>
Date: Mon, 15 Feb 2016 06:45:54 -0800
Subject: [PATCH] version.sh: Use $GIT_DIR

---
 version.sh | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)

diff --git a/version.sh b/version.sh
index a9d7e39..c46aec5 100755
--- a/version.sh
+++ b/version.sh
@@ -2,18 +2,20 @@
 
 # Usage: version.sh <ffmpeg-root-dir> <output-version.h> <extra-version>
 
+export GIT_DIR="$1/.git"
+
 # check for git short hash
 if ! test "$revision"; then
     if (cd "$1" && grep git RELEASE 2> /dev/null >/dev/null) ; then
-        revision=$(cd "$1" && git describe --tags --match N 2> /dev/null)
+        revision=$(git describe --tags --match N 2> /dev/null)
     else
-        revision=$(cd "$1" && git describe --tags --always 2> /dev/null)
+        revision=$(git describe --tags --always 2> /dev/null)
     fi
 fi
 
 # Shallow Git clones (--depth) do not have the N tag:
 # use 'git-YYYY-MM-DD-hhhhhhh'.
-test "$revision" || revision=$(cd "$1" &&
+test "$revision" || revision=$(
   git log -1 --pretty=format:"git-%cd-%h" --date=short 2> /dev/null)
 
 # Snapshots from gitweb are in a directory called ffmpeg-hhhhhhh or
-- 
2.1.4
```

Then when `make`ing, add `git_hash=$($(PKG)_VERSION)` as an environmental variable. Tell me if it works. If it does I'll send it to FFmpeg for review.

**Comment by TimothyGu** [comment]
By "adding ... as an environmental variable" I meant this:

```diff
diff --git a/src/ffmpeg.mk b/src/ffmpeg.mk
index 14de3cc..7a350a1 100644
--- a/src/ffmpeg.mk
+++ b/src/ffmpeg.mk
@@ -65,6 +65,6 @@ define $(PKG)_BUILD
         --enable-libvpx \
         --enable-libx264 \
         --enable-libxvid
-    $(MAKE) -C '$(1)' -j '$(JOBS)'
+    $(MAKE) -C '$(1)' -j '$(JOBS)' git_hash=$($(PKG)_VERSION)
     $(MAKE) -C '$(1)' -j 1 install
 endef
```

**Comment by avih** [comment]
Thanks, I'll try it too. For now, I see that `version.sh` has this comment+code:
```shell
# Snapshots from gitweb are in a directory called ffmpeg-hhhhhhh or
# ffmpeg-HEAD-hhhhhhh.
if [ -z "$revision" ]; then
  srcdir=$(cd "$1" && pwd)
  case "$srcdir" in
    */ffmpeg-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f])
      git_hash="${srcdir##*-}";;
    */ffmpeg-HEAD-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f])
      git_hash="${srcdir##*-}";;
  esac
fi```

So it does try to do something for archives too, but apparently the format is slightly different for github archives which are  `FFmpeg-<full-hash>`.

I'll try few approaches and let you know if I got it to work. Thanks.

**Comment by TimothyGu** [comment]
Yeah, that's why I asked you to simply override the hash detection by forcing `git_hash`. FFmpeg doesn't "officially" support GitHub tarballs so we haven't gotten that fixed yet.

**Comment by avih** [comment]
Hmm.. actually.. this might be enough:

```shell
$(MAKE) -C '$(1)' -j '$(JOBS)' revision=$($(PKG)_VERSION)
```

Since version.sh start by testing $revision and using it if it exists.

And this would use only the first 7 chars (I'm not a makefile/shell guru, but it works for me, and I couldn't find a substring function for makefiles...):
```shell
$(MAKE) -C '$(1)' -j '$(JOBS)' revision=$(shell (rev=$($(PKG)_VERSION); echo $${rev:0:7}))
```

7 chars should also cover an actual version in `$($(PKG)_VERSION)`, e.g. `2.8.4` is 5 chars and `2.12.40` would be 7 chars.

Also, since MXE/ffmpeg cannot know the revision date without an actual git repo, then I think it's OK to not have a date at all with the revision. Alternatively, it could use the build date (i.e. now), but I think the version which is defined at `ffmpeg.mk` should be good enough as is, as up to 7 chars.

**Comment by avih** [comment]
And if we want to avoid bashism and instead depend on `awk` (not sure if it's a dependency of MXE), then this patch works for me:
```diff
diff --git a/src/ffmpeg.mk b/src/ffmpeg.mk
index 7671f1b..e1c9c93 100644
--- a/src/ffmpeg.mk
+++ b/src/ffmpeg.mk
@@ -71,6 +71,6 @@ define $(PKG)_BUILD
         --enable-libx264 \
         --enable-libxvid \
        --enable-libmfx
-    $(MAKE) -C '$(1)' -j '$(JOBS)'
+    $(MAKE) -C '$(1)' -j '$(JOBS)' revision=$(shell (echo $($(PKG)_VERSION) | awk '{ s=substr($$0, 1, 7); print s; }'))
     $(MAKE) -C '$(1)' -j 1 install
 endef
```

Or, worse case we could leave it as exactly `$($(PKG)_VERSION)`. A bit long when 40 chars hash, but not terrible.

**Comment by TimothyGu** [comment]
The reason why I didn't use this approach is because I wanted to be consistent with the official format, which is 2.8.6.git-1234567.

We use GMSL (GNU Make Standard Library), which has a substring function:

```make
REV = $(call substr,$($(PKG)_VERSION),1,7)
```

**Comment by avih** [comment]
Well, I tried your first patches to `version.sh` and `ffmpeg.mk`, and the version ended up as
`2.8.git-<40-digits-hash>`
But as far as I understand master is already 2.9... so something seems off I think.

**Comment by avih** [comment]
Actually, `2.8.git` seems somewhat correct, since that's exactly the current content of https://github.com/FFmpeg/FFmpeg/blob/master/RELEASE even though the changelog on github already shows version 3.0 (and beyond too). So possibly some bug with their update process.

In general though, I think master is a version later than what appears at the file `RELEASE` but which version it actually is _might_ only be available at the git repo, not sure.

Also, the 40 digits hash should probably have been 7 instead.

**Comment by avih** [comment]
TBH, I think it would be OK to use the MXE version (possibly truncated to 7 chars). It would appear as a normal version or a plain hash if someone edits `ffmpeg.mk` for a different version/source. Up to you. I'm currently using your substring suggestion as:
```
$(MAKE) -C '$(1)' -j '$(JOBS)' revision=$(call substr,$($(PKG)_VERSION),1,7)
```

**Comment by TimothyGu** [comment]
RELEASE file fixed: ffmpeg/ffmpeg@5d823709301b3f2ca1c69b92f2f7dde37b6918a3.

Michael (who does all the FFmpeg releases) has a habit of forgetting to update RELEASE after a release. We just released FFmpeg 3.0 a few hours ago so nobody noticed that yet. Thanks for noticing.

> Well, I tried your first patches to version.sh and ffmpeg.mk, and the version ended up as
`2.8.git-<40-digits-hash>`

Yeah. You can use `substr` with `git_hash` as well.

> In general though, I think master is a version later than what appears at the file RELEASE but which version it actually is might only be available at the git repo, not sure.

True. I've brought this up in FFmpeg several years ago but nobody really cared. So the status quo was kept.

Regardless, you could probably consider updating the package to 3.0, which is close enough to master.

**Comment by avih** [comment]
> Regardless, you could probably consider updating the package to 3.0, which is close enough to master.

For MXE? sure, I'll PR.

Personally, I've been using master (updated occasionally) for some months now and I had no issues with it, except the reported version which I've now fixed.

**Comment by avih** [comment]
> True. I've brought this up in FFmpeg several years ago but nobody really cared. So the status quo was kept.

BTW, if you're going to bring it up again, I'd suggest that RELEASE on the master branch could have the following format `<next-version>-pre.git-<hash>`, and when the version branch is split from master, just remove the suffix and leave it as the version it became.

**Comment by tonytheodore** [comment]
This appears to be resolved.

Note that with #1470 you can use a local tree:

```
make ffmpeg ffmpeg_SOURCE_TREE=/path/to/ffmpeg/repo
```

**Comment by avih** [comment]
> This appears to be resolved.

Is it resolved at ffmpeg or at MXE?

Does it mean that I can patch `ffmpeg.mk` like the example at the first comment and expect the resulting executable/etc to have the correct revision/version?

**Comment by tonytheodore** [comment]
@avih wrote:
> I had no issues with it, except the reported version which I've now fixed.

Where did you fix this?

**Comment by avih** [comment]
I "fixed" it only locally following the suggestions above - by using a local patch similar to this:
``` diff
-    $(MAKE) -C '$(1)' -j '$(JOBS)'
+    $(MAKE) -C '$(1)' -j '$(JOBS)' revision=$(call substr,$($(PKG)_VERSION),1,7)
```

**Comment by TimothyGu** [comment]
See http://lists.ffmpeg.org/pipermail/ffmpeg-devel/2016-March/190885.html for a better fix. It was never applied to FFmpeg due to lack of reviews, but I'll make a renewed effort when I get the time.

**Comment by avih** [comment]
Thanks, Interesting read.

I'd be happy to drop my local patch once it's fixed at the ffmpeg side, but for now my patch does what I wanted.
