### ISSUE TITLE
problems with copydlldeps.sh

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1226]
https://github.com/mxe/mxe/pull/1215
1)Case sensitivity:
```
I will now search for $alldeps
debugOut: ADVAPI32.dll
debugOut: CRYPT32.dll
debugOut: DNSAPI.dll
debugOut: GDI32.dll
debugOut: IPHLPAPI.DLL
debugOut: KERNEL32.dll
debugOut: libaspell-15.dll
debugOut: libboost_system-mt.dll
debugOut: libbz2.dll
debugOut: LIBEAY32.dll
debugOut: libfreetype-6.dll
debugOut: libgcc_s_seh-1.dll
debugOut: libglib-2.0-0.dll
debugOut: libharfbuzz-0.dll
debugOut: libiconv-2.dll
debugOut: libidn-11.dll
debugOut: libintl-8.dll
debugOut: libjsoncpp.dll
debugOut: liblua5.3.dll
debugOut: libminiupnpc.dll
debugOut: libpcre16-0.dll
debugOut: libpcre-1.dll
debugOut: libpcrecpp-0.dll
debugOut: libpng16-16.dll
debugOut: libstdc++-6.dll
debugOut: MPR.dll
debugOut: msvcrt.dll
debugOut: ole32.dll
debugOut: OPENGL32.dll
debugOut: Qt5Concurrent.dll
debugOut: Qt5Core.dll
debugOut: Qt5Declarative.dll
debugOut: Qt5Gui.dll
debugOut: Qt5Multimedia.dll
debugOut: Qt5Network.dll
debugOut: Qt5Script.dll
debugOut: Qt5Sql.dll
debugOut: Qt5Widgets.dll
debugOut: Qt5Xml.dll
debugOut: Qt5XmlPatterns.dll
debugOut: SHELL32.dll
debugOut: SSLEAY32.dll
debugOut: USER32.dll
debugOut: WINMM.dll
debugOut: WS2_32.dll
debugOut: zlib1.dll
Warning: "ADVAPI32.dll"  not found. $counter=0.
Warning: "CRYPT32.dll"  not found. $counter=0.
Warning: "DNSAPI.dll"  not found. $counter=0.
Warning: "GDI32.dll"  not found. $counter=0.
Warning: "IPHLPAPI.DLL"  not found. $counter=0.
Warning: "KERNEL32.dll"  not found. $counter=0.
Warning: "LIBEAY32.dll"  not found. $counter=0.
Warning: "MPR.dll"  not found. $counter=0.
Warning: "msvcrt.dll"  not found. $counter=0.
Warning: "ole32.dll"  not found. $counter=0.
Warning: "OPENGL32.dll"  not found. $counter=0.
Warning: "SHELL32.dll"  not found. $counter=0.
Warning: "SSLEAY32.dll"  not found. $counter=0.
Warning: "USER32.dll"  not found. $counter=0.
Warning: "WINMM.dll"  not found. $counter=0.
Warning: "WS2_32.dll"  not found. $counter=0.
```
thus openssl libs (```LIBEAY32.dll```, ```SSLEAY32.dll```) are not copied.
2)Option ```--enforce```: It does not work for more than one argument (for example,  \<path_to_mxe>/mxe/usr/\<compiler>/qt5/plugins/platforms/  \<path_to_mxe>/mxe/usr/\<compiler>/qt5/plugins/audio/  \<path_to_mxe>/mxe/usr/\<compiler>/qt5/plugins/sqldrivers/).

**Comment by dl5rcw** [comment]
to be case insensitive, please give this a try: instead of find -name, use find -iname. iname shall be case insensitive. Find a modified file here: https://github.com/dl5rcw/mxe/blob/master/tools/copydlldeps.sh
Please let me know if this already solves your issue.

please not that --enforce is copying a directory into DESTDIR - e.g. creating DESTDIR/platforms. It is not a multi call and takes a single argument only. Mabe I should rename it --enforceDir to make it more precise?

**Comment by pavelvat** [comment]
>Please let me know if this already solves your issue.

```
MXE_DIR=~/builds/mxe
INSTALL_DIR=$BUILD_DIR/EiskaltDC++
TARGET_DIR=$MXE_DIR/usr/$GCC_VARIANT
GCC_VARIANT=x86_64-w64-mingw32.shared
$MXE_DIR/tools/copydlldeps.sh -c -d $INSTALL_DIR -F $INSTALL_DIR -R $TARGET_DIR -o $MXE_DIR/usr/bin/$GCC_VARIANT-objdump -e $TARGET_DIR/qt5/plugins/sqldrivers
```
Not solved: http://pastebin.com/4s3BJspN

>Please not that --enforce is copying a directory into DESTDIR - e.g. creating DESTDIR/platforms. It is not a multiCall and takes a single argument in the current version.

Ok, but this: 
```-e /path/to/dir1 -e /path/to/dir2 -e /path/to/dir3```
also does not work.

**Comment by dl5rcw** [comment]
Thanks, I see where we get here. Option --enforce is designed to be only called once, hence not tagged as multiCall in the description (see copydlldeps.sh --help).

With your feature request of making -e a multiCall option, you need a loop when processing the string. 
change  for curFile in $enforce; do 
into	for curFile in $( echo "${enforce}" | tr -s ' ' | tr ' ' '\n'); do

I am currently off-side but tried to add this feature for you on the fly via web-browser on github.com. Please go ahead and give this a try now: https://github.com/dl5rcw/mxe/blob/master/tools/copydlldeps.sh

**Comment by starius** [comment]
Maybe it would be easier to reimplement it in Python (or merge with existing `tools/copydlldeps.py`)? Python has nice built-in library `argparse` to parse arguments.

**Comment by dl5rcw** [comment]
The case sensitivity was an easy fix and great finding. The second one with option --enforce was just not necessary for multiple directories. Bash can loop and I hope my one-the-way-fix will help out of the box. 

But I have no problems if someone likes to reimplement in python. There were some issues when I looked at the python script it in the beginning and I think it was you that pointed out problems when used on 64bit applications. Someone then pointed out the shell script from Timothy and it was easier to start from there. I think we can improve it and add the multiple --enforce if not already working now.

**Comment by pavelvat** [comment]
>The case sensitivity was an easy fix and great finding. 

???
Case sensitivity problem is not solved: https://github.com/mxe/mxe/issues/1226#issuecomment-186826205

**Comment by dl5rcw** [comment]
Can you please check if find -iname works on your system? I am running debian 8.3.0.
I searched for your library with these modifications:
find /home/mxeuser/mxe/usr/x86_64-w64-mingw32.shared/ -iname "SSLEAY32.dll"
/home/mxeuser/mxe/usr/x86_64-w64-mingw32.shared/bin/ssleay32.dll

**Comment by pavelvat** [comment]
>Please go ahead and give this a try now: https://github.com/dl5rcw/mxe/blob/master/tools/copydlldeps.sh

Doesn't work:
```
~/builds/mxe/tools/copydlldeps.sh -c -d ~/builds/eiskaltdcpp/windows-release/64-bit/shared/EiskaltDC++ -F ~/builds/eiskaltdcpp/windows-release/64-bit/shared/EiskaltDC++ -R ~/builds/mxe/usr/x86_64-w64-mingw32.shared -o ~/builds/mxe/usr/bin/x86_64-w64-mingw32.shared-objdump -e /home/pavel/builds/mxe/usr/x86_64-w64-mingw32.shared/qt5/plugins/audio -e /home/pavel/builds/mxe/usr/x86_64-w64-mingw32.shared/qt5/plugins/platforms -e /home/pavel/builds/mxe/usr/x86_64-w64-mingw32.shared/qt5/plugins/sqldrivers
info: created --destdir /home/pavel/builds/eiskaltdcpp/windows-release/64-bit/shared/EiskaltDC++
/home/pavel/builds/mxe/tools/copydlldeps.sh: line 327: [: too many arguments
I will now search for $alldeps
```

**Comment by pavelvat** [comment]
>Can you please check if find -iname works on your system?

$  find /home/pavel/builds/mxe/usr/x86_64-w64-mingw32.shared/ -iname "SSLEAY32.dll"
/home/pavel/builds/mxe/usr/x86_64-w64-mingw32.shared/bin/ssleay32.dll

**Comment by starius** [comment]
> `copydlldeps.sh: line 327: [: too many arguments`

Try to replace `if [ ! -z $enforce ]; then` with `if [ ! -z "$enforce" ]; then`

It is often safer to use `"$foo"` instead of `$foo`.

**Comment by dl5rcw** [comment]
@starius absolutely right, thanks. The command was testing a single string before (which was okay). But when adding multiple directories, the quotes become necessary. I thought the loop would be fine. Regret that I edited without being able to check. Got tempted by the github.com feature

**Comment by pavelvat** [comment]
>Try to replace if [ ! -z $enforce ]; then with if [ ! -z "$enforce" ]; then

It works. Thanks.

**Comment by dl5rcw** [comment]
@pavelvat - great! I will provide a clean version as soon as I find a putty client to do a test. :)

**Comment by dl5rcw** [comment]
Updated the copydlldeps.sh and copydlldeps.md file according to this thread. Tested with a sample application. Offering updates in pull request #1227

**Comment by pavelvat** [comment]
@dl5rcw 
Not solved problems:
1)Case sensitivity ("find -iname" not fixed it)
2)How to search depends for plugins dll files from "install_dir/sqldrivers/"? The file ```install_dir/sqldrivers/qsqlite.dll``` depends on ```/home/pavel/builds/mxe/usr/x86_64-w64-mingw32.shared/bin/libsqlite3-0.dll```. Previously for ```copydlldeps.py``` I had used option ```-C /path/to/dir1 /path/to/dir2```:
https://github.com/mxe/mxe/pull/1165/files#diff-17d9a471cc45b22771072c4634dc97d9R60
Option:
```  -F, --infiles, --indir  The input directory of executable files and/or DLLs.``` doesn't search in subdirectories and doesn't support this: ```-F dir1 -F dir2 -F dir3```. 
Moreover ```copydlldeps.sh``` should work as follows:
first step: copy all dll plugins to ```install_dir/sqldrivers```, ```install_dir/audio```, ```install_dir/platforms```, etc.
second step: launch objdump.

**Comment by dl5rcw** [comment]
I appreciate your posting regarding proposed  behaviour. As you said: thanks, works! - I intended to help out offering an improved script. It worked in all of our four projects here, sorry that it did not work out yet for your needs.
I have simply not yet seen the need for recursive search in input directory as we have just had to search the application.exe. Adding plugins then worked perfectly fine. I am happy that we can further improve the code, feel free to contribute.

**Comment by pavelvat** [comment]
Simple test for openssl libs (Qt5Network.dll depends on openssl):
According to https://github.com/mxe/mxe/issues/1226#issuecomment-186814030 
edit file ```/path/to/mxe/tools/copydlldeps.sh``` instead of find -name, use find -iname.
```mkdir ~/tmp/Qt5NetworkDLLdepends```
```cp /path/to/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Network.dll ~/tmp/Qt5NetworkDLLdepends```
```/path/to/mxe/tools/copydlldeps.sh -c -d ~/tmp/Qt5NetworkDLLdepends -F ~/tmp/Qt5NetworkDLLdepends -R /path/to/mxe/usr/x86_64-w64-mingw32.shared```

```ls ~/tmp/Qt5NetworkDLLdepends```:
```libgcc_s_seh-1.dll  libpcre16-0.dll  libstdc++-6.dll  Qt5Core.dll  Qt5Network.dll  zlib1.dll```

**Comment by TimothyGu** [comment]
@pavelvat can you please use fenced code blocks when commenting? Your comments are fairly hard to read.

<pre>
```
&lt;paste your output here&gt;
```
</pre>

**Comment by dl5rcw** [comment]
find -iname was the first thing I edited. It is in my pull request.
