### ISSUE TITLE
Building MXE on Travis CI

### ISSUE THREAD

**Issue by ooxi** [mxe/mxe#1238]
Hi,

I experimented with [building MXE on Travis CI](https://github.com/ooxi/mxe-build/tree/travis) and [the results look promising](https://travis-ci.org/ooxi/mxe-build/builds/110905657):
1. Most packages can be build directly (291/396)
2. Some packages exceed a total build time of 50 minutes (56/396) this in including all dependencies
3. Some build tasks fail because of no output for more than 10 minutes (e.g. [itk](https://travis-ci.org/ooxi/mxe-build/jobs/110905775))
4. Some build tasks fail because of build errors (everything depending on [gdk-pixbuf](https://travis-ci.org/ooxi/mxe-build/builds/110905657))

Currently a build takes several days because I limited the number of parallel jobs. If we could reuse build artefacts (e.g. by uploading them on bintray) a Travis CI build would be totally feasible.

What do you think about this idea? I think a periodical rebuild of MXE could increase the confidentiality and would decrease the need for private tests.

-- ooxi

**Comment by TimothyGu** [comment]
If that helps, you can use [directory caching](https://docs.travis-ci.com/user/caching/) using `sudo: false` (which activates container-based architecture).

**Comment by starius** [comment]
Can packages build one by one in separated builds without rebuilding it from scratch?

**Comment by TimothyGu** [comment]
@starius without caching, no.

**Comment by ooxi** [comment]
Sorry I did not have Internet access in the last days. Maybe MXE could be build in a container based environment, if all dependencies are allowed.

**Comment by tonytheodore** [comment]
I've found the GitLab CI to be ideally suited to full MXE builds (in my minimal testing). The build slaves run on local hardware and are very easy to set up - I see Travis more as a CI for downstream projects using the binary distributions of MXE.

I'm not sure that caching solutions are in the spirit of the terms of service (of any given provider - knowing what we know about build resources!), and I'm pretty certain that containers are solutions looking for problems.

There's an enormous amount of latent computational capacity in the world, don't constrain yourself to free and centralised services.
