### ISSUE TITLE
non-free packages

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1242]
Is it possible to add non-free package ```FAAC```? For example, to mxe/plugins/non-free.
https://en.wikipedia.org/wiki/FAAC
https://sourceforge.net/projects/faac/

**Comment by tonytheodore** [comment]
Unfortunately, no.

Initial thoughts about plugins were that they could be used for "non-free" packages (in the Debian sense) and the basic mechanism allows for people to do that locally.

The recent [ZFS on Linux](https://sfconservancy.org/blog/2016/feb/25/zfs-and-linux/) closes a lot of loose ends about licence compatibility and what any given project wants to distribute.

We're not lawyers and don't want to be - the ambiguity of two licences that meet our DFSG criteria... for the time being, we'll stick to subsets of the GPL.
