### ISSUE TITLE
strip $(PREFIX)/$(TARGET)/bin/test-$(PKG).exe

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1249]
Some ```test-$(PKG).exe``` files have very large size and not used end users. In some cases after ```strip test-$(PKG).exe``` size decreases to ~10-20 times. For example, the package ```sparsehash``` has used strip https://github.com/mxe/mxe/blob/master/src/sparsehash.mk#L25.
https://github.com/mxe/mxe/issues/985 - this will really very useful option. Currently MXE has stripped by default some libraries (for example qt5 and zlib), but doesn't strip many other libraries, it is very uncomfortably.

**Comment by starius** [comment]
I have made a list of files with their sizes: https://gist.github.com/158805cd0383a8d702a4

I agree that we should strip executables (including large tests), but libraries should not be stripped, because it is hard to debug bugs without debugging info.

**Comment by pavelvat** [comment]
>but libraries should not be stripped, because it is hard to debug bugs without debugging info.

??? 
For debugging a program not needed debug symbols from dependencies. If I want run my program under ```GDB``` I just make the debug build of my program (for example -DCMAKE_BUILD_TYPE=Debug).

**Comment by starius** [comment]
Some entries of a backtrace can be library functions:

  * program passes wrong value (e.g., dangling pointer) to a library function,
  * buggy function from a program is called by a library function (callback).

A library's code can also be buggy, by the way. Without a debugging info, how can one identify a memory leak?

**Comment by starius** [comment]
I have calculated sum of sizes of all files and of .exe files:

```
$ cat sizes.txt | awk '{ sum+=$1} END {print sum}'
29438627499
$ cat sizes.txt | grep '.exe$' | awk '{ sum+=$1} END {print sum}'
12840322514
```

Exe files make up almost half of all size of MXE tree!

**Comment by pavelvat** [comment]
Currently Qt5 in MXE fully stripped by default and debugging Qt applications work fine.
In my opinion by default MXE should provide only stripped dll.

**Comment by starius** [comment]
I think, we should provide the following options:

```
STRIP_TARGET_BIN = TRUE # .exe
STRIP_TARGET_LIB = FALSE # .dll and .a
STRIP_NATIVE_EXE = TRUE # e.g., gcc
STRIP_NATIVE_LIB = TRUE # native libs
```

And provide a macro `STRIP` which takes a file and deduces its type and its target, consults values of `STRIP_*` settings and applies the corresponding prefixed `strip` to it, if necessary.

Maybe it is too complex.

**Comment by tonytheodore** [comment]
> Exe files make up almost half of all size of MXE tree!

Not ideal given we generally focus on libs! As a start, we should automatically strip the tests.
