### ISSUE TITLE
Qt 4 on x86_64-w64-mingw32.static.posix fails compiling

### ISSUE THREAD

**Issue by luca-penasa** [mxe/mxe#1251]
The build fails with the (first) error:

```
make[2]: Entering directory `/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/config.tests/unix/db2'
x86_64-w64-mingw32.static.posix-g++ -c -pipe -fno-keep-inline-dllexport -O2 -Wall -Wextra -fno-exceptions -fno-rtti -DUNICODE -DQT_NO_DYNAMIC_CAST -I'../../../mkspecs/win32-g++-4.6' -o db2.o db2.cpp
db2.cpp:42:20: fatal error: sqlcli.h: No such file or directory
 #include <sqlcli.h>
                    ^
compilation terminated.
make[2]: *** [db2.o] Error 1
make[2]: Leaving directory `/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/config.tests/unix/db2'
DB2 disabled.
InterBase auto-detection... ()
make[2]: Entering directory `/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/config.tests/unix/ibase'
x86_64-w64-mingw32.static.posix-g++ -c -pipe -fno-keep-inline-dllexport -O2 -Wall -Wextra -fno-exceptions -fno-rtti -DUNICODE -DQT_NO_DYNAMIC_CAST -I'../../../mkspecs/win32-g++-4.6' -o ibase.o ibase.cpp
ibase.cpp:42:19: fatal error: ibase.h: No such file or directory
 #include <ibase.h>
                   ^
compilation terminated.
make[2]: *** [ibase.o] Error 1
make[2]: Leaving directory `/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/config.tests/unix/ibase'
InterBase disabled.
OCI auto-detection... ()
make[2]: Entering directory `/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/config.tests/unix/oci'
x86_64-w64-mingw32.static.posix-g++ -c -pipe -fno-keep-inline-dllexport -O2 -Wall -Wextra -fno-exceptions -fno-rtti -DUNICODE -DQT_NO_DYNAMIC_CAST -I'../../../mkspecs/win32-g++-4.6' -o oci.o oci.cpp
oci.cpp:42:17: fatal error: oci.h: No such file or directory
 #include <oci.h>


etc...

Any idea?

**Comment by mabrand** [comment]
Those are just the results of configuration tests. The DB2 and OCI detection results shouldn't matter if Qt wasn't configured explicitly to build the db2 and oci drivers. Assuming that Qt was configured to use "system-sqlite", then the sqlite test failure probably is considered a failure for Qt's configure step. The solution would be to install the sqlite3-dev package. Or you could configure Qt to use its bundled sqlite3 sources. See the help in Qt's configure script and the options uses in qt.mk.

**Comment by luca-penasa** [comment]
the target with the "posix"  should enable c++11 threading library , see here: https://github.com/mxe/mxe/pull/958

Given qt4 compiles jut fine in static mode without posix I suspect it is a mxe bug...

**Comment by mabrand** [comment]
Thanks for that explanation. In addition, I see that what I wrote about sqlite was wrong.  (I mistakenly read "sqlcli.h:" as having to do with sqlite3, but that's not the sqlite3 driver.) I fixed my first comment.

So please give us your whole log..

**Comment by luca-penasa** [comment]
Here is the whole log if anybody wants to furhter investigate. I actually modified my code to make use of boost::mutex and boost::thread instead of std::*. So I was able to compile without the need of full c++11 support.

``
make[1]: Entering directory `/home/luca/Code/mxe.git'
uname -a
Linux aymaro 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
git log --pretty=tformat:"%H - %s [%ar] [%d]" -1
c702e6d44e8ca44ff181b99ff6c808af92cf672a - Update versions.json & build-matrix.html [24 hours ago] [ (HEAD, origin/master, origin/HEAD, master)]
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 17.1 Rebecca
Release:	17.1
Codename:	rebecca
autoconf --version 2>/dev/null | head -1
autoconf (GNU Autoconf) 2.69
automake --version 2>/dev/null | head -1
automake (GNU automake) 1.14.1
python --version
Python 2.7.6
perl --version 2>&1 | head -3

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 44 registered patches, see perl -V for more detail)
rm -rf   '/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix'
mkdir -p '/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix'
cd '/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix' &&  tar xzf '/home/luca/Code/mxe.git/pkg/qt-everywhere-opensource-src-4.8.7.tar.gz'
cd '/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7'
(cd '/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7' && patch -p1 -u) < /home/luca/Code/mxe.git/src/qt-1-cherrypicks.patch
patching file src/corelib/codecs/codecs.pri
patching file configure
patching file src/corelib/codecs/codecs.pri
patching file src/corelib/codecs/codecs.pri
patching file src/corelib/codecs/qtextcodec.cpp
patching file src/corelib/codecs/codecs.pri
patching file src/corelib/codecs/cp949codetbl_p.h
patching file src/corelib/codecs/qbig5codec.cpp
patching file src/corelib/codecs/qbig5codec_p.h
patching file src/corelib/codecs/qeucjpcodec.cpp
patching file src/corelib/codecs/qeucjpcodec_p.h
patching file src/corelib/codecs/qeuckrcodec.cpp
patching file src/corelib/codecs/qeuckrcodec_p.h
patching file src/corelib/codecs/qfontjpcodec.cpp
patching file src/corelib/codecs/qfontjpcodec_p.h
patching file src/corelib/codecs/qgb18030codec.cpp
patching file src/corelib/codecs/qgb18030codec_p.h
patching file src/corelib/codecs/qjiscodec.cpp
patching file src/corelib/codecs/qjiscodec_p.h
patching file src/corelib/codecs/qjpunicode.cpp
patching file src/corelib/codecs/qjpunicode_p.h
patching file src/corelib/codecs/qsjiscodec.cpp
patching file src/corelib/codecs/qsjiscodec_p.h
patching file src/corelib/codecs/qtextcodec.cpp
patching file src/plugins/codecs/cn/cn.pro
patching file src/plugins/codecs/cn/main.cpp
patching file src/plugins/codecs/cn/qgb18030codec.cpp
patching file src/plugins/codecs/cn/qgb18030codec.h
patching file src/plugins/codecs/codecs.pro
patching file src/plugins/codecs/jp/jp.pro
patching file src/plugins/codecs/jp/main.cpp
patching file src/plugins/codecs/jp/qeucjpcodec.cpp
patching file src/plugins/codecs/jp/qeucjpcodec.h
patching file src/plugins/codecs/jp/qfontjpcodec.cpp
patching file src/plugins/codecs/jp/qfontjpcodec.h
patching file src/plugins/codecs/jp/qjiscodec.cpp
patching file src/plugins/codecs/jp/qjiscodec.h
patching file src/plugins/codecs/jp/qjpunicode.cpp
patching file src/plugins/codecs/jp/qjpunicode.h
patching file src/plugins/codecs/jp/qsjiscodec.cpp
patching file src/plugins/codecs/jp/qsjiscodec.h
patching file src/plugins/codecs/kr/cp949codetbl.h
patching file src/plugins/codecs/kr/kr.pro
patching file src/plugins/codecs/kr/main.cpp
patching file src/plugins/codecs/kr/qeuckrcodec.cpp
patching file src/plugins/codecs/kr/qeuckrcodec.h
patching file src/plugins/codecs/tw/main.cpp
patching file src/plugins/codecs/tw/qbig5codec.cpp
patching file src/plugins/codecs/tw/qbig5codec.h
patching file src/plugins/codecs/tw/tw.pro
patching file src/plugins/plugins.pro
patching file src/corelib/codecs/qbig5codec.cpp
patching file src/corelib/codecs/qeucjpcodec.cpp
patching file src/corelib/codecs/qeucjpcodec_p.h
patching file src/corelib/codecs/qeuckrcodec.cpp
patching file src/corelib/codecs/qfontjpcodec.cpp
patching file src/corelib/codecs/qgb18030codec.cpp
patching file src/corelib/codecs/qjiscodec.cpp
patching file src/corelib/codecs/qjiscodec_p.h
patching file src/corelib/codecs/qjpunicode.cpp
patching file src/corelib/codecs/qsjiscodec.cpp
patching file src/corelib/codecs/qsjiscodec_p.h
patching file src/corelib/codecs/cp949codetbl_p.h
patching file src/corelib/codecs/qbig5codec.cpp
patching file src/corelib/codecs/qbig5codec_p.h
patching file src/corelib/codecs/qeucjpcodec.cpp
patching file src/corelib/codecs/qeucjpcodec_p.h
patching file src/corelib/codecs/qeuckrcodec.cpp
patching file src/corelib/codecs/qeuckrcodec_p.h
patching file src/corelib/codecs/qfontjpcodec.cpp
patching file src/corelib/codecs/qfontjpcodec_p.h
patching file src/corelib/codecs/qgb18030codec.cpp
patching file src/corelib/codecs/qgb18030codec_p.h
patching file src/corelib/codecs/qjiscodec.cpp
patching file src/corelib/codecs/qjiscodec_p.h
patching file src/corelib/codecs/qjpunicode.cpp
patching file src/corelib/codecs/qjpunicode_p.h
patching file src/corelib/codecs/qsjiscodec.cpp
patching file src/corelib/codecs/qsjiscodec_p.h
patching file src/corelib/codecs/codecs.pri
patching file src/corelib/codecs/qtextcodec.cpp
patching file src/corelib/codecs/qtextcodecplugin.cpp
patching file src/corelib/codecs/qtextcodecplugin.h
patching file src/corelib/global/qconfig-medium.h
patching file src/corelib/global/qconfig-minimal.h
patching file src/corelib/global/qconfig-nacl.h
patching file src/corelib/global/qconfig-small.h
patching file src/corelib/global/qfeatures.h
patching file src/corelib/global/qfeatures.txt
patching file src/gui/image/qmnghandler.pri
patching file src/gui/image/qtiffhandler.pri
patching file src/corelib/global/qglobal.h
patching file configure
patching file configure
patching file tools/designer/src/plugins/activeqt/activeqt.pro
patching file src/3rdparty/webkit/Source/WebKit/qt/tests/hybridPixmap/hybridPixmap.pro
patching file configure
cd '/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7' && QTDIR='/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7' ./bin/syncqt
header (master) created for ActiveQt
headers.pri file created for ActiveQt
headers.pri file created for QtXmlPatterns
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/codecs/cp949codetbl_p.h (1)
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/codecs/qbig5codec_p.h (1)
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/codecs/qeucjpcodec_p.h (1)
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/codecs/qeuckrcodec_p.h (1)
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/codecs/qfontjpcodec_p.h (1)
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/codecs/qgb18030codec_p.h (1)
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/codecs/qjiscodec_p.h (1)
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/codecs/qjpunicode_p.h (1)
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/codecs/qsjiscodec_p.h (1)
header created for /home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7/src/corelib/global/qconfig.h (2)
header (master) created for QtCore
headers.pri file created for QtCore
header (master) created for Qt3Support
headers.pri file created for Qt3Support
header (master) created for QtMultimedia
headers.pri file created for QtMultimedia
headers.pri file created for QtDeclarative
header (master) created for QtGui
headers.pri file created for QtGui
headers.pri file created for QtSql
header (master) created for QtDesigner
headers.pri file created for QtDesigner
header (master) created for QtNetwork
headers.pri file created for QtNetwork
headers.pri file created for QtScript
header (master) created for QtXml
headers.pri file created for QtXml
cd '/home/luca/Code/mxe.git/tmp-qt-x86_64-w64-mingw32.static.posix/qt-everywhere-opensource-src-4.8.7' && OPENSSL_LIBS="`'x86_64-w64-mingw32.static.posix-pkg-config' --libs-only-l openssl`" PSQL_LIBS="-lpq -lsecur32 `'x86_64-w64-mingw32.static.posix-pkg-config' --libs-only-l openssl` -lws2_32" SYBASE_LIBS="-lsybdb `'x86_64-w64-mingw32.static.posix-pkg-config' --libs-only-l gnutls` -liconv -lws2_32" ./configure -opensource -confirm-license -fast -xplatform win32-g++-4.6 -device-option CROSS_COMPILE=x86_64-w64-mingw32.static.posix- -device-option PKG_CONFIG='x86_64-w64-mingw32.static.posix-pkg-config' -force-pkg-config -release -exceptions -static -prefix '/home/luca/Code/mxe.git/usr/x86_64-w64-mingw32.static.posix/qt' -prefix-install -script -no-iconv -opengl desktop -no-webkit -no-glib -no-gstreamer -no-phonon -no-phonon-backend -accessibility -no-reduce-exports -no-rpath -make libs -nomake demos -nomake docs -nomake examples -qt-sql-sqlite -qt-sql-odbc -qt-sql-psql -no-sql-mysql -qt-sql-tds -D Q_USE_SYBASE -system-zlib -system-libpng -system-libjpeg -system-libtiff -system-libmng -no-system-sqlite -openssl-linked -dbus-linked -v
-no-system-sqlite: invalid command-line switch
Determining system architecture... (Linux:3.13.0-37-generic:x86_64)
    64-bit AMD 80x86 (x86_64)
    'windows' is supported
    'x86_64' is supported
System architecture: 'windows'
Precompiled-headers support enabled.

Usage:  configure [-h] [-prefix <dir>] [-prefix-install] [-bindir <dir>] [-libdir <dir>]
        [-docdir <dir>] [-headerdir <dir>] [-plugindir <dir> ] [-importdir <dir>] [-datadir <dir>]
        [-translationdir <dir>] [-sysconfdir <dir>] [-examplesdir <dir>]
        [-demosdir <dir>] [-buildkey <key>] [-release] [-debug]
        [-debug-and-release] [-developer-build] [-shared] [-static] [-no-fast] [-fast] [-no-largefile]
        [-largefile] [-no-exceptions] [-exceptions] [-no-accessibility]
        [-accessibility] [-no-stl] [-stl] [-no-sql-<driver>] [-sql-<driver>]
        [-plugin-sql-<driver>] [-system-sqlite] [-no-qt3support] [-qt3support]
        [-platform] [-D <string>] [-I <string>] [-L <string>] [-help]
        [-qt-zlib] [-system-zlib] [-no-gif] [-no-libtiff] [-qt-libtiff] [-system-libtiff]
        [-no-libpng] [-qt-libpng] [-system-libpng] [-no-libmng] [-qt-libmng]
        [-system-libmng] [-no-libjpeg] [-qt-libjpeg] [-system-libjpeg] [-make <part>]
        [-nomake <part>] [-R <string>]  [-l <string>] [-no-rpath]  [-rpath] [-continue]
        [-verbose] [-v] [-silent] [-no-nis] [-nis] [-no-cups] [-cups] [-no-iconv]
        [-iconv] [-no-pch] [-pch] [-no-dbus] [-dbus] [-dbus-linked] [-no-gui]
        [-no-separate-debug-info] [-no-mmx] [-no-3dnow] [-no-sse] [-no-sse2]
        [-no-sse3] [-no-ssse3] [-no-sse4.1] [-no-sse4.2] [-no-avx] [-no-neon]
        [-qtnamespace <namespace>] [-qtlibinfix <infix>] [-separate-debug-info] [-armfpa]
        [-no-optimized-qmake] [-optimized-qmake] [-no-xmlpatterns] [-xmlpatterns]
        [-no-multimedia] [-multimedia] [-no-phonon] [-phonon] [-no-phonon-backend] [-phonon-backend]
        [-no-media-backend] [-media-backend] [-no-audio-backend] [-audio-backend] 
        [-no-openssl] [-openssl] [-openssl-linked]
        [-no-gtkstyle] [-gtkstyle] [-no-svg] [-svg] [-no-webkit] [-webkit] [-webkit-debug]
        [-no-javascript-jit] [-javascript-jit]
        [-no-script] [-script] [-no-scripttools] [-scripttools] 
        [-no-declarative] [-declarative] [-no-declarative-debug] [-declarative-debug]
        [additional platform specific options (see below)]


Installation options:

    -qpa [name] ......... This will enable the QPA build.
                          QPA is a window system agnostic implementation of Qt.
                          If [name] is given, sets the default QPA platform (e.g xcb, cocoa).

 These are optional, but you may specify install directories.

    -prefix <dir> ...... This will install everything relative to <dir>
                         (default /home/luca/Code/mxe.git/usr/x86_64-w64-mingw32.static.posix/qt)

  * -prefix-install .... Force a sandboxed "local" installation of
                         Qt. This will install into
                         /home/luca/Code/mxe.git/usr/x86_64-w64-mingw32.static.posix/qt, if this option is
                         disabled then some platforms will attempt a
                         "system" install by placing default values
                         in a system location other than PREFIX.

 You may use these to separate different parts of the install:

    -bindir <dir> ......... Executables will be installed to <dir>
                            (default PREFIX/bin)
    -libdir <dir> ......... Libraries will be installed to <dir>
                            (default PREFIX/lib)
    -docdir <dir> ......... Documentation will be installed to <dir>
                            (default PREFIX/doc)
    -headerdir <dir> ...... Headers will be installed to <dir>
                            (default PREFIX/include)
    -plugindir <dir> ...... Plugins will be installed to <dir>
                            (default PREFIX/plugins)
    -importdir <dir> ...... Imports for QML will be installed to <dir>
                            (default PREFIX/imports)
    -datadir <dir> ........ Data used by Qt programs will be installed to <dir>
                            (default PREFIX)
    -translationdir <dir> . Translations of Qt programs will be installed to <dir>
                            (default PREFIX/translations)
    -sysconfdir <dir> ..... Settings used by Qt programs will be looked for in <dir>
                            (default PREFIX/etc/settings)
    -examplesdir <dir> .... Examples will be installed to <dir>
                            (default PREFIX/examples)
    -demosdir <dir> ....... Demos will be installed to <dir>
                            (default PREFIX/demos)

 You may use these options to turn on strict plugin loading.

    -buildkey <key> .... Build the Qt library and plugins using the specified
                         <key>.  When the library loads plugins, it will only
                         load those that have a matching key.

Configure options:

 The defaults (*) are usually acceptable. A plus (+) denotes a default value
 that needs to be evaluated. If the evaluation succeeds, the feature is
 included. Here is a short explanation of each option:

 *  -release ........... Compile and link Qt with debugging turned off.
    -debug ............. Compile and link Qt with debugging turned on.
    -debug-and-release . Compile and link two versions of Qt, with and without
                         debugging turned on (Mac only).

    -developer-build ... Compile and link Qt with Qt developer options (including auto-tests exporting)

    -opensource ........ Compile and link the Open-Source Edition of Qt.
    -commercial ........ Compile and link the Commercial Edition of Qt.


 *  -shared ............ Create and use shared Qt libraries.
    -static ............ Create and use static Qt libraries.

 *  -no-fast ........... Configure Qt normally by generating Makefiles for all
                         project files.
    -fast .............. Configure Qt quickly by generating Makefiles only for
                         library and subdirectory targets.  All other Makefiles
                         are created as wrappers, which will in turn run qmake.

    -no-largefile ...... Disables large file support.
 +  -largefile ......... Enables Qt to access files larger than 4 GB.

 *  -no-system-proxies . Do not use system network proxies by default.
    -system-proxies .... Use system network proxies by default.

    -no-exceptions ..... Disable exceptions on compilers that support it.
 *  -exceptions ........ Enable exceptions on compilers that support it.

    -no-accessibility .. Do not compile Accessibility support.
 *  -accessibility ..... Compile Accessibility support.

    -no-stl ............ Do not compile STL support.
 *  -stl ............... Compile STL support.

    -no-sql-<driver> ... Disable SQL <driver> entirely.
    -qt-sql-<driver> ... Enable a SQL <driver> in the QtSql library, by default
                         none are turned on.
    -plugin-sql-<driver> Enable SQL <driver> as a plugin to be linked to
                         at run time.

                         Possible values for <driver>:
                         [  db2 ibase mysql oci odbc psql sqlite sqlite2 sqlite_symbian symsql tds ]

    -system-sqlite ..... Use sqlite from the operating system.

    -no-qt3support ..... Disables the Qt 3 support functionality.
 *  -qt3support ........ Enables the Qt 3 support functionality.

    -no-xmlpatterns .... Do not build the QtXmlPatterns module.
 +  -xmlpatterns ....... Build the QtXmlPatterns module.
                         QtXmlPatterns is built if a decent C++ compiler
                         is used and exceptions are enabled.

    -no-multimedia ..... Do not build the QtMultimedia module.
 +  -multimedia ........ Build the QtMultimedia module.

    -no-audio-backend .. Do not build the platform audio backend into QtMultimedia.
 +  -audio-backend ..... Build the platform audio backend into QtMultimedia if available.

    -no-phonon ......... Do not build the Phonon module.
 +  -phonon ............ Build the Phonon module.
                         Phonon is built if a decent C++ compiler is used.
    -no-phonon-backend.. Do not build the platform phonon plugin.
 +  -phonon-backend..... Build the platform phonon plugin.

    -no-svg ............ Do not build the SVG module.
 +  -svg ............... Build the SVG module.

    -no-webkit ......... Do not build the WebKit module.
 +  -webkit ............ Build the WebKit module.
                         WebKit is built if a decent C++ compiler is used.
    -webkit-debug ...... Build the WebKit module with debug symbols.

    -no-javascript-jit . Do not build the JavaScriptCore JIT compiler.
 +  -javascript-jit .... Build the JavaScriptCore JIT compiler.

    -no-script ......... Do not build the QtScript module.
 +  -script ............ Build the QtScript module.

    -no-scripttools .... Do not build the QtScriptTools module.
 +  -scripttools ....... Build the QtScriptTools module.

    -no-declarative ..... Do not build the declarative module.
 +  -declarative ....... Build the declarative module.

    -no-declarative-debug ..... Do not build the declarative debugging support.
 +  -declarative-debug ....... Build the declarative debugging support.

    -platform target ... The operating system and compiler you are building
                         on (linux-g++).

                         See the README file for a list of supported
                         operating systems and compilers.
    -graphicssystem <sys> Sets an alternate graphics system. Available options are:
                           raster - Software rasterizer
                           opengl - Rendering via OpenGL, Experimental!
                           openvg - Rendering via OpenVG, Experimental!


    -no-mmx ............ Do not compile with use of MMX instructions.
    -no-3dnow .......... Do not compile with use of 3DNOW instructions.
    -no-sse ............ Do not compile with use of SSE instructions.
    -no-sse2 ........... Do not compile with use of SSE2 instructions.
    -no-sse3 ........... Do not compile with use of SSE3 instructions.
    -no-ssse3 .......... Do not compile with use of SSSE3 instructions.
    -no-sse4.1.......... Do not compile with use of SSE4.1 instructions.
    -no-sse4.2.......... Do not compile with use of SSE4.2 instructions.
    -no-avx ............ Do not compile with use of AVX instructions.
    -no-neon ........... Do not compile with use of NEON instructions.

    -qtnamespace <name>  Wraps all Qt library code in 'namespace <name> {...}'.
    -qtlibinfix <infix>  Renames all libQt*.so to libQt*<infix>.so.

    -D <string> ........ Add an explicit define to the preprocessor.
    -I <string> ........ Add an explicit include path.
    -L <string> ........ Add an explicit library path.

    -help, -h .......... Display this information.

Third Party Libraries:

    -qt-zlib ........... Use the zlib bundled with Qt.
 +  -system-zlib ....... Use zlib from the operating system.
                         See http://www.gzip.org/zlib

    -no-gif ............ Do not compile GIF reading support.

    -no-libtiff ........ Do not compile TIFF support.
    -qt-libtiff ........ Use the libtiff bundled with Qt.
 +  -system-libtiff .... Use libtiff from the operating system.
                         See http://www.libtiff.org

    -no-libpng ......... Do not compile PNG support.
    -qt-libpng ......... Use the libpng bundled with Qt.
 +  -system-libpng ..... Use libpng from the operating system.
                         See http://www.libpng.org/pub/png

    -no-libmng ......... Do not compile MNG support.
    -qt-libmng ......... Use the libmng bundled with Qt.
 +  -system-libmng ..... Use libmng from the operating system.
                         See http://www.libmng.com

    -no-libjpeg ........ Do not compile JPEG support.
    -qt-libjpeg ........ Use the libjpeg bundled with Qt.
 +  -system-libjpeg .... Use libjpeg from the operating system.
                         See http://www.ijg.org

    -no-openssl ........ Do not compile support for OpenSSL.
 +  -openssl ........... Enable run-time OpenSSL support.
    -openssl-linked .... Enabled linked OpenSSL support.

    -ptmalloc .......... Override the system memory allocator with ptmalloc.
                         (Experimental.)

Additional options:

    -make <part> ....... Add part to the list of parts to be built at make time.
                         (libs tools examples demos docs translations)
    -nomake <part> ..... Exclude part from the list of parts to be built.

    -R <string> ........ Add an explicit runtime library path to the Qt
                         libraries.
    -l <string> ........ Add an explicit library.

    -no-rpath .......... Do not use the library install path as a runtime
                         library path.
 +  -rpath ............. Link Qt libraries and executables using the library
                         install path as a runtime library path. Equivalent
                         to -R install_libpath

    -continue .......... Continue as far as possible if an error occurs.

    -verbose, -v ....... Print verbose information about each step of the
                         configure process.

    -silent ............ Reduce the build output so that warnings and errors
                         can be seen more easily.

 *  -no-optimized-qmake ... Do not build qmake optimized.
    -optimized-qmake ...... Build qmake optimized.

    -no-gui ............ Don't build the Qt GUI library

    -no-nis ............ Do not compile NIS support.
 *  -nis ............... Compile NIS support.

    -no-cups ........... Do not compile CUPS support.
 *  -cups .............. Compile CUPS support.
                         Requires cups/cups.h and libcups.so.2.

 *  -no-iconv .......... Do not compile support for iconv(3).
    -iconv ............. Compile support for iconv(3).

    -no-pch ............ Do not use precompiled header support.
 *  -pch ............... Use precompiled header support.

    -no-dbus ........... Do not compile the QtDBus module.
 +  -dbus .............. Compile the QtDBus module and dynamically load libdbus-1.
    -dbus-linked ....... Compile the QtDBus module and link to libdbus-1.

    -reduce-relocations ..... Reduce relocations in the libraries through extra
                              linker optimizations (Qt/X11 and Qt for Embedded Linux only;
                              experimental; needs GNU ld >= 2.18).
make[1]: *** [build-only-qt_x86_64-w64-mingw32.static.posix] Error 1
make[1]: Leaving directory `/home/luca/Code/mxe.git'

real	1m8.705s
user	0m8.670s
sys	0m2.615s

**Comment by mabrand** [comment]
The answer is near the end:

    -no-system-sqlite: invalid command-line switch

**Comment by uwehermann** [comment]
qt builds fine for me on x86_64-w64-mingw32.static.posix, fresh MXE cloned today with only the following patch (due to bug #565):

```
--- a/src/qt.mk
+++ b/src/qt.mk
@@ -76,12 +76,12 @@ define $(PKG)_BUILD
     # lrelease (from linguist) needed to prepare translation files
     $(MAKE) -C '$(1)/tools/linguist/lrelease' -j '$(JOBS)' install

-    cd '$(1)/tools/assistant' && '$(1)/bin/qmake' assistant.pro
-    # can't figure out where -lQtCLucene comes from so use
-    # sed on the output instead of patching the input
-    $(MAKE) -C '$(1)/tools/assistant' sub-lib-qmake_all
-    $(SED) -i 's,-lQtCLucene$$,-lQtCLucene4,' '$(1)/tools/assistant/lib/Makefile.Release'
-    $(MAKE) -C '$(1)/tools/assistant' -j '$(JOBS)' install
+    ## cd '$(1)/tools/assistant' && '$(1)/bin/qmake' assistant.pro
+    ## # can't figure out where -lQtCLucene comes from so use
+    ## # sed on the output instead of patching the input
+    ## $(MAKE) -C '$(1)/tools/assistant' sub-lib-qmake_all
+    ## $(SED) -i 's,-lQtCLucene$$,-lQtCLucene4,' '$(1)/tools/assistant/lib/Makefile.Release'
+    ## $(MAKE) -C '$(1)/tools/assistant' -j '$(JOBS)' install
```
