### ISSUE TITLE
How can I un-install individual MXE package

### ISSUE THREAD

**Issue by hansni** [mxe/mxe#1257]
For example, I want to un-install the package of glib. It seems that none of "clean-*" target can do that.

**Comment by tonytheodore** [comment]
There is no way to do that with the normal MXE source builds. The git-based install tracking mechanism in #1243 may be used for such purposes in the future, but it's not likely in the short/mid-term.

If you're using an "apt" based system, you could try the binary packages at http://pkg.mxe.cc

**Comment by hansni** [comment]
Got it. Thanks
