### ISSUE TITLE
subversion can't be downloaded

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1261]
Log: https://gist.github.com/858b51c88c4ba3c96994

**Comment by mgerhardy** [comment]
WTF - they are deleting old versions from the mirrors... 1.9.3 is available there.

**Comment by mgerhardy** [comment]
it's not even available on http://archive.apache.org/dist/subversion/

**Comment by mgerhardy** [comment]
added the archive url like we did for the other apache projects

**Comment by starius** [comment]
Fixed.
