### ISSUE TITLE
Qt 5.6 undefined reference to `qt_static_plugin_QJp2Plugin()'

### ISSUE THREAD

**Issue by oaeide** [mxe/mxe#1262]
Hello. First of all, I am sorry og this is not a MXE issue. I had a working static build of Qt 5.5 on my Ubuntu box. Today I did a make clean and  make qt5 MXE_TARGETS='x86_64-w64-mingw32.static' 

This seemingly went fine (although I an not certain what the last line reading "[no-build] qt5" actually means..

When I try to compile my program, however I get this: 

> error: undefined reference to `qt_static_plugin_QJp2Plugin()'

The file project name_plugins_import.cpp contains

```
 // This file is autogenerated by qmake. It imports static plugin classes for
// static plugins specified using QTPLUGIN and QT_PLUGIN_CLASS.<plugin> variables.
#include <QtPlugin>
Q_IMPORT_PLUGIN(QWindowsPrinterSupportPlugin)
Q_IMPORT_PLUGIN(QWindowsIntegrationPlugin)
Q_IMPORT_PLUGIN(QDDSPlugin)
Q_IMPORT_PLUGIN(QICNSPlugin)
Q_IMPORT_PLUGIN(QICOPlugin)
Q_IMPORT_PLUGIN(QMngPlugin)
Q_IMPORT_PLUGIN(QTgaPlugin)
Q_IMPORT_PLUGIN(QTiffPlugin)
Q_IMPORT_PLUGIN(QWbmpPlugin)
Q_IMPORT_PLUGIN(QWebpPlugin)
Q_IMPORT_PLUGIN(QGeoPositionInfoSourceFactoryGeoclue)
Q_IMPORT_PLUGIN(QGeoPositionInfoSourceFactoryPoll)
Q_IMPORT_PLUGIN(QGenericEnginePlugin)
Q_IMPORT_PLUGIN(QNativeWifiEnginePlugin)
```

I.e no jp2. I have never even heard of jp2 before, I don't believe I use it... I include core, printsupport, xml, networking, widgets, gui,  positioning

**Comment by starius** [comment]
> error: undefined reference to `qt_static_plugin_QJp2Plugin()'

Which function uses `qt_static_plugin_QJp2Plugin()`? (This information may be in the error message.)

**Comment by oaeide** [comment]
:-1: error: collect2: error: ld returned 1 exit status

Is the only other thing there

**Comment by starius** [comment]
Can you provide source and build command, please?

**Comment by oaeide** [comment]
I'll make a minimum case when I get home I guess. I'm doing this from the QtCreator btw.

Commands:
qmake: qmake missionLogCMF.pro -r -spec win32-g++make -j 4 in /home/blu/dev/cmf-toolkit/build-missionLogCMF-qt_static-Release

**Comment by oaeide** [comment]
Could [this ](https://bugreports.qt.io/browse/QTBUG-49769)be relevant?

**Comment by pavelvat** [comment]
https://wiki.qt.io/New_Features_in_Qt_5.6

>For security reasons, the MNG and JPEG 2000 handlers will by default no longer be built, unless the corresponding codec libraries are provided by the OS. Hence, the binary Qt releases for Windows and Mac will not contain prebuilt handlers for those formats, but users can still build them from source. 

try this:
```make libmng openjpeg qt5 MXE_TARGETS='x86_64-w64-mingw32.static' ```

**Comment by pavelvat** [comment]
>The file project name_plugins_import.cpp contains

```
...
Q_IMPORT_PLUGIN(QMngPlugin)
...
```

**Comment by mabrand** [comment]
0a89a58bb7ed0a660f035ed479e199608933dc4d

It might help.

**Comment by oaeide** [comment]
Ok so i tried buildinf with pavelats command - no dice. Gonna try 0a89a58 now mabrand

**Comment by oaeide** [comment]
That works! Amazing support and response times. Thank you so much!
