### ISSUE TITLE
messages when using boost about deprecated headers

### ISSUE THREAD

**Issue by nzsquirrell** [mxe/mxe#1265]
Seeing this when compiling applications with boost 1.60.0:

mxe/usr/i686-w64-mingw32.static/include/boost/type_traits/detail/bool_trait_def.hpp:18:79: note: # pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
mxe/usr/i686-w64-mingw32.static/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")

is resolved by applying this patch to the boost include files - https://github.com/boostorg/iostreams/pull/15/commits/331e7b70dc3e0869194d0ecdc5dff0c8c8f471e7

**Comment by starius** [comment]
I have created a pull request which adds this patch: https://github.com/mxe/mxe/pull/1266
Please check if it fixes the warnings for you.

**Comment by starius** [comment]
ping
