### ISSUE TITLE
version of protobuf is too old

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1269]
```protobuf.mk``` currently have version 2.5.0 this leads to incompatibility when build of ```Clementine```: http://pastebin.com/Zr17VsL9
I tried to upgrade ```protobuf.mk``` to version 2.6.1 and encountered with a very strange problem http://pastebin.com/cb19jtvt
./autogen.sh trying to download http://googletest.googlecode.com/files/gtest-1.5.0.tar.bz2 and fail. ```gtest-1.5.0.tar.bz2``` is successfully downloaded through internet browser or command line (curl, wget), but it fail when downloading inside MXE.

Workaround for this problem:
```
wget http://googletest.googlecode.com/files/gtest-1.5.0.tar.bz2
tar fjx gtest-1.5.0.tar.bz2
wget https://github.com/google/protobuf/archive/2.6.1.tar.gz
tar fzx 2.6.1.tar.gz
cp -r protobuf-2.6.1/ protobuf-2.6.1.orig
cp -r gtest-1.5.0 protobuf-2.6.1/
diff -Naur protobuf-2.6.1.orig/ protobuf-2.6.1 > protobuf-1-fixes.patch
cp protobuf-1-fixes.patch /path/to/mxe/src/
```
clementine.exe was built and launched successfully.

The same problem with ```protobuf.mk``` version 3.0.0-beta-2, but with another link https://googlemock.googlecode.com/files/gmock-1.7.0.zip.

**Comment by starius** [comment]
MXE has [a protection](https://github.com/mxe/mxe/blob/c26f3225fba8ffe9dd54db759d4680a1314d350f/Makefile#L439) against (potentially unverified) downloads during building.

You should create package `gtest` and unpack its source while building `protobuf`. It can be done with macro `PREPARE_PKG_SOURCE`. For example, package `upx` [unpacks](https://github.com/mxe/mxe/blob/c26f3225fba8ffe9dd54db759d4680a1314d350f/src/upx.mk#L20) source of package `uxl`. Add `gtest` to dependencies of `protobuf`.
