### ISSUE TITLE
Other files than main.qml are 'not included' in the build so the resulting (.exe) application doesn't run.

### ISSUE THREAD

**Issue by hekri-d** [mxe/mxe#1294]
I don't know if this really is an issue or is there something I need to do that I'm not aware of but creating a 'Hello World' project with qtcreator (qt5.4 and 5.6) and crosscompiling it with mxe works fine. It works also with more complicated projects as long as there are no 'extra' files added to the project. By extra files I mean going to ..>Add New File in qtcreator and adding a foo.qml file to the project. In this case running mxe (i686...-qmake-qt5) creates a  the .exe file in the (by mxe created) release folder but that (.exe) file doesn't run with wine nor does it work on windows xp x32. No errors no warnings. Nothing.

It kinda seems like the added files are completely ignored. I tried to make sense out of the Make file generated by mxe but being new to this thing and to programming in general I couldn't find any obvious reason why other files than main.qml (which is created automatically by qtcreator) are ignored.

Edit. Tried creating a project with (qt5.4 with qtcreator) which includes  a ui file automatically but it didn't work either. So the problem is not only with files added (semi)manually but also with those created automatically.

**Comment by tonytheodore** [comment]
I haven't used qtcreator so can't be of much help. Is this an mxe-specific issue, what happens when you build the project natively?

If you can post an example of the *.pro file it may help investigating further.

**Comment by hekri-d** [comment]
I'm really sorry that I didn't reply earlier. I've missed the notification. First I'd like to apologize for not knowing any programming terminology. I'm not a real programmer just a mechanical engineering student doing little apps that I (and some colleagues) use to help us with homework and stuff.

Going back to my initial problem again.Now new projects created with qtcreator even with other files added do run. I don't know why they didn't at first! But I still can't build my actual project with mxe.

Here's the *.pro file of my project. It's nothing fancy I've just started it. 

[DMApp.txt](https://github.com/mxe/mxe/files/219416/DMApp.txt)

And here are the  qml.qrc and js.qrc files. Just in case they're relevant to the problem somehow.
[js.txt](https://github.com/mxe/mxe/files/219418/js.txt)
[qml.txt](https://github.com/mxe/mxe/files/219419/qml.txt)

Thank you for taking the time to read this. :)

**Comment by hekri-d** [comment]
Ok guys. I've looked a little bit more into this and it seems that not the files itself are the problem but the imported qt modules. This is reproducible (at least here in my installation of qt and mxe) by creating a new, simple, 'hello world' project and importing any modules that aren't imported by default. Like for example the QtQuick.Controls 1.3. Basically just adding "import QtQuick.Controls 1.3" in any of the *.qml files makes the application not start. It seems like it does compile but the resulting *.exe from the release directory doesn't run.

**Comment by tonytheodore** [comment]
Okay, I can see the same here. Apparently, you need to copy the `qml` subdirectories to the same directory as the *.exe and I can confirm that works. See here for more details:

https://wiki.qt.io/Deploy_an_Application_on_Windows

**Comment by tonytheodore** [comment]
I built the `qtquickcontrols2` example easily with:

```diff
diff --git a/src/qtquickcontrols2.mk b/src/qtquickcontrols2.mk
index e7fc90c..cd83f26 100644
--- a/src/qtquickcontrols2.mk
+++ b/src/qtquickcontrols2.mk
@@ -20,4 +20,8 @@ define $(PKG)_BUILD
     cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' CONFIG-='debug debug_and_release'
     $(MAKE) -C '$(1)' -j '$(JOBS)'
     $(MAKE) -C '$(1)' -j 1 install
+
+    cd '$(1)/examples' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' CONFIG-='debug debug_and_release'
+    $(MAKE) -C '$(1)/examples' -j '$(JOBS)'
+    $(MAKE) -C '$(1)/examples' -j 1 install
 endef
```

but no amount of copying directories can get it to actually run, let alone find the minimal set of required files.

A better strategy might be to find some sort of debugging mode that lists the paths it's searching for.

**Comment by hekri-d** [comment]
Thanks for the heads up. It seems like I'm going to have to find an old Wiondows 7 DVD that I got somewhere and put it on one of my computers.
