### ISSUE TITLE
package libical is broken

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1302]
Commit: a7e50dbde1deeaf3a8b104b9094a46c3625dce28
Log: https://gist.github.com/8ba59cde9a8f0b9d9b70f5b1a1eb9753
It can be related to https://github.com/mxe/mxe/pull/1290 (cmake update).

**Comment by tonytheodore** [comment]
I don't think it's related to cmake update, I've had a successful full build after that: https://gist.github.com/tonytheodore/80fa8c20e0700ef43b070346f41e65fc

**Comment by tonytheodore** [comment]
Only difference in logs appears to be `-- Looking for include file dlfcn.h - not found` on Wheezy.

**Comment by starius** [comment]
It is a [known race](https://github.com/libical/libical/issues/219). File `icalderivedvalue.h` and some other generated files were not included into generated file `ical.h`. Compare file `ical.h` from the [broken build](https://gist.github.com/starius/019884bfc6e9fc59841ddca57ef03680#file-bad-ical-h) and from the [working build](https://gist.github.com/starius/019884bfc6e9fc59841ddca57ef03680#file-good-ical-h).

This issue was fixed in https://github.com/libical/libical/commit/dcc40c7ae2d337a0d83c077bf9d8f283499c6717 (issue https://github.com/libical/libical/issues/219 ). I tried to update `libical` to version 2.0.0, but it doesn't compile and requires some patching.
