### ISSUE TITLE
dll files in lib/

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1311]
After https://github.com/mxe/mxe/pull/1210 some dll files was built and installed to mxe/usr/i686-w64-mingw32.shared/lib/:
```
$ find /home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/lib/ -name *.dll
/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/lib/aspell-0.60/tex-filter.dll
/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/lib/aspell-0.60/texinfo-filter.dll
/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/lib/aspell-0.60/nroff-filter.dll
/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/lib/aspell-0.60/context-filter.dll
/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/lib/aspell-0.60/email-filter.dll
/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/lib/aspell-0.60/sgml-filter.dll
```

**Comment by starius** [comment]
Is `bin/aspell-0.60/*.dll` the correct place or these files?

**Comment by pavelvat** [comment]
I don't know.

**Comment by TimothyGu** [comment]
I believe they are so-called "plugins," that instead of being linked to, are loaded at runtime. I believe the convention is to leave them in `lib/`.

**Comment by pavelvat** [comment]
>I believe they are so-called "plugins," that instead of being linked to, are loaded at runtime. I believe the convention is to leave them in lib/.

Ok.
