### ISSUE TITLE
How to build debug version of qt5

### ISSUE THREAD

**Issue by und3f** [mxe/mxe#1316]
I need to cross compile qt5 application with debug symbols

But i got next error:
`make[1]: *** No rule to make target '/dev/mxe/usr/i686-w64-mingw32.static.debug/qt5/lib/libQt5Widgetsd.a', needed by 'debug/app.exe'.  Stop.`

How to build libQt5Widgetsd?

**Comment by tonytheodore** [comment]
In the short term, you can do something like:
```diff
diff --git a/src/qt-test.pro b/src/qt-test.pro
index fd4f55b..992a9cd 100644
--- a/src/qt-test.pro
+++ b/src/qt-test.pro
@@ -9,3 +9,4 @@ HEADERS += qt-test.hpp
 SOURCES += qt-test.cpp
 FORMS   += qt-test.ui
 RESOURCES += qt-test.qrc
+CONFIG += release
diff --git a/src/qtbase.mk b/src/qtbase.mk
index e4575be..8180937 100644
--- a/src/qtbase.mk
+++ b/src/qtbase.mk
@@ -33,7 +33,7 @@ define $(PKG)_BUILD
             -device-option PKG_CONFIG='${TARGET}-pkg-config' \
             -force-pkg-config \
             -no-use-gold-linker \
-            -release \
+            -debug-and-release \
             -static \
             -prefix '$(PREFIX)/$(TARGET)/qt5' \
             -no-icu \
@@ -62,7 +62,7 @@ define $(PKG)_BUILD

     # invoke qmake with removed debug options as a workaround for
     # https://bugreports.qt-project.org/browse/QTBUG-30898
-    $(MAKE) -C '$(1)' -j '$(JOBS)' QMAKE="$(1)/bin/qmake CONFIG-='debug debug_and_release'"
+    $(MAKE) -C '$(1)' -j '$(JOBS)' #QMAKE="$(1)/bin/qmake CONFIG-='debug debug_and_release'"
     rm -rf '$(PREFIX)/$(TARGET)/qt5'
     $(MAKE) -C '$(1)' -j 1 install
     ln -sf '$(PREFIX)/$(TARGET)/qt5/bin/qmake' '$(PREFIX)/bin/$(TARGET)'-qmake-qt5
```

however that isn't ideal and the workaround for QTBUG-30898 needs to be revisited.

**Comment by tonytheodore** [comment]
So it seems the options to `configure` are very counter-intuitive:
 - `-release` *.pc files created with `d` suffix on lib names
 - `-debug-and-release` without suffix
 - `-debug` without suffix

I doubt `-debug-and-release` is really useful (for MXE) so getting the distinct options working is the first step.

**Comment by starius** [comment]
Does `-debug-and-release` produce optimized binaries with debug info? MXE seems to use this mode for other packages.

**Comment by tonytheodore** [comment]
> Does -debug-and-release produce optimized binaries with debug info?

It produces two sets of libs, one with a `d` suffix, but it's apparently not supported:

```
WARNING: -debug-and-release is not supported outside of Mac OS X.
Qt can be built in release mode with separate debug information, so
-debug-and-release is not necessary anymore
```

There are some other options like:

```
    -force-debug-info .. Create symbol files for release builds.

 *  -no-separate-debug-info . Do not store debug information in a separate file.
    -separate-debug-info .... Strip debug information into a separate file.

 *  -no-optimized-tools ... Do not build optimized host tools even in debug build.
    -optimized-tools ...... Build optimized host tools even in debug build.
```

but I'm not familiar with what they really do. The `-separate-debug-info` isn't compatible with static builds.

> MXE seems to use this mode for other packages.

I was mostly thinking along the lines of adding support for separate debug targets (#301) so the builds are completely isolated from each other.

**Comment by tonytheodore** [comment]
@und3f, can you test #1330 and let us know how it goes?

**Comment by und3f** [comment]
@tonytheodore everything works perfectly.
