### ISSUE TITLE
mingw-w64 v5.0

### ISSUE THREAD

**Issue by avih** [mxe/mxe#1321]
Currently the 5.0 branch of mingw-w64 is at 5.0-rc2 (from about a month ago). I tried it locally using this:

``` diff
diff --git a/src/mingw-w64.mk b/src/mingw-w64.mk
index 5bdaf53..7c88f4c 100644
--- a/src/mingw-w64.mk
+++ b/src/mingw-w64.mk
@@ -3,8 +3,8 @@

 PKG             := mingw-w64
 $(PKG)_IGNORE   :=
-$(PKG)_VERSION  := 4.0.6
-$(PKG)_CHECKSUM := 0c407394b0d8635553f4fbca674cdfe446aac223e90b4010603d863e4bdd015c
+$(PKG)_VERSION  := 5.0-rc2
+$(PKG)_CHECKSUM := 8981d1d6d2281e6069afe8d7015157c25dca627fee8e032372f100897c56ad46
 $(PKG)_SUBDIR   := $(PKG)-v$($(PKG)_VERSION)
 $(PKG)_FILE     := $(PKG)-v$($(PKG)_VERSION).tar.bz2
 $(PKG)_URL      := http://$(SOURCEFORGE_MIRROR)/project/$(PKG)/$(PKG)/$(PKG)-release/$($(PKG)_FILE)
```

And also removed the patch `src/mingw-w64-1.patch` since 5.0-rc2 seems to have similar code to what the patch adds, and got the following packages built cleanly:

```
$ ls usr/i686-w64-mingw32.static/installed/
binutils            harfbuzz      libpng        pthreads
bzip2               icu4c         libvpx        sdl
cairo               jpeg          libxml2       speex
dbus                lame          luajit        theora
dlfcn-win32         lcms          lzo           tiff
expat               libarchive    mingw-w64     vidstab
ffmpeg              libass        mpg123        vo-amrwbenc
fontconfig          libbluray     mxe-conf      vorbis
freetype            libbs2b       nettle        x264
freetype-bootstrap  libffi        ogg           xvidcore
fribidi             libgcrypt     opencore-amr  xz
gcc                 libgnurx      openssl       yasm
gettext             libgpg_error  opus          zlib
glib                libiconv      pcre
gmp                 libidn        pixman
gnutls              liblsmash     pkgconf
```

As well as `libmfx`, `uchardet` and `mpv`(not part of MXE), and `mpv` seems to work just fine. So far everything seems to work out of the box for me with 5.0-rc2 (my `ffmpeg` is master rather than from MXE, and configured to use `libmfx`).

The 5.0 branch has some improvement over 4.0.6, at the very least with support for hardware decoding of h265 videos (via the directx headers) - which the 4.0.x branch lacks.

FYI.

**Comment by sofakng** [comment]
Thanks for this!  I was wondering why I couldn't enable D3D11 support in FFmpeg and traced it to the MinGW-w64 headers.  I'm going to try 5.0-rc2 and see how it works.

**Comment by avih** [comment]
Final 5.0.0 has been released about a week ago, and I've been using it since without issues. My tests are limited to same usage as the first comment, and like 5.0rc2, it also doesn't seem to need `src/mingw-w64-1.patch`.

That's the new info for `src/mingw-w64.mk`:
```
$(PKG)_VERSION  := 5.0.0
$(PKG)_CHECKSUM := e41d8ca739e22b4215c8ebe99ed2fc398c734cae73877f3143c394661b096d08
```

FYI.

**Comment by tonytheodore** [comment]
updated in #1613
