### ISSUE TITLE
Unable to compile libtorrent 1.1

### ISSUE THREAD

**Issue by TbtBI** [mxe/mxe#1331]
Here configure log - https://gist.github.com/TbtBI/06b0249479b458a3ce15d47faab47b4e
Here make log -https://gist.github.com/TbtBI/cbf83472985b5290881251c732cf8554
Can someone tell me how to fix it?

**Comment by tonytheodore** [comment]
We're still compiling with WinXP support, so some functions use the older names. Adding `CXXFLAGS='-D_WIN32_WINNT=0x0501'`will fix it.

See #1336, the x86_64-w64-mingw32.static is broken in another way.

**Comment by TbtBI** [comment]
Thanks for the reply.
 WIth changes from #1336 returns error - https://gist.github.com/TbtBI/36c85d81b849a6af95dd31434ec4f716
x86_64-w64-mingw32.static also returns error - configure (https://gist.github.com/TbtBI/599a6315eb1b47660fbeeedd707690fa) and make (https://gist.github.com/TbtBI/c65da614910dd9f11994f49d54608148)
i686-w64-mingw32.static - configure (https://gist.github.com/TbtBI/cf5bc41ceaf40f3e75df0a7e8aef3438) and make (https://gist.github.com/TbtBI/3a06169b900ebf2dd4f60308c2286f69)
qBittorrent returns error - configure (https://gist.github.com/TbtBI/686b48e0a2127951216249f4e984f3d5) and make (https://gist.github.com/TbtBI/2e4cf562def531488dcc6a91797f213e). How to fix that error?

**Comment by tonytheodore** [comment]
Fixed in #1336.
