### ISSUE TITLE
deactivate optional dependencies of library

### ISSUE THREAD

**Issue by rkanavath** [mxe/mxe#1334]
It is not possible now to deactive some of dependencies of library in the current mxe build.

For example, take the case of qt4

make qt; will build qt4 with as much as modules enabled. This is good as we don't know if the user/developer using mxe needs just a QtCore, QtCore+QtGui or all of them. so "all components" enabled build will keep on the "safe" side.

I like to discuss the possibility of having a configuration settings( perhaps in settings.mk) to disable this.

so if there is NO_WEBKIT set in settings.mk the all packages (qt4 & qt5) building webkit will skip this!

this can also be a dependency. eg: freetype and harfbuzz

if NO_HARFBUZZ set then freetype or any other package using this dependency will be able to do produce a build of the package without harfbuzz. by default all are included. 

so no issue of breaking existing packages.

**Comment by TobiX** [comment]
Please take a look at plugins: https://github.com/mxe/mxe/blob/master/plugins/examples/custom-qt-min/overrides.mk

**Comment by rkanavath** [comment]
Excellent!. I will give this a try and let you know.

**Comment by rkanavath** [comment]
How do I deal with patches in the overrides.mk?

**Comment by tonytheodore** [comment]
Plugins finally have docs! See https://github.com/mxe/mxe/tree/master/plugins#creating-plugins for notes on patches.
