### ISSUE TITLE
libxslt compilation as shared target do not work

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#1343]
With In 32 bits static target no problem :

[download]  libxslt                                                                                       
[build]     libxslt                i686-w64-mingw32.static                                                
[done]      libxslt                i686-w64-mingw32.static                                 30976 KiB      0m11.755s

with 64 bits shared target nothing is compiled :

[download]  libxslt                                                                                       
[no-build]  libxslt                i686-w64-mingw32.shared 

It's reproducible in 64 bits.

Build log :

[gilles@localhost 20160509_184938]$ cat ./libxslt_i686-w64-mingw32.shared 
make[1]: Entering directory '/mnt/devel/GIT/5.x/project/mxe/build'
touch '/mnt/devel/GIT/5.x/project/mxe/build/usr/i686-w64-mingw32.shared/installed/libxslt'
make[1]: Leaving directory '/mnt/devel/GIT/5.x/project/mxe/build'

real    0m2.713s
user    0m2.658s
sys     0m0.019s

**Comment by tonytheodore** [comment]
Shared build enabled in #1344.

BTW, there's a [build matrix](http://mxe.cc/build-matrix.html) that details the current status of packages.

**Comment by cgilles** [comment]
Thanks for the info. I try it now.

Gilles Caulier

**Comment by cgilles** [comment]
I just tested and libxslt compile fine now as shared library.

Thanks for the fix

Gilles Caulier

**Comment by tonytheodore** [comment]
> I just tested and libxslt compile fine now as shared library.

Thanks.
