### ISSUE TITLE
Is it possible to add package liblastfm in MXE from non original git repo?

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1356]
https://github.com/davidsansome/liblastfm

**Comment by tonytheodore** [comment]
There's nothing wrong in principle with using a fork, however both appear to be unmaintained. How about https://github.com/lastfm/liblastfm ?

**Comment by pavelvat** [comment]
>There's nothing wrong in principle with using a fork, however both appear to be unmaintained

Ok. I need liblastfm library for https://github.com/clementine-player/Clementine

https://github.com/davidsansome/liblastfm is maintained by main author of Clementine, it may contain some specific functionality required for Clementine.
