### ISSUE TITLE
Plugins and patches

### ISSUE THREAD

**Issue by rr-** [mxe/mxe#1365]
After the user overrides package signature with a plugin using `MXE_PLUGIN_DIRS` variable, upstream patches are still applied normally.

This is bad - for example, `make gcc MXE_PLUGIN_DIRS=plugins/gcc6` with `gcc-2.patch` proposed in #1362, which is meant for 4.9.3, will result in conflicts. For this reason, users should be able to control patches from within plugins as well.

A simple way to implement this would be to expose additional package-level variable containing list of patches in sequential order. If there's no such variable, mxe would search for patches on its own like it does now. This approach is backwards compatible, and allows to freely manipulate patches at will.

In #935 it's mentioned that this feature is already supported, but there is no mention of how to do this, and I haven't found any substantial clues in the `plugins/` directory either. Apparently, the user needs to put a `.patch` files to override default behavior, but this is flawed - what if the user wants to remove all upstream patches? In that case, they'd need to add empty dummy patch, which is kind of silly.

**Comment by tonytheodore** [comment]
> A simple way to implement this would be to expose additional package-level variable containing list of patches in sequential order. If there's no such variable, mxe would search for patches on its own like it does now.

Sounds like a nice way to handle it, a minimal working example is:

```diff
diff --git a/Makefile b/Makefile
index 2edab45..ab61761 100644
--- a/Makefile
+++ b/Makefile
@@ -190,7 +190,11 @@ UNPACK_PKG_ARCHIVE = \
 # all files for extension plugins will be considered for outdated checks
 PKG_MAKEFILES = $(realpath $(sort $(wildcard $(addsuffix /$(1).mk, $(TOP_DIR)/src $(MXE_PLUGIN_DIRS)))))
 PKG_TESTFILES = $(realpath $(sort $(wildcard $(addsuffix /$(1)-test*, $(TOP_DIR)/src $(MXE_PLUGIN_DIRS)))))
-PKG_PATCHES   = $(realpath $(sort $(wildcard $(addsuffix /$(1)-[0-9]*.patch, $(TOP_DIR)/src $(MXE_PLUGIN_DIRS)))))
+# allow packages to specify a list of zero or more patches
+PKG_PATCHES   = $(if $(findstring undefined,$(origin $(1)_PATCHES)), \
+                    $(realpath $(sort $(wildcard $(addsuffix /$(1)-[0-9]*.patch, $(TOP_DIR)/src $(MXE_PLUGIN_DIRS))))) \
+                $(else), \
+                    $($(1)_PATCHES))

 define PREPARE_PKG_SOURCE
     cd '$(2)' && $(call UNPACK_PKG_ARCHIVE,$(1))
```

I'll work on it alongside/after #1418.

**Comment by tonytheodore** [comment]
Merged now, see the usage notes at https://github.com/mxe/mxe/tree/master/plugins#creating-plugins.
