### ISSUE TITLE
qt5 is broken

### ISSUE THREAD

**Issue by Majestio** [mxe/mxe#1385]
logs:
`...
...
rm -f ../../../lib/libQt5Bootstrap.a
ar cqs ../../../lib/libQt5Bootstrap.a .obj/qlatincodec.o .obj/qtextcodec.o .obj/qutfcodec.o .obj/qglobal.o .obj/qlogging.o .obj/qmalloc.o .obj/qnumeric.o .ob
gmake[4]: выход из каталога «/usr/home/majestio/Dev/cross/mxe/tmp-qtbase-x86_64-w64-mingw32.shared/qtbase-opensource-src-5.6.0/src/tools/bootstrap»
cd tools/moc/ && ( test -e Makefile || /usr/home/majestio/Dev/cross/mxe/tmp-qtbase-x86_64-w64-mingw32.shared/qtbase-opensource-src-5.6.0/bin/qmake CONFIG-='d
cd tools/rcc/ && ( test -e Makefile || /usr/home/majestio/Dev/cross/mxe/tmp-qtbase-x86_64-w64-mingw32.shared/qtbase-opensource-src-5.6.0/bin/qmake CONFIG-='d
gmake[4]: вход в каталог «/usr/home/majestio/Dev/cross/mxe/tmp-qtbase-x86_64-w64-mingw32.shared/qtbase-opensource-src-5.6.0/src/tools/rcc»
gmake[4]: вход в каталог «/usr/home/majestio/Dev/cross/mxe/tmp-qtbase-x86_64-w64-mingw32.shared/qtbase-opensource-src-5.6.0/src/tools/moc»
clang++ -c -pipe -O2 -std=c++11 -fno-exceptions -Wall -W -pthread -D_THREAD_SAFE -fPIC -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_TSLIB -DQT_NO_LIBI
clang++ -c -pipe -O2 -std=c++11 -fno-exceptions -Wall -W -pthread -D_THREAD_SAFE -fPIC -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_TSLIB -DQT_NO_LIBI
clang++ -c -pipe -O2 -std=c++11 -fno-exceptions -Wall -W -pthread -D_THREAD_SAFE -fPIC -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_TSLIB -DQT_NO_LIBI
clang++ -c -pipe -O2 -std=c++11 -fno-exceptions -Wall -W -pthread -D_THREAD_SAFE -fPIC -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_TSLIB -DQT_NO_LIBI
clang++ -pthread -o ../../../bin/rcc .obj/rcc.o .obj/main.o   -L/usr/local/lib -L/usr/home/majestio/Dev/cross/mxe/tmp-qtbase-x86_64-w64-mingw32.shared/qtbase
.obj/rcc.o: In function `RCCResourceLibrary::readFiles(bool, QIODevice&)':
rcc.cpp:(.text+0x4663): undefined reference to `QString::operator=(QLatin1String)'
.obj/main.o: In function `createProject(QString const&)':
main.cpp:(.text+0x2f4): undefined reference to `QString::operator=(QLatin1String)'
.obj/main.o: In function `runRcc(int, char**)':
main.cpp:(.text+0x17c3): undefined reference to `QString::operator=(QLatin1String)'
main.cpp:(.text+0x19d1): undefined reference to `QString::operator=(QLatin1String)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
...
...`

**Comment by tonytheodore** [comment]
Could you post a link to the full log (preferably as a gist)?

**Comment by Majestio** [comment]
Full log : http://pastebin.com/LP5r2fmv

**Comment by tonytheodore** [comment]
I suspect it's finding `-lQt5Bootstrap` in `/usr/local/lib` instead of the one that has just been compiled.

**Comment by Majestio** [comment]
Hm, exactly the same steps for Funtoo Linux (except libmysqlclient) allowed to build successful.

**Comment by tonytheodore** [comment]
Do you have a native Qt5 installed on the Linux system? Can you check if there's a `Qt5Bootstrap` in `/usr/local/lib` on FreeBSD and rename it, or maybe try something like what happens with the below:

```diff
diff --git a/src/qtbase.mk b/src/qtbase.mk
index d803d19..66b9b43 100644
--- a/src/qtbase.mk
+++ b/src/qtbase.mk
@@ -19,6 +19,7 @@ define $(PKG)_UPDATE
 endef

 define $(PKG)_BUILD
+    $(SED) -i '/QMAKE_LIBDIR/d' '$(1)/mkspecs/freebsd-clang/qmake.conf'
     # ICU is buggy. See #653. TODO: reenable it some time in the future.
     cd '$(1)' && \
         OPENSSL_LIBS="`'$(TARGET)-pkg-config' --libs-only-l openssl`" \
```

**Comment by Majestio** [comment]
I remembered the difference really be installed on Linux and FreeBSd occurs. Linux: 1) installs mxe 2) installs Qt from Installer. On FreeBSD in reverse order 1) installing native Qt5 from the ports collection 2) attempt to install mxe qt5

Trying your patch...

**Comment by Majestio** [comment]
tonytheodore, thank you very much! All are built on the FreeBSD 10.3 to the eight goals: i866/x86_64/shared/static/win/posix

As a result, I use: 
1) this patch
2) http://github.com/mxe/mxe/issues/1355
3) https://github.com/mxe/mxe/issues/1347
