### ISSUE TITLE
error when linking against dbus+poppler: multiple definition of `DllMain@12'

### ISSUE THREAD

**Issue by darealshinji** [mxe/mxe#1388]
Linking a program against dbus and poppler results in the following error:

```
mxe/usr/i686-w64-mingw32.static/lib/libdbus-1.a(libdbus_1_la-dbus-sysdeps-thread-win.o):dbus-sysdeps-thread-win.c:(.text+0x32): multiple definition of `DllMain@12'
mxe/usr/i686-w64-mingw32.static/lib/libpoppler.a(libpoppler_la-GlobalParams.o):GlobalParams.cc:(.text+0x290): first defined here
```

Adding `-Wl,--allow-multiple-definition` resolves it and so far the linked program seems to work fine. But I still wanted to report this issue.

**Comment by starius** [comment]
Sources:

  * [poppler/GlobalParams.cc](https://gist.github.com/cfad7718d7ff68bc9e7243ecd2b9a193#file-globalparams-cc-L155)
  * [dbus/dbus-sysdeps-thread-win.c](https://gist.github.com/b85662738a0b5098e096a573425f293a#file-dbus-sysdeps-thread-win-c-L74)

AFAIK, DllMain is not needed in static build.

Can we preprocess out these functions in static builds?

Which macro can be used to determine if the build is static/shared?

**Comment by darealshinji** [comment]
Taking a look at the build logs reveals that `-DDBUS_STATIC_BUILD` is added for dbus. Otherwise, since both packages are using autoconf, `-DDLL_EXPORT -DPIC` is automatically added for dll builds but not for static builds.
So maybe something like this can be used:
``` diff
--- orig/dbus-sysdeps-thread-win.c
+++ dbus-sysdeps-thread-win.c
@@ -61,6 +61,8 @@
   return dbus_dll_hmodule;
 }
 
+#ifndef DBUS_STATIC_BUILD
+
 #ifdef DBUS_WINCE
 #define hinst_t HANDLE
 #else
@@ -105,6 +107,8 @@
   return TRUE;
 }
 
+#endif /* !DBUS_STATIC_BUILD */
+
 DBusCMutex *
 _dbus_platform_cmutex_new (void)
 {
--- orig/GlobalParams.cc
+++ GlobalParams.cc
@@ -150,6 +150,7 @@
 
 static HMODULE hmodule;
 
+#ifdef DLL_EXPORT
 extern "C" {
 BOOL WINAPI
 DllMain (HINSTANCE hinstDLL,
@@ -166,6 +167,7 @@
   return TRUE;
 }
 }
+#endif /* DLL_EXPORT */
 
 static const char *
 get_poppler_datadir (void)
```
