### ISSUE TITLE
InitializeConditionVariable on XP when adding sql to project

### ISSUE THREAD

**Issue by Ahrotahn** [mxe/mxe#1394]
I'm able to successfully compile my program and have it run correctly on xp+ until I add `QT += sql` to my project file.  It's able to run fine in wine and later versions of windows, but xp throws an error:
`The procedure entry point InitializeConditionVariable could not be located in the dynamic link library KERNEL32.dll`

I tried adding `DEFINES += WINVER=0x0501` and `DEFINES += _WIN32_WINNT=0x0501` with no change.  Qtbase seems to have the -no-icu flag set so I'm not sure what else could be causing the issue.  

The problem can be reproduced by creating a new widget application in qtcreator and add `QT += sql` to the project.

**Comment by scorpio810** [comment]
I have the same problem only for  Windows XP with cross compil mxe, it run perfect if I build  with qmake and mingw32-make on virtualbox seven !

**Comment by Ahrotahn** [comment]
After searching online for similar issues I found that other people had issues with newer versions of the mysql connector working on xp.  Since I only needed Postgresql for my program I rebuilt qtbase changing lines 45-50 in qtbase.mk from:
```
            -plugin-sql-mysql \
            -mysql_config $(PREFIX)/$(TARGET)/bin/mysql_config \
            -plugin-sql-sqlite \
            -plugin-sql-odbc \
            -plugin-sql-psql \
            -plugin-sql-tds -D Q_USE_SYBASE \
```
to:
```
            -no-sql-mysql \
            -no-sql-sqlite \
            -no-sql-tds \
            -plugin-sql-odbc \
            -plugin-sql-psql \
```

Now my program runs fine on xp.  When I get some more time I'll dig into the mysql stuff to see if anything can be done to make that work.

**Comment by scorpio810** [comment]
I only needed sqlite for my program, strange.

**Comment by scorpio810** [comment]
If I remember after October 2015, binaries produced by mxe caused this error and not before.
No time and nor the desire to compile in a Windows only for my QElectroTech on XP users.
It's too long.

**Comment by scorpio810** [comment]
Thank you my program run fine too on XP

            -no-sql-mysql \
            -plugin-sql-sqlite \
            -plugin-sql-odbc \
            -plugin-sql-psql \
            -no-sql-tds \

**Comment by tonytheodore** [comment]
Note you can override build options:

```
make qtbase qtbase_CONFIGURE_OPTS='-no-sql-tds -no-sql-mysql'
```
