### ISSUE TITLE
Qt 5.6-LTS vs Qt 5.7

### ISSUE THREAD

**Issue by tehnick** [mxe/mxe#1396]
Which version of Qt5 should we prefer in the next update of the packages?
There are some pros and cons for each of them.

Related news:
http://blog.qt.io/blog/2016/06/08/qt-5-6-1-released/
http://blog.qt.io/blog/2016/06/16/qt-5-7-released/

**Comment by lawipac** [comment]
5.7 is better, even though 5.6 is LTS, as QtQuickControl only works with 5.7 when 'static' built.

**Comment by lawipac** [comment]
if possible, can we have two branches, one for LTS, the other for latest.

**Comment by tehnick** [comment]
Probably this is possible to do as a plugin. But I am not sure that it is worth efforts.

**Comment by mabrand** [comment]
Hi, I also think 5.7 is the right choice. I'm working on an update for MXE now.

**Comment by mabrand** [comment]
341bca52d5399403a2faa6efe225a3313225b392

No big problems. -freetype and -fontconfig don't work now, so I disabled these options. I'm not sure if they produce useful features anyway. Anybody know about this?

**Comment by tehnick** [comment]
@mabrand 
> -freetype and -fontconfig don't work now, so I disabled these options

I think this is a bad idea. Please try #1400 instead.
