### ISSUE TITLE
automatically reporting feedback for build failures

### ISSUE THREAD

**Issue by woncount** [mxe/mxe#140]
been thinking about the idea mentioned previously:

> like I mentioned earlier, it would be great if the toplevel Makefile could be extended such 
> that failed log reports can optionally be sent automatically to either the mailing list or the 
> some other dedicated address, so that feedback can be more easily provided

What about using wget/curl to simply make a POST request to upload failed logs to a pastebin like codepad.org ? We could have mxe.codepad.org: http://codepad.org/mkproj

And then the makefile could also post important version info (autotools, cmake) plus the log with the error message to codepad

That would be a good way to collect feedback for different distros

What do you think ?

**Comment by tonytheodore** [comment]
perennial issue
