### ISSUE TITLE
names of targets (question to MXE developers)

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1411]
How about to change name of target according to rule from mingw-w64 project (https://sourceforge.net/projects/mingw-w64/) and provide some additional targets without official support:
replace `<triplet>.<link>.<threads>` to `<triplet>.<link>.<threads>.<exceptions>` (or to `<triplet>.<threads>.<exceptions>.<link>`)

Currently targets with official MXE support (`<threads>` is hidden for win32 threads model):

```
i686-w64-mingw32.static
i686-w64-mingw32.shared
x86_64-w64-mingw32.static
x86_64-w64-mingw32.shared
```

Currently targets without official MXE support:

```
i686-w64-mingw32.static.posix
i686-w64-mingw32.shared.posix
x86_64-w64-mingw32.static.posix
x86_64-w64-mingw32.shared.posix
```

New names of targets:
targets with official MXE support:

```
i686-w64-mingw32.static.win32.sjlj
i686-w64-mingw32.shared.win32.sjlj
x86_64-w64-mingw32.static.win32.seh
x86_64-w64-mingw32.shared.win32.seh
```

targets without official MXE support:

```
i686-w64-mingw32.static.win32.dwarf
i686-w64-mingw32.shared.win32.dwarf
x86_64-w64-mingw32.static.win32.sjlj
x86_64-w64-mingw32.shared.win32.sjlj

i686-w64-mingw32.static.posix.sjlj
i686-w64-mingw32.shared.posix.sjlj
x86_64-w64-mingw32.static.posix.seh
x86_64-w64-mingw32.shared.posix.seh

i686-w64-mingw32.static.posix.dwarf
i686-w64-mingw32.shared.posix.dwarf
x86_64-w64-mingw32.static.posix.sjlj
x86_64-w64-mingw32.shared.posix.sjlj
```

**Comment by starius** [comment]
Is it true that `win32`/`posix` regulates only whether libgcc comes with C++11 and C11 multithreading features? If it is true, why not to use `posix` as a default (or even the only) variant?

**Comment by tonytheodore** [comment]
There's a [nice summary by rubenvb regarding win32/posix threads](http://stackoverflow.com/questions/17242516/mingw-w64-threads-posix-vs-win32/30390278#30390278).

At some point in the past, there were [performance implications with C11 features](https://wiki.qt.io/MinGW-64-bit#GCC_Threading_model_.28posix_vs_win32.29), but I doubt they would affect our choice of default. The main reason we'd leave it as an option is that I suspect most users would prefer a more flexible toolchain than a large set of supported packages. Someone will find (say) the extra `winpthreads` dependency an issue and it's a worthy goal to support different options.

This has worked before (in #1019) and the "ugly" build rules don't actually seem so bad after six months;). The main holdup is determining (and documenting) a consistent approach to handling variants/customisation.

**Comment by starius** [comment]
There is a [project](https://github.com/meganz/mingw-std-threads) adding support of C++11 threading features to MinGW-w64 without dependency on pthreads. It is a simple header-only implementation of thread, mutex and convar which calls native Windows functions directly. Can we add it to enable C++ threading features on all targets?

**Comment by tehnick** [comment]
> Is it true that `win32`/`posix` regulates only whether libgcc comes with C++11 and C11 multithreading features? If it is true, why not to use `posix` as a default (or even the only) variant?

Now the time for such change [has come](https://github.com/mxe/mxe/issues/2258#issuecomment-450441252).

BWT, I failed to understand what is this issue about. Could anyone explain it in other words than in description?

**Comment by tonytheodore** [comment]
I think the issue is about:
  - adding support for exception handling variants (#1664)
  - using more explicit/consistent naming

The MinGW-w64 project doesn't really have to choose a default, so they can just produce every combination of toolchain. For mxe, we can't test those across all packages so the defaults become important.

That said, my [current thinking](https://github.com/mxe/mxe/pull/2208#issuecomment-422349529) is to have target names like:
```
  x86_64-w64-mingw32.static.gcc8
  i686-w64-mingw32.static.gcc7
```
and maybe even
```
  x86_64-w64-mingw32.static.gcc8.ucrt
  i686-w64-mingw32.static.gcc7.msvcrt
```

**Comment by pavelvat** [comment]
After https://github.com/mxe/mxe/pull/1664 and https://github.com/mxe/mxe/pull/2263 this  issue can be closed.

>using more explicit/consistent naming

It was proposed to explicitly indicate the exception handling variants in the name of the target.
