### ISSUE TITLE
Move package metadata from index.html to src/*.mk

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1422]
Following on from #638, I'd like to move all package metadata back to the relevant package makefiles and generate a (say) `.json` manifest to populate the list of packages. With 400 odd packages, it's not feasible to maintain a manually sorted list in html.

First pass of moving "name" and "website" is reasonably straightforward.

The next passes of:
- unifying `build-matrix`
- extending the matrix for future target specs (threads, exceptions, compiler [gcc\* | clang])
- incorporating `tools/install-deps`
- ..."json-ify" all shared lists (doesn't have to be json)

warrant a coherent approach.

@TimothyGu, @TobiX, do you want to tackle this?

**Comment by starius** [comment]
I sent PR https://github.com/mxe/mxe/pull/1602
