### ISSUE TITLE
libcaca do not compile in shared 32 or 64 bits.

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#1428]
[build]     libcaca                  x86_64-w64-mingw32.shared                                           

Failed to build package libcaca for target x86_64-w64-mingw32.shared!
------------------------------------------------------------
Alternatively, you may set the environment variables GL_CFLAGS
and GL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Makefile:565: recipe for target 'build-only-libcaca_x86_64-w64-mingw32.shared' failed
make[1]: *** [build-only-libcaca_x86_64-w64-mingw32.shared] Error 1
make[1]: Leaving directory '/mnt/data/5.x/project/mxe/build.win64'
real    0m13.480s
user    0m9.415s
sys     0m1.529s
------------------------------------------------------------
[log]      /mnt/data/5.x/project/mxe/build.win64/log/libcaca_x86_64-w64-mingw32.shared

Makefile:565: recipe for target '/mnt/data/5.x/project/mxe/build.win64/usr/x86_64-w64-mingw32.shared/installed/libcaca' failed
make: *** [/mnt/data/5.x/project/mxe/build.win64/usr/x86_64-w64-mingw32.shared/installed/libcaca] Error 1

[gilles@localhost core]$ cat /mnt/data/5.x/project/mxe/build.win64/log/libcaca_x86_64-w64-mingw32.shared
make[1]: Entering directory '/mnt/data/5.x/project/mxe/build.win64'
uname -a
Linux localhost 4.4.6-desktop-1.mga6 #1 SMP Thu Mar 17 05:35:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
git log --pretty=tformat:"%H - %s [%ar] [%d]" -1
9ebb730d86dfc9ea416368b2b9042297e3eff9d6 - oce: disable installing dependent libs [10 hours ago] [ (HEAD -> master, origin/master, origin/gh-pages, origin/HEAD)]
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
LSB Version:    *
Distributor ID: Mageia
Description:    Mageia 6
Release:        6
Codename:       thornicroft
autoconf --version 2>/dev/null | head -1
autoconf (GNU Autoconf) 2.69
automake --version 2>/dev/null | head -1
automake (GNU automake) 1.15
gcc --version
gcc (GCC) 5.3.1 20160419
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version
g++ (GCC) 5.3.1 20160419
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

python --version
Python 2.7.11
perl --version 2>&1 | head -3

This is perl 5, version 22, subversion 2 (v5.22.2) built for x86_64-linux-thread-multi
(with 1 registered patch, see perl -V for more detail)
rm -rf   '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared'
mkdir -p '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared'
# disable wine with readonly directory
# see https://github.com/mxe/mxe/issues/841
mkdir -p '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared/readonly'
chmod 0555 '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared/readonly'
cd '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared' &&  tar xzf '/mnt/data/5.x/project/mxe/build.win64/pkg/libcaca-0.99.beta19.tar.gz'
cd '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared/libcaca-0.99.beta19'
(cd '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared/libcaca-0.99.beta19' && patch -p1 -u) < /mnt/data/5.x/project/mxe/build.win64/src/libcaca-1-fixes.patch 
patching file caca/driver/ncurses.c
patching file caca/driver/slang.c
patching file caca-config.in
patching file caca/caca.pc.in
patching file configure.ac
(cd '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared/libcaca-0.99.beta19' && patch -p1 -u) < /mnt/data/5.x/project/mxe/build.win64/src/libcaca-2-vsnprintf.patch
patching file caca/driver/ncurses.c
patching file caca/driver/slang.c
patching file caca/driver/x11.c
patching file caca/prof.c
patching file caca/figfont.c
patching file caca/string.c
cd '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared/libcaca-0.99.beta19' && autoreconf -fi
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.auto'.
libtoolize: copying file '.auto/ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:23: installing '.auto/compile'
configure.ac:8: installing '.auto/missing'
Makefile.am: installing './INSTALL'
caca/Makefile.am: installing '.auto/depcomp'
java/Makefile.am:13: warning: wildcard $(srcdir: non-POSIX variable name
java/Makefile.am:13: (probably a GNU make extension)
ruby/Makefile.am:11: warning: 'CFLAGS' is a user variable, you should not override it;
ruby/Makefile.am:11: use 'AM_CFLAGS' instead
cd '/mnt/data/5.x/project/mxe/build.win64/tmp-libcaca-x86_64-w64-mingw32.shared/libcaca-0.99.beta19' && ./configure --host='x86_64-w64-mingw32.shared' --build='x86_64-unknown-linux-gnu' --prefix='/mnt/data/5.x/project/mxe/build.win64/usr/x86_64-w64-mingw32.shared'  --disable-static --enable-shared  ac_cv_prog_HAVE_DOXYGEN="false" --disable-doxygen --disable-csharp --disable-java --disable-python --disable-ruby --disable-doc
configure: WARNING: unrecognized options: --disable-doxygen
configure: loading site script /mnt/data/5.x/project/mxe/build.win64/usr/x86_64-w64-mingw32.shared/share/config.site
checking build system type... (cached) x86_64-unknown-linux-gnu
checking host system type... x86_64-w64-mingw32.shared
checking target system type... x86_64-w64-mingw32.shared
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for x86_64-w64-mingw32.shared-strip... x86_64-w64-mingw32.shared-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for style of include used by make... GNU
checking for x86_64-w64-mingw32.shared-gcc... x86_64-w64-mingw32.shared-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-w64-mingw32.shared-gcc accepts -g... yes
checking for x86_64-w64-mingw32.shared-gcc option to accept ISO C89... none needed
checking whether x86_64-w64-mingw32.shared-gcc understands -c and -o together... yes
checking dependency style of x86_64-w64-mingw32.shared-gcc... gcc3
checking how to run the C preprocessor... x86_64-w64-mingw32.shared-gcc -E
checking for x86_64-w64-mingw32.shared-g++... x86_64-w64-mingw32.shared-g++
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-w64-mingw32.shared-g++ accepts -g... yes
checking dependency style of x86_64-w64-mingw32.shared-g++... gcc3
checking how to run the C++ preprocessor... x86_64-w64-mingw32.shared-g++ -E
checking dependency style of ... none
checking dependency style of x86_64-w64-mingw32.shared-gcc... gcc3
checking for x86_64-w64-mingw32.shared-as... x86_64-w64-mingw32.shared-as
checking for x86_64-w64-mingw32.shared-dlltool... x86_64-w64-mingw32.shared-dlltool
checking for x86_64-w64-mingw32.shared-objdump... x86_64-w64-mingw32.shared-objdump
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by x86_64-w64-mingw32.shared-gcc... /mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-ld
checking if the linker (/mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-nm -B
checking the name lister (/mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-w64-mingw32.shared format... func_convert_file_nix_to_w32
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-ld option to reload object files... -r
checking for x86_64-w64-mingw32.shared-objdump... (cached) x86_64-w64-mingw32.shared-objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for x86_64-w64-mingw32.shared-dlltool... (cached) x86_64-w64-mingw32.shared-dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for x86_64-w64-mingw32.shared-ar... x86_64-w64-mingw32.shared-ar
checking for archiver @FILE support... @
checking for x86_64-w64-mingw32.shared-strip... (cached) x86_64-w64-mingw32.shared-strip
checking for x86_64-w64-mingw32.shared-ranlib... x86_64-w64-mingw32.shared-ranlib
checking command to parse /mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-nm -B output from x86_64-w64-mingw32.shared-gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for x86_64-w64-mingw32.shared-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... no
checking for objdir... .libs
checking if x86_64-w64-mingw32.shared-gcc supports -fno-rtti -fno-exceptions... no
checking for x86_64-w64-mingw32.shared-gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if x86_64-w64-mingw32.shared-gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if x86_64-w64-mingw32.shared-gcc static flag -static works... yes
checking if x86_64-w64-mingw32.shared-gcc supports -c -o file.o... yes
checking if x86_64-w64-mingw32.shared-gcc supports -c -o file.o... (cached) yes
checking whether the x86_64-w64-mingw32.shared-gcc linker (/mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... x86_64-w64-mingw32.shared-g++ -E
checking for ld used by x86_64-w64-mingw32.shared-g++... /mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-ld
checking if the linker (/mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-ld) is GNU ld... yes
checking whether the x86_64-w64-mingw32.shared-g++ linker (/mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-ld) supports shared libraries... yes
checking for x86_64-w64-mingw32.shared-g++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if x86_64-w64-mingw32.shared-g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if x86_64-w64-mingw32.shared-g++ static flag -static works... yes
checking if x86_64-w64-mingw32.shared-g++ supports -c -o file.o... yes
checking if x86_64-w64-mingw32.shared-g++ supports -c -o file.o... (cached) yes
checking whether the x86_64-w64-mingw32.shared-g++ linker (/mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-ld) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking return type of signal handlers... void
checking for x86_64-w64-mingw32.shared-pkg-config... /mnt/data/5.x/project/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for suffix of libraries... -0.dll
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking sys/ioctl.h usability... no
checking sys/ioctl.h presence... no
checking for sys/ioctl.h... no
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking endian.h usability... no
checking endian.h presence... no
checking for endian.h... no
checking for unistd.h... (cached) yes
checking arpa/inet.h usability... no
checking arpa/inet.h presence... no
checking for arpa/inet.h... no
checking netinet/in.h usability... no
checking netinet/in.h presence... no
checking for netinet/in.h... no
checking winsock2.h usability... yes
checking winsock2.h presence... yes
checking for winsock2.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for dlfcn.h... (cached) no
checking termios.h usability... no
checking termios.h presence... no
checking for termios.h... no
checking for signal... yes
checking for ioctl... no
checking for snprintf... yes
checking for sprintf_s... yes
checking for vsnprintf... yes
checking for vsnprintf_s... yes
checking for getenv... yes
checking for putenv... yes
checking for strcasecmp... yes
checking for htons... no
checking for usleep... yes
checking for gettimeofday... yes
checking for atexit... yes
checking for getopt_long... yes
checking for Sleep... yes
checking for fsin/fcos... yes
checking for fldln2/fxch/fyl2x... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for gzopen in -lz... yes
checking for sin in -lm... yes
checking conio.h usability... yes
checking conio.h presence... yes
checking for conio.h... yes
checking for ScreenUpdate in pc.h... no
checking windows.h usability... yes
checking windows.h presence... yes
checking for windows.h... yes
checking for AllocConsole in windows.h... yes
checking slang.h usability... no
checking slang.h presence... no
checking for slang.h... no
checking slang/slang.h usability... no
checking slang/slang.h presence... no
checking for slang/slang.h... no
checking for X... no
checking for XOpenDisplay in -lX11... no
checking X11/XKBlib.h usability... no
checking X11/XKBlib.h presence... no
checking for X11/XKBlib.h... no
checking OpenGL/gl.h usability... no
checking OpenGL/gl.h presence... no
checking for OpenGL/gl.h... no
checking GL/gl.h usability... yes
checking GL/gl.h presence... yes
checking for GL/gl.h... yes
checking for GL... no
configure: error: Package requirements (glut glu gl) were not met:

Package glut was not found in the pkg-config search path.
Perhaps you should add the directory containing `glut.pc'
to the PKG_CONFIG_PATH environment variable
Package 'glut', required by 'world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GL_CFLAGS
and GL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Makefile:565: recipe for target 'build-only-libcaca_x86_64-w64-mingw32.shared' failed
make[1]: *** [build-only-libcaca_x86_64-w64-mingw32.shared] Error 1
make[1]: Leaving directory '/mnt/data/5.x/project/mxe/build.win64'

real    0m13.480s
user    0m9.415s
sys     0m1.529s
[gilles@localhost core]$ 

libcaca is a dependency of ffmpeg. If i disable libcaca support in ffmpeg makefile, all is fine.

Gilles Caulier

**Comment by tonytheodore** [comment]
Fixed in #1429.
