### ISSUE TITLE
a lot of packages fails to download 

### ISSUE THREAD

**Issue by maruncz** [mxe/mxe#1435]
hi
i am trying to build qt5 but a lot of packages fails to download

i checked logs of these packages and it douwnloads only little data (<1k)

here is my console output in log and whole build log

[mxe.tar.gz](https://github.com/mxe/mxe/files/361736/mxe.tar.gz)

**Comment by tonytheodore** [comment]
I've been seeing issues with SourceForge today, try this:

```
make download SOURCEFORGE_MIRROR=example.com
```

it will force downloading from MXE mirrors instead.

**Comment by maruncz** [comment]
it works 
thanks

**Comment by tonytheodore** [comment]
Good to hear, SF appears to be up again.
