### ISSUE TITLE
fatal error: Windows.h: No such file or directory

### ISSUE THREAD

**Issue by maruncz** [mxe/mxe#1437]
i have cmake project configured with x86_64-w64-mingw32.shared-cmake but compile fails on missing Windows.h 
even i686-w64-mingw32.shared-cmake has same error
which package is my mxe build missing?

**Comment by tonytheodore** [comment]
Most likely need to use lowercase `windows.h` instead of `Windows.h`.

**Comment by maruncz** [comment]
thanks fixed

**Comment by maruncz** [comment]
i'm reopening this issue because i found another project with this issue
i suspect that windows.h has to actually be Windows.h

**Comment by starius** [comment]
I have renamed Windows.h to windows.h in many projects.

[MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363855(v=vs.85).aspx) proposes `Windows.h`. Can we create symlink `Windows.h` pointing to `windows.h`? And the same for other Windows specific files (like `Winsock2.h`).

**Comment by tonytheodore** [comment]
MSDN also uses [`WINDOWS.H`](https://msdn.microsoft.com/en-us/library/aa271858(v=vs.60).aspx) and [`windows.h`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682516(v=vs.85).aspx) or [`winsock2.h`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms737629%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) in code samples, it doesn't really matter on Windows.

It think it's better to change the project to match the mingw headers, if we do symlinks, it's only a workaround for MXE users - every other mingw-based toolchain would still be incompatible.

**Comment by maruncz** [comment]
ok i will post issue to that projects

**Comment by aravindk64** [comment]
./result/final_8080.c:1:10: fatal error: windows.h: No such file or directory
#include <windows.h>
^~~~~~~~~~~
compilation terminated

**Comment by amjack0** [comment]
did you find the solution ?

> ./result/final_8080.c:1:10: fatal error: windows.h: No such file or directory
> #include <windows.h>
> ^~~~~~~~~~~
> compilation terminated
> Can any one help

**Comment by qwertysam** [comment]
I'm having the same problem building `libsndfile` with the `x86_64-w64-mingw32` toolchain (both `static` and `shared`)

```
src/file_io.c:599:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
```

**Comment by Royanon001** [comment]
#include<windows.h>
Windows.h: No such file or directory
[{
	"resource": "/home/anon/Documents/C PROGRAMS/Login_sys.c",
	"owner": "C/C++",
	"code": "1696",
	"severity": 8,
	"message": "cannot open source file \"windows.h\"",
	"source": "C/C++",
	"startLineNumber": 3,
	"startColumn": 1,
	"endLineNumber": 3,
	"endColumn": 20
}]

**Comment by mamesareagan** [comment]
fatal error: windows.h: No such file or directory
    4 | #include <windows.h>
help
