### ISSUE TITLE
test.cpp:15:33: error: ‘_putenv_s’ was not declared in this scope

### ISSUE THREAD

**Issue by abma** [mxe/mxe#1448]
when compiling this:

``` c
#include <stdlib.h>
int setenv(const char *name, const char *value, int overwrite)
{   
    return _putenv_s(name, value);
}

int main()
{
        setenv("a", "b", 1);
        return 0;
}
```

i get:
   error: ‘_putenv_s’ was not declared in this scope

it seems MINGW_HAS_SECURE_API=1 is not defined for some reason in include/_mingw.h which is defined for a system installed mingw64.

as workarround i have to add -DMINGW_HAS_SECURE_API=1 to the compile line options, then the example compiles fine!

**Comment by tonytheodore** [comment]
See https://github.com/mxe/mxe/pull/1378#issuecomment-225103604 you can call:

```
make mingw-w64-headers_CONFIGURE_OPTS=--enable-secure-api
```

or add `mingw-w64-headers_CONFIGURE_OPTS=--enable-secure-api` to `settings.mk`.

**Comment by starius** [comment]
I have compiled `test.cpp` with `-DMINGW_HAS_SECURE_API=1`.
It works on Windows Vista, but fails on Windows XP:

![secure.exe](https://i.imgur.com/YSh7bcS.png)

Why did not it result in linking errors?

**Comment by tonytheodore** [comment]
Did you compile with `-Wl,--no-undefined`?

**Comment by starius** [comment]
Both commands:

```
$ ./usr/bin/i686-w64-mingw32.static-gcc secure.cpp -DMINGW_HAS_SECURE_API=1 -o secure.exe
```

and

```
$ ./usr/bin/i686-w64-mingw32.static-gcc -Wl,--no-undefined secure.cpp -DMINGW_HAS_SECURE_API=1 -o secure.exe
```

report no linking errors.

**Comment by tonytheodore** [comment]
> report no linking errors.

Of course, the symbols are stubs without an actual implementation - that's provided by the *.dll.

**Comment by starius** [comment]
Can we provide stub symbols for cases like [SetProcessDPIAware](http://lists.nongnu.org/archive/html/mingw-cross-env-list/2016-07/msg00002.html) as well?

**Comment by tonytheodore** [comment]
We can use [spec files](https://github.com/tonytheodore/mxe/blob/0960b9f8892d77fdb1b828b7183fb1b1982926ff/src/gcc.mk#L131) to use a [different msvcrt*](https://github.com/mxe/mxe/issues/10). That means (somehow) shipping additional runtime components, but avoids special casing individual cases that will get harder to maintain over time.

**Comment by tonytheodore** [comment]
`--enable-secure-api` is now the default (#1648), and doesn't break XP support on it's own. The hill gets steeper for every upstream project using those newer APIs, better to work on the runtime components #10.
