### ISSUE TITLE
poppler build failed on i686-w64-mingw32.shared

### ISSUE THREAD

**Issue by dl5rcw** [mxe/mxe#1455]
I found poppler to fail on a build:

https://gist.github.com/starius/c322db93252f50a87d078323b1ff8b06

**Comment by starius** [comment]
Thanks for the report! I moved the error message to gist and updated your initial comment.

Could you provide the full version of the log, please? The log contains information which is needed to reproduce the bug (e.g., commit and OS).

**Comment by tonytheodore** [comment]
I'm guessing it's an ordering issue when `mman-win32` is detected and doesn't pass `-lmman` in any way.

**Comment by dl5rcw** [comment]
I started two servers to reproduce this in order to provide more detailed and deterministric information. Currently waiting for the CPUs to compile. I have a Debian up and testing & a KUbuntu in parallel.

**Comment by starius** [comment]
> I'm guessing it's an ordering issue when mman-win32 is detected and doesn't pass -lmman in any way.

Confirmed. `poppler` fails if `mman-win32` is built.

**Comment by starius** [comment]
@dl5rcw 
Please check https://github.com/mxe/mxe/pull/1457

**Comment by dl5rcw** [comment]
@starius #1457 solved the issue on the much faster KUbuntu machine. Waiting for the Debian machine to get there.

**Comment by dl5rcw** [comment]
@starius - #1457 works on Debian, too.
