### ISSUE TITLE
qt3d fails to build

### ISSUE THREAD

**Issue by dl5rcw** [mxe/mxe#1462]
On Debian I did a `make qt5` and the built failed for qt3d. Please find the full log here: https://gist.github.com/dl5rcw/7f9e679ebc3f74c7e5b5442643bdf9cd
It is reproducible on the debian build-server.

For your first insight, here is the potential log sniplet
make[5]: Entering directory '/share/mxe/tmp-qt3d-i686-w64-mingw32.static/qt3d-opensource-src-5.7.0/src/quick3d/imports/extras'
make[5]: *** No rule to make target '/share/mxe/tmp-qt3d-i686-w64-mingw32.static/qt3d-opensource-src-5.7.0/lib/libQt53DQuick.a', needed by '../../../../qml/Qt3D/Extras/libquick3dextrasplugin.a'.  Schluss.
make[5]: Leaving directory '/share/mxe/tmp-qt3d-i686-w64-mingw32.static/qt3d-opensource-src-5.7.0/src/quick3d/imports/extras'
Makefile.importsextras:34: recipe for target 'release' failed
make[4]: *** [release] Error 2
make[4]: Leaving directory '/share/mxe/tmp-qt3d-i686-w64-mingw32.static/qt3d-opensource-src-5.7.0/src/quick3d/imports/extras'
Makefile:414: recipe for target 'sub-quick3d-imports-extras-make_first' failed
make[3]: *** [sub-quick3d-imports-extras-make_first] Error 2
make[3]: *** Warte auf noch nicht beendete Prozesse...

**Comment by dl5rcw** [comment]
I found no 'real' issue, so I went for a race condition. I compile with JOBS:= 4 in the settings.mk file.
When I did JOBS:=1, qt3d compiled! The past days, I had KUbuntu do JOBS:= 8 and qt3d was OK.
I suggest to modify qt3d.mk
```
define $(PKG)_BUILD
    cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake'
    #$(MAKE) -C '$(1)' -j  '$(JOBS)'
    $(MAKE) -C '$(1)' -j  1
    $(MAKE) -C '$(1)' -j 1 install
endef
```
to prevent such ugly behaviour in future. I guess this issue is something to report to qt3d itself.

**Comment by tonytheodore** [comment]
Seems fine with either 6 or 8 jobs. A retry is usually better:
```
$(MAKE) -C '$(1)' -j  '$(JOBS)' || $(MAKE) -C '$(1)' -j  1
```

**Comment by dl5rcw** [comment]
@tonytheodore Excellent! I was not aware of such a method. I will give it a try and could start a pull request for that little issue. Maybe I can provide that by tonight.

**Comment by dl5rcw** [comment]
@tonytheodore works good now just like you mentioned before. Offering the fix now.

**Comment by tonytheodore** [comment]
@dl5rcw, retrying can [hide subtle issues](#1474), can you report this upstream? The `*** No rule to make target...` errors indicate something is amiss in the build system, we really should only retry where the failure is hardware related (exhausted memory, too many open files etc.).

**Comment by dl5rcw** [comment]
@tonytheodore - I deleted the directory, did a reboot and started all over to reproduce it. With your proposed solution, everything went smooth (on two machines).

**Comment by tonytheodore** [comment]
@dl5rcw I'm saying my solution of retrying is wrong. @starius [reminded me](https://github.com/mxe/mxe/pull/1474#issuecomment-237323352) why that approach [is flawed](https://www.google.com/search?q=there+are+solutions+even+to+the+hardest+problems).

Even in the case of [exhausted hardware](https://github.com/mxe/mxe/issues/1381), we should provide more control over resources and ways to easily test upstream changes.

Your original suggestion of a serial build and

> I guess this issue is something to report to qt3d itself.

is the correct course of action.
