### ISSUE TITLE
pkg-config file for tinyxml for TIXML_USE_ST?

### ISSUE THREAD

**Issue by Quintus** [mxe/mxe#1463]
The following example tries to use the tinyxml library:

~~~~ cpp
#include <tinyxml.h>

int main(void) {

   TiXmlDocument Doc("test.xml");

   return EXIT_SUCCESS;
}
~~~~

Try to build this:

~~~~
% i686-w64-mingw32.static-g++ xml.cpp -o xml -ltinyxml 
/tmp/ccVvRYSb.o:xml.cpp:(.text$_ZN11TiXmlString4quitEv[__ZN11TiXmlString4quitEv]+0xf): undefined reference to `TiXmlString::nullrep_'
collect2: error: ld returned 1 exit status
~~~~

The problem can be resolved by passing `-DTIXML_USE_ST`:

~~~~
% i686-w64-mingw32.static-g++ -DTIXML_USE_STL xml.cpp -o xml -ltinyxml
%
~~~~

MXE doesn’t indicate this flag is needed anywhere. This should be added to a pkg-config file I guess?

Vale,
Quintus

**Comment by tonytheodore** [comment]
Curiously, the `tinyxml` pkg (version 2.6.2) patches and uses `-DTIXML_USE_STL`, but `tinyxml2` (version 3.0.0?) doesn't.

**Comment by starius** [comment]
tinyxml2 doesn't seem to have this macro.

tinyxml2 has no test file.
tinyxml has no pc file.

**Comment by tonytheodore** [comment]
From: https://github.com/leethomason/tinyxml2#tinyxml-1-vs-tinyxml-2
> TinyXML-2 has no requirement for STL, but has also dropped all STL support.

I think updating `tinyxml2` should fix this.

**Comment by tonytheodore** [comment]
tinyxml is deprecated upstream and no longer updated. I've added a deprecation message (#1466) and we should remove it eventually.
