### ISSUE TITLE
liblzma is installed by xz not lzma

### ISSUE THREAD

**Issue by witwall** [mxe/mxe#1481]
I tried to compile lzma with 

```
make MXE_TARGETS='x86_64-w64-mingw32.static' lzma
```

without fail, but no liblzma.a or liblzma.la output(but has lzma.exe).

btw,  i686-w64-mingw32.static is ok.

**Comment by tonytheodore** [comment]
Very strange, lzma doesn't seem to install any libs - xz installs liblzma.

**Comment by witwall** [comment]
my fault.

**Comment by tonytheodore** [comment]
It's very counter-intuitive, I've changed the description and re-opened it.

**Comment by tonytheodore** [comment]
So it seems that xz is indeed the official source of liblzma, I guess people are supposed to know that.

> ANSI-C and C++ source code in LZMA SDK is subset of source code of 7-Zip.

@starius, since we only build the tools, would building 7z.exe be more useful than lzma.exe?

**Comment by tonytheodore** [comment]
Added note in lzma https://github.com/mxe/mxe/commit/1bc2e4c1810997968a338c5efbe022bbb047bfde
