### ISSUE TITLE
static freetds (and qt which depends on it) fails to build

### ISSUE THREAD

**Issue by avih** [mxe/mxe#1482]
```
[build]     freetds                  i686-w64-mingw32.static

Failed to build package freetds for target i686-w64-mingw32.static!
------------------------------------------------------------
Makefile:461: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/user/dev/mxe/tmp-freetds-i686-w64-mingw32.static/freetds-1.00.6'
Makefile:589: recipe for target 'build-only-freetds_i686-w64-mingw32.static' failed
make[1]: *** [build-only-freetds_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory '/home/user/dev/mxe'
real    0m44.651s
user    1m36.176s
sys     0m8.700s
------------------------------------------------------------
[log]      /home/user/dev/mxe/log/freetds_i686-w64-mingw32.static
```

The part of the log where the errors start (there are few more similar after this too):

```
...
  CCLD     bsqldb.exe
../dblib/.libs/libsybdb.a(bulk.o): In function `tds_bcp_fread':
/home/user/dev/mxe/tmp-freetds-i686-w64-mingw32.static/freetds-1.00.6/src/tds/bulk.c:1059: undefined reference to `_imp___lock_file'
/home/user/dev/mxe/tmp-freetds-i686-w64-mingw32.static/freetds-1.00.6/src/tds/bulk.c:1064: undefined reference to `_imp___unlock_file'
collect2: error: ld returned 1 exit status
Makefile:592: recipe for target 'freebcp.exe' failed
make[5]: *** [freebcp.exe] Error 1
make[5]: *** Waiting for unfinished jobs....
../dblib/.libs/libsybdb.a(bulk.o): In function `tds_bcp_fread':
/home/user/dev/mxe/tmp-freetds-i686-w64-mingw32.static/freetds-1.00.6/src/tds/bulk.c:1059: undefined reference to `_imp___lock_file'
/home/user/dev/mxe/tmp-freetds-i686-w64-mingw32.static/freetds-1.00.6/src/tds/bulk.c:1064: undefined reference to `_imp___unlock_file'
collect2: error: ld returned 1 exit status
Makefile:588: recipe for target 'defncopy.exe' failed
make[5]: *** [defncopy.exe] Error 1
...
```

Also, I use mingw-w64 v5 RC2, however, if I recall correctly Qt did build with it in the past. If you think it's a mingw issue, let me know.

**Comment by tonytheodore** [comment]
With #1470, I can see the same error on current mingw-w64 master but not v4.0.6.

**Comment by tonytheodore** [comment]
@avih this appears to be fixed with recent freetds updates and/or mingw-w64 5.0.1.

Please re-open if you see the same issues.

**Comment by avih** [comment]
Thanks, I can confirm that static freedts and qt5 now builds (with mingw-w64 5.0.1).

On an unrelated note (I'll open an issue for it if you think it's an issue), should cmake work for Qt5 projects when MXE is configured to build static?

I was able to build qmake projects with static MXE-Qt5 (which produces a nice single statically linked executable which works fine), but with cmake it builds everything and then fails while linking - tons of complaints similar to `qt5/lib/libQt5Core.a(qglobal.o):qglobal.cpp:(.text+0x49a): undefined reference to '_imp__WSACleanup@0'`, and this is despite the fact that `ws32_2` (which has this symbol) is linked as far as I can tell.

FWIW the project is Quassel IRC which does state (in its `CMakeList.txt` file) that static linking might not be trivial, so this definitely could be an issue with static linking for this specific project.

**Comment by tonytheodore** [comment]
@avih see #1642, it's a general issue with cmake.
