### ISSUE TITLE
gdb fails to build.

### ISSUE THREAD

**Issue by garry-iglesias** [mxe/mxe#1486]
On a '_almost vanilla_' Slackware 14.2 system:

**Focus:**<code><pre>gdb-dlfcn.o: In function `gdb_dlopen':
/mxe/tmp-gdb-i686-w64-mingw32.static/gdb-7.11.1/gdb/gdb-dlfcn.c:72: undefined reference to `dlopen'
/mxe/tmp-gdb-i686-w64-mingw32.static/gdb-7.11.1/gdb/gdb-dlfcn.c:80: undefined reference to `dlerror'
gdb-dlfcn.o: In function `gdb_dlclose':
/mxe/tmp-gdb-i686-w64-mingw32.static/gdb-7.11.1/gdb/gdb-dlfcn.c:113: undefined reference to `dlclose'
gdb-dlfcn.o: In function `gdb_dlsym':
/mxe/tmp-gdb-i686-w64-mingw32.static/gdb-7.11.1/gdb/gdb-dlfcn.c:103: undefined reference to `dlsym'
gdb-dlfcn.o: In function `gdb_dlclose':
/mxe/tmp-gdb-i686-w64-mingw32.static/gdb-7.11.1/gdb/gdb-dlfcn.c:113: undefined reference to `dlclose'
../bfd/libbfd.a(plugin.o): In function `try_load_plugin':
/mxe/tmp-gdb-i686-w64-mingw32.static/gdb-7.11.1/bfd/plugin.c:217: undefined reference to `dlopen'
/mxe/tmp-gdb-i686-w64-mingw32.static/gdb-7.11.1/bfd/plugin.c:224: undefined reference to `dlsym'
/mxe/tmp-gdb-i686-w64-mingw32.static/gdb-7.11.1/bfd/plugin.c:220: undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
</pre></code>

Complete log here: https://gist.github.com/garry-iglesias/8b3c5cb7c2a2c74d72e51e86e7fc3717

Thanks.

**Comment by tonytheodore** [comment]
It's detecting `dlfcn` incorrectly due to missing `-lpsapi`. See #1487.
