### ISSUE TITLE
[solved] -Wno-error=misleading-indentation error while compiling upx

### ISSUE THREAD

**Issue by jorox** [mxe/mxe#1493]
Hello,
Upon making mxe using 
`make gcc`
I encountered an error with the package upx.
It is because of the compiler option `misleading-indentation` which is implemented as of g++6

For those with g++ version <6 the error can be fixed by removing part of the lines 50-51 in  `/opt/mxe/src/upx.mk`

old line:
`echo "CXXFLAGS=-Wno-error=unused-local-typedefs -Wno-error=misleading-indentation" || \
            echo "CXXFLAGS=-Wno-error=misleading-indentation") \`

new lines:
`echo "CXXFLAGS=-Wno-error=unused-local-typedefs")\`

Might want to consider adding some qualifier to that compiler option

**Comment by tonytheodore** [comment]
Fixed in #1496 by disabling `-Werror`.
