### ISSUE TITLE
[solved] cross-compiling openCV linkage issues

### ISSUE THREAD

**Issue by jorox** [mxe/mxe#1494]
If you are trying to compile a project with openCV here are the necessary library includes (in order) for your linkage to work:

`-L/opt/mxe/usr/i686-w64-mingw32.static/lib -lopencv_imgproc -lopencv_highgui -lIlmImf -lIlmThread -lIex -lImath -lHalf -lopencv_core -lopengl32 -ljasper -lpthread -lgthread-2.0`

I have tried this for a project that uses Qt+openCV and it has compiled and ran perfectly!

Details: (--> = depends on)
libopencv_core.a --> libopengl32.a
libopencv_highgui --> libIlmImf.a libIlmThread.a libIex.a libImath.a libHalf.a

**Comment by tonytheodore** [comment]
Did you try using the pkg-config file?
