### ISSUE TITLE
MXE_TARGETS not validate, confusing error on update

### ISSUE THREAD

**Issue by rdoeffinger** [mxe/mxe#1497]
After updating from an old version, I only got this error message for anything I did:
Makefile:445: **\* recipe commences before first target.  Stop.
This happened because of this line from the old settings.mk:
MXE_TARGETS := i686-w64-mingw32
Changes in the settings.mk format should be tested to either be auto-converted or create an understandable error message, which would probably also be useful in case of typos in the settings.

**Comment by tonytheodore** [comment]
See #1499, hopefully the messages are more useful.
