### ISSUE TITLE
Broken HAVE_RANDOM in popt patch

### ISSUE THREAD

**Issue by rdoeffinger** [mxe/mxe#1498]
`src/popt-1-win32.patch` adds

``` c
#ifndef HAVE_RANDOM
```

but there is no way `HAVE_RANDOM` would ever be set.

If these hacks really are still needed the `configure.ac` needs to be changed to test for `random()`.

Would probably be good to test such patches by trying a standard Linux build with them applied, which with the patch as-is fails with:

```
popt.c: At top level:
popt.c:980:1: error: conflicting types for ‘random’
 random ()
 ^
In file included from system.h:32:0,
                 from popt.c:11:
/usr/include/stdlib.h:321:17: note: previous declaration of ‘random’ was here
 extern long int random (void) __THROW;
```

**Comment by tonytheodore** [comment]
The patch originally added extra checks for [`random`](https://github.com/mxe/mxe/blob/55e7cdb8d349480614f4a3303f4da57825a439ba/src/popt-1-win32.patch#L47) and [`sys/ioctl.h`](https://github.com/mxe/mxe/blob/55e7cdb8d349480614f4a3303f4da57825a439ba/src/popt-1-win32.patch#L38) but they were [removed in an update](https://github.com/mxe/mxe/commit/b57b64eda4ac66e58ac4bf850eed2336cecc9fc0). If you have time to do a PR to restore the checks and `autoreconf` it would be great.
