### ISSUE TITLE
[core] Adjust to new GitHub Pages mechanism

### ISSUE THREAD

**Issue by vog** [mxe/mxe#1500]
This is a question to the core team.

Good news: The GitHub Pages mechanism has improved and no longer requires us to maintain a separate `gh-pages` branch that we must keep in sync with master.

See also: https://github.com/blog/2228-simpler-github-pages-publishing

So what do we want to do?

1. Stick with the `gh-pages` branch
 * Don't change anything
2. Point GitHub Pages to `master`
 * Remove our `gh-pages` branch
 * Remove our specialized `gh-pages` settings from all our local `.git/config` files
3. Point GitHub Pages to `master docs/`
 * Remove our `gh-pages` branch
 * Remove our specialized `gh-pages` settings from all our local `.git/config` files
 * (Noted by Tony:) Remove `gh-pages` deployment from `tools/travis-push.sh`
 * Rename `doc/` to `docs/`
 * Move `index.html` to `docs/index.html`, adjust `Makefile` accordingly
 * Move `versions.json` to `docs/versions.json`, adjust `Makefile` accordingly
 * Move `build-matrix.html` to `docs/build-matrix.html`, adjust `Makefile` accordingly
 * (Noted by Boris:) Move `CNAME` to `docs/CNAME`
 * Adjust source headers from "See index.html for further information." to "See docs/index.html for further information."

**Please state your opinions!**

(To get this discussion started: I personally prefer 3, but I'm afraid that this may cause too much work.)

**Comment by mgerhardy** [comment]
point 3 imo. point 2 maybe - point 1: please not

**Comment by starius** [comment]
Option 3 looks good to me.

According to the [documentation](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/), file `CNAME` should be moved to docs/ as well.

**Comment by tonytheodore** [comment]
Good news indeed, removing the `gh-pages` branch will be a welcome
change. Some of the local `.git/config` [has already been removed][1]
and [replaced by travis][2]. I'm mostly in favour of the third option,
the changes are largely "mechanical" and worth the work for greater 
clarity.

> Adjust source headers from "See index.html for further information."

I'd remove this reference altogether - it's unlikely there's any help
for the new user in `index.html`. Package-specific notes should be 
"close" to the respective package (patch headers are already in this
direction).

We have very few "RTFM" questions, more frequently - "document this
somewhere". As MXE grows, `index.html` becomes less "docs" and more 
"website".

[1]:https://github.com/mxe/mxe/commit/0ce4144
[2]:https://github.com/mxe/mxe/commit/452229c

**Comment by TimothyGu** [comment]
Option 3 is quite obviously the cleanest solution. The source header can go, but we might want to add a small blurb stating that the file is under the MIT License, not that it matters much.

**Comment by vog** [comment]
@tonytheodore, @TimothyGu: The full header is:

    # This file is part of MXE.
    # See index.html for further information.

When I created that statement, this was meant to be a kind of short copyright notice. The part "See index.html for ..." was most intended to refer to where to look for licensing information, because that information was only in `index.html`. Nowadays we also have LICENSE.md, so we could refer to that one instead.

Maybe we could shorten it to:

    # This file is part of MXE. See LICENSE.md for licensing information.

**Comment by vog** [comment]
It seems there is a clear preference for option 3. Does anyone volunteer to implement it as a pull request?

I would them review it, and merge it, adjust GitHub Pages settings and remove the old `gh-pages` branch.

**Comment by starius** [comment]
> Does anyone volunteer to implement it as a pull request?

I will look at it.

**Comment by vog** [comment]
@starius Thanks!

**Comment by starius** [comment]
Done: https://github.com/mxe/mxe/pull/1503

Additional advantage of option 3 is the reduction of the list of files in the top directory. Files `versions.json`, `build-matrix.html` and `CNAME` are no longer listed in build-pkg for package mxe-source.

**Comment by vog** [comment]
@starius Thanks for your work!

**Comment by vog** [comment]
I just changed the repository settings and removed the now obsolete `gh-pages` branch.
