### ISSUE TITLE
Add CMake's cpack

### ISSUE THREAD

**Issue by Quintus** [mxe/mxe#1502]
Hi everyone,

since MXE already ships with its own CMake, is it possible to add [CPack](https://cmake.org/cmake/help/v3.6/manual/cpack.1.html) as well, which is part of the CMake suite? It is very handy for building Windows installers directly from the CMakeLists.txt file, for which it delegates to `makensis` (which in turn is part of the NSIS Windows installer builder).

Greetings
Marvin

**Comment by tonytheodore** [comment]
It seems cpack is already installed in the same directory as cmake - `usr/<build>/bin`?

**Comment by Quintus** [comment]
> It seems cpack is already installed in the same directory as cmake

Indeed, you are right, I have one in `usr/x86_64-unknown-linux-gnu/bin/cpack`. However, shouldn't it be available as `usr/bin/i686-w64-mingw32.static-cpack` as well (which is where I was looking for it)?

Anyway, thanks for the hint. I'll try if it works. Thanks!
Marvin

**Comment by Quintus** [comment]
@tonytheodore While it is there, it does not work:

~~~~~
% cpack -G NSIS
CPack Error: Cannot find NSIS compiler makensis: likely it is not installed, or not in your PATH
CPack Error: Could not read NSIS registry value. This is usually caused by NSIS not being installed. Please install NSIS from http://nsis.sourceforge.net
CPack Error: Cannot initialize the generator NSIS
~~~~~

This looks to me as it it is looking for `makensis`, but the executable is actually named `i686-w64-mingw32.static-makensis`, which it does not find. 

Greetings
Marvin

**Comment by tonytheodore** [comment]
Looks like we need a wrapper script, do you have time to find the "CPACK_NSIS_EXECUTABLE" variable and the correct invocation of `cpack`?

**Comment by Quintus** [comment]
I am sorry I don't understand. I have googled for `CPACK_NSIS_EXECUTABLE` now a few times, but I couldn't find anything related to that variable.

With current master (commit 75df27cdfc69bdff80e353076e12b581aff0831e) things haven't changed, it still does not find `makensis` by default. However, I found the `makensis` executable resides inside `(mxe root)/usr/i686-w64-mingw32.static/bin`, and if I manually add that path to my `$PATH` variable it _does_ work and creates the installer as expected. I however thought that one isn't supposed to add that directory to `$PATH`? Shouldn't it suffice to add `(mxe root)/usr/bin`?

If you still need/want me to help, you'll need to be more specific probably, as I don't understand what exactly I am supposed to do according to your last comment.

Greetings
Marvin

**Comment by Quintus** [comment]
Okay, I am confused now with the pathes. Today I appearently accidentally used by host system's `cpack`, but that worked flawlessly. That however is probably not what is intended.

The pathes in question are these:

1. mxeroot/usr/bin: This one contains all the i686-w64-mingw32.static-* executables. *There is no i686-w64-mingw32.static-cpack in this directory*, which is unexpected to me.
2. mxeroot/usr/x86_64-unknown-linux-gnu/bin: There is a `cpack` executable here, which I appearently have not used yet.
3. mxeroot/usr/i686-w64-mingw32.static/bin: Here is the `makensis` executable, but it is not found.

If I add pathes 1) and 3) to my `$PATH` it works, but it appearently uses my host system's `cpack` (the one from `/usr/bin` that my distro shipped). The documentation however explicitely advises against doing that.

On the other hand, if I only add pathes 1) and 2), the problem does not go away. It does not find `makensis` still.

Greetings
Marvin

**Comment by ArseniyShestakov** [comment]
@Quintus any chance you solved it somehow?
I'm looking into the same problem: while it's works usually I don't want MXE to use system CPack.

**Comment by tonytheodore** [comment]
See #1880, it adds a prefixed `*-cpack` and sets the prefixed `*-makensis`. I don't use either so I'm not sure how it's supposed to work, but it does find the correct executables without modifying `$PATH`.

**Comment by ArseniyShestakov** [comment]
Thank you. I'll test it in a few days on our CI and report back if something goes wrong.

**Comment by ArseniyShestakov** [comment]
Sorry for delay. I successfully generated installer using:
```
/usr/lib/mxe/usr/bin/i686-w64-mingw32.shared-cpack -D CPACK_NSIS_EXECUTABLE=/usr/lib/mxe/usr/bin/i686-w64-mingw32.shared-makensis
```

Though having some problem with installer not working, but this easily could be my own failure.

**Comment by ArseniyShestakov** [comment]
Update: everything is okay, it's just me copying it to Windows over SSH screwed something.
It's generate fine working installer! Thanks again for fixing it.
