### ISSUE TITLE
No rule to make target a QT Library

### ISSUE THREAD

**Issue by GianlucaBelardinelli** [mxe/mxe#1506]
I used MXE to cross compile form Linux to Windows but, when starting the command "make", I got an error that even from hours is still not solved .( Basically, I'm using x86_64-w64-mingw32.static from MXE and the command I run from inside of the project folder is:

 `sudo make MXE_TARGETS=x86_64-w64-mingw32.static/qt/bin/qmake && make`
and this is the error I get:

```
make -f Makefile.Debug
make[1]: Entering directory '/var/lib/jenkins/workspace/mcdu'
make[1]: *** No rule to make target '/home/myusername/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5OpenGLd.a', needed by 'debug/mcdu.exe'.  Stop.
make[1]: Leaving directory '/var/lib/jenkins/workspace/mcdu'
Makefile:34: recipe for target 'debug' failed
make: *** [debug] Error 2
```

I don't really know what I'm doing wrong. I also run before make clean then make command again but same error. For Linux, using local qmake is running with success!

Running on Ubuntu 16.04

**Comment by tonytheodore** [comment]
> sudo make MXE_TARGETS=x86_64-w64-mingw32.static/qt/bin/qmake && make

Please show the exact commands you used and the directories you ran them from. That command doesn't make sense for either MXE or qmake.

Note also, you shouldn't be using `sudo`

**Comment by tonytheodore** [comment]
You've run `*qmake` at some stage, but ignore that for the time being - debug libs aren't built by default and have only recently been enabled as an option. From the start:

```
# build qt5 with debug enabled
cd /path/to/mxe
make qt5 qtbase_CONFIGURE_OPTS=-debug-and-release MXE_TARGETS=x86_64-w64-mingw32.static

# prepare build dir for project
cd /path/to/your/project
mkdir x86_64-w64-mingw32.static.build && cd x86_64-w64-mingw32.static.build

# either of the following qmake invocations pointing to `..` where `*.pro` file exists
/path/to/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake ..
# or
x86_64-w64-mingw32.static-qmake-qt5 ..

# then the final build of your project
make
```

**Comment by tonytheodore** [comment]
Note you may need to run:
```
cd /path/to/mxe
touch src/qtbase.mk
```
first to ensure it is rebuilt.

**Comment by GianlucaBelardinelli** [comment]
> # either of the following qmake invocations pointing to `..` where `*.pro` file exists
> /path/to/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake .. 

I am sorry about that, @tonytheodore but I want to have more info about this point. I have the mcdu.pro file under /var/lib/jenkins/workspace/mdcu so what should I run with the command you linked above?

Thank you so much for your help, really!

**Comment by tonytheodore** [comment]
Hopefully the below is clearer with the directories as variables. The only command that needs to be run within a directory is `*-qmake` and that should be run from a temp build dir, not the project dir.

First check that qt5 is built with debug enabled by checking `pkg-config`:
```sh
$ x86_64-w64-mingw32.static-pkg-config --libs-only-l Qt5OpenGld
-lQt5OpenGLd -lQt5Widgetsd -lQt5Guid -lQt5Cored -lcomdlg32 -loleaut32 -limm32 -lopengl32 -ljpeg -lharfbuzz -lcairo -lgobject-2.0 -lfontconfig -lusp10 -lmsimg32 -lgdi32 -lpixman-1 -lffi -lexpat -lfreetype -lbz2 -lpng16 -lharfbuzz_too -lglib-2.0 -lwinmm -lshlwapi -lpcre -lintl -liconv -lpng -lole32 -luuid -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32 -lmpr -lz -lpcre16
```

If that returns the same libs, run the following:
```sh
export target=x86_64-w64-mingw32.static
export project_dir=/var/lib/jenkins/workspace/mdcu
export build_dir=$project_dir.build
rm -rf $build_dir
mkdir $build_dir
cd $build_dir && $target-qmake-qt5 $project_dir
make -C $build_dir debug
```

**Comment by GianlucaBelardinelli** [comment]
Woah, thank you so much for your help!
Should I run the first command in /home/gianluca/mxe where mxe is located or in my temp build dir: /usr/lib/var/jenkins/workspace/mcdu/x86_64-w64-mingw32.static ?

**Comment by tonytheodore** [comment]
If you have set MXE up correctly, it will be in your `$PATH` and you can run it from anywhere.

**Comment by GianlucaBelardinelli** [comment]
It doesn't :( I should haveee did someething wrong wuth that for suree...

**Comment by tonytheodore** [comment]
Please step through the [tutorial](http://mxe.cc/#tutorial) and open a new issue with specifics detailing the project you're trying to build.

**Comment by tonytheodore** [comment]
Mmm, that *.pro file isn't going to work with MXE (and is unlikely to work with upgrades to your compiler). You are putting compiler-version-specific references in there, the compiler is `msvc` so I don't think we can help.

**Comment by tonytheodore** [comment]
Try running `make release` from your project folder. You'll likely see other errors related to boost and/or freetype, but it should get you a little further.
