### ISSUE TITLE
Failed to build package ragel for target x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by illu11** [mxe/mxe#1510]
This is the guide that I used for qt5: http://askubuntu.com/questions/656219/building-a-windows-executable-in-qt-on-a-linux-system

After the third step I get this error: https://gist.github.com/illu11/3471a3eb1bda4529a943b21eb9dc28dd

**Comment by tonytheodore** [comment]
See #1511, it's a problem with stricter warnings in gcc 6.
