### ISSUE TITLE
Update pkg.mxe.cc packages

### ISSUE THREAD

**Issue by ooxi** [mxe/mxe#1516]
The current packages are build half a year ago. Maybe they could be updated? And providing i686 packages would be nice, too.

**Comment by starius** [comment]
I am going to update the binary packages.

> And providing i686 packages would be nice

Can some packages be shared across i686 and amd64? A typical cross-compiled library should work in both hosts. Unfortunately it is not trivial to determine if a package can be used this way. For example, Qt packages contain native binaries: rcc, moc, etc.

I will build full version of i686 this time not to break something.

**Comment by ooxi** [comment]
Most likely some packages can be shared between i686 and amd64 but the identification might be manual. The only way I can think of to automate the process would be to first do a complete i686 and amd64 build and then merge the binary identical packages (not sure if the savings in disc space is any where near worth the trouble, though).

Thanks for the fast feedback btw.!

**Comment by lereldarion** [comment]
Is it possible to enable the qt5 module in the poppler package ? It is missing in the current poppler package.

**Comment by starius** [comment]
[mxe-requirements](http://lists.nongnu.org/archive/html/mingw-cross-env-list/2016-07/msg00005.html) should be sorted out before rebuilding the packages. I propose to make whole package `mxe-requirements` a recommendation rather than a dependency. Or make all packages it depends on recommendations.

**Comment by starius** [comment]
Packages were [built](http://pkg.mxe.cc/releases/2016-10-12/build-pkg.log) and [tested against NPG-explorer](https://travis-ci.org/starius/npge/builds/169360848).
Permanent link to this release: http://pkg.mxe.cc/releases/2016-10-12/
(Default path http://pkg.mxe.cc/repos/ is pointing to the same directory currently.)
[Tag build-2016-10-12](https://github.com/mxe/mxe/tree/build-2016-10-12) was pushed to Github.

My apologies for releasing it so slow.

**Comment by ooxi** [comment]
Thanks for the updated build, [Violetland already compiled successfully](https://travis-ci.org/ooxi/violetland/builds/151300096)!
