### ISSUE TITLE
Build Fails for Package: libgda_i686-w64-mingw32.static

### ISSUE THREAD

**Issue by D3m0nKingx** [mxe/mxe#1524]
https://gist.github.com/D3m0nKingx/15157941c139e6171be154d231a0f01c

**Comment by starius** [comment]
I opened a PR which should fix this problem: https://github.com/mxe/mxe/issues/1524

**Comment by D3m0nKingx** [comment]
[download]  libgda
[build]     libgda                   i686-w64-mingw32.static
[done]      libgda                   i686-w64-mingw32.static                               113148 KiB     3m2.339s


Success, thank you :+1:

**Comment by D3m0nKingx** [comment]
New problem:

Makefile:483: recipe for target 'download-only-bzip2-1.0.6.tar.gz' failed
make: *** [download-only-bzip2-1.0.6.tar.gz] Error 1

https://gist.github.com/D3m0nKingx/976292df40445155052d35bc99b127bc

**Comment by starius** [comment]
Thank you for reporting! I moved it to another issue: https://github.com/mxe/mxe/issues/1552
Please open new issues for unrelated bugs.

**Comment by D3m0nKingx** [comment]
I don't understand. why this occured:

ader@UbuntuHP:~/mxe/mxe$ make
[build]     libgda                   i686-w64-mingw32.static

Failed to build package libgda for target i686-w64-mingw32.static!
------------------------------------------------------------
Makefile:619: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/ader/mxe/mxe/tmp-libgda-i686-w64-mingw32.static/libgda-4.2.13'
Makefile:602: recipe for target 'build-only-libgda_i686-w64-mingw32.static' failed
make[1]: *** [build-only-libgda_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory '/home/ader/mxe/mxe'
real	3m42.543s
user	5m12.484s
sys	0m26.604s
------------------------------------------------------------
[log]      /home/ader/mxe/mxe/log/libgda_i686-w64-mingw32.static

Makefile:602: recipe for target '/home/ader/mxe/mxe/usr/i686-w64-mingw32.static/installed/libgda' failed

------------------------------------------------------------
[log]      /home/ader/mxe/mxe/log/libgda_i686-w64-mingw32.static

Makefile:602: recipe for target '/home/ader/mxe/mxe/usr/i686-w64-mingw32.static/installed/libgda' failed
make: *** [/home/ader/mxe/mxe/usr/i686-w64-mingw32.static/installed/libgda] Error 1

**Comment by starius** [comment]
Probably you tried master branch without the pull request.
I have just merged it. I hope the problem was gone.

**Comment by D3m0nKingx** [comment]
Now there's some issue with the C compiler:
However I checked I am able to build 32bit executables in my 64 bit environment. which I tested quickly making a simple file:

 m32test.c:
```
// Minimal C example
#include <stdio.h>
int main()
{
   printf("This works\n");
   return 0;
}

```
then running:
```
gcc -m32 -o m32test m32test.c
```
and executing it:
```
ader@UbuntuHP:/tmp$ ./m32test 
This works
ader@UbuntuHP:/tmp$ 
```
```
ader@UbuntuHP:~/mxe$ make
[git-log]   2c8b747 Merge pull request #1551 from LuaAndC/libgda-perl
[build]     libgda                   i686-w64-mingw32.static

Failed to build package libgda for target i686-w64-mingw32.static!
------------------------------------------------------------
configure: error: in `/home/ader/mxe/tmp-libgda-i686-w64-mingw32.static/libgda-4.2.13':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:602: recipe for target 'build-only-libgda_i686-w64-mingw32.static' failed
make[1]: *** [build-only-libgda_i686-w64-mingw32.static] Error 77
make[1]: Leaving directory '/home/ader/mxe'
real	0m16.313s
user	0m14.044s
sys	0m0.916s
------------------------------------------------------------
[log]      /home/ader/mxe/log/libgda_i686-w64-mingw32.static

Makefile:602: recipe for target '/home/ader/mxe/usr/i686-w64-mingw32.static/installed/libgda' failed
make: *** [/home/ader/mxe/usr/i686-w64-mingw32.static/installed/libgda] Error 1
```

Config.log:
https://gist.github.com/D3m0nKingx/4cfa9f5005ffea5ff6e04fd66d6fe947

Hope you can sort this one out bro :/

**Comment by starius** [comment]
Please upload file /home/ader/mxe/log/libgda_i686-w64-mingw32.static

**Comment by starius** [comment]
Error message from config.log looks strange.

MXE cross-compiles target packages (including libgda) with an internal gcc, not with a system gcc. (The system gcc is still needed to build internal gcc and native packages, e.g. cmake.) The internal gcc is built by `make gcc`. All target packages (including libgda) depend on the internal gcc package, so you are likely to have it built. The file is `./usr/bin/i686-w64-mingw32.static-gcc`. Can you compile your minimal C example (m32test.c) with it, please?

```
./usr/bin/i686-w64-mingw32.static-gcc m32test.c
```

It works for me. If it does not work for you, something is wrong with the internal compiler. In this case you can rebuild everything from scratch in clean clone of MXE.

**Comment by D3m0nKingx** [comment]
after executing the command:
```
ader@UbuntuHP:~/mxe$ ./usr/bin/i686-w64-mingw32.static-gcc m32test.c
/tmp/cc88t5fH.s: Assembler messages:
/tmp/cc88t5fH.s:2: Error: unknown pseudo-op: `.def'
/tmp/cc88t5fH.s:2: Error: unknown pseudo-op: `.scl'
/tmp/cc88t5fH.s:2: Error: Missing symbol name in directive
/tmp/cc88t5fH.s:2: Error: unrecognized symbol type "32"
/tmp/cc88t5fH.s:2: Error: unknown pseudo-op: `.endef'
/tmp/cc88t5fH.s:3: Fatal error: bad .section directive: want a,l,w,x,M,S,G,T in string
ader@UbuntuHP:~/mxe$ 
```

**Comment by starius** [comment]
Clone MXE to another directory and try there.

```
git clone https://github.com/mxe/mxe mxe2
cd mxe2
make gcc
./usr/bin/i686-w64-mingw32.static-gcc m32test.c
```

**Comment by D3m0nKingx** [comment]
the output created an executabe 'a.exe'

**Comment by starius** [comment]
Probably libgda issue is solved as well. Try `make libgda`

**Comment by D3m0nKingx** [comment]
​Correct. I will try again soon. thank you for the update.

**Comment by D3m0nKingx** [comment]
It works now thank you!

**Comment by D3m0nKingx** [comment]
Also is there any significant difference installing mxe as 32-bit or 64-bit, performance wise or anything?

**Comment by starius** [comment]
Please open new issues for unrelated bugs.
I have moved your new question to https://github.com/mxe/mxe/issues/1555
