### ISSUE TITLE
Building openssl fails with commit 3198f4432d2aa1f37e501bdf74899594fd8d8f7b and dynamic linking

### ISSUE THREAD

**Issue by Hullu2000** [mxe/mxe#1526]
https://gist.github.com/Hullu2000/b25f364a5db67ea2534453dd3eacea0c

While building qtbase openssl builds perfectly with static linkin but fails with dynamic. I had to revert this commit to get it to build.

**Comment by mabrand** [comment]
I think you meant commit 2140afda262f9395b6a42a0649f35ca4de254406.
It should be fixed in a0c57d032b627e853da1726369c59b725212e8bb.
