### ISSUE TITLE
luajit: missing system dependencies

### ISSUE THREAD

**Issue by rtkt** [mxe/mxe#1531]
Hi, there are two undeclared system dependencies for luajit:
1)  32 bit glibc's headers (/usr/include/gnu/stubs-32.h file to be exact)
Package failed to build with [this ending](https://gist.github.com/rtkt/3d36a8a45d1014770a4af7b329fc29e4)
Installation of glibc-devel-32bit fixed this problem
2) 32bit gcc (missing libgcc)
Package failed to build with [this ending](https://gist.github.com/rtkt/a0d2137fd5f7873a83f6fe66f421bf1e)
Installation of gcc-32bit fixed this problem.

OS: openSUSE Tumbleweed, x64

**Comment by starius** [comment]
[MXE requirements for openSUSE](http://mxe.cc/#requirements-opensuse) include both packages (glibc-devel-32bit and gcc-32bit).
Script `tools/install-deps` should install these packages automatically if run on openSUSE x64.

**Comment by rtkt** [comment]
Sorry, I didn't know
