### ISSUE TITLE
binary dpkg CGAL .static package actually contains shared .dll s

### ISSUE THREAD

**Issue by donbright** [mxe/mxe#1535]
I followed the instructions on 

http://pkg.mxe.cc/

and i downloaded the mxe-x86-64-w64-mingw32.static-cgal debian package but it appears to not contain the static libraries, only shared .dlls

```
don@aloo:~/openscad$ dpkg --listfiles mxe-x86-64-w64-mingw32.static-cgal | grep libcgal -i
/usr/lib/mxe/usr/x86_64-w64-mingw32.static/bin/libCGAL_Core.dll
/usr/lib/mxe/usr/x86_64-w64-mingw32.static/bin/libCGAL_Qt4.dll
/usr/lib/mxe/usr/x86_64-w64-mingw32.static/bin/libCGAL.dll
/usr/lib/mxe/usr/x86_64-w64-mingw32.static/bin/libCGAL_ImageIO.dll
/usr/lib/mxe/usr/x86_64-w64-mingw32.static/lib/libCGAL_ImageIO.dll.a
/usr/lib/mxe/usr/x86_64-w64-mingw32.static/lib/libCGAL_Core.dll.a
/usr/lib/mxe/usr/x86_64-w64-mingw32.static/lib/libCGAL.dll.a
/usr/lib/mxe/usr/x86_64-w64-mingw32.static/lib/libCGAL_Qt4.dll.a

```

I compared this to a system that was compiled from source, which shows the proper static libraries

```
don@vecher:~/openscad/scripts$ find /home/don/openscad_deps/mxe/ | grep libCGAL
/home/don/openscad_deps/mxe/usr/i686-w64-mingw32.static/lib/libCGAL.a
/home/don/openscad_deps/mxe/usr/i686-w64-mingw32.static/lib/libCGAL_Core.a
/home/don/openscad_deps/mxe/usr/i686-w64-mingw32.static/lib/libCGAL_Qt4.a
/home/don/openscad_deps/mxe/usr/i686-w64-mingw32.static/lib/libCGAL_ImageIO.a
/home/don/openscad_deps/mxe/usr/x86_64-w64-mingw32.static/lib/libCGAL.a
/home/don/openscad_deps/mxe/usr/x86_64-w64-mingw32.static/lib/libCGAL_Core.a
/home/don/openscad_deps/mxe/usr/x86_64-w64-mingw32.static/lib/libCGAL_Qt4.a
/home/don/openscad_deps/mxe/usr/x86_64-w64-mingw32.static/lib/libCGAL_ImageIO.a

```

This is not exacly the same problem as  #1402 but is possibly related.

Thanks

**Comment by starius** [comment]
Binary files are older than fix for #1402 :(
I am going to rebuild them soon.

**Comment by donbright** [comment]
thanks, how much machine time is required to rebuild entire tree?

**Comment by starius** [comment]
For me it takes several days. I hope to make new release by the weekend.

**Comment by donbright** [comment]
how much RAM and disk space? thanks.

**Comment by starius** [comment]
Ram depends on number of parallel jobs. 8 gigs should be enough for 4 jobs.
Disk space depends on whether you use build-pkg (and building Debian
packages) or just building everything with 'make'. The former needs 100
gigs, the latter 30 gigs. Resulting files in case of packages are
compressed and are within 10 gigs.

13 окт. 2016 г. 1:23 пользователь "don bright" <notifications@github.com>
написал:

**Comment by donbright** [comment]
weird error i got trying to build

`root@ubuntu-64gb-nyc2-01:/usr/lib/mxe# lua tools/build-pkg.lua
lua: tools/build-pkg.lua:1067: Remove usr/
stack traceback:
	[C]: in function 'assert'
	tools/build-pkg.lua:1067: in function 'main'
	tools/build-pkg.lua:1120: in main chunk
	[C]: in ?
`

**Comment by starius** [comment]
Build-pkg builds all packages from scratch, that is why existing usr/
directory should be removed before building. Ideally this should happen in
/usr/lib/mxe to get the same layout of filed as in official binary
distribution.

14 окт. 2016 г. 1:18 пользователь "don bright" <notifications@github.com>
написал:

weird error i got trying to build

root@ubuntu-64gb-nyc2-01:/usr/lib/mxe# lua tools/build-pkg.lua
lua: tools/build-pkg.lua:1067: Remove usr/
stack traceback:
[C]: in function 'assert'
tools/build-pkg.lua:1067: in function 'main'
tools/build-pkg.lua:1120: in main chunk
[C]: in ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mxe/mxe/issues/1535#issuecomment-253676363>, or mute
the thread

**Comment by starius** [comment]
Finally binary packages were built. See https://github.com/mxe/mxe/issues/1516#issuecomment-255243424
My apologies for releasing it so slow.

Now cgal static packages contains no DLL files.
(It can be verified from [the file with package contents](http://pkg.mxe.cc/releases/2016-10-12/list/mxe-i686-w64-mingw32.static/mxe-i686-w64-mingw32.static-cgal.list).)

**Comment by donbright** [comment]
thank you very much, very helpful for OpenSCAD
