### ISSUE TITLE
download from backup appends to file from previous attempt

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1552]
See https://github.com/mxe/mxe/issues/1524#issuecomment-255623701

I reproduced this issue locally.

First URL http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz is very slow at the moment and can not output whole file until timeout (30 seconds). wget tries 3 times (option `-t 3` of wget) and fails them all, after it tries to download from backup server: http://s3.amazonaws.com/mxe-pkg/bzip2%2D1%2E0%2E6%2Etar%2Egz The file is downloaded in few seconds, but checksum fails.

Correct file bzip2-1.0.6.tar.gz has size 782025 bytes, but the file got has size 924991 bytes. Checked both files with `tail` and `head`, I see that they have equal prefix and suffix. Probably, subsequent download attempts append to old file instead of overwriting it.

**Comment by D3m0nKingx** [comment]
Is it downloading it to the /tmp directory? what if I manually download the correct file and place it in the tmp folder?

**Comment by D3m0nKingx** [comment]
bzip2-1.0.6.tar.gz Failed - Network error
http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz

I tried downloading manually in chrome... it failed lol, will the one from amazon server work?

**Comment by starius** [comment]
> will the one from amazon server work?

It works here.

**Comment by D3m0nKingx** [comment]
Worked here too, just passed it during compile :) Thank you

I'll let you know if anything else comes up.
