### ISSUE TITLE
Failed to build package qt for target i686-w64-mingw32.shared

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1554]
This for clean MXE installation.
https://gist.github.com/pavelvat/2a4ed4911ab2fd439154ba7dd044145a

**Comment by starius** [comment]
The error is as follows:

```
cc1: error: one or more PCH files were found, but they were invalid
cc1: error: use -Winvalid-pch for more information
cc1: fatal error: .obj/release-shared/qt_pch.h: No such file or directory
```

Probably it is a result of using gcc 6 on host.
See https://github.com/mxe/mxe/issues/1103
See https://github.com/mxe/mxe/pull/1527#issuecomment-254001204

**Comment by starius** [comment]
Can you apply https://github.com/mxe/mxe/pull/1557 and build `qt` and `qtbase` on a system with GCC 6, please?

**Comment by starius** [comment]
Can you apply https://github.com/mxe/mxe/pull/1557 and build `qt` and `qtbase` on a system with GCC 6, please?

**Comment by pavelvat** [comment]
This patch fix qtbase.
qt still fail: http://pastebin.com/Sinjnppw

**Comment by starius** [comment]
I have updated https://github.com/mxe/mxe/pull/1557 (added commit "qt 4: backport patch for -no-pch from qtbase 5.7.0").

Does it work now?

**Comment by pavelvat** [comment]
>Does it work now?

Yes, it does.

**Comment by starius** [comment]
Fixed in https://github.com/mxe/mxe/pull/1557
