### ISSUE TITLE
libzip header zipconf.h is installed in wrong location

### ISSUE THREAD

**Issue by razor5k** [mxe/mxe#1565]
replace
 $(MAKE) -C '$(1)' -j '$(JOBS)' install $(MXE_DISABLE_CRUFT) SUBDIRS=lib
with
 $(MAKE) -C '$(1)' -j '$(JOBS)' install $(MXE_DISABLE_CRUFT) SUBDIRS=lib libincludedir='$(PREFIX)/$(TARGET)/include'
to install the zipconf.h header in the correct location. So the zip.h header is able to find the zipconf.h header.

**Comment by starius** [comment]
Currently libzip installs the following files:

```
$ cat mxe-x86-64-w64-mingw32.static-libzip.list 
usr/x86_64-w64-mingw32.static/bin/test-libzip.exe
usr/x86_64-w64-mingw32.static/include/zip.h
usr/x86_64-w64-mingw32.static/installed/libzip
usr/x86_64-w64-mingw32.static/lib/libzip.a
usr/x86_64-w64-mingw32.static/lib/libzip.la
usr/x86_64-w64-mingw32.static/lib/libzip/include/zipconf.h
usr/x86_64-w64-mingw32.static/lib/pkgconfig/libzip.pc
```

`libzip.pc` defines `libincludedir=${exec_prefix}/lib/libzip/include` and sets `Cflags: -I${includedir} -I${libincludedir}`. If `pkg-config` is used to generate compiler flags, then the zip.h header is able to find the zipconf.h header.

Many libraries put config headers to `lib/` directory:

```
$ find usr/x86_64-w64-mingw32.static/lib -name '*.h'                                                                                             
usr/x86_64-w64-mingw32.static/lib/giomm-2.4/include/giommconfig.h
usr/x86_64-w64-mingw32.static/lib/gtkglext-1.0/include/gdkglext-config.h
usr/x86_64-w64-mingw32.static/lib/glibmm-2.4/include/glibmmconfig.h
usr/x86_64-w64-mingw32.static/lib/sigc++-2.0/include/sigc++config.h
usr/x86_64-w64-mingw32.static/lib/gtkmm-2.4/include/gtkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/gdkmm-3.0/include/gdkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/atkmm-1.6/include/atkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/wx/include/x86_64-w64-mingw32.static-msw-unicode-static-3.0/wx/msw/rcdefs.h
usr/x86_64-w64-mingw32.static/lib/wx/include/x86_64-w64-mingw32.static-msw-unicode-static-3.0/wx/setup.h
usr/x86_64-w64-mingw32.static/lib/libffi-3.2.1/include/ffitarget.h
usr/x86_64-w64-mingw32.static/lib/libffi-3.2.1/include/ffi.h
usr/x86_64-w64-mingw32.static/lib/gdkmm-2.4/include/gdkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/dbus-1.0/include/dbus/dbus-arch-deps.h
usr/x86_64-w64-mingw32.static/lib/gtkmm-3.0/include/gtkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/gtksourceviewmm-2.0/include/gtksourceviewmmconfig.h
usr/x86_64-w64-mingw32.static/lib/libxml++-2.6/include/libxml++config.h
usr/x86_64-w64-mingw32.static/lib/libgdamm-4.0/include/libgdammconfig.h
usr/x86_64-w64-mingw32.static/lib/glib-2.0/include/glibconfig.h
usr/x86_64-w64-mingw32.static/lib/gtk-2.0/include/gdkconfig.h
usr/x86_64-w64-mingw32.static/lib/gstreamer-1.0/include/gst/gstconfig.h
usr/x86_64-w64-mingw32.static/lib/pangomm-1.4/include/pangommconfig.h
usr/x86_64-w64-mingw32.static/lib/cairomm-1.0/include/cairommconfig.h
usr/x86_64-w64-mingw32.static/lib/libzip/include/zipconf.h
usr/x86_64-w64-mingw32.static/lib/gtkglextmm-1.2/include/gdkglextmm-config.h
```

If we change config header location for libzip to `include/` directory, we will have to change it for all them as well.

**Comment by razor5k** [comment]
Thank you for that information. Then this is no bug but intentional and I will also use pkg-config to solve the header include issue. So the bug can be closed.
 

Gesendet: Freitag, 04. November 2016 um 20:29 Uhr
Von: "Boris Nagaev" <notifications@github.com>
An: mxe/mxe <mxe@noreply.github.com>
Cc: razor5k <razor5000@web.de>, Author <author@noreply.github.com>
Betreff: Re: [mxe/mxe] libzip header zipconf.h is installed in wrong location (#1565)


Currently libzip installs the following files:

$ cat mxe-x86-64-w64-mingw32.static-libzip.list 
usr/x86_64-w64-mingw32.static/bin/test-libzip.exe
usr/x86_64-w64-mingw32.static/include/zip.h
usr/x86_64-w64-mingw32.static/installed/libzip
usr/x86_64-w64-mingw32.static/lib/libzip.a
usr/x86_64-w64-mingw32.static/lib/libzip.la
usr/x86_64-w64-mingw32.static/lib/libzip/include/zipconf.h
usr/x86_64-w64-mingw32.static/lib/pkgconfig/libzip.pc


libzip.pc defines libincludedir=${exec_prefix}/lib/libzip/include and sets Cflags: -I${includedir} -I${libincludedir}. If pkg-config is used to generate compiler flags, then the zip.h header is able to find the zipconf.h header.

Many libraries put config headers to lib/ directory:

$ find usr/x86_64-w64-mingw32.static/lib -name '*.h'                                                                                             
usr/x86_64-w64-mingw32.static/lib/giomm-2.4/include/giommconfig.h
usr/x86_64-w64-mingw32.static/lib/gtkglext-1.0/include/gdkglext-config.h
usr/x86_64-w64-mingw32.static/lib/glibmm-2.4/include/glibmmconfig.h
usr/x86_64-w64-mingw32.static/lib/sigc++-2.0/include/sigc++config.h
usr/x86_64-w64-mingw32.static/lib/gtkmm-2.4/include/gtkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/gdkmm-3.0/include/gdkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/atkmm-1.6/include/atkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/wx/include/x86_64-w64-mingw32.static-msw-unicode-static-3.0/wx/msw/rcdefs.h
usr/x86_64-w64-mingw32.static/lib/wx/include/x86_64-w64-mingw32.static-msw-unicode-static-3.0/wx/setup.h
usr/x86_64-w64-mingw32.static/lib/libffi-3.2.1/include/ffitarget.h
usr/x86_64-w64-mingw32.static/lib/libffi-3.2.1/include/ffi.h
usr/x86_64-w64-mingw32.static/lib/gdkmm-2.4/include/gdkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/dbus-1.0/include/dbus/dbus-arch-deps.h
usr/x86_64-w64-mingw32.static/lib/gtkmm-3.0/include/gtkmmconfig.h
usr/x86_64-w64-mingw32.static/lib/gtksourceviewmm-2.0/include/gtksourceviewmmconfig.h
usr/x86_64-w64-mingw32.static/lib/libxml++-2.6/include/libxml++config.h
usr/x86_64-w64-mingw32.static/lib/libgdamm-4.0/include/libgdammconfig.h
usr/x86_64-w64-mingw32.static/lib/glib-2.0/include/glibconfig.h
usr/x86_64-w64-mingw32.static/lib/gtk-2.0/include/gdkconfig.h
usr/x86_64-w64-mingw32.static/lib/gstreamer-1.0/include/gst/gstconfig.h
usr/x86_64-w64-mingw32.static/lib/pangomm-1.4/include/pangommconfig.h
usr/x86_64-w64-mingw32.static/lib/cairomm-1.0/include/cairommconfig.h
usr/x86_64-w64-mingw32.static/lib/libzip/include/zipconf.h
usr/x86_64-w64-mingw32.static/lib/gtkglextmm-1.2/include/gdkglextmm-config.h


If we change config header location for libzip to include/ directory, we will have to change it for all them as well.
