### ISSUE TITLE
msmtp fails to build...

### ISSUE THREAD

**Issue by andrew-strong** [mxe/mxe#1567]
I am new to mxe and cannot build my first new package: msmtp. Steps I have taken:

 1. Created the msmtp.mk file, copying from [here..](https://github.com/maximeh/buildroot/blob/master/package/msmtp/msmtp.mk).

 2. Added the details to doc/index.html file

 3. Ran the following command:
```
andrew@ilium~/test/mxe$ make msmtp                                                                    
[using autodetected 6 job(s)]
[no-build]  msmtp                    i686-w64-mingw32.static
andrew@ilium~/test/mxe$ 
```

So no generated executable file... Log shows:
```

make[1]: Entering directory '/home/andrew/test/mxe'
touch '/home/andrew/test/mxe/usr/i686-w64-mingw32.static/installed/msmtp'
make[1]: Leaving directory '/home/andrew/test/mxe'

real	0m4.601s
user	0m4.501s
sys	0m0.105s
```

I suspect I am missing something basic here, if so my apologies...

**Comment by andrew-strong** [comment]
Hmmm... looks like that is not actually a file intended for mxe? Does anybody have such a file for msmtp or perhaps I will need to start building my own...

**Comment by starius** [comment]
File https://github.com/maximeh/buildroot/blob/master/package/msmtp/msmtp.mk does not looks like a file for MXE.

> I will need to start building my own

You can use tools/skeleton.py to automate most of the routine inclusing updating docs/index.html

See http://mxe.cc/#creating-packages

**Comment by andrew-strong** [comment]
OK so a little closer now. I have created my own msmtp.mk file:

http://pastebin.com/2t43TgnW

And now the process seems complete:

```
andrew@athens:~/mxe$ make msmtp
[using autodetected 6 job(s)]
[build]     msmtp                    i686-w64-mingw32.static
[done]      msmtp                    i686-w64-mingw32.static     2244 KiB       0m10.273s
andrew@athens:~/mxe
```
Dependencies were all downloaded and built previously. But I cannot find the msmtp executable:
```
andrew@athens:~/mxe$ find . -name msmtp
./usr/i686-w64-mingw32.static/installed/msmtp
andrew@athens:~/mxe$
```
I have posted the log here:

http://pastebin.com/trwzw4SA

I am so close now :)

**Comment by andrew-strong** [comment]
The good news is that msmtp 1.6.5 has compiled fine against the MXE static libraries and I have my executable. So just my packaging of the msmtp.mk is awry....

**Comment by starius** [comment]
You can open a pull request to add it.

Please replace `cd '$(1)' && ./configure \` with `cd '$(BUILD_DIR)' && $(SOURCE_DIR)/configure \` and adjust `make` command. (Use out-of-tree builds when possible.)

Please replace `--host='$(TARGET)' --prefix='$(PREFIX)/$(TARGET)'` with `$(MXE_CONFIGURE_OPTS)`.

Please split build and install. Build with `-j $(JOBS)` and install with `-j 1`.

> find . -name msmtp

A program is likely to have `.exe` in its name.

> But I cannot find the msmtp executable

You disabled installation of executables by `bin_PROGRAMS= sbin_PROGRAMS= noinst_PROGRAMS=`. Use macro `$(MXE_DISABLE_CRUFT)` instead of them. Is this package a library or a program? If it is a library, it should not install executables, except `test-<pkg>.exe` for testing. If it is a program, you should put it into `plugins/apps` instead of `src`. If it is both, you can add two packages with different names: one in `src` and one in `plugins/apps`.

**Comment by andrew-strong** [comment]
msmtp is in fact a program not a library. I have produced a successful package using the 'older' syntax:

```
# This file is part of MXE. See LICENSE.md for licensing information.

PKG             := msmtp
$(PKG)_IGNORE   :=
$(PKG)_VERSION  := 1.6.5
$(PKG)_CHECKSUM := 76a0d60693c7e65d0c7a12f01d300882d280b1e1be0202f54730ae44d44a5006
$(PKG)_SUBDIR   := $(PKG)-$($(PKG)_VERSION)
$(PKG)_FILE     := $(PKG)-$($(PKG)_VERSION).tar.xz
$(PKG)_URL      := http://$(SOURCEFORGE_MIRROR)/project/$(PKG)/$(PKG)/$($(PKG)_VERSION)/$($(PKG)_FILE)
$(PKG)_DEPS     := gcc libidn libgsasl gnutls libiconv libgpg_error libgcrypt libntlm

define $(PKG)_UPDATE
    $(WGET) -q -O- 'http://sourceforge.net/projects/msmtp/files/msmtp/' | \
    $(SED) -n 's,.*/\([0-9][^"]*\)/".*,\1,p' | \
    head -1
endef

define $(PKG)_BUILD
    cd '$(1)' && ./configure \
        $(MXE_CONFIGURE_OPTS) \
        --disable-nls \
        --without-libsecret \
        --without-macosx-keyring \
        --with-tls=gnutls \
        --with-libidn
    $(MAKE) -C '$(1)' -j '$(JOBS)'
    $(MAKE) -C '$(1)' -j 1 install
endef
```
which is very gratifying! I will grep through the other *.mk files and find an example of `cd '$(BUILD_DIR)' && $(SOURCE_DIR)/configure \ ` to emulate. Some fine tuning I know before I can pull to MXE for formal inclusion but I am very happy to have it working even if in a slightly clunky fashion :)

**Comment by andrew-strong** [comment]
OK I have reworked the whole thing and the following works perfectly on my end:

```
# This file is part of MXE. See LICENSE.md for licensing information.

PKG             := msmtp
$(PKG)_IGNORE   :=
$(PKG)_VERSION  := 1.6.5
$(PKG)_CHECKSUM := 76a0d60693c7e65d0c7a12f01d300882d280b1e1be0202f54730ae44d44a5006
$(PKG)_SUBDIR   := $(PKG)-$($(PKG)_VERSION)
$(PKG)_FILE     := $(PKG)-$($(PKG)_VERSION).tar.xz
$(PKG)_URL      := http://$(SOURCEFORGE_MIRROR)/project/$(PKG)/$(PKG)/$($(PKG)_VERSION)/$($(PKG)_FILE)
$(PKG)_DEPS     := gcc libidn libgsasl gnutls libiconv libgpg_error libgcrypt libntlm

define $(PKG)_UPDATE
    $(WGET) -q -O- 'http://sourceforge.net/projects/msmtp/files/msmtp/' | \
    $(SED) -n 's,.*/\([0-9][^"]*\)/".*,\1,p' | \
    head -1
endef

define $(PKG)_BUILD
    cd '$(BUILD_DIR)' && '$(SOURCE_DIR)/configure' \
        $(MXE_CONFIGURE_OPTS) \
        --disable-nls \
        --without-libsecret \
        --without-macosx-keyring \
        --with-tls=gnutls \
        --with-libidn
    $(MAKE) -C $(BUILD_DIR) -j '$(JOBS)'
    $(MAKE) -C $(BUILD_DIR) -j 1 install
endef
```

Have I missed anything? If not I will have a shot at the pull process...

**Comment by starius** [comment]
The source looks good to me. Not tested.

Set `$(PKG)_OWNER := https://github.com/andrew-strong`
It means that you use this package and you can help with possible issues with the package in the future (e.g. help updating it to new version).

Feel free to open a pull request.

**Comment by andrew-strong** [comment]
Thanks starius for guiding me through this process :)
