### ISSUE TITLE
'ml' not found - earlier boost versions fail to build

### ISSUE THREAD

**Issue by ksynb** [mxe/mxe#1574]
Attempting to build boost >= 1.55, the following error occurs:

Jamfile</home/xcomp/dev/mxe/tmp-boost-i686-w64-mingw32.static/boost_1_58_0/libs/context/build>.masm bin.v2/libs/context/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/link-static/target-os-windows/threadapi-win32/threading-multi/asm/make_i386_ms_pe_masm.o
/bin/sh: 2: ml: not found

    ml /c /Fo"bin.v2/libs/context/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/link-static/target-os-windows/threadapi-win32/threading-multi/asm/make_i386_ms_pe_masm.o" "libs/context/src/asm/make_i386_ms_pe_masm.asm"

...failed Jamfile</home/xcomp/dev/mxe/tmp-boost-i686-w64-mingw32.static/boost_1_58_0/libs/context/build>.masm bin.v2/libs/context/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/link-static/target-os-windows/threadapi-win32/threading-multi/asm/make_i386_ms_pe_masm.o

What I'm attempting to build requires earlier versions of boost.  Has anyone else encountered this and if so, found a solution?

**Comment by starius** [comment]
I reverted boost to 1.57 (before fdd5b9f7aa8bf0e40c1f1f8119701af96e51457e) locally.

```
git checkout 49a753be3bdd5a511cd6807d1f0f8db52cdfcf5e src/boost.mk src/boost-1-fixes.patch
```

It builds here.

**Comment by ksynb** [comment]
That did indeed build, starius.  Thank you very much.  Would it be trivial to create a similar patch for 1.55?

**Comment by starius** [comment]
It was updated from 1.53 to 1.57 in https://github.com/mxe/mxe/commit/fc36ca160af70952dd320f0cc185f8eb6c43df2e
You can try to revert back to 1.53 by
```
git checkout 6d28d3748550bce3200010553d7ada43640c0684 src/boost.mk
rm src/boost-1-fixes.patch
```
and setting
```
$(PKG)_CHECKSUM := f88a041b01882b0c9c5c05b39603ec8383fb881f772f6f9e6e6fd0e0cddb9196
```
in boost.mk

**Comment by starius** [comment]
@ksynb 
Does it solve your problem?

Does it fails with current version of boost (1.60)? If yes, can you share what is your setup?
