### ISSUE TITLE
cmake unable to find OpenCV

### ISSUE THREAD

**Issue by GuLinux** [mxe/mxe#1576]
Hello,
My application with cmake build system is unable to correctly find OpenCV.

This is the cmake error message:

~~~~
-- OpenCV ARCH: x86
-- OpenCV RUNTIME: mingw
-- OpenCV STATIC: ON
CMake Warning at /mxe/usr/x86_64-w64-mingw32.static/OpenCVConfig.cmake:161 (message):
  Found OpenCV Windows Pack but it has not binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:25 (find_package)


CMake Error at CMakeLists.txt:25 (find_package):
  Found package configuration file:

    /mxe/usr/x86_64-w64-mingw32.static/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.
~~~~

What's a bit strange is the architecture is detected to be x86, not x86_64. I will try with the 32bit version too, just in case.

**Comment by starius** [comment]
MXE provides cmake and cmake wrapper (`mxe/usr/bin/$(TARGET)-cmake`).
 Do you use it or system-wide cmake (e.g., `/usr/bin/cmake`)?

**Comment by GuLinux** [comment]
I forgot to specify, but yes, I'm using the wrapper

**Comment by GuLinux** [comment]
I can confirm that the same error appears on i686 too

**Comment by beamerkun** [comment]
looked a bit into the issue - OpenCVConfig.cmake files that are result of mxe build still expect libs and config files to land under ../${OpenCV_ARCH}/${OpenCV_VERSION}/(lib|staticlib). There are patches to build system that change output dirs, so it's just a matter of making patch complete and reflect those changes in .cmake files.
I'm gonna to need this personally, so in a few days I'll submit a pull request for this
