### ISSUE TITLE
Failed to update docs/versions.json when plugins are used

### ISSUE THREAD

**Issue by tehnick** [mxe/mxe#1580]
$ LC_ALL=C make MXE_PLUGIN_DIRS=plugins/gcc6 docs/versions.json
make: *** No rule to make target 'src/gcc6-overlay.mk', needed by 'docs/versions.json'.  Stop.

Any idea how to fix this?

**Comment by starius** [comment]
It should be fixed in https://github.com/LuaAndC/mxe/commit/8babea394878b670eb0edd9b985ddef46622ac5f (pull request https://github.com/mxe/mxe/pull/1583).

**Comment by tehnick** [comment]
Thanks!
