### ISSUE TITLE
cmake creates ~/.cmake

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1585]
```
$ cd ~/.cmake
$ find
.
./packages
./packages/cppnetlib
./packages/cppnetlib/e35a156f4a9dbf7127996645635b21da
./packages/cppnetlib/977835979753f52dee0acdfa78a21984
./packages/cppnetlib/ddb7553d0f188d1c97284ae584ff6c7d
./packages/yaml-cpp
./packages/yaml-cpp/f2be7d62b1e3907afef29456653bdd37
./packages/yaml-cpp/99da36886f7ba3c29302d0c166945488
./packages/glm
./packages/glm/486aef86d3e079282ccbbcd75e0d5b36
./packages/glm/dfc63164dc234bf84b4934ecb8d1f24b
./packages/glm/bdf2f588f67b90e4eca484ffca74708f
./packages/glm/691d25f8f3dc433a50b1a459289556f4
./packages/libwebsockets
./packages/libwebsockets/6da17edf4139463a3f7ed1bb7285159b
./packages/libwebsockets/0f407eda18036d744e40093d18ac4b15
```

MXE should not create files outside of its directory (and maybe `/tmp`).

**Comment by starius** [comment]
See https://cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html
I think, it makes sense to move this directory from `~/.cmake/packages` to `usr/<target>/cmake/packages`. CMake can be patched for this.

Some of packages creating these file use MXE cmake, but other use system cmake. The later should be changed to use MXE cmake.

**Comment by tonytheodore** [comment]
These files reference the build directory so there's no real point in moving them under `usr/`. #1639  disables the installation of them.
