### ISSUE TITLE
freetds fails

### ISSUE THREAD

**Issue by Axe-Usa** [mxe/mxe#1596]
freetds fails when i try to download and install

distro: kali linux

logfile:

> --2016-12-17 00:22:54--  ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.23.tar.bz2
>            => “/home/omar/Escritorio/mxe/pkg/.tmp-freetds-1.00.23.tar.bz2”
> Resolviendo ftp.freetds.org (ftp.freetds.org)... 38.117.134.18
> Conectando con ftp.freetds.org (ftp.freetds.org)[38.117.134.18]:21... conectado.
> Identificándose como anonymous ... 
> Error en la respuesta del servidor, cerrando la conexión de control.
> Reintentando.
> 
> --2016-12-17 00:23:18--  ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.23.tar.bz2
>   (intento: 2) => “/home/omar/Escritorio/mxe/pkg/.tmp-freetds-1.00.23.tar.bz2”
> Conectando con ftp.freetds.org (ftp.freetds.org)[38.117.134.18]:21... conectado.
> Identificándose como anonymous ... 
> Error en la respuesta del servidor, cerrando la conexión de control.
> Reintentando.
> 
> --2016-12-17 00:23:39--  ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.23.tar.bz2
>   (intento: 3) => “/home/omar/Escritorio/mxe/pkg/.tmp-freetds-1.00.23.tar.bz2”
> Conectando con ftp.freetds.org (ftp.freetds.org)[38.117.134.18]:21... conectado.
> Identificándose como anonymous ... 
> Error en la respuesta del servidor, cerrando la conexión de control.
> Abandonando.
> 
> MXE Warning! Downloading freetds from backup.
> --2016-12-17 00:23:59--  http://s3.amazonaws.com/mxe-pkg/freetds%2D1%2E00%2E23%2Etar%2Ebz2
> Resolviendo s3.amazonaws.com (s3.amazonaws.com)... 54.231.49.67
> Conectando con s3.amazonaws.com (s3.amazonaws.com)[54.231.49.67]:80... conectado.
> Petición HTTP enviada, esperando respuesta... 404 Not Found
> 2016-12-17 00:24:01 ERROR 404: Not Found.
> 
> --2016-12-17 00:24:01--  http://d1yihgixbnrglp.cloudfront.net/freetds%2D1%2E00%2E23%2Etar%2Ebz2
> Resolviendo d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)... 54.230.216.157, 54.230.216.109, 54.230.216.205, ...
> Conectando con d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)[54.230.216.157]:80... conectado.
> Petición HTTP enviada, esperando respuesta... 404 Not Found
> 2016-12-17 00:24:03 ERROR 404: Not Found.
> 
> 
> Download failed!

Anyways freetds show error in xml so i think the problem is the url or something:

> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>freetds-1.00.23.tar.bz2</Key><RequestId>DE01AE057B03BDAB</RequestId><HostId>5Mxgbagwj8RrPiuciu2D2K9+I/XQOqVQqJjc3usg9I1LaJUClG9GRDgpq8b6dq4R0qVMFKXJ054=</HostId></Error>

I tried to download of other site and install but i get this error:

> Makefile:551: fallo en las instrucciones para el objetivo 'tls.lo'
> make[4]: *** [tls.lo] Error 1
> make[4]: se sale del directorio '/home/omar/Descargas/freetds-1.00.23/src/tds'
> Makefile:571: fallo en las instrucciones para el objetivo 'all-recursive'
> make[3]: *** [all-recursive] Error 1
> make[3]: se sale del directorio '/home/omar/Descargas/freetds-1.00.23/src/tds'
> Makefile:445: fallo en las instrucciones para el objetivo 'all'
> make[2]: *** [all] Error 2
> make[2]: se sale del directorio '/home/omar/Descargas/freetds-1.00.23/src/tds'
> Makefile:420: fallo en las instrucciones para el objetivo 'all-recursive'
> make[1]: *** [all-recursive] Error 1
> make[1]: se sale del directorio '/home/omar/Descargas/freetds-1.00.23/src'
> Makefile:461: fallo en las instrucciones para el objetivo 'all-recursive'
> make: *** [all-recursive] Error 1
>

**Comment by starius** [comment]
Your machine seems to be unable to connect to the official FTP server of freetds (ftp://ftp.freetds.org).
I added alternative HTTP download URL in https://github.com/mxe/mxe/issues/1597 and it should work now.

There are backup servers in cloud which normally serve as a backup, but freetds package was updated recently and the backup servers have not updated their files yet.
