### ISSUE TITLE
Qt5 package Not Found from d1yihgixbnrglp.cloudfront.net

### ISSUE THREAD

**Issue by yjdwbj** [mxe/mxe#1599]
```
$ cd mxe
mxe$ make qt5
[target]   i686-pc-mingw32 with 1 goal from command line
[download] qtbase

Wrong checksum of package qtbase!
------------------------------------------------------------
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.226.91|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-18 09:43:01 ERROR 404: Not Found.
--2016-12-18 09:43:01--  http://d1yihgixbnrglp.cloudfront.net/qtbase%2Dopensource%2Dsrc%2D5%2E1%2E0%2Etar%2Exz
Resolving d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)... 52.222.234.192, 52.222.234.123, 52.222.234.87, ...
Connecting to d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)|52.222.234.192|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-18 09:43:01 ERROR 404: Not Found.
```

**Comment by starius** [comment]
Can you upload file log/qtbase-download to [gist](https://gist.github.com/) please?

**Comment by yjdwbj** [comment]
Hello, uploaded to here .
https://gist.github.com/yjdwbj/a33269d3c0ccc5557748d4d84b0f193c

2016-12-18 10:26 GMT+08:00 Boris Nagaev <notifications@github.com>:

**Comment by starius** [comment]
It tries to download http://download.qt-project.org/official_releases/qt/5.1/5.1.0/submodules/qtbase-opensource-src-5.1.0.tar.xz
Current version of Qt5 used in MXE is 5.7.1. File http://download.qt.io/official_releases/qt/5.7/5.7.1/submodules/qtbase-opensource-src-5.7.1.tar.xz exists.
Try to update your MXE tree to latest master.

**Comment by yjdwbj** [comment]
Thank you do this job.  I'm did change to the mxe directory, run git pull
and then run git checkout master ,was is stable branch. and then make qt5 ,
output  another error.

------------------------------

M-Cross-env$ make qt5
[using autodetected 4 job(s)]
[build]     cmake                    x86_64-unknown-linux-gnu
[done]      cmake
x86_64-unknown-linux-gnu                              291564 KiB
4m48.127s
[download]  geoip-database
[build]     geoip-database           x86_64-unknown-linux-gnu
[done]      geoip-database
x86_64-unknown-linux-gnu                              6444 KiB
0m5.423s
[download]  googlemock
[no-build]  googlemock               x86_64-unknown-linux-gnu
[download]  googletest
[no-build]  googletest               x86_64-unknown-linux-gnu
[download]  lzma
[no-build]  lzma                     x86_64-unknown-linux-gnu
[download]  mpfr
[build]     mpfr                     x86_64-unknown-linux-gnu
[done]      mpfr
x86_64-unknown-linux-gnu                              15676 KiB
0m30.412s
[download]  mpc
[build]     mpc                      x86_64-unknown-linux-gnu
[done]      mpc
x86_64-unknown-linux-gnu                              5528 KiB
0m12.199s
[download]  pkgconf
[build]     pkgconf                  x86_64-unknown-linux-gnu
[done]      pkgconf
x86_64-unknown-linux-gnu                              1440 KiB
0m7.623s
[download]  protobuf
MXE Warning! Downloading protobuf from backup.

Download failed or wrong checksum of package protobuf!
------------------------------------------------------------
--2016-12-18 21:31:41--
http://d1yihgixbnrglp.cloudfront.net/protobuf%2D3%2E1%2E0%2Etar%2Egz
Resolving d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)...
52.222.234.201, 52.222.234.50, 52.222.234.231, ...
Connecting to d1yihgixbnrglp.cloudfront.net
(d1yihgixbnrglp.cloudfront.net)|52.222.234.201|:80...
connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-18 21:31:44 ERROR 404: Not Found.
Download failed!
------------------------------------------------------------
[log]      /home/michael/3TB-DISK/M-Cross-env/log/protobuf-download

Makefile:488: recipe for target 'download-only-protobuf-3.1.0.tar.gz' failed
make: *** [download-only-protobuf-3.1.0.tar.gz] Error 1


2016-12-18 11:24 GMT+08:00 Boris Nagaev <notifications@github.com>:

**Comment by starius** [comment]
Can you upload file log/protobuf-download to gist please?
