### ISSUE TITLE
qt3d target x86_64-w64-mingw32.shared fails to build on Jessie

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1608]
[Build log](https://gist.githubusercontent.com/anonymous/329e11c04ed9f3cb172bb176aaf3885b/raw/044acfbf625eaecbee311ac4327b3baaf87236d0/qt3d_x86_64-w64-mingw32.shared)
Other 3 targets on Jessie and all 4 targets on Wheezy work.

**Comment by starius** [comment]
I can't reproduce this with `make JOBS=4 -j 1`.
Failed build was with `-j 4 JOBS=1`.

**Comment by tonytheodore** [comment]
I saw the [same error on Darwin i686-w64-mingw32.shared](https://gist.github.com/tonytheodore/634285c9e24bfd0e62347bce0f2b2bea) with `-j4 JOBS=6` but next run with same options succeeded. The [serial retry workaround isn't a solution](https://github.com/mxe/mxe/issues/1462#issuecomment-239797907) ;)
