### ISSUE TITLE
lua fails to build if plugins/luarocks is enabled

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1614]
Build log: https://gist.github.com/53ba36b6b8fe710eba0b267c8b5f4fb3

The error is caused by `$(TEST_FILE)` being empty. Tracing this variable up to its source, I found the following code:

```makefile
# include files from MXE_PLUGIN_DIRS, set base filenames and `all-<plugin>` target
PLUGIN_FILES := $(realpath $(wildcard $(addsuffix /*.mk,$(MXE_PLUGIN_DIRS))))
PLUGIN_PKGS  := $(basename $(notdir $(PLUGIN_FILES)))
$(foreach FILE,$(PLUGIN_FILES),\
    $(eval $(basename $(notdir $(FILE)))_MAKEFILE  ?= $(FILE)) \
    $(eval $(basename $(notdir $(FILE)))_TEST_FILE ?= $(wildcard $(basename $(FILE))-test.*)) \
    $(eval all-$(lastword $(call split,/,$(dir $(FILE)))): $(basename $(notdir $(FILE)))))
```

The value of `MXE_PLUGIN_DIRS` variable in this loop was `plugins/apps plugins/luarocks /home/mxe/mxe/src`. So, for `FILE=plugins/luarocks/lua.mk`, the value of `_TEST_FILE` was set to empty string (since `$(wildcard $(basename $(FILE))-test.*))` found no files matching the mask). Later, for `FILE=src/lua.mk`, the value of `_TEST_FILE` was not reset to correct value (`src/lua-test.c`), since `?=` sets the variable only if it was not set before.

This can be addressed in two ways:

  * reorder plugins to make sure that core packages go first
  * add check for emptiness of `$(wildcard $(basename $(FILE))-test.*))` to the code above.

Any of these approaches is enough to fix the failure. I think, that first one can be useful anyway (because it can fail in other code like this).

**Comment by tonytheodore** [comment]
#1615 fixed this
