### ISSUE TITLE
undeclared dependencies of gst-plugins-*

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1624]
While (re)building packages for https://github.com/mxe/mxe/pull/1622 I discovered new files which did not exist in the first build:

```
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstbs2b.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstcacasink.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstchromaprint.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstdtls.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstgdkpixbuf.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstgtksink.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstmodplug.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstneonhttpsrc.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstopencv.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstopenexr.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstopus.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstresindvd.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstrsvg.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstrtmp.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstsndfile.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstvpx.a
i686-w64-mingw32.static/lib/gstreamer-1.0/libgstwebp.a
```

I have found some of them. E.g. libgstcacasink.a comes from [plugin-cacasink](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-plugin-cacasink.html) (part of Good plugins). Probably it depends on libcaca which is not in the list of dependencies of gst-plugins-good.

**Comment by pavelvat** [comment]
see commit "add missing gstreamer dependencies" in https://github.com/mxe/mxe/pull/1684

matching:
libgstbs2b -> libbs2b (gst-plugins-bad)
libgstcacasink -> libcaca (gst-plugins-good)
libgstchromaprint -> chromaprint (gst-plugins-bad)
libgstdtls -> openssl (gst-plugins-bad)
libgstgdkpixbuf -> gdk-pixbuf (gst-plugins-good)
libgstgtksink -> cairo (gst-plugins-good)
libgstmodplug -> libmodplug (gst-plugins-bad)
libgstneonhttpsrc -> neon (gst-plugins-bad)
libgstopencv -> opencv (gst-plugins-bad)
libgstopenexr -> openexr (gst-plugins-bad)
libgstopus -> opus (gst-plugins-base)
libgstresindvd -> libdvdnav libdvdread (gst-plugins-bad)
libgstrsvg -> librsvg (gst-plugins-bad)
libgstrtmp -> librtmp (gst-plugins-bad)
libgstsndfile -> libsndfile (gst-plugins-bad)
libgstvpx -> libvpx (gst-plugins-good)
libgstwebp -> libwebp (gst-plugins-bad)

**Comment by pavelvat** [comment]
> libgstgtksink -> cairo (gst-plugins-good)

This was error. Correct variant: libgstgtksink -> gtk3 (gst-plugins-bad).

Moreover I found yet another undeclared dependency. I firstly built all MXE packages for target i686-w64-mingw32.static except gstreamer packages and openscenegraph, vtk, vtk6. After this I built gstreamer packages. In result:
libgstfdkaac -> fdk-aac (gst-plugins-bad).
fdk-aac and gtk3 have been added in commit "add missing gstreamer dependencies" in https://github.com/mxe/mxe/pull/1684.

Also I found that plugin libgstdvdread (gst-plugins-ugly) exists for i686-w64-mingw32.shared but doesn't exist for i686-w64-mingw32.static.

**Comment by pavelvat** [comment]
>Also I found that plugin libgstdvdread (gst-plugins-ugly) exists for i686-w64-mingw32.shared but doesn't exist for i686-w64-mingw32.static.

part of log for i686-w64-mingw32.shared:
>configure: *** checking feature: dvdread library ***
configure: *** for plug-ins: dvdreadsrc ***
checking for DVDOpen in -ldvdread... yes
checking dvdread/dvd_reader.h usability... yes
checking dvdread/dvd_reader.h presence... yes
checking for dvdread/dvd_reader.h... yes
configure: *** These plugins will be built: dvdreadsrc

part of log for i686-w64-mingw32.static:
>configure: *** checking feature: dvdread library ***
configure: *** for plug-ins: dvdreadsrc ***
checking for DVDOpen in -ldvdread... no
configure: *** These plugins will not be built: dvdreadsrc

**Comment by pavelvat** [comment]
This issue has been solved in https://github.com/mxe/mxe/pull/1695 and should be closed.
