### ISSUE TITLE
Can someone tell me if this is normal

### ISSUE THREAD

**Issue by JellyKid** [mxe/mxe#1640]
I thought according to the tutorial I should be able to just do "make gcc" and have a basic build but it seems to be building everything. geoip-database, cloog, and a whole bunch of other stuff.
> jake@JS-MSI:~/src/mxe$ make gcc
> [check requirements]
> [build nonetwork lib]
> [git-log]   43a40a4 Merge pull request #1499 from tonytheodore/target-checks
> [build]     mxe-conf                 x86_64-unknown-linux-gnu
> [done]      mxe-conf                 x86_64-unknown-linux-gnu                              648 KiB        0m10.761s
> [build]     gmp                      x86_64-unknown-linux-gnu
> [done]      gmp                      x86_64-unknown-linux-gnu                              32041 KiB      3m51.082s
> [build]     isl                      x86_64-unknown-linux-gnu
> [done]      isl                      x86_64-unknown-linux-gnu                              46989 KiB      1m21.807s
> [build]     cloog                    x86_64-unknown-linux-gnu
> [done]      cloog                    x86_64-unknown-linux-gnu                              38303 KiB      0m51.126s
> [build]     cmake                    x86_64-unknown-linux-gnu
> [done]      cmake                    x86_64-unknown-linux-gnu                              250670 KiB     7m45.348s
> [build]     geoip-database           x86_64-unknown-linux-gnu
> [done]      geoip-database           x86_64-unknown-linux-gnu                              6672 KiB       0m5.979s
> [build]     libiconv                 x86_64-unknown-linux-gnu
> [done]      libiconv                 x86_64-unknown-linux-gnu                              46286 KiB      2m55.442s
> [build]     gettext                  x86_64-unknown-linux-gnu
> [done]      gettext                  x86_64-unknown-linux-gnu                              383000 KiB     17m2.991s
> [download]  googlemock
> [no-build]  googlemock               x86_64-unknown-linux-gnu
> [download]  googletest
> [no-build]  googletest               x86_64-unknown-linux-gnu
> [download]  lzma
> [no-build]  lzma                     x86_64-unknown-linux-gnu
> [download]  mpfr
> [build]     mpfr                     x86_64-unknown-linux-gnu
> [done]      mpfr                     x86_64-unknown-linux-gnu                              17201 KiB      1m53.469s
> [download]  mpc
> [build]     mpc                      x86_64-unknown-linux-gnu
> [done]      mpc                      x86_64-unknown-linux-gnu                              6336 KiB       0m48.727s
> [download]  pkgconf
> [build]     pkgconf                  x86_64-unknown-linux-gnu
> [done]      pkgconf                  x86_64-unknown-linux-gnu                              3468 KiB       0m13.910s
> [download]  protobuf
> [build]     protobuf                 x86_64-unknown-linux-gnu
> [done]      protobuf                 x86_64-unknown-linux-gnu                              714804 KiB     4m11.277s
> [download]  ragel
> [build]     ragel                    x86_64-unknown-linux-gnu
> [done]      ragel                    x86_64-unknown-linux-gnu                              19978 KiB      0m26.995s
> [download]  ucl
> [build]     ucl                      x86_64-unknown-linux-gnu
> [done]      ucl                      x86_64-unknown-linux-gnu                              6874 KiB       2m0.828s
> [download]  zlib
> [build]     zlib                     x86_64-unknown-linux-gnu
> [done]      zlib                     x86_64-unknown-linux-gnu                              5337 KiB       0m9.137s
> [download]  upx
> [build]     upx                      x86_64-unknown-linux-gnu
> [done]      upx                      x86_64-unknown-linux-gnu                              32046 KiB      0m24.196s
> [download]  waf
> [build]     waf                      x86_64-unknown-linux-gnu
> [done]      waf                      x86_64-unknown-linux-gnu                              7540 KiB       0m8.722s
> [download]  yasm
> [build]     yasm                     x86_64-unknown-linux-gnu
> [done]      yasm                     x86_64-unknown-linux-gnu                              55207 KiB      0m39.990s
> [build]     mxe-conf                 i686-w64-mingw32.static
> [done]      mxe-conf                 i686-w64-mingw32.static                               0 KiB          0m5.695s
> [build]     pkgconf                  i686-w64-mingw32.static
> [done]      pkgconf                  i686-w64-mingw32.static                               360 KiB        0m6.034s
> [download]  bfd
> [build]     binutils                 i686-w64-mingw32.static
> [done]      binutils                 i686-w64-mingw32.static                               514197 KiB     4m19.405s
> [download]  gendef
> [no-build]  mingw-w64                i686-w64-mingw32.static
> [download]  gcc
> [build]     gcc                      i686-w64-mingw32.static

**Comment by tonytheodore** [comment]
Yes, this is expected behaviour at the moment. `make gcc` will build a basic cross-compiler (binutils, gcc) along with the native libraries and configury to support that (cloog, isl, gmp, mpfr, mpc, mxe-conf, pkgconf).

The other packages you see are native (x86_64-unknown-linux-gnu) or target-independent (geoip-database) packages needed by the rest of mxe that we don't want to build multiple times for each cross target. There are plans to separate these out and have explicit cross-target dependencies, but in the interim, they're just bundled into the "native" build phase.
