### ISSUE TITLE
Update Gtk 3

### ISSUE THREAD

**Issue by mdickie** [mxe/mxe#1647]
MSys 2 provides a newer version of gtk.

**Comment by starius** [comment]
I tried to [update gtk3](https://gist.github.com/starius/1148df405c5fe0ea51ffec24a9ae0f5e#file-) but it requires updating glib first:
```
Package dependency requirement 'glib-2.0 >= 2.49.4' could not be satisfied.
Package 'glib-2.0' has version '2.44.1', required version is '>= 2.49.4'
```

I am trying to update `glib`.

**Comment by starius** [comment]
Next issue is cairo. gtk3 configure fails with the following message:

```
checking for cairo_win32_surface_create_with_format in -lcairo... no
configure: error: cairo_win32_surface_create_with_format is not found in cairo library
You need a cairo snapshot 1.15.x or 1.16.x release or newer
```

Latest release of cairo is 1.14.8. Cairo [1.15.x's snapshot](https://www.cairographics.org/snapshots/) is available, but snapshots are considered unstable.

**Comment by starius** [comment]
Help is needed.

gtk3 3.22.7 is built but its test [fails with linking errors](https://gist.github.com/7a736cb61f60de9a6bc7f1789f22c535).

My current state is fcbe7e30651b5c3be0cbd95541308cd5cbe393f7 + https://gist.github.com/637ee595aa389b31b9c0fe1525c8f254

I traced symbol `_imp__epoxy_glViewport`. It comes from package `libepoxy`, file `usr/i686-w64-mingw32.static/include/epoxy/wgl_generated.h`. The function is declared with `EPOXY_IMPORTEXPORT`, which comes from `usr/i686-w64-mingw32.static/include/epoxy/gl.h` and is defined to `__declspec(dllimport)`. It seems to be responsible for adding `_imp_` prefix to the symbol, breaking the linking. This is where the help is needed. Why is it defined to `__declspec(dllimport)` on a static target? How to the the error?

**Comment by tonytheodore** [comment]
Something like the below (untested) is usually required:

```diff
diff --git a/include/epoxy/gl.h b/include/epoxy/gl.h
index 0be3a66..2a40766 100644
--- a/include/epoxy/gl.h
+++ b/include/epoxy/gl.h
@@ -71,7 +71,15 @@ extern "C" {
 #endif

 #ifndef EPOXY_IMPORTEXPORT
-#define EPOXY_IMPORTEXPORT __declspec(dllimport)
+#  ifndef EPOXY_STATIC
+#    ifdef EPOXY_DLL
+#      define EPOXY_IMPORTEXPORT __declspec(dllexport)
+#    else
+#      define EPOXY_IMPORTEXPORT __declspec(dllimport)
+#    endif
+#  else
+#    define EPOXY_IMPORTEXPORT
+#  endif
 #endif

 #ifndef GLAPI
```

**Comment by starius** [comment]
Thank you! I am trying to build with this patch.
`libepoxy` turned out to be an undeclared dependency of `gtk3`.

**Comment by starius** [comment]
EPOXY_STATIC and EPOXY_DLL aren't defined.

**Comment by tonytheodore** [comment]
Sorry, the build system should define those (or something similar) based on configure options and populate the *.pc files etc. Looks like that support would have to be added, or just disable explicitly it in the gtk3 build if it's optional (most likely).

**Comment by starius** [comment]
I split the update to 3 pull requests:

  * https://github.com/mxe/mxe/pull/1648 mingw-w64: add --enable-secure-api
  * https://github.com/mxe/mxe/pull/1652 fix libepoxy
  * https://github.com/mxe/mxe/pull/1653 update glib, cairo, gtk3

I am rebuilding fcbe7e30651b5c3be0cbd95541308cd5cbe393f7 + these 3 pull requests.
