### ISSUE TITLE
luajit-i686-w64-mingw32.static fails to build

### ISSUE THREAD

**Issue by kingseva** [mxe/mxe#1670]
clonned from master

https://gist.github.com/anonymous/f144253e0f32a1d8c352784ab573d6e1

**Comment by kingseva** [comment]
It's interesting that at the same time of runing make luajit_x86_64-w64-mingw32.static builds fine

https://gist.github.com/kingseva/a3124dbdc482df4e4314bc94d8b2f341

**Comment by kingseva** [comment]
Ok, it seems to be gcc-multilib is missing on machine. sudo apt-get install gcc-multilib is fix issue.

https://gist.github.com/kingseva/ecad5d4d66eb80a1df774121bce0a340

**Comment by tonytheodore** [comment]
`g++-multilib` and `libc6-dev-i386` are also required http://mxe.cc/#requirements-debian

**Comment by kingseva** [comment]
I'm still think that it's an error to build 32 bit executables on x86_64 architecture. Luajit should be built fine without multilib. As any other modern package. 

I'm notice that only these executables have i386 compatible format:
i686-w64-mingw32.static/bin/ocamlrun
i686-w64-mingw32.static/bin/ocamlyacc

Notice that i686-w64-mingw32.shared ocaml built for x86_64.

Maybe it's can be fixed.

**Comment by starius** [comment]
LuaJIT builds and executes minilua binary. It is used while building the rest of LuaJIT.
Can this be a reason why multilib is needed?
