### ISSUE TITLE
Qttools package: MinGW lrelease binary missing

### ISSUE THREAD

**Issue by davidebeatrici** [mxe/mxe#1673]
Using the package **mxe-x86-64-w64-mingw32.static-qttools_5.7.0-20161012_amd64.deb**:
`sh: 1: /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-lrelease-qt5: not found`

As a workaround I used a symlink:
`ln -s /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/lrelease /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-lrelease-qt5`

The same issue is probably there also for the other targets.

**Comment by starius** [comment]
Can you try [candidate version](http://lists.nongnu.org/archive/html/mingw-cross-env-list/2017-02/msg00017.html) of binary packages? To try it, use official instructions (http://pkg.mxe.cc), replacing http://pkg.mxe.cc/repos/apt/debian with http://pkg.mxe.cc/releases/2017-02-11/apt/debian

**Comment by davidebeatrici** [comment]
Just tested, same problem. I also noticed that the **x86_64-w64-mingw32.static-protoc** binary is missing from the candidate version of the protobuf package, while it is present in the "normal" one.

**Comment by starius** [comment]
> Just tested, same problem

I checked [release of 2015-12-16](http://pkg.mxe.cc/releases/2015-12-16-sha256/repos/list/mxe-x86-64-w64-mingw32.static/mxe-x86-64-w64-mingw32.static-qttools.list). There was no file /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-lrelease-qt5 at that point as well. There are also no symlinks in `usr/bin` for other tools from the package.

Could you share your workflow, please?

> I also noticed that the x86_64-w64-mingw32.static-protoc binary is missing from the candidate version of the protobuf package, while it is present in the "normal" one.

protoc binary is the same for all targets. It was moved to a native package in https://github.com/mxe/mxe/pull/1561/commits/113781a492f2bf3d4ad0421af501dd422f60c3a7

**Comment by davidebeatrici** [comment]
> Could you share your workflow, please?

I'm using the latest Debian (Jessie) docker image, with just MXE packages on it.
The project has a QMake script to find the _lrelease_ binary:
```QMake
isEmpty(QMAKE_LRELEASE) {
  QMAKE_QMAKE_BASE = $$basename(QMAKE_QMAKE)
  QMAKE_LRELEASE_PATH = $$dirname(QMAKE_QMAKE)/$$replace(QMAKE_QMAKE_BASE,qmake,lrelease)
  isEqual(QT_MAJOR_VERSION, 5) {
    QMAKE_LRELEASE = $$shell_path($$QMAKE_LRELEASE_PATH)
  } else {
    QMAKE_LRELEASE = $$QMAKE_LRELEASE_PATH
  }
}
```

> protoc binary is the same for all targets. It was moved to a native package in 113781a

I think that using the same name as the native Linux binaries without any prefix/suffix is a problem, because it interferes with them in case a user has MXE's directory in PATH.

**Comment by davidebeatrici** [comment]
Is it normal that the _protoc_ binary is missing from the latest protobuf package? Only _protoc.exe_ is present.
The native Linux binary is available in **mxe-x86-64-unknown-linux-gnu-protobuf_3.1.0-20170208_amd64.deb**, but the package isn't installed as a dependency of protobuf.
