### ISSUE TITLE
behaviour MXE_GET_GITHUB_TAGS

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1674]
I have detected problem with update ```libsoup```. After replace line ```$(PKG)_IGNORE := libsoup-pre%``` to ```$(PKG)_IGNORE :=``` the command ```make update-package-libsoup``` output:
```
NEW      libsoup  2.54.0.1 --> libsoup-pre214-branch-base
```
The reason of that: https://github.com/mxe/mxe/blob/master/Makefile#L176
If replace ```$(SORT) -V``` to  ```$(SORT) -n``` then the command ```make update-package-libsoup``` output:
```
NEW      libsoup  2.54.0.1 --> 2.57.1
```

Full string for tests:
```
wget -q -O- 'https://api.github.com/repos/GNOME/libsoup/git/refs/tags/' | sed -n 's#.*"ref": "refs/tags/\([^"]*\).*#\1#p' | sed 's,^,,g' | sort -n | tail -1
```

**Comment by starius** [comment]
With `$(PKG)_IGNORE := libsoup-pre%` (master version), the output is
```
IGNORED  libsoup  libsoup-pre214-branch-base
```

Probably ignored versions should be sorted out before `head -1` in `define UPDATE`

**Comment by pavelvat** [comment]
look at output this command:
```
wget -q -O- 'https://api.github.com/repos/GNOME/libsoup/git/refs/tags/' | sed -n 's#.*"ref": "refs/tags/\([^"]*\).*#\1#p' | sed 's,^,,g' | sort -n
```

I think that need to add a toggle "sort type" to call of function:
```
define $(PKG)_UPDATE
    $(call MXE_GET_GITHUB_TAGS, repo/libname)
endef

```

**Comment by starius** [comment]
> look at output this command:

There are multiple types of strings there:
  * gnome-2-12-base
  * LIBSOUP_1_99_20
  * libsoup-2-0-branch-base
  * LIBSOUP_2_28_2_THIS_TIME_FOR_REAL
  * libsoup-hacking-branch-base
  * SOUP_0_5_4
  * 2.51.90
  * 2.49.91.1

The tag naming system is organized not ideally. We could deal with that by adding additional filtering (like `grep -e '^[0-9]\+\.[0-9]\+\.[0-9]\+$'`). It can be applied after `sed` and before `sort`.

**Comment by tonytheodore** [comment]
I've got some [old WIP to standardise this](https://gist.github.com/tonytheodore/4140626804d42e5d3532b5d2b94bc5d1), I'll tidy it up and do a PR.

**Comment by pavelvat** [comment]
By the way, why does MXE not provide command ```make check-update-package-name```?

**Comment by tonytheodore** [comment]
See #1712 for PR and the [libsoup GH_CONF line](https://github.com/tonytheodore/mxe/blob/1ea17b52392758d333fb3fb7a80a643fbdaeb518/src/libsoup.mk#L10) for an example of how this may be handled in a standard way.

**Comment by tonytheodore** [comment]
> If replace $(SORT) -V to $(SORT) -n

The `-V` option is needed to correctly sort semantic versioning schemes:
```
$ printf '1.9.10\n1.10.0' | sort -n
1.10.0
1.9.10
$ printf '1.9.10\n1.10.0' | sort -V
1.9.10
1.10.0
```

> why does MXE not provide command make check-update-package-name

[Added](https://github.com/mxe/mxe/commit/b4161379ee5c572d84c74e848999cbd5bae89f30) and [documented](https://github.com/mxe/mxe/pull/1723/commits/3606a3e158ceeaa1dc943c8192f319289a3927b3)

I think #1712 should cover most common cases, let us know if you find some others.
