### ISSUE TITLE
ERROR: Feature 'sql-psql' was enabled, but the pre-condition 'libs.psql' failed.

### ISSUE THREAD

**Issue by Majestio** [mxe/mxe#1676]
Error build qt5

**Comment by mabrand** [comment]
It seems likely that the postgresl update recently, which got merged by accident, is to blame. Could you please try again after reverting commit e4fef6b0ef0fa08a02a02e42e6feef039c32afe2 locally? If that solves the the problem, we should probably revert the commit on the master branch.

**Comment by Majestio** [comment]
Alas, I did not succeed. Maybe I did something wrong with the patch.

**Comment by jaccarmac** [comment]
`postgresql` builds for me after the suggested revert.

**Comment by mabrand** [comment]
For me too, so I just pushed it. Thanks.
