### ISSUE TITLE
Remove obsolete branches gh-pages and libsamplerate-tidy

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1679]
gh-pages might be created by outdated automation.
libsamplerate-tidy seems to be a push to wrong repo.

See https://github.com/mxe/mxe/pull/1677#issuecomment-280654319
See https://github.com/mxe/mxe/issues/1500#issuecomment-243083583

**Comment by vog** [comment]
Regarding `gh-pages`: Sorry! My fault. I had a left-over line in my `.git/config`:

    push = refs/heads/master:refs/heads/gh-pages

I just removed that line and also deleted the accidentally-recreated branch `gh-pages`.

Regarding `libsamplerate-tidy`: I'm okay with removing it.

**Comment by tonytheodore** [comment]
`libsamplerate-tidy` has been removed, it was just a test to see if it is merged automatically - I've raised a new issue for it #1683.
