### ISSUE TITLE
Branches pushed to origin (mxe/mxe) are automatically merged

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1683]
See:
https://github.com/mxe/mxe/pull/1671#issuecomment-279219714
https://github.com/mxe/mxe/pull/1672#issuecomment-279221817

**Comment by TobiX** [comment]
2 things:

1. In travis.yml, `if [ "$GH_TOKEN" != "" ]; then ./tools/travis-push.sh; fi` is run for any branch in the main repo
2. In travis-push.sh, everything is always pushed to origin:master...

**Comment by tonytheodore** [comment]
Thanks @TobiX
