### ISSUE TITLE
fallback to software rendering for Qt qml applications

### ISSUE THREAD

**Issue by therecipe** [mxe/mxe#1685]
Hey
First, thanks for your work on this project :)

I figured that the (new) [software backend](http://blog.qt.io/blog/2016/08/15/the-qt-quick-graphics-stack-in-qt-5-8/) is not automatically used by qml applications running on windows systems, that don't have proper OpenGL support.
Like on these virtual machines: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

The following example works with the "official" pre-built Qt package, if it's compiled on windows.
(It was tested on the microsoft images)

But it's not working when cross compiled with "i686-w64-mingw32.shared" or "x86_64-w64-mingw32.shared"
I'm using the jessie packages, but the wheezy packages didn't worked as well (and I think the Qt files inside even had the same checksum?)

"gallery.pro"
```
QT += quick quickcontrols2

SOURCES += gallery.cpp

RESOURCES += gallery.qml
```

"gallery.cpp"
```c++
#include <QGuiApplication>
#include <QQmlApplicationEngine>

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    engine.load(QUrl("qrc:/gallery.qml"));
    if (engine.rootObjects().isEmpty())
        return -1;

    return app.exec();
}
```

"gallery.qml"
```qml
import QtQuick 2.6
import QtQuick.Controls 2.1

ApplicationWindow {
    id: window
    width: 360
    height: 520
    visible: true
    title: "Qt Quick Controls 2"

    Rectangle {
      width: 100
      height: 100
      color: "green"
    }
}
```

It's however working if you force the use of the software backend, like this:

```c++
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQuickWindow>
#include <QSGRendererInterface>

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);
    QQuickWindow::setSceneGraphBackend(QSGRendererInterface::Software);

    QQmlApplicationEngine engine;
    engine.load(QUrl("qrc:/gallery.qml"));
    if (engine.rootObjects().isEmpty())
        return -1;

    return app.exec();
}
```

So maybe Qt just needs to be configured with the `-opengl dynamic` option (like the official pre-built packages)?
Taken from: http://doc.qt.io/qt-5/configure-options.html#opengl-options-for-windows
also some more infos: http://doc.qt.io/qt-5/windows-requirements.html#dynamically-loading-graphics-drivers

It's currently configured with `-opengl desktop`, if I saw it right.

**Comment by therecipe** [comment]
Fixed itself in newer Qt versions.

**Comment by tonytheodore** [comment]
Thanks for the update, it's still an open issue how we enable `-opengl dynamic`. There's some approaches in https://github.com/mxe/mxe/issues/947#issuecomment-248561369 and #2012 but I don't know enough to incorporate them (or keep them updated).
