### ISSUE TITLE
curl uses libidn2 instead of libidn

### ISSUE THREAD

**Issue by lostbard** [mxe/mxe#1691]
Newer versions of curl look for libidn2 instead of libidn, and when not found disables idn support.

**Comment by starius** [comment]
I'm adding libidn2.

**Comment by starius** [comment]
@lostbard 
I sent the pull request https://github.com/mxe/mxe/pull/1693
Can you test it, please?

**Comment by lostbard** [comment]
compiled as i686 static and ran both test-libidn2 and test-curl. curl -V also shows IDN now as a feature.

Thanks!!
