### ISSUE TITLE
wget on Wheezy fails to download https://otr.cypherpunks.ca/libotr-4.1.1.tar.gz

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1730]
```
$ wget https://otr.cypherpunks.ca/libotr-4.1.1.tar.gz 
--2017-03-21 03:49:03--  https://otr.cypherpunks.ca/libotr-4.1.1.tar.gz
Resolving otr.cypherpunks.ca (otr.cypherpunks.ca)... 198.96.155.5
Connecting to otr.cypherpunks.ca (otr.cypherpunks.ca)|198.96.155.5|:443... connected.
ERROR: The certificate of `otr.cypherpunks.ca' is not trusted.
```

`curl` works at the same time. Oh, those crypto packages...

**Comment by tonytheodore** [comment]
Did it fall back to `http://s3.amazonaws.com/mxe-pkg/libotr-4.1.1.tar.gz`? The backup runs at
```
  15,45  *   *   *   *   cd /home/mxe/mxe/ && ./tools/s3-fetch-and-sync
```
so it should have been there.

**Comment by starius** [comment]
Yes it did. otr.cypherpunks.ca uses Let's Encrypt. I tried to add root certs of Let's Encrypt manually to the system, but wget still isn't working. I checked with `strace` that it does open the CA file, but doesn't recognize cert of otr.cypherpunks.ca. It is confusing.
As more sites switch to Let's Encrypt, we'll see more downloading problems on Wheezy. Furthermore, it was my `./tools/update_backup.py` that failed.

**Comment by vszakats** [comment]
What's the result of `curl -v -LO https://otr.cypherpunks.ca/libotr-4.1.1.tar.gz` on a system failing with `wget`?

**Comment by starius** [comment]
the result of `curl -v -O https://otr.cypherpunks.ca/libotr-4.1.1.tar.gz`
https://gist.github.com/starius/b6db5d6304e8447d1720784cad0c8c5c

**Comment by starius** [comment]
By the way, this is the same on another system with Wheezy (wget fails, curl works).

**Comment by vszakats** [comment]
For sure it looks like a valid certificate, so the question if why `wget` bugs out. I've only used `wget` in the non-TLS days and now I'm mainly a `curl` user, so not very familiar with `wget` behaviour in this area.

I've found `curl` rather reliable and it's also the tool of choice in some popular projects like Homebrew, so one workaround may be to first try to use `curl` and only fall back to `wget` if it's not available. Unless there is a good reason to give `wget` the priority here.

**Comment by vszakats** [comment]
(This could also possibly resolve reliability problems with the backup URLs.)

**Comment by tonytheodore** [comment]
From the curl output:
```
SSL connection using ECDHE-RSA-AES256-GCM-SHA384
```
This is a [TLS v1.2 cipher](https://curl.haxx.se/docs/ssl-ciphers.html) which [was added in wget 1.16.1](http://savannah.gnu.org/forum/forum.php?forum_id=8159) wheezy uses 1.13.4:
```
$ wget https://otr.cypherpunks.ca/libotr-4.1.1.tar.gz  --secure-protocol=TLSv1_2
wget: --secure-protocol: Invalid value `TLSv1_2'.
$ wget https://otr.cypherpunks.ca/libotr-4.1.1.tar.gz  --secure-protocol=TLSv1
--2017-11-13 03:30:35--  https://otr.cypherpunks.ca/libotr-4.1.1.tar.gz
Resolving otr.cypherpunks.ca (otr.cypherpunks.ca)... 198.96.155.5
Connecting to otr.cypherpunks.ca (otr.cypherpunks.ca)|198.96.155.5|:443... connected.
ERROR: The certificate of `otr.cypherpunks.ca' is not trusted.
```

The site appears to support TLSv1, but the first few ciphers appear invalid:
https://www.ssllabs.com/ssltest/analyze.html?d=otr.cypherpunks.ca
