### ISSUE TITLE
Is it possible to use Qt 5.5

### ISSUE THREAD

**Issue by dexter369** [mxe/mxe#1734]
Is it possible to use Qt 5.5 instead of Qt 5.8 or Qt 4.8, since Qt 5.8 is not backward compatible.

**Comment by starius** [comment]
Qt was updated from 5.5.1 to 5.6.0 in f6b440461885129a4fd6162db02f88a41ffdb11a.
Can you checkout 7f07dab9a289ec9c1e96a97eee6e328b33779866 and check if it works for you, please?

**Comment by dexter369** [comment]
Thanks I tried the checkout 7f07dab9a289ec9c1e96a97eee6e328b33779866 however I am getting checksum mismatch error. I tried make update and then make qt5 but got build error.

**Comment by tonytheodore** [comment]
> however I am getting checksum mismatch error

Was the error with `qtsystems`? https://github.com/mxe/mxe/commit/04027754fa0984e81a5eca1b33707f29fafe6d93 should fix it, though that package isn't [really part of the qt5 modules](https://github.com/mxe/mxe/commit/56a6275ed94ce104cfa9d6acb6eddaa0e84d11d3)

**Comment by tonytheodore** [comment]
See #1828 for an example of how this may be done without freezing the whole toolchain.
