### ISSUE TITLE
Which git commit is the last working?

### ISSUE THREAD

**Issue by 93i** [mxe/mxe#1736]
I am trying to get a mxe version with gcc 5.4 to build on gentoo system, current master does not work, fails on libmms (so far). I tried to go backwards with git and hat several issues, like poppler trying to install to system root, and many others.

Which git commit is supposed to work? I have a working git commit, but it uses gcc 5.3 and i need 5.4, everything newer i tried so far failed at some point. Can we have the stable branch back please?

Here is the settings.mk

    JOBS := 8
    MXE_TARGETS := x86_64-w64-mingw32.shared i686-w64-mingw32.shared x86_64-w64-mingw32.static i686-w64-mingw32.static
    LOCAL_PKG_LIST := gcc boost qt5 nettle libidn libssh2 curl mpc cryptopp openscenegraph
    MXE_PLUGIN_DIRS := plugins/gcc5
    .DEFAULT local-pkg-list:
    local-pkg-list: $(LOCAL_PKG_LIST)

Here is the log of libmms:

https://gist.github.com/93i/0469d74db0fa0a8b2557efc75ec81964#file-libmms_x86_64-w64-mingw32-shared

How can i fix this, or can anyone name me a commit id that works?

Kind regards,

**Comment by tonytheodore** [comment]
We're patching `configure.in` without regenerating the configuration. Could you try:
```diff
diff --git a/src/libmms.mk b/src/libmms.mk
index 418516f..1d8f992 100644
--- a/src/libmms.mk
+++ b/src/libmms.mk
@@ -18,6 +18,7 @@ define $(PKG)_UPDATE
 endef

 define $(PKG)_BUILD
+    cd '$(SOURCE_DIR)' && autoreconf -fi
     cd '$(BUILD_DIR)' && '$(SOURCE_DIR)/configure' \
         $(MXE_CONFIGURE_OPTS)
     $(MAKE) -C '$(BUILD_DIR)' -j $(JOBS)
```

**Comment by tonytheodore** [comment]
Actually, that is unlikely to work - you need matching autoconf/automake/libtool. Try this instead:

```
make libtool MXE_PLUGIN_DIRS=plugins/native
```

> Which git commit is supposed to work?

These days, every commit (or last commit of a PR) is expected to work across a reasonable timeframe. 

> Can we have the stable branch back please?

The old "stable" branch was very unreliable unless you could control all external factors (like downloading tarballs, validating certificates, and every aspect of a local setup ;).

**Comment by 93i** [comment]
Thank you, almost there...

Now i have two packages still failing: I need open scene graph, which depends on poppler and poppler fails, because it tries to install to the system root, which is bad:

https://gist.github.com/93i/f5c69ae0c436cf29061e221c4072d657#file-poppler_x86_64-w64-mingw32-shared

As far as i know, poppler is an optional package for OSG, can i somehow get mxe to ignore the fact that poppler is not installed and install openscenegraph anyway?

Another package that fails is cegui, not sure why it is compiled, maybe a dependency too, i don't need it:

https://gist.github.com/93i/f5c69ae0c436cf29061e221c4072d657#file-cegui_x86_64-w64-mingw32-shared

**Comment by tonytheodore** [comment]
Poppler appears to be trying to create an odd-looking directory for doc install:
```
mkdir: cannot create directory â€˜/popplerâ€™: Permission denied
```
It seems that there are no real configure options to disable the docs fully, could you try:
```
diff --git a/src/poppler.mk b/src/poppler.mk
index 43a4d98..206639d 100644
--- a/src/poppler.mk
+++ b/src/poppler.mk
@@ -55,8 +55,8 @@ define $(PKG)_BUILD
         CXXFLAGS=-D_WIN32_WINNT=0x0500 \
         LIBTIFF_LIBS="`'$(TARGET)-pkg-config' libtiff-4 --libs`"
     PATH='$(PREFIX)/$(TARGET)/qt/bin:$(PATH)' \
-        $(MAKE) -C '$(1)' -j '$(JOBS)' $(MXE_DISABLE_CRUFT) HTML_DIR=
-    $(MAKE) -C '$(1)' -j 1 install $(MXE_DISABLE_CRUFT) HTML_DIR=
+        $(MAKE) -C '$(1)' -j '$(JOBS)' $(MXE_DISABLE_CRUFT) HTML_DIR='$(BUILD_DIR).sink'
+    $(MAKE) -C '$(1)' -j 1 install $(MXE_DISABLE_CRUFT) HTML_DIR='$(BUILD_DIR).sink'

     # Test program
     '$(TARGET)-g++' \
```

> can i somehow get mxe to ignore the fact that poppler is not installed and install openscenegraph anyway

You could try a workaround like `make poppler_BUILD=` to skip the build. You could also write a simple [plugin](https://github.com/mxe/mxe/tree/master/plugins) to modify the dependencies:

```
echo 'openscenegraph_DEPS := $(filter-out poppler,$(openscenegraph_DEPS))' > ~/mxe-plugins/overrides.mk
make MXE_PLUGIN_DIRS=~/mxe-plugins
```

> Another package that fails is cegui, not sure why it is compiled

See #1740, `LOCAL_PKG_LIST` needs a fix.

**Comment by tonytheodore** [comment]
> MXE_PLUGIN_DIRS := plugins/gcc5

Also note that gcc5 is the default since #1541.

**Comment by 93i** [comment]
Thank you, all up and running now, there was one issue left: openscenegraph seemed to compile qt4 although i wanted qt5, for now i forced it this way, but i am pretty sure that is not the official way:

    index bd958da..8503407 100644
    --- a/src/openscenegraph.mk
    +++ b/src/openscenegraph.mk
    @@ -33,8 +33,6 @@ define $(PKG)_BUILD
             -DPOPPLER_HAS_CAIRO_EXITCODE=0 \
             -D_OPENTHREADS_ATOMIC_USE_GCC_BUILTINS_EXITCODE=1 \
             -D_OPENTHREADS_ATOMIC_USE_WIN32_INTERLOCKED=1 \
    -        $(if $(filter qtbase,$($(PKG)_DEPS)), \
    -          -DDESIRED_QT_VERSION=5, \
    -          -DDESIRED_QT_VERSION=4)
    +       -DDESIRED_QT_VERSION=5
         $(MAKE) -C '$(1).build' -j '$(JOBS)' install VERBOSE=1
     endef
