### ISSUE TITLE
LOCAL_PKG_LIST from settings.mk is ignored

### ISSUE THREAD

**Issue by tehnick** [mxe/mxe#1745]
Something is broken now. I have successfully used this feature in the past. But now `make` command attempts to build all available packages instead of listed in LOCAL_PKG_LIST.

**Comment by tonytheodore** [comment]
Can you test #1740?

**Comment by tehnick** [comment]
It works fine. Thanks.

**Comment by tonytheodore** [comment]
Thanks for testing, it's merged now.
