### ISSUE TITLE
Add --config /dev/null to $(WGET)?

### ISSUE THREAD

**Issue by bacondropped** [mxe/mxe#1747]
I have a `.wgetrc` file which looks something like this:

```wgetrc
noclobber = on
header = User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 SamsungFridgeBrowser/413.0 Frigidaire/5
header = Accept: */*
```

The top-level MXE Makefile sets wget to this command line:
 ```make
WGET        = wget --user-agent='$(or $($(1)_UA),$(DEFAULT_UA))'
```

I think wgetrc UA overrides the command line UA, because this line fails for me: when the build gets to `gendef`, Sourceforge gives me an interactive HTML (timed) page for the browser instead of the MinGW archive, which, of course, fails (the checksum, specifically). I solved it by manually editing the above line to add `--config /dev/null`, but that seems kludgy. It would be nice if either

1. MXE forbade all user wgetrc files with `--config /dev/null`,

2. Or, less invasively, allowed the user to add their own command line options via a make variable or something (like from `settings.mk`, perhaps?).

**Comment by tonytheodore** [comment]
See #1756, you can set `WGET_TOOL` (or `WGET`) in `settings.mk` or command line. These are recursively expanded variables (defined with `=` instead of `:=`) so their value is evaluated when used instead of when parsed.

**Comment by bacondropped** [comment]
Nice, thanks!
