### ISSUE TITLE
-lUser32 not found

### ISSUE THREAD

**Issue by ArsenArsen** [mxe/mxe#1751]
Upon running qmake with a .pro file which depends on the [QHotkey](https://github.com/Skycoder42/QHotkey/) project, compilation will fail with a linker error,
```
/opt/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lUser32
collect2: error: ld returned 1 exit status
```
MXE is in this case installed into /opt/mxe, for the i686 static target, and the Makefile for the project is made with `/opt/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake`

QHotkey relies on User32 to register hotkeys.

**Comment by starius** [comment]
The toolchain is case sensitive to names of libraries (and headers).
Try to replace `-lUser32` with `-luser32`

**Comment by ArsenArsen** [comment]
That fixed it, and I opened a pull request towards QHotkey to fix it for everyone. Thanks :)

MXE made cross compilation easy :)
