### ISSUE TITLE
ffmpeg-3.2.4 fails to build (probably due to error in gnutls-3.5.11)

### ISSUE THREAD

**Issue by phillipberndt** [mxe/mxe#1753]
In a fresh mxe environment (`usr` deleted), with `MXE_TARGETS=i686-w64-mingw32.static`,

    make gcc zlib cairo ffmpeg gdk-pixbuf glib gtk2 imagemagick libarchive

fails to build ffmpeg. The build.log is unspectacular, but ffmpeg's [config.log](https://gist.github.com/e620791a534285254f7bcabba966ff4e) shows that something is apparently wrong with the latest gnutls version:

    usr/i686-w64-mingw32.static/lib/libgnutls.a(str-iconv.o): In function `gnutls_ucs2_to_utf8':
    mxe/tmp-gnutls-i686-w64-mingw32.static/gnutls-3.5.11/lib/str-iconv.c:88: undefined reference to `u16_to_u8'
    tmp-gnutls-i686-w64-mingw32.static/gnutls-3.5.11/lib/str-unicode.c:96: undefined reference to `UC_CATEGORY_Lu'

etc.

(/cc @mabrand as author of 745274400b22a5775def171c7172e81331b9665f)

**Comment by phillipberndt** [comment]
The issue appears to be that gnutls.pc pulls in `libunistring.a` directly rather than using `-lunistring`: Somehow the file is sorted *before* configure's test C file in the gcc arguments. I still don't know whether this is a bug in ffmpeg or gnutls, but a simple solution would be to patch gnutls to use proper linker flags in it's pkgconfig definition.

I can confirm that replacing

    Libs.private: @LIBZ_PC@ @LIBINTL@ @LIBSOCKET@ @LIBNSL@ @LIBPTHREAD@ @LIB_SELECT@ @TSS_LIBS@ @GMP_LIBS@ @LIBUNISTRING@ @LIBIDN2_LIBS@ -lcrypt32

in the patched gnutls.pc.in with 

    Libs.private: @LIBZ_PC@ @LIBSOCKET@ @LIBNSL@ @LIBPTHREAD@ @LIB_SELECT@ @TSS_LIBS@ @GMP_LIBS@ @LIBIDN2_LIBS@ -liconv -lunistring -lcrypt32 

fixes the issue for me.

**Comment by starius** [comment]
ffmpeg is broken here too.

**Comment by starius** [comment]
The linker command is

```
i686-w64-mingw32.static-gcc -Wl,--large-address-aware 
-Wl,--nxcompat,--dynamicbase -Wl,--as-needed 
-Wl,--pic-executable,-e,_mainCRTStartup 
-I/home/pberndt/pqiv_builds/mxe/usr/i686-w64-mingw32.static/include 
/home/pberndt/pqiv_builds/mxe/usr/i686-w64-mingw32.static/lib/libunistring.a 
-L/home/pberndt/pqiv_builds/mxe/usr/i686-w64-mingw32.static/lib 
/home/pberndt/pqiv_builds/mxe/usr/i686-w64-mingw32.static/lib/libiconv.a 
-o /tmp/ffconf.PVp0sXNF.exe /tmp/ffconf.7sP63bXH.o -lgnutls -lhogweed 
-lnettle -lidn -lz -lws2_32 -lcrypt32 -lgmp -lintl -liconv -lm -llzma 
-lbz2 -lz -lpsapi -ladvapi32 -lshell32 -mconsole
```

It looks like it moved all libraries defined as `foo.a` files before `-o exe` and all libraries defined as `-l foo` after `-o exe`, that is why `libunistring.a` is before `-lgnutls` (which probably causes the link error).

**Comment by starius** [comment]
I edited installed `gnutls.pc` file and replaced libunistring.a path with -lunistring and libiconv.a path with -liconv. It builds now.

**Comment by starius** [comment]
I sent PR https://github.com/mxe/mxe/pull/1757
