### ISSUE TITLE
SFML 2.4.2 update

### ISSUE THREAD

**Issue by oomek** [mxe/mxe#1759]
Any chance to update sfml to 2.4.2 ?

**Comment by starius** [comment]
Please take a look https://github.com/mxe/mxe/pull/1760

**Comment by oomek** [comment]
Awesome, thanks. Will the precompiled package be updated soon?

**Comment by oomek** [comment]
I've updated mxe with apt-get from pkg.mxe.cc but config.cppin the SFML filder still showing 2.3.2

**Comment by starius** [comment]
The pull request https://github.com/mxe/mxe/pull/1760 hasn't been even merged yet.
Then the rebuild of binary distribution will take at least a day.

**Comment by starius** [comment]
Travis fails to download new sfml for some reason:
https://travis-ci.org/mxe/mxe/builds/228516653#L735

**Comment by oomek** [comment]
I see, the green checkmark mislead me. Thanks for explaining.

**Comment by oomek** [comment]
Did you make any proggress with this issue by any chance?

**Comment by oomek** [comment]
I desperately need this update. Have you managed to figure out why it's not compiling yet?

**Comment by starius** [comment]
Sorry for the delay!

The issue was not with sfml but with the fact its site uses new CA which is not recognized by old version of wget used in the test. I updated the test environment in https://github.com/mxe/mxe/pull/1760/commits/3ad6743c7bfba5c16bb3fa8cf9c3e1eb08500d97 so it works now.

Regarding pkg.mxe.cc - I'll start the build soon.

**Comment by oomek** [comment]
Thanks a lot!

**Comment by oomek** [comment]
I don't want to hustle you or anything, but can you please be more specific what soon means in this case :)

**Comment by starius** [comment]
The packages have been built. They are being packed to .deb and to .tar now.

**Comment by starius** [comment]
The packages are available for testing. Can you test your workflow on the new version of packages, please? To try it, use official instructions (http://pkg.mxe.cc), replacing http://pkg.mxe.cc/repos/apt/debian with http://pkg.mxe.cc/releases/2017-05-19/apt/debian

I'll also do some tests on my side. If everything is OK, I'll announce the new version and switch default path http://pkg.mxe.cc/repos/apt/debian to the new version.

**Comment by oomek** [comment]
Unfortunately on the new version compiling fails during linking.
Here is the log file:
http://paste.ubuntu.com/24614093/

**Comment by oomek** [comment]
I see now all sfml package config files has been consolidated to one sfml.pc
I've updated my makefile, but it's still throwing an error because one dependency is missing
gl.pc

**Comment by oomek** [comment]
http://paste.ubuntu.com/24614212/

**Comment by starius** [comment]
gl.pc should be in /usr/lib/mxe/usr/x86_64-w64-mingw32.static/lib/pkgconfig/gl.pc

**Comment by oomek** [comment]
I've checked there before posting and there is only:
glew.pc
glewmx.pc
glfw3.pc
glpk.pc
glut.pc

but no gl.pc or glu.pc

**Comment by starius** [comment]
Can you post output of:
```
$ dpkg -L mxe-x86-64-w64-mingw32.static-mxe-conf
```

**Comment by oomek** [comment]
```
root@ubuntu:~# dpkg -L mxe-x86-64-w64-mingw32.static-mxe-conf
dpkg-query: package 'mxe-x86-64-w64-mingw32.static-mxe-conf' is not installed
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.

```

**Comment by starius** [comment]
Hmm, that is strange. Can you now post output of
```
$ aptitude show mxe-x86-64-w64-mingw32.static-mxe-conf
```
?

**Comment by oomek** [comment]
I'm unable to install aptitude due to some dependencies failing to install.
I looked at the install log of mxe and indeed conf hasn't been installed
After typing apt-get install -f I get some errors:

```
root@ubuntu:~# apt-get install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  mxe-x86-64-unknown-linux-gnu-mxe-conf mxe-x86-64-w64-mingw32.static-gtk2 mxe-x86-64-w64-mingw32.static-mxe-conf
The following NEW packages will be installed:
  mxe-x86-64-unknown-linux-gnu-mxe-conf mxe-x86-64-w64-mingw32.static-gtk2 mxe-x86-64-w64-mingw32.static-mxe-conf
0 upgraded, 3 newly installed, 0 to remove and 5 not upgraded.
432 not fully installed or removed.
Need to get 0 B/15.8 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 345872 files and directories currently installed.)
Preparing to unpack .../mxe-x86-64-unknown-linux-gnu-mxe-conf_1-20170519_amd64.deb ...
Unpacking mxe-x86-64-unknown-linux-gnu-mxe-conf (1-20170519) ...
dpkg: error processing archive /var/cache/apt/archives/mxe-x86-64-unknown-linux-gnu-mxe-conf_1-20170519_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/mxe/usr/x86_64-unknown-linux-gnu/lib/nonetwork.so', which is also in package mxe-x86-64-unknown-linux-gnu-cmake-conf 1-20170519
Preparing to unpack .../mxe-x86-64-w64-mingw32.static-mxe-conf_1-20170519_amd64.deb ...
Unpacking mxe-x86-64-w64-mingw32.static-mxe-conf (1-20170519) ...
dpkg: error processing archive /var/cache/apt/archives/mxe-x86-64-w64-mingw32.static-mxe-conf_1-20170519_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/mxe/usr/x86_64-w64-mingw32.static/installed/.gitkeep', which is also in package mxe-x86-64-w64-mingw32.static-cmake-conf 1-20170519
Preparing to unpack .../mxe-x86-64-w64-mingw32.static-gtk2_2.24.29-20170519_amd64.deb ...
Unpacking mxe-x86-64-w64-mingw32.static-gtk2 (2.24.29-20170519) ...
dpkg: error processing archive /var/cache/apt/archives/mxe-x86-64-w64-mingw32.static-gtk2_2.24.29-20170519_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/mxe/usr/x86_64-w64-mingw32.static/lib/gailutil.def', which is also in package mxe-x86-64-w64-mingw32.static-gtk3 3.22.7-20170519
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/mxe-x86-64-unknown-linux-gnu-mxe-conf_1-20170519_amd64.deb
 /var/cache/apt/archives/mxe-x86-64-w64-mingw32.static-mxe-conf_1-20170519_amd64.deb
 /var/cache/apt/archives/mxe-x86-64-w64-mingw32.static-gtk2_2.24.29-20170519_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by starius** [comment]
This seems to be the same as https://github.com/mxe/mxe/issues/1772 but with mxe-conf vs cmake-conf now...

I built a list of files included to multiple packages in the recent build (2017-05-19):
https://gist.github.com/05435e5095ca41ee062fc1338e6e736d

Some of them can be excluded (.gitkeep, nonetwork.so), but there are also some headers and libraries.

**Comment by oomek** [comment]
I know, but every time I use apt-get I'm bobbarded by the tons of lines like this one:

> mxe-x86-64-w64-mingw32.static-qtsensors : Depends: mxe-x86-64-w64-mingw32.static-mxe-conf but it is not going to be installed
>                                            Depends: mxe-x86-64-unknown-linux-gnu-mxe-conf but it is not going to be installed
>

**Comment by starius** [comment]
It says `it is not going to be installed` because of trying to overwrite the common files.

**Comment by oomek** [comment]
I see, but does it explain missing OpenGL pc files?

**Comment by starius** [comment]
I have to fix this problem with common files.
Whatever the fix is, it is likely to need another release to apply.
Meanwhile the following workaround can be used:
```
$ sudo apt-get -o Dpkg::Options::="--force-overwrite" install ...
```

**Comment by starius** [comment]
> does it explain missing OpenGL pc files?

Yes, it does. OpenGL pc (gl.pc) is a part of `mxe-conf`, which fails to install due to the issue with common files.

**Comment by starius** [comment]
See the list of files in the package:
http://pkg.mxe.cc/releases/2017-05-19/list/mxe-x86-64-w64-mingw32.static/mxe-x86-64-w64-mingw32.static-mxe-conf.list

**Comment by oomek** [comment]
Thank you for the tip.
`apt-get -o Dpkg::Options::="--force-overwrite" install -f`
It finally compiled.
