### ISSUE TITLE
Failed to build package luajit for target i686-w64-mingw32.static!

### ISSUE THREAD

**Issue by joede** [mxe/mxe#1769]
Failed to build package `luajit` for target i686-w64-mingw32.static! The build is running on a Debian 8 desktop system. The log is here: https://gist.github.com/joede/d8c9281cae25d33ee4dc5873b91c6ca8

Is there a simple way to exclude a package from the complete build?

```
Makefile:103: recipe for target 'src/luajit' failed
make[2]: *** [src/luajit] Error 2
make[2]: Leaving directory '/usr/lib/mxe/tmp-luajit-i686-w64-mingw32.static/LuaJIT-2.0.4'
Makefile:642: recipe for target 'build-only-luajit_i686-w64-mingw32.static' failed
make[1]: *** [build-only-luajit_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory '/usr/lib/mxe'
```

**Comment by starius** [comment]
Host `gcc` fails with the following error:

```
buildvm.h:9:23: fatal error: sys/types.h: File or directory not found
```

It looks your system is missing some of [requirements](http://mxe.cc/#requirements-debian) (likely `g++-multilib libc6-dev-i386`). You can install all the requirements with `sudo ./tools/install-deps`

> Is there a simple way to exclude a package from the complete build?

Try `make EXCLUDE_PKGS='luajit'`

**Comment by joede** [comment]
Thanks for the fast solution. I've missed to install `libc6-dev-i386`. I've avoided to use `install-deps` because I always try to install packages with `--no-install-recommends`.
