### ISSUE TITLE
mailing list down?

### ISSUE THREAD

**Issue by crobarcro** [mxe/mxe#1773]
Sorry, this probably isn't the best place to report this, but I just attempted to send a mail to mingw-cross-env-list@nongnu.org, but got a failure notice with the following message:

 No MX or A records for nongnu.org

Is the list working?

**Comment by crobarcro** [comment]
I received your test message to the list and sent a reply which doesn't seem to have failed.

**Comment by vog** [comment]
Your first-time post had to be approved by a moderator. Now you are whitelisted.

**Comment by crobarcro** [comment]
Ahh, ok thanks
