### ISSUE TITLE
Add ability to use system MinGW

### ISSUE THREAD

**Issue by h4tr3d** [mxe/mxe#1778]
Hi team! 

Most Linux systems ships more-less actual MinGW in his repos: Debian and derivatives, ArchLinux and derivatives and possible others.

So, my question: is it possible to use pre-installed toolchain and omit building gcc, binutils?

If no, is it possible to add such behavior?

For example, add targets like: gcc-sys, binutils-sys and so on that just reports that such packages must be re-used from system. Also, it is good reason that use must provide some information via settings: Exception handling model, threading model and so on.

PS in any case: thanks for project!

**Comment by tonytheodore** [comment]
It is theoretically possible in the sense that `gcc` is just a wrapper that invokes other programs in the right order with the right flags. You can turn your native `gcc` into a cross-compiler by carefully stepping through every invocation it makes but that's really an academic exercise and wouldn't be very robust in practice.

We will have less complex wrappers at some stage to [build the toolchain only once per arch/thread/exception](https://github.com/mxe/mxe/pull/1019), but even that is quite difficult using our own toolchain - let alone keeping it updated. In such a scenario, it may be possible to swap out the underlying toolchain with a pre-installed one - but that's extremely advanced and beyond the scope of what MXE does.
