### ISSUE TITLE
MXE tries to link to both system libltdl.so and mxe package version

### ISSUE THREAD

**Issue by crobarcro** [mxe/mxe#1779]
I'm cross compiling an autotools project, which requires libltdt, but in the final link command for the program, both the system libltdt.so andthe mxe version of libltdt

I configured like this:

`./configure --host=x86_64-w64-mingw32.static CXXFLAGS="-D_P_WAIT=0 -static -static-libgcc -static-libstdc++" CFLAGS="-D_P_WAIT=0" --enable-static --disable-shared`

I get an error like below

```
libtool: link: x86_64-w64-mingw32.static-g++ -D_P_WAIT=0 -static-libgcc -static-libstdc++ -pthread -pthread -Wl,--export-all-symbols -o mbdyn.exe mbdyn.o ../mbdyn/base/.libs/libbase.a -L/opt/mxe/usr/x86_64-w64-mingw32.static/lib -L/opt/mxe/usr/mingw/lib aero/.libs/libaero.a struct/.libs/libstruct.a elec/.libs/libelec.a thermo/.libs/libthermo.a hydr/.libs/libhydr.a base/.libs/libbase.a ../libraries/libmbc/.libs/libmbc_static.a -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../.. -lgfortran -lquadmath /usr/lib/x86_64-linux-gnu/libltdl.so -ldl ../libraries/libmbwrap/.libs/libmbwrap.a ../libraries/libann/.libs/libmbann.a -L/opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0 -L/opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0/../../../../x86_64-w64-mingw32.static/lib/../lib -L/opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0/../../../../x86_64-w64-mingw32.static/lib /home/rcrozier/src/mbdyn/libraries/liby12/.libs/liby12.a /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0/libgfortran.a -lmingw32 -lmoldname -lmingwex -lmsvcrt /opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0/libquadmath.a -ladvapi32 -lshell32 -luser32 -lkernel32 /opt/mxe/usr/x86_64-w64-mingw32.static/lib/libltdl.a -pthread -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libltdl.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [mbdyn.exe] Error 1
```

In the last command there are several `-L` entries like `-L/usr/lib/x86_64-linux-gnu`

It also links explicitly to `/usr/lib/x86_64-linux-gnu/libltdl.so`

but I actually want to link only to, `/opt/mxe/usr/x86_64-w64-mingw32.static/lib/libltdl.a` which is also specified in the command.

If I remove the `-L` entries which aren't pointing to mxe tools directories and the reference to `libltdl.so` and run the command manually this completes successfully and mbdyn.exe is produced, and it runs on a windows machine.

Is this an issue with MXE, or have I done something wrong?

**Comment by tonytheodore** [comment]
Can you post the full log? There should be no `-L` entries like `-L/usr/lib/x86_64-linux-gnu`.

**Comment by crobarcro** [comment]
I've tried to reproduce this, but I can't. It has basically just gone away and everything is working fine now. Could it be that  I required some paths to be set or something like this after building the libltdtl package and a reboot solved the issue?

**Comment by tonytheodore** [comment]
It is very likely something in your environment variables causing problems. You can try a whitelist:
```
unset `env | \
    grep -vi '^EDITOR=\|^HOME=\|^LANG=\|MXE\|^PATH=' | \
    grep -vi 'PKG_CONFIG\|PROXY\|^PS1=\|^TERM=' | \
    cut -d '=' -f1 | tr '\n' ' '`
```
to get the most isolated and repeatable session.

**Comment by crobarcro** [comment]
Thnaks, if I ever see the issue again I will supply logs
