### ISSUE TITLE
Cmake won't find libsodium

### ISSUE THREAD

**Issue by zigapk** [mxe/mxe#1781]
Hi,

I am working on a windows package for [ElectronPass](https://github.com/electronpass/electronpass-desktop/). Its dependency [libelectronpass](https://github.com/electronpass/libelectronpass) is what causes problems to me. I have:
- cloned the mxe repo,
- executed `make qtbase libsodium` and
- executed `/home/zigapk/Desktop/temp/mxe/usr/bin/i686-w64-mingw32.static-cmake ..` from my build folder.

The problem is cmake won't find libsodium:
```
== Using MXE wrapper: /home/zigapk/Desktop/temp/mxe/usr/bin/i686-w64-mingw32.static-cmake
     - cmake version 3.7.2
     - warnings for unused CMAKE_POLICY_DEFAULT variables can be ignored
== Using MXE toolchain: /home/zigapk/Desktop/temp/mxe/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.cmake
== Using MXE runresult: /home/zigapk/Desktop/temp/mxe/usr/share/cmake/modules/TryRunResults.cmake
== Adding "-DCMAKE_BUILD_TYPE=Release"
loading initial cache file /home/zigapk/Desktop/temp/mxe/usr/share/cmake/modules/TryRunResults.cmake
CMake Error at /home/zigapk/Desktop/temp/mxe/usr/x86_64-unknown-linux-gnu/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find sodium (missing: sodium_LIBRARY_RELEASE
  sodium_LIBRARY_DEBUG)
Call Stack (most recent call first):
  /home/zigapk/Desktop/temp/mxe/usr/x86_64-unknown-linux-gnu/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  Findsodium.cmake:206 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/zigapk/Desktop/temp/libelectronpass/build/CMakeFiles/CMakeOutput.log".
```

I've tried a whole lot of desperate things, but after a few days I decided to ask for help.
Thank you in advance.

**Comment by zigapk** [comment]
I finally managed to link the sodium library. I had to remove Findsodium.cmake and set include and library directories myself.

**Comment by Gbps** [comment]
Have a solution for this problem while getting libsodium to work in a Docker build container.

Findsodium.cmake silently fails if you don't have "pkg-config" installed.

A simple `apt install pkg-config` on Debian-based systems should do the trick.
