### ISSUE TITLE
gcc 7 with i686-w64-mingw32.shared fails

### ISSUE THREAD

**Issue by muellni** [mxe/mxe#1782]
On current mxe
`make MXE_PLUGIN_DIRS=plugins/gcc7 MXE_TARGETS='i686-w64-mingw32.shared' -j2 JOBS=4 gcc`
fails with `mxe/tmp-gcc-i686-w64-mingw32.shared/gcc-7.1.0.build_/mingw-w64-v5.0.2/mingw-w64-libraries/winpthreads/src/clock.c:137: undefined reference to '__divmoddi4'`
Possibly related: https://sourceforge.net/p/mingw-w64/mailman/message/35828144/

**Comment by TriptoKnocker** [comment]
I have this issue with gcc7.2 too. There's enough of a trail in the link you've provided to make the required fix.
I note that the MinGW-w64 project itself has posted a fix in their own repo for exactly this issue, as can be found here: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/431ac2a912708546cd7271332e9331399e66bc62/
I surmise that whenever the guys at MinGW-w64 release whatever version comes after 5.0.2, that this will then be fixed. In the meantime, I've created a 'drop-in' patch for that can be used until MinGW-w64 is updated. [mingw-w64-2.txt](https://github.com/mxe/mxe/files/1281989/mingw-w64-2.txt)
Rename the attached file to mingw-w64-2.patch and place in the src directory of mxe.

To the maintainers: I can produce a pull request for this patch if you'd like.

**Comment by tonytheodore** [comment]
Thanks, I've added the patch to #1922 since `winpthreads-host` also needs it (static).
