### ISSUE TITLE
Using pre-compiled MXE binaries, qmake projects do not link against shared versions of Qt 5 out-of-the-box

### ISSUE THREAD

**Issue by mhoeher** [mxe/mxe#1783]
Hi everyone,

I have an issue using pre-compiled MXE packages and a shared version of Qt5. Basically, I've installed pre-compiled MXE binaries as described [here](http://pkg.mxe.cc/). I installed the shared version of the packages.

When I try to compile a Qt project which uses `qmake`, the resulting Makefiles link against the static versions of the Qt libraries located in `/usr/lib/mxe/usr/x86_64-w64-mingw32.shared/qt5/lib/`. However, my expectation would be that the project is linked against the libraries in `/usr/lib/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/`.

I am able to get the desired results by applying the following "workarounds":
* I created a file `/usr/lib/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/qt.conf` with the following content:
```
[Paths]
Prefix=/usr/lib/mxe/usr/x86_64-w64-mingw32.shared/qt5
Libraries=bin
```
* Instead of using `/usr/lib/mxe/usr/bin/x86_64-w64-mingw32.shared-qmake-qt5`, I use `/usr/lib/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/qmake`.
* Copied the file `/usr/lib/mxe/usr/x86_64-w64-mingw32.shared/qt5/lib/libqtmain.a` to `/usr/lib/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin`.

With these tweaks, the Makefiles that are generated properly link against the shared Qt versions.

Attached, please find a minimal [example](https://github.com/mxe/mxe/files/1055834/prl_test.tar.gz) I used for testing. Don't mind the name, I initially thought that the issue might be caused by using qmake's `create_prl` and `link_prl` features, but that does not seem to be the case, as the issue also occurs when not using these.

I am not sure if this is an issue in MXE, the Debian packages or upstream Qt, so feel free to close this issue if you think it it not directly related to MXE.

**Comment by tonytheodore** [comment]
Can you try removing the `CONFIG += staticlib` from `testlib.pro`? The prefixed `qmake` should set this correctly without any other config.

**Comment by mhoeher** [comment]
I can give it a try as soon as I am home (don't have my test environment at hand).

However, I think this is not really a solution for the issue :(

I originally encountered the issue in a project of mine where I have exactly this setup:
* My main code resides in a static library.
* I have the actual app which links against that library.
* Additionally, I have several unit tests which also link against the library.

It would be great if I could continue with this setup, as there is actually not purpose to have my library build as a shared one.

**Comment by mhoeher** [comment]
Update: I tried to comment out the `staticlib` config line, which however did not seem to have any effect. It still links against static Qt.
Even more: With the line commented out, the `testlib` still is built as static library.

**Comment by tonytheodore** [comment]
I can see similar behaviour with qt built from source. However, while it appears to be linking against static libs, it's actually producing a shared executable that indeed uses the *.dlls at runtime. I think the confusion could be that qmake uses `-Wl,--out-implib,release/libtestlib.a` where I'd expect that to be `*.dll.a`.

You can also check the size of executable, it will be a lot larger if it's statically linked.

>It would be great if I could continue with this setup, as there is actually not purpose to have my library build as a shared one.

I'm not sure I understand, are you trying to build static or shared?

**Comment by mhoeher** [comment]
You are absolutely right :) Thanks!

I just observed the generated calls to the linker (actually because I currently mainly use MXE in some CI tests). Indeed the resulting executable correctly tries to load the DLLs.

I have to admit I am not too familiar with the typical naming of libraries and other artifacts on Windows, however, could it be that these `*.a` files actually correspond to the `*.lib` files used on Windows?

> I'm not sure I understand, are you trying to build static or shared?

My goal is to build the project internal library as static one (as there is no one outside the project who needs to link against it) but otherwise link against shared versions of "external" libraries like the Qt ones. Anyway, it seems everything works as it should, so I think this issue can be considered closed.

Thanks again for your help and sorry for any confusion this might have caused!

**Comment by tonytheodore** [comment]
> could it be that these *.a files actually correspond to the *.lib files used on Windows?

They do, the *.lib files can either be static libs or import libs, you can use `nm` to see how the names are mangled differently in each case (with an `__imp_` prefix).

The usual convention with mingw/gcc is to call static libs *.a to mimic unix naming and import libs *.dll.a so there's no confusion. There's a [patch for qmake that does this](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-qt5-static/0008-qt-5.3.0-win32-g-Add-QMAKE_EXTENSION_IMPORTLIB-defaulting-to-.patch) but I'm not sure if that then breaks the expectations of qt users...
