### ISSUE TITLE
Building with libtar

### ISSUE THREAD

**Issue by supertriodo** [mxe/mxe#1796]
Is it possible to use mxe to crosscompile a project that use libtar?

Thx!

**Comment by darealshinji** [comment]
I guess you have to build libtar from source too: https://github.com/tklauser/libtar

**Comment by tonytheodore** [comment]
I did a quick test of the above repo and libtar requires `tar.h`.

[GNU Tar](https://www.gnu.org/software/tar/) fails to build with `SIGPIPE` errors. These are available in mingw-w64 using `-D_POSIX`, but then there's `conflicting types for 'sigset_t'` errors.

It looks like GNU Tar is using gnu-lib, the notes on these headers to start with:
  - [signal.h](https://www.gnu.org/software/gnulib/manual/gnulib.html#signal_002eh)
  - [tar.h](https://www.gnu.org/software/gnulib/manual/gnulib.html#tar_002eh)

don't look promising. 

See if you can use [libarchive](https://www.libarchive.org) instead - it's packaged in MXE already.
