### ISSUE TITLE
Lots of linker errors when trying to link libav* from FFmpeg

### ISSUE THREAD

**Issue by ArsenArsen** [mxe/mxe#1798]
Hello! I am using a static linked MXE instance (is that the correct term?) to cross compile my project, but when compiling I get a load of linker errors.

FFmpeg is not the only library I use, I use Qt too, but FFmpeg is the only one which has these linker errors.

Relevant part of my build log: https://hastebin.com/rizucekiti.swift

Thanks for making MXE, it saved me. Alot.

**Comment by tonytheodore** [comment]
Could you post the full log? Need to see the linker invocation and any configure detections.

**Comment by ArsenArsen** [comment]
I've done a fresh build with the static triple on my CI, and here is the output https://nativeci.arsenarsen.com/job/KShare%20Windows%20x86_64/70/console

**Comment by tonytheodore** [comment]
Okay, you probably need to use `pkg-config` for the linking, something like:
```
CONFIG += link_pkgconfig
PKGCONFIG += libavformat libavcodec libswscale libavutil
```
in your *.pro file should help.

**Comment by ArsenArsen** [comment]
This worked! Thank you!
