### ISSUE TITLE
json_spirit fails to build with gcc6 or gcc7 overlays

### ISSUE THREAD

**Issue by mbunkus** [mxe/mxe#1812]
json_spirit fails to build with both overlays due to `ambiguous overload of operator=` errors. [Here](https://gist.github.com/mbunkus/a26cf7ad733d204de05b873f622ad2f9) is the full build log.

To me it seems that json_spirit is not developed actively anymore. There are modified forks, and in one of them [there is a fix](https://github.com/sirikata/json-spirit/commit/9107b6d2f302f547b141c40014000235fc3016f7) for building with gcc 6. Unfortunately that patch doesn't apply to MXE's current version of json_spirit.

These problems only affect the test suite, not the main functionality or the sample programs. Locally I've therefore simply disabled the test suite instead of trying to figure out how to apply upstream's gcc 6 fix to MXE's version. The test suite cannot be run on the build host anyway.

If disabling the test suite is an acceptable workaround for MXE, then just shout and I'll provide a pull request for it.

**Comment by tonytheodore** [comment]
Disabling the test suite (along with docs, programs, demos...) is ideal - the main test we want is a link test (using any *.pc, *.cmake, or *-config helpers the package provides to demonstrate usage).

A PR is welcome!
