### ISSUE TITLE
mirror.mxe.cc certificate expired

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1819]
I'll fix it on the weekend if no-one gets a chance to look at it before then.

**Comment by tonytheodore** [comment]
It seems the ipv6 config isn't correct and `certbot` can't auto-renew.

@vog could you update the `AAAA` record for `mirror.mxe.cc` to `2604:a880:800:10::156:f001`? The previous entry I gave you is actually the gateway.

**Comment by vog** [comment]
@tonytheodore Sorry for the late response. I just changed `mirror.mxe.cc` to `2604:a880:800:10::156:f001`. As usual, please be aware that it may take up to 24h until the change is globally effective.

**Comment by tonytheodore** [comment]
Thanks @vog! Renewal is working again (after some other tweaks to the config).
