### ISSUE TITLE
poppler fails to build unless this line

### ISSUE THREAD

**Issue by jjbenham** [mxe/mxe#1820]
$(SED) -i 's,reference,'',g' '$(1)/glib/Makefile'
I put this after configure because it still tries to build and install reference docs and where it does not have permission.

**Comment by tonytheodore** [comment]
I can see this in the logs also but it doesn't cause and error:
```
ginstall: cannot create regular file '/poppler': Permission denied
```

**Comment by darealshinji** [comment]
@jjbenham 's solution fixes this for me. Otherwise the build fails: [log](https://gist.github.com/darealshinji/6f44123cfbefd8c652c0831d54d625f0)

**Comment by darealshinji** [comment]
Question: how do I build poppler-qt4 without modifying `src/poppler.mk`?

**Comment by GreedyMe** [comment]
darealshinji <notifications@github.com> wrote:

> Question: how do I build poppler-qt4 without modifying src/poppler.mk?


@darealshinji, you could try `plugins/qt4`.
