### ISSUE TITLE
Incorrectly working gcc builds (macOS and Linux)

### ISSUE THREAD

**Issue by ronaaron** [mxe/mxe#1821]
Compiled using the latest MXE from git.
Did 'make clean' and 'make gcc' on Linux, and on macOS followed the instructions on the MXE web page (e.g. installed gcc5 using macports, etc.)

Modified the PREFIX to be where I wanted to install the resultant gcc etc., since otherwise the tools didn't work at all.

The resultant gcc and g++ binaries seemed to work once I did all that.  However, the executable generated while compiling with them, did not work correctly.   Both the Linux version and the macOS version of the MXE g++ generated code which did not work correctly.

I verified that the latest g++ was the culprit by switching to the old version I was using (4.9.1) and it worked correctly.

macOS [compile log](https://gist.github.com/ronaaron/034b8b02d6c2b085f47c64805767c832)
Linux [compile log](https://gist.github.com/ronaaron/c0337e51021debc32534367165238a58)

**Comment by schloegl** [comment]
I can confirm this problem for my applications as well, which crashes at startup (attached is the backtrace.txt). In order to reproduce this, compile stimfit (just add the files src/stimfit* src/libbiosig* src/biosig* src/libb64* from  https://github.com/schloegl/mxe) and running 
   make stimfit 
(I've enabled only static builds MXE_TARGETS := i686-w64-mingw32.static x86_64-w64-mingw32.static)
The problem seems to have started around Feb 2017, however, I did not find time to bisect which update cause the problem.

**Comment by tonytheodore** [comment]
> attached is the backtrace.txt

??

**Comment by tonytheodore** [comment]
@schloegl, I was going to suggest trying the `gcc4` plugin, but you [seem to be using v4.9.4](https://github.com/schloegl/mxe/blob/master/src/gcc.mk)?

OT, adding the libs from your repo is a [long-standing issue](https://github.com/mxe/mxe/issues/1037#issuecomment-162718823). There's a new `./tools/skeleton.py` helper that makes adding packages to MXE much smoother - can you give it a try with one (or two) packages?

@ronaaron wrote:
> Modified the PREFIX to be where I wanted to install the resultant gcc etc., since otherwise the tools didn't work at all.

That [isn't entirely supported yet](#967), though it will work in some scenarios. You shouldn't "have" to do that for MXE to work.

Can you provide more details of the failing binaries, and confirm that native builds with the same compiler work as expected? We need to narrow this down - see some of the [self-contained, reproducible bugs that caused us to downgrade to gcc 4](https://github.com/mxe/mxe/pull/965#issuecomment-155362507).

We're in a tricky position with needing to update parts of the toolchain (#1822) and balancing gcc[4-7].

**Comment by tonytheodore** [comment]
@schloegl, `libbiosig` isn't setup to cross-compile from darwin so I can't test this quickly. Can you post the backtrace on gist (or some other paste-bin)?

**Comment by schloegl** [comment]
The backtrace is available from here:
https://pub.ist.ac.at/~schloegl/tmp/backtrace.txt
``

**Comment by schloegl** [comment]
The issue is gone after upgrading gcc to 7.2 . The patch is here:

https://github.com/schloegl/mxe/commit/702d99d81c9d7b24079a67f551dc1c6011ab95fb

I tested this in my own branch as well as the master branch on mxe.cc

**Comment by tonytheodore** [comment]
> The issue is gone after upgrading gcc to 7.2

@ronaaron can you try gcc7? It's likely to be the next default (#1919) and can be built with:

```
make clean
make gcc MXE_PLUGIN_DIRS=plugins/gcc7
```

The `clean` is important as the native deps (e.g. `isl`) can have different versions.

**Comment by ronaaron** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    My code doesn't compile with the new version, not sure if I want
      to invest the time to understand why it works OK w/ the old
      version...
    
    
    It may be gcc; my code is normally compiled with 5.2, which might
      be more permissive.  But I don't think that's it, since I'm seeing
      errors like "invalid use of incomplete type", which shouldn't work
      on 5.2, and also aren't correct errors.
    
    
    On 11/10/2017 11:32, Tony Theodore
      wrote:
    
    
      
        The issue is gone after upgrading gcc to 7.2
      
      @ronaaron can you try gcc7? It's
        likely to be the next default (#1919) and can be built with:
      make clean
make gcc MXE_PLUGIN_DIRS=plugins/gcc7

      The clean is important as the native deps (e.g. isl)
        can have different versions.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mxe/mxe","title":"mxe/mxe","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mxe/mxe"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tonytheodore in #1821: \u003e The issue is gone after upgrading gcc to 7.2\r\n\r\n@ronaaron can you try gcc7? It's likely to be the next default (#1919) and can be built with:\r\n\r\n```\r\nmake clean\r\nmake gcc MXE_PLUGIN_DIRS=plugins/gcc7\r\n```\r\n\r\nThe `clean` is important as the native deps (e.g. `isl`) can have different versions."}],"action":{"name":"View Issue","url":"https://github.com/mxe/mxe/issues/1821#issuecomment-335733227"}}}
    
    
    
      
        
          Ron Aaron | 
           CTO  Aaron High-Tech, Ltd |
          +1 425.296.0766 / +972 52.652.5543 |
          
            GnuPG Key: 91F92EB8
