### ISSUE TITLE
i686-w64-mingw32.static build target missing dwmapi.dll

### ISSUE THREAD

**Issue by yjdwbj** [mxe/mxe#1827]
Hi,all.
why the i686-w64-mingw32.static build target missing ``dwmapi.dll`` under windows XP 32bit? ``test-qt.exe`` also missing ``dwmapi.dll``.
---
![missing-dwmapi](https://user-images.githubusercontent.com/321919/28302506-4d591bec-6bc0-11e7-92a8-c75aa3ebb0be.png)

**Comment by tonytheodore** [comment]
The core MXE toolchain still supports Win XP, but individual projects may not - e.g. Qt [dropped support for XP in 5.7](https://wiki.qt.io/PlatformSupport). You'll have to check with the project you're trying to build to see if they can continue XP support.

**Comment by yjdwbj** [comment]
@tonytheodore  which version of MXE to supported ``Qt5.7 ``.  I wan to checkout this version and rebuild ``i686-w64-mingw32.static``.

**Comment by tonytheodore** [comment]
Qt was updated 5.7.1 --> 5.8.0 in https://github.com/mxe/mxe/commit/0f724ee4b398bab31567a2ad3a54a56ac2911c0f as part of #1650

**Comment by tonytheodore** [comment]
See #1828, staying on an old commit will make it harder to merge toolchain changes, though either approach will end up being a lot of work.
