### ISSUE TITLE
status virtual packages in http://mxe.cc/build-matrix.html

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#1829]
The status of virtual packages can be misleading.
See https://github.com/mxe/mxe/issues/1741 for example:
>Is there a specific reason why googletest is not supported on any configuration?

The same problem with mingw-w64, qt5.

While in fact these packages are fully supported

**Comment by tonytheodore** [comment]
Indeed, we should probably remove virtual (and native) packages from the build-matrix altogether - they're internal and not useful for most users.

**Comment by pavelvat** [comment]
Perhaps the best variant is to split table on three tables: "packages", "virtual packages", "native packages".

**Comment by pavelvat** [comment]
>to split table on three tables

Other variant is to remove "virtual packages", "native packages" from table and list them elsewhere. This is required to inform users that they exist.

**Comment by tonytheodore** [comment]
See #1989, preview https://htmlpreview.github.io/?https://raw.githubusercontent.com/tonytheodore/mxe/c68f9d9/docs/build-matrix.html
