### ISSUE TITLE
protobuf fails to build with too much parallelization

### ISSUE THREAD

**Issue by fiesh** [mxe/mxe#1851]
When running `make -j64`, `protobuf` initially fails to build.  After some retries, it works.  So I suspect there is a missing dependency somewhere?

```
Failed to build package protobuf for target x86_64-pc-linux-gnu!
------------------------------------------------------------
configure.ac:25: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf-2.69: /usr/bin/autoconf-2.69 failed with exit status: 1
make[1]: *** [Makefile:674: build-only-protobuf_x86_64-pc-linux-gnu] Error 1
make[1]: Leaving directory '/tmp/mxe'
real    0m26.555s
user    0m21.740s
sys     0m0.612s
------------------------------------------------------------
[log]      /tmp/mxe/log/protobuf_x86_64-pc-linux-gnu
```

**Comment by tonytheodore** [comment]
Are you running jessie, trusty, or wheezy?

**Comment by fiesh** [comment]
Gentoo :)

**Comment by tonytheodore** [comment]
Hmmm. That error should only happen if `libtool` isn't installed, but since we're not building it on Gentoo, it's hard to see why it would work after retries.

Can you post the `protobuf` and `mxe-conf` logs and the terminal output leading up to the error?

**Comment by fiesh** [comment]
[mxe-conf_x86_64-pc-linux-gnu.txt](https://github.com/mxe/mxe/files/1170068/mxe-conf_x86_64-pc-linux-gnu.txt)
[protobuf_x86_64-pc-linux-gnu.txt](https://github.com/mxe/mxe/files/1170067/protobuf_x86_64-pc-linux-gnu.txt)

**Comment by fiesh** [comment]
For some reason, to re-create the issue, I had to remove `pkg` and thus trigger re-downloading of the files.  When the files were already downloaded, it worked.  That might be a coincidence though of course if it's a race condition.

**Comment by tonytheodore** [comment]
Okay, a couple of clues:
```
# mxe-conf log - settings.mk
MXE_PLUGIN_DIRS := plugins plugins/native plugins/gcc6
# protobuf
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /tmp/mxe2/usr/x86_64-pc-linux-gnu/bin/automake line 3936.
```
It looks like the build of native `libtool` et. al. is partly finished when `protobuf` starts so the autotools are mismatched. This makes sense with a high number of inter-package jobs as they generally would use lexical sorting and finish `l*` before `p*`.

Not sure how best to handle this, we can't add `libtool` to `protobuf` deps for all builds - it's only a dep when `plugins/native` is included. Probably some metadata for packages needing the autotools and some include guard in `plugins/native` to toggle deps.

**Comment by fiesh** [comment]
Would it be possible to one unique dependency `builddep` or soto all targets and fill `builddep` in `plugins/native` with the necessary dependencies, or leave it empty otherwise?

**Comment by tonytheodore** [comment]
We currently have a similar thing in that `$(BUILD)` (e.g. `x86_64-pc-linux-gnu`) is a unique dependency with all the necessary deps MXE is going to build.

Can you try the below, its a bit more selective:
```diff
diff --git a/plugins/native/libtool.mk b/plugins/native/libtool.mk
index d4ee284..44b72c7 100644
--- a/plugins/native/libtool.mk
+++ b/plugins/native/libtool.mk
@@ -3,6 +3,7 @@
 PKG                  := libtool
 $(PKG)_TARGETS       := $(BUILD)
 $(PKG)_DEPS_$(BUILD) := autoconf automake
+$(PKG).pkg           := $(PKG)

 define $(PKG)_BUILD_$(BUILD)
     mkdir '$(1).build'
diff --git a/src/protobuf.mk b/src/protobuf.mk
index 30bfd97..985ea8e 100644
--- a/src/protobuf.mk
+++ b/src/protobuf.mk
@@ -10,7 +10,7 @@ $(PKG)_FILE     := $(PKG)-$($(PKG)_VERSION).tar.gz
 $(PKG)_URL      := https://github.com/google/$(PKG)/archive/v$($(PKG)_VERSION).tar.gz
 $(PKG)_DEPS     := gcc googlemock googletest zlib
 $(PKG)_TARGETS  := $(BUILD) $(MXE_TARGETS)
-$(PKG)_DEPS_$(BUILD) := googlemock googletest
+$(PKG)_DEPS_$(BUILD) = googlemock googletest $(libtool.pkg)

 define $(PKG)_UPDATE
     $(call MXE_GET_GITHUB_TAGS, google/protobuf, v)
```

**Comment by tonytheodore** [comment]
`pkgconf` will also need the deps line:
```
$(PKG)_DEPS_$(BUILD) = $(libtool.pkg)
```
note there isn't the usual colon in the assignment, this tells `make` to defer the evaluation until the variable is used.

**Comment by fiesh** [comment]
I had already started the build process before your update, and it ran through.  Now I'm trying again with your second change as well.  I suppose the first time I couldn't trigger the remaining race condition with `pkgconfig` that the second change resolves.

**Comment by fiesh** [comment]
... but in the true spirit of a race condition, it now failed again :(

**Comment by tonytheodore** [comment]
Same failure or different ones? The problem with `plugins/native` is that it doesn't fully bootstrap itself and does change it's own tools as it goes.

**Comment by fiesh** [comment]
The exact same problem with `protobuf`.

**Comment by tonytheodore** [comment]
What happens if you simply add `libtool` to `protobuf` deps without any of the previous changes:
```
$(PKG)_DEPS_$(BUILD) := googlemock googletest libtool
```

**Comment by tonytheodore** [comment]
See #1853, I can't actually replicate the error, but can see the logical race is fixed with:
```
make protobuf pkgconf --debug=b -n --always-make -R | grep 'Must remake target'
```

**Comment by fiesh** [comment]
I have re-run it now lots of times with `libtool` added to `protobuf` as a dependency and it always worked.  (5 times, given that it happened before in at least 2/3 of the cases, that leaves us with a likelihood that things are fine of 1-1/3^5 > 99.5 % :))

**Comment by tonytheodore** [comment]
Okay, I can replicate the error with:
```
make automake MXE_PLUGIN_DIRS=plugins/native
make protobuf MXE_TARGETS= MXE_PLUGIN_DIRS=plugins/native
```
After #1853, that order of packages (i.e. `automake` without `libtool`) won't be possible.

As an aside, why are you using `plugins/native`?

**Comment by fiesh** [comment]
I have re-run it now lots of times with `libtool` added to `protobuf` as a dependency and it always worked.  (5 times, given that it happened before in at least 2/3 of the cases, that leaves us with a likelihood that things are fine of 1-1/3^5 > 99.5 % :))

**Comment by fiesh** [comment]
As for `plugins/native`, I cannot reproduce why it's there.  Alas our `settings.mk` isn't version controlled, so I cannot even reproduce who put it there or when.  Sorry!  Removing it doesn't break anything, so I guess we'll go without it.

**Comment by tonytheodore** [comment]
> Removing it doesn't break anything, so I guess we'll go without it.

It's a trade-off between:
  - stable set of build tools for MXE if your OS updates too quickly or slowly
  - differences to normal builds since those tools are only visible to MXE

If it's been working, there's no need to change it - this bug is unrelated.
