### ISSUE TITLE
QtWebKit based program crashes at startup

### ISSUE THREAD

**Issue by dirkhh** [mxe/mxe#1863]
This used to work with an older version of MXE (Qt 5.7.1 based - SHA e134a77279b36 from December of last year), but with today's MXE (Qt 5.9.0 based - SHA 030efef3b646e I get a crash in ZN7QObject7connectEPKS_PKcS1_S3_N2Qt14ConnectionTypeE which demangles to QObject::connect, called by ZN7WebCore19initializeWebCoreQtEv () (Qt5WebKit.dll)
Are there any known problems with QtWebKit? Or with the current tool chain?
I need Qt 5.9 for my app, so I can't really go back to the older version. But given how little QtWebKit has changed over the last year, I wonder if this is maybe a tool chain issue? The big change is of course the jump from gcc 4.9.4 to 5.4.0...

**Comment by dirkhh** [comment]
I now verified that this still works with Qt5.8.0 (so SHA 90df394cecf) - but current master crashes at app start.

**Comment by dirkhh** [comment]
My favorite problems are the ones that go away... as off 265e069986b82ef55b977f9396886215c0dbd93 this is now fixed. Binaries built against Qt 5.9.1 no longer crash at startup.

**Comment by tonytheodore** [comment]
Good to hear - my favourite too!
