### ISSUE TITLE
freetype-boostrap 2.8 failed to build (undefined "HB_SCRIPT_ADLAM"/"HB_SCRIPT_OSAGE")

### ISSUE THREAD

**Issue by kmatheussen** [mxe/mxe#1865]
Here's the log:
https://gist.github.com/kmatheussen/56a72cc013fd2161484268ce391831dc

Here's my (very) simple workaround (which is obviously not the right solution, but it compiles):
```
diff --git a/src/freetype.mk b/src/freetype.mk
index 81a614b..29fd004 100644
--- a/src/freetype.mk
+++ b/src/freetype.mk
@@ -18,7 +18,7 @@ define $(PKG)_UPDATE
 endef
 
 define $(PKG)_BUILD_COMMON
-    cd '$(1)' && GNUMAKE=$(MAKE) ./configure \
+    cd '$(1)' && GNUMAKE=$(MAKE) CFLAGS="-DHB_SCRIPT_ADLAM=1 -DHB_SCRIPT_OSAGE" ./configure \
         $(MXE_CONFIGURE_OPTS) \
         LIBPNG_CFLAGS="`$(TARGET)-pkg-config libpng --cflags`" \
         LIBPNG_LDFLAGS="`$(TARGET)-pkg-config libpng --libs`" \
```

**Comment by kmatheussen** [comment]
Oh, and I also googled the problem, but it seems like no one else has had this problem.

**Comment by tonytheodore** [comment]
Looks like #1866 will fix it.

**Comment by kmatheussen** [comment]
Thank you. Haven't tried, but I guess that fixes it.

**Comment by TobiX** [comment]
Yeah, that log looks similar to the problem I was having 👍

**Comment by kmatheussen** [comment]
Yes, I can confirm that #1866 fixed it. (I recompiled everything in a desperate attempt #1868, but it didn't help.)
