### ISSUE TITLE
glib not found with fribidi

### ISSUE THREAD

**Issue by MTres19** [mxe/mxe#1867]
I'm trying to cross-compile SuperTuxKart. I installed all the dependencies I (think) I need (gcc libpng zlib libjpeg-turbo jpeg openal ogg vorbis openssl fribidi freetype curl). I generated a Makefile with CMake and edited it as described under step 5d described [here](http://mxe.cc/#tutorial), and ran make with the appropriate parameter (also described in step 5d). When make gets to compiling the translation parts, though, fribidi has trouble including glib.h, which is strange because fribidi seems to have compiled fine before. I'm not really familiar with build systems, so this might be some silly mistake I'm making, but anyway here's the build log (it's short because it's already partly compiled.)

~~~
[matthewtrescott@Toshiba-Arch bld]$ make CROSS=i686-w64-mingw32.static-
[  4%] Built target angelscript
[ 17%] Built target bulletcollision
[ 18%] Built target bulletmath
[ 21%] Built target bulletdynamics
[ 23%] Built target enet
[ 23%] Built target glew
[ 24%] Built target graphics_utils
[ 42%] Built target stkirrlicht
[ 42%] Building CXX object CMakeFiles/supertuxkart.dir/src/utils/translation.cpp.obj
In file included from /home/matthewtrescott/Projects/mxe/usr/i686-w64-mingw32.static/include/fribidi/fribidi.h:35:0,
                 from /home/matthewtrescott/Projects/stk/stk-code/src/utils/translation.cpp:40:
/home/matthewtrescott/Projects/mxe/usr/i686-w64-mingw32.static/include/fribidi/fribidi-common.h:61:20: fatal error: glib.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/supertuxkart.dir/build.make:10114: CMakeFiles/supertuxkart.dir/src/utils/translation.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/supertuxkart.dir/all] Error 2
make: *** [Makefile:135: all] Error 2
~~~

**Comment by tonytheodore** [comment]
> I generated a Makefile with CMake and edited it as described under step 5d

Try using the cmake wrapper script (`i686-w64-mingw32.static-cmake`) described in the [CMake section](http://mxe.cc/#tutorial-5b).

**Comment by MTres19** [comment]
I did use the wrapper. Sorry I forgot to mention it.

**Comment by tonytheodore** [comment]
You may need to alter [FindFribidi.cmake](https://github.com/supertuxkart/stk-code/blob/master/cmake/FindFribidi.cmake#L19) so that it uses pkg-config - `elseif(UNIX OR MINGW)` should do it.

**Comment by MTres19** [comment]
Thanks, that got me through that problem; now however I have a huge mess because STK expects to use its own dependencies package on MinGW, not the ones I compiled with MXE. So I think I will have to forget about MXE for SuperTuxKart until I know a bit more about CMake and could figure this out. Thanks for your time though.

**Comment by tonytheodore** [comment]
It looks like you'll also need to use pkg-config to add other defines:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 552f04a..74808b3 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -386,11 +386,13 @@ endif()
 # CURL
 if(MSVC)
     target_link_libraries(supertuxkart ${PROJECT_SOURCE_DIR}/dependencies/lib/libcurl.lib)
-elseif(MINGW)
+elseif(MINGW AND USE_BUNDLED_DEPENDENCIES)
     target_link_libraries(supertuxkart ${PROJECT_SOURCE_DIR}/dependencies/lib/libcurldll.a)
 else()
-    find_package(CURL REQUIRED)
+    include(FindPkgConfig)
+    pkg_check_modules(CURL libcurl)
     include_directories(${CURL_INCLUDE_DIRS})
+    add_definitions(${CURL_CFLAGS_OTHER})
 endif()

 # Common library dependencies
```

errors like `undefined reference to _imp__` are usually a missing define like `-DAL_LIBTYPE_STATIC` or `-DCURL_STATICLIB`. Other undefined references can be caused by [incorrect ordering](https://github.com/supertuxkart/stk-code/blob/master/cmake/FindOggVorbis.cmake#L42) or [de-duping](https://github.com/supertuxkart/stk-code/blob/master/cmake/FindOggVorbis.cmake#L44).

Maybe try a shared build first, if you also have to ship assets etc. static builds may not have all the usual benefits.
