### ISSUE TITLE
Hundreds of undefined references linking my Qt project

### ISSUE THREAD

**Issue by alexanderVonBergner** [mxe/mxe#1869]
Hey.
I'm trying to cross compile a Qt-GUI from Ubuntu to Windows.
I installed mxe via "make qt5" because I need QtCharts, which is only included in Qt5. I am using qmake.
While building, unfortunately I get a ton of linking errors.

I uploaded the make-command output [here](https://gist.github.com/alexanderVonBergner/d4f2502d399eb6dd6d980112ba11c10e).

Obviously I have a massive linking problem, which I am unable to understand. Do you have any ideas?

greets,
alex

**Comment by tonytheodore** [comment]
What does your *.pro file contain - it almost looks like you're somehow overriding the default `CONFIG += staticlib`

**Comment by alexanderVonBergner** [comment]
Damn, your right.
I once tried to build my application with qt4. Then I added these lines to my *.pro file:
`unix:!macx: LIBS += -L$$PWD/../../../../../Qt5.8.0/5.8/gcc_64/lib/ -lQt5Charts`
`INCLUDEPATH += $$PWD/../../../../../Qt5.8.0/5.8/gcc_64/include`
`DEPENDPATH += $$PWD/../../../../../Qt5.8.0/5.8/gcc_64/include`
`unix:!macx: LIBS += -licui18n -licuuc -licudata`
It seems I don't need these lines anymore, since I use qt5. But I left them in the file since they did not seem to harm anyway.

But when cross-compiling I obviously overrode some lib-path with this. Removing these commands from my *.pro file solved the issue.

Thank you for your quick support!
