### ISSUE TITLE
Downloads from pkg.mxe.cc are very slow

### ISSUE THREAD

**Issue by ArseniyShestakov** [mxe/mxe#1879]
I using pre-built MXE packages for our Travis CI and 200mb of downloads could take like 10+ minutes.
I certainly can just mirror packages we depend on GitHub releases, but this still need to be reported at least.

Would be nice if server could have better upload rate. I guess there plenty of open source projects and CDNs who would be happy to provide mirror for MXE or just hosting for the files with better upload rate.

**Comment by starius** [comment]
Thank you for reporting this!

I tried to reproduce the issue. I tested downloading of the file http://pkg.mxe.cc/repos/tar/mxe-x86-64-w64-mingw32.shared/mxe-x86-64-w64-mingw32.shared-gcc_5.4.0.tar.xz
From a server located in Germany I observed download speed 17.2MB/s. From a server located in the US the speed was 9.93MB/s. From a server in Russia the speed was 6.06M/s. (B means "bytes".)

Also, I rebuilt a Travis CI build that uses pkg.mxe.cc:
https://travis-ci.org/starius/battleship/jobs/152112350#L741
> Fetched 250 MB in 40s (6,132 kB/s)

Can you provide more details on how you use the service, please?
Maybe URL of a file that is being downloaded slowly.

**Comment by ArseniyShestakov** [comment]
This is really weird. Yesterday I tested it from both my own Internet connection (I'm in Russia and have 100Mbps) as well as our project DigitalOcean sever in France. From Russia it's was going as slow as 30KB/s and from France was around 1MB/s. Today for my own connection it's starting from 2MB/s and dropping down to 500KB/s, but from DigitalOcean it's solid 50MB/s.

Also here are our build logs with MXE from yesterday:
https://travis-ci.org/vcmi/vcmi/jobs/264144895 (37 minutes and 927.82s for packages install)
https://travis-ci.org/vcmi/vcmi/jobs/264154317 (31 minute and 596.66s for packages install)

Though today it's much better and package install just took about 220s for this yet-to-finish build I restarted:
https://travis-ci.org/vcmi/vcmi/builds/264156044

**Comment by ArseniyShestakov** [comment]
I really have no clue what's wrong with Travis connection to MXE server since our DigitalOcean instances have good download speed, but again it's took Travis up to 20 minutes to download 200mb of packages.

So I just mirrored our deps on GitHub releases:
https://github.com/vcmi/vcmi-deps-mxe

**Comment by tonytheodore** [comment]
> So I just mirrored our deps on GitHub releases:

Nice approach! Mirrors are often the only solution, we use up to 5 sources as it was once one our most common issues.
