### ISSUE TITLE
jack package fails to build

### ISSUE THREAD

**Issue by bill-auger** [mxe/mxe#1881]
the debian package contains only one single 'installed' file
```
$ apt show mxe-i686-w64-mingw32.static-jack 
Package: mxe-i686-w64-mingw32.static-jack
Version: 1.9.10-20170208
...

$ dpkg -L mxe-i686-w64-mingw32.static-jack 
/.
/usr
/usr/lib
/usr/lib/mxe
/usr/lib/mxe/usr
/usr/lib/mxe/usr/i686-w64-mingw32.static
/usr/lib/mxe/usr/i686-w64-mingw32.static/installed
/usr/lib/mxe/usr/i686-w64-mingw32.static/installed/jack
```

`make jack` build from a clone of this git repo (af2108d8 2017-08-20) is apparently successful but the jack library is not actually built - this is the entire contents of the build log:
```
$ cat  log/jack_i686-w64-mingw32.static
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/code/mxe'
touch '/code/mxe/usr/i686-w64-mingw32.static/installed/jack'
make[1]: Leaving directory '/code/mxe'

real	0m5.113s
user	0m4.916s
sys	0m0.044s
```

**Comment by ArseniyShestakov** [comment]
Problems appear from here: #1139

**Comment by ArseniyShestakov** [comment]
And one more note: while Windows MSVC build for Jack is not entirely static it's still only contain portaudio_x86.dll and JackRouter.dll.

**Comment by bill-auger** [comment]
ok so this is a 'wontfix'? - i just wanted to point out that you are currently shipping a debian package that is essentially empty - it's not clear that it serves any purpose

**Comment by tonytheodore** [comment]
It's a known issue, we currently don't have any way to distinguish between virtual packages used for [dependencies or file downloads](https://github.com/mxe/mxe/commit/686afc35ecd513c2e0934a6d0287665efcc2a3a7) (e.g. qt5 and googlemock), and [disabled packages](https://github.com/mxe/mxe/commit/c2c0c26761808c5778c243cd337d8961a81a7672). Some extra metadata is required in the package makefiles to filter these out - I have some WIP on this but it's mixed in with a larger set of changes.

For this specific package, it uses the `waf` build system that most people are unfamiliar with. The only other package using `waf` is `aubio`, but that seems to require a [lot of patching for static builds](https://github.com/mxe/mxe/commits/master/src/aubio-1-fixes.patch).

**Comment by tonytheodore** [comment]
#1990 will fix the empty package problem, enabling static `jack` still looks tricky.

**Comment by bill-auger** [comment]
thanks - just to be clear that this issue is not a priority for me - this was some time ago but as i remember the only reason i wanted to use static libs was because the shared libs of sdl-ttf were not available and the static libs for JACK appeared to be available - i would like to put this together someday but still for now my program's requirements of both JACK and SDL1.2 are unsatisfiable with MXE unless i re-write it for SDL2

**Comment by tonytheodore** [comment]
I see, enabling shared builds is sometimes as easy as `--enable-shared` (as for sdl_ttf and sdl_net in #1992). It's often a case that nobody has looked at it where disabled static builds are usually for a reason.
