### ISSUE TITLE
build-pkg issues

### ISSUE THREAD

**Issue by hurzelchen** [mxe/mxe#1886]
I'm currently having to minor issues with build-pkg:

- It doesn't create a meta-package for `qt5` that would just simply reference all dependencies.
- the packages for `mxe-conf` and `cmake-conf` contain conflicting `.gitkeep` files.

**Comment by hurzelchen** [comment]
the `x86-64-pc-linux-gnu` versions of `mxe-conf` and `cmake-conf` also both contain `nonetwork.so`.

**Comment by hurzelchen** [comment]
and a last more cosmetic issue: the `Installed-Size` field of the debian packages are not set, so `apt-get` always reports no new disk space to be used.

**Comment by starius** [comment]
Binary package for qt5 is not created because the package itself is empty.
Empty packages such that no non-empty packages depend on them are skipped after https://github.com/mxe/mxe/issues/968
Frankly speaking I don't remember what was the issue with empty packages, probably just a matter of taste. I'll try to change build-pkg to build such packages. Also it is likely to result in its simplification.

**Comment by starius** [comment]
I've sent the fix in https://github.com/mxe/mxe/pull/1906
Can you verify that it builds the qt5 package, please?

**Comment by starius** [comment]
With regard to the conflicting .gitkeep files, I identified all such files:
```
$ cat *.list | grep .gitkeep | sort | uniq -d
usr/i686-w64-mingw32.shared/installed/.gitkeep
usr/i686-w64-mingw32.static/installed/.gitkeep
usr/x86_64-unknown-linux-gnu/installed/.gitkeep
usr/x86_64-unknown-linux-gnu/lib/.gitkeep
usr/x86_64-w64-mingw32.shared/installed/.gitkeep
usr/x86_64-w64-mingw32.static/installed/.gitkeep
```

In all cases a package installs other files to the same library, so these `.gitkeep` files can be safely added to the blacklist. I'll send a PR.

**Comment by starius** [comment]
The PR to ignore these .gitkeep files: https://github.com/mxe/mxe/pull/1907

**Comment by starius** [comment]
https://github.com/mxe/mxe/pull/1908 was sent to address the Installed-Size issue.
