### ISSUE TITLE
 error: 'Orientation' in 'class QPrinter' does not name a type / 'QPrinter::Orientation' has not been declared

### ISSUE THREAD

**Issue by FyreDemonyte** [mxe/mxe#1887]
```bash
In file included from ../mxe/usr/i686-w64-mingw32.static/qt5/include/QtPrintSupport/QtPrintSupport:21:0,
                 from src/qt/qcustomplot.h:54,
                 from src/qt/qcustomplot.cpp:26:
../mxe/usr/i686-w64-mingw32.static/qt5/include/QtPrintSupport/qprintpreviewwidget.h:78:15: error: 'Orientation' in 'class QPrinter' does not name a type
     QPrinter::Orientation orientation() const;
               ^
../mxe/usr/i686-w64-mingw32.static/qt5/include/QtPrintSupport/qprintpreviewwidget.h:91:35: error: 'QPrinter::Orientation' has not been declared
     void setOrientation(QPrinter::Orientation orientation);

Makefile.Release:19375: recipe for target 'build/qcustomplot.o' failed
make: *** [build/qcustomplot.o] Error 1
make: *** Waiting for unfinished jobs....
```
This is somewhat confusing as it seems the error is in MXE's QtPrintSupport file? 
The project that I'm cross-compiling for 32-bit binary on Windows is [AmsterdamCoin](https://github.com/CoinProjects/AmsterdamCoin)

**Comment by D3m0nKingx** [comment]
My linux box setup is:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
Linux UbuntuHP 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tonytheodore** [comment]
Qt5 has since been updated, can you see if the error still occurs?

**Comment by mosolovsa** [comment]
Got that error due to 
add_compile_definitions(QT_NO_PRINTER)
in CMakeLists.txt of third-party project

Remove define of QT_NO_PRINTER fixes the issue in my case
