### ISSUE TITLE
Jasper library for MXE 32 bits shared linking problem.

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#1896]
Hi,

Even if Jasper library is compiled properly here with and update from today evening, the linking stage with my client application "digiKam" do not work as expected : 

Scanning dependencies of target digikamcore
[ 61%] Building CXX object core/app/CMakeFiles/digikamcore.dir/utils/digikam_debug.cpp.obj
[ 61%] Linking CXX shared library ../../bin/libdigikamcore.dll
CMakeFiles/digikamcore.dir/objects.a(jp2kloader.cpp.obj): In function `ZN7Digikam10JP2KLoader4saveERK7QStringPNS_18DImgLoaderObserverE':
/mnt/data/GIT/5.x/core/libs/dimg/loaders/jp2kloader.cpp:813: undefined reference to `jp2_encode'
collect2: error: ld returned 1 exit status
core/app/CMakeFiles/digikamcore.dir/build.make:1971: recipe for target 'bin/libdigikamcore.dll' failed
make[2]: *** [bin/libdigikamcore.dll] Error 1
CMakeFiles/Makefile2:11944: recipe for target 'core/app/CMakeFiles/digikamcore.dir/all' failed
make[1]: *** [core/app/CMakeFiles/digikamcore.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Sound like a method is not well exported from the Jasper dll.

Note : The digiKam code about JPEG2K codec support still unchanged since a while, so we suppose that problem is located with Jasper MXE packaging, because it compile fine few week ago when we release digiKam 5.7.0.

Best

Gilles Caulier

**Comment by cgilles** [comment]
An update : same problem with 64 bits shared build process. Same error reported at the same place.

**Comment by tonytheodore** [comment]
Jasper has [since been updated](https://github.com/mxe/mxe/commit/104095662ad12c8fec932dd8c757ca572f057c1d#diff-a9534434302200f4e3621a1f9bb0e4d3), can you check if the error is still there?

**Comment by cgilles** [comment]
yes, i will do it this evening...

Gilles Caulier

**Comment by tonytheodore** [comment]
It will probably still fail, it looks like there's quite a few missing export/DLL changes recently, something must have changed going from v1.9x to v2x:
https://github.com/mdadams/jasper/commits/master/src/libjasper/include/jasper/jas_image.h

**Comment by cgilles** [comment]
The problem is not fully solved. I updated MXE (i see the patch applied to Jasper library), but at end it still on symbol not exported from Jasper API : 

Scanning dependencies of target digikamcore
[ 85%] Building CXX object core/app/CMakeFiles/digikamcore.dir/digikamcore_autogen/moc_compilation.cpp.obj
[ 85%] Building CXX object core/app/CMakeFiles/digikamcore.dir/utils/digikam_debug.cpp.obj
[ 85%] Linking CXX shared library ../../bin/libdigikamcore.dll
CMakeFiles/digikamcore.dir/objects.a(jp2kloader.cpp.obj): In function `ZN7Digikam10JP2KLoader4saveERK7QStringPNS_18DImgLoaderObserverE':
/mnt/devel/GIT/5.x/core/libs/dimg/loaders/jp2kloader.cpp:813: undefined reference to `jp2_encode'
collect2: error: ld returned 1 exit status
core/app/CMakeFiles/digikamcore.dir/build.make:1719 : la recette pour la cible « bin/libdigikamcore.dll » a échouée
make[2]: *** [bin/libdigikamcore.dll] Erreur 1
CMakeFiles/Makefile2:11956 : la recette pour la cible « core/app/CMakeFiles/digikamcore.dir/all » a échouée
make[1]: *** [core/app/CMakeFiles/digikamcore.dir/all] Erreur 2
Makefile:140 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by tonytheodore** [comment]
Can you try [this patch for jasper](https://gist.github.com/tonytheodore/9d369a754f0ea217fd11f22c7f3ef5ee)? It's only the `jp2*` functions, but I imagine the `JAS_DLLEXPORT` needs to be added to all public functions.

**Comment by tonytheodore** [comment]
> but I imagine the JAS_DLLEXPORT needs to be added to all public functions.

I've asked upstream https://github.com/mdadams/jasper/issues/155

**Comment by tonytheodore** [comment]
It seems the `jp2_*` functions are internal and shouldn't be exported https://github.com/mdadams/jasper/issues/155#issuecomment-334163924:

> Generally speaking, library users should not be directly calling internal functions in the library. The only functions that should be exposed to the user start with the jas_ prefix. Functions with the jp2_ prefix are internal implementation details of the JP2 codec and should not be invoked directly by the library user.

You can add custom patches to the digikam tree by adding folder with the patch and building with:
```
make MXE_PLUGIN_DIRS=/path/to/custom/patches ...
```
 see the usage notes for more details https://github.com/mxe/mxe/tree/master/plugins#usage

**Comment by cgilles** [comment]
Thanks. This must be fixed with this commit : 
https://commits.kde.org/digikam/56ba3493e4b06ba43546c87dec09f0e2cd42acc5
