### ISSUE TITLE
MXE 32 bits shared : Protobuf package download is broken while MXE install from scratch

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#1897]
The Protobuf package download fail while installing MXE 32 bits from scratch :  

[no-build]  googletest             x86_64-pc-linux-gnu                                                                    
[download]  isl                                                                                                           
+ echo 'MXE Warning! Downloading isl from second URL.'                                                                    
MXE Warning! Downloading isl from second URL.                                                                                                           
[build]     isl                    x86_64-pc-linux-gnu                                                                                                  
[done]      isl                    x86_64-pc-linux-gnu                                      40964 KiB      0m27.409s                                    
[download]  libltdl                                                                                                                                     
[no-build]  libtool                x86_64-pc-linux-gnu                                                                                                  
[download]  lzma                                                                                                                                        
[no-build]  lzma                   x86_64-pc-linux-gnu                                                                                                  
[download]  mpfr                                                                                                                                        
[build]     mpfr                   x86_64-pc-linux-gnu                                                                                                  
[done]      mpfr                   x86_64-pc-linux-gnu                                      15628 KiB      0m24.399s                                    
[download]  mpc
[build]     mpc                    x86_64-pc-linux-gnu
[done]      mpc                    x86_64-pc-linux-gnu                                      5620 KiB       0m8.946s
[download]  pkgconf
[build]     pkgconf                x86_64-pc-linux-gnu
[done]      pkgconf                x86_64-pc-linux-gnu                                      1504 KiB       0m6.124s
[download]  protobuf

Download failed or wrong checksum of package protobuf!
------------------------------------------------------------
  4000K .......... .......... .......... .......... .......... 95% 1,67M 0s
  4050K .......... .......... .......... .......... .......... 96% 1,21M 0s
  4100K .......... .......... .......... .......... .......... 97% 3,73M 0s
  4150K .......... .......... .......... .......... .......... 99% 1,77M 0s
  4200K .......... .......... .......... .....                100% 6,54M=2,6s
2017-09-13 22:50:54 (1,60 MB/s) — « /home/gilles/Documents/GIT/5.x/project/bundles/mxe/build.win32/pkg/.tmp-protobuf-3.3.2.tar.gz » sauvegardé [4337495/4337495]
+ cat /home/gilles/Documents/GIT/5.x/project/bundles/mxe/build.win32/pkg/.tmp-protobuf-3.3.2.tar.gz
+ rm /home/gilles/Documents/GIT/5.x/project/bundles/mxe/build.win32/pkg/.tmp-protobuf-3.3.2.tar.gz
------------------------------------------------------------
[log]      /home/gilles/Documents/GIT/5.x/project/bundles/mxe/build.win32/log/protobuf-download

Makefile:533: recipe for target 'download-only-protobuf-3.3.2.tar.gz' failed
make: *** [download-only-protobuf-3.3.2.tar.gz] Error 1

Problem is always reproducible, even if MXE broken install is cleanup and restarted.

**Comment by starius** [comment]
It should be fixed after https://github.com/mxe/mxe/pull/1895
