### ISSUE TITLE
Portability Issue

### ISSUE THREAD

**Issue by jdk** [mxe/mxe#1902]
I'm using Travis-CI to deploy my software. Unfortunately, there is no qt5 package in the mxe apt-repo, so I need to build mxe on travis. The mxe building times out. With build matrixes, the build time grows exponentially.  So I figured, I'd get the same docker image they use, build mxe, archive it to the cloud. On Travis, I download that, unzip to the same directory it was built on, and use it in my build.

Unfortunately, that's not working, and I'm getting the following error:
/tmp/ccWJHzeP.s:2: Fatal error: bad .section directive: want a,l,w,x,M,S,G,T in string

So it's still unhappy about being relocated. Any help would be greatly appreciated. I'm stuck.

**Comment by tonytheodore** [comment]
MXE generally isn't relocatable, though it "should" work if all paths are the same - unfortunately, I've never really tried so don't have any tips.

The next set of packages will have a `qt5` meta-package, but in the mean time it may be best to just list out all the individual packages (may vary slightly depending on the version of qt5 in the apt repo):
```
$ make gmsl-print-qt5_DEPS
qt5_DEPS = qt3d qtbase qtactiveqt qtcanvas3d qtcharts qtconnectivity qtdatavis3d qtdeclarative qtgamepad qtgraphicaleffects qtimageformats qtlocation qtmultimedia qtpurchasing qtquickcontrols qtquickcontrols2 qtscript qtscxml qtsensors qtserialbus qtserialport qtspeech qtsvg qttools qttranslations qtvirtualkeyboard qtwebchannel qtwebkit qtwebsockets qtwebview qtwinextras qtxmlpatterns
```
