### ISSUE TITLE
Establish HTTPS for mxe.cc and pkg.mxe.cc

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1909]
We can use Let's Encrypt for this.
Proposed in https://github.com/mxe/mxe/pull/1899#issuecomment-331719814

**Comment by tonytheodore** [comment]
How would `mxe.cc` be handled? It's currently a github pages site and most recommendations involve using an intermediary with re-directs (which doesn't seem ideal).

**Comment by vszakats** [comment]
https://www.netlify.com/ does support custom domains with HTTPS, it also integrates well with GitHub, and it's free for projects like MXE. I believe it was or is used for the Homebrew homepage.

(Some put their GitHub hosted pages behind a CloudFlare proxy, but that's a non-solution, as the traffic remains unencrypted/unprotected between CloudFlare and GitHub. Not very honest/secure.)

**Comment by tonytheodore** [comment]
Netlify looks good though I'm not sure if we want to add a service to serve static html - we don't really use any gh-pages functionality.

**Comment by vszakats** [comment]
Anything blocking to enable this for `mxe.cc`? It may need some DNS record updates, but the bigger part of HTTPS is support is automatically handled by GitHub, all it needs is enabling support for it on the project settings page.

**Comment by tonytheodore** [comment]
@vog, can you take a look at this? The DNS records need to be updated as noted in https://help.github.com/articles/troubleshooting-custom-domains/#custom-domains-configured-with-a-records

**Comment by vog** [comment]
@tonytheodore Thanks for bringing this to my attention. I'll take care of this as soon as possible.

**Comment by vog** [comment]
Okay, I just changed the A records for mxe.cc from:

* 192.30.252.153
* 192.30.252.154

to:

* 185.199.108.153
* 185.199.109.153
* 185.199.110.153
* 185.199.111.153

Some remarks:

* Please note that it may take up to 24h for those changes to propagate through the DNS caches all over the world
* I did not need to change www.mxe.cc, as this is a CNAME for mxe.cc.
* "you must remove and re-add your custom domain to the repository you’re using to publish your Pages site to trigger the process of enabling HTTPS" (from https://help.github.com/articles/troubleshooting-custom-domains/#custom-domains-configured-with-a-records)

@tonytheodore Would you mind to take care of that last step?

**Comment by vszakats** [comment]
Thank you @vog and @tonytheodore. Can someone update the address on the header of this GitHub project? [ https://github.com/mxe/mxe/ ]

**Comment by tonytheodore** [comment]
> update the address on the header of this GitHub project?

Done.

**Comment by vog** [comment]
I just updated the website link in our documentation as well.

So the transition of (www.)mxe.cc from HTTP to HTTPS is finished.

@starius It seems that pkg.mxe.cc is stil HTTP. What can we do about that? Do you need any assistance from me?

**Comment by vszakats** [comment]
[ Issued a PR that updates the URL over the whole repo (plus some more URL updates): https://github.com/mxe/mxe/pull/2170

**Comment by vszakats** [comment]
Any thoughts on what would need to be done to HTTPS-ify <http://pkg.mxe.cc/>? Pulling binaries via HTTP has its risks.

The web server already seems to support HTTPS, but the assigned certificate doesn't match the domain name. Presumably a Let's Encrypt certificate configured for that domain would solve the issue, along with a cron job periodically running `certbot` on the server.

![screen shot 2018-09-14 at 21 06 25](https://user-images.githubusercontent.com/1446897/45570277-64aa7a80-b862-11e8-9aa3-7ee899f86d5e.png)

**Comment by tehnick** [comment]
@tonytheodore add label `build-pkg` to this issue please.

**Comment by vog** [comment]
Why was this ticket closed?

**Comment by vszakats** [comment]
HTTPS has been working fine for a while now on these two domains.

**Comment by vog** [comment]
OK, great!

**Comment by tonytheodore** [comment]
See #2536, we can improve the protocols and ciphers being used.
