### ISSUE TITLE
Add support for sqlcipher

### ISSUE THREAD

**Issue by aquiles2k** [mxe/mxe#1911]
Hi, would it generally be possible to add the sqlcipher library? Its a sqlite variant with builtin encryption support. See https://github.com/sqlcipher/sqlcipher

**Comment by aquiles2k** [comment]
As a note, msys2 also added it some month ago, so this could be used as an orientation?

https://github.com/Alexpux/MINGW-packages/commit/f083f27fb163b68673d5ac649fae353f44b49c7d

**Comment by tonytheodore** [comment]
Seems like it could clobber the existing `sqlite` install?

**Comment by aquiles2k** [comment]
Hm i dont see why? I'm using it already successfully on my msys2/mingw setup on win and it doesnt get in the way of normal sqlite, well at least as far as i can tell. In homebrew its also a non keg package (https://github.com/Homebrew/homebrew-core/blob/master/Formula/sqlcipher.rb).

Or am i missing something?

**Comment by starius** [comment]
I tried to add sqlcipher to MXE: https://github.com/LuaAndC/mxe/commit/5bcf2e2b47212540220b375c9655c537c23544b4
It fails to build: https://gist.github.com/4097310f8c99876eed37efc01cc10b41

**Comment by aquiles2k** [comment]
Hm sorry thats over my head, i dont know why hes missing something basic like fcntl and the other stuff. As far as i can see in code the sqlite3.c file includes the fcntl.h header.  Its the same with missing uid_t or gid_t typenames which should be in unistd.h which looks as included.

**Comment by aquiles2k** [comment]
perhaps something with the static build due to missing dlfcn.h? have u tried a dynamic build?

**Comment by tonytheodore** [comment]
Try the following:
```
diff --git a/src/sqlcipher.mk b/src/sqlcipher.mk
index ce8caf5..36698da 100644
--- a/src/sqlcipher.mk
+++ b/src/sqlcipher.mk
@@ -14,6 +14,8 @@ define $(PKG)_BUILD
     cd '$(BUILD_DIR)' && $(SOURCE_DIR)/configure \
         "LIBS=$$($(TARGET)-pkg-config --libs libcrypto)" \
         "CFLAGS=-DSQLITE_HAS_CODEC" \
+        config_BUILD_EXEEXT='' \
+        config_TARGET_EXEEXT='.exe' \
         --enable-tempstore=yes \
         --disable-tcl \
         --disable-editline \
```
I also added `dlfcn-win32` to deps but I'm not sure if it's necessary.

Also, it won't affect normal `sqlite`, headers and libs are separated:
```
$ i686-w64-mingw32.static-pkg-config --cflags --libs sqlcipher
-I/Users/tonyt/dev/mxe/usr/i686-w64-mingw32.static/include/sqlcipher -lsqlcipher -lpthread -lcrypto -lws2_32 -lgdi32 -lcrypt32 -lz
```
