### ISSUE TITLE
Xcode 9 Support?

### ISSUE THREAD

**Issue by jonpryor** [mxe/mxe#1913]
In a surprise move that should shock nobody, MXE commit ce28d4e5 doesn't build as-is with Xcode 9 on macOS 10.12.6 (should I upgrade?):

    make MXE_TARGETS="x86_64-w64-mingw32.static" PKGS="mxe-conf mingw-w64 gmp mpfr mpc isl gcc cmake-conf cmake zlib pthreads dlfcn-win32 mman-win32" MXE_VERBOSE=true

eventually fails with:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:1398:2: error: no member named 'fancy_abort' in namespace 'std::__1'; did you mean simply 'fancy_abort'?
        _VSTD::abort();
        ^~~~~~~
```

If you're wondering why I'm using `PKGS="..."`, it's because if I build everything, it fails when trying to build `protobuf`. I don't know if this is because I have a hosed Homebrew install (seems good to me?) or because of Xcode 9:

https://gist.github.com/jonpryor/85e7152120693e24d46ff7bd254afd1d

**Comment by tonytheodore** [comment]
I've seen that `fancy_abort` error with [Xcode 9 before](https://github.com/mxe/mxe/issues/1758#issuecomment-314744552), but haven't had a chance to really investigate. I've now updated to Xcode 9/macOS 10.13 and will do some testing.

The `protobuf` error is most likely mismatched autoconf/automake/libtool installs. If the output of:
```
$ which {autoconf,automake,libtool}
```
are in different prefixes, you can try:
```
make libtool MXE_PLUGIN_DIRS=plugins/native
```
to build a known working set and avoid `PKGS="..."`.

**Comment by tonytheodore** [comment]
See #1915, the `gcc` error has luckily been fixed upstream.

**Comment by akoeplinger** [comment]
The PR fixed the issue for me :)

**Comment by tonytheodore** [comment]
Good to hear, it's working consistent here too.
