### ISSUE TITLE
Cross-compile GNU Make

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#1924]
From https://github.com/mxe/mxe/tree/master/plugins/examples/host-toolchain#make:

> Make is difficult to cross-compile so it is downloaded from the [source
recommended by the GNU Make team](https://git.savannah.gnu.org/cgit/make.git/tree/README.W32.template)

We really should build this ourselves;)

**Comment by darealshinji** [comment]
Here's a Makefile I made based on build_w32.bat: https://gist.github.com/darealshinji/b9ebd436313be6bb8be1e72ddc1b2906

To build without guile run `make -f Makefile.mingw WITHOUT_GUILE=1`

However I didn't check if the built make.exe actually works.
