### ISSUE TITLE
gtk2 & gtk3 - test programs does not build

### ISSUE THREAD

**Issue by AmatCoder** [mxe/mxe#1934]
On Arch Linux host, **gtk2** & **gtk3** packages fails to build because test programs gives an error.
It is a _'multiple definition of symbol'_ linker error. It seems a conflict between **gtk** and **glib** symbols.

gtk2 error:
```
/tmp/mxe/tmp-glib-i686-w64-mingw32.static/glib-2.50.2/gobject/gmarshal.c:2452: multiple definition of g_cclosure_marshal_BOOLEAN__BOXED_BOXED'
/tmp/mxe/usr/i686-w64-mingw32.static/lib/../lib/libgtk-win32-2.0.a(gtkmarshalers.o):/tmp/mxe/tmp-gtk2-i686-w64-mingw32.static/gtk+-2.24.29/gtk/gtkmarshalers.c:101: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:675: build-only-gtk2_i686-w64-mingw32.static] Error 1
```
gtk3 error:
```
/tmp/mxe/tmp-glib-i686-w64-mingw32.static/glib-2.50.2/gobject/gmarshal.c:2492: multiple definition of `g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv'
/tmp/mxe/usr/i686-w64-mingw32.static/lib/../lib/libgtk-3.a(libgtk_3_la-gtkmarshalers.o):/tmp/mxe/tmp-gtk3-i686-w64-mingw32.static/gtk+-3.22.7/gtk/gtkmarshalers.c:189: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:675: build-only-gtk3_i686-w64-mingw32.static] Error 1
```
Complete logs:
[gtk2_i686-w64-mingw32.static.log](https://gist.github.com/AmatCoder/461ca54bde6050019742c16be50a30b6/raw/82c8111fc1136cf24e6137cbd3ea95b6bf18b2c2/gistfile1.txt)
[gtk3_i686-w64-mingw32.static.log](https://gist.githubusercontent.com/AmatCoder/0845b84c9b44ba6a84a3a3b6f1bbaae0/raw/2f400e165ea547b3d21b9b1781b93ebc109934f1/gistfile1.txt)

**Comment by tonytheodore** [comment]
Could you post the full log for `glib`? I suspect there's something there that's affecting both gtk2 & 3.

**Comment by AmatCoder** [comment]
Sure, here it is:
[glib_i686-w64-mingw32.static.log](https://gist.githubusercontent.com/AmatCoder/6b7fa6c52f79829938d175ea6d2bd080/raw/44d13b5e89d44e69971fdc5893c3939f0ff5384c/gistfile1.txt)

**Comment by AmatCoder** [comment]
Hmm, it seems that mxe uses **'glib-genmarshal'** from host. It is an utility that generates C code marshallers for callback functions.

In version 2.53.1 'glib-genmarshal' utility was rewritten in python.

As Arch Linux currently has 2.54.1 version, I think this is an incompatibility between versions ('glib-genmarshal' from 2.54.1 does not generate correct C code with a list of marshallers coming from 2.50.2).

**Comment by AmatCoder** [comment]
Confirmed, it works if I edit **glib.mk** file to force to build glib tools.

**Comment by tonytheodore** [comment]
Thanks, I can see the same error after updating OSX to the latest glib (same as Arch v2.54.1) but the native build fails. The native build has always been an issue (also for FreeBSD) but I think it's the best option to keep the tools in sync.

**Comment by soen-vanned** [comment]
What did you change in glib.mk to force building of glib tools?

**Comment by tonytheodore** [comment]
@soen-vanned, this should work:

```diff
diff --git a/src/glib.mk b/src/glib.mk
index 9f1bb46..e01df36 100644
--- a/src/glib.mk
+++ b/src/glib.mk
@@ -83,7 +83,7 @@ define $(PKG)_BUILD
             $(shell [ -x "`which glib-genmarshal`" ] && \
                     [ -x "`which glib-compile-schemas`" ] && \
                     [ -x "`which glib-compile-resources`" ] && echo y)), \
-        $($(PKG)_SYMLINK), \
+        $($(PKG)_NATIVE_BUILD), \
         $($(PKG)_NATIVE_BUILD))

     # cross build
```

**Comment by soen-vanned** [comment]
Awesome, thank you!

**Comment by tonytheodore** [comment]
@AmatCoder, @soen-vanned can you test #1943 and let me know if it works?

**Comment by AmatCoder** [comment]
@tonytheodore yes, it works here on Arch Linux (x86_64-pc-linux-gnu with glib 2.54.1).
Thanks!
