### ISSUE TITLE
Qt5 compilation QML missing module

### ISSUE THREAD

**Issue by mathben** [mxe/mxe#1939]
I am on Arch Linux, I installed Qt5 from Qt website. I compiled with qmake and cmake without problem.

I follow this guide : https://askubuntu.com/questions/656219/building-a-windows-executable-in-qt-on-a-linux-system

~/git/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 ..
Project ERROR: Unknown module(s) in QT: qml quick svg charts 3dcore 3drender 3dextras

.qmake.stash output : 
https://gist.github.com/mathben/fa4faca4f7d54ac774926b0fe7e210d9

**Comment by mabrand** [comment]
The cause of the missing modules might be that you didn't build them. "make qtbase" builds only that. If you  want to build all of qt5, do "make qt5". Or, you can build the specific modules you need.

By the way, the guide you followed might be a bit dated. Good directions are in MXE documentation.
