### ISSUE TITLE
cannot find -lsecp256k1

### ISSUE THREAD

**Issue by LowKey88** [mxe/mxe#1942]
Hi,

I'm having an issue and stuck at here. Can anyone advise on how to fix this?

lib/libQt5Core.a -lmpr -lversion -lws2_32 -lkernel32 -luser32 -lshell32 -luuid -lole32 -ladvapi32 -lwinmm -lz -lpcre2-16 build/bitcoin-qt_res.o
/mnt/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lsecp256k1
/mnt/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_system-mgw49-mt-s-1_57
/mnt/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_filesystem-mgw49-mt-s-1_57
/mnt/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_program_options-mgw49-mt-s-1_57
/mnt/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_chrono-mgw49-mt-s-1_57
collect2: error: ld returned 1 exit status

Thank you

**Comment by tonytheodore** [comment]
You need to add the library path (with `-L`) where `sec256k1` and `boost-*` libraries are installed. The name mangling on the boost libs looks like you are mixing in a custom build of boost?

**Comment by LowKey88** [comment]
@tonytheodore , it's working now.

Yes, fixed by correct the library path.

Thanks a lot.

**Comment by aigamal** [comment]
@tonytheodoreMay I get more details how to fix this error.
my compile process works for an hour then I get this error, which file and which parameter need to change

**Comment by tonytheodore** [comment]
> which file and which parameter need to change

The file depends on which build system you use and the parameter is whatever sets (or adds to) the library search path (or extra linker flags).

**Comment by hronopay** [comment]
@tonytheodore Thank you for answers, but I did not finally understand what you mean by adding library path  with -L. Do i need to add a new path to the PATH variable (secp256k1 is installed in /usr/local/lib, this path is already in $PATH), or  need to add some entry to one of the skript files (which one?). Could you clarify what exactly and where i need to write down to? Thank you.

**Comment by talium-project** [comment]
I also would like to know that.

**Comment by project-Positronium** [comment]
I am encountering exactly the same problem. Could someone explain how to solve this? 

Thanks in advance!

**Comment by tonytheodore** [comment]
If you think it through, in order to find a library:
  - the library must exist and have been compiled with a compatible toolchain
  - the linker must be told where the library is located
  - the `-L` flag tells the linker where to find `-lsecp256k1`

If you could explain exactly what you are trying to do (and not the final problem encountered) it would be easier to offer some help. I suspect you are reading some outdated instructions and/or using a *.pro file with hard-coded library names.

**Comment by project-Positronium** [comment]
Thanks for you response. For 4/5 of the errors it was indeed the case that there were hard-coded library names in the *.pro file. 

I am only left with the error;
> /mnt/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lsecp256k1
collect2: error: ld returned 1 exit status`

I am following this instructions [https://bitcointalk.org/index.php?topic=1080289.0 ](https://bitcointalk.org/index.php?topic=1080289.0)
and try to compile [https://github.com/MEDICCOIN/MedicCoin/blob/master/qt.pro](https://github.com/MEDICCOIN/MedicCoin/blob/master/qt.pro) with the following compile.sh (taken from the example of bitcointalk):

(I'm using Ubuntu 16.04)

`#!/bin/bash
MXE_INCLUDE_PATH=/mnt/mxe/usr/i686-w64-mingw32.static/include
MXE_LIB_PATH=/mnt/mxe/usr/i686-w64-mingw32.static/lib

i686-w64-mingw32.static-qmake-qt5 \
	BOOST_LIB_SUFFIX=-mt \
	BOOST_THREAD_LIB_SUFFIX=_win32-mt \
	BOOST_INCLUDE_PATH=$MXE_INCLUDE_PATH/boost \
	BOOST_LIB_PATH=$MXE_LIB_PATH \
	OPENSSL_INCLUDE_PATH=$MXE_INCLUDE_PATH/openssl \
	OPENSSL_LIB_PATH=$MXE_LIB_PATH \
	BDB_INCLUDE_PATH=$MXE_INCLUDE_PATH \
	BDB_LIB_PATH=$MXE_LIB_PATH \
	MINIUPNPC_INCLUDE_PATH=$MXE_INCLUDE_PATH \
	MINIUPNPC_LIB_PATH=$MXE_LIB_PATH \
	QMAKE_LRELEASE=/mnt/mxe/usr/i686-w64-mingw32.static/qt5/bin/lrelease qt.pro

make -f Makefile.Release`

My problem is that I do not know how I can add secp256k1. Can I compile it in the coin folder (where it is located) with particular flags? Should I add something to my $PATH? Do I have to specify the library location in my compile.sh ? I tried a lot of these options but nothing has worked so far. 

It would be great if you would know how to do this or could give me some direction,

Thanks in advance!

**Comment by tonytheodore** [comment]
Search the *.pro file for `secp`.

The first section seems to [disable the build for win32 and hard-code a previously built library path](https://github.com/MEDICCOIN/MedicCoin/blob/master/qt.pro#L127-L146), notably that path is on `C:`.

The next section [adds the (erroneous) library path to `-L`](https://github.com/MEDICCOIN/MedicCoin/blob/master/qt.pro#L607) - there's no problem with this per-se, just that the library doesn't exist there.

> My problem is that I do not know how I can add secp256k1

There's no reference to `secp` in the original tutorial, or the repositories it links to. At some point, forks have added this lib and you need to ask them why the build is disabled for win32 and if it's possible to obtain the source and build it yourself.

**Comment by JadeMoney** [comment]
Turns out devs like to remove the share, contrib, and doc folders from repos and this created the boost errors.

I'm still struggling with the lsecp256k1 issue.
