### ISSUE TITLE
Download failed or wrong checksum of package nettle!

### ISSUE THREAD

**Issue by Dracoctix** [mxe/mxe#1955]
When I attempt to execute the command `make qtbase` under this repository, there is a problem with package nettle.

The make program cannot verify the checksum of the downloaded package, but his checksum is not correct. There is a log file, for this download : https://gist.github.com/Dracoctix/61cc87e3c667b019b5a73cbe805a5bed

I'm on ArchLinux

**Comment by tonytheodore** [comment]
Strange, it seems the site is up, the only difference I see in the log is that `--user-agent` is empty. Can you try:
```
make download-only-nettle nettle_URL=foo
```
to force a download from backup mirror?

**Comment by Dracoctix** [comment]
I tried this, and it seems to work, nettle was downloaded and built :)
