### ISSUE TITLE
Failed to build package qtbase : qmake configurations files don't exist

### ISSUE THREAD

**Issue by dracoctix** [mxe/mxe#1956]
Hello ! 
I attempt to build mxe, on my ArchLinux computer, by using the command `mxe qtbase`, in order to compile Qt5 projects.
However, when it was time to build the qtbase package, there is an error. In the repository folder, the file with the path `mkspecs/qmake.conf` doesn't exists, so the build fails. I tried to download another time the package, but with the same problem. 

There is the build log : https://gist.github.com/Dracoctix/60d003a044313e9364b2980d2bbf0f65

Thanks by advance :)

**Comment by tonytheodore** [comment]
There's nothing obvious in the log, what happens if you manually unpack the tarball (unpatched) and run configure?

**Comment by tonytheodore** [comment]
Okay, I can see a similar error if I build in a directory with `Téléchargement`. I tried both perl5.26 and perl5.18, building out-of-source doesn't help.

Can you try `make qtbase MXE_TMP=~/Downloads/mxe`.

**Comment by tonytheodore** [comment]
Appears it can't be fixed:
>Oswald Buddenhagen added a comment - 04 Apr '14 7:31 PM
we can't change this before qt6 any more, and there won't be a qmake in qt6.

https://bugreports.qt.io/browse/QTBUG-27896?focusedCommentId=239383&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-239383

**Comment by Beirdo** [comment]
So what is the workaround here?  I am now seeing a similar issue.

**Comment by tonytheodore** [comment]
The only certain workaround I can see is to build in a directory with only latin1 characters. I just tried with lots of LC_ALL and LANG settings, but nothing seems to work. If:

```
echo `pwd` | iconv -f UTF-8 -t LATIN1
```
returns odd characters, then `qmake` isn't going to work.
