### ISSUE TITLE
Failed to build package glib for target x86_64-pc-linux-gnu!

### ISSUE THREAD

**Issue by Neyromancer** [mxe/mxe#1959]
Hi, have the same problem. Checked the #PATH but don't have "..." in it.
$gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

$uname -a:
Linux dmitry 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

$env:
XDG_VTNR=7
LC_PAPER=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
XDG_SESSION_ID=c1
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/dmitry
CLUTTER_IM_MODULE=xim
LC_MONETARY=ru_RU.UTF-8
GPG_AGENT_INFO=/home/dmitry/.gnupg/S.gpg-agent:0:1
TERM=screen
SHELL=/bin/bash
VTE_VERSION=4205
DERBY_HOME=/usr/lib/jvm/java-8-oracle/db
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
LC_NUMERIC=ru_RU.UTF-8
WINDOWID=52428810
OLDPWD=/home/dmitry/dmitry/program/mxe
GNOME_KEYRING_CONTROL=
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1108
GTK_MODULES=gail:atk-bridge:unity-gtk-module
USER=dmitry
LC_TELEPHONE=ru_RU.UTF-8
QT_ACCESSIBILITY=1
LS_COLORS=di=1;36:fi=0
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
TMUX=/tmp/tmux-1000/default,2121,0
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/j
ava-8-oracle/jre/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
DESKTOP_SESSION=ubuntu
QT_QPA_PLATFORMTHEME=appmenu-qt5
QT_IM_MODULE=ibus
EVENT_NOEPOLL=1
LC_IDENTIFICATION=ru_RU.UTF-8
XDG_SESSION_TYPE=x11
JOB=gnome-session

**Comment by tonytheodore** [comment]
Can you link to the full log on gist?

**Comment by Neyromancer** [comment]
What log to link? I have a few directories in a log dir:
20171103_095711
20171103_102741
20171103_102853
20171103_103623
20171103_103843
20171103_104125
20171103_104419
20171103_112558
20171103_114158
20171103_114226
20171103_114320

**Comment by tonytheodore** [comment]
Just the one that failed, there should be a symlink to the most recent in `log/glib_x86_64-pc-linux-gnu` otherwise it should be in `log/20171103_114320/glib_x86_64-pc-linux-gnu`. 

I'm typing those but error message will print the actual log file.

**Comment by tonytheodore** [comment]
What the log won't tell me is why you had to invoke `make` so many times...

**Comment by joede** [comment]
I have the same problem building MXE after todays pull. Here is what I've done:

~~~~
cd /usr/lib/mxe
git pull
make clean
make EXCLUDE_PKGS='ocaml% jack sox ucl teem rucksack suitesparse t4k_common vcdimager libdvd% speex% rubberband vamp-% hdf-% hdf4 hdf5 pcl vtk vtk6'
~~~~

And here is the log of the `glib` build: https://gist.github.com/joede/3503d2ed49f2f7884557f20d9d9720db

**Comment by tonytheodore** [comment]
Can you try:
```
make pkgconf MXE_TARGETS= && make glib MXE_TARGETS=
```

**Comment by joede** [comment]
This works. So should I build `pkgconfig` with my targets first?

**Comment by tonytheodore** [comment]
> So should I build pkgconfig with my targets first?

No, #1971 should fix it - can you confirm after a `make clean`?

As an aside, `make EXCLUDE_PKGS=...` will likely build a lot of things you don't need - you might be better off just building an explicit list of packages.

**Comment by joede** [comment]
OK, it is running so far...

~~~~
$ git pull
Already up-to-date.
$ make clean
rm -rf /usr/lib/mxe/tmp-* /usr/lib/mxe/usr \
       ./*-*.list ./mxe-*.tar.xz ./mxe-*.deb* ./wheezy ./jessie
$ make MXE_TARGETS='i686-w64-mingw32.static x86_64-w64-mingw32.static i686-w64-mingw32.shared x86_64-w64-mingw32.shared' EXCLUDE_PKGS='ocaml% jack sox ucl teem rucksack suitesparse t4k_common vcdimager libdvd% speex% rubberband vamp-% hdf-% hdf4 hdf5 pcl vtk vtk6'
[check requirements]
[build nonetwork lib]
[git-log]   a1523ae Update packages.json & build-matrix.html
[build]     cmake-conf             x86_64-pc-linux-gnu
[done]      cmake-conf             x86_64-pc-linux-gnu                                    12 KiB         0m10.351s
[build]     mxe-conf               x86_64-pc-linux-gnu
[done]      mxe-conf               x86_64-pc-linux-gnu                                    328 KiB        0m12.483s
[build]     m4                     x86_64-pc-linux-gnu
[done]      m4                     x86_64-pc-linux-gnu                                    18152 KiB      0m32.822s
[build]     autoconf               x86_64-pc-linux-gnu
[done]      autoconf               x86_64-pc-linux-gnu                                    8280 KiB       0m13.214s
[build]     automake               x86_64-pc-linux-gnu
[done]      automake               x86_64-pc-linux-gnu                                    12560 KiB      0m12.890s
[build]     cmake                  x86_64-pc-linux-gnu
...
~~~~

The option @EXCLUDE_PKGS=@ is much easier to do. As long as the build is shorter than without, I will avoid parsing all the packages to a get a list of interesting stuff. ;-)

**Comment by tonytheodore** [comment]
> [git-log]   a1523ae Update packages.json & build-matrix.html

You need to pull the PR, i.e:
```
git checkout -b tonytheodore-autotools master
git pull https://github.com/tonytheodore/mxe.git autotools
```

**Comment by joede** [comment]
OK, after this pull the build with my configuration has build glib without errors. Thanks.

I think I can switch back to "master" after the pull request is integrated?

Does this work without a full rebuild? Or will the change to glib force this?
