### ISSUE TITLE
SDL2: SDL_opengl.h declares extension prototypes even without -DGL_GLEXT_PROTOTYPES

### ISSUE THREAD

**Issue by charlemagnelasse** [mxe/mxe#1961]
@richard42 and @rcgordon should be interested in the discussion.

I've tried to compile mupen64plus against MXE and found following problem with SDL2 in MXE:

 * https://travis-ci.org/charlemagnelasse/mupen64plus-video-glide64/jobs/297566071
 * https://travis-ci.org/charlemagnelasse/mupen64plus-video-glide64/jobs/297566072
 * https://travis-ci.org/charlemagnelasse/mupen64plus-video-rice/jobs/297566188
 * https://travis-ci.org/charlemagnelasse/mupen64plus-video-rice/jobs/297566189

Problem is that SDL_opengl.h is declaring prototypes even when GL_GLEXT_PROTOTYPES is not set. And when you set GL_GLEXT_PROTOTYPES then it declares it twice (one time in SDL_opengl.h and one time in SDL_opengl_glext.h):

    i686-w64-mingw32.shared-g++ -fvisibility-inlines-hidden -std=gnu++0x -O3 -flto -Wall -Wno-unused-function -ffast-math -fno-strict-aliasing -fvisibility=hidden -I../../src -I../../src/Glitch64/inc -DGCC -mmmx -msse -fno-PIC -I/usr/lib/mxe/usr/i686-w64-mingw32.shared/include   -I/usr/lib/mxe/usr/i686-w64-mingw32.shared/include/libpng16    -I/usr/lib/mxe/usr/i686-w64-mingw32.shared/include/SDL2 -Dmain=SDL_main -DGL_GLEXT_PROTOTYPES "-I/home/travis/build/charlemagnelasse/mupen64plus-video-glide64mk2/deps/mupen64plus-core/src/api/" -MD -MP -DNO_FILTER_THREAD -DTEXTURE_FILTER -DDUMP_CACHE  -c -o _obj/Glitch64/OGLgeometry.o ../../src/Glitch64/OGLgeometry.cpp
    In file included from ../../src/Glitch64/OGLcombiner.cpp:30:0:
    ../../src/Glitch64/glitchmain.h:77:38: error: 'void (__attribute__((__stdcall__)) * glActiveTextureARB)(GLenum)' redeclared as different kind of symbol
         extern PFNGLACTIVETEXTUREARBPROC glActiveTextureARB;
                                          ^
    In file included from ../../src/Glitch64/glitchmain.h:76:0,
                     from ../../src/Glitch64/OGLcombiner.cpp:30:
    /usr/lib/mxe/usr/i686-w64-mingw32.shared/include/SDL2/SDL_opengl.h:2019:23: note: previous declaration 'void glActiveTextureARB(GLenum)'
     GLAPI void GLAPIENTRY glActiveTextureARB(GLenum texture);
                           ^
    In file included from ../../src/Glitch64/OGLcombiner.cpp:30:0:
    ../../src/Glitch64/glitchmain.h:78:37: error: 'void (__attribute__((__stdcall__)) * glAttachObjectARB)(GLhandleARB, GLhandleARB)' redeclared as different kind of symbol
         extern PFNGLATTACHOBJECTARBPROC glAttachObjectARB;
                                         ^
    In file included from /usr/lib/mxe/usr/i686-w64-mingw32.shared/include/SDL2/SDL_opengl.h:2098:0,
                     from ../../src/Glitch64/glitchmain.h:76,
                     from ../../src/Glitch64/OGLcombiner.cpp:30:
    /usr/lib/mxe/usr/i686-w64-mingw32.shared/include/SDL2/SDL_opengl_glext.h:3659:21: note: previous declaration 'void glAttachObjectARB(GLhandleARB, GLhandleARB)'
     GLAPI void APIENTRY glAttachObjectARB (GLhandleARB containerObj, GLhandleARB obj);
                         ^
    In file included from ../../src/Glitch64/OGLcombiner.cpp:30:0:
    ../../src/Glitch64/glitchmain.h:79:40: error: 'void (__attribute__((__stdcall__)) * glBindFramebufferEXT)(GLenum, GLuint)' redeclared as different kind of symbol
         extern PFNGLBINDFRAMEBUFFEREXTPROC glBindFramebufferEXT;

The commit introducing this problem is http://hg.libsdl.org/SDL/file/c94127dcbe97/include/SDL_opengl.h and this commit should definitely be reverted.

When can we expect that the fix is available in http://pkg.mxe.cc/repos/apt/debian/ ?

**Comment by charlemagnelasse** [comment]
I think, @slouken could also be interested because he is mentioned as copyright holder in SDL_opengl.h.

**Comment by tonytheodore** [comment]
> declares it twice (one time in SDL_opengl.h and one time in SDL_opengl_glext.h)

What happens if you define `NO_SDL_GLEXT`:
http://hg.libsdl.org/SDL/file/c94127dcbe97/include/SDL_opengl.h#l2097

**Comment by charlemagnelasse** [comment]
@slouken @tonytheodore 

Already tried that but then even more stuff is undefined (tested with both "-DNO_SDL_GLEXT" and "-DNO_SDL_GLEXT -DGL_GLEXT_PROTOTYPES"):

    /usr/lib/mxe/usr/i686-w64-mingw32.shared/include/SDL2/SDL_opengl.h:2031:23: note: previous declaration 'void glMultiTexCoord2fARB(GLenum, GLfloat, GLfloat)'
     GLAPI void GLAPIENTRY glMultiTexCoord2fARB(GLenum target, GLfloat s, GLfloat t);
                           ^
    In file included from ../../src/Glitch64/OGLgeometry.cpp:26:0:
    ../../src/Glitch64/glitchmain.h:98:12: error: 'PFNGLRENDERBUFFERSTORAGEEXTPROC' does not name a type
         extern PFNGLRENDERBUFFERSTORAGEEXTPROC glRenderbufferStorageEXT;
                ^
    ../../src/Glitch64/glitchmain.h:99:12: error: 'PFNGLSECONDARYCOLOR3FPROC' does not name a type
         extern PFNGLSECONDARYCOLOR3FPROC glSecondaryColor3f;
                ^
    ../../src/Glitch64/glitchmain.h:100:12: error: 'PFNGLSHADERSOURCEARBPROC' does not name a type
         extern PFNGLSHADERSOURCEARBPROC glShaderSourceARB;
                ^
    ../../src/Glitch64/glitchmain.h:101:12: error: 'PFNGLUNIFORM1FARBPROC' does not name a type
         extern PFNGLUNIFORM1FARBPROC glUniform1fARB;
                ^
    ../../src/Glitch64/glitchmain.h:102:12: error: 'PFNGLUNIFORM1IARBPROC' does not name a type
         extern PFNGLUNIFORM1IARBPROC glUniform1iARB;
                ^
    ../../src/Glitch64/glitchmain.h:103:12: error: 'PFNGLUNIFORM4FARBPROC' does not name a type
         extern PFNGLUNIFORM4FARBPROC glUniform4fARB;
                ^
    ../../src/Glitch64/glitchmain.h:104:12: error: 'PFNGLUSEPROGRAMOBJECTARBPROC' does not name a type
         extern PFNGLUSEPROGRAMOBJECTARBPROC glUseProgramObjectARB;
                ^
    ../../src/Glitch64/glitchmain.h:105:12: error: 'PFNGLGETHANDLEARBPROC' does not name a type
         extern PFNGLGETHANDLEARBPROC glGetHandleARB;
                ^
    ../../src/Glitch64/glitchmain.h:140:34: error: 'void (__attribute__((__stdcall__)) * glActiveTextureARB)(GLenum)' redeclared as different kind of symbol
     extern PFNGLACTIVETEXTUREARBPROC glActiveTextureARB;
                                      ^
    In file included from ../../src/Glitch64/glitchmain.h:76:0,
                     from ../../src/Glitch64/OGLgeometry.cpp:26:
    /usr/lib/mxe/usr/i686-w64-mingw32.shared/include/SDL2/SDL_opengl.h:2019:23: note: previous declaration 'void glActiveTextureARB(GLenum)'
     GLAPI void GLAPIENTRY glActiveTextureARB(GLenum texture);
                           ^
    In file included from ../../src/Glitch64/OGLgeometry.cpp:26:0:
    ../../src/Glitch64/glitchmain.h:141:36: error: 'void (__attribute__((__stdcall__)) * glMultiTexCoord2fARB)(GLenum, GLfloat, GLfloat)' redeclared as different kind of symbol
     extern PFNGLMULTITEXCOORD2FARBPROC glMultiTexCoord2fARB;
                                        ^
    In file included from ../../src/Glitch64/glitchmain.h:76:0,
                     from ../../src/Glitch64/OGLgeometry.cpp:26:
    /usr/lib/mxe/usr/i686-w64-mingw32.shared/include/SDL2/SDL_opengl.h:2031:23: note: previous declaration 'void glMultiTexCoord2fARB(GLenum, GLfloat, GLfloat)'
     GLAPI void GLAPIENTRY glMultiTexCoord2fARB(GLenum target, GLfloat s, GLfloat t);
                           ^
    In file included from ../../src/Glitch64/OGLgeometry.cpp:26:0:
    ../../src/Glitch64/glitchmain.h:142:8: error: 'PFNGLBLENDFUNCSEPARATEEXTPROC' does not name a type
     extern PFNGLBLENDFUNCSEPARATEEXTPROC glBlendFuncSeparateEXT;
            ^
    ../../src/Glitch64/glitchmain.h:143:8: error: 'PFNGLFOGCOORDFPROC' does not name a type
     extern PFNGLFOGCOORDFPROC glFogCoordfEXT;
            ^
    ../../src/Glitch64/glitchmain.h:145:8: error: 'PFNGLCREATESHADEROBJECTARBPROC' does not name a type
     extern PFNGLCREATESHADEROBJECTARBPROC glCreateShaderObjectARB;
            ^
    ../../src/Glitch64/glitchmain.h:146:8: error: 'PFNGLSHADERSOURCEARBPROC' does not name a type
     extern PFNGLSHADERSOURCEARBPROC glShaderSourceARB;
            ^
    ../../src/Glitch64/glitchmain.h:147:8: error: 'PFNGLCOMPILESHADERARBPROC' does not name a type
     extern PFNGLCOMPILESHADERARBPROC glCompileShaderARB;
            ^
    ../../src/Glitch64/glitchmain.h:148:8: error: 'PFNGLCREATEPROGRAMOBJECTARBPROC' does not name a type
     extern PFNGLCREATEPROGRAMOBJECTARBPROC glCreateProgramObjectARB;
            ^
    ../../src/Glitch64/glitchmain.h:149:8: error: 'PFNGLATTACHOBJECTARBPROC' does not name a type
     extern PFNGLATTACHOBJECTARBPROC glAttachObjectARB;
            ^
    ../../src/Glitch64/glitchmain.h:150:8: error: 'PFNGLLINKPROGRAMARBPROC' does not name a type
     extern PFNGLLINKPROGRAMARBPROC glLinkProgramARB;
            ^
    ../../src/Glitch64/glitchmain.h:151:8: error: 'PFNGLUSEPROGRAMOBJECTARBPROC' does not name a type
     extern PFNGLUSEPROGRAMOBJECTARBPROC glUseProgramObjectARB;
            ^
    ../../src/Glitch64/glitchmain.h:152:8: error: 'PFNGLGETHANDLEARBPROC' does not name a type
     extern PFNGLGETHANDLEARBPROC glGetHandleARB;
            ^
    ../../src/Glitch64/glitchmain.h:153:8: error: 'PFNGLGETUNIFORMLOCATIONARBPROC' does not name a type
     extern PFNGLGETUNIFORMLOCATIONARBPROC glGetUniformLocationARB;
            ^
    ../../src/Glitch64/glitchmain.h:154:8: error: 'PFNGLUNIFORM1IARBPROC' does not name a type
     extern PFNGLUNIFORM1IARBPROC glUniform1iARB;
            ^
    ../../src/Glitch64/glitchmain.h:155:8: error: 'PFNGLUNIFORM4IARBPROC' does not name a type
     extern PFNGLUNIFORM4IARBPROC glUniform4iARB;
            ^
    ../../src/Glitch64/glitchmain.h:156:8: error: 'PFNGLUNIFORM4FARBPROC' does not name a type
     extern PFNGLUNIFORM4FARBPROC glUniform4fARB;
            ^
    ../../src/Glitch64/glitchmain.h:157:8: error: 'PFNGLUNIFORM1FARBPROC' does not name a type
     extern PFNGLUNIFORM1FARBPROC glUniform1fARB;
            ^
    ../../src/Glitch64/glitchmain.h:158:8: error: 'PFNGLDELETEOBJECTARBPROC' does not name a type
     extern PFNGLDELETEOBJECTARBPROC glDeleteObjectARB;
            ^
    ../../src/Glitch64/glitchmain.h:159:8: error: 'PFNGLGETINFOLOGARBPROC' does not name a type
     extern PFNGLGETINFOLOGARBPROC glGetInfoLogARB;
            ^
    ../../src/Glitch64/glitchmain.h:160:8: error: 'PFNGLGETOBJECTPARAMETERIVARBPROC' does not name a type
     extern PFNGLGETOBJECTPARAMETERIVARBPROC glGetObjectParameterivARB;
            ^
    ../../src/Glitch64/glitchmain.h:161:8: error: 'PFNGLSECONDARYCOLOR3FPROC' does not name a type
     extern PFNGLSECONDARYCOLOR3FPROC glSecondaryColor3f;
            ^
    ../../src/Glitch64/OGLgeometry.cpp: In function 'void grDrawTriangle(const void*, const void*, const void*)':
    ../../src/Glitch64/OGLgeometry.cpp:390:60: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *a_q) / 255.0f, 0.0f, 0.0f);
                                                                ^
    ../../src/Glitch64/OGLgeometry.cpp:392:62: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *a_fog) / 255.0f, 0.0f, 0.0f);
                                                                  ^
    ../../src/Glitch64/OGLgeometry.cpp:417:60: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *b_q) / 255.0f, 0.0f, 0.0f);
                                                                ^
    ../../src/Glitch64/OGLgeometry.cpp:419:62: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *b_fog) / 255.0f, 0.0f, 0.0f);
                                                                  ^
    ../../src/Glitch64/OGLgeometry.cpp:445:60: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *c_q) / 255.0f, 0.0f, 0.0f);
                                                                ^
    ../../src/Glitch64/OGLgeometry.cpp:447:62: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *c_fog) / 255.0f, 0.0f, 0.0f);
                                                                  ^
    ../../src/Glitch64/OGLgeometry.cpp: In function 'void grDrawPoint(const void*)':
    ../../src/Glitch64/OGLgeometry.cpp:502:58: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *q) / 255.0f, 0.0f, 0.0f);
                                                              ^
    ../../src/Glitch64/OGLgeometry.cpp:504:60: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *fog) / 255.0f, 0.0f, 0.0f);
                                                                ^
    ../../src/Glitch64/OGLgeometry.cpp: In function 'void grDrawLine(const void*, const void*)':
    ../../src/Glitch64/OGLgeometry.cpp:567:60: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *a_q) / 255.0f, 0.0f, 0.0f);
                                                                ^
    ../../src/Glitch64/OGLgeometry.cpp:569:62: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *a_fog) / 255.0f, 0.0f, 0.0f);
                                                                  ^
    ../../src/Glitch64/OGLgeometry.cpp:594:60: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *b_q) / 255.0f, 0.0f, 0.0f);
                                                                ^
    ../../src/Glitch64/OGLgeometry.cpp:596:62: error: 'glSecondaryColor3f' was not declared in this scope
           glSecondaryColor3f((1.0f / *b_fog) / 255.0f, 0.0f, 0.0f);
                                                                  ^
    ../../src/Glitch64/OGLgeometry.cpp: In function 'void grDrawVertexArray(FxU32, FxU32, void*)':
    ../../src/Glitch64/OGLgeometry.cpp:665:60: error: 'glSecondaryColor3f' was not declared in this scope
             glSecondaryColor3f((1.0f / *q) / 255.0f, 0.0f, 0.0f);
                                                                ^
    ../../src/Glitch64/OGLgeometry.cpp:667:62: error: 'glSecondaryColor3f' was not declared in this scope
             glSecondaryColor3f((1.0f / *fog) / 255.0f, 0.0f, 0.0f);
                                                                  ^
    ../../src/Glitch64/OGLgeometry.cpp: In function 'void grDrawVertexArrayContiguous(FxU32, FxU32, void*, FxU32)':
    ../../src/Glitch64/OGLgeometry.cpp:740:60: error: 'glSecondaryColor3f' was not declared in this scope
             glSecondaryColor3f((1.0f / *q) / 255.0f, 0.0f, 0.0f);
                                                                ^
    ../../src/Glitch64/OGLgeometry.cpp:742:62: error: 'glSecondaryColor3f' was not declared in this scope
             glSecondaryColor3f((1.0f / *fog) / 255.0f, 0.0f, 0.0f);

**Comment by charlemagnelasse** [comment]
The instruction to build it can be found in:

* https://github.com/charlemagnelasse/mupen64plus-video-glide64/blob/travis-mxe/.travis.yml#L25
* https://github.com/charlemagnelasse/mupen64plus-video-rice/blob/travis-mxe/.travis.yml#L26

And it worked fine before @rcgordon added this change to SDL2. But it works fine again when reverting the change using a simple patch in MXE.

**Comment by tonytheodore** [comment]
Can you do a PR for the patch?

**Comment by charlemagnelasse** [comment]
Yes, will do that. But I don't know how to generate mailbox format patches with mercurial. I hope a "# HG changeset patch" will also be ok in the MXE tree

**Comment by charlemagnelasse** [comment]
When is the next debian package snapshot planned? I would really like to get the travis build test enabled for mupen64plus-video-glide64 and mupen64plus-video-rice

**Comment by tonytheodore** [comment]
Next build is soon, see #2021.
