### ISSUE TITLE
Build escapes cmake wrapper, using headers from /usr/include

### ISSUE THREAD

**Issue by Stefan-Olt** [mxe/mxe#1964]
I try to cross-compile GNU Radio, after fixing the first problem (https://github.com/mxe/mxe/issues/1962) I came to this problem:
`In file included from /usr/include/string.h:25:0,
                 from /home/stefan/gnuradio/gr-fec/lib/reed-solomon/encode_rs.c:5:
/usr/include/features.h:391:23: fatal error: gnu/stubs.h: No such file or directory
compilation terminated.`
First I thought /usr/include is sandboxing, but no, it is using /usr/include/string.h
I replaced `<string.h>` in the file with `"/home/stefan/mxe/usr/i686-w64-mingw32.static/include/string.h"`, but then same problem:
`In file included from /usr/include/string.h:25:0,
                 from /home/stefan/mxe/usr/i686-w64-mingw32.static/include/sec_api/string_s.h:9,
                 from /home/stefan/mxe/usr/i686-w64-mingw32.static/include/string.h:190,
                 from /home/stefan/gnuradio/gr-fec/lib/reed-solomon/encode_rs.c:5:
/usr/include/features.h:391:23: fatal error: gnu/stubs.h: No such file or directory
compilation terminated.`

I thought `/usr/include` is always replaced by `/path/to/mxe/usr/i686-w64-mingw32.static/include/`, why does it start using headers from the systems include directory?

**Comment by tonytheodore** [comment]
I suspect it is picking up some `*-config` script from the host system, possibly `pkg-config` with the same issue as https://github.com/mxe/mxe/issues/1023.

Can you check the build log and cmake cache files to see if there's anything suspicious? If it's `pkg-config`, can you try:
```diff
diff --git a/src/pkgconf.mk b/src/pkgconf.mk
index 409e0201..ab8b6ce1 100644
--- a/src/pkgconf.mk
+++ b/src/pkgconf.mk
@@ -32,7 +32,7 @@ define $(PKG)_BUILD
     chmod 0755 '$(PREFIX)/bin/$(TARGET)-pkg-config'

     # create cmake file
-    echo 'set(PKG_CONFIG_EXECUTABLE $(PREFIX)/bin/$(TARGET)-pkg-config CACHE PATH "pkg-config executable")' \
+    echo 'set(PKG_CONFIG_EXECUTABLE $(PREFIX)/bin/$(TARGET)-pkg-config CACHE PATH "pkg-config executable" FORCE)' \
     > '$(CMAKE_TOOLCHAIN_DIR)/pkgconf.cmake'

 endef
```

**Comment by Stefan-Olt** [comment]
The only references to something outside the source path and mxe are /usr/bin/lsb_release, /usr/bin/swig3.0, /usr/bin/qmake-qt4 and /usr/bin/python
I was able to compile and link everything with a trick: I renamed /usr/include and made a bind mount of the mxe-i686 include folder to /usr/include.
Unfortunately the result does not work. In Windows the application hangs during startup at 100% load at one core.

**Comment by tonytheodore** [comment]
Can you make a gist of the cmake cache files? The python/swig will not work with MXE and should be disabled, the qmake/lrelease should be configured to use MXE versions.
