### ISSUE TITLE
Docs: what is the best way to mix Qt 5.7.1, Qt 5.9.2 environment in the same mxe folder?

### ISSUE THREAD

**Issue by scorpio810** [mxe/mxe#1980]
Hi, 
at this time I use two separate mxe folders and in my package script  I replace mxe folders name for Win Xp Vista builds or Windows 10 builds :
https://qelectrotech.org/wiki_new/doc/packaging_debian#packaging_script
For Qt 5.7.1 win Xp I use :
`make --jobs=16 MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static' MXE_PLUGIN_DIRS=plugins/examples/qt5-freeze gcc glib libzip libusb1 libftdi1 glibmm boost check qt5 qtbase_CONFIGURE_OPTS='-no-sql-mysql'`

For other Windows builds in other mxe folder : 
`make --jobs=16 MXE_PLUGIN_DIRS=plugins/gcc7 MXE_TARGETS='x86_64-w64-mingw32.static.posix i686-w64-mingw32.static.posix' gcc`and
`make --jobs=16 MXE_TARGETS='x86_64-w64-mingw32.static.posix i686-w64-mingw32.static.posix' qt5`

Is there a better method ?

**Comment by tonytheodore** [comment]
There's no realistic way to mix downstream libraries from different versions of gcc even though gcc itself can have multiple installs. The complexity of managing the separation far outweighs the extra build time of different top level folders.

I would have thought gcc7 still supports WinXp - it's more mingw-w64 options and downstream libs that don't, so theoretically you could use the same gcc version for both. Likewise `*.posix` is largely internal to gcc so it should be fine.

Qt (and anything built with qmake) may be possible since it already installs to it's own versioned prefix. Something like:
```diff
diff --git a/plugins/examples/qt5-freeze/qtbase.mk b/plugins/examples/qt5-freeze/qtbase.mk
index 55455800..aa996b7a 100644
--- a/plugins/examples/qt5-freeze/qtbase.mk
+++ b/plugins/examples/qt5-freeze/qtbase.mk
@@ -37,7 +37,7 @@ define $(PKG)_BUILD
             -no-use-gold-linker \
             -release \
             -static \
-            -prefix '$(PREFIX)/$(TARGET)/qt5' \
+            -prefix '$(PREFIX)/$(TARGET)/qt5.7' \
             -no-icu \
             -opengl desktop \
             -no-glib \
```

```
# WinXp
make --jobs=16 \
    qt5 libzip libusb1 libftdi1 glibmm boost check \
    MXE_TARGETS='x86_64-w64-mingw32.static.posix i686-w64-mingw32.static.posix' \
    MXE_PLUGIN_DIRS='plugins/gcc7 plugins/examples/qt5-freeze' \
    qtbase_CONFIGURE_OPTS='-no-sql-mysql'

touch src/qtbase.mk

# Other - will only build qtbase and downstream
make --jobs=16 \
    qt5  \
    MXE_TARGETS='x86_64-w64-mingw32.static.posix i686-w64-mingw32.static.posix' \
    MXE_PLUGIN_DIRS='plugins/gcc7'
```

then use the respective full path `/prefix/target/qt5[.7]/bin/qmake` instead of `target-qmake`. If it works, you can loop over the targets and add `qtbase_CONFIGURE_OPTS='-no-sql-mysql -prefix ...'
to the WinXp build.

**Comment by tonytheodore** [comment]
Actually, there's also an `rm` that needs to be changed but the general idea should work:
```diff
@@ -65,7 +65,7 @@ define $(PKG)_BUILD
             $($(PKG)_CONFIGURE_OPTS)

     $(MAKE) -C '$(1)' -j '$(JOBS)'
-    rm -rf '$(PREFIX)/$(TARGET)/qt5'
+    rm -rf '$(PREFIX)/$(TARGET)/qt5.7'
     $(MAKE) -C '$(1)' -j 1 install
     ln -sf '$(PREFIX)/$(TARGET)/qt5/bin/qmake' '$(PREFIX)/bin/$(TARGET)'-qmake-qt5
```

**Comment by tonytheodore** [comment]
... and the other references to `'$(PREFIX)/$(TARGET)/qt5'`

**Comment by scorpio810** [comment]
Thanks for informations, I will try it soon.

**Comment by scorpio810** [comment]
```
[build]     qtbase                   x86_64-w64-mingw32.static.posix

Failed to build package qtbase for target i686-w64-mingw32.static.posix!
------------------------------------------------------------
mkdir            '/home/laurent/mxe/tmp-qtbase-i686-w64-mingw32.static.posix/qtbase-opensource-src-5.7.1/test-qt'
cd               '/home/laurent/mxe/tmp-qtbase-i686-w64-mingw32.static.posix/qtbase-opensource-src-5.7.1/test-qt' && '/home/laurent/mxe/usr/i686-w64-mingw32.static.posix/qt5/bin/qmake' '/home/laurent/mxe/src/qt-test.pro'
bash: /home/laurent/mxe/usr/i686-w64-mingw32.static.posix/qt5/bin/qmake: Aucun fichier ou dossier de ce type
Makefile:687 : la recette pour la cible « build-only-qtbase_i686-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtbase_i686-w64-mingw32.static.posix] Erreur 127
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    9m43,926s
user    39m11,638s
sys     2m53,944s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtbase_i686-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtbase » a échouée
make: *** [/home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtbase] Erreur 1
make: *** Attente des tâches non terminées....

Failed to build package qtbase for target x86_64-w64-mingw32.static.posix!
------------------------------------------------------------
mkdir            '/home/laurent/mxe/tmp-qtbase-x86_64-w64-mingw32.static.posix/qtbase-opensource-src-5.7.1/test-qt'
cd               '/home/laurent/mxe/tmp-qtbase-x86_64-w64-mingw32.static.posix/qtbase-opensource-src-5.7.1/test-qt' && '/home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/qt5/bin/qmake' '/home/laurent/mxe/src/qt-test.pro'
bash: /home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/qt5/bin/qmake: Aucun fichier ou dossier de ce type
Makefile:687 : la recette pour la cible « build-only-qtbase_x86_64-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtbase_x86_64-w64-mingw32.static.posix] Erreur 127
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    10m2,529s
user    41m13,336s
sys     2m48,336s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtbase_x86_64-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/installed/qtbase » a échouée
make: *** [/home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/installed/qtbase] Erreur 1
```
I only change plugins/examples/qt5-freeze/qtbase.mk b/plugins/examples/qt5-freeze/qtbase.mk file
-prefix '$(PREFIX)/$(TARGET)/qt5.7' \
rm -rf '$(PREFIX)/$(TARGET)/qt5.7'


I would see at it when I have a little more free time
Thanks

**Comment by scorpio810** [comment]
```
diff --git a/plugins/examples/qt5-freeze/qtbase.mk b/plugins/examples/qt5-freeze/qtbase.mk
index 55455800..7c080a9f 100644
--- a/plugins/examples/qt5-freeze/qtbase.mk
+++ b/plugins/examples/qt5-freeze/qtbase.mk
@@ -37,7 +37,7 @@ define $(PKG)_BUILD
             -no-use-gold-linker \
             -release \
             -static \
-            -prefix '$(PREFIX)/$(TARGET)/qt5' \
+            -prefix '$(PREFIX)/$(TARGET)/qt5.7' \
             -no-icu \
             -opengl desktop \
             -no-glib \
@@ -65,23 +65,23 @@ define $(PKG)_BUILD
             $($(PKG)_CONFIGURE_OPTS)
 
     $(MAKE) -C '$(1)' -j '$(JOBS)'
-    rm -rf '$(PREFIX)/$(TARGET)/qt5'
+    rm -rf '$(PREFIX)/$(TARGET)/qt5.7.7'
     $(MAKE) -C '$(1)' -j 1 install
-    ln -sf '$(PREFIX)/$(TARGET)/qt5/bin/qmake' '$(PREFIX)/bin/$(TARGET)'-qmake-qt5
+    ln -sf '$(PREFIX)/$(TARGET)/qt5.7/bin/qmake' '$(PREFIX)/bin/$(TARGET)'-qmake-qt5
 
     mkdir            '$(1)/test-qt'
-    cd               '$(1)/test-qt' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' '$(PWD)/src/qt-test.pro'                                                                                                                                                                          
+    cd               '$(1)/test-qt' && '$(PREFIX)/$(TARGET)/qt5.7/bin/qmake' '$(PWD)/src/qt-test.pro'                                                                                                                                                                        
     $(MAKE)       -C '$(1)/test-qt' -j '$(JOBS)' $(BUILD_TYPE)                                                                                                                                                                                                               
     $(INSTALL) -m755 '$(1)/test-qt/$(BUILD_TYPE)/test-qt5.exe' '$(PREFIX)/$(TARGET)/bin/'                                                                                                                                                                                    
                                                                                                                                                                                                                                                                              
     # build test the manual way                                                                                                                                                                                                                                              
     mkdir '$(1)/test-$(PKG)-pkgconfig'                                                                                                                                                                                                                                       
-    '$(PREFIX)/$(TARGET)/qt5/bin/uic' -o '$(1)/test-$(PKG)-pkgconfig/ui_qt-test.h' '$(TOP_DIR)/src/qt-test.ui'
-    '$(PREFIX)/$(TARGET)/qt5/bin/moc' \
+    '$(PREFIX)/$(TARGET)/qt5.7/bin/uic' -o '$(1)/test-$(PKG)-pkgconfig/ui_qt-test.h' '$(TOP_DIR)/src/qt-test.ui'
+    '$(PREFIX)/$(TARGET)/qt5.7/bin/moc' \
         -o '$(1)/test-$(PKG)-pkgconfig/moc_qt-test.cpp' \
         -I'$(1)/test-$(PKG)-pkgconfig' \
         '$(TOP_DIR)/src/qt-test.hpp'
-    '$(PREFIX)/$(TARGET)/qt5/bin/rcc' -name qt-test -o '$(1)/test-$(PKG)-pkgconfig/qrc_qt-test.cpp' '$(TOP_DIR)/src/qt-test.qrc'
+    '$(PREFIX)/$(TARGET)/qt5.7/bin/rcc' -name qt-test -o '$(1)/test-$(PKG)-pkgconfig/qrc_qt-test.cpp' '$(TOP_DIR)/src/qt-test.qrc'
     '$(TARGET)-g++' \
         -W -Wall -Werror -std=c++0x -pedantic \
         '$(TOP_DIR)/src/qt-test.cpp' \


```

**Comment by tonytheodore** [comment]
It takes a little more to make every module aware of the side-by-side install, see #1981 for progress.

**Comment by tonytheodore** [comment]
#1981 looks good to go from my testing - the test program runs on WinXp with 5.7 and fails on the normal build. Can you confirm it works for you?

**Comment by scorpio810** [comment]
[done]      qt3d                     i686-w64-mingw32.static.posix                  112728 KiB     5m44,644s
[no-build]  qt5                      i686-w64-mingw32.static.posix
[14:25:20] laurent@debian:~/mxe$ rm usr/*/installed/qtbase
laurent@debian:~/mxe$ make --jobs=16 \
>     qt5  \
>     MXE_TARGETS='x86_64-w64-mingw32.static.posix i686-w64-mingw32.static.posix' \
>     MXE_PLUGIN_DIRS='plugins/gcc7'
[download]  pcre2
[download]  qtbase
[download]  qtsvg
[download]  qtxmlpatterns
[download]  qtdeclarative
[download]  qt3d
[download]  qtactiveqt
[download]  qtcanvas3d
[download]  qtmultimedia


[build]     qtlocation             x86_64-w64-mingw32.static.posix

Failed to build package qtgamepad for target x86_64-w64-mingw32.static.posix!
------------------------------------------------------------
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make[2]: *** [sub-src-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/laurent/mxe/tmp-qtgamepad-x86_64-w64-mingw32.static.posix/qtgamepad-opensource-src-5.9.2 »
Makefile:687 : la recette pour la cible « build-only-qtgamepad_x86_64-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtgamepad_x86_64-w64-mingw32.static.posix] Erreur 2
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    1m37,643s
user    0m20,853s
sys     0m5,167s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtgamepad_x86_64-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/installed/qtgamepad » a échouée
make: *** [/home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/installed/qtgamepad] Erreur 1
make: *** Attente des tâches non terminées....

Failed to build package qtlocation for target i686-w64-mingw32.static.posix!
------------------------------------------------------------

Failed to build package qtcharts for target i686-w64-mingw32.static.posix!
------------------------------------------------------------
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make[2]: *** [sub-src-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/laurent/mxe/tmp-qtlocation-i686-w64-mingw32.static.posix/qtlocation-opensource-src-5.9.2 »
Makefile:687 : la recette pour la cible « build-only-qtlocation_i686-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtlocation_i686-w64-mingw32.static.posix] Erreur 2
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    3m31,635s
user    2m45,109s
sys     0m16,202s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtlocation_i686-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtlocation » a échouée
make: *** [/home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtlocation] Erreur 1
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make[2]: *** [sub-src-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/laurent/mxe/tmp-qtcharts-i686-w64-mingw32.static.posix/qtcharts-opensource-src-5.9.2 »
Makefile:687 : la recette pour la cible « build-only-qtcharts_i686-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtcharts_i686-w64-mingw32.static.posix] Erreur 2
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    3m31,675s
user    3m31,068s
sys     0m23,874s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtcharts_i686-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtcharts » a échouée
make: *** [/home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtcharts] Erreur 1

Failed to build package qtconnectivity for target x86_64-w64-mingw32.static.posix!
------------------------------------------------------------
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make[2]: *** [sub-src-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/laurent/mxe/tmp-qtconnectivity-x86_64-w64-mingw32.static.posix/qtconnectivity-opensource-src-5.9.2 »
Makefile:687 : la recette pour la cible « build-only-qtconnectivity_x86_64-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtconnectivity_x86_64-w64-mingw32.static.posix] Erreur 2
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    1m43,923s
user    0m33,553s
sys     0m9,320s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtconnectivity_x86_64-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/installed/qtconnectivity » a échouée
make: *** [/home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/installed/qtconnectivity] Erreur 1

Failed to build package qtdatavis3d for target i686-w64-mingw32.static.posix!
------------------------------------------------------------
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make[2]: *** [sub-src-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/laurent/mxe/tmp-qtdatavis3d-i686-w64-mingw32.static.posix/qtdatavis3d-opensource-src-5.9.2 »
Makefile:687 : la recette pour la cible « build-only-qtdatavis3d_i686-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtdatavis3d_i686-w64-mingw32.static.posix] Erreur 2
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    3m36,265s
user    3m47,403s
sys     0m18,546s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtdatavis3d_i686-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtdatavis3d » a échouée
make: *** [/home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtdatavis3d] Erreur 1

Failed to build package qtcharts for target x86_64-w64-mingw32.static.posix!
------------------------------------------------------------
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make[2]: *** [sub-src-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/laurent/mxe/tmp-qtcharts-x86_64-w64-mingw32.static.posix/qtcharts-opensource-src-5.9.2 »
Makefile:687 : la recette pour la cible « build-only-qtcharts_x86_64-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtcharts_x86_64-w64-mingw32.static.posix] Erreur 2
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    1m46,667s
user    0m24,557s
sys     0m8,720s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtcharts_x86_64-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/installed/qtcharts » a échouée
make: *** [/home/laurent/mxe/usr/x86_64-w64-mingw32.static.posix/installed/qtcharts] Erreur 1
[done]      qtgraphicaleffects     x86_64-w64-mingw32.static.posix                  20556 KiB      1m47,095s

Failed to build package qtquickcontrols2 for target i686-w64-mingw32.static.posix!
------------------------------------------------------------
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make[2]: *** [sub-src-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/laurent/mxe/tmp-qtquickcontrols2-i686-w64-mingw32.static.posix/qtquickcontrols2-opensource-src-5.9.2 »
Makefile:687 : la recette pour la cible « build-only-qtquickcontrols2_i686-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtquickcontrols2_i686-w64-mingw32.static.posix] Erreur 2
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    3m39,600s
user    3m54,916s
sys     0m17,930s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtquickcontrols2_i686-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtquickcontrols2 » a échouée
make: *** [/home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtquickcontrols2] Erreur 1

Failed to build package qtquickcontrols for target i686-w64-mingw32.static.posix!
------------------------------------------------------------
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make[2]: *** [sub-src-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/laurent/mxe/tmp-qtquickcontrols-i686-w64-mingw32.static.posix/qtquickcontrols-opensource-src-5.9.2 »
Makefile:687 : la recette pour la cible « build-only-qtquickcontrols_i686-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qtquickcontrols_i686-w64-mingw32.static.posix] Erreur 2
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    3m45,544s
user    4m3,310s
sys     0m21,471s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qtquickcontrols_i686-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtquickcontrols » a échouée
make: *** [/home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qtquickcontrols] Erreur 1
[done]      qtcanvas3d             i686-w64-mingw32.static.posix                    20928 KiB      3m52,837s

Failed to build package qttools for target i686-w64-mingw32.static.posix!
------------------------------------------------------------
Makefile:42 : la recette pour la cible « sub-src-make_first » a échouée
make[2]: *** [sub-src-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/laurent/mxe/tmp-qttools-i686-w64-mingw32.static.posix/qttools-opensource-src-5.9.2 »
Makefile:687 : la recette pour la cible « build-only-qttools_i686-w64-mingw32.static.posix » a échouée
make[1]: *** [build-only-qttools_i686-w64-mingw32.static.posix] Erreur 2
make[1] : on quitte le répertoire « /home/laurent/mxe »
real    4m13,264s
user    5m45,421s
sys     0m23,314s
------------------------------------------------------------
[log]      /home/laurent/mxe/log/qttools_i686-w64-mingw32.static.posix

Makefile:687 : la recette pour la cible « /home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qttools » a échouée
make: *** [/home/laurent/mxe/usr/i686-w64-mingw32.static.posix/installed/qttools] Erreur 1
[done]      qtcanvas3d             x86_64-w64-mingw32.static.posix                  21404 KiB      2m56,374s
[done]      qtdatavis3d            x86_64-w64-mingw32.static.posix                  29132 KiB      4m6,154s
[done]      qtlocation             x86_64-w64-mingw32.static.posix                  93756 KiB      4m27,410s
[done]      qt3d                   x86_64-w64-mingw32.static.posix                  162052 KiB     7m34,089s

**Comment by tonytheodore** [comment]
Can you post a gist of the log for one of the failed packages?

P.S. can you also make sure you quote the terminal output correctly? Just "Preview" before you comment.

**Comment by scorpio810** [comment]
Sorry! I deleted directory and logs .., I try again with your fork.

**Comment by tonytheodore** [comment]
I've merged it now, so just try with the latest master.

Read the [notes](https://github.com/mxe/mxe/blob/master/plugins/examples/qt5-freeze/README.md#side-by-side-install), and make sure you specifically set `qtbase_VERSION_ID` for the "frozen" install.

**Comment by scorpio810** [comment]
Yes, I read the release note, and now I prefer  wait and finish these builds and see if builds are ok.
It's still quite long to builds all environments even with a ryzen 1700X, not money for a Threadripper 1950X now ...

**Comment by scorpio810** [comment]
Builds all cross-environment ok now with latest master, my problem is I think when I build with jobs=16 ok with 8 jobs, thank you.

**Comment by tonytheodore** [comment]
Good to hear.

> my problem is I think when I build with jobs=16

There could be some missing dependencies, you should be able to tell from the failed logs, but in general any number of `--jobs` should work.

**Comment by scorpio810** [comment]
Strangely on the last try when the warnings arrived (only at the end of the compilation of the last environment ) I saw dmesg logs, perhaps a hardware problem or other software problem, strange is a RMAed CPU..

```
 sudo dmesg | tail
[sudo] Mot de passe de laurent : 
[40733.354791] [32373]  1000 32373    12990     2708      28       3        0             0 cc1plus
[40733.354792] [32374]  1000 32374     4002     1124      13       3        0             0 x86_64-w64-ming
[40733.354793] [32375]  1000 32375    13050     2754      28       3        0             0 cc1plus
[40733.354794] [32376]  1000 32376     4002     1124      12       3        0             0 x86_64-w64-ming
[40733.354795] [32378]  1000 32378     2604       25      11       3        0             0 x86_64-w64-ming
[40733.354796] [32381]  1000 32381    11950     2055      25       3        0             0 cc1plus
[40733.354797] [32383]  1000 32383     4002     1125      12       3        0             0 x86_64-w64-ming
[40733.354799] [32385]  1000 32385     2604       30      10       3        0             0 x86_64-w64-ming
[40733.354800] Out of memory: Kill process 10955 (chrome) score 301 or sacrifice child
[40733.354810] Killed process 10955 (chrome) total-vm:1147876kB, anon-rss:29816kB, file-rss:0kB, shmem-rss:2088kB
[17:00:10] laurent@debian:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          16065        3166       11946          97         952       12525
Swap:             0           0           0

```

**Comment by tonytheodore** [comment]
You don't have some low `ulimit` settings?

**Comment by scorpio810** [comment]
None at this time.

**Comment by scorpio810** [comment]
In fact, I think the problem does not come from there but with JOBS=16..
No problem here with make -j4  --jobs=4, and I think make -j8  --jobs=2 seems to be better i my case.
