### ISSUE TITLE
[PATCH] glib build failure when automake version != 1.15

### ISSUE THREAD

**Issue by janvdijk** [mxe/mxe#1986]
I encounter a glib build failure with HEAD on my openSUSE Leap 42.3 box, which has automake 1.13.4 installed. The culprit is that MXE's glibc-patches trigger an invocation of aclocal-1.15, as seen in the log:

/home/jan/local/src/mxe/tmp-glib-x86_64-pc-linux-gnu/glib-2.50.2/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.

That, after all, is the version that was used for the creation of the glib-package.

The problem is solved by calling `autoreconf` in the glib sources before starting the compilation. IMHO that should always be done after patching any of the autotools-files. I implemented this by applying the patch [glib-patch.txt](https://github.com/mxe/mxe/files/1495066/glib-patch.txt), but there may be a better place (a pre-built hook in the makefiles  I am not aware of?) to achieve this.

**Comment by tonytheodore** [comment]
Thanks! Applied slightly differently in https://github.com/mxe/mxe/commit/517ca7ccd009919fed5cdb623821e78cff5d0ef0 to match the cross-build.
