### ISSUE TITLE
openssl update fails to build

### ISSUE THREAD

**Issue by crypto-assortments** [mxe/mxe#1993]
i am running mxe on ubuntu 14 and went to update open ssl package,
the build fails with log
https://gist.github.com/crypto-assortments/ce3a3f572672ebc06ee17f642485be77

i assume because openssl.mk updates but their is no openssl-1-fixes.patch update.

also strangely local version of openssl.mk is up to 1.1.0g whereas https://github.com/mxe/mxe/blob/master/src/openssl.mk is 1.0.2m
this made it impossible to manually update openssl-1-fixes.patch as the github is also at 1.0.2m

**Comment by tonytheodore** [comment]
See #1508, openssl update to 1.1x is blocked on qtbase and boost updates. In that PR, the patch has simply been removed as it was either applied upstream or is no longer necessary.

**Comment by crypto-assortments** [comment]
thanks,
after wiping the openssl-1-fixes.patch file, 1.1.0g compiled fine.

still leaves me with two questions,
1 - why is mxe updating from a different git?
this made it hard for me to see the obvious fix

2 - why didnt mxe update the patches file when i updated?

**Comment by tonytheodore** [comment]
I think you may be conflating `make update` with `git pull`.
  - `make update*` runs locally and checks the upstream package to update the version and checksum of the source tarball. This could break a package (for various reasons including patches) or any of it's downstream dependencies. It needs to be tested locally to fix those breakages.
  - `git pull` will fetch the latest versions/patches that have been committed to mxe

> 1 - why is mxe updating from a different git?
this made it hard for me to see the obvious fix

It isn't, your local version will have the new version after `make update-package-openssl`. Try `git status` to see what has been changed.

> 2 - why didnt mxe update the patches file when i updated?

mxe only knows about changes to the patches "after" you(or someone) has updated (i.e. `make update`), fixed any issues, submitted those changes back, and the PR is accepted.

I'm not entirely sure what you're asking.

**Comment by crypto-assortments** [comment]
ok. my mistake. i used 
`make update-package-openssl`
and assumed it would pull data from the git, 

i will update the initial question and close.
