### ISSUE TITLE
protobuf is failing during make

### ISSUE THREAD

**Issue by cinemast** [mxe/mxe#1994]
https://gist.github.com/cinemast/11ebb2d058246aad3f568c5a1ff48242

**Comment by tonytheodore** [comment]
> On 28 Nov 2017, at 05:24, Peter Spiess-Knafl <notifications@github.com> wrote:
> 
> https://gist.github.com/cinemast/11ebb2d058246aad3f568c5a1ff48242

Try grabbing the latest version, we recently changed the backup logic to keep trying on failed checksums in #1974.

**Comment by cinemast** [comment]
I already used the latest version. Running `make update-checksum-protobuf` is a quickfix.

**Comment by tonytheodore** [comment]
Check the log, it looks like you're on a different branch or haven't run `git pull` for a while:
```
[git-log]   27facf1c Merge pull request #1659 from tonytheodore/gcc5-fix
```

**Comment by cinemast** [comment]
My bad. Sorry for the noise. I checked out the latest release, which was from february this year.
Thanks for the quick response.

**Comment by tonytheodore** [comment]
I see now, we don't have releases per-se, those are tags for when binary packages are produced. The master branch is generally the most trouble-free.
