### ISSUE TITLE
Hyperscan build is failing when making qt5base-dev

### ISSUE THREAD

**Issue by Cenkron** [mxe/mxe#1997]
The hyperscan make fails in a recently installed MXE, for both Windows build targets.
I see that there is a recent patch for something in this area, but have no idea how to install it, or if it is relevant to this issue.

My underlying issue is the failure of Cmake to  understand qt5_wrap_ui, and I have the impression that installing qt5base-dev might be the solution to this.

**Comment by tonytheodore** [comment]
Can you post a link to the full log?

**Comment by Cenkron** [comment]
Here is the hyperscan build log
[hyperscan_i686-w64-mingw32.static.posix.txt](https://github.com/mxe/mxe/files/1531508/hyperscan_i686-w64-mingw32.static.posix.txt)

**Comment by tonytheodore** [comment]
I see, it's not detecting SSSE3 correctly, possibly something to do with VirtualBox. Can you check if #2000 fixes it?
