### ISSUE TITLE
qt3d i686-w64-mingw32.shared can not be built by mxe from master branch

### ISSUE THREAD

**Issue by aido93** [mxe/mxe#1999]
$ make MXE_TARGETS='i686-w64-mingw32.shared' qt5 -j2 JOBS=2

Failed to build package qt3d for target i686-w64-mingw32.shared!
------------------------------------------------------------
Makefile:43: ошибка выполнения рецепта для цели «sub-src-make_first»
make[2]: *** [sub-src-make_first] Error 2
make[2]: выход из каталога «/home/bunny/mxe/tmp-qt3d-i686-w64-mingw32.shared/qt3d-opensource-src-5.9.3»
Makefile:687: ошибка выполнения рецепта для цели «build-only-qt3d_i686-w64-mingw32.shared»
make[1]: *** [build-only-qt3d_i686-w64-mingw32.shared] Error 2
make[1]: выход из каталога «/home/bunny/mxe»
real    21m32,849s
user    20m12,516s
sys     1m33,112s
------------------------------------------------------------
[log]      /home/bunny/mxe/log/qt3d_i686-w64-mingw32.shared

$ uname -a
Linux sLDUpdate01 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

**Comment by tonytheodore** [comment]
Can you post a link to the full log?

**Comment by tonytheodore** [comment]
Qt5 has since been updated, can you open a new issue (with full log) if it still fails?
