### ISSUE TITLE
winpcap: Missing headers in i686-w64-mingw32.static

### ISSUE THREAD

**Issue by charlemagnelasse** [mxe/mxe#2004]
I just tried to build https://dev.cloudtrax.com/git/ap51-flash.git but it failed because the winpcap package neither provides pcap.h nor Win32-Extensions.h and no *wpcap.(so|a). Seems to be a bug in the MXE winpcap package because it works with the WpdPack_4_1_2.zip

    make PLATFORM=WIN32 CROSS=i686-w64-mingw32.shared- V=s ap51-flash
    i686-w64-mingw32.shared-gcc -Wall -Werror -W -g3 -std=gnu99 -Os -fno-strict-aliasing -DWIN32 -D_GNU_SOURCE -DREVISION_VERSION=\"f94f9c9\"  -MD -c flash.c -o flash.o
    In file included from flash.h:22:0,
                     from flash.c:29:
    compat.h:64:18: fatal error: pcap.h: No such file or directory
    compilation terminated.
    Makefile:142: recipe for target 'flash.o' failed

The only files I could find in mxe were

* ./usr/i686-w64-mingw32.shared/include/wpcapi.h
* ./usr/i686-w64-mingw32.shared/include/wpcapi.idl

Not sure what I should to with them

**Comment by tonytheodore** [comment]
`winpcap` is disabled for shared builds so you may have to try the static version.

**Comment by charlemagnelasse** [comment]
Thanks for the fast reply. But also the shared version doesn't work. There seems to be a different problem but there is still a problem:

    $ make PLATFORM=WIN32 CROSS=i686-w64-mingw32.static- V=s ap51-flash
    i686-w64-mingw32.static-gcc -Wall -Werror -W -g3 -std=gnu99 -Os -fno-strict-aliasing -DWIN32 -D_GNU_SOURCE -DREVISION_VERSION=\"3f67302\"  -MD -c flash.c -o flash.o
    In file included from compat.h:64:0,
                     from flash.h:22,
                     from flash.c:29:
    /mxe/usr/i686-w64-mingw32.static/include/pcap.h:45:23: fatal error: pcap/pcap.h: No such file or directory
    compilation terminated.

There is now a more stuff in mxe but it seems that some of the required things are missing:

    $ find . -iname "*wpcap*"                                          
    ./pkg/WpcapSrc_4_1_3.zip
    ./usr/i686-w64-mingw32.static/lib/libwpcap.a
    ./usr/i686-w64-mingw32.static/include/WpcapNames.h
    ./usr/i686-w64-mingw32.static/include/wpcapi.h
    ./usr/i686-w64-mingw32.static/include/wpcapi.idl
    ./usr/i686-w64-mingw32.shared/include/wpcapi.h
    ./usr/i686-w64-mingw32.shared/include/wpcapi.idl
    $ find . -iname Win32-Extensions.h
    ./usr/i686-w64-mingw32.static/include/Win32-Extensions.h
    $ find . -iname pcap.h            
    ./usr/i686-w64-mingw32.static/include/pcap.h

Here is the interesting content from pcap.h:

    /*
     * For backwards compatibility.
     *
     * Note to OS vendors: do NOT get rid of this file!  Many applications
     * expect to be able to include <pcap.h>, and at least some of them
     * go through contortions in their configure scripts to try to detect
     * OSes that have "helpfully" moved pcap.h to <pcap/pcap.h> without
     * leaving behind a <pcap.h> file.
     */
    #include <pcap/pcap.h>

**Comment by tonytheodore** [comment]
It seems there are more issues with it in #1389.

**Comment by tonytheodore** [comment]
Looks really hard to fix, there's other headers in various directories and it's not clear what should be in the libs. Probably have to wade through the Visual Studio projects to figure it out.

**Comment by charlemagnelasse** [comment]
All files which need to be installed in the correct include directiory are:

    ip6_misc.h
    pcap-namedb.h
    pcap-bpf.h
    pcap/namedb.h
    pcap/sll.h
    pcap/bpf.h
    pcap/usb.h
    pcap/pcap.h
    pcap/bluetooth.h
    pcap/vlan.h
    remote-ext.h
    Packet32.h
    Win32-Extensions.h
    bittypes.h
    pcap-stdinc.h
    pcap.h

They can all be found in:

    ip6_misc.h         == winpcap/wpcap/libpcap/Win32/Include/ip6_misc.h
    pcap-namedb.h      == winpcap/wpcap/libpcap/pcap-namedb.h
    pcap-bpf.h         == winpcap/wpcap/libpcap/pcap-bpf.h
    pcap/namedb.h      == winpcap/wpcap/libpcap/pcap/namedb.h
    pcap/sll.h         == winpcap/wpcap/libpcap/pcap/sll.h
    pcap/bpf.h         == winpcap/wpcap/libpcap/pcap/bpf.h
    pcap/usb.h         == winpcap/wpcap/libpcap/pcap/usb.h
    pcap/pcap.h        == winpcap/wpcap/libpcap/pcap/pcap.h
    pcap/bluetooth.h   == winpcap/wpcap/libpcap/pcap/bluetooth.h
    pcap/vlan.h        == winpcap/wpcap/libpcap/pcap/vlan.h
    remote-ext.h       == winpcap/wpcap/libpcap/remote-ext.h
    Packet32.h         == winpcap/Common/Packet32.h
    Win32-Extensions.h == winpcap/wpcap/Win32-Extensions/Win32-Extensions.h
    bittypes.h         == winpcap/wpcap/libpcap/Win32/Include/bittypes.h
    pcap-stdinc.h      == winpcap/wpcap/libpcap/pcap-stdinc.h
    pcap.h             == winpcap/wpcap/libpcap/pcap.h

**Comment by charlemagnelasse** [comment]
Sorry, should have told you where this information is taken from. Just check winpcap/create_include.bat in  WpcapSrc_4_1_3.zip

**Comment by tonytheodore** [comment]
Thanks, it didn't occur to me to look in the *.bat files.
