### ISSUE TITLE
Qt 5.10 with OpenSSL 1.1

### ISSUE THREAD

**Issue by JulyIGHOR** [mxe/mxe#2014]
Looks like currently mxe building Qt 5.10 with OpenSSL 1.0, but OpenSSL 1.1 is now supported by Qt.
It should be fixed to use OpenSSL 1.1

**Comment by JulyIGHOR** [comment]
If anyone know how to make it compile with OpenSSL 1.1 instead, please comment here with patch or instruction.

**Comment by tonytheodore** [comment]
I think the holdup may be that freetds uses gnutls and the newer version of openssl now implements functions that conflict. @mabrand do you recall if #1508 was blocked by the core qt build or the test program?

I'm not really sure how to fix this within `qmake`, or even in a single invocation of plain `ld` for that matter - it may be that we have to use openssl for freetds or provide some switching mechanism.

**Comment by tonytheodore** [comment]
The openssl 1.1 update breaks nearly every package that uses it. @JulyIGHOR, if you just want qt5, apply the changes from https://gist.github.com/tonytheodore/c9f2daa8385735c0978db866ddbce80d

**Comment by tonytheodore** [comment]
Will be updated in #1508 #2057
