### ISSUE TITLE
For qt5 harfbuzz depands on glib

### ISSUE THREAD

**Issue by alphaonex86** [mxe/mxe#2015]
Hi.

For qt5 harfbuzz depands on glib (and freetype). Can you drop it to be coerante with qt?
![36efbly](https://user-images.githubusercontent.com/778581/34157013-05721f12-e4c0-11e7-87b2-71bc1a6fb11a.png)

Cheers,

**Comment by tonytheodore** [comment]
Are you looking for something like #2001?

**Comment by alphaonex86** [comment]
Only if disabling it is well for Qt international support

**Comment by tonytheodore** [comment]
I imagine removing it will reduce legibility in international support.
