### ISSUE TITLE
mxe-x86_64-w64-mingw32-shared-qt5 link on LIBGCC_S_SJLJ-1.DLL

### ISSUE THREAD

**Issue by alphaonex86** [mxe/mxe#2022]
Hi,
I try compile Ultracopier with: mxe-x86_64-w64-mingw32-shared-qt5 for Windows 64Bits then.
Is linked on LIBGCC_S_SEH-1.DLL, well found.
Is linked on LIBGCC_S_SJLJ-1.DLL (conflict?), not found.
Cheers,

**Comment by tonytheodore** [comment]
`seh` is the default for `x86_64-w64-mingw32` and gcc can't have two exception handing models. To build with `sjlj`:
```
make MXE_TARGETS=x86_64-w64-mingw32.static.sjlj
```

Then use `x86_64-w64-mingw32.static.sjlj-g++` etc.

**Comment by alphaonex86** [comment]
Then why by default use two exception handing models?
Because I use the default build, and I wish only seh

**Comment by tonytheodore** [comment]
> Then why by default use two exception handing models?

You'd have to ask on the gcc/mingw-w64 lists but I believe that the choice is mostly performance related - dw2 may have a performance penalty on i686 so sjlj is preferred, there's no penalty for seh on x86_64 so that is the default.

> Because I use the default build, and I wish only seh

I'm not sure I understand correctly, is the default build doing what you want?

**Comment by tonytheodore** [comment]
> Is linked on LIBGCC_S_SEH-1.DLL, well found.
> Is linked on LIBGCC_S_SJLJ-1.DLL (conflict?), not found.

Actually, I probably don't understand the original question. Are you saying there's a binary that is linked to both?

**Comment by alphaonex86** [comment]
Sorry for my poor english.
I use the default Qt Shared MXE 64Bits, I wish the default SEH.
MXE link on LIBGCC_S_SEH-1.DLL and LIBGCC_S_SJLJ-1.DLL, on both by default.

Compile a Qt exemple program with mxe-x86_64-w64-mingw32-shared-qt5 to reproduce this bug.

**Comment by tonytheodore** [comment]
I can't reproduce with the MXE example program, can you detail the exact steps you used? Maybe also provide the binary so I can look at it with dependency walker.

**Comment by alphaonex86** [comment]
tested with: https://github.com/alphaonex86/Ultracopier/blob/master/ultracopier.pro

**Comment by tonytheodore** [comment]
There's a bunch of qmake errors:
```
RCC: Error in 'resources/ultracopier-resources.qrc': Cannot find file 'Languages/en/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'CopyEngine/Ultracopier/Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Themes/Oxygen/Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins-windows.qrc': Cannot find file 'PluginLoader/catchcopy-v0002/Languages/fr/translation.qm'
RCC: Error in 'resources/ultracopier-resources.qrc': Cannot find file 'Languages/en/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'CopyEngine/Ultracopier/Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Themes/Oxygen/Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins-windows.qrc': Cannot find file 'PluginLoader/catchcopy-v0002/Languages/fr/translation.qm'
```

but the generated Makefiles and objects have no reference to `sjlj` at all - only `seh` in the object files.

I don't really know how it could possibly link to both, you'll have to detail the exact steps and possibly provide a binary.

**Comment by alphaonex86** [comment]
Do empty file at the .qm file path mentioned, and qmake,make

**Comment by tonytheodore** [comment]
```
$ x86_64-w64-mingw32.shared-objdump -p release/ultracopier.exe | grep 'DLL Name'
	DLL Name: ADVAPI32.dll
	DLL Name: KERNEL32.dll
	DLL Name: msvcrt.dll
	DLL Name: SHELL32.dll
	DLL Name: USER32.dll
	DLL Name: libgcc_s_seh-1.dll
	DLL Name: libstdc++-6.dll
	DLL Name: Qt5Core.dll
	DLL Name: Qt5Gui.dll
	DLL Name: Qt5Network.dll
	DLL Name: Qt5Widgets.dll
	DLL Name: Qt5Xml.dll
```

**Comment by alphaonex86** [comment]
Sample binary: https://ultracopier.first-world.info/temp/ultracopier-windows-x86_64-1.4.0.5.zip

Qt5Core.dll is linked over LIBGCC_S_SJLJ-1.DLL
ultracopier.exe over LIBGCC_S_SEH-1.DLL

**Comment by tonytheodore** [comment]
Now I can see that in your file:
```
$ x86_64-w64-mingw32.shared-objdump -p ultracopier-windows-x86_64/Qt5Core.dll | grep 'DLL Name'
	DLL Name: ADVAPI32.dll
	DLL Name: KERNEL32.dll
	DLL Name: MPR.DLL
	DLL Name: msvcrt.dll
	DLL Name: ole32.dll
	DLL Name: libpcre2-16-0.dll
	DLL Name: SHELL32.dll
	DLL Name: USER32.dll
	DLL Name: VERSION.dll
	DLL Name: WINMM.DLL
	DLL Name: WS2_32.dll
	DLL Name: zlib1.dll
	DLL Name: libgcc_s_sjlj-1.dll
	DLL Name: libstdc++-6.dll
```
but not in an MXE build:
```
$ x86_64-w64-mingw32.shared-objdump -p usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Core.dll | grep 'DLL Name'
	DLL Name: ADVAPI32.dll
	DLL Name: KERNEL32.dll
	DLL Name: MPR.dll
	DLL Name: msvcrt.dll
	DLL Name: NETAPI32.dll
	DLL Name: ole32.dll
	DLL Name: libpcre2-16-0.dll
	DLL Name: SHELL32.dll
	DLL Name: USER32.dll
	DLL Name: USERENV.dll
	DLL Name: VERSION.dll
	DLL Name: WINMM.dll
	DLL Name: WS2_32.dll
	DLL Name: zlib1.dll
	DLL Name: libgcc_s_seh-1.dll
	DLL Name: libstdc++-6.dll
```

This question now is - how did you build qtbase?

**Comment by alphaonex86** [comment]
via make MXE_TARGETS='x86_64-w64-mingw32.shared i686-w64-mingw32.shared' qt5

**Comment by tonytheodore** [comment]
Okay, so you seem to have copied the 32-bit version into your zip:
```
$ file ultracopier-windows-x86_64/Qt5Core.dll
ultracopier-windows-x86_64/Qt5Core.dll: PE32 executable (DLL) (GUI) Intel 80386 (stripped to external PDB), for MS Windows
```
```
$ file usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Core.dll
usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Core.dll: PE32+ executable (DLL) (GUI) x86-64 (stripped to external PDB), for MS Windows
```

**Comment by alphaonex86** [comment]
Ok, my mistake, you can close it
