### ISSUE TITLE
MXE build failed on protobuf, Tar.Gz doesn't exist

### ISSUE THREAD

**Issue by zavodnyrichard** [mxe/mxe#2024]
Hi. I'm on Fedora 27 64-bit and tried to install MXE to compile my project for Windows. This is the third time the build failed on protobuf.

[https://pastebin.com/9KWTfJKW](https://pastebin.com/9KWTfJKW)

Steps I followed:
1. Git clone
2. Move to the /opt/mxe
3. make (2nd time: make EXCLUDE_PKGS='ocaml%', 3rd time: previous but with sudo)

**Comment by ted423** [comment]
https://github.com/google/googlemock/releases/tag/release-1.7.0

**Comment by tonytheodore** [comment]
Fixed in https://github.com/mxe/mxe/commit/9a48a19e875375aa811d7d5f8e96c57f2adc65a6
