### ISSUE TITLE
i686-w64-mingw32.static-cmake: command not found

### ISSUE THREAD

**Issue by zavodnyrichard** [mxe/mxe#2026]
Okay, today morning I posted my issue. I decided to build MXE only at basic (make cc). My project use CMake, so I wanted to use MXE CMake wrapper, but got this error: `bash: i686-w64-mingw32.static-cmake: command not found...`. PATH variable is correct, since I can use **i686-w64-mingw32.static-g++ ...** command.

**Comment by zavodnyrichard** [comment]
Problem solved by making **cmake-conf** package.

`make cmake-conf`

**Comment by tonytheodore** [comment]
The more intuitive `make cmake` will also work now https://github.com/mxe/mxe/commit/28e5279c1774f7416151ee458dcce2b14f5e8dbd. `cmake-conf` is more an internal package that may go away at some point.

**Comment by cool2528** [comment]
@zavodnyrichard How do I make a `cmake-conf` package? Do you have detailed steps?
