### ISSUE TITLE
make MXE_TARGETS="i686-w64-mingw32.static" qttools FAILS

### ISSUE THREAD

**Issue by mroxso** [mxe/mxe#2029]
qttools fails while building with Ubuntu 14.04.

building with sudo make `MXE_TARGETS="x86_64-w64-mingw32.static" qttools ` **works**, but I need 32 Bit to be build as well.

Stackoverflow:
https://stackoverflow.com/questions/47951089/building-qttools-with-mxe-causes-error-altcoin-compiling

Log:
https://gist.github.com/mroxso/8e049409813c44180a6e0fea1b53426a

**Comment by tonytheodore** [comment]
Strange, seems to be the same as #2011.

**Comment by tehnick** [comment]
Try with `MXE_PLUGIN_DIRS += plugins/gcc6` or `MXE_PLUGIN_DIRS += plugins/gcc7` in `settings.mk`.

**Comment by tonytheodore** [comment]
Please try again with the latest master
