### ISSUE TITLE
C++17 support

### ISSUE THREAD

**Issue by zavodnyrichard** [mxe/mxe#2030]
Does MXE support C++17? I need use std::byte, which is C++17 functionality. How can I enable it?

**Comment by PsychoXIVI** [comment]
You should use **GCC 7**, so make sure you selected `gcc7` plugin in `settings.mk`.

**Comment by tehnick** [comment]
Use `MXE_PLUGIN_DIRS += plugins/gcc6` or `MXE_PLUGIN_DIRS += plugins/gcc7` in `settings.mk`.

**Comment by juzzlin** [comment]
I can see that `settings.mk` is a generated file which make this a bit hard to do in my `Dockerfile`. I tried to set GCC version in to 9.3.0 in `src/gcc/gcc.mk` but then `make qt5` fails:

```
[download]    gcc-9.3.0.tar.xz
[build]       gcc                    i686-w64-mingw32.static

Failed to build package gcc for target i686-w64-mingw32.static!
------------------------------------------------------------
Hunk #1 succeeded at 69 with fuzz 2 (offset 24 lines).
Hunk #2 succeeded at 118 (offset -431 lines).
Hunk #3 succeeded at 131 with fuzz 2 (offset -431 lines).
Makefile:855: recipe for target 'build-only-gcc_i686-w64-mingw32.static' failed
make[1]: *** [build-only-gcc_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory '/mxe'
real	0m12.329s
user	0m10.202s
sys	0m4.002s
------------------------------------------------------------
[log]      /mxe/log/gcc_i686-w64-mingw32.static

Makefile:855: recipe for target '/mxe/usr/i686-w64-mingw32.static/installed/gcc' failed
make: *** [/mxe/usr/i686-w64-mingw32.static/installed/gcc] Error 1
The command '/bin/sh -c make qt5' returned a non-zero code: 2
```

Is it supposed to work like that or is 9.3.0 just "too new" ? :)

**Comment by tonytheodore** [comment]
You can do:
```
make \
    IGNORE_SETTINGS=yes \
    MXE_PLUGIN_DIRS=plugins/gccx \
    qt5
```
There's been a few gcc11 fixes recently, so anything from gcc7-11 should work for you.

**Comment by juzzlin** [comment]
Seemed to work, thanks! I still had to create empty `settings.mk` due to `cat: ./settings.mk: No such file or directory`.

**Comment by tehnick** [comment]
> There's been a few gcc11 fixes recently

I saw segfaults in qtwebkit on youtube, when all build environment is built with gcc-10 or gcc-11, but I did not re-check this bug after your last patches though. For other Qt programs, which do not use QtWebkit, I did not see any difference with builds via gcc-9.

**Comment by tehnick** [comment]
And gcc-9 already has c++17 support IIRC.

**Comment by juzzlin** [comment]
I ended up in a problem with `GCC11` and `qtdeclarative`:

```
e/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++  -o .obj/release/qv4compilationunitmapper.o jsruntime/qv4compilationunitmapper.cpp
In file included from jsruntime/qv4regexp_p.h:62,
                 from jsruntime/qv4regexp.cpp:40:
../3rdparty/masm/yarr/Yarr.h:46:44: error: 'numeric_limits' is not a member of 'std'
   46 | static const unsigned offsetNoMatch = std::numeric_limits<unsigned>::max();
      |                                            ^~~~~~~~~~~~~~
../3rdparty/masm/yarr/Yarr.h:46:59: error: expected primary-expression before 'unsigned'
   46 | static const unsigned offsetNoMatch = std::numeric_limits<unsigned>::max();
      |                                                           ^~~~~~~~
make[5]: *** [Makefile.Release:25966: .obj/release/qv4regexp.o] Error 1
```

Probably there's some header now missing.

**Comment by realnc** [comment]
@juzzlin 

> Seemed to work, thanks! I still had to create empty `settings.mk` due to `cat: ./settings.mk: No such file or directory`.

`make check-requirements` before building anything. This will generate `settings.mk` for you. Then you can `echo >>` whatever you want to `settings.mk`. For example:

```dockerfile
make check-requirements
for settings_line in \
        "" \
        'JOBS := $(shell nproc)' \
        "MXE_TMP := /tmp/mxe" \
        "MXE_TARGETS := ${DOCKER_MXE_TARGET}" \
        "MXE_USE_CCACHE=" \
        "" \
        "override MXE_PLUGIN_DIRS += plugins/gcc11" \
        "gcc_CONFIGURE_OPTS := --enable-languages=c,c++" \
    ; do echo "$settings_line" >> settings.mk; done
```
