### ISSUE TITLE
Build specific version of package

### ISSUE THREAD

**Issue by cbrnr** [mxe/mxe#2034]
I was wondering how I can build a specific version of a package. For example, I need Qt 5.8, but the `qt5` package only provides Qt 5.10. There is also a question on StackOverflow: https://stackoverflow.com/questions/42953229/how-to-specify-specific-qt-version-in-mxe

Do I have to check out the MXE repository at the specific point in time where Qt 5.8 was available in `qt5`? Or is there an easier way such as `make qt5==5.8`?

**Comment by tonytheodore** [comment]
There's no easy way - it's possible to simply stay on a git checkout, but then other toolchain features are also frozen. See the [qt5-freeze plugin](https://github.com/mxe/mxe/tree/master/plugins/examples/qt5-freeze) for an example of how to create a longer term specific version of Qt5.

**Comment by cbrnr** [comment]
Thanks, that's what I thought. Meanwhile, I managed to build Qt 5.8 by checking out the repository at a specific commit, but it didn't work out of the box. For example, the hash sums of some source files did not match, and one source package could not be extracted because the `.tar.gz` file actually was not zipped.
