### ISSUE TITLE
Failed to build package protobuf for target x86_64-pc-linux-gnu (fedora 25) googlemock-release-1.7.0.tar.gz isn't getting downloaded

### ISSUE THREAD

**Issue by flintjr** [mxe/mxe#2035]
The googlemock-release-1.7.0.tar.gz isn't getting downloaded?

https://gist.github.com/flintjr/606984703063d8f7053921b73cbdd770

**Comment by tonytheodore** [comment]
Ouch, I'll can see the same - I'll have a look at it.

**Comment by andrevmatos** [comment]
Related to #2024 ? I'm also experiencing this, `make qt5` and friends failing on docker on `ubuntu:17.10`

**Comment by e-nexus** [comment]
I had to add googlemock and googletest to make command lately when building protobuf.

**Comment by ted423** [comment]
https://github.com/google/googlemock/releases/tag/release-1.7.0

**Comment by bobozm** [comment]
try 
sudo make update

**Comment by tonytheodore** [comment]
fixed in https://github.com/mxe/mxe/commit/9a48a19e875375aa811d7d5f8e96c57f2adc65a6
