### ISSUE TITLE
Windows style is broken in Qt 5.10.0

### ISSUE THREAD

**Issue by tehnick** [mxe/mxe#2037]
Controls of applications built with Qt 5.10.0 from MXE use style of Win98.

There is no such issue with Qt 5.9.3, so I have reverted build environment to older version of MXE as temporary workaround.

**Comment by tehnick** [comment]
Problem was found by Psi+ users. If my description is not enough clear, you may launch few last builds of Psi+ and see the difference yourself. For example:
* `psi-plus-1.2.139_win7_x86.7z` and `psi-plus-1.2.139_win7_x86_64.7z` are built with Qt 5.10.0
* `psi-plus-1.2.156_win7_x86.7z` and `psi-plus-1.2.156_win7_x86_64.7z` are build with Qt 5.9.3

They may be downloaded from:
https://sourceforge.net/projects/psiplus/files/MS-Windows/Personal-Builds/tehnick/

**Comment by tehnick** [comment]
After small research I have found that now Windows Vista Style is in separate plugin:
styles/qwindowsvistastyle.dll
When it is packaged with program all works fine.

**Comment by 209914097** [comment]
Hello! 
when I convert python3 application to exe in windows7 . Using pyinstaller -w -F program.py .Windows style is broken in Qt 5.what should I do ?Can you help me ?
