### ISSUE TITLE
Which version of MINGW64 was used to compile prebuilt MXE packages?

### ISSUE THREAD

**Issue by martinrotter** [mxe/mxe#2039]
I would like to use prebuild Qt 5.10 from http://pkg.mxe.cc/

So I download all Qt* binaries I want, and now I need my Qt application build against those libraries with matching mingw64 compiler. Where can I get matching mingw64 compiler? Is it available on http://pkg.mxe.cc/ too? Or should I just download newest mingw64 from https://sourceforge.net/projects/mingw-w64/files/ and proceed?

Thank you for info.

**Comment by ooxi** [comment]
Depending on whether you want to use i686 oder amd64 I recommend you to install either mxe-i686-w64-mingw32.static-gcc or mxe-x86-64-w64-mingw32.static-gcc from pkg.mxe.cc

Those packages can easily be installed on debian, when adding pkg.mxe.cc as repository. You can see an example of how this can be achieved [here](https://github.com/ooxi/violetland/blob/master/deploy/travis-ci/windows-i686/before-install.sh)

**Comment by tonytheodore** [comment]
To see the actual version used (5.0.1), find the last `build-` tag:

https://github.com/mxe/mxe/tags

and view the file at that point:

https://github.com/mxe/mxe/blob/build-2017-02-11/src/mingw-w64.mk
