### ISSUE TITLE
Curl with OpenSSL. Is this combination possible with MXE?

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [mxe/mxe#2048]
I would like to download files through https in a program of mine through libcurl. This works fine on Linux, but I'm totally unable to compile this with MXE.

The default configuration of libcurl with MXE doesn't have OpenSSL. So trying to compile this directly with what the default MXE creates an error in libcurl, the error is "Unknown protocol", because ssl is not there. Changing that is very easy, one just has to change `--without-ssl` to `--with-ssl` in `curl.mk`. Now after compiling OpenSSL, compiling libcurl there works fine. However, it's not possible at all to link a program that uses curl+ssl. This is the issue at hand that I need help with.

To illustrate the issue, I've created a minimal example, please find it here: https://github.com/TheQuantumPhysicist/CurlWithSSLMinimal

You can simply use `i686-w64-mingw32.static-cmake` to cmake that project then `make`. You'll get many undefined reference errors. I tried to improvise and add all the missing libraries (as you see in the cmake file), but it never linked successfully.

So is it ever possible to get this to work? Thank you in advance and I appreciate your help.

**Comment by ThKattanek** [comment]
You must use pkg-config for list required libs (sorry for my bad english ;) )
check this Makefile ...
```make
cmake_minimum_required(VERSION 2.8)

project(CurlSSLMinimal)

add_executable(${PROJECT_NAME} "main.cpp")

if(WIN32)

    execute_process(
        COMMAND ${PKG_CONFIG_EXECUTABLE} libcurl --libs
        OUTPUT_VARIABLE CURL_LIBS
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    target_link_libraries(${PROJECT_NAME} ${CURL_LIBS})
else()
    target_link_libraries(${PROJECT_NAME} -lcurl)
endif(WIN32)
```

**Comment by TheQuantumPhysicist** [comment]
@ThKattanek 
Thanks a lot man! That solved the problem! I'm grateful!
