### ISSUE TITLE
Installing MXE via homebrew

### ISSUE THREAD

**Issue by keilmillerjr** [mxe/mxe#2053]
[gist issue](https://gist.github.com/keilmillerjr/60a59bcdeaafd7c6ab453d2c8bd6ff6e)

I would like to install MXE on my mac so I can compile [attract](https://github.com/mickelson/attract) for multiple environments.

Installing MXE via home-brew on Mac to compile attract.

I choose home-brew because I already have home-brew installed. Ran the following command:

```
brew install \
    autoconf automake coreutils gdk-pixbuf gettext \
    gnu-sed gnu-tar intltool libtool p7zip wget xz
```
This part of the requirements is what bothers me:

> Some formulae are keg-only and will need brew link to be found.
> - [requirements](http://mxe.cc/#requirements)

I think there is some issues relating to keg-only based on the output from the command. See [gist issue](https://gist.github.com/keilmillerjr/60a59bcdeaafd7c6ab453d2c8bd6ff6e). Can anyone help me? I am rather new to this.

**Comment by tonytheodore** [comment]
I don't use homebrew, but the keg-only warnings seem related to conflicts with normal tools/libs. You could try building mxe without the `brew link` step and manually add each PATH to the `make` invocation as required if the build fails.

You should be able to ignore `All commands have been installed with the prefix 'g'.` as we already detect the prefixed versions (if any are missing, they should be added).

**Comment by keilmillerjr** [comment]
Thank you @tonytheodore! I am a step closer.

First I read [this article](http://osxdaily.com/2014/08/14/add-new-path-to-path-command-line/) on adding paths to the command line. I added the following paths, based on the brew install log:

```
Keils-iMac:mxe keiljr$ export PATH="/usr/local/opt/gettext/bin:$PATH"
Keils-iMac:mxe keiljr$ export PATH="/usr/local/opt/openssl/bin:$PATH"
```

I run ```make``` command and now I have the following error:

```
Keils-iMac:mxe keiljr$ make
[check requirements]
Missing requirement: scons

Please have a look at "docs/index.html" to ensure
that your system meets all requirements.

make: *** [/opt/mxe/usr/installed/check-requirements] Error 1
```

**Comment by keilmillerjr** [comment]
I ran ```brew install scons``` and then ```make``` and everything seemed to be going well until the following error:

```
Failed to build package glib for target x86_64-apple-darwin15.6.0!
------------------------------------------------------------
# easy to build on linux, but error-prone on darwin (and freebsd?)
# on darwin, use pre-built tools from macports with pinned
# version set in plugins/native/darwin/glib2-macports
cd '/opt/mxe/tmp-glib-x86_64-apple-darwin15.6.0/glib-2.50.2.build_' &&    tar xjf '/opt/mxe/pkg/glib2-2.50.3_0.darwin_16.x86_64.tbz2'
tar: Error opening archive: Failed to open '/opt/mxe/pkg/glib2-2.50.3_0.darwin_16.x86_64.tbz2'
make[1]: *** [build-only-glib_x86_64-apple-darwin15.6.0] Error 1
real	0m5.054s
user	0m4.137s
sys	0m0.774s
------------------------------------------------------------
[log]      /opt/mxe/log/glib_x86_64-apple-darwin15.6.0

make: *** [/opt/mxe/usr/x86_64-apple-darwin15.6.0/installed/glib] Error 1
```

[Complete log](https://gist.github.com/keilmillerjr/7d729357274b7b59ccd16e472d1dd07e).

**Comment by keilmillerjr** [comment]
Dowloaded this version of [glib](https://mirror.mxe.cc/pkg/glib2-2.50.3_0.darwin_16.x86_64.tbz2) and installed to ``` /opt/mxe/pkg/glib2-2.50.3_0.darwin_16.x86_64.tbz2``` and ran ```make``` again. Resolved that issue. Currently processing the ```make`` command.

**Comment by tonytheodore** [comment]
> Is this an error in the docs?

Yes, thanks. I've added some more notes:https://github.com/mxe/mxe/commit/e81c9a6f77ec9bc361e6489f8588c87aaa034acd

> Failed to build package glib

try a `git pull`, this should be fixed since yesterday:https://github.com/mxe/mxe/commit/9a48a19e875375aa811d7d5f8e96c57f2adc65a6. It downloads pre-built binaries from `macports`, but they should run on on any modernish version and don't affect your normal system as they're installed in an mxe-specific location.

**Comment by keilmillerjr** [comment]
Ran into another issue with alure, even after a git pull.

```
Keils-iMac:mxe keiljr$ make
[check requirements]
[git-log]   501e308 docs: use descriptive macos headings
[download]    libtool-2.4.4.tar.gz
[build]       alure                  i686-w64-mingw32.static

Failed to build package alure for target i686-w64-mingw32.static!
------------------------------------------------------------
/opt/mxe/tmp-alure-i686-w64-mingw32.static/alure-1.2/include/main.h:61:19: warning: 'BigEndian' defined but not used [-Wunused-variable]
 static const bool BigEndian = !LittleEndian;
                   ^
make[3]: *** [CMakeFiles/ALURE32-static.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build-only-alure_i686-w64-mingw32.static] Error 2
real	0m19.953s
user	0m25.978s
sys	0m4.321s
------------------------------------------------------------
[log]      /opt/mxe/log/alure_i686-w64-mingw32.static

make: *** [/opt/mxe/usr/i686-w64-mingw32.static/installed/alure] Error 1
```

**Comment by tonytheodore** [comment]
Can you post the full log?

**Comment by keilmillerjr** [comment]
@tonytheodore [mxe-issue-3.log](https://gist.github.com/keilmillerjr/d0587fb0280b0d31ee24fbf5d67a01e6)

**Comment by keilmillerjr** [comment]
@tonytheodore Woohoo! Alure issue resolved. Thank you for all your help.

Next issue:

```
Failed to build package atk for target i686-w64-mingw32.static!
------------------------------------------------------------
make[4]: *** Waiting for unfinished jobs....
bash: line 1: 35965 Trace/BPT trap: 5       /opt/mxe/usr/i686-w64-mingw32.static/bin/glib-genmarshal --prefix=atk_marshal ./atkmarshal.list --body >> xgen-gmc
make[4]: *** [stamp-atkmarshal.c] Error 133
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [build-only-atk_i686-w64-mingw32.static] Error 2
real	0m13.260s
user	0m7.134s
sys	0m3.394s
------------------------------------------------------------
[log]      /opt/mxe/log/atk_i686-w64-mingw32.static
```

[mxe-issue-4.log](https://gist.github.com/keilmillerjr/5cb98ef93fd2d30c86a68829dd3fb174)
[atk_i686-w64-mingw32.static](https://gist.github.com/keilmillerjr/a4e645ec94c6de0025da3fa84cf22b59)

**Comment by tonytheodore** [comment]
> It downloads pre-built binaries from macports, but they should run on on any modernish version

Seems I was wrong about this, I thought they were static binaries. I'm not sure what to try next, the version of glib in homebrew is too new and building it is always tricky.

**Comment by keilmillerjr** [comment]
Anyone have an idea of what to do next? Help is appreciated.

**Comment by tonytheodore** [comment]
Try #2059 to build glib tools (as we do on Linux).

**Comment by tonytheodore** [comment]
#2059 is merged now, seems to be working well.

**Comment by jdk** [comment]
been following closely but unfortunately this doesn't work for me. I'm getting the error attached.
[log.txt](https://github.com/mxe/mxe/files/1760630/log.txt)

libffi is installed in brew and I've tried:
export LIBFFI_CFLAGS=-I/usr/local/opt/libffi/lib/libffi-3.2.1/include
export LIBFFI_LIBS="-L/usr/local/opt/libffi/lib -lffi"

Any help would be greatly appreciated.

**Comment by tonytheodore** [comment]
What's the output of:
```
pkg-config --libs --cflags libffi
```

**Comment by jdk** [comment]
`Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing libffi.pc
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found`

But I had actually tried the following with the same error:
`export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/libffi.pc`

**Comment by tonytheodore** [comment]
See https://github.com/mxe/mxe/commit/55c488bb2947ee61e0e7d0c5900d4471f1c59ded which builds native libffi so there are no external deps.
```
$ otool -L usr/x86_64-apple-darwin17.4.0/bin/glib-compile-resources
usr/x86_64-apple-darwin17.4.0/bin/glib-compile-resources:
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 158.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1451.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1451.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.19.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by keilmillerjr** [comment]
Another ```git pull``` and ```make``` and I sucessfully built libffii and zlib. Hung up on glib.

[mxe-issue-4.log](https://gist.github.com/keilmillerjr/a13902b934985cfecaae571281329fee)
[glib_x86_64-apple-darwin15.6.0](https://gist.github.com/keilmillerjr/a4eb5e4910c6fa77438c81d3048dd30a)

**Comment by tonytheodore** [comment]
Can you try:
```diff
diff --git a/src/glib.mk b/src/glib.mk
index a6dea81a..cc5c4819 100644
--- a/src/glib.mk
+++ b/src/glib.mk
@@ -51,8 +51,10 @@ define $(PKG)_BUILD_DARWIN
         --disable-dtrace \
         --disable-libmount \
         --with-pcre=internal \
-        CPPFLAGS='-I$(BUILD_DIR).usr/include -I$(PREFIX)/$(TARGET)/include' \
-        LDFLAGS='-L$(BUILD_DIR).usr/lib -L$(PREFIX)/$(TARGET)/lib -lffi'
+        LIBFFI_CFLAGS='-I$(PREFIX)/$(TARGET)/include' \
+        LIBFFI_LIBS='-L$(PREFIX)/$(TARGET)/lib -lffi' \
+        CPPFLAGS='-I$(BUILD_DIR).usr/include' \
+        LDFLAGS='-L$(BUILD_DIR).usr/lib'
     $(MAKE) -C '$(BUILD_DIR)/glib'    -j '$(JOBS)'
     $(MAKE) -C '$(BUILD_DIR)/gthread' -j '$(JOBS)'
     $(MAKE) -C '$(BUILD_DIR)/gmodule' -j '$(JOBS)'
```

**Comment by tonytheodore** [comment]
Actually, that won't work, libffi installs headers to a subdir of lib. I'm testing this:
```diff
diff --git a/src/glib.mk b/src/glib.mk
index a6dea81a..ede5494f 100644
--- a/src/glib.mk
+++ b/src/glib.mk
@@ -51,8 +51,10 @@ define $(PKG)_BUILD_DARWIN
         --disable-dtrace \
         --disable-libmount \
         --with-pcre=internal \
-        CPPFLAGS='-I$(BUILD_DIR).usr/include -I$(PREFIX)/$(TARGET)/include' \
-        LDFLAGS='-L$(BUILD_DIR).usr/lib -L$(PREFIX)/$(TARGET)/lib -lffi'
+        LIBFFI_CFLAGS='-I$(PREFIX)/$(TARGET)/lib/$(libffi_VERSION)/include' \
+        LIBFFI_LIBS='-L$(PREFIX)/$(TARGET)/lib -lffi' \
+        CPPFLAGS='-I$(BUILD_DIR).usr/include' \
+        LDFLAGS='-L$(BUILD_DIR).usr/lib'
     $(MAKE) -C '$(BUILD_DIR)/glib'    -j '$(JOBS)'
     $(MAKE) -C '$(BUILD_DIR)/gthread' -j '$(JOBS)'
     $(MAKE) -C '$(BUILD_DIR)/gmodule' -j '$(JOBS)'
```

**Comment by tonytheodore** [comment]
Still a typo in the above (should be `lib/libffi-$(libffi_VERSION)`), but it's better to use `pkgconf` https://github.com/mxe/mxe/commit/15c4583c5177549dc13a1941cf5194b0ebb4f8b7.

**Comment by jdk** [comment]
giving it another go, thanks so much Tony

**Comment by jdk** [comment]
Alright, got much farther. New error attached. 

Looks like the perl in brew is missing XML/Parser.pm 

Should that be installed manually with cpan, or is there a dependency addition for that somewhere in mxe?

[log.txt](https://github.com/mxe/mxe/files/1761434/log.txt)

**Comment by tonytheodore** [comment]
There's nothing in MXE for perl modules, for that matter, perl isn't listed in the Homebrew reqs at all. 
I'd install perl via homebrew and then use that perl to manually install https://metacpan.org/pod/XML::Parser from cpan. Can you make a note of the commands to add to the docs?

P.S. bison and flex are missing from the list also, though they may not be required as the ones in /usr/bin may be recent enough.

**Comment by jdk** [comment]
Just wanted to thank you for the reply and give you a quick update. Cpan that comes with perl brew isn't working. After an install, which says success, the module doesn't get installed. 

I can see that it's putting the cpan module downloads in ~/.cpan/build/

The installation for said module should go in: ~/perl5/lib/perl5 

Checking in that directory, there is nothing installed. So I manually run make install in the XML perl directory download in ~/.cpan/build/ and it does indeed get installed in  ~/perl5/lib/perl5 

However, that location is not in the brew perl search path: 
```
(@INC contains: ../../tools/pm /usr/local/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/darwin-thread-multi-2level /usr/local/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1 /usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2level /usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1 /usr/local/lib/perl5/site_perl/5.26.1 /Users/kotzin/Projects/mxe/usr/i686-w64-mingw32.static/lib/glibmm-2.4/proc/pm)
```

This doesn't seem to be correct, and I want to say that maybe CPAN is intentionally broken with brew perl. CPAN should be installing modules to: /usr/local/Cellar/perl/$VER/lib/perl5/$VER/

However, that would also mean that with each update of perl through brew, these modules would not be carried over (and shouldn't, as they would very well have compatibility issues with the new version installed).

This is why most distributions package managers manage perl libs, and don't leave it up to cpan.

Still googling to find out what's going on. But currently stuck on this.

**Comment by tonytheodore** [comment]
Odd, I tried uninstalling it from macports and it's required by `intltool`, but not for `intltool` in homebrew (maybe it's just for docs). Did a forced uninstall and glibmm still succeeds, apparently it's part of the system perl in `/System/Library/Perl/Extras/5.18/` and it was using /usr/bin/perl all along.

Try https://github.com/mxe/mxe/commit/3ce8607dc5e46c643d5545db5f0c744b2aa0f51a

**Comment by jdk** [comment]
awesome, thanks1 Getting farther. New log aattached.
[log.txt](https://github.com/mxe/mxe/files/1765734/log.txt)

**Comment by tonytheodore** [comment]
Tricky one, libiconv is usually required by gettext but homebrew has it as keg-only and not part of gettext deps. I'll have to think about it.

As an aside, you can use the `-k` option to make to keep the build going as far as possible.

**Comment by tonytheodore** [comment]
See https://github.com/mxe/mxe/compare/9f9e0bb...e3071de

**Comment by keilmillerjr** [comment]
We got even further with a ```git pull``` and ```make```! :)

```
Keils-iMac:mxe keiljr$ make
[git-log]   b940094 gettext: remove native deps fixups
[build]       libiconv               i686-w64-mingw32.static
[done]        libiconv               i686-w64-mingw32.static                                26364 KiB      0m58.190s
[build]       gettext                i686-w64-mingw32.static
[done]        gettext                i686-w64-mingw32.static                                110992 KiB     1m7.986s
[build]       libiconv               x86_64-apple-darwin15.6.0
[done]        libiconv               x86_64-apple-darwin15.6.0                              28896 KiB      0m48.447s
[build]       gettext                x86_64-apple-darwin15.6.0
[done]        gettext                x86_64-apple-darwin15.6.0                              177204 KiB     7m34.498s
[build]       glib                   x86_64-apple-darwin15.6.0

Failed to build package glib for target x86_64-apple-darwin15.6.0!
------------------------------------------------------------
checking for msgfmt... no
configure: error: 
*** You must have either have gettext support in your C library, or use the
*** GNU gettext library. (http://www.gnu.org/software/gettext/gettext.html
make[1]: *** [build-only-glib_x86_64-apple-darwin15.6.0] Error 1
real	0m46.323s
user	0m25.289s
sys	0m5.591s
------------------------------------------------------------
[log]      /opt/mxe/log/glib_x86_64-apple-darwin15.6.0

make: *** [/opt/mxe/usr/x86_64-apple-darwin15.6.0/installed/glib] Error 1
```

[mxe-issue-5.log](https://gist.github.com/keilmillerjr/8c6d2cf8413f7c471759f9a8cd412cba)
[glib_x86_64-apple-darwin15.6.0](https://gist.github.com/keilmillerjr/d0ee2d2646e50e525ba1a2a32b961cb0)

**Comment by jdk** [comment]
@keilmillerjr when you installed the brew dependencies, a note came up telling you to append the location of gettext to your path: /usr/local/opt/gettext/bin

export PATH="${PATH}:/usr/local/opt/gettext/bin"

Try that and run make again, alternatively, you can add that to your bashrc file.

I've been compiling for ~3 hours. I think it's going to finish.

**Comment by jdk** [comment]
Okay, getting a lot closer. New log attached.

Failure snippet:
```
checking for perl... /usr/local/bin/perl
checking for bison... /usr/bin/bison
checking bison version 2.3 >= 2.4... configure: error: no
make[1]: *** [build-only-gstreamer_i686-w64-mingw32.static] Error 1
```

Installed bison meets the requirements:
```
#  which bison
/usr/bin/bison

# bison --version
bison (GNU Bison) 2.3
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

[log.txt](https://github.com/mxe/mxe/files/1768865/log.txt)

**Comment by tonytheodore** [comment]
> alternatively, you can add that to your bashrc file.

I believe that's what `brew link` does and what @keilmillerjr was trying to avoid initially.

> checking bison version 2.3 >= 2.4... configure: error: no

Seems to need 2.4 or greater, try the MXE version(will also install flex):
```
make bison MXE_TARGETS= MXE_PLUGIN_DIRS=plugins/native
```

I think I can detect this automatically but don't have time right now. Also, I think the `/usr/bin/openssl` version is recent enough and we now build `gettext` so they can probably be removed.

**Comment by tonytheodore** [comment]
@jdk see https://github.com/mxe/mxe/commit/50ba42cce4f27263d90832a83563d39a983171bd for flex/bison - there's no real need to do version detection, if they're always built I'll pick up issues sooner.

@keilmillerjr see https://github.com/mxe/mxe/commit/e30dd374299d3d6065039e1be6cf22847bf09201 for gettext fix to install bins in PATH visible to MXE.

Could either/both of you also test:
```
make download OPENSSL=/usr/bin/openssl
```

to test the system installed version is recent enough? We can remove the PATH instructions for homebrew if it is.

**Comment by tonytheodore** [comment]
Actually, could you both test without setting PATH for gettext also?

**Comment by jdk** [comment]
Testing:

```
make download OPENSSL=/usr/bin/openssl
```

right now on the original branch. I'll post the stdout.log of this, and then switch to ^HEAD and give it another go shortly.

**Comment by jdk** [comment]
Here is the output on 0591e69537a6e7f5bc17b8b94a17e273a840f40d
[stdout.txt](https://github.com/mxe/mxe/files/1769876/stdout.txt)

**Comment by tonytheodore** [comment]
https://github.com/mxe/mxe/commit/0591e69537a6e7f5bc17b8b94a17e273a840f40d was before the OPENSSL variable was added but the same can be achieved by removing `/usr/local/opt/openssl/bin` from PATH

**Comment by jdk** [comment]
Okay, same perl error on different package.

I tried adding the line '$(shell [ `uname -s` == Darwin ] && echo "PERL=/usr/bin/perl")' similar to your previous patch to libgsf.mk but that didn't help

[log.txt](https://github.com/mxe/mxe/files/1771995/log.txt)

**Comment by tonytheodore** [comment]
grepping through `./configure`, the variable is `INTLTOOL_PERL`, see https://github.com/mxe/mxe/commit/35bee25b0be988a744379670291db5e2b6b89d91

**Comment by jdk** [comment]
Success!

```
#  ./usr/bin/i686-w64-mingw32.static-gcc -v
Using built-in specs.
COLLECT_GCC=./usr/bin/i686-w64-mingw32.static-gcc
COLLECT_LTO_WRAPPER=/Users/kotzin/Projects/mxe/usr/libexec/gcc/i686-w64-mingw32.static/5.4.0/lto-wrapper
Target: i686-w64-mingw32.static
```

There were a few more files that needed to get the perl patch, so I did those as I completed the compile. Pull request created with the patches. 

Thank you so much for all the help. Been dying to get mxe working on darwin for a while.

Going to try the openssl command now.

**Comment by keilmillerjr** [comment]
@jdk Amazing! Thank you! Anything I need to add to path variable before make?

**Comment by jdk** [comment]
@keilmillerjr I believe tony patched it so gettext can be found in: https://github.com/mxe/mxe/commit/e30dd374299d3d6065039e1be6cf22847bf09201

So as long as you grab HEAD and add my patches, I don't see any reason why it wont work.

**Comment by jdk** [comment]
@tonytheodore The patches are in pull request #2061

The output of the below command is attached.
```
#  make download OPENSSL=/usr/bin/openssl
````

[stdout.txt](https://github.com/mxe/mxe/files/1776198/stdout.txt)

**Comment by tonytheodore** [comment]
Thanks @jdk, the openssl versions in [10.11.6](https://opensource.apple.com/release/os-x-10116.html) and [10.13.3](https://opensource.apple.com/release/macos-10133.html) are both in the 0.98.x series and should be suitable. 

@keilmillerjr, I've [updated the docs](https://github.com/mxe/mxe/commit/a845d52674d4dcb701d02254bebe72c4c9441890) to indicate that `$PATH` mods and `brew link` aren't necessary.

**Comment by keilmillerjr** [comment]
Thank you guys so much! Finally successful!
