### ISSUE TITLE
Weak gnupg key for pkg.mxe.cc

### ISSUE THREAD

**Issue by tehnick** [mxe/mxe#2054]
https://travis-ci.org/eiskaltdcpp/eiskaltdcpp/jobs/342501527
```
...
sudo apt-key adv --keyserver x-hkp://keys.gnupg.net --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
Executing: /tmp/tmp.OGbRDQOmRx/gpg.1.sh --keyserver
x-hkp://keys.gnupg.net
--recv-keys
D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
gpg: requesting key DB45C6AB from hkp server keys.gnupg.net
gpg: key DB45C6AB: public key "Boris Nagaev <bnagaev@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
+sudo apt-get update -qq
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
+sudo apt-get install -qq mxe-x86-64-w64-mingw32.shared-aspell mxe-x86-64-w64-mingw32.shared-boost mxe-x86-64-w64-mingw32.shared-jsoncpp mxe-x86-64-w64-mingw32.shared-libidn mxe-x86-64-w64-mingw32.shared-lua mxe-x86-64-w64-mingw32.shared-miniupnpc mxe-x86-64-w64-mingw32.shared-qtmultimedia mxe-x86-64-w64-mingw32.shared-qttools
...
```
@starius Could you update the gpg key used in that PPA?

**Comment by tehnick** [comment]
https://juliank.wordpress.com/2016/03/14/dropping-sha-1-support-in-apt/

**Comment by tonytheodore** [comment]
Strange, it looks like @starius already updated that https://github.com/mxe/mxe-apt/commit/58a198bb0156259b62a1f971c95fc43155ac022d.

**Comment by ArseniyShestakov** [comment]
Website still mentions old key that is no longer available on keyserver.

**Comment by tehnick** [comment]
How about closing of this bug report?

All builds of EiskaltDC++ project using MXE are successful now. For example:
https://travis-ci.org/eiskaltdcpp/eiskaltdcpp/builds/429769054
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/f85ba8c01/.travis.yml
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/f85ba8c01/tests/travis/install-build-depends.sh#L64
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/f85ba8c01/tests/travis/build-and-test.sh#L117
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/f85ba8c01/windows/build-using-mxe.sh

Any feedback from other projects?
