### ISSUE TITLE
p7zip not working

### ISSUE THREAD

**Issue by WZ2100ModsFan** [mxe/mxe#2056]
here's the log

https://gist.github.com/WZ2100ModsFan/5badf58a2bfda5198b46be987fac1249

Can't seem to detect that i already have p7zip

**Comment by tonytheodore** [comment]
You need [p7za-full](https://packages.debian.org/stretch/all/p7zip-full/filelist) for `7za`. It's easiest to install all the [requirements](http://mxe.cc/#requirements-debian).
