### ISSUE TITLE
Luajit compiling failed because gcc-multilib was not installed

### ISSUE THREAD

**Issue by alexandruchirita4192** [mxe/mxe#2058]
Could not compile "luajit" package on Debian 9 because cdefs.h was missing on the system because gcc-multilib-dev was not installed (but the package was not found in the dependencies list for mxe).

I installed the gcc-multilib (and g++-multilib because of excess of zeal) and the package build worked perfectly.

**Comment by tonytheodore** [comment]
You'll also need `libc6-dev-i386` for some other packages, check the requirements:
http://mxe.cc/#requirements-debian

**Comment by alexandruchirita4192** [comment]
Sorry. I didn't see the comment for 64 bit Debian. Thank you.

**Comment by alexandruchirita4192** [comment]
There was the following paragraph I missed:
"On 64-bit Debian, install also:
apt-get install g++-multilib libc6-dev-i386"

**Comment by tonytheodore** [comment]
I think 64-bit systems are the default these days, and I'm not even sure if [MXE can be built with the amount of virtual memory on 32-bit systems](https://github.com/mxe/mxe/issues/1381#issuecomment-225459494).

I've [changed the docs for 64-bit to be the default case](https://github.com/mxe/mxe/commit/8c784dbef1c419826433f76c639e89a582ddd6e4).
