### ISSUE TITLE
build-pkg.lua fails creating debian packages

### ISSUE THREAD

**Issue by ooxi** [mxe/mxe#2064]
When trying to create debian packages using tools/build-pkg.lua, no `.deb` files are created. However, during the build I receive numerous messages like

```
dpkg-deb: error: package architecture is missing or empty
dpkg-deb: warning: parsing file './mxe-x86-64-w64-mingw32.static-binutils_2.28/DEBIAN/control' near line 16 package 'mxe-x86-64-w64-mingw32.static-binutils':
 empty value for architecture
```

How can we fix this issue?

**Comment by ooxi** [comment]
I most likely found the reason, build-pkg.lua is using dpkg-architecture which I did not have installed. I'm currently testing whether this fixes the problem and will prepare a pull request for the documentation, if that's the case.

**Comment by tonytheodore** [comment]
Ouch! That must happen after the entire MXE build as I can build with `MXE_BUILD_PKG_NO_DEBS` on darwin and still create the deb-control files (with missing arch).

**Comment by ooxi** [comment]
I would have but thankfully you guys already provided `MXE_BUILD_PKG_MAX_ITEMS` which allowed my to experiment with much shorter iteration times :-)

Anyway for anybody looking at this in the future, make sure you have the commands `dpkg-deb` as well as `dpkg-architecture` available, e.g. by installing the Debian package `dpkg` as well as `dpkg-dev`

**Comment by tonytheodore** [comment]
Also note the `MXE_BUILD_PKG_NO_SECOND_PASS` option if you just want to build deb pkgs. It reveals [missing deps](https://github.com/mxe/mxe/commit/b5b527f782f8526a2094f724b9c5ecfd0bbe8eec) but more than doubles the runtime.

**Comment by ooxi** [comment]
I did not realize that, thank you!
