### ISSUE TITLE
Cannot build LuaJIT

### ISSUE THREAD

**Issue by padicao2010** [mxe/mxe#2068]
Run `make luajit` according to [the tutorial](http://mxe.cc/#tutorial). But it failed.

[log](https://gist.github.com/padicao2010/e99ac07e550058e291cbb1a286db45f2)

It shows that it can't find sys/cdefs.h, sys/types.h. But they exists in mxe/usr/i686-w64-mingw32.static/include/sys.

**Comment by tonytheodore** [comment]
That error is part of a native build step with HOSTCC, do you have the [multi-lib packages](http://mxe.cc/#requirements-debian) (g++-multilib libc6-dev-i386) installed?

**Comment by padicao2010** [comment]
It works after g++-multilib and libc6-dev-i386 are installed. Sorry for my careleseness. I thought only 32bit installs these two packages.

**Comment by tonytheodore** [comment]
The docs were a little confusing and we only [updated them a few days ago](https://github.com/mxe/mxe/commit/8c784dbef1c419826433f76c639e89a582ddd6e4#diff-eae600270579316beb8b8d9b9a5732d4).
