### ISSUE TITLE
Out of date libraries

### ISSUE THREAD

**Issue by zavodnyrichard** [mxe/mxe#2079]
I noticed these libraries are out of date:
CryptoPP, latest version 6.1.0, MXE includes 5.6.3
Boost, latest version 1.66.0, MXE includes 1.60.0
GLEW, latest version 2.1.0, MXE includes 1.12.0

**Comment by tonytheodore** [comment]
Boost update is in progress https://github.com/mxe/mxe/pull/2043 and blocked on breaking some downstream packages. A PR to update the others is welcome!

You can see which packages have updates (or broken update scripts) with:
```
make update UPDATE_DRYRUN=true
```
To update the version and checksum of a package:
```
make update-package-glew
```
To see which packages are used by `glew` and need to be tested:
```
make show-deps-glew
```
