### ISSUE TITLE
Config file in homedir

### ISSUE THREAD

**Issue by mgerhardy** [mxe/mxe#208]
I would like to have a config file with (at least) the path to mxe.

Not for mxe itself - but for others to use it. 
if you currently use mxe (have all the libs compiled), you have to know the path of the mxe installation. You first have to cd /my/own/project; export PATH=/mxe/usr/bin/:/mxe/usr/i686.../bin; make

There is no way for a project to auto-get the path of the mxe installation. It would be cool if there would be some kind of ini file where the path is stored. So one could write a makefile that can auto-find mxe.

**Comment by tonytheodore** [comment]
mxe is better suited to being stateless
