### ISSUE TITLE
cmake does not discover openblas

### ISSUE THREAD

**Issue by ajmay81** [mxe/mxe#2081]
With a fresh mxe clone and installing 'blas' one now gets openblas instead of netlib routines. For our project cmake (FindBLAS) does not locate the openblas library because it has been built with openmp threading and it fails to resolve the openmp calls, eg. in CMakeError.log:

    mxe/usr/x86_64-w64-mingw32.static/lib/libopenblas.a(sgemm.obj):gemm.c:(.text+0x27b): undefined reference to `omp_in_parallel'

(our project does not use openmp threading).

I actually don't mind if this is fixed or not, but would like to still have the old 'blas', 'lapack' etc. available. Would it be possible to create for instance 'netlibblas', 'netliblapack' etc. so one can choose these instead? The netlib routines are now hosted in an official github repository so instead of the netlib website the sources could be obtained from:

`https://github.com/Reference-LAPACK/lapack-release`

Just to note, when building mxe the openblas package took several hours to build on my machine, of course it's not a problem since it's a one-time build, but nevertheless surprising to see it take several times longer to build than all the other selected packages combined.

**Comment by tonytheodore** [comment]
> cmake (FindBLAS) does not locate the openblas library

I'll add a cmake test, at the moment we just use [`pkg-config` to override `-DBLAS_LIBRARIES` etc.](https://github.com/mxe/mxe/commit/434d7aa4a453ab0a43634b0b4209891e6e17cc2b#diff-23c8a928a4389da728e703c379cdfc74)

> Would it be possible to create for instance 'netlibblas', 'netliblapack' etc

I'm happy to add them back with their current names, there's no conflicts with `openblas` (AFAIK) and I only [disabled them](https://github.com/mxe/mxe/pull/1985#issuecomment-345970677) thinking people would prefer the "optimised" versions.

> https://github.com/Reference-LAPACK/lapack-release

Nice! Thanks for the tip.

> openblas package took several hours to build

It's certainly in the top 5 pkgs for build time, I think this can be reduced with selective tuning of options, but we have to make it broadly useful ("optimised" being core2).

**Comment by ajmay81** [comment]
Thanks very much, adding them back would be great. The simple 'blas' and 'lapack' names are quite often aliases for the reference implementation anyway, certainly on my system this is the case:

https://build.opensuse.org/package/view_file/openSUSE:Factory/lapack/lapack.spec?expand=1

and other implementations such as openblas packaged by name.

For us the generated executable on Windows doesn't need to be absolutely optimal, it's a way for users to interact with a serial version of the code and run mid sized calculations on their desktop. For users that care about performance they will make a build and run on their HPC machine with local compilers, MPI libraries etc.

**Comment by ajmay81** [comment]
I tried to reinstate and update the packages, in all cases taking from the same git repo rather than netlib tarball files. I apologize if the syntax is not quite correct, and I only tested with x86_64-w64-mingw32.static target so far.

**Comment by tonytheodore** [comment]
Thanks, the netlib packages are now back in #2086 but I'll leave this open for the cmake test.

**Comment by tonytheodore** [comment]
I've added the cmake test, to find openblas add `-DBLA_VENDOR=OpenBLAS -DCMAKE_C_FLAGS=-fopenmp` to your cmake invocation.
