### ISSUE TITLE
Name of libraries from openssl package

### ISSUE THREAD

**Issue by tehnick** [mxe/mxe#2087]
Please unificate the name of libraries in openssl package.

Currently for `i686-w64-mingw32.shared` target we have:
```
libssl-1_1.dll
libcrypto-1_1.dll
```
and for `x86_64-w64-mingw32.shared` target:
```
libssl-1_1-x64.dll
libcrypto-1_1-x64.dll
```

This is non-standard naming scheme and it is very inconvenient in some use cases. (Mostly in qmake based projects and in projects which do not use autotools+pkgconfig or cmake.)

**Comment by tonytheodore** [comment]
It's not particularly easy to (find where to) change, there's no config options for it and the build system is a custom perl setup. Upstream are unlikely to change it https://github.com/openssl/openssl/issues/903, but you should ask if they could make it a configurable option.

If we changed it in MXE, that could break existing scripts that have already worked around it. The below should do what you want if you save it in a local plugin dir:

```diff
diff -ur openssl-1.1.0g/Configurations/unix-Makefile.tmpl openssl-1.1.0g.new/Configurations/unix-Makefile.tmpl
--- openssl-1.1.0g/Configurations/unix-Makefile.tmpl	2017-11-03 01:29:01.000000000 +1100
+++ openssl-1.1.0g.new/Configurations/unix-Makefile.tmpl	2018-03-22 14:24:40.000000000 +1100
@@ -40,7 +40,7 @@
      sub shlib {
          return () if $disabled{shared};
          my $lib = shift;
-         return $unified_info{sharednames}->{$lib} . $shlibext;
+         return $lib."-".$config{shlib_major}."_".$config{shlib_minor} . $shlibext;
      }
      sub shlib_simple {
          return () if $disabled{shared};
```

**Comment by tehnick** [comment]
Their argumentation just do not make any sense. It is a pity that such widespread library has a lot of issues (from maintainer point of view). Starting from very specific license...

Thank you for a such detailed answer.

**Comment by tehnick** [comment]
> Starting from very specific license...

Though I see a progress with this:
https://www.openssl.org/blog/blog/2017/03/22/license/
https://www.openssl.org/blog/blog/2018/03/01/last-license/

**Comment by tonytheodore** [comment]
Good to know they're re-licensing, I've updated the docs https://github.com/mxe/mxe/commit/b2472742bf4258db461bc9cba57b1ae2641d81a6.

**Comment by tonytheodore** [comment]
You can also use something like `peldd` #2092 so you don't have to worry about the names - if the linker managed to link it, it should be possible to extract the path and lib.
