### ISSUE TITLE
openssl src/bignum.h:57:24: error: invalid use of incomplete type 'BIGNUM {aka struct bignum_st}'

### ISSUE THREAD

**Issue by saddam1997** [mxe/mxe#2100]
Hi,

I am getting this error please help me !!!

/mnt/mxe/usr/i686-w64-mingw32.static/qt5/bin/uic src/qt/forms/optionsdialog.ui -o build/ui_optionsdialog.h
i686-w64-mingw32.static-g++ -c -pipe -fno-keep-inline-dllexport -O2 -std=gnu++11 -fdiagnostics-show-option -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DENABLE_WALLET -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DQT_DISABLE_DEPRECATED_BEFORE=0 -DUSE_UPNP=1 -DMINIUPNP_STATICLIB -DSTATICLIB -DWIN32 -D_MT -DBOOST_THREAD_PROVIDES_GENERIC_SHARED_MUTEX_ON_WIN -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -Isrc -Isrc/json -Isrc/qt -I../mxe/usr/i686-w64-mingw32.static/include -Isrc/leveldb/include -Isrc/leveldb/helpers -I../mxe/usr/i686-w64-mingw32.static/include/boost -I../mxe/usr/i686-w64-mingw32.static/include -I../mxe/usr/i686-w64-mingw32.static/include/openssl -I../mxe/usr/i686-w64-mingw32.static/qt5/include -I../mxe/usr/i686-w64-mingw32.static/qt5/include/QtWidgets -I../mxe/usr/i686-w64-mingw32.static/qt5/include/QtGui -I../mxe/usr/i686-w64-mingw32.static/qt5/include/QtNetwork -I../mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore -Ibuild -Ibuild -I../mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++  -o build/txdb-leveldb.o src/txdb-leveldb.cpp
In file included from src/script.h:18:0,
                 from src/core.h:11,
                 from src/main.h:8,
                 from src/kernel.h:7,
                 from src/txdb-leveldb.cpp:17:
src/bignum.h:57:24: error: invalid use of incomplete type 'BIGNUM {aka struct bignum_st}'
 class CBigNum : public BIGNUM
                        ^
In file included from /mnt/mxe/usr/i686-w64-mingw32.static/include/openssl/crypto.h:31:0,
                 from src/allocators.h:12,
                 from src/serialize.h:22,
                 from src/core.h:9,
                 from src/main.h:8,
                 from src/kernel.h:7,
                 from src/txdb-leveldb.cpp:17:
/mnt/mxe/usr/i686-w64-mingw32.static/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'BIGNUM {aka struct bignum_st}'
 typedef struct bignum_st BIGNUM;
                ^
In file included from src/script.h:18:0,
                 from src/core.h:11,
                 from src/main.h:8,
                 from src/kernel.h:7,
                 from src/txdb-leveldb.cpp:17:
src/bignum.h: In constructor 'CBigNum::CBigNum()':
src/bignum.h:62:21: error: 'BN_init' was not declared in this scope
         BN_init(this);
                     ^
src/bignum.h: In copy constructor 'CBigNum::CBigNum(const CBigNum&)':
src/bignum.h:67:21: error: 'BN_init' was not declared in this scope
         BN_init(this);
                     ^
src/bignum.h:68:30: error: cannot convert 'CBigNum*' to 'BIGNUM* {aka bignum_st*}' for argument '1' to 'BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)'
         if (!BN_copy(this, &b))
                              ^
src/bignum.h:70:31: error: cannot convert 'CBigNum*' to 'BIGNUM* {aka bignum_st*}' for argument '1' to 'void BN_clear_free(BIGNUM*)'
             BN_clear_free(this);
                               ^
src/bignum.h: In member function 'CBigNum& CBigNum::operator=(const CBigNum&)':
src/bignum.h:77:30: error: cannot convert 'CBigNum*' to 'BIGNUM* {aka bignum_st*}' for argument '1' to 'BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)'
         if (!BN_copy(this, &b))
                              ^
src/bignum.h: In destructor 'CBigNum::~CBigNum()':
src/bignum.h:84:27: error: cannot convert 'CBigNum*' to 'BIGNUM* {aka bignum_st*}' for argument '1' to 'void BN_clear_free(BIGNUM*)'
         BN_clear_free(this);
                           ^
src/bignum.h: In constructor 'CBigNum::CBigNum(signed char)':
src/bignum.h:88:49: error: 'BN_init' was not declared in this scope
     CBigNum(signed char n)        { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                                 ^
src/bignum.h: In constructor 'CBigNum::CBigNum(short int)':
src/bignum.h:89:49: error: 'BN_init' was not declared in this scope
     CBigNum(short n)              { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                                 ^
src/bignum.h: In constructor 'CBigNum::CBigNum(int)':
src/bignum.h:90:49: error: 'BN_init' was not declared in this scope
     CBigNum(int n)                { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                                 ^
src/bignum.h: In constructor 'CBigNum::CBigNum(long int)':
src/bignum.h:91:49: error: 'BN_init' was not declared in this scope
     CBigNum(long n)               { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                                 ^
src/bignum.h: In constructor 'CBigNum::CBigNum(long long int)':
src/bignum.h:92:49: error: 'BN_init' was not declared in this scope
     CBigNum(long long n)          { BN_init(this); setint64(n); }
                                                 ^

                           ^
bignum_st*}' for argument '1' to 'int BN_cmp(const BIGNUM*, const BIGNUM*)'
 inline bool operator>(const CBigNum& a, const CBigNum& b)  { return (BN_cmp(&a, &b) > 0); }
                                                                                   ^
Makefile.Release:11023: recipe for target 'build/txdb-leveldb.o' failed

**Comment by ivan-cbqa** [comment]
how can I fix that I am trying to cross compile blackcoin for windows 32 bits and I have the same output error :(

**Comment by saddam1997** [comment]
Hi @ivan-cbqa ,

This is error of openssl version. 
Update this file 
https://github.com/mxe/mxe/blob/master/src/openssl.mk with 
https://github.com/mxe/mxe/blob/a063f9b35279d83f692df0345d84147c0f23c992/src/openssl.mk#L6
$(PKG)_VERSION  := 1.0.2m
$(PKG)_CHECKSUM := 8c6ff15ec6b319b50788f42c7abc2890c08ba5a1cdcd3810eb9092deada3$

Replace with above and install it then this problem is solve.

**Comment by ivan-cbqa** [comment]
thanks for the reply @saddam1997  I ran it and it shows the following message:

[download]    openssl-1.0.2m.tar.gz
MXE Warning! Downloading openssl from second URL.
MXE Warning! Downloading openssl from backup.

Download failed or wrong checksum of package openssl!
------------------------------------------------------------
--2018-10-11 17:59:44--  http://d1yihgixbnrglp.cloudfront.net/openssl%2D1%2E0%2E2m%2Etar%2Egz_8c6ff15ec6b319b50788f42c7abc2890c08ba5a1cdcd3810eb9092deada3
Resolving d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)... 13.33.80.177, 13.33.80.90, 13.33.80.95, ...
Connecting to d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)|13.33.80.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-11 17:59:44 ERROR 404: Not Found.
Download failed!
------------------------------------------------------------
[log]      /home/debian/mxe/log/openssl-download

Makefile:651: recipe for target 'download-only-openssl-1.0.2m.tar.gz' failed
make: *** [download-only-openssl-1.0.2m.tar.gz] Error 1

How did you get that Checksum?

I am trying to build blackcoin for windows 32 bit

**Comment by ivan-cbqa** [comment]
thanks for the reply @saddam1997 I tried it and the following message appears:

[download]    openssl-1.0.2m.tar.gz
MXE Warning! Downloading openssl from second URL.
MXE Warning! Downloading openssl from backup.

Download failed or wrong checksum of package openssl!
------------------------------------------------------------
--2018-10-11 17:59:44--  http://d1yihgixbnrglp.cloudfront.net/openssl%2D1%2E0%2E2m%2Etar%2Egz_8c6ff15ec6b319b50788f42c7abc2890c08ba5a1cdcd3810eb9092deada3
Resolving d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)... 13.33.80.177, 13.33.80.90, 13.33.80.95, ...
Connecting to d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)|13.33.80.177|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-11 17:59:44 ERROR 404: Not Found.
Download failed!
------------------------------------------------------------
[log]      /home/debian/mxe/log/openssl-download

Makefile:651: recipe for target 'download-only-openssl-1.0.2m.tar.gz' failed
make: *** [download-only-openssl-1.0.2m.tar.gz] Error 1


Trying to buid blackcoin for windows 32 bits using debian jessie
