### ISSUE TITLE
Failed to build package libotr for target i686-w64-mingw32.static!

### ISSUE THREAD

**Issue by Caysho** [mxe/mxe#2102]
Log uploaded to gist:
https://gist.github.com/Caysho/22043eb88e181e953b5de4371ee6a839

**Comment by tonytheodore** [comment]
Looks like the [latest libgpg_error update](https://github.com/mxe/mxe/commit/f0dd16d059c87f6592f6a3fa67cd44a75f9a4434) also needs `-lws2_32` added to the *.pc file
