### ISSUE TITLE
Update to GStreamer 1.14

### ISSUE THREAD

**Issue by epozuelo** [mxe/mxe#2107]
Please update GStreamer packages to 1.14 (newest stable release). With 1.12, linking static plugins was broken. First, one needed to build with --disable-shared --enable-static-plugins (IIRC), but even then things were not working. With 1.14 this is all working fine thanks to this commit:

https://cgit.freedesktop.org/gstreamer/gstreamer/commit/?id=e7ede5a487d8c1571a4387a5f8eeb4d5e73a9553

**Comment by tonytheodore** [comment]
see #2111
