### ISSUE TITLE
Qt5 and QtMultimediaQuick

### ISSUE THREAD

**Issue by jaytea** [mxe/mxe#2109]
For my current project I need the multimedia qml items, but unfortunately, they are apparently missing in my MXE build.
I'm building mxe with `make qt5 qtdeclarative qtmultimedia` but I'm still missing the QtMultimediaQuick.dll and the QtMultimedia-folder in qt5/qml.

**Comment by mabrand** [comment]
Please pull and try again. Commit 
b7a259364702e029d422f0f2757c1bb167e708b8 should fix it.

Mark

**Comment by jaytea** [comment]
Thank you, that did it!
