### ISSUE TITLE
MXE GCC4 Plugin

### ISSUE THREAD

**Issue by giftcoinofficial** [mxe/mxe#2116]
Hello everyone, I have tried compiling a crypto-currency wallet for my project. Before, the old version of MXE was installed on my other server and I was able to compile .exe without any problem. 

However, right now, since the MXE has updated the built-in GCC to 5.4, I am not able to compile my project because of syntax changes. So, I want to use GCC4 plugin, instead of built-in GCC 5.4. However, I am not able to run this plugin and compile my project with GCC4 plugin.

Can someone please help me use GCC4 on my project instead of GCC 5.4? I have tried using older releases, however, then I can't compile the MXE for Boost / QTTools, because some dependencies on the older builds no longer exists.

**Comment by PsychoXIVI** [comment]
> I am not able to run this plugin

...why? Any logs or something?

**Comment by tonytheodore** [comment]
These packages (and any dependents) are failing on gcc4, notably `qtbase`:
```
fluidsynth
libsignal-protocol-c
libtasn1
libzmq
llvm
poco
primesieve
qtbase
sdl2_mixer
wt
```
You won't get very far with this.
