### ISSUE TITLE
db utilities fails to install

### ISSUE THREAD

**Issue by e-nexus** [mxe/mxe#2122]
When using:

echo 'override MXE_PLUGIN_DIRS += plugins/gcc8' >> settings.mk
make MXE_TARGETS=x86_64-w64-mingw32.static.posix db

it fails with:

Installing DB utilities: /home/varg/dev/exp/mxe/usr/x86_64-w64-mingw32.static.posix/bin ...
libtool: install: cp -p db_archive /home/varg/dev/exp/mxe/usr/x86_64-w64-mingw32.static.posix/bin/db_archive.exe
cp: cannot stat 'db_archive': No such file or directory
x86_64-w64-mingw32.static.posix-strip: '/home/varg/dev/exp/mxe/usr/x86_64-w64-mingw32.static.posix/bin/db_archive.exe': No such file
chmod: cannot access '/home/varg/dev/exp/mxe/usr/x86_64-w64-mingw32.static.posix/bin/db_archive.exe': No such file or directory

etc...

**Comment by PsychoXIVI** [comment]
Can you post whole log (from `mxe/log` folder)?? It should be named as package and target name.

Anyway, I suppose that it is all about extension - sometimes executables are compiled with `.exe`, but script tries to copy them, but without extension.

**Comment by PsychoXIVI** [comment]
I do not fully understand: How files are being built? With extension `.exe` or without? 

If you are not sure, could you check for example `/home/varg/dev/exp/mxe/tmp-db-x86_64-w64-mingw32.static.posix/db-6.1.26/build_unix/db_verify` is this file has `.exe` or no extension? (I could mess up with the path, but I hope you will find it anyway).

Of course I just suppose this, I may not be right. I just have similar situation while building Lua while using GCC 8 plugin.

**Comment by e-nexus** [comment]
With .exe extension.
