### ISSUE TITLE
qtbase fails to build

### ISSUE THREAD

**Issue by jaytea** [mxe/mxe#2125]
I currently always get a build error when trying to build qtbase, apparently no matter with which settings. This is the log: https://gist.github.com/jaytea/dd56d8a617841ac16c1ff349d0c7bbe8

**Comment by tonytheodore** [comment]
Looks similar to #1956 but I can't see any odd characters.

**Comment by jaytea** [comment]
Yes, I saw that one but, as you said, I don't have any special characters in the path name.
I just made some more tests. The problem might be my setup, it's in a docker on an Arch Linux host system. I tried Ubuntu and Arch as guest systems, but both throw this error.
The same ubuntu docker on a Debian Linux host system works just fine. So it might be a problem with my Arch system.

**Comment by jaytea** [comment]
Ok, my bad. It looks like this error was produced by my system being slightly outdated. I had a conflict in my packages which lead to the package manager ui not giving me a hint to update and I just forgot. 
Now I upgraded all packages and it's working again.
