### ISSUE TITLE
sh: 1: i686-w64-mingw32.static-g++: not found 

### ISSUE THREAD

**Issue by number435398** [mxe/mxe#2126]
when trying to run /mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake I get:

> Project ERROR: Cannot run target compiler 'i686-w64-mingw32.static-g++', Output:
===============
sh: 1: i686-w64-mingw32.static-g++: not found
===============
Maybe you forgot to setup the environment?

**Comment by tonytheodore** [comment]
Did you add `/mxe/usr/bin` to your `PATH`?

**Comment by VtpVlan-oo7** [comment]
@tonytheodore 
 yes  I add this    /mnt/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5

how to resolve this error please help me to fix it.

**Comment by tonytheodore** [comment]
```
export PATH=/mnt/mxe/usr/bin:$PATH
```
and retry.

**Comment by VtpVlan-oo7** [comment]
@tonytheodore 
i still got the same errror when i use 

$sudo ./compile-blk.sh 
Project ERROR: Cannot run target compiler 'i686-w64-mingw32.static-g++'. Output:
===================
sh: 1: i686-w64-mingw32.static-g++: not found
===================
Maybe you forgot to setup the environment?
make: Makefile.Release: No such file or directory
make: *** No rule to make target 'Makefile.Release'.  Stop.

**Comment by tonytheodore** [comment]
Now you're using a different command and there seems to be a new error (`Makefile.Release: No such file or directory`).

Across the board, mxe doesn't `sudo` unless you know you've installed mxe in a way that somehow requires it - that's very unlikely so avoid trying that.

What project are you trying to build? Can you share the contents of `compile-blk.sh`?

**Comment by VtpVlan-oo7** [comment]
@tonytheodore  

I am trying to build a linux cryptocoin for windows in which QT 5.5 is used.and for that we are using the link ->                 https://bitcointalk.org/index.php?topic=1080289.0


file $./compile-blk.sh content


#!/bin/bash
MXE_INCLUDE_PATH=/mnt/mxe/usr/i686-w64-mingw32.static/include
MXE_LIB_PATH=/mnt/mxe/usr/i686-w64-mingw32.static/lib

i686-w64-mingw32.static-qmake-qt5 \
	BOOST_LIB_SUFFIX=-mt \
	BOOST_THREAD_LIB_SUFFIX=_win32-mt \
	BOOST_INCLUDE_PATH=$MXE_INCLUDE_PATH/boost \
	BOOST_LIB_PATH=$MXE_LIB_PATH \
	OPENSSL_INCLUDE_PATH=$MXE_INCLUDE_PATH/openssl \
	OPENSSL_LIB_PATH=$MXE_LIB_PATH \
	BDB_INCLUDE_PATH=$MXE_INCLUDE_PATH \
	BDB_LIB_PATH=$MXE_LIB_PATH \
	MINIUPNPC_INCLUDE_PATH=$MXE_INCLUDE_PATH \
	MINIUPNPC_LIB_PATH=$MXE_LIB_PATH \
	QMAKE_LRELEASE=/mnt/mxe/usr/i686-w64-mingw32.static/qt5/bin/lrelease blackcoin-qt.pro

make -f Makefile.Release

**Comment by tonytheodore** [comment]
I can't think of anything, if invoking `i686-w64-mingw32.static-qmake-qt5` works, then `i686-w64-mingw32.static-g++` should be found as it's in the same directory.

**Comment by tonytheodore** [comment]
What's the output of:
```
which i686-w64-mingw32.static-qmake-qt5
```

**Comment by tonytheodore** [comment]
Is `i686-w64-mingw32.static-g++` in that directory (`/mnt/mxe/usr/bin`)?

**Comment by tonytheodore** [comment]
Ahh, the ` Cannot run target compiler` may be significant - did you build it on a difference machine with (say) a different glibc?

**Comment by VtpVlan-oo7** [comment]
@tonytheodore 

yeah this is in the same directory
i686-w64-mingw32.static-g++ in that directory (/mnt/mxe/usr/bin)

**Comment by VtpVlan-oo7** [comment]
we got this error

Project ERROR: Unknown module(s) in QT: webkitwidgets
make: Makefile.Release: No such file or directory
make: *** No rule to make target 'Makefile.Release'. Stop

**Comment by tonytheodore** [comment]
> Project ERROR: Unknown module(s) in QT: webkitwidgets

There's no immediate solution to this, see #2070.

**Comment by tonytheodore** [comment]
Indeed, using those and `MXE_TARGETS := i686-w64-mingw32.shared.posix` should solve it.
