### ISSUE TITLE
gettext not building on MacOS

### ISSUE THREAD

**Issue by markghayden** [mxe/mxe#2142]
We've been using MXE on MacOS for several years.  For some time now, gettext does not build.  I can't make sense of what the root problem in the build is.

Below is link to log file:

https://gist.github.com/markghayden/92180a74d54cb0982e213b460256d5ed

**Comment by tonytheodore** [comment]
From https://github.com/mxe/mxe/commit/f4751046f70915c1689fe323f6d12a1b6206dbc6#commitcomment-29522032

> Can you confirm if you can still build gettext on MacOS host?

Yes, I can confirm that it builds with the same versions of gcc (Apple LLVM version 9.1.0 (clang-902.0.39.2)) and MacOS (17.6.0) from the log.

Unfortunately, I can't see anything in the log other than picking up `/usr/lib/libiconv.la` for some reason.

**Comment by markghayden** [comment]
Thanks for confirming the build is working for you.

I agree the issue seems to be that /usr/lib/libiconv.la is being picked up.  I can't figure out why libtool is doing this.  I just tried again a fresh build and gettext is still not building, for same reason.

I'm using Homebrew for the MacOS build environment.  What are you using?

Is there any other information I can collect to help diagnose this issue?

**Comment by tonytheodore** [comment]
I'm using Macports and I imagine Homebrew is shadowing the standard libiconv*.dylib:
```
$ ll /usr/lib/libiconv*
lrwxr-xr-x  1 root  wheel    16B 28 Sep  2017 /usr/lib/libiconv.2.4.0.dylib -> libiconv.2.dylib
-r-xr-xr-x  1 root  wheel   2.0M 28 Mar 15:02 /usr/lib/libiconv.2.dylib
lrwxr-xr-x  1 root  wheel    20B 28 Sep  2017 /usr/lib/libiconv.dylib -> libiconv.2.4.0.dylib
```
From memory, `brew link` may have something to do with it - see #2053.

**Comment by tonytheodore** [comment]
Actually, that doesn't make sense either, Homebrew installs to `/usr/local/lib` doesn't it?

**Comment by tonytheodore** [comment]
That won't work, forgot the `.gnu` suffix and setting `--prefix` should have the same effect.

Can you try adding `--with-included-libcroco` instead? I'm pretty sure there's a `/usr/local/lib/libcroco-0.6.la` file which hardcodes the location of `libiconv`.

**Comment by markghayden** [comment]
Thanks for the suggestion.  '--with-included-libcroco' seems to have fixed the problem.  The MXE build is now continuing past gettext.  Thanks!

**Comment by tonytheodore** [comment]
Good to hear, the only package failing on Darwin at the moment is `llvm` #2106.
