### ISSUE TITLE
build-only-qtbase_x86_64-w64-mingw32.static build failure

### ISSUE THREAD

**Issue by vranki** [mxe/mxe#2148]
Built in Ubuntu 18.04.

Could not find qmake spec ''.

Full log: https://gist.github.com/vranki/42fad379de6ab6956ed8d4a674c22ba7

**Comment by vranki** [comment]
..and the build command was make MXE_TARGETS=x86_64-w64-mingw32.static qt5

**Comment by ashkulz** [comment]
are you running it inside docker? There's a bug in it, so you need to use `--privileged` or upgrade to official docker.

**Comment by vranki** [comment]
Yep, inside docker. It seems weird that compiling something in userspace is affected by running in a container. Is this a bug in mxe, Qt or docker?

**Comment by ashkulz** [comment]
It's a bug in Docker, see https://bugreports.qt.io/browse/QTBUG-66930

**Comment by vranki** [comment]
Thanks. I'll close this issue as it's not mxe. Hopefully this will start working by itself when docker is fixed.

**Comment by ashkulz** [comment]
@vranki: you just have to update docker (use official CE packages) or use the flags mentioned in that issue.

**Comment by xSke** [comment]
Which version of Docker has the fix for this? It's broken on what appears to be the latest version (18.05.0-ce).
