### ISSUE TITLE
mxe build of isl fails due to automake

### ISSUE THREAD

**Issue by yanbuatois** [mxe/mxe#2155]
Hello, 
I tried to make mxe to compile a qt software for Windows, but I had a problem. When typing make qt, the installation of isl fails always.

According to the log (https://gist.github.com/dracoctix/1912983d7f6ec5d490b889ee68933a8f), I haven't automake-1.14.1, which is needed, and it's true, I haven't this version of automake, but I have the 1.15.1.
I tried various workaround to avoid this problem (from symlink to try to change the isl version), but none solution worked, and I don't know how I can fix the problem, knowing that I cannot install the 1.14.1 (I have ArchLinux, I tried to install from AUR and compile from sources, but in these two cases, it fails, and it can, apparently, not being fixed.

So can you help me to solve this issue, and compile mxe without problem, pls ?
Thx by advance =)

**Comment by PsychoXIVI** [comment]
There is dirty way to solve the problem:
https://github.com/UBERTC/isl/issues/1#issuecomment-167342197

**Comment by dracoctix** [comment]
Hello, thanks for your reply ^^
I saw this during my searchs about that problem, but when I try this, the build fails another time, but with a different error https://gist.github.com/dracoctix/38c5c1a446496fd8554bf9b722dbb77e

**Comment by tonytheodore** [comment]
Could you try:
``` 
make libtool MXE_PLUGIN_DIRS=plugins/native MXE_TARGETS=`ext/config.guess`
```
and try again? It will build a known working set of autotools, though I'm not sure why `automake` would be invoked at all given none of the input files have changed. It could be that the filesystem on `/data` has a timestamp issues, similar to https://github.com/mxe/mxe/issues/1892#issuecomment-343726260. In that case:
```
make qt MXE_TMP=~/mxe-tmp
```
may work.
