### ISSUE TITLE
cmake on void linux

### ISSUE THREAD

**Issue by kasymovga** [mxe/mxe#2156]
on void linux cmake build failed without --system-curl option.
i think internal curl not compatible with libressl from void linux.

maybe it better add --system-curl to cmake.mk

**Comment by tonytheodore** [comment]
I'll see if we can disable curl altogether since we never want our cmake to download anything.

**Comment by basiliscos** [comment]
@tonytheodore any update on this?

**Comment by tonytheodore** [comment]
I haven't had a chance to look at it yet, but my previous comment is incorrect. While mxe is building, we don't want cmake to download anything, but outside of that it should be up to the project if they want to use such features. I've finally got docker set up properly so should be able to test with the [void image](https://hub.docker.com/r/voidlinux/voidlinux/).

As an aside, do you have the prerequisite install commands for void we can add to the [docs](https://mxe.cc/#requirements)?

**Comment by basiliscos** [comment]
I cannot remember all requirements, but here are what I installed into my `void` to let mxe work:

```
flex
gettext-devel
gperf
intltool
ruby
gettext
perl-XML-Parser
```

**Comment by kasymovga** [comment]
Your docker image is outdated, current libressl version is 2.7.4
`$ openssl version
LibreSSL 2.7.4`

For vanilla cmake 3.10.0 build failed this way: https://gist.github.com/kasymovga/2a4cdeb0616ccdf85b4bebbbe4a2a4ca

**Comment by kasymovga** [comment]
For latest MXE:
https://gist.github.com/kasymovga/c8513973e1809df571e0177c12f7a169

**Comment by tonytheodore** [comment]
Still succeeds after `xbps-install -Su` and latest libressl:
```
# openssl version
LibreSSL 2.7.4
```
Can you post the full log?

**Comment by kasymovga** [comment]
https://gist.github.com/kasymovga/7f2b609e07d5790602028ee2759dcafa

**Comment by tonytheodore** [comment]
Okay, it needed the `libressl-devel` pkg to trigger the issue.
