### ISSUE TITLE
Failed to build package libao for target i686-w64-mingw32.static!

### ISSUE THREAD

**Issue by wexi** [mxe/mxe#2157]
mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2/src/plugins/pulse/ao_pulse.c:35:30: fatal error: pulse/pulseaudio.h: No such file or directory
compilation terminated.
Makefile:464: recipe for target 'ao_pulse.lo' failed

**Comment by PsychoXIVI** [comment]
Please provide full logs of this package build process. You can find them in `mxe/log` folder named as package and target name.

**Comment by orrinjelo** [comment]
I've gotten the same error; perhaps my log can be of help.
`make[1]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe'
uname -a
Linux Lothlorien 4.9.86-1-MANJARO #1 SMP PREEMPT Sun Mar 4 21:54:39 UTC 2018 x86_64 GNU/Linux
git log --pretty=tformat:"%H - %s [%ar] [%d]" -1
a37bce64dbca8b73b381860a595495c5335a359a - Update packages.json & build-matrix.html [6 days ago] [ (HEAD -> master, origin/master, origin/HEAD)]
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.1.6
Codename:	Hakoila
autoconf --version 2>/dev/null | head -1
autoconf (GNU Autoconf) 2.69
automake --version 2>/dev/null | head -1
automake (GNU automake) 1.15.1
gcc --version
gcc (GCC) 6.4.1 20171003
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version
g++ (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

python --version
Python 3.6.4
perl --version 2>&1 | head -3

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-thread-multi

rm -rf   '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static'
mkdir -p '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static'
mkdir -p '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2'
mkdir -p '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_'
# disable wine with readonly directory
# see https://github.com/mxe/mxe/issues/841
mkdir -p '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/readonly'
chmod 0555 '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/readonly'
cd '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static' &&  tar xzf '/home/orrinjelo/git/libreueldrd-builds/mxe/pkg/libao-1.2.2.tar.gz'
cd '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2'
cd '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2' && ./autogen.sh
Updating build configuration files for libao, please wait....
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:35: installing './compile'
configure.ac:24: installing './config.guess'
configure.ac:24: installing './config.sub'
configure.ac:4: installing './install-sh'
configure.ac:4: installing './missing'
src/Makefile.am: installing './depcomp'
cd '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_' && /home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2/configure --host='i686-w64-mingw32.static' --build='x86_64-pc-linux-gnu' --prefix='/home/orrinjelo/git/libreueldrd-builds/mxe/usr/i686-w64-mingw32.static'  --enable-static --disable-shared  ac_cv_prog_HAVE_DOXYGEN="false" --enable-doc=no --enable-gtk-doc=no --enable-gtk-doc-html=no --enable-gtk-doc-pdf=no --{docdir,infodir,mandir,with-html-dir}='/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_.sink' --disable-doxygen --disable-esd --enable-wmm LIBS=-lksuser
configure: WARNING: unrecognized options: --enable-doc, --enable-gtk-doc, --enable-gtk-doc-html, --enable-gtk-doc-pdf, --with-html-dir, --disable-doxygen
configure: loading site script /home/orrinjelo/git/libreueldrd-builds/mxe/usr/i686-w64-mingw32.static/share/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i686-w64-mingw32.static-strip... i686-w64-mingw32.static-strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking build system type... (cached) x86_64-pc-linux-gnu
checking host system type... i686-w64-mingw32.static
checking for i686-w64-mingw32.static-gcc... i686-w64-mingw32.static-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether i686-w64-mingw32.static-gcc accepts -g... yes
checking for i686-w64-mingw32.static-gcc option to accept ISO C89... none needed
checking whether i686-w64-mingw32.static-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of i686-w64-mingw32.static-gcc... gcc3
checking for i686-w64-mingw32.static-as... i686-w64-mingw32.static-as
checking for i686-w64-mingw32.static-dlltool... i686-w64-mingw32.static-dlltool
checking for i686-w64-mingw32.static-objdump... i686-w64-mingw32.static-objdump
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by i686-w64-mingw32.static-gcc... /home/orrinjelo/git/libreueldrd-builds/mxe/usr/bin/i686-w64-mingw32.static-ld
checking if the linker (/home/orrinjelo/git/libreueldrd-builds/mxe/usr/bin/i686-w64-mingw32.static-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /home/orrinjelo/git/libreueldrd-builds/mxe/usr/bin/i686-w64-mingw32.static-nm -B
checking the name lister (/home/orrinjelo/git/libreueldrd-builds/mxe/usr/bin/i686-w64-mingw32.static-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to i686-w64-mingw32.static format... func_convert_file_nix_to_w32
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /home/orrinjelo/git/libreueldrd-builds/mxe/usr/bin/i686-w64-mingw32.static-ld option to reload object files... -r
checking for i686-w64-mingw32.static-objdump... (cached) i686-w64-mingw32.static-objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for i686-w64-mingw32.static-dlltool... (cached) i686-w64-mingw32.static-dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for i686-w64-mingw32.static-ar... i686-w64-mingw32.static-ar
checking for archiver @FILE support... @
checking for i686-w64-mingw32.static-strip... (cached) i686-w64-mingw32.static-strip
checking for i686-w64-mingw32.static-ranlib... i686-w64-mingw32.static-ranlib
checking command to parse /home/orrinjelo/git/libreueldrd-builds/mxe/usr/bin/i686-w64-mingw32.static-nm -B output from i686-w64-mingw32.static-gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for i686-w64-mingw32.static-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... i686-w64-mingw32.static-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if i686-w64-mingw32.static-gcc supports -fno-rtti -fno-exceptions... no
checking for i686-w64-mingw32.static-gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if i686-w64-mingw32.static-gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if i686-w64-mingw32.static-gcc static flag -static works... yes
checking if i686-w64-mingw32.static-gcc supports -c -o file.o... yes
checking if i686-w64-mingw32.static-gcc supports -c -o file.o... (cached) yes
checking whether the i686-w64-mingw32.static-gcc linker (/home/orrinjelo/git/libreueldrd-builds/mxe/usr/bin/i686-w64-mingw32.static-ld) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for dlfcn.h... (cached) yes
checking for library containing dlopen... no
checking if libraries can be versioned... yes
checking for pthread_kill in -lpthread... yes
checking size of short... 2
checking size of int... 4
checking size of long... 4
checking for mmsystem.h... yes
checking waveOut family functions... yes
checking sys/soundcard.h usability... no
checking sys/soundcard.h presence... no
checking for sys/soundcard.h... no
checking machine/soundcard.h usability... no
checking machine/soundcard.h presence... no
checking for machine/soundcard.h... no
checking for snd_pcm_open in -lasound... no
checking alsa/asoundlib.h usability... no
checking alsa/asoundlib.h presence... no
checking for alsa/asoundlib.h... no
checking sys/audioio.h usability... no
checking sys/audioio.h presence... no
checking for sys/audioio.h... no
checking sndio.h usability... no
checking sndio.h presence... no
checking for sndio.h... no
checking libroar/config.h usability... no
checking libroar/config.h presence... no
checking for libroar/config.h... no
checking for artsc-config... no
checking for X... libraries /usr/lib, headers /usr/include
checking whether -R must be followed by a space... neither works
checking for dnet_ntoa in -ldnet... no
checking for dnet_ntoa in -ldnet_stub... no
checking for gethostbyname... no
checking for gethostbyname in -lnsl... no
checking for gethostbyname in -lbsd... no
checking for connect... no
checking for connect in -lsocket... no
checking for remove... yes
checking for shmat... no
checking for shmat in -lipc... no
checking for IceConnectionNumber in -lICE... no
checking for XauFileName in -lXau... no
checking for AuOpenServer in -laudio... no
checking audio/audiolib.h usability... no
checking audio/audiolib.h presence... no
checking for audio/audiolib.h... no
checking for pkg-config... /usr/bin/pkg-config
checking for  libpulse-simple >= 0.9 ... yes
checking PULSE_CFLAGS... -D_REENTRANT
checking PULSE_LIBS... -lpulse-simple -lpulse
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating include/Makefile
config.status: creating include/ao/Makefile
config.status: creating include/ao/os_types.h
config.status: creating src/plugins/Makefile
config.status: creating src/plugins/esd/Makefile
config.status: creating src/plugins/oss/Makefile
config.status: creating src/plugins/alsa/Makefile
config.status: creating src/plugins/sun/Makefile
config.status: creating src/plugins/irix/Makefile
config.status: creating src/plugins/arts/Makefile
config.status: creating src/plugins/macosx/Makefile
config.status: creating src/plugins/nas/Makefile
config.status: creating src/plugins/pulse/Makefile
config.status: creating src/plugins/sndio/Makefile
config.status: creating src/plugins/roar/Makefile
config.status: creating ao.pc
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: unrecognized options: --enable-doc, --enable-gtk-doc, --enable-gtk-doc-html, --enable-gtk-doc-pdf, --with-html-dir, --disable-doxygen

------------------------------------------------------------------------
  libao 1.2.2:  Automatic configuration OK.

  Backends to be built:

    AU file output: .............. yes
    RAW file output: ............. yes
    WAV file output: ............. yes

    AIX live output: ............. no
    ALSA live output: ............ no
    ARTS live output: ............ no
    ESD live output: ............. no
    IRIX live output: ............ no
    MACOSX live output: .......... no
    NAS live output: ............. no
    NULL live output: ............ yes
    OSS live output: ............. no
    PULSE live output: ........... yes
    ROAR live output: ............ no
    SNDIO live output: ........... no
    SUN live output: ............. no
    Windows WMM live output: ..... yes

  Installation paths:

    libao: ....................... /home/orrinjelo/git/libreueldrd-builds/mxe/usr/i686-w64-mingw32.static/lib
    C header files: .............. /home/orrinjelo/git/libreueldrd-builds/mxe/usr/i686-w64-mingw32.static/include/ao
    Documentation: ............... /home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_.sink

  Building:

    Type 'make' to compile libao.

    Type 'make install' to install libao.

------------------------------------------------------------------------

/usr/bin/make -C '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_' -j '4' bin_PROGRAMS= sbin_PROGRAMS= noinst_PROGRAMS=
make[2]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_'
Making all in src
make[3]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src'
Making all in plugins
make[4]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins'
Making all in oss
make[5]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/oss'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/oss'
Making all in esd
make[5]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/esd'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/esd'
Making all in arts
make[5]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/arts'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/arts'
Making all in alsa
make[5]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/alsa'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/alsa'
Making all in sun
make[5]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/sun'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/sun'
Making all in irix
make[5]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/irix'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/irix'
Making all in macosx
make[5]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/macosx'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/macosx'
Making all in nas
make[5]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/nas'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/nas'
Making all in pulse
make[5]: Entering directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/pulse'
  CC       ao_pulse.lo
/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2/src/plugins/pulse/ao_pulse.c:35:30: fatal error: pulse/pulseaudio.h: No such file or directory
compilation terminated.
make[5]: *** [Makefile:463: ao_pulse.lo] Error 1
make[5]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins/pulse'
make[4]: *** [Makefile:382: all-recursive] Error 1
make[4]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src/plugins'
make[3]: *** [Makefile:536: all-recursive] Error 1
make[3]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_/src'
make[2]: *** [Makefile:561: all-recursive] Error 1
make[2]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe/tmp-libao-i686-w64-mingw32.static/libao-1.2.2.build_'
make[1]: *** [Makefile:806: build-only-libao_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory '/home/orrinjelo/git/libreueldrd-builds/mxe'

real	0m15.906s
user	0m8.943s
sys	0m1.233s
`

It says it's having issue finding `pulse/pulseaudio.h` as @wexi pointed out.  When I have a workaround or solution, I'll post it here.

**Comment by orrinjelo** [comment]
I ended up disabling pulse audio in mxe/src/libao.mk:
```
# This file is part of MXE. See LICENSE.md for licensing information.

PKG             := libao
$(PKG)_WEBSITE  := https://www.xiph.org/ao/
$(PKG)_DESCR    := AO
$(PKG)_IGNORE   :=
$(PKG)_VERSION  := 1.2.2
$(PKG)_CHECKSUM := df8a6d0e238feeccb26a783e778716fb41a801536fe7b6fce068e313c0e2bf4d
$(PKG)_GH_CONF  := xiph/libao/tags
$(PKG)_DEPS     := cc

define $(PKG)_BUILD
    cd '$(SOURCE_DIR)' && ./autogen.sh
    cd '$(BUILD_DIR)' && $(SOURCE_DIR)/configure \
        $(MXE_CONFIGURE_OPTS) \
        --enable-pulse=no \
        --disable-esd \
        --enable-wmm \
        LIBS=-lksuser
    $(MAKE) -C '$(BUILD_DIR)' -j '$(JOBS)' bin_PROGRAMS= sbin_PROGRAMS= noinst_PROGRAMS=
    $(MAKE) -C '$(BUILD_DIR)' -j 1 install bin_PROGRAMS= sbin_PROGRAMS= noinst_PROGRAMS=

    # compile test
    '$(TARGET)-gcc' \
        -W -Wall \
        '$(SOURCE_DIR)/doc/ao_example.c' -o \
        '$(PREFIX)/$(TARGET)/bin/test-$(PKG).exe' \
        `'$(TARGET)-pkg-config' ao --cflags --libs`
endef
```

Not sure if this is the best way, but at least it moved me forward.

**Comment by tonytheodore** [comment]
Thanks - AFAIK, `pulse` doesn't work on Windows so disabling it seems right. 

The log does look a little suspicious:
```
checking for pkg-config... /usr/bin/pkg-config
```
and
```
gcc --version
gcc (GCC) 6.4.1 20171003
[...]
g++ --version
g++ (GCC) 7.3.0
```
The first would be why it's detecting a native pulse install.
