### ISSUE TITLE
Qt5: RCC cannot find anything

### ISSUE THREAD

**Issue by juzzlin** [mxe/mxe#2159]
I'm running MXE inside a Ubuntu 18.04 Docker container and Qt5 works very oddly (the image is juzzlin/mxe-qt5 and mxe is in /opt/mxe).

(For some reason I need to specify the exact project file which is also weird):

$ mkdir build && cd build
$ /opt/mxe/usr/i686-w64-mingw32.static/qt5/bin/qmake ../project.pro 

```
Project MESSAGE: Building for Qt version 5.11.1.
Project MESSAGE: Building for Qt version 5.11.1.
Project MESSAGE: Building for Qt version 5.11.1.
RCC: Error in '../data/images/images.qrc': Cannot find file 'about.png'
RCC: Error in '../data/images/images.qrc': Cannot find file 'add.png'
RCC: Error in '../data/images/images.qrc': Cannot find file 'colors.png'
RCC: Warning: No resources in '../data/images/images.qrc'.

```

It builds otherwise ok, but fails due to these "missing" resource files. There's nothing special in the resource files:

```
<RCC>
    <qresource prefix="/">
        <file>about.png</file>
        <file>add.png</file>
        <file>colors.png</file>
    </qresource>
</RCC>
```

This same build works on the host with default Qt tools in the same way. I also failed to build the project with the CMake wrapper.

I'm not actually sure if Docker has anything to do with this. I'll compile MXE also for my host machine and try that also now.

**Comment by juzzlin** [comment]
This seem to work ok with both qmake and cmake when I build on my host machine, which is great. It's still weird that this fails in Docker because I have built qt5 and MXE itself inside this same container..

**Comment by juzzlin** [comment]
This was about running docker with --privileged and it worked.

**Comment by simonschmeisser** [comment]
see here for more info: https://github.com/docker/for-linux/issues/208
