### ISSUE TITLE
Failed to build package gnutls for target x86_64-w64-mingw32.static!

### ISSUE THREAD

**Issue by crobarcro** [mxe/mxe#2161]
Build log below:

https://gist.github.com/crobarcro/32288392b301866ea8de135f672f74c3

error is:

```
autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac
               file requires the infrastructure from gettext-0.19 but this version
               is older. Please upgrade to gettext-0.19 or newer.
```

I'm using:

```
commit a37bce64dbca8b73b381860a595495c5335a359a
Author: MXEBot as Travis CI <mxebot@gmail.com>
Date:   Fri Jun 22 22:28:25 2018 +0000

    Update packages.json & build-matrix.html
```

**Comment by crobarcro** [comment]
I did 

`make gettext MXE_PLUGIN_DIRS=plugins/native/ MXE_TARGETS=`

based on what I saw here: https://github.com/mxe/mxe/pull/1342

then I was able to build gnutls

**Comment by PeterTillema** [comment]
Then update [gettext](https://www.gnu.org/software/gettext/), download the `.tar.gz`, unpack it and read README how to install it. You can also download precompiled binaries for Windows if that's your Operating System.

**Comment by tonytheodore** [comment]
The cross build of `gettext` now depends on the native build - it's better to keep the native and cross versions in sync since we always build gettext (#1943 and https://github.com/mxe/mxe/commit/f4751046f)

**Comment by crobarcro** [comment]
I think it's nicer to not have to depend on system gettext, thanks
