### ISSUE TITLE
zstd pkg-config filename does not match native

### ISSUE THREAD

**Issue by Hello71** [mxe/mxe#2164]
there is a mismatch of "lib" prefix on the file.

I filed https://github.com/facebook/zstd/pull/1203 to just have them install it, but I guess they want everyone to sign CLA, so either someone from MXE can sign it, or MXE can rename its installed file (or MXE can patch it downstream, but that's kinda ugly).

**Comment by tonytheodore** [comment]
Thanks, I don't have time to look at the CLA and it's a small enough patch.
