### ISSUE TITLE
CMake: undefined reference to `qt_static_plugin_QWindowsIntegrationPlugin()'

### ISSUE THREAD

**Issue by juzzlin** [mxe/mxe#2166]
I have build my application against a statically linked Qt 5.11 with the CMake wrapper. However, when I try to run the application on Windows I get: `"This application failed to start because no Qt platform plugin could be initialized."`

After some desperate googling I guess that I need to add:

`#include <QtPlugin>`

`Q_IMPORT_PLUGIN(QWindowsIntegrationPlugin)`

...but this leads to this `undefined reference to qt_static_plugin_QWindowsIntegrationPlugin()` when building the application. 

How should I do this with CMake? Running the application on Windows has worked before without doing anything so I guess something has changed in the recent Qt versions.

**Comment by tonytheodore** [comment]
You need to add a few lines to your CMakeLists.txt, something like:
```
    add_definitions(-DQT_STATICPLUGIN)
    target_link_libraries({target} Qt5PlatformSupport Qt5::Gui)
```

I have some wip on this in #1645 that I'll try to have a look at again soon.

**Comment by juzzlin** [comment]
Ok. How do you make CMake find `Qt5PlatformSupport` ? I tried `find_package(Qt5PlatformSupport REQUIRED)` but it didn't work.
