### ISSUE TITLE
How to handle down site for dependencies? (For bzip2)

### ISSUE THREAD

**Issue by Gjacquenot** [mxe/mxe#2176]
I try to build boost with mxe with the following command

    make TARGET=x86_64-w64-mingw32.static.posix boost

It depends on bzip2, that is first downloaded but bzip.org seems to be down, and thus I cannot build `boost`.

Wouldn't it be safer to have a clone on GitHub?

Is there a quick solution to workaround this problem?

The log of the failing download is located [here](
https://travis-ci.org/Gjacquenot/ssc_build_win64/builds/414803490)

The returned page for `http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz` is

    Error. Page cannot be displayed. Please contact your service provider for more details. (32)

It seems that the domain name is no longer valid.

**Comment by tonytheodore** [comment]
```
Download failed or wrong checksum of package bzip2!
------------------------------------------------------------
HTTP request sent, awaiting response... 200 OK
Length: 271 [text/html]
```
We have multiple backups, but they're only triggered by an error, not a `200 OK`. You can try:
```
make MXE_TARGETS=x86_64-w64-mingw32.static.posix boost bzip2_URL=foo.org
```
to force falling back to one of the mirrors.

**Comment by tonytheodore** [comment]
Actually, this should be fixed since [Nov 17](https://github.com/mxe/mxe/commit/1e9aa771e36a75058f092f8b29450f65a830faa7#diff-b67911656ef5d18c4ae36cb6741b7965), what version of mxe are you using?

**Comment by Gjacquenot** [comment]
Thanks @tonytheodore , your recommendation works!

**Comment by Gjacquenot** [comment]
I am using mxe with sha 994ad47302e8811614b7eb49fc05234942b95b89 (2017-10-25) from [dockcross](
https://github.com/dockcross/dockcross/blob/112d113365e44770cac70fb11e5a2e7281ebe6e6/common.windows#L17)

**Comment by chickenandpork** [comment]
FWIW this is occurring right now, and has been breaking my non-mxe build for a while. (I only came here because the error message googles well and I wanted to let you guys know it's still a thing and your tools might want to intentionally route around breakage better than mine do)

**Comment by tonytheodore** [comment]
I see the [recent bzip2 url fix](https://github.com/mxe/mxe/commit/7350b9825613312e01039952ccadcf04f7efe014#diff-c1a4b8e91e9ae6cc7158a0ac9597d56e) is actually wrong, but it's still falling back to the mirrors and retrieving the file (at least here). 

Since 2017-11 (PR #1974) every commit should be downloadable indefinitely, there's no current mechanism to purge three of the four mirrors and we probably won't look at that till years down the track.
