### ISSUE TITLE
include_next breaking future cmake builds

### ISSUE THREAD

**Issue by donbright** [mxe/mxe#2177]
so this is not a fail with current master, but it will be soon. 

i tried to upgrade gcc to 7.3.0 to fix an internal compiler failure on a build. the main way to fix an internal compiler error that makes sense is to upgrade gcc. however. 

the use of 'include_next' is beginning to break things for certain cmake builds

https://gist.github.com/donbright/f2cdd9bc5488bf94eb043d572e082ec4

seems to be related to use of inclue_next and its relationship to progrmas like cmake improperly using -isystem

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129

**Comment by donbright** [comment]
cant get a good log... closing for now...

**Comment by tonytheodore** [comment]
I've seen something similar before and have a partial workaround with `MXE_DISABLE_INCLUDE_SYSTEM_FLAG` in https://github.com/mxe/mxe/pull/1854/files and cgal fix in https://github.com/mxe/mxe/pull/1860/commits/e4b7a77f288dabf46f717190b1a522b8c277c8cc. I'm not too happy about an mxe-specific fix, but (from memory) upstream cmake developers consider it a "won't fix".

**Comment by tonytheodore** [comment]
I've [cherry-picked the cgal fix](https://github.com/mxe/mxe/commit/8912905d690604cddb95f68fd437d5f86924713f) and tested  with:
```
make MXE_PLUGIN_DIRS=plugins/gcc7 MXE_TARGETS=i686-w64-mingw32.static.posix
make MXE_PLUGIN_DIRS=plugins/gcc7 MXE_TARGETS=i686-w64-mingw32.static
make MXE_TARGETS=i686-w64-mingw32.static
```
gcc8 plugin will most likely work also.
