### ISSUE TITLE
libQt5OpenGLd.a needed while building

### ISSUE THREAD

**Issue by LogX7** [mxe/mxe#2180]
hello i'm trying to build embrodiermodder 2 for windows on linux mint 19 using mxe

so here's what i'm getting 

```
cd ../../libembroidery-convert/ && ( test -e Makefile || /home/hammi/.mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 -o Makefile /home/hammi/Embroidermodder/libembroidery-convert/libembroidery-convert.pro ) && make -f Makefile 
make[1]: Entering directory '/home/hammi/Embroidermodder/libembroidery-convert'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/hammi/Embroidermodder/libembroidery-convert'
cd ../../embroidermodder2/ && ( test -e Makefile || /home/hammi/.mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 -o Makefile /home/hammi/Embroidermodder/embroidermodder2/embroidermodder2.pro ) && make -f Makefile 
make[1]: Entering directory '/home/hammi/Embroidermodder/embroidermodder2'
make[1]: *** No rule to make target '/home/hammi/.mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5OpenGLd.a', needed by 'embroidermodder2.exe'.  Stop.
make[1]: Leaving directory '/home/hammi/Embroidermodder/embroidermodder2'
Makefile:84: recipe for target 'sub-------embroidermodder2-make_first-ordered' failed
make: *** [sub-------embroidermodder2-make_first-ordered] Error 2

```

currently i've made qtbase and qtscript .. because they've got what i need .. i don't want to make qt5 because it takes alot of time ... i wonder if this issue is because of that, and if it is can i make only specific packages to solve it. if yes which ones ?

**Comment by tonytheodore** [comment]
When you run qmake, try adding `CONFIG-=debug CONFIG+=release`. It looks like it's trying a debug build by default (with the *d suffixes).

**Comment by LogX7** [comment]
@tonytheodore  thnx for responding .. 
i tried the following  

~/.mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 CONFIG-=debug CONFIG+=release 
then 
make -j4

and the same issue presist

here are the last couple of output lines


```
moc statusbar-button.h
moc imagewidget.h
moc property-editor.h
moc undo-editor.h
moc object-save.h
moc application.h
compiling .moc/moc_mainwindow.cpp
compiling .moc/moc_mdiarea.cpp
compiling .moc/moc_mdiwindow.cpp
compiling .moc/moc_view.cpp
compiling .moc/moc_cmdprompt.cpp
compiling .moc/moc_embdetails-dialog.cpp
compiling .moc/moc_settings-dialog.cpp
compiling .moc/moc_preview-dialog.cpp
compiling .moc/moc_layer-manager.cpp
compiling .moc/moc_statusbar.cpp
compiling .moc/moc_statusbar-button.cpp
compiling .moc/moc_imagewidget.cpp
compiling .moc/moc_property-editor.cpp
compiling .moc/moc_undo-editor.cpp
compiling .moc/moc_object-save.cpp
compiling .moc/moc_application.cpp
linking embroidermodder2.exe
/home/hammi/.mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lqtmaind
/home/hammi/.mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lwindowsprintersupportd
/home/hammi/.mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lqwindowsvistastyled
/home/hammi/.mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lqwindowsd
/home/hammi/.mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lqgifd
/home/hammi/.mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lqicod
/home/hammi/.mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lqjpegd
collect2: error: ld returned 1 exit status
Makefile:652: recipe for target 'embroidermodder2.exe' failed
make[1]: *** [embroidermodder2.exe] Error 1
make[1]: Leaving directory '/home/hammi/Embroidermodder/embroidermodder2'
Makefile:84: recipe for target 'sub-------embroidermodder2-make_first-ordered' failed
make: *** [sub-------embroidermodder2-make_first-ordered] Error 2


```

**Comment by LogX7** [comment]
@tonytheodore hello, this didn't not work, what i tried doing is linking file with d's with file without d's like libQt5OpenGLd.a  to libQt5OpenGL.a

this bypassed the previous issue but when doing 
linking embrodiermodder2.exe
it fails while showing like 200 can't refrence ...some function errors and the root of most of those errors are the linked files .. 
i'm starting to lose hope .. 
any ideas ??

**Comment by tonytheodore** [comment]
You could try (note the `-after`):
```
~/.mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 -after CONFIG-=debug CONFIG+=release
```
or build qt with debug enabled:
```
make qtbase qtscript qtbase_CONFIGURE_OPTS=-debug-and-release
```

**Comment by LogX7** [comment]
@tonytheodore  so i tried this
`~/.mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 -after CONFIG-=debug CONFIG+=release`
and it worked, it complied without a problem but when i compied the exe to my windows computer and i launched it i get 
this messages for a bunch of dlls 

The program can't start because file.dll is missing 

the dlls are : 

Qt5Core.dll
QT5Gui.dll
QT5PrintSupport.dll
QT5Script.dll

**Comment by tonytheodore** [comment]
Not sure what's happening, there should be no reference to *.dlls at all. This works (replaced with your `qmake`):
```
export em_tmp=`pwd`/Embroidermodder
git clone https://github.com/Embroidermodder/Embroidermodder.git --depth=1 $em_tmp
mkdir $em_tmp.build && cd $em_tmp.build
~/.mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 $em_tmp/embroidermodder2/ CONFIG+=deploy
make -j8
mkdir embroidermodder2-deploy
mv embroidermodder2.exe embroidermodder2-deploy/
cp -R $em_tmp/embroidermodder2/{commands,help,icons,images,samples,translations} embroidermodder2-deploy/
```
copy the `embroidermodder2-deploy` folder to a windows machine and open `embroidermodder2.exe`:

![voila_capture 2018-08-15_16-40-25_](https://user-images.githubusercontent.com/537773/44134869-f352bc5a-a0a9-11e8-8390-26e19d489e1d.png)

**Comment by LogX7** [comment]
@tonytheodore  i've deleted mxe and i'm recloning and rebuilding qtbase and qtscript ... i'll try this when i'm done

in the meanwhile would it be oky for you to share the windows build ?

**Comment by tonytheodore** [comment]
You mean the binaries and folder? I've deleted it but will rebuild - only takes a couple of minutes.

**Comment by LogX7** [comment]
@tonytheodore  ... you're a life saver thank you so much ... 
by the way how can i get a better understanding for building software, as you can see I've been struggling to build this (I've never used make or qmake .. etc i don't even understand the point of  using them)
PS : sorry i'm a nooby

**Comment by tonytheodore** [comment]
Good to hear it worked, I don't know if there's any tips about getting a better understanding - it's a lot of trial and error!
