### ISSUE TITLE
db-2-install-exe.patch defines wrong variable

### ISSUE THREAD

**Issue by FyreDemonyte** [mxe/mxe#2187]
@starius when building BerkelyDB after installing qt5 with gcc8:

The patch does not change the $$i variable in https://github.com/mxe/mxe/blob/13d6257891f94d539b29a786641cef60b0874233/src/db-2-install-exe.patch#L24 

and leaves `$(INSTALLER) $$i` still in place from the original Makefile.in setup. 

This results in libtool not being able to locate the bindir files in build_unix to copy over to mxe/usr/i686-w64-mingw32.static/bin (or relevant target dir), because $$i variable isn't defined, like it is in the original makefile.in

@tonytheodore believes this patch may be removed all together and use the transform variable to fix this issue. https://github.com/mxe/mxe/pull/2186#issuecomment-414134618. 

I'm not familiar with making this type of change. I'll let it to you guys.

**Comment by tonytheodore** [comment]
> make update-package-gcc && make db

Now I see, what happens if you do:

```
$ make gmsl-print-db_PATCHES
db_PATCHES = /usr/lib/mxe/src/db-1-fix-including-winioctl-h-lowcase.patch /usr/lib/mxe/src/db-2-install-exe.patch
$ make gmsl-print-db_PATCHES MXE_PLUGIN_DIRS=plugins/gcc8
db_PATCHES = ./src/db-1-fix-including-winioctl-h-lowcase.patch
```

That usage of `MXE_PLUGIN_DIRS=plugins/gcc8` is about to be deprecated, in the mean time, simply delete `src/db-2-install-exe.patch`. The fix for all gcc versions looks like:

```diff
diff --git a/src/db-2-install-exe.patch b/src/db-2-install-exe.patch
deleted file mode 100644
index 57d26f07..00000000
--- a/src/db-2-install-exe.patch
+++ /dev/null
@@ -1,28 +0,0 @@
-This file is part of MXE. See LICENSE.md for licensing information.
-
-From 67a1bbc57a368efd2ebb81f771ef7ba794bac5a0 Mon Sep 17 00:00:00 2001
-From: Boris Nagaev <bnagaev@gmail.com>
-Date: Wed, 2 Sep 2015 20:18:30 +0300
-Subject: [PATCH] install executables with .exe
-
----
- dist/Makefile.in | 3 +--
- 1 file changed, 1 insertion(+), 2 deletions(-)
-
-diff --git a/dist/Makefile.in b/dist/Makefile.in
-index 8358e53..8839ea6 100644
---- a/dist/Makefile.in
-+++ b/dist/Makefile.in
-@@ -1150,8 +1150,7 @@ install_utilities:
- 	    ($(MKDIR) -p $(DESTDIR)$(bindir) && \
- 	    $(CHMOD) $(dmode) $(DESTDIR)$(bindir))
- 	@for i in $(UTIL_PROGS); do \
--		test -f $$i.exe && i=$$i.exe; \
--		e=`echo $$i | $(SED) '$(transform)'`; \
-+		e=$$i.exe; \
- 		$(RM) $(DESTDIR)$(bindir)/$$e; \
- 		$(INSTALLER) $$i $(DESTDIR)$(bindir)/$$e; \
- 		$(STRIP) $(DESTDIR)$(bindir)/$$e; \
--- 
-2.1.4
-
diff --git a/src/db.mk b/src/db.mk
index fe4a013a..e0c39ecd 100644
--- a/src/db.mk
+++ b/src/db.mk
@@ -20,6 +20,7 @@ endef
 define $(PKG)_BUILD
     cd '$(1)/build_unix' && ../dist/configure \
         $(MXE_CONFIGURE_OPTS) \
+        --program-transform-name='s,.exe,,;s,\(.*\),\1.exe,' \
         --enable-mingw \
         --enable-cxx \
         --enable-cryptography \
```

**Comment by D3m0nKingx** [comment]
>$ make gmsl-print-db_PATCHES
db_PATCHES = /home/demon/dev/mxe/src/db-1-fix-including-winioctl-h-lowcase.patch /home/demon/dev/mxe/src/db-2-install-exe.patch

**Output**:
```
db_PATCHES = /home/demon/dev/mxe/src/db-1-fix-including-winioctl-h-lowcase.patch
make: Nothing to be done for '/home/demon/dev/mxe/src/db-2-install-exe.patch'.
```

>$ make gmsl-print-db_PATCHES MXE_PLUGIN_DIRS=plugins/gcc8
db_PATCHES = ./src/db-1-fix-including-winioctl-h-lowcase.patch

**Output**: 
```
db_PATCHES = ./src/db-1-fix-including-winioctl-h-lowcase.patch
```

**Comment by D3m0nKingx** [comment]
:+1: for adding to db.mk L#23, works like a charm :100: 
```
+        --program-transform-name='s,.exe,,;s,\(.*\),\1.exe,' \
```
