### ISSUE TITLE
Built-in way to check other package is or is going to be installed

### ISSUE THREAD

**Issue by PsychoXIVI** [mxe/mxe#2194]
Is there a built-in way to check if other package is also in the list to make or is already installed?

I think I could use sum of `usr/<target>/installed` and as checks, but I want to ask first. 

I am working on to add `libbacktrace` to MXE to allow `boost` use of it (if it's installed) to provide better stacktraces, since I think there is a problem with MinGW option (`DBOOST_STACKTRACE_USE_WINDBG` - `DebugCreate` undefined reference while linking) and basic Boost unwinding also doesn't work. By the way, shouldn't I open other issue about this?

**Comment by tonytheodore** [comment]
> just add boost to the *_DEPS

Other way around, add `libbacktrace` to boost.
