### ISSUE TITLE
failing to link with OpenAL32 - ole32 is missing some implementations?

### ISSUE THREAD

**Issue by elwyos** [mxe/mxe#2202]
So, I've been getting this issue when trying to link with OpenAL:

```
/opt/mxe/usr/i686-w64-mingw32.static/lib/libOpenAL32.a(dsound.c.obj):dsound.c:(.text+0xd8b): undefined reference to `_imp
__CoInitialize@4'
/opt/mxe/usr/i686-w64-mingw32.static/lib/libOpenAL32.a(dsound.c.obj):dsound.c:(.text+0x123e): undefined reference to `_im
p__CoInitialize@4'
/opt/mxe/usr/i686-w64-mingw32.static/lib/libOpenAL32.a(dsound.c.obj):dsound.c:(.text+0x1a04): undefined reference to `_im
p__CoInitialize@4'
/opt/mxe/usr/i686-w64-mingw32.static/lib/libOpenAL32.a(dsound.c.obj):dsound.c:(.text+0x1d38): undefined reference to `_im
p__StringFromCLSID@8'
/opt/mxe/usr/i686-w64-mingw32.static/lib/libOpenAL32.a(mmdevapi.c.obj):mmdevapi.c:(.text+0x4b2): undefined reference to `
_imp__CoInitialize@4'
/opt/mxe/usr/i686-w64-mingw32.static/lib/libOpenAL32.a(mmdevapi.c.obj):mmdevapi.c:(.text+0x1406): undefined reference to 
`_imp__PropVariantClear@4'
/opt/mxe/usr/i686-w64-mingw32.static/lib/libOpenAL32.a(mmdevapi.c.obj):mmdevapi.c:(.text+0x19bc): undefined reference to 
`_imp__CoInitialize@4'
```
My linking flags did have ```-lole32 -luuid -lvfw32 -lportaudio -lOpenAL32``` in thar order.

I went to the /lib/ directory and tried to grep for _imp__CoInitialize

```
$ grep -R _imp__CoInitialize .
Binary file ./libOpenAL32.a matches
Binary file ./libportaudio.a matches
Binary file ./libole32.a matches
```
And that seems to be all. I included portaudio in case these symbols are defined there, but I'm pretty sure it's an ole32 thing.

What is causing this issue? I just pulled this mxe yesterday, if that makes a difference. That, and I'm using gcc8.

Thanks in advance!

**Comment by tonytheodore** [comment]
> My linking flags did have -lole32 -luuid -lvfw32 -lportaudio -lOpenAL32 in thar order.

Try the reverse order, the linker goes left to right to find symbols. Lower level systems libs should be the furthest to the right. Also consider using pkg-config, it's the easiest way.

**Comment by elwyos** [comment]
That did the trick - had to put ole32 after OpenAL32. Thank you very much!

(for some reason, I thought it had to be put beforehand, too)
