### ISSUE TITLE
Expat library is broken in 32 or 64 bits shared

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2203]
Host : Linux Mageia6
digiKam Windows bundle scripts.

[build-mxe.full.log](https://github.com/mxe/mxe/files/2363191/build-mxe.full.log)
[expat-download](https://github.com/mxe/mxe/files/2363193/expat-download.txt)
[expat_x86_64-w64-mingw32.shared](https://github.com/mxe/mxe/files/2363194/expat_x86_64-w64-mingw32.shared.txt)
[Expat internal config.log](https://github.com/mxe/mxe/files/2363190/config.log)

**Comment by tonytheodore** [comment]
Should be fixed in https://github.com/mxe/mxe/commit/842827a489087b77f51554655c0d4f48ddebd5a5

**Comment by cgilles** [comment]
Confirmed. It work. 
Thanks for your fast support and your brillant project.
Gilles Caulier
