### ISSUE TITLE
Help cross compiling a program with gcc8

### ISSUE THREAD

**Issue by Gjacquenot** [mxe/mxe#2204]
Not really an issue , but more a help request.

I would like to cross compile the following Fortran program for windows 64 (in a static way if possible)

    program test
    integer, parameter :: dp = kind(1.d0)
    real(kind=dp) :: vec(2,3,3,6,2,3,12,8)
    end program

One compiles this test program with

    gfortran -std=f2008 test.f90 -o test

It requires gfortran 8, which is not the default compiler for mxe.

Therefore, I would like to setup mxe with gcc8, gfortran8.

I have tried to build gcc 8 with the command `make MXE_PLUGIN_DIRS=plugins/gcc8 gcc`, but I am not sure this is the way to go, because it builds gcc8 for windows, that's right? I need more a linux  version of gcc 8 to cross  compile?

@tonytheodore , @mabrand , do you have any advice?

I can see my trials here: https://github.com/Gjacquenot/windows-x64-posix-gcc8

It is a GitHub repo with a Dockerfile, that builds an image gcc 8 from mxe. but I don't know how to use it...

**Comment by Gjacquenot** [comment]
Thanks @tonytheodore!

I had run the command you gave me, but did not know where compilers were located...

I manage to compile the test program and tested it with wine.

Result can be seen [here](https://travis-ci.org/Gjacquenot/windows-x64-posix-gcc8/builds/426172944)

Do you know when direct usage of `MXE_PLUGIN_DIRS=plugins/gcc8` will be deprecated?

**Comment by tonytheodore** [comment]
> Do you know when direct usage of MXE_PLUGIN_DIRS=plugins/gcc8 will be deprecated?

Hopefully in the next week or so. 

In regards to https://github.com/dockcross/dockcross/issues/259, it will let you have multiple gcc versions side-by-side to more easily test future versions while keeping a stable version as long as you want, independent of mxe defaults.

**Comment by JulyIGHOR** [comment]
My solution for this was before any compilations do edit file:
mxe/src/gcc.mk to change gcc version I want than run commands:
make update-checksum-gcc
make gcc
You will get gcc-8 as default.
I had no problems with it.
Will wait for tonytheodore updates since two gcc is better than one

**Comment by Gjacquenot** [comment]
For time being, I have forked [dockcross](https://github.com/dockcross/dockcross) project, created a branch [gcc8](https://github.com/Gjacquenot/dockcross/tree/gcc8) where I build a docker image that embeds gcc8.

As you mentioned, I wait for the possibility to gcc reference and gcc 8 with a simple change of target.
