### ISSUE TITLE
MXE build on MacOS with Xcode 10

### ISSUE THREAD

**Issue by markghayden** [mxe/mxe#2217]
MXE does not appear to build on MacOS using Xcode 10, apparently because 32-bit host compiler is deprecated.  Below is a fresh git checkout and build.

--Mark

+ rm -rf mxe
+ git clone https://github.com/mxe/mxe.git
Cloning into 'mxe'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 44861 (delta 7), reused 13 (delta 6), pack-reused 44841
Receiving objects: 100% (44861/44861), 23.10 MiB | 7.07 MiB/s, done.
Resolving deltas: 100% (32483/32483), done.
+ jobs='--jobs=4 JOBS=4'
+ nice make -k --jobs=4 JOBS=4 -C mxe MXE_TARGETS=x86_64-w64-mingw32.shared gettext
[create settings.mk]
[download]    binutils-2.28.tar.bz2
[download]    gmp-6.1.2.tar.xz
[download]    mingw-w64-v5.0.4.tar.bz2
[download]    isl-0.15.tar.bz2
[download]    mpfr-3.1.5.tar.xz
[download]    mpc-1.1.0.tar.gz
[download]    gcc-5.5.0.tar.xz
[download]    pkgconf-da179fd.tar.gz
[download]    libtool-2.4.4.tar.gz
[download]    flex-2.6.0.tar.bz2
[download]    bison-3.0.4.tar.xz
[download]    patch-2.7.5.tar.gz
[download]    gettext-0.19.8.1.tar.gz
[download]    libiconv-1.15.tar.gz
[check reqs]
[nonet lib]   /Users/mhayden/plotter/proj/mxe/version/fresh/mxe/usr/x86_64-apple-darwin18.0.0/lib/nonetwork.dylib                                                                       
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "___error", referenced from:
      _connect in nonetwork-e23ca6.o
  "___stderrp", referenced from:
      _print_message in nonetwork-e23ca6.o
  "_fflush", referenced from:
      _print_message in nonetwork-e23ca6.o
  "_fprintf", referenced from:
      _print_message in nonetwork-e23ca6.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/mhayden/plotter/proj/mxe/version/fresh/mxe/usr/x86_64-apple-darwin18.0.0/lib/nonetwork.dylib] Error 1
[git-log]   920f4dbb Update packages.json & build-matrix.html
make: Target `gettext' not remade because of errors.

**Comment by Lord-Kamina** [comment]
Maybe try using your package manager to install some version of gcc?

**Comment by Lord-Kamina** [comment]
Try ‘CC=/path/to/gcv CXX=/path/to/g++ your make command here‘

**Comment by markghayden** [comment]
Thanks for the suggestion but CC and CXX doesn't seem to affect thing.  It still stops with the same error.  Do you know simply using CC and CXX environment variable works or does it require more changes as in your further comments?

**Comment by tonytheodore** [comment]
> Do you know simply using CC and CXX environment variable works 

These won't work, BUILD_CC & BUILD_CXX may work but you generally shouldn't have to fiddle with those and you'll probably waste time with issues further down the track.

> other versions of gcc are supported by MXE, or how to select them through configuring MXE

It varies depending on what is broken, something like https://github.com/mxe/mxe/issues/1758#issuecomment-309708854 worked in the past.

> select a different Xcode installation for use with MXE

`xcode-select` may be what you're looking for (I haven't used it).

I get a warning with Xcode 10 and darwin17.7.0 which is fixed with:
```diff
diff --git a/Makefile b/Makefile
index e526af88..98255a80 100644
--- a/Makefile
+++ b/Makefile
@@ -657,7 +657,7 @@ ifeq ($(findstring darwin,$(BUILD)),)
 else
     NONET_LIB := $(PREFIX)/$(BUILD)/lib/nonetwork.dylib
     PRELOAD   := DYLD_FORCE_FLAT_NAMESPACE=1 DYLD_INSERT_LIBRARIES='$(NONET_LIB)'
-    NONET_CFLAGS := -arch i386 -arch x86_64
+    NONET_CFLAGS := -arch x86_64
 endif

 $(NONET_LIB): $(TOP_DIR)/tools/nonetwork.c | $(PREFIX)/$(BUILD)/lib/.gitkeep
```

I'll update to Mojave and see what happens.

**Comment by tonytheodore** [comment]
I won't get to it today, I've pushed https://github.com/mxe/mxe/commit/a063f9b35279d83f692df0345d84147c0f23c992 in the mean time.

**Comment by tonytheodore** [comment]
After updating, I get the same error and can confirm the above fixed it.

**Comment by markghayden** [comment]
Thanks!  The builds are now working again.

**Comment by sherifomran** [comment]
i would pass this issue 
https://github.com/frankmorgner/OpenSCToken/issues/7#issuecomment-504744918

**Comment by tonytheodore** [comment]
```
now copy pkgconf to mxe/usr/x86-apple-darwin17.70/installed
```
Don't do that, you could just have easily `touch`ed that file and the build would pass that package and fail at the next one.
