### ISSUE TITLE
gcc8 and std::filesystem : fail to compile

### ISSUE THREAD

**Issue by basiliscos** [mxe/mxe#2220]
```cpp
#include <filesystem>

using namespace std::filesystem;

int main() {
    auto path = temp_directory_path().native();
}
```

```
i686-w64-mingw32.static.posix-c++ -std=gnu++1z -c a.cpp
In file included from /home/b/development/cpp/mxe/usr/lib/gcc/i686-w64-mingw32.static.posix/8.2.0/include/c++/filesystem:37,
                 from a.cpp:1:
/home/b/development/cpp/mxe/usr/lib/gcc/i686-w64-mingw32.static.posix/8.2.0/include/c++/bits/fs_path.h: In member function 'std::filesystem::__cxx11::path& std::filesystem::__cxx11::path::op
erator/=(const std::filesystem::__cxx11::path&)':
/home/b/development/cpp/mxe/usr/lib/gcc/i686-w64-mingw32.static.posix/8.2.0/include/c++/bits/fs_path.h:237:47: error: no match for 'operator!=' (operand types are 'std::filesystem::__cxx11::
path' and 'std::filesystem::__cxx11::path')
    || (__p.has_root_name() && __p.root_name() != root_name()))
...
```

**Comment by e-nexus** [comment]
You probably need to use -std=c++17

**Comment by basiliscos** [comment]
Nope. The error  is the same.

**Comment by e-nexus** [comment]
This post says you need to add '-lstdc++fs ' when compiling.
https://www.reddit.com/r/cpp/comments/7o9kg6/gcc_80_support_stdfilesystem_include_filesystem/

**Comment by basiliscos** [comment]
Nope. The error is the same. AFAIK, `-l` is needed for linking, not for compiling. Also, the sample compiles fine on host by system compile with the initial flags.

**Comment by abbasinasab** [comment]
(mingw perhaps? I c++17 and fs are still not very good friends or IDK I may have a problem with them)
Apparently, this has been fixed in trunk 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78870

Required patches are:
https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=260479
https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=261034

**Comment by Jan200101** [comment]
gcc 9 fixes this

**Comment by abhiarora4** [comment]
I am facing some problem as well. I have posted my question over here: https://stackoverflow.com/questions/57612612/unable-to-cross-compile-qt-application-for-windows-on-ubuntu

**Comment by tonytheodore** [comment]
Last link is a 404
