### ISSUE TITLE
aubio compilation fails

### ISSUE THREAD

**Issue by aquilarubra** [mxe/mxe#2222]
I am posting the x86_64 version here, but I also tried the i686 version and it didn't work too. It is not possible to make MXE, as it stops on aubio.

https://gist.github.com/aquilarubra/3132744cc7e1670f99eb6b9c5ccb8458

**Comment by jnards** [comment]
I also encounter an error when attempting to build aubio, my log was building i686 MXE

https://gist.github.com/jnards/e685290e47076cb7cf083e41185b947c

**Comment by aquilarubra** [comment]
The issue seems to be known: https://github.com/aubio/aubio/issues/173

The (temporary) solution is to add the following line to src/aubio.mk:
            --disable-avcodec                     \

Snippet:
            configure                             \
            -j '$(JOBS)'                          \
            --with-target-platform='win$(BITS)'   \
            --prefix='$(PREFIX)/$(TARGET)'        \
            --enable-fftw3f                       \
            --libdir='$(PREFIX)/$(TARGET)/lib'    \
            --disable-avcodec                     \

This way, it builds fine without ffmpeg support.
