### ISSUE TITLE
SFML 2.5.1

### ISSUE THREAD

**Issue by oomek** [mxe/mxe#2234]
I'm having some problems upding SFML to the 2.5.1 version. When I just copy precompiled includes and libs to the mxe folder I get undefined reference errors like this one:
`/home/oomek/mxe/usr/x86_64-w64-mingw32.static/lib/../lib/libsfml-system-s.a(Err.cpp.obj):Err.cpp:(.text+0x61): undefined reference to __imp___acrt_iob_func`

I assume this is caused by gcc version mismatch. Apps that use SFML 2.5.1 need to be compiled with GCC 7.3.0 MinGW (SEH) - 64-bit if I understand it correctly.

If this is the case how can I safely update SFML with all it dependencies?

**Comment by tonytheodore** [comment]
See #2245 for the 2.5.1 update.

I don't think you need gcc7, those `undefined reference to __imp*` errors are usually caused by a missing `-DSFML_STATIC` in CFLAGS.
