### ISSUE TITLE
Failed to build package glib for target x86_64-pc-linux-gnu!

### ISSUE THREAD

**Issue by hxingpax** [mxe/mxe#2242]
[Log on Gist](https://gist.github.com/hxingpax/1ce5af278656cbe85040ab6119a7a960)

Seems like I have to compile with fPIC, how can I add this option during my MXE compiling?

**MXE repo info**

    $ git log -5
    =>
    commit 611aafdb5afecddcdaad59e60920d9d4e3528e2e (grafted, HEAD -> master, origin/master, origin/HEAD)
    Author: Mark Brand <mabrand@mabrand.nl>
    Date:   Fri Nov 16 10:40:23 2018 +0100
    
        qtimageformats: detect and use "system" libwebp

**System info**

    $ uname -a
    =>
    Linux xing-MacBookPro 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tonytheodore** [comment]
Could you post the full log on gist?

**Comment by fermanmf** [comment]
how did you solve this?
