### ISSUE TITLE
Add release tags

### ISSUE THREAD

**Issue by temap** [mxe/mxe#2248]
Hi, I'm building my packages with mxe in docker which checkout head of master. And after some period, it breaks build due to update packages in mxe.

Do you have plans on tagging release version? 

Thanks.

**Comment by mabrand** [comment]
MXE used to have formal releases, but this seemed to be too much work for little added value.

My recommendation would be for you to make a local tag for a "stable" commit in the sense that it meets your needs. To benefit from later updates, you can advance your tag toward head of master after checking that it still works for you. Another approach would be for you to maintain your own branch, which you would rebase on a working upstream commit when convenient.

Also, if something important is broken in head of master, we want to fix it. What's not working for you?

**Comment by tonytheodore** [comment]
At the moment, all packages are building for all targets except itk-i686-w64-mingw32.shared. I've looked at it a couple of times and haven't made any progress towards a fix.

**Comment by tonytheodore** [comment]
@temap you can use the [`build-*` tags](https://github.com/mxe/mxe/tags) to keep a mostly stable version. These generally are created when all packages are successful, but the one I've just created still has the broken itk-i686-w64-mingw32.shared. These will hopefully be updated quarterly (or so) when we run a new set of binary packages.

**Comment by temap** [comment]
@tonytheodore thank you.
