### ISSUE TITLE
llvm: Allocator.cpp:(.text+0x2aa): undefined reference to `__msan_allocated_memory'

### ISSUE THREAD

**Issue by rcx11** [mxe/mxe#2250]
https://gist.github.com/rcx11/f3a08cab470f6e0bd484f476f3c48cd3

Issue appears to be solvable for a direct LLVM build: https://stackoverflow.com/questions/48146921/llvm-3-42-build-from-source-fails-on-ubuntu-17-04

Request assistance with converting this to MXE build.

**Comment by tonytheodore** [comment]
llvm is need of an update, it's also broken on recent darwin (#2106) but I haven't had time to look at it.

If you don't need it for your project, you can add `EXCLUDE_PKGS=llvm` to your `make` invocation.

**Comment by tonytheodore** [comment]
Actually, the error on darwin is the same.

I've [updated llvm to v7](https://github.com/mxe/mxe/commit/86ea790880c36c9ae0481dbb97ae282ee6f308ec) but it now requires a posix toolchain with c++11 support (I may look at making posix the default soon).

**Comment by tonytheodore** [comment]
see #2263
