### ISSUE TITLE
Cannot create temporary file in C:\WINDOWS\: Permission denied

### ISSUE THREAD

**Issue by crazybytes** [mxe/mxe#2255]
Gerard Wensink@DESKTOP-NJ5FGA2 MINGW64 /opt/mxe
$ make MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static'
[nonet lib]   /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so
Cannot create temporary file in C:\WINDOWS\: Permission denied
make: *** [Makefile:667: /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so] Fout 3

**Comment by tonytheodore** [comment]
Are you using MSYS? I'm not sure that has ever worked, you can try [WSL](https://mxe.cc/#requirements-wsl) or Docker if you're using Windows.

**Comment by crazybytes** [comment]
Ok.
Here is what i have done.

i put some debug info in the makefile, look very closely:

$(NONET_LIB): $(TOP_DIR)/tools/nonetwork.c | $(PREFIX)/$(BUILD)/lib/.gitkeep
	$(info LINE 1 is $(NONET_LIB): $(TOP_DIR)/tools/nonetwork.c | $(PREFIX)/$(BUILD)/lib/.gitkeep)
	$(info LINE 2 is @$(PRINTF_FMT) '[nonet lib]' '$@')
	@$(PRINTF_FMT) '[nonet lib]' '$@'
	$(info LINE 3 is +@$(BUILD_CC) -shared -fPIC $(NONET_CFLAGS) -o $@ $<)
	+@$(BUILD_CC) -shared -fPIC $(NONET_CFLAGS) -o $@ $<
	$(info LINE 4 is +@$(BUILD_CC) -shared -fPIC $(NONET_CFLAGS) -o $@ $<)

Ok, so it prints out the statements, now it gets weird, really weird.
It give as output:

[check reqs]
LINE 1 is /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so: ./tools/nonetwork.c | /opt/mxe/usr/x86_64-pc-mingw64/lib/.gitkeep
LINE 2 is @printf '%-13s %-22s %-53s %-15s %s\n' '[nonet lib]' '/opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so'
LINE 3 is +@gcc -shared -fPIC  -o /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so tools/nonetwork.c
LINE 4 is +@gcc -shared -fPIC  -o /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so tools/nonetwork.c
[nonet lib]   /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so                                                         
Cannot create temporary file in C:\WINDOWS\: Permission denied
make: *** [Makefile:673: /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so] Fout 3

Ok, so line 673 is 	+@$(BUILD_CC) -shared -fPIC $(NONET_CFLAGS) -o $@ $<

So, this is impossible, because it prints out line 1 2 3 and 4
THEN it outputs [nonet lib]   /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so to the console, which must be the line with 	@$(PRINTF_FMT) '[nonet lib]' '$@'   after line 2
So, it should never reach line 3 and 4 output like the output says.
But still it starts puking AFTER it outputs line 4

So, that is what i don't understand, but THEN:

after this error i give:

gcc -shared -fPIC  -o /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so tools/nonetwork.c

witch gives NO ERROR! OK?

then i type make again, and it gives no error on line 673 

So, on what statement it gives the error?????????? in the first make run?
Because after compiling the nonetwork.c in the shell, not the makefile, its compiled, 

Howerer, without the +@ prefix on the gcc command. For whitch purpose it is i don't know.

So, i thought nice,

But then you get the next trap they set in the jungle,

git-oneline
[git-log]   2ae85c54 Update packages.json & build-matrix.html
[build]       mxe-conf               x86_64-w64-mingw32.static
[done]        mxe-conf               x86_64-w64-mingw32.static                              0 KiB          0m11,262s
[build]       binutils               x86_64-w64-mingw32.static

Failed to build package binutils for target x86_64-w64-mingw32.static!
------------------------------------------------------------
------------------------------------------------------------
[log]      /opt/mxe/log/binutils_x86_64-w64-mingw32.static

make: *** [Makefile:838: /opt/mxe/usr/x86_64-w64-mingw32.static/installed/binutils] Fout 1

So, it  doesn't output 
....
LINE 4 is +@gcc -shared -fPIC  -o /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so tools/nonetwork.c
[nonet lib]   /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so                                                         
Cannot create temporary file in C:\WINDOWS\: Permission denied
make: *** [Makefile:673: /opt/mxe/usr/x86_64-pc-mingw64/lib/nonetwork.so] Fout 3

anymore, but now there is another error on building the binutils.

for convenience i set up MXE_TARGETS := x86_64-w64-mingw32.static in the settings.mk
i also set MXE_TMP := /tmp/mxe-tmp like the manual says.

So, i followed the manual exactly, you encounter lots of problems, but this one must be set up 
by Microsoft or mxe, who want to put people on the wrong leg, so only insiders can use mxe,

Maybe they are trolling around in this forum also, pushing you into all kind of traps,
I think they have joint the illuminati inbred bastards to corrupt mxe.

what do you think?

Because they are everywhere, 
and these thingies are everywhere,

They collect the open source code from the community, infiltrate, change things,
so you can not follow up on that, meanwhile they publish nice programs, 
while we (i) am struggling with these kind of issues.
Then when you talk on forums, everybody talks like chickens, and get 
trolled around by people giving wrong answers and putting you in wrong directions.
Pages are corrupted, nothing works like they say,

So, what is the problem, 

I and my team are studying these kind of issues for over more than 40 years,

Ok?

And it gets worse and worse, people get really traumatized by all.

nothing, nothing, nothing works like they PRETEND, 

I know that if they don't join the illuminati, their whole family will be unemployed, or killed, or get
cancer etc., if they don't join them.

Others are unaware, getting fooled around by them also.

So, here is the fix:

I give them one week, to fix everything.

EVERYTHING, OK? Not only on the msys2 / mingw / mxe  stuff.

Because is also see it happening on the nice ffmpeg tool, they changed it, they can follow up with their knowledge (insiders) because they joint the club of evil,
but my guys can not follow up anymore, code is out of date, not adapted, but they can.

Like they changed the ffmpeg open source, so EVERY OLD CODE which uses the ffmpeg is incompatible, and has to be changed, but the writers are not updating their  code, because they can not follow up, and have to use ffmpeg-2.8 for example, which is out of date.

Etc etc etc.

So, we say we put everybody for responsible that ON PURPOSE put all these traps and shit into the code, so only THEY can use it, because they made it an know what is going on.

Ok, its conspiracy shit, and nobody is gonna believe it.

But we go further, we have a bunch of lawyers who together with some really good experts,
who did not join the club of Gates and the bankers and illuminati, and they studied the case for 
a long time
This here is only one of the many examples where they corrupt the open source, because its 
corrupted EVERYWHERE.

OK? 

So we set a date for all rats involved to fix the thing, everywhere, the pages on the web, the forums, etc.
They have to fix everything so everything has to run smooth just like they PRETENDING, 

Otherwise they will be sued for court, which will take many many years, but the outcome will be
its exactly what i am telling here, and then they will have to BLEED.

So, you never can tell who is naif and stupid, and believes all the shit they are saying here, 
or who are the rats that troll you around, because you can never proof their intentions.

Its all about the money you know, so after court they will be sued for live and will have to pay billions to the open source for restoring the fate, 

because that is the only way to make them feel. 

So, enough of all conspiracy shit, i know they set up traps nobody can understand, because they
made the jungle where the traps are located.

You study my findings, then talk to the msys club, and the mxe club, and the windows club, 
because here are only three parties involvod. msys2 mxe and microbastard.

Then the open source community has to put up a website, were these accusations will be showed,
so we make all public, as an issue. To inform the open source its infiltrated to the bone, in every 
cel of the open source body, and corrupts the dna of it.

So, what are your  thoughts of that?

If not, we will send out the dogs, and nobody wants that. 
If you know what i am saying.

I check out the next trap on the binutils.
Bye for now, and tell it around, we will get them, if it takes forever, and the devils who created all 
the traps, 

you know,

they will burn in hell forever.

I will get back on all this later.
Have a nice day.

**Comment by crazybytes** [comment]
Looks like you sending me to somewhere else in the jungle, i will check it out.
WSL you are saying eh? 
Is it one part of the binaire tree trap? Walking 1000 paths before you get to the cliff with skulls and bones?

**Comment by crazybytes** [comment]
Who knows are you trolling around also, you never know for sure what the intentions are, and who is on who's side, but some open source guys disappeared or gotten  into all kinds of trouble. Like the mafia.

**Comment by crazybytes** [comment]
If you think i am insane, that is exactly what they want people to think. 
And what the trolls say. We need a lie detector we can put them on.

**Comment by crazybytes** [comment]
I also want to tell here i won a fight with facebook, about a story about gang stalking, by governments, police etc. By the whole community, who is unaware of what is going on.

PEOPLE ARE GETTING KILLED, you know?

So i put the story out on facebook, had a fight for two weeks because secret service putted it on black every day, facebook started to annoy etc., but i won the case, ok? so this story is now published on facebook, BECAUSE I GOT SOME PEOPLE BEHIND ME WHO BACKED ME UP.
We are doing this for everybody, even for Gates and the illuminati, to create a better world.
ALSO IN THE OPEN SOURCE COMMUNITY, where the devil is walking around.
SO EVERYBODY, BE AWARE, THE CHANGE IS COMING, AND ALL WHO STAY JOINING THE ILLUMINATI WILL RECEIVE EXACTLY THE SAME AS THE POOR GUYS WHO HAVE GOTTEN TORTURED, 

just because he was a honest guy with only good intentions for everybody.

SO FIX IT.

One week.

**Comment by crazybytes** [comment]
You know "they" are reading this eh?
Also check out my program, its really nice for starters. 
It uses codeblocks compiler.
SFML
SFEMOVIE / SFEMOVIEFIX
Then for the ffmpeg part ffmpeg-2.8 ( :( ) (because of changes in new versions that are not fixed in sfemovie)
CMAKE, MINGW, MSYS2 etc.
MXE now makes part of that to.
So help the sfemovie guys also to get them code getting adapted to the new ffmpeg code.
Same story as like here, we give it 1 week so they must get things back straight.
I am not telling them, i putted it here, so you tell them. Then inform the ffmpeg team to help them fix it.

If not, you all we see a big ball of fire. I swear.

(busje komt zo).... (they know).
