### ISSUE TITLE
Module charts

### ISSUE THREAD

**Issue by OpoOpo** [mxe/mxe#2257]
Hi, I'm trying to build program with charts module and error showing up:
```Project MESSAGE: Warning: unknown QT: charts```
and when i try to make missing module with```make charts```
is says ```make: *** No rule to make target 'charts'.  Stop.```
Any suggestions?
Thank you

**Comment by tonytheodore** [comment]
Did you build the `qtcharts` package or just `qtbase`?

**Comment by OpoOpo** [comment]
I tried to build ```qtcharts``` with command ```make charts``` or ```make chart``` but no rule was found...

**Comment by tonytheodore** [comment]
Did you try `make qtcharts`?

**Comment by OpoOpo** [comment]
It helped.
Thank you
