### ISSUE TITLE
What to do with libraries which require GCC built with posix threads?

### ISSUE THREAD

**Issue by tehnick** [mxe/mxe#2258]
More and more C++ based projects currently begin to use treads implementation from C++11 (`<thread>`, `<mutex>`, `<future>`, etc.). This applies to both end-user programs and libraries.

Applications are out of scope from MXE project: their maintainers may build libraries with any preferable options. MXE already provides all required for this.

As for widely used libraries, the recent examples are: `protobuf`, `qtwebkit` (see #2070) and `boost` (probably optional, I have not tested). New versions of these (and maybe other libraries in not far perspective) will require GCC built with `posix` threads option, but by default MXE comes with GCC built with `win32` and in documentation it is marked as officially supported (vs. experimental support of `posix` threads).

The question is: what to do with these libraries?

Should we stuck with their current versions forever? Or should update them? But how to do this properly?

**Comment by tehnick** [comment]
I saw few interesting projects like [mingw-std-threads](https://github.com/meganz/mingw-std-threads), but these program layers are not suitable for building discussed libraries without modifications.

**Comment by tonytheodore** [comment]
I think we should switch the default over to the posix enabled build, it's really an additional gcc feature and doesn't need a separate toolchain target. Things like exception handling and arch aren't features per se, more like variants that do need separate targets.

There are some packages with disabled non-posix builds ([llvm](https://github.com/mxe/mxe/commit/86ea790880c36c9ae0481dbb97ae282ee6f308ec#diff-72f8689eaf8f36430657da1905cd1be4R13) & [qtifw](https://github.com/mxe/mxe/commit/8418ae7764a8a158450ac04c06b5f11186d7f389#diff-f19bb5f73c2f6f9c66754a743747f869R15)) and updates pending for [glib and friends](https://github.com/mxe/mxe/pull/2174). Last time I checked (a few weeks ago), there was only one package broken with the posix build, freeimage shared.

**Comment by tonytheodore** [comment]
Freeimage is now [fixed](https://github.com/mxe/mxe/commit/e9d4e7d1a082fd2256327e1af4bb0abf70816527) and I'll start on a PR to switch the default over and update the docs.

**Comment by tehnick** [comment]
> I think we should switch the default over to the posix enabled build, it's really an additional gcc feature and doesn't need a separate toolchain target.

Great! This simplifies things a lot.
