### ISSUE TITLE
libclang-3.8-dev is a requirement on Debian9 for compiling qt5/qttools 

### ISSUE THREAD

**Issue by schloegl** [mxe/mxe#2262]
When trying to compile qt5 on debian9, it failed to compile 
`Info: creating stash file /mnt/ramdisk/mxetmp/tmp-qttools-i686-w64-mingw32.static/qttools-everywhere-src-5.12.0/.qmake.stash
Project ERROR: Cannot find libclang's main header file, candidate: /usr/lib/llvm-3.8/include/clang-c/Index.h.
 `

Only after installing libclang-3.8-dev, I was able to compile qttools and qt5. however, libclang-3.8-dev is not listed as a prerequisite  at
  https://mxe.cc/#requirements

It's not really clear to me why clang is needed on the build platform, the only non-default settings (in settings.mk are 

```
  MXE_TARGETS :=  i686-w64-mingw32.static  x86_64-w64-mingw32.static
  override MXE_PLUGIN_DIRS += plugins/gcc8

```

If libclang-dev is a requirement, it should be mentioned in the requirements sections,

**Comment by tonytheodore** [comment]
Can you make a gist of the full log? I'm guessing qttools is autodetecting a clang install and trying to use it.

**Comment by schloegl** [comment]
The gist of the full log is available here:
https://gist.github.com/schloegl/d970f0a16394cf265593bb0aa17df5a0

**Comment by Shamus397** [comment]
I'm seeing the exact same issue.  Full log gist: https://gist.github.com/Shamus397/ffe8ab757fcb921cd5405c532351b78a

**Comment by tonytheodore** [comment]
It seems if you have clang installed it tries to use it for the `qtdoc` feature and then requires the *-dev package.

I don't think should be added to the requirements, can you check if:
```diff
diff --git a/src/qttools.mk b/src/qttools.mk
index 0a042250..a1c45c99 100644
--- a/src/qttools.mk
+++ b/src/qttools.mk
@@ -19,7 +19,7 @@ define $(PKG)_UPDATE
 endef

 define $(PKG)_BUILD
-    cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake'
+    cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' CONFIG+=config_clang_done CONFIG-=config_clang
     $(MAKE) -C '$(1)' -j '$(JOBS)'
     $(MAKE) -C '$(1)' -j 1 install

@@ -32,7 +32,7 @@ define $(PKG)_BUILD
 endef

 define $(PKG)_BUILD_$(BUILD)
-    cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake'
+    cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' CONFIG+=config_clang_done CONFIG-=config_clang
     $(MAKE) -C '$(1)' -j '$(JOBS)'
     $(MAKE) -C '$(1)' -j 1 install
 endef
```
fixes it?
