### ISSUE TITLE
Patch to build MXE from snapshot

### ISSUE THREAD

**Issue by gballabio** [mxe/mxe#2270]
Hello,
please apply the attached to the top-level Makefile.
It makes it possible to compile MXE from a downloaded snapshot without having to clone the git tree.
It works simply by telling make not to abort if the "git log" command fails. This is the only modification needed, everything else just works.
(Appending .txt to the filename because GitHub doesn't let me attach it otherwise.)

Thank you
Gerardo Ballabio

[Makefile.patch.txt](https://github.com/mxe/mxe/files/2752633/Makefile.patch.txt)

**Comment by tonytheodore** [comment]
Thanks.
