### ISSUE TITLE
searching topics for MXE github repo

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#2271]
The search for the word "mingw" on https://github.com does not contain a link to the https://github.com/mxe/mxe. In the same time, the search results have a link to MXE analog - https://github.com/Alexpux/MINGW-packages.

To fix it you can use "searching topics", see for example https://github.com/niXman/mingw-builds.

**Comment by tonytheodore** [comment]
Thanks, I’ve added that and some others it suggested.
