### ISSUE TITLE
Using ccache

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#2272]
@tehnick [wrote](https://github.com/mxe/mxe/pull/2268#issuecomment-452884914):
> BTW, is it any way to use ccache in MXE?

Using the [symlink method](https://ccache.samba.org/manual/latest.html#_run_modes) and adjusting the cmake toolchain file results in nice speedups for qtwebkit:
```
no cache     57m15.298s
cache 00     72m13.544s
cache 01     12m20.226s
cache 02     12m26.279s
cache 03     12m22.409s
```
Looks like a 20-25% penalty for the first cache run, then speedups just under 500%!

I think we'd use the `content` [compiler_check config](https://ccache.samba.org/manual/latest.html#_configuration_settings) but otherwise the defaults are very easy to get started with. The cache stats:
```
$ ccache -s
cache directory                     /Users/tonyt/.ccache
primary config                      /Users/tonyt/.ccache/ccache.conf
secondary config      (readonly)    /opt/local/etc/ccache.conf
stats updated                       Sun Jan 20 00:49:31 2019
cache hit (direct)                 10713
cache hit (preprocessed)              42
cache miss                          3585
cache hit rate                     75.00 %
called for link                      176
called for preprocessing            6608
compile failed                         4
preprocessor error                     4
no input file                         81
cleanups performed                     0
files in cache                      7388
cache size                         194.7 MB
max cache size                       5.0 GB
```
qtwebkit is the largest package so we may not even need to tweak the compression or cache size. I'm certainly going to look further into adding it to mxe.

**Comment by tehnick** [comment]
> Looks like a 20-25% penalty for the first cache run, then speedups just under 500%!

Very interesting results. Not such impressive as at a build of native libraries and programs in my system. But nevertheless the speed up is huge.

> I'm certainly going to look further into adding it to mxe.

Excellent!

**Comment by tonytheodore** [comment]
Progress so far is in #2273 though I'm thinking of removing support for a system ccache and only using our own version/config.

**Comment by tehnick** [comment]
> Progress so far is in #2273 though I'm thinking of removing support for a system ccache and only using our own version/config.

Yes, this is a good idea. Users would not want to mix cache for system libraries and programs and cache for MXE libraries.

**Comment by tonytheodore** [comment]
I'm happy with #2273 for now, thanks for the tip @tehnick - there's no going back once you start using it.
