### ISSUE TITLE
CMake build is broken at 744f553022aabe5c9946828235b6a5dd9416a6d0

### ISSUE THREAD

**Issue by mgerhardy** [mxe/mxe#2275]
https://gist.github.com/mgerhardy/75bcd4db5010d3840f1ce7850eb49a04

**Comment by mgerhardy** [comment]
the log is outdated

the second try did it without problems. will try to investigate and if it pops up again, reopen this issue with updated log.

**Comment by mgerhardy** [comment]
A second try on building it as dependency of sdl_mixer worked fine. But just executing
```
make sdl2
make cmake
```
was broken (fresh clone)

**Comment by tonytheodore** [comment]
I can't replicate this in a debian:testing docker image, you could try:
```
make cmake cmake_CONFIGURE_OPTS=--system-libarchive
```
to bypass building the bundled version.

**Comment by highperformancecoder** [comment]
I submitted a PR upgrading cmake to latest version. This now builds fine.

**Comment by tonytheodore** [comment]
Cmake has since been updated.
