### ISSUE TITLE
Failed to build package ITK for target i686-w64-mingw32.shared

### ISSUE THREAD

**Issue by devoffice** [mxe/mxe#2277]
[ 84%] Linking CXX shared library ../../../../../../../bin/libitkgdcmMSFF-4.13.dll
cd /opt/mxe/tmp-itk-i686-w64-mingw32.shared/ITK-4.13.1.build_/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat && /opt/mxe/usr/x86_64-pc-linux-gnu/bin/cmake -E cmake_link_script CMakeFiles/gdcmMSFF.dir/link.txt --verbose=1
/opt/mxe/usr/x86_64-pc-linux-gnu/bin/cmake -E remove -f CMakeFiles/gdcmMSFF.dir/objects.a
/opt/mxe/usr/bin/i686-w64-mingw32.shared-ar cr CMakeFiles/gdcmMSFF.dir/objects.a @CMakeFiles/gdcmMSFF.dir/objects1.rsp
/opt/mxe/usr/bin/i686-w64-mingw32.shared-g++    -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel  -msse2 -mthreads -w -fno-ipa-cp-clone -O3 -DNDEBUG -Wl,--enable-runtime-pseudo-reloc   -mthreads -shared -Wl,--export-all-symbols -Wl,--enable-auto-import -o ../../../../../../../bin/libitkgdcmMSFF-4.13.dll -Wl,--out-implib,../../../../../../../lib/libitkgdcmMSFF-4.13.dll.a -Wl,--major-image-version,1,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/gdcmMSFF.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/gdcmMSFF.dir/linklibs.rsp
CMakeFiles/gdcmMSFF.dir/objects.a(gdcmJPEGLSCodec.cxx.obj):gdcmJPEGLSCodec.cxx:(.text+0x185): undefined reference to `_imp__JpegLsReadHeader@12'
CMakeFiles/gdcmMSFF.dir/objects.a(gdcmJPEGLSCodec.cxx.obj):gdcmJPEGLSCodec.cxx:(.text+0x533): undefined reference to `_imp__JpegLsEncode@24'
CMakeFiles/gdcmMSFF.dir/objects.a(gdcmJPEGLSCodec.cxx.obj):gdcmJPEGLSCodec.cxx:(.text+0x5d8): undefined reference to `_imp__JpegLsReadHeader@12'
CMakeFiles/gdcmMSFF.dir/objects.a(gdcmJPEGLSCodec.cxx.obj):gdcmJPEGLSCodec.cxx:(.text+0x660): undefined reference to `_imp__JpegLsDecode@20'
CMakeFiles/gdcmMSFF.dir/objects.a(gdcmJPEGLSCodec.cxx.obj):gdcmJPEGLSCodec.cxx:(.text+0xab6): undefined reference to `_imp__JpegLsEncode@24'
CMakeFiles/gdcmMSFF.dir/objects.a(gdcmJPEGLSCodec.cxx.obj):gdcmJPEGLSCodec.cxx:(.text+0xff5): undefined reference to `_imp__JpegLsEncode@24'
CMakeFiles/gdcmMSFF.dir/objects.a(gdcmJPEGLSCodec.cxx.obj):gdcmJPEGLSCodec.cxx:(.text+0x15ee): undefined reference to `_imp__JpegLsReadHeader@12'
CMakeFiles/gdcmMSFF.dir/objects.a(gdcmJPEGLSCodec.cxx.obj):gdcmJPEGLSCodec.cxx:(.text+0x169c): undefined reference to `_imp__JpegLsDecode@20'
collect2: error: ld returned 1 exit status
make[2]: *** [Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/CMakeFiles/gdcmMSFF.dir/build.make:2648: bin/libitkgdcmMSFF-4.13.dll] Error 1
make[2]: Leaving directory '/opt/mxe/tmp-itk-i686-w64-mingw32.shared/ITK-4.13.1.build_'
make[1]: *** [CMakeFiles/Makefile2:6129: Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/CMakeFiles/gdcmMSFF.dir/all] Error 2
make[1]: Leaving directory '/opt/mxe/tmp-itk-i686-w64-mingw32.shared/ITK-4.13.1.build_'
make: *** [Makefile:155: all] Error 2

uname -a
Linux homeWork1 4.20.5-arch1-1-ARCH #1 SMP PREEMPT Sat Jan 26 12:59:18 UTC 2019 x86_64 GNU/Linux

**Comment by tonytheodore** [comment]
ITK has since been updated and this is now fixed.
