### ISSUE TITLE
Support latest Eigen 3.3.7?

### ISSUE THREAD

**Issue by thehans** [mxe/mxe#2278]
I have an issue where including Eigen in some source files causes gcc to spit out many false warnings in non-Eigen code.  This only occurs when working with mingw.  I want to report this to Eigen project but they request that I test on the latest version before reporting a bug.

When i try to `make update-package-eigen` then build it, I get errors about missing patches
https://gist.github.com/thehans/57b30ec0a988b252c4e33b884ee09c76

**Comment by thehans** [comment]
Here is the related bug I have reported to mingw-w64:
https://sourceforge.net/p/mingw-w64/bugs/786/

Its hard to know where to report this sort of thing honestly.

**Comment by tonytheodore** [comment]
Eigen is [now updated to 3.3.7](https://github.com/mxe/mxe/commit/1df09125a67e39bed8356b93a612335c95bf8ab0). The patches are no longer required, but the subdirectory has a commit ref that needs to be manually updated.

I see you've raised the issue on the gcc list, that's probably the best option when you can find a minimal test case.
