### ISSUE TITLE
hello i am facing issue in mxe can anyone help me ? when i run make -f Makefile.Release i get this error

### ISSUE THREAD

**Issue by awaissakhi11** [mxe/mxe#2279]
xe/usr/i686-w64-mingw32.static/lib/libpcre2-16.a
/home/ubuntu/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lqrencode
/home/ubuntu/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_system-mgw49-mt-s-1_57
/home/ubuntu/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_filesystem-mgw49-mt-s-1_57
/home/ubuntu/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_program_options-mgw49-mt-s-1_57
/home/ubuntu/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lboost_chrono-mgw49-mt-s-1_57
collect2: error: ld returned 1 exit status
Makefile.Release:516: recipe for target 'release/A

**Comment by tonytheodore** [comment]
You are not using mxe instructions.
