### ISSUE TITLE
go script for recursive copy of DLL dependencies

### ISSUE THREAD

**Issue by r0l1** [mxe/mxe#2281]
I am working on a Qt binding for Go. During my tests the `copydlldeps.sh` script failed to find all valid dependencies and that's why I quickly created a small go helper tool. It outperforms the script and maybe somebody is interested to use it.

Here is the link: https://github.com/desertbit/gml/blob/master/cmd/gml-copy-dlls/main.go

Have fun

**Comment by tonytheodore** [comment]
Thanks, I've added a list in the docs https://github.com/mxe/mxe/commit/6fd7725950a38c0e1dcb68d5cdf28d32cf3b6e91
