### ISSUE TITLE
eigen 32bits fail to compile

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2288]
[gilles@localhost mxe]$ ./01-build-mxe.sh 
01-build-mxe.sh : build a bundle MXE install with digiKam dependencies.
-----------------------------------------------------------------------
Target Windows architecture: 32 bits.
CPU Cores to use : 7
/mnt/devel/GIT/6.x/project/bundles/mxe/build.win32 already exist. Do you want to remove it or to continue an aborted previous installation ? [(r)emove/(c)ontinue/(s)top] c
---------- Continue aborted previous installation in /mnt/devel/GIT/6.x/project/bundles/mxe/build.win32

---------- Updating MXE
Déjà à jour.

---------- Building digiKam low level dependencies with MXE
make: rien à faire pour « expat ».
[build]       eigen                  i686-w64-mingw32.shared

Failed to build package eigen for target i686-w64-mingw32.shared!
------------------------------------------------------------
Package 'eigen3', required by 'world', not found
/mnt/devel/GIT/6.x/project/bundles/mxe/build.win32/src/eigen-test.cpp:8:23: fatal error: Eigen/Dense: No such file or directory
compilation terminated.
Makefile:800 : la recette pour la cible « build-only-eigen_i686-w64-mingw32.shared » a échouée
make[1]: *** [build-only-eigen_i686-w64-mingw32.shared] Erreur 1
make[1] : on quitte le répertoire « /mnt/devel/GIT/6.x/project/bundles/mxe/build.win32 »
real    0m7.602s
user    0m6.472s
sys     0m0.802s
------------------------------------------------------------
[log]      /mnt/devel/GIT/6.x/project/bundles/mxe/build.win32/log/eigen_i686-w64-mingw32.shared

Makefile:800 : la recette pour la cible « /mnt/devel/GIT/6.x/project/bundles/mxe/build.win32/usr/i686-w64-mingw32.shared/installed/eigen » a échouée
make: *** [/mnt/devel/GIT/6.x/project/bundles/mxe/build.win32/usr/i686-w64-mingw32.shared/installed/eigen] Erreur 1
FAILED COMMAND: make MXE_TARGETS=$MXE_BUILD_TARGETS gcc gdb cmake gettext freeglut libxml2 libxslt libjpeg-turbo libpng tiff boost expat lcms liblqr-1 eigen jasper zlib mman-win32 pthreads qtbase qttranslations qtimageformats qtwebkit qttools qtwinextras qtscript ffmpeg openal libical opencv
[gilles@localhost mxe]$ 

Log file : 
https://gist.github.com/cgilles/2b75796ac2bd219bf803bd3e15507308

**Comment by tonytheodore** [comment]
I think I know what happened, the latest update doesn’t install the *.pc file.

**Comment by tonytheodore** [comment]
Actually, it defaults to non-standard `share` instead of `lib`. We can detect this by removing the previous install before building.

**Comment by cgilles** [comment]
Work fine now. Thanks...
