### ISSUE TITLE
gnutls build error ("missing separator.  Stop.")

### ISSUE THREAD

**Issue by CyberShadow** [mxe/mxe#2301]
```
Failed to build package gnutls for target x86_64-w64-mingw32.static!
------------------------------------------------------------
make -C '/tmp/2019-03-10/mxe/tmp-gnutls-x86_64-w64-mingw32.static/gnutls-3.6.6' -j '6' install
make[2]: Entering directory '/tmp/2019-03-10/mxe/tmp-gnutls-x86_64-w64-mingw32.static/gnutls-3.6.6'
Makefile:2057: *** missing separator.  Stop.
make[2]: Leaving directory '/tmp/2019-03-10/mxe/tmp-gnutls-x86_64-w64-mingw32.static/gnutls-3.6.6'
make[1]: *** [Makefile:820: build-only-gnutls_x86_64-w64-mingw32.static] Error 2
make[1]: Leaving directory '/tmp/2019-03-10/mxe'
real	1m28.764s
user	1m18.095s
sys	0m11.173s
------------------------------------------------------------
```

`settings.mk`:
```
JOBS := 12
MXE_TARGETS := x86_64-w64-mingw32.static
```

Log: https://dump.thecybershadow.net/25dfe36cfe157dca7d6bac066adff466/gnutls_x86_64-w64-mingw32.static

The bad line in the Makefile in question is:

```
@CODE_COVERAGE_RULES@
```

Looks like some kind of macro didn't run.

**Comment by tonytheodore** [comment]
Looks like the autoconf-archive package is overwriting the gnutls version of a macro:
```
aclocal: overwriting 'm4/ax_code_coverage.m4' with '/usr/share/aclocal/ax_code_coverage.m4'
```
and it needs [extra includes](https://github.com/autoconf-archive/autoconf-archive/blob/master/m4/ax_code_coverage.m4#L35).

Maybe a quick fix would be to try not installing these:
```diif
diff --git a/src/gnutls.mk b/src/gnutls.mk
index 3c49b7ee..219f5776 100644
--- a/src/gnutls.mk
+++ b/src/gnutls.mk
@@ -21,7 +21,7 @@ endef
 define $(PKG)_BUILD
     # AI_ADDRCONFIG referenced by src/serv.c but not provided by mingw.
     # Value taken from https://msdn.microsoft.com/library/windows/desktop/ms737530
-    cd '$(1)' && autoreconf -fi && ./configure \
+    cd '$(1)' && autoreconf -f && ./configure \
         $(MXE_CONFIGURE_OPTS) \
         --disable-rpath \
         --disable-nls \
```

**Comment by CyberShadow** [comment]
> Maybe a quick fix would be to try not installing these:

Unfortunately this patch did not seem to have an effect.

The [new log](https://dump.thecybershadow.net/b86f06da4600b5e771b92b5f290c199b/gnutls_x86_64-w64-mingw32.static) is a little different, but the line you quoted is still there.

**Comment by tonytheodore** [comment]
Maybe try `-i` without the `f` or just plain `autoreconf`.

**Comment by CyberShadow** [comment]
> Maybe try `-i` without the `f` or just plain `autoreconf`.

Same effect.

**Comment by tonytheodore** [comment]
Looks like it's [fixed upstream](https://gitlab.com/gnutls/gnutls/merge_requests/905), try https://github.com/mxe/mxe/commit/1d4ac6200698bed9187e1c5b5b85840e538dc30a

**Comment by CyberShadow** [comment]
That worked, thank you!
