### ISSUE TITLE
Downgrade Openssl Version to MXE

### ISSUE THREAD

**Issue by mastercoincore** [mxe/mxe#2303]
Hello,
How I can downgrade openssl version to mxe?
There is openssl 1.1 and I need openssl1.0.1.

I already tried this:
cd /mnt/mxe/src
sudo nano openssl.mk
Search for the following lines

$(PKG)_VERSION := 1.1.0h
$(PKG)_CHECKSUM := 5835626cde9e99656585fc7aaa2302a73a7e1340bf8c14fd635a62c66802a517

Change the lines of code to

$(PKG)_VERSION := 1.0.2n
$(PKG)_CHECKSUM := 370babb75f278c39e0c50e8c4e7493bc0f18db6867478341a832a982fd15a8fe

but that gives me errors: 
[build]       openssl                i686-w64-mingw32.static
 
Failed to build package openssl for target i686-w64-mingw32.static!
------------------------------------------------------------
Makefile:287: recipe for target 'build_crypto' failed
make[2]: *** [build_crypto] Error 1
make[2]: Leaving directory '/mnt/mxe/tmp-openssl-i686-w64-mingw32.static/openssl-1.0.2n'
Makefile:813: recipe for target 'build-only-openssl_i686-w64-mingw32.static' failed
make[1]: *** [build-only-openssl_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory '/mnt/mxe'
real    0m6.979s
user    0m5.964s
sys     0m1.195s
------------------------------------------------------------
[log]      /mnt/mxe/log/openssl_i686-w64-mingw32.static
 
Makefile:813: recipe for target '/mnt/mxe/usr/i686-w64-mingw32.static/installed/openssl' failed
make: *** [/mnt/mxe/usr/i686-w64-mingw32.static/installed/openssl] Error 1

Thanks for your help!

**Comment by tonytheodore** [comment]
Try:
```
make openssl1.0 MXE_PLUGIN_DIRS=plugins/examples/openssl1.0/
```

**Comment by thepcb** [comment]
That command works.
Do I need "make qt" also?
Make qt makes same error that I posted before. 
Make openssl1.0 MXE_Plugin... works fine.
Thank you
