### ISSUE TITLE
unable to build binutils

### ISSUE THREAD

**Issue by Jan200101** [mxe/mxe#2305]
compiling binutils or anything requiring binutils results in this
https://gist.github.com/Jan200101/53a5b0fd7dcd24ed8925460b3932a742
this only occurs after running  `make update`

**Comment by tonytheodore** [comment]
The patch may have been (partially) accepted upstream and doesn't apply to later versions - that's generally expected after an update.

**Comment by tonytheodore** [comment]
What isn't expected is the `Don't use network from MXE build rules!`, it seems bizarre that `tar` would be accessing an external network.

**Comment by Jan200101** [comment]
seems to be fixed
