### ISSUE TITLE
"Failed to build package ccache for target i686-w64-mingw32.static!"

### ISSUE THREAD

**Issue by koutoftimer** [mxe/mxe#2306]
1. Cloned mxe to `/srv/git/mxe`.
2. Started `$ make`.
3. Got an error.

[Log and `script` record](https://gist.github.com/koutoftimer/a735c50afd2fdda3b7a5aae090bacd14)

**Comment by tonytheodore** [comment]
This error is strange:
```
bash: ./ext/config.guess: /bin/sh^M: bad interpreter: No such file or directory
```

Is there really no `/bin/sh` on your system?

**Comment by koutoftimer** [comment]
@tonytheodore 
```bash
$ ll /bin/sh
lrwxrwxrwx 1 root root 4 Oct  4 02:54 /bin/sh -> dash*
$ ll /bin/dash
-rwxr-xr-x 1 root root 117208 Jan 24  2017 /bin/dash*

```

**Comment by tonytheodore** [comment]
Can you run `./ext/config.guess` from a normal shell?

**Comment by koutoftimer** [comment]
@tonytheodore using bash
```bash
$ . ext/config.guess
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: ext/config.guess: line 63: syntax error near unexpected token `$'in\r''
'ash: ext/config.guess: line 63: `  case $1 in
```

**Comment by koutoftimer** [comment]
@tonytheodore I have used this [advice](https://coderwall.com/p/qgyqfw/fixing-vagrant-on-windows-bin-sh-m-bad-interpreter) and now it starts without a problem. Just saved file after `set fileformat=unix`.

```bash
$ ./ext/config.guess
x86_64-pc-linux-gnu
```

**Comment by koutoftimer** [comment]
Looks like you have to change line ending for entire repository. I suppose this [SO answer](https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings#answer-40821931) should do the trick.

**Comment by koutoftimer** [comment]
My question is solved, but it looks like code changes required.

**Comment by koutoftimer** [comment]
Ok, so it was **MY** mistake. I had [`core.autocrlf = true`][git-autocrlt] on my linux machine...

You can clone an issue, maybe after adding this into FAQ.

[git-autocrlt]: https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code

**Comment by tehnick** [comment]
@tonytheodore Ping? You may close this issue.

**Comment by tonytheodore** [comment]
@koutoftimer can you raise a PR for the doc updates?
