### ISSUE TITLE
pkg.mxe.cc potential security issue

### ISSUE THREAD

**Issue by vranki** [mxe/mxe#2312]
Browsing to https://pkg.mxe.cc/ on Firefox causes a warning 

"Warning: Potential Security Risk Ahead

Firefox detected a potential security threat and did not continue to pkg.mxe.cc. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details."

What's the deal with this? Has the server been compromised? If so, this may mean any apps built with packages in the repository may have been backdoored.

**Comment by jonaski** [comment]
No its because the SSL certificate is issued to mirror.mxe.cc and doesnt include pkg:
https://mirror.mxe.cc/

**Comment by vranki** [comment]
Ok. Perhaps the links at https://mxe.cc/ should point to https://mirror.mxe.cc/ then?

**Comment by Kaos-Industries** [comment]
Came here to report this very thing. It was my intention to point people towards MXE as a solution in a medium that is likely to reach a fair amount of people over time, but I can't knowingly do that until this issue has been fixed.

**Comment by tonytheodore** [comment]
My holdup, I thought I needed to find some time to research but it was actually very straightforward. I've now added `pkg.mxe.cc` to the certificate:

```
$ sudo certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name: mirror.mxe.cc
    Domains: mirror.mxe.cc pkg.mxe.cc
    Expiry Date: 2019-06-28 00:06:31+00:00 (VALID: 89 days)
    Certificate Path: /etc/letsencrypt/live/mirror.mxe.cc/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/mirror.mxe.cc/privkey.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```
