### ISSUE TITLE
Build debian packages to newer distributions

### ISSUE THREAD

**Issue by vranki** [mxe/mxe#2313]
Current mxe packages are for ubuntu xenial / debian stretch. There's new LTS ubuntu (bionic) which is soon one year old. Stretch is also quite aged so it might be good to distribute packages for buster already.

**Comment by tonytheodore** [comment]
My [current plan](https://github.com/mxe/mxe/issues/2253#issuecomment-469586644) is to support Ubuntu LTS (trusty, xenial, bionic) and Debian old stable, stable, and testing (jessie, stretch, buster) - it's just a matter of time;)
