### ISSUE TITLE
Why does x86_64-unknown-cygwin seem to be building by default?

### ISSUE THREAD

**Issue by Kaos-Industries** [mxe/mxe#2314]
I'm trying to build a few packages with MXE on Cygwin with the end goal of compiling FFmpeg (which so far I've had no luck doing using both Cygwin itself, a MinGW-W64 cross-compile toolchain on Cygwin, or MSYS2).

I just ran:

`make MXE_TARGETS="x86_64-w64-mingw32.static" lame libass libvpx ogg opus sdl2 theora vorbis x264`

However, based on what I understand of the output that I'm getting, it seems that MXE is compiling packages for both my target and for `unknown_cygwin`. Can you confirm whether this is the case, and if so, how to disable this behaviour so I only get compiled versions for `x86_64-w64-mingw32.static`?

Here is the output I have so far:

> [check reqs]
> [download]    binutils-2.28.tar.bz2
> [nonet lib]   /usr/mxe/usr/x86_64-unknown-cygwin/lib/nonetwork.so               
> [git-log]   5fc2cfc5 Update packages.json & build-matrix.html
> [build]       mxe-conf               x86_64-w64-mingw32.static
> [done]        mxe-conf               x86_64-w64-mingw32.static                              0 KiB          0m11.250s
> [download]    ccache-3.6.tar.xz
> [build]       mxe-conf               x86_64-unknown-cygwin
> [done]        mxe-conf               x86_64-unknown-cygwin                                  0 KiB          0m11.348s
> [build]       ccache                 x86_64-unknown-cygwin
> [done]        ccache                 x86_64-unknown-cygwin                                  4820 KiB       0m58.006s
> [build]       ccache                 x86_64-w64-mingw32.static
> [done]        ccache                 x86_64-w64-mingw32.static                              2207 KiB       0m13.567s
> [build]       binutils               x86_64-w64-mingw32.static
> [done]        binutils               x86_64-w64-mingw32.static                              511605 KiB     11m13.190s
> [download]    mingw-w64-v6.0.0.tar.bz2
> [build]       mingw-w64              x86_64-w64-mingw32.static
> [done]        mingw-w64              x86_64-w64-mingw32.static                              4 KiB          0m11.766s
> [download]    gmp-6.1.2.tar.xz
> [build]       gmp                    x86_64-unknown-cygwin
> [done]        gmp                    x86_64-unknown-cygwin                                  27478 KiB      7m50.532s
> [download]    isl-0.15.tar.bz2
> [build]       isl                    x86_64-unknown-cygwin
> make MXE_TARGETS="x86_64-w64-mingw32.static" lame libass libvpx ogg opus sdl2 theora vorbis x264
> [done]        isl                    x86_64-unknown-cygwin                                  37824 KiB      3m11.142s
> [download]    mpfr-3.1.5.tar.xz
> [build]       mpfr                   x86_64-unknown-cygwin

Thanks in advance.

**Comment by tonytheodore** [comment]
Yes, that is the correct behaviour. mxe needs to build some native tools and libraries in order to build the cross toolchain and libraries. e.g. the cross-gcc is a native program that requires native libs for gmp, isl, mpc, and mpfr - there's no way to disable these. In this particular case, the sources for those libs could be unpacked into the gcc build tree, but that would mean they are build multiple times unnecessarily.

See also https://github.com/mxe/mxe/issues/2285#issuecomment-466278520.

**Comment by Kaos-Industries** [comment]
Brilliant, thanks again for your prompt responses to all of my issues.
