### ISSUE TITLE
Build failure: gnutls MXE_TARGETS="i686-w64-mingw32.static"

### ISSUE THREAD

**Issue by lotharsm** [mxe/mxe#2318]
Since the last update of the gnutls package, building gnutls for i686-w64-mingw32.static fails during the linking stage complaining about function gnutls_x509_cidr_to_rfc5280.

x86_64-w64-mingw32.static is *not* affected. Before the latest update, I was able to compile gnutls without any problems on the same system. 

Since gnutls is a depency of curl, curl is currently also broken. Again, no issues on x86_64.

Am I missing something here?

Log:
https://gist.githubusercontent.com/lotharsm/1d530fea4208d8e1ccb546a1ef077782/raw/eb04a3082233e7e34b56a1a2fb40f7bde27b61fa/gistfile1.txt

**Comment by CHLLHC** [comment]
Same thing on my end, undefined `inet_pton`

**Comment by tonytheodore** [comment]
Can you compare the output of:
```
i686-w64-mingw32.static-pkg-config gnutls --cflags --libs
# and
x86_64-w64-mingw32.static-pkg-config gnutls --cflags --libs
```
the new update specifically adds `@INET_PTON_LIB@` to the *.pc file.

**Comment by tonytheodore** [comment]
Hmmm, `inet_pton` is wrapped in `#if (_WIN32_WINNT >= 0x0600)` in the current mingw headers. I'll remove those manual flags and see what happens.

**Comment by tonytheodore** [comment]
That has no affect and I can't see anything particularly different in the x86_64 build.

**Comment by lotharsm** [comment]
> Can you compare the output of:

Sure! Seems like they are identical:

```
i686-w64-mingw32.static-pkg-config gnutls --cflags --libs
-lgnutls -lhogweed -lnettle -lidn2 -lws2_32  -latomic -lcrypt32 -lgmp -lunistring -liconv -lcharset
```

```
./x86_64-w64-mingw32.static-pkg-config gnutls --cflags --libs
-lgnutls -lhogweed -lnettle -lidn2 -lws2_32  -latomic -lcrypt32 -lgmp -lunistring -liconv -lcharset
```

**Comment by tonytheodore** [comment]
Someone [already reported it upstream](https://gitlab.com/gnutls/gnutls/issues/745) and it may be a packaging bug. I'm inclined to revert the update and wait for the next release.
