### ISSUE TITLE
Document GNU make requirement

### ISSUE THREAD

**Issue by cup** [mxe/mxe#2320]
I see that **define** is used in some places, for example:

https://github.com/mxe/mxe/blob/61875bd32dd1148e265b0c818ef87b672f811852/src/a52dec.mk#L14-L18

**define** is not specified by POSIX:

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html

so it might be helpful to document that MXE requires GNU Make.

**Comment by ashkulz** [comment]
I think it's pretty well documented in the [Usage section](https://mxe.cc/#usage).

**Comment by cup** [comment]
where is the source code for that page?

**Comment by ashkulz** [comment]
See [docs/index.html](https://github.com/mxe/mxe/blob/ea56b37/docs/index.html#L1143) in this repo.

**Comment by tonytheodore** [comment]
I've [changed the intro to `GNU Makefile`](https://github.com/mxe/mxe/commit/77c804b840757654007f5c48063cd0a4fc491fca) - `define` is used everywhere.
