### ISSUE TITLE
Fails to Build OCE on MacOS Mojave

### ISSUE THREAD

**Issue by sandboxgod** [mxe/mxe#2321]
I am unable to build oce on MacOS Mojave 10.14. You can view the log here:
https://gist.github.com/sandboxgod/8d06c6260f2c27a5ac2fd053f22cfc33

This is the command I typed to build oce:
make MXE_TARGETS='x86_64-w64-mingw32.static' oce

The other packages I needed to build have worked fine such as Qt5.12 ad others.

Thanks

**Comment by tonytheodore** [comment]
Very strange, it's working here on 10.14.4. It's failing at the test program with what looks like cmake being unable to find a library. If that's the case, it should have failed earlier during cmake's configure step.

Can you make a tarball of the contents of:
"/Users/robo/homebrew/opt/mxe/tmp-oce-x86_64-w64-mingw32.static/oce-OCE-0.18.2/examples/find_package_oce"?

**Comment by sandboxgod** [comment]
Sure, I uploaded the tar file here:
[oce.tar.gz](https://github.com/mxe/mxe/files/3054716/oce.tar.gz)

**Comment by tonytheodore** [comment]
I see, it's finding a native install in `/usr/local/OCE.framework/`. I have a PR (#2097) that will fix this with `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY` but I'm not sure why it's still WIP - I'll do some further testing.

**Comment by sandboxgod** [comment]
Excellent! Thanks a lot it appears to have built successfully.
