### ISSUE TITLE
libgpg_error does not build on MacOS

### ISSUE THREAD

**Issue by markghayden** [mxe/mxe#2323]
There is problem building libgpg_error on MacOS (Xcode 10.2.1).  Please see log file below.

thanks, Mark

https://gist.github.com/markghayden/fe3b69e56c5e5fbd80ade8e65263ee68

**Comment by tonytheodore** [comment]
What version of `gawk` do you have?
```
$ which gawk
/opt/local/bin/gawk
$ gawk --version
GNU Awk 4.2.1, API: 2.0
Copyright (C) 1989, 1991-2018 Free Software Foundation.
```

**Comment by markghayden** [comment]
—Mark


% which gawk
/usr/local/bin/gawk
sakhalin% gawk --version
GNU Awk 5.0.0, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)
Copyright (C) 1989, 1991-2019 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.

**Comment by tonytheodore** [comment]
I've added the [upstream fix](https://dev.gnupg.org/rE7865041c77f4f7005282f10f9b6666b19072fbdf).

**Comment by markghayden** [comment]
Thanks!  I confirm the problem is fixed.
