### ISSUE TITLE
can't build dream - linker error

### ISSUE THREAD

**Issue by jcable** [mxe/mxe#2334]
I made a prototype package file to help describe the environment: https://github.com/jcable/mxe/blob/master/src/dream.mk 

The error is:

collect2: fatal error: ld terminated with signal 11 [Segmentation fault: 11]
compilation terminated.
make[1]: *** [release/dream.exe] Error 1
make: *** [release] Error 2

I get this on my Mac and on a clean ubuntu 18.04 LTS server running in virtual box and using the MXE Debian packages.

The dream.mk doesn't actually seem to try to do the build but it does create the environment so you can reproduce the problem with

make dream
cd tmp-dream-i686-w64-mingw32.static/dream-2.2
make

**Comment by tonytheodore** [comment]
The`# define DLL_EXPORT 1` line from `dream-2.2/src/GlobalDefinitions.h` shouldn't be defined for static builds.

> The dream.mk doesn't actually seem to try to do the build

There's no `install` target.

**Comment by jcable** [comment]
Thanks Tony - no the dream.mk is a work in progress but the DLL_EXPORT hint might help me.

Thanks.

**Comment by jcable** [comment]
No, I undefined that and got the same error. I've updated my dream.mk so it does try to build now.

**Comment by jcable** [comment]
I've added an install target in the .pro file for an mxe build and updated the tarball with these changes and updated the sha256 in the dream.mk. So in theory if the linker problem went away this might be a complete dream.mk.
