### ISSUE TITLE
Upgrade ImageMagick 6.9.0-0 to last stable 7.0.8

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2335]
ImageMagick package in MXE still a very old version 6.9.0.

New one is 7.0.8 commng with plenty of new format supported (XCF compressed, HEIF, FITS, etc...)

Please update this package. If 7.0.8 has problems to compile under MXE due to changes of API from 6 to 7, at least please upgrade to last 6.9.10-44, as this serie still maintained with API compatibility

Thanks in advance

Gilles Caulier

**Comment by tonytheodore** [comment]
see #2336

**Comment by cgilles** [comment]
#2336 sous fine for me to be applied on master

**Comment by cgilles** [comment]
Any news about #2336 pull request integration in master ?
Thanks in advance
Gilles Caulier

**Comment by tonytheodore** [comment]
It breaks downstream package `cimg` and I have no familiarity with either project. Can you check if it's an easy fix?

**Comment by cgilles** [comment]
Where is the trace of the CI about the CImg broken package ?

Gilles Caulier

**Comment by cgilles** [comment]
MXE has a very old CImg version, later than IM 7.x was released with API changes. Please try to update CImg to last 2.6.2 which have been released in May 2019 and must support IM 7 API.

Gilles Caulier

**Comment by dlang123** [comment]
Any news on this?

**Comment by Tuxie** [comment]
This is apparently a blocker for enabling .heic image support in the Windows version of DigiKam.

**Comment by cgilles** [comment]
yes exactly...

**Comment by cgilles** [comment]
Hi,

Thanks to upgrade IM to version 7.

I recompiled digiKam from scratch with MXE this morning. The 32 bits target do not compile and the broken stage appear in IM : 

---------- Building digiKam extra dependencies with MXE
[download]    fftw-3.3.8.tar.gz
[build]       fftw                   i686-w64-mingw32.shared
[done]        fftw                   i686-w64-mingw32.shared                                  53208 KiB      2m39.309s
[build]       libltdl                i686-w64-mingw32.shared
[done]        libltdl                i686-w64-mingw32.shared                                  9428 KiB       0m10.046s
[download]    ilmbase-2.2.0.tar.gz
[build]       ilmbase                i686-w64-mingw32.shared
[done]        ilmbase                i686-w64-mingw32.shared                                  9952 KiB       0m15.508s
[download]    openexr-2.2.0.tar.gz
[build]       openexr                i686-w64-mingw32.shared
[done]        openexr                i686-w64-mingw32.shared                                  88624 KiB      1m50.467s
[download]    imagemagick-7.0.8-63.tar.gz
[build]       imagemagick            i686-w64-mingw32.shared

Failed to build package imagemagick for target i686-w64-mingw32.shared!
------------------------------------------------------------
Makefile:5963: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/mnt/data/GIT/6.x/project/bundles/mxe/build.win32/tmp-imagemagick-i686-w64-mingw32.shared/ImageMagick-7.0.8-63.build_'
Makefile:812: recipe for target 'build-only-imagemagick_i686-w64-mingw32.shared' failed
make[1]: *** [build-only-imagemagick_i686-w64-mingw32.shared] Error 2
make[1]: Leaving directory '/mnt/data/GIT/6.x/project/bundles/mxe/build.win32'
real    0m36.155s
user    0m30.611s
sys     0m11.416s
------------------------------------------------------------
[log]      /mnt/data/GIT/6.x/project/bundles/mxe/build.win32/log/imagemagick_i686-w64-mingw32.shared

Makefile:812: recipe for target '/mnt/data/GIT/6.x/project/bundles/mxe/build.win32/usr/i686-w64-mingw32.shared/installed/imagemagick' failed
make: *** [/mnt/data/GIT/6.x/project/bundles/mxe/build.win32/usr/i686-w64-mingw32.shared/installed/imagemagick] Error 1
FAILED COMMAND: make MXE_TARGETS=$MXE_BUILD_TARGETS imagemagick

See IM log file for details:

[imagemagick_i686-w64-mingw32.shared.log](https://github.com/mxe/mxe/files/3586617/imagemagick_i686-w64-mingw32.shared.log)

**Comment by tonytheodore** [comment]
Please ensure you enclose terminal output in triple-backticks.

It seems to be detecting a native `libheif` but I can't see how.

**Comment by cgilles** [comment]
You are right. heif is expected to be compiled using MXE just before IM to include this codec, but there is a mistake in cmake script. I will fix it and try again.

**Comment by cgilles** [comment]
For information: in digiKam Windows bundle scrip, i cross-compile now libheif and libde265 before to install ImageMagick 7 with MXE. With some fix in libde265 to compile fine, it works.

If you is interested to add officially HEIF support in ImageMagick under MXE project look my adjustments here: 

https://invent.kde.org/kde/digikam/tree/master/project/bundles/3rdparty/ext_heif

Gilles Caulier
