### ISSUE TITLE
Module MQTT

### ISSUE THREAD

**Issue by clementlgl** [mxe/mxe#2337]
Hi, 
I'm trying to build program with mqtt module and error showing up:
Project MESSAGE: Warning: unknown QT: mqtt

I installed the `QtMQTT` module with the following commands:
```
git clone https://code.qt.io/qt/qtmqtt.git
cd qmqtt
mkdir build
cd build
~/Qt/5.10.1/gcc_64/bin/qmake qmake -r ..
```

Any suggestions?
Thank you

**Comment by tonytheodore** [comment]
That isn't an mxe version of `qmake`, build you program using the same qmake you used to build mqtt.

**Comment by clementlgl** [comment]
@tonytheodore thank you for your reply.

But when I compile a project with mqtt, I have the following error 
```
~/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake .
Project ERROR: Unknown module(s) in QT: mqtt
```
To build with the mxe cross toolchain, `qtmqtt` must be included in this one. And currently it is not compiled, I think a plugin should be added.

Can you confirm if I understand correctly 

Thank you
Clément
