### ISSUE TITLE
configure: error: Cannot find OpenSSL libraries

### ISSUE THREAD

**Issue by rgatti508** [mxe/mxe#2344]
Hi,
Can any one help me to fix this issue while making qt5
make qt5
fatal: Not a git repository (or any parent up to mount point /global/freeware)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[build]       freetds                i686-w64-mingw32.static

Failed to build package freetds for target i686-w64-mingw32.static!
------------------------------------------------------------
checking size of SQLWCHAR... 2
checking if openssl is wanted... yes
checking for OPENSSL... no
configure: error: Cannot find OpenSSL libraries
make[1]: *** [build-only-freetds_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory `/opt/mxe'
real	5m56.848s
user	1m4.958s
sys	2m11.648s
------------------------------------------------------------
[log]      /opt/mxe/log/freetds_i686-w64-mingw32.static

make: *** [/opt/mxe/usr/i686-w64-mingw32.static/installed/freetds] Error 1

**Comment by tehnick** [comment]
@tonytheodore Probably this issue may be closed.

**Comment by tonytheodore** [comment]
Agreed, I've updated the [issue template](https://github.com/mxe/mxe/commit/3860b273e42ca36d763aca7befdaa133e66ef520).
