### ISSUE TITLE
[pkg.mxe.cc] Update Qt5 to 5.12.3

### ISSUE THREAD

**Issue by bugwelle** [mxe/mxe#2346]
Hi,

I hope this is the right place and not too much to ask for :)

Currently, pkg.mxe.cc and mirror.mxe.cc provide Qt 5.12.1 which has some serious issues with multithreading, i.e. any use of `QLocale::system()` is unsafe and may lead to applications crashing. This makes any use of `QDate` and `QDateTime` unsafe as well.
An application that I'm working on crashes on startup due to this issue.

Qt issue: https://bugreports.qt.io/browse/QTBUG-73403

Is it possible to update Qt's binary packages on pkg.mxe.cc? :)
if there's anything I can do to help, please let me know.

Thank you. :)

**Comment by bugwelle** [comment]
Hi,

thanks for your reply. 
I've noticed that Qt is up-to-date in this repository but not on pkg.mxe.cc. I'm not talking about this Git repository but about the binary distribution of mxe packages which can be consumed with `apt-get install mxe-...` on Debian based systems :-)

Example:
```sh
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
$ sudo add-apt-repository 'deb [arch=amd64] https://mirror.mxe.cc/repos/apt bionic main'
$ apt search mxe-i686-w64-mingw32.shared-qt5               
Sorting... Done
Full Text Search... Done
mxe-i686-w64-mingw32.shared-qt5/unknown 5.12.1-bionic-20190331 amd64
  MXE package qt5 for i686-w64-mingw32.shared
```


Regards,
Andre

**Comment by mabrand** [comment]
Apparently there are some problems with pkg.mce.cc. See https://github.com/mxe/mxe/issues/2253.

Have you considered building MXE from source? (Instructions at https://mxe.cc/.)

I'll close this for now since it looks like a dupe of #2253.

**Comment by bugwelle** [comment]
Hi,

thanks. I know of that issue and have been following it since last year. mirror.mxe.cc was set up as a working alternative and now even pkg.mxe.cc works again. Prior to pkg.mxe.cc being offline, it provided Qt 5.8, so it's been updated since then. :-)

This isn't a duplicate of #2253. I'm not saying that pkg.mxe.cc is down or isn't working or anything.
I'm asking if it's possible to update the binaries of Qt5 (and maybe others). I can't find any information on mxe.cc about how often the packages are updated and am therefore asking here. :-)
As per https://github.com/mxe/mxe/issues/2253#issuecomment-449968117 issue #2253 is mostly resolved.

I'm using pkg.mxe.cc for some TravisCI projects. For releasing new versions my projects, I'm using this GitHub repository and am building mxe myself (works great!).

Regards,
Andre

**Comment by mabrand** [comment]
Let's see if someone involved with the binaries can help..

**Comment by tonytheodore** [comment]
I've created the next [build tag](https://github.com/mxe/mxe/releases/tag/build-2019-06-02) with two broken packages:
itk i686-w64-mingw32.shared
xmlsec i686-w64-mingw32.shared

and started the package builds (can take 30-40 hours)

**Comment by tonytheodore** [comment]
bionic, stretch, and xenial are now updated, trusty is running again but [we'll drop support for it soon](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment).

**Comment by bugwelle** [comment]
Thank you very much! :smiley:
