### ISSUE TITLE
compiling in mac high sierra

### ISSUE THREAD

**Issue by sherifomran** [mxe/mxe#2352]
Failed log in this link
https://gist.github.com/sherifomran/116ecc90f5250c6baa9ea33505105c90

this is the result i got, i installed the required packages with brew (as given on the website) and then git clone to download the latest version and gave make

Failed to build package pkgconf for target x86_64-apple-darwin17.7.0!
------------------------------------------------------------
-n *info* running aclocal
autom4te: need GNU m4 1.4 or later: /opt/local/bin/gm4
aclocal: error: echo failed with exit status: 1
*error* aclocal failed. (exit code = 1)
make[1]: *** [build-only-pkgconf_x86_64-apple-darwin17.7.0] Error 1
real	0m31.911s
user	0m20.317s
sys	0m1.733s
------------------------------------------------------------
[log]      /Users/sherifomran/Downloads/mxe/log/pkgconf_x86_64-apple-darwin17.7.0

make: *** [/Users/sherifomran/Downloads/mxe/usr/x86_64-apple-darwin17.7.0/installed/pkgconf] Error 1

**Comment by tonytheodore** [comment]
You possibly have a mismatch of macports and homebrew if it's looking for `/opt/local/bin/gm4`. You can try building an mxe-specific autotools with:

```
make autotools MXE_PLUGIN_DIRS=plugins/native MXE_TARGETS=
```

then continue with the `make` invocation you first tried.

**Comment by sherifomran** [comment]
yes i had an old version of ports installed and i switched to brew. I checked the ~/.bash_profile file and removed the /opt/local path from it, there was a comment it is from macports. Unfortunately, this took me very long time to determine and solve before i get your comment.

i found when i export path /usr/local/cellar/automake/1.16xxxx/bin and /usr/local/cellar/autoconf/2.69/bin and the call the aclocal it works 

but the next step is how to compile qt and create the exe file?

**Comment by sherifomran** [comment]
now i get this error

Failed to build package a52dec for target i686-w64-mingw32.static!
------------------------------------------------------------
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2
libtool: and run autoconf again.
build]       autotools              x86_64-apple-darwin17.7.0
[done]        autotools              x86_64-apple-darwin17.7.0                              312 KiB        0m15.043s
[build]       a52dec                 i686-w64-mingw32.static

Failed to build package a52dec for target i686-w64-mingw32.static!
------------------------------------------------------------
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2
libtool: and run autoconf again.
make[3]: *** [bitstream.lo] Error 63
make[2]: *** [all-recursive] Error 1
make[1]: *** [build-only-a52dec_i686-w64-mingw32.static] Error 2
real	0m33.368s
user	0m23.782s
sys	0m7.302s
------------------------------------------------------------
[log]      /opt/mxe/log/a52dec_i686-w64-mingw32.static

make: *** [/opt/mxe/usr/i686-w64-mingw32.static/installed/a52dec] Error 1

i found when i export path /usr/local/cellar/automake/1.16xxxx/bin and /usr/local/cellar/autoconf/2.69/bin and the call the aclocal it works 

but the next step is how to compile qt and create the exe file?

**Comment by sherifomran** [comment]
I made sure to add the path of other components from brew: The next issue is:
```
Sherif:mxe sherifomran$ make
[build]       glibmm                 i686-w64-mingw32.static

Failed to build package glibmm for target i686-w64-mingw32.static!
------------------------------------------------------------
make[2]: *** Deleting file `.stamps/action.stamp'
make[2]: *** [.stamps/actionmap.stamp] Error 134
make[2]: *** Deleting file `.stamps/actionmap.stamp'
make[2]: *** [.stamps/actiongroup.stamp] Error 134
make[2]: *** Deleting file `.stamps/actiongroup.stamp'
make[1]: *** [build-only-glibmm_i686-w64-mingw32.static] Error 2
real	0m31.180s
user	0m25.193s
sys	0m8.977s
------------------------------------------------------------
[log]      /opt/mxe/log/glibmm_i686-w64-mingw32.static

```

when i checked the error log it says
`/usr/bin/perl -I../../tools/pm -- ../../tools/gmmproc -I ../../tools/m4 --defs . actiongroup . ../giomm
sh: line 1: 45963 Abort trap: 6           gm4 -I../../tools/m4 -I/opt/mxe/usr/i686-w64-mingw32.static/lib/glibmm-2.4/proc/m4 "/tmp/gtkmmproc_45960.g1"$
m4 failed with exit code 134.  Aborting...
sh: line 1: 45967 Abort trap: 6           gm4 -I../../tools/m4 -I/opt/mxe/usr/i686-w64-mingw32.static/lib/glibmm-2.4/proc/m4 "/tmp/gtkmmproc_45958.g1"$
sh: line 1: 45970 Abort trap: 6           gm4 -I../../tools/m4 -I/opt/mxe/usr/i686-w64-mingw32.static/lib/glibmm-2.4/proc/m4 "/tmp/gtkmmproc_45959.g1"$
m4 failed with exit code 134.  Aborting...
make[2]: *** [.stamps/applaunchcontext.stamp] Error 134
make[2]: *** Deleting file `.stamps/applaunchcontext.stamp'
make[2]: *** Waiting for unfinished jobs....
sh: line 1: 45975 Abort trap: 6           gm4 -I../../tools/m4 -I/opt/mxe/usr/i686-w64-mingw32.static/lib/glibmm-2.4/proc/m4 "/tmp/gtkmmproc_45961.g1"$
m4 failed with exit code 134.  Aborting...
m4 failed with exit code 134.  Aborting...
make[2]: *** [.stamps/action.stamp] Error 134
make[2]: *** Deleting file `.stamps/action.stamp'
make[2]: *** [.stamps/actionmap.stamp] Error 134
make[2]: *** Deleting file `.stamps/actionmap.stamp'
make[2]: *** [.stamps/actiongroup.stamp] Error 134
`

**Comment by tonytheodore** [comment]
```
Abort trap: 6 gm4 -I../..
```
You have two conflicts, `/opt/local/bin` and g* prefixed tools. I'd recommend against adding paths of individual components - you shouldn't need to touch `$PATH` to build mxe, only to use it (and that is a single path addition of `${mxe_dir}/usr/bin`).

I've [made it the default to build mxe-specific versions of autotools on darwin](https://github.com/mxe/mxe/commit/3db4dc3a44cfe0069886b5c09a5b9d11680af3f5). After a `git pull`, you should see `m4` being built - if not, stop the build and start again with a `make clean`.

P.S. please ensure you quote all log or terminal output in triple-backticks

**Comment by sherifomran** [comment]
ok i started from the begining

removing all macport traces
`sudo rm -rf \
        /opt/local \
        /Applications/DarwinPorts \
        /Applications/MacPorts \
        /Library/LaunchDaemons/org.macports.* \
        /Library/Receipts/DarwinPorts*.pkg \
        /Library/Receipts/MacPorts*.pkg \
        /Library/StartupItems/DarwinPortsStartup \
        /Library/Tcl/darwinports1.0 \
        /Library/Tcl/macports1.0 \
        ~/.macports`

removing all mxe folder
`sudo rm -rf mxe`

current path
echo $PATH

`/usr/local/bin:/usr/local/opt:/usr/lib/libpc:/usr/local/Cellar/libtool/2.4.6_1/bin/glibtool:/usr/local/Cellar/pcre/8.43/lib:/usr/local/Cellar/pcre/8.43/bin:/usr/local/sbin:/usr/local/opt/sqlite/bin:/usr/local/Qt-5.12.0/bin:/System/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/Cellar/autoconf/2.69/bin:/usr/local/Cellar/automake/1.16.1_1/bin:/usr/local/Cellar/m4/1.4.18/bin:/usr/local/Cellar/libtool/2.4.6_1/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands`

```
cd /opt
sudo git clone https://github.com/mxe/mxe.git
```

```
cd mxe
sudo make
```

**Comment by tonytheodore** [comment]
Stop that build, you never want to use `sudo` with mxe unless you know you have a reason.

**Comment by sherifomran** [comment]
i used it because the script tries to create and enviroment file but complained from the permission.
Ok, I changed the used of the foler
`sudo chown sherifomran mxe`

```Sherif:~ sherifomran$ ls -l | grep mxe
drwxrwxrwx   18 sherifomran  staff       612 Jun 24 14:43 mxe```

**Comment by tonytheodore** [comment]
```
-bash: /usr/local/bin/autoheader: /opt/local/bin/perl: bad interpreter: No such file or directory
```
again, look at your path mismatches. I can't help you with this.

**Comment by sherifomran** [comment]
I reinstalled the brew packages from the beginning and added each path to the output
```
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
```
and tried again with make and now it is running

**Comment by tonytheodore** [comment]
Why are you adding `*gnubin` to your $PATH?

**Comment by sherifomran** [comment]
when i installed these 3 components, i got a message saying that i should add this to the path. If it is wrong, please correct me. Till now make is still running.

**Comment by tonytheodore** [comment]
The [homebrew instructions](https://mxe.cc/#requirements-macos-homebrew) say:
```
You will see messages about keg-only formulae and tools prefixed with 'g' - you can safely ignore these and no homebrew related $PATH modifications or brew links are necessary.
```
In general, you should read what `homebrew` tells you very carefully. It is very useful in certain circumstances, but a world of bad advice.

**Comment by sherifomran** [comment]
So far it has been compiling too many packages and stopped at nettle 3.4.1

```
Failed to build package nettle for target i686-w64-mingw32.static!
------------------------------------------------------------
	  fi ; done
/bin/sh: line 1: 55524 Abort trap: 6           /Users/sherifomran/mxe/usr/x86_64-apple-darwin17.7.0/bin/m4 ./asm.m4 machine.m4 config.m4 aes-decrypt-internal.asm > aes-decrypt-internal.s
make[3]: *** [aes-decrypt-internal.o] Error 134
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install] Error 2
make[1]: *** [build-only-nettle_i686-w64-mingw32.static] Error 2
real	0m44.084s
user	0m27.537s
sys	0m10.863s

```

inside the log file it says
`/usr/local/opt/coreutils/libexec/gnubin/mkdir -p /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/include/nettle
/Users/sherifomran/mxe/usr/x86_64-apple-darwin17.7.0/bin/m4 ./asm.m4 machine.m4 config.m4 aes-decrypt-internal.asm >aes-decrypt-internal.s
i686-w64-mingw32.static-gcc -I.  -DHAVE_CONFIG_H -g -O2 -ggdb3 -Wall -W   -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes   -Wpointer-$
        && true
for f in aes.h arcfour.h arctwo.h asn1.h blowfish.h base16.h base64.h bignum.h buffer.h camellia.h cast128.h cbc.h ccm.h cfb.h chacha.h chacha-poly130$
          if [ -f "$f" ] ; then \
            /usr/local/opt/coreutils/libexec/gnubin/install -c -m 644 "$f" /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/include/nettle ; \
          else \
            /usr/local/opt/coreutils/libexec/gnubin/install -c -m 644 "./$f" /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/include/nettle ; \
          fi ; done
/bin/sh: line 1: 55524 Abort trap: 6           /Users/sherifomran/mxe/usr/x86_64-apple-darwin17.7.0/bin/m4 ./asm.m4 machine.m4 config.m4 aes-decrypt-i$
make[3]: *** [aes-decrypt-internal.o] Error 134
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install] Error 2
make[1]: *** [build-only-nettle_i686-w64-mingw32.static] Error 2
`

**Comment by sherifomran** [comment]
I skipped this package and make 
`make cc` and this ran with no problems
then i made
`make qt5`
but then it stopped at qttools
then i gave
`make qttools -d` and i got the following log
```       Trying pattern rule with stem `qdbus_resource.rc.sh'.
          Trying implicit prerequisite `s.qdbus_resource.rc.sh'.
          Trying pattern rule with stem `qdbus_resource.rc.sh'.
          Trying implicit prerequisite `SCCS/s.qdbus_resource.rc.sh'.
         No implicit rule found for `qdbus_resource.rc'.
         Finished prerequisites of target file `qdbus_resource.rc'.
        No need to remake target `qdbus_resource.rc'.
       Finished prerequisites of target file `.obj/release/qdbus_resource_res.o'.
       Prerequisite `qdbus_resource.rc' is older than target `.obj/release/qdbus_resource_res.o'.
      No need to remake target `.obj/release/qdbus_resource_res.o'.
     Finished prerequisites of target file `../../../bin/qdbus.exe'.
    Must remake target `../../../bin/qdbus.exe'.
i686-w64-mingw32.static-g++ -Wl,-s -Wl,-subsystem,console -Wl,--gc-sections -o ../../../bin/qdbus.exe .obj/release/qdbus.o  /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5DBus.a /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/lib/libdbus-1.a /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/lib/libws2_32.a /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/lib/libiphlpapi.a /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/lib/libdbghelp.a /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Xml.a /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5Core.a -lmpr -lnetapi32 -luserenv -lversion -lws2_32 -lkernel32 -luser32 -lshell32 -luuid -lole32 -ladvapi32 -lwinmm /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/lib/libz.a /Users/sherifomran/mxe/usr/i686-w64-mingw32.static/lib/libpcre2-16.a .obj/release/qdbus_resource_res.o   
Putting child 0x7ffa8fc122c0 (../../../bin/qdbus.exe) PID 26776 on the chain.
Live child 0x7ffa8fc122c0 (../../../bin/qdbus.exe) PID 26776 
/Users/sherifomran/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5DBus.a(qdbuspendingcall.o):qdbuspendingcall.cpp:(.text$_ZN23QDBusPendingCallPrivateD2Ev+0x12): undefined reference to `_imp__dbus_pending_call_cancel'
/Users/sherifomran/mxe/usr/i686-w64-mingw32.static/qt5/lib/libQt5DBus.a(qdbuspendingcall.o):qdbuspendingcall.cpp:(.text$_ZN23QDBusPendingCallPrivateD2Ev+0x1e): undefined reference to `_imp__dbus_pending_call_unref'
collect2: error: ld returned 1 exit status
Reaping losing child 0x7ffa8fc122c0 PID 26776 
make[4]: *** [../../../bin/qdbus.exe] Error 1
Removing child 0x7ffa8fc122c0 PID 26776 from chain.
Reaping losing child 0x7febd14246c0 PID 26775 
make[3]: *** [release] Error 2
Removing child 0x7febd14246c0 PID 26775 from chain.
Reaping losing child 0x7f8e514287e0 PID 26771 
make[2]: *** [sub-qdbus-make_first] Error 2
Removing child 0x7f8e514287e0 PID 26771 from chain.
Reaping losing child 0x7f97b3d376e0 PID 26766 
make[1]: *** [sub-qdbus-make_first] Error 2
Removing child 0x7f97b3d376e0 PID 26766 from chain.
Reaping losing child 0x7fdb8b61bb90 PID 26652 
make: *** [sub-src-make_first] Error 2
Removing child 0x7fdb8b61bb90 PID 26652 from chain.
```

**Comment by sherifomran** [comment]
I made a hello world c file and tried to compile it but it fails

Sherif:WinTes3 sherifomran$ i686-w64-mingw32.static-g++
i686-w64-mingw32.static-g++: fatal error: no input files
compilation terminated.
Sherif:WinTes3 sherifomran$ nano Makefile
Sherif:WinTes3 sherifomran$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.Release
i686-w64-mingw32.static-g++ -c -pipe -fno-keep-inline-dllexport -O2 -std=gnu++11 -Wall -W -Wextra -ffunction-sections -fdata-sections -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I../../mxe/usr/i686-w64-mingw32.static/qt5/include -I../../mxe/usr/i686-w64-mingw32.static/qt5/include/QtCore -Irelease -I../../mxe/usr/i686-w64-mingw32.static/qt5/mkspecs/win32-g++  -o release/main.o main.cpp
make[1]: i686-w64-mingw32.static-g++: No such file or directory
make[1]: *** [release/main.o] Error 1
make: *** [release] Error 2

**Comment by tonytheodore** [comment]
nettle and qttools are now fixed, a `git pull` will fetch the latest updates.
