### ISSUE TITLE
Trouble using SHGetKnownFolderPath from shlobj.h

### ISSUE THREAD

**Issue by onpon4** [mxe/mxe#2353]
I was just trying to cross-compile Project: Starfighter for Windows (MXE is what I used for the previous release, and I wanted to use it again for a new release I'm almost ready to push out). But I seem to be running into some trouble.

The source code to the project can be found here if testing is needed (latest Git version is required to see this issue): https://savannah.nongnu.org/git/?group=starfighter

But basically, I'm #include'ing <shlobj.h>, which goes fine, and then calling this:

	if (SHGetKnownFolderPath(FOLDERID_LocalAppData, KF_FLAG_CREATE, NULL, &userHome) != S_OK)
	{
		userHome = ".";
		engine_warn("Could not get appdata location; using the current working directory instead.");
	}

I'm not terribly familiar with the Windows API, but I think based on what I've read that this should be correct, right? Every bit of documentation on the Windows API says that these are a part of shlobj.h, which I'm including with the line (at the top of the same source file):

    #include <shlobj.h>

When it gets to the part using SHGetKnownFolderPath, though, it seems the compiler doesn't have a reference to SHGetKnownFolderPath or KF_FLAG_CREATE:

    engine.c:207:6: warning: implicit declaration of function 'SHGetKnownFolderPath' [-Wimplicit-function-declaration]
      if (SHGetKnownFolderPath(FOLDERID_LocalAppData, KF_FLAG_CREATE, NULL, &userHom
          ^
    engine.c:207:50: error: 'KF_FLAG_CREATE' undeclared (first use in this function)

Full log of how compilation was done found here: https://pastebin.com/3iA8Zgxx

Is this just a part of the Windows API that MXE doesn't support (or doesn't yet support)?

**Comment by sago007** [comment]
I am using SHGetKnownFolderPath with MXE.
It is a Windows Vista or later API and I believe MXE defaults to Windows XP compatibility.

I added "-D_WIN32_WINNT=0x0601 -DWINVER=0x0601" to my compile flags and it worked.

**Comment by onpon4** [comment]
Awesome, thanks for the answer!
