### ISSUE TITLE
CPack fails to create installer

### ISSUE THREAD

**Issue by eichf** [mxe/mxe#2355]
Hello there,

my application is a Qt5 application which I build with CMake. No, I don't want to switch to qmake. After some playing around with the build for a while, figuring out the static-vs-dynamic issues, I now have it producing an exe; since it now depends on a bunch of dlls to run, I now need to run CPack to generate the installer. I had this working when building statically (the installer, of course not with the dlls) and in Windows natively with mingw. Anyway, here's what I'm doing and getting:

```
» x86_64-w64-mingw32.shared-cpack ..
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: GridBoxLite
CPack: - Install project: GridBoxLite
CPack: Create package
CPack Error: Problem running NSIS command: "/home/flrn/bin/mxe/usr/bin/x86_64-w64-mingw32.shared-makensis" "/home/flrn/workbench/GridBoxLite/winbuild/_CPack_Packages/win64/NSIS/project.nsi"
Please check /home/flrn/workbench/GridBoxLite/winbuild/_CPack_Packages/win64/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: GridBoxLite
```

and the following is the famed NSISOutput.log:

```
» tail -15 _CPack_Packages/win64/NSIS/NSISOutput.log
!define: "MUI_STARTMENUPAGE_REGISTRY_VALUENAME"="Start Menu Folder"
!insertmacro: MUI_PAGE_STARTMENU
!insertmacro: end of MUI_PAGE_STARTMENU
!insertmacro: MUI_PAGE_INSTFILES
!insertmacro: end of MUI_PAGE_INSTFILES
!insertmacro: MUI_PAGE_FINISH
Plugin directories:
  /home/flrn/bin/mxe/usr/x86_64-w64-mingw32.shared/share/nsis/Plugins/amd64-unicode
Plugin not found, cannot call System::Call
Error in macro _IsHighContrastModeActive on macroline 6
Error in macro _If on macroline 9
Error in macro MUI_FUNCTION_FINISHPAGE on macroline 325
Error in macro MUI_PAGE_FINISH on macroline 45
Error in script "/home/flrn/workbench/GridBoxLite/winbuild/_CPack_Packages/win64/NSIS/project.nsi" on line 562 -- aborting creation process
```

so as it seems it's failing when trying to call the `MUI_PAGE_FINISH` macro in the CPack project file. Seems like it shouldn't do that; it certainly didn't do that before and I'm somewhat flustered.

(Very sorry if this seems like a support question; I may be doing something wrong here but I'm super confused because CPack worked before and I didn't really anything about the CPack part of the process.)

**Comment by tonytheodore** [comment]
```
Plugin not found, cannot call System::Call
```
I don't know much about `nsis` but it seems that plugin [was disabled for 64-bit builds](https://github.com/mxe/mxe/commit/dce1bc264918aa09efff4ca161b0ce8c3112d66f#diff-ec76eb3311ea913928703ef98598e2db).

**Comment by eichf** [comment]
I see. So it's back to 32bit builds for Windows.
