### ISSUE TITLE
CMake is unable to find a library

### ISSUE THREAD

**Issue by hcasse** [mxe/mxe#2357]
The target CMake is unable to find a library of mine with the following command:

  find_library(ARM_SIM arm PATHS "${CMAKE_SOURCE_DIR}/armv5t/src")

with TARGET=x86_64-w64-mingw32-

There is a library named armv5t/src/libarm.a with full path:
  /home/casse/Enseignement/boardsim.win/boardsim/armv5t/src/libarm.a
Compiled for target:
  export CC=x86_64-w64-mingw32-gcc
strace'ing the cmake invocation, I get the suspicious system call:

 stat("/home/casse/Enseignement/boardsim.win/mxe/mxe/usr/i686-w64-mingw32.static/home/casse/Enseignement/boardsim.win/boardsim/armv5t/src", 0x7ffee8c081a0) = -1 ENOENT (No such file or directory)

The ${CMAKE_SOURCE_DIR} variable is duplicated and I get the same even if I remove ${CMAKE_SOURCE_DIR}. Sounds like concatenating current absolute directory path with the absolute library path not handled in the right way.

**Comment by hcasse** [comment]
Sorry. The last paragraph should:
The ${CMAKE_SOURCE_DIR} variable is duplicated but I get the right work when I remove the find_library ${CMAKE_SOURCE_DIR}. Sounds like concatenating current absolute directory path with the absolute library path not handled in the right way.

**Comment by tonytheodore** [comment]
[`${CMAKE_SOURCE_DIR}`](https://cmake.org/cmake/help/v3.10/variable/CMAKE_SOURCE_DIR.html) is the `full path to the top level of the current CMake source tree`. You typically don't want to be building within the source directory or searching for libraries there.

The [`find_library`](https://cmake.org/cmake/help/v3.10/command/find_library.html) has lots of notes about correctly specifying the search paths.

**Comment by tonytheodore** [comment]
Cmake has since been updated, but the behaviour is likely the same:

> The CMake variable CMAKE_FIND_ROOT_PATH specifies one or more directories to be prepended to all other search directories. This effectively “re-roots” the entire search under given locations. Paths which are descendants of the CMAKE_STAGING_PREFIX are excluded from this re-rooting, because that variable is always a path on the host system. By default the CMAKE_FIND_ROOT_PATH is empty.

the toolchain file sets `CMAKE_FIND_ROOT_PATH` so it will be prepended to all searches. You might be better off adding to that instead of specifying `PATHS`.
