### ISSUE TITLE
The directory that should contain system headers does not exist

### ISSUE THREAD

**Issue by JulyIghor** [mxe/mxe#2376]
I'm always updating gcc to newer version, 7.4.0 or 8.3.0 it still there.
I'm getting error that folder does not exists.
I can solve it by just creating folder and compile again, but I think it should be fixed.

![image](https://user-images.githubusercontent.com/3390357/61642709-bbae8680-aca1-11e9-8e28-cae3dd70f651.png)

**Comment by tonytheodore** [comment]
I thought this [patch removing the hard-coded directory](https://github.com/mxe/mxe/blob/master/plugins/gcc8/gcc8.patch#L32) solves that issue?

**Comment by JulyIghor** [comment]
Maybe it fixed for gcc 8, but I got it on gcc 7.4.0 yesterday

**Comment by tonytheodore** [comment]
The patch is present in gcc7 plugin also.

**Comment by JulyIghor** [comment]
ok, thanks
