### ISSUE TITLE
"<filesystem>": No such file or directory for mingw32

### ISSUE THREAD

**Issue by abhiarora4** [mxe/mxe#2386]
I am trying to compile a QT5 application on Linux for windows. I have download `mxe` and build it (using `make` and `make qt5`). My QT5 application uses `<filesystem>` header file and compiler is not recognizing it and linker flag `lstdc++fs`.

It says can't find linker flag.

**Comment by tonytheodore** [comment]
What are the exact commands you're running?

**Comment by ZachBacon** [comment]
This probably requires a new gcc to be honest, iirc gcc 7+ is the set of gcc that makes use of the filesystem stuff within libstdc++. Which is available as an mxe plugin. Might be worth updating base gcc to at least gcc 8. That was the next level stable build of gcc that I'd compare to in terms of stability of gcc 5.

**Comment by Jan200101** [comment]
I'd suggest using the gcc 9 patch as none of the previous ones seem to feature it though that could have changed since I've tried
