### ISSUE TITLE
Getting i686-w64-mingw32.static-g++ command not found on mac os Mojave add support for Berkeley DB 4.8.30

### ISSUE THREAD

**Issue by LegitMan-cyber** [mxe/mxe#2388]
I have built cc, boost, miniupnpc and qttools, but unfortunately when I look for the above file in my mac the finder doesn't return any result although the file is located in macos. is there any way I can fix this? Also when running the command `which i686-w64-mingw32.static-g++` in terminal it cannot find it?

I have the latest xcode and macports installed. I followed all the instructions on the website.

**Comment by LegitMan-cyber** [comment]
Problem solved by adding the $PATH for mxe in .zshrc file

**Comment by tonytheodore** [comment]
Thanks, I've added a note about other shell config scripts to the docs.
