### ISSUE TITLE
hdf-eos5 patches fail to apply

### ISSUE THREAD

**Issue by dshadowwolf** [mxe/mxe#2400]
Fresh build attempt on Debian 10 results in patches failing to apply (actually, it looks like the patch to EHapi.c is no longer needed) and the build failing - log file here: https://gist.github.com/dshadowwolf/0e6f28a0678980a073ae58f68a3160f3

**Comment by dshadowwolf** [comment]
The final patch in hdf-eos5-1-fixes.patch  (here: https://github.com/mxe/mxe/blob/08544fd3f2d06c25cf9879edf4dde08ace00b1d8/src/hdf-eos5-1-fixes.patch#L129-L157) is apparently no longer needed and patch responds as if the patch had already been applied. Removing that section of the file allows the compilation to complete successfully.

**Comment by mabrand** [comment]
Thanks. Should be fixed now.
