### ISSUE TITLE
libQt5DBus won't compile for x86_64-w64-mingw32.static

### ISSUE THREAD

**Issue by JulyIghor** [mxe/mxe#2413]
https://gist.github.com/JulyIghor/77408d0282c6e1f7c6481d82466fb68e

**Comment by JulyIghor** [comment]
Any advice or temporary fix help?

**Comment by tonytheodore** [comment]
I can't replicate on a basically identical machine https://gist.github.com/tonytheodore/3334287778675ceaa66956cdce666d71

**Comment by JulyIghor** [comment]
Thanks for checking. Maybe my issue may have reason of no disk space left in some moment.
I'll do it again.
