### ISSUE TITLE
ghostscript build failure

### ISSUE THREAD

**Issue by dshadowwolf** [mxe/mxe#2424]
Build fails with a "conflicting types" issue in gp_unix.c - looks like a forward declaration in gp.h doesn't agree fully. Uploading log to https://gist.github.com/dshadowwolf/dead66d9a58a2531ac0865b9ea2ed080

It appears to be an overlooked bit - in ``gp.h`` the prototype given uses ``gp_file *`` as the type of the first parameter, in ``gp_unix.c`` the function is declared with the first parameter being the class ``FILE *``. A naive patch of the code should solve that issue... let me see if I can generate such :)

**Comment by anzyelay** [comment]
i meet the same problem to u.
#ifdef __MINGW32__
int
gp_local_arg_encoding_get_codepoint(FILE *file, const char **astr);
#else
int
gp_local_arg_encoding_get_codepoint(gp_file *file, const char **astr);
#endif

**Comment by dshadowwolf** [comment]
and I've had no time to pursue a fix here for the past week or so - I've got some time before I have to try and have the app compiled for Windows, so it can wait, but...
