### ISSUE TITLE
Failed to build package pe-util for target x86_64-pc-linux-gnu

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2425]
While compiling MXE env for digiKam from scratch, pe-util refuse to build :

[build]       pe-util                x86_64-pc-linux-gnu

Failed to build package pe-util for target x86_64-pc-linux-gnu!
------------------------------------------------------------
make[3]: *** [CMakeFiles/Makefile2:76: CMakeFiles/peldd.dir/all] Error 2
make[3]: Leaving directory '/mnt/devel/GIT/6.x/project/bundles/mxe/build.win32/tmp-pe-util-x86_64-pc-linux-gnu/gsauthof-pe-util-04f9475.build_'
make[2]: *** [Makefile:130: all] Error 2
make[2]: Leaving directory '/mnt/devel/GIT/6.x/project/bundles/mxe/build.win32/tmp-pe-util-x86_64-pc-linux-gnu/gsauthof-pe-util-04f9475.build_'
make[1]: *** [Makefile:836: build-only-pe-util_x86_64-pc-linux-gnu] Error 2
make[1]: Leaving directory '/mnt/devel/GIT/6.x/project/bundles/mxe/build.win32'
real    0m5.454s
user    0m6.096s
sys     0m0.465s
------------------------------------------------------------
[log]      /mnt/devel/GIT/6.x/project/bundles/mxe/build.win32/log/pe-util_x86_64-pc-linux-gnu

Log file : https://gist.github.com/cgilles/bc9fb486eb40ed4de76f408f5028be71

**Comment by tonytheodore** [comment]
Please ensure you quote terminal output. 

It looks like cmake isn’t detecting the mxe version of boost, it shouldn’t be hard to fix.
