### ISSUE TITLE
pe-util fails to build

### ISSUE THREAD

**Issue by mbunkus** [mxe/mxe#2428]
This is with revision 3e04a1a05567eb4ab6957f29bf962fb114ed61ef. I need `pe-util` due to the following dependency chain:

`pe-util` ← `icu4c` ← `harfbuzz` ← … ← Qt

How to reproduce:

1. Check out the aforementioned revision.
2. Compile with `make MXE_TARGETS=x86_64-w64-mingw32.static pe-util`

The log is available [here](https://gist.github.com/mbunkus/0b4cfe313d507ab9710f4ace82b61155).

Looks like `-lboost_system` is needed.

**Comment by tonytheodore** [comment]
Hmm, I thought https://github.com/mxe/mxe/commit/6dfdebbc0d974aecc3fb85984f8b1b243a574bfc would avoid that.

Can you try this:
```diff
diff --git a/src/pe-util.mk b/src/pe-util.mk
index 16b9f8a0..345f6f9b 100644
--- a/src/pe-util.mk
+++ b/src/pe-util.mk
@@ -43,7 +43,10 @@ define $(PKG)_BUILD_$(BUILD)
     cd '$(BUILD_DIR)' && cmake '$(SOURCE_DIR)' \
         -DCMAKE_INSTALL_PREFIX='$(PREFIX)/$(TARGET)' \
         -DBOOST_ROOT='$(PREFIX)/$(TARGET)' \
+        -DBOOST_INCLUDEDIR='$(PREFIX)/$(TARGET)/include' \
+        -DBOOST_LIBRARYDIR='$(PREFIX)/$(TARGET)/lib' \
         -DBoost_NO_SYSTEM_PATHS=ON \
+        -DBoost_NO_BOOST_CMAKE=ON \
         -DCMAKE_CXX_FLAGS='-I$(PREFIX)/$(TARGET)/include'
     $(MAKE) -C '$(BUILD_DIR)' -j '$(JOBS)'
     $(MAKE) -C '$(BUILD_DIR)' -j 1 install
```

**Comment by mbunkus** [comment]
Thanks for your quick response. `pe-util` builds fine with your patch.
