### ISSUE TITLE
Failed to build package qt for target i686-w64-mingw32.static

### ISSUE THREAD

**Issue by Zero3K** [mxe/mxe#2433]
When I try to install MXE, I get to where it gives me the error in this issue's title. The log is available at:

https://gist.github.com/Zero3K/1fb4089d95d0fa0afe6bbbf877f56e3d

**Comment by tonytheodore** [comment]
Fixed in https://github.com/mxe/mxe/commit/0c1b092fc4eb7751c926c7c0371386e18f8ec1e8
