### ISSUE TITLE
Failed to build package ocaml-cairo for target i686-w64-mingw32.static

### ISSUE THREAD

**Issue by hkroeger** [mxe/mxe#2436]
I stumbled across the above error when building MXE on my Ubuntu 18.04 LTS machine.

The log file indicates some problems when linking to libharfbuzz.

See:
https://gist.github.com/hkroeger/11c0d7f02bf78c929333c4964f0b49e0

Do you have any hint for me on how to proceed?

Thanks a lot!

**Comment by hkroeger** [comment]
Ah, I guess this is related:
https://mxe.cc/#issue-non-multilib

Sorry for bothering

**Comment by Scorbie** [comment]
Thank you for the pointer, it saved me a lot of time.
In Ubuntu 20.04 I got it to work after I...

1. Installed the following packages:
`sudo apt-get install gcc-multilib-i686-linux-gnu g++-multilib-i686-linux-gnu linux-libc-dev:i386`

2. Added the following line to ocaml-cairo.mk:26 (may not be necessary)
    ```make
    define $(PKG)_BUILD
    cd '$(1)' && autoreconf -fi -I support
    cd '$(1)' && ./configure \
        --host $(TARGET) \
        --build="`config.guess`" \
        --prefix='$(PREFIX)/$(TARGET)' \
        CC="$(BUILD_CC) -m32" ##### This Line #####
    $(MAKE) -C '$(1)' -j '$(JOBS)' install
    ```
