### ISSUE TITLE
Enabling certain modules in VTK

### ISSUE THREAD

**Issue by haampie** [mxe/mxe#2439]
For a project with VTK and QML I need to set `cmake -DModule_vtkRenderingExternal=ON`. Right now I changed it by hand in the `vtk.mk` file.

What would be the recommended way of adding this flag?

**Comment by tonytheodore** [comment]
With https://github.com/mxe/mxe/commit/181da98e5475257e11cbbeb21f710a91877fa172 you can add `vtk_CONFIGURE_OPTS=-DModule_vtkRenderingExternal=ON` to `settings.mk` or your make invocation.

**Comment by haampie** [comment]
Amazing @tonytheodore, that was an incredibly quick fix :) thanks a bunch!

**Comment by tonytheodore** [comment]
Actually, it should be using the new style `$(PKG_CONFIGURE_OPTS)` to allow things like #2291 

You can add that to the end of any package rule, eventually we'll update all packages to use it.
