### ISSUE TITLE
Windeployqt not built

### ISSUE THREAD

**Issue by haampie** [mxe/mxe#2441]
It seems windeployqt.exe (part of qttools) is not built. 

For me it would be very useful to bundle a complete Qt app with all necessary DLLs, plugins and QML files in my CI environment. So I'm hoping I could run windeployqt.exe via Wine in CI.

Could it be possible that it is simply not included because of this conditional during cross-compilation? https://github.com/qt/qttools/blob/v5.13.2/src/src.pro#L38

**Comment by haampie** [comment]
Ok, it seems a bit more intricate that I thought it would be. `windeployqt.exe` relies on `qmake.exe`, which is not built because we're cross-compiling.

I'll just do a pessimistic bundling then where I copy over all Qt plugins + all translation files + all QML files.

**Comment by autoantwort** [comment]
I run windeployqt on my windows machine and put all files except of the .exe in a release folder. The CI compile the .exe and move the .exe in the release folder. The complete release folder is then an artifact that can be downloaded.

**Comment by tonytheodore** [comment]
> Maybe wine can at least help to detect the necessary dependent dll's to be bundle

See [this approach of tracing the dll loads](https://stackoverflow.com/a/36388450).

There is also [an example of building a host toolchain](https://github.com/mxe/mxe/tree/master/plugins/examples/host-toolchain), but it's probably outdated (and was pretty fiddly to begin with).
