### ISSUE TITLE
apt's signing GPG public key is wrong on pkg.mxe.cc and mirror.mxe.cc

### ISSUE THREAD

**Issue by be1** [mxe/mxe#2442]
The GPG public key given at [pkg.mxe.cc](https://pkg.mxe.cc/repos/apt/client-conf/mxeapt.gpg) is not the same as the GPG key that signed the debian and ubuntu repos of pkg.mxe.cc nor mirror.mxe.cc. And i cannot find the expected key anywhere.
Expected behaviour: apt update give no error.
Current behaviour: apt update yields an error.
```
wget https://pkg.mxe.cc/repos/apt/client-conf/mxeapt.gpg
...
sudo apt-key add mxeapt.gpg 
OK
sudo apt update
Get:7 https://mirror.mxe.cc/repos/apt bionic InRelease [1780 B]
Err:7 https://mirror.mxe.cc/repos/apt bionic InRelease
The following signatures couldn't be verified because the public key is not available: 
NO_PUBKEY C6BF758A33A3A276
Reading package lists... Done
...
W: GPG error: https://mirror.mxe.cc/repos/apt bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C6BF758A33A3A276
gpg --recv-keys C6BF758A33A3A276
gpg: keyserver receive failed: No data

**Comment by tonytheodore** [comment]
I've just updated the [key file](https://pkg.mxe.cc/repos/apt/client-conf/mxeapt.gpg), it still had the old one after pkg.mxe.cc went down and I started using a [new signing key](https://github.com/mxe/mxe/issues/2253#issuecomment-449646901).
