### ISSUE TITLE
Simple Qt5 program works in Windows/VirtualBox but segfaults in Wine

### ISSUE THREAD

**Issue by hkroeger** [mxe/mxe#2451]
I have installed mxe successfully and I'm able to compile programs for Windows.

I just came across one issue, when I tried to run my program in wine (my program it is part of a program suite which has components running in Windows and others running in Linux, using wine would simplify development).

When I start the program, it immediately throws a segmentation fault. The full error message is here: https://gist.github.com/hkroeger/41ec9563ec56ef4e3a14198c0a3bf28c
I guess, it should be possible to run MXE compiled programs with wine, right?
I could only trace the origin to somewhere inside the constructor of the QApplication object.

I have no idea where to continue searching for the problem here. Any hints are appreciated. 

The program is the QtCreator-Wizard-created minimum: 
[sample.zip](https://github.com/mxe/mxe/files/4044329/sample.zip)

The compile log is here:
https://gist.github.com/hkroeger/1ceab66ea3fdf9b3c9acc91dd0b04d7f

**Comment by euphoria** [comment]
I don't have a solution or additional information here, but just as a note I always had this same problem as well and have not figured it out, so hopefully someone else knows more.

**Comment by tehnick** [comment]
I saw such problem some time ago. It never happened nor with older versions of WINE, nor with current one in Debian unstable:
```
wine (5.0~rc6-1) unstable; urgency=medium

   * New upstream release 5.0-rc6, released Jan 17, 2020.
```

So I would suggest you to try other versions of WINE.

**Comment by tonytheodore** [comment]
It looks like it's emulating Win XP:
```
System information:
    Wine build: wine-4.0.3
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 4.15.0-74-generic
```
This is expected to fail after Qt 5.7 when XP support was dropped.
