### ISSUE TITLE
Qt 5.12.6 fontconfig and system-freetype problem

### ISSUE THREAD

**Issue by davidovv** [mxe/mxe#2454]
There seems to be a bug in qt 5.12.4 that affects my code and that is fixed in 5.12.6. After 5.12.4 mxe switched to 5.13.0 so  I wanted to create a branch for 5.12.6. by continuing from last commit before 5.13.0 (af2744a8bc86df0d7d4fc223227e2035d46a3d93). 
I successfuly compiled this commit with make --jobs=4 MXE_TARGETS="i686-w64-mingw32.shared" qt5. 
Then i made changes to some .mk and .patch files (mostly just modified check sums, and line numbers where patch is applied), but with my modifications, same make command fails when building qtbase with errors:   

Failed to build package qtbase for target i686-w64-mingw32.shared!                                                                      
------------------------------------------------------------                                                                            
ERROR: Feature 'system-freetype' was enabled, but the pre-condition 'features.freetype && libs.freetype' failed.                        
ERROR: Feature 'fontconfig' was enabled, but the pre-condition '!config.msvc && features.system-freetype && libs.fontconfig' failed.    
Makefile:812: recipe for target 'build-only-qtbase_i686-w64-mingw32.shared' failed                                                      
make[1]: *** [build-only-qtbase_i686-w64-mingw32.shared] Error 3                                                                        
make[1]: Leaving directory '/opt/mxe-qt5C6'

I believe that system-freetype and fontconfig pre-conditions should be met because i compiled previous version without problems. Now i just have no idea what to try next.

I hope some experienced maintainer here can help me to see what i am missing.

**Comment by tonytheodore** [comment]
Qt5 has since been updated, can you raise again if there's still an issue?
