### ISSUE TITLE
filed to build gmp

### ISSUE THREAD

**Issue by luntik2012** [mxe/mxe#2455]
current dir is not in PATH

[log.txt](https://github.com/mxe/mxe/files/4112005/log.txt)

**Comment by tonytheodore** [comment]
The final error:
```
rm: cannot remove '/opt/mxe/tmp-gmp-i686-w64-mingw32.static/readonly': Directory not empty
```

is caused by `wine` putting a bunch of files in there. This has permissions of 0555 and I'm not sure how they would be written there, and since they are, why `rm -rf` fails.
