### ISSUE TITLE
Qt5 build with JOBS=6 failed, but JOBS=4 works fine

### ISSUE THREAD

**Issue by JulyIghor** [mxe/mxe#2457]
I'm using command `mxe MXE_PLUGIN_DIRS=plugins/gcc9 -j6 JOBS=6 gcc qt5`
And its failing to compile with error:
`make: *** [Makefile:834: /mxe/x86_64-w64-mingw32.static/installed/qtquickcontrols2] Error 1`
But when I change threads count from 6 to 4 it works fine.
Failed for both i686, x86_64 static and shared builds.
Tested and confirmed many times, it is always work with threads 4 and always fails to build with 6.

**Comment by tonytheodore** [comment]
I can't replicate this with 6 or 16 threads. Does it always fail on `qtquickcontrols2`?

**Comment by JulyIghor** [comment]
low memory issue
