### ISSUE TITLE
Qt5 $(STRIP) variable is empty

### ISSUE THREAD

**Issue by JulyIghor** [mxe/mxe#2460]
How to make $(STRIP) to work properly in qmake project profile?

**Comment by tonytheodore** [comment]
Have a look in `.../mkspecs/common/g++-win32.conf`, you probably want to use `QMAKE_STRIP`:
```
...
QMAKE_LIB               = $${CROSS_COMPILE}ar -rc
QMAKE_RC                = $${CROSS_COMPILE}windres

QMAKE_STRIP             = $${CROSS_COMPILE}strip
QMAKE_STRIPFLAGS_LIB   += --strip-unneeded
QMAKE_OBJCOPY           = $${CROSS_COMPILE}objcopy
QMAKE_NM                = $${CROSS_COMPILE}nm -P
...
```

**Comment by JulyIghor** [comment]
QMAKE_STRIP is not accessible in other platforms in some reason
$(STRIP) works fine everywhere except mxe, https://github.com/GarageGames/Qt/blob/master/qt-5/qtwebengine/src/core/core_module.pro

**Comment by tonytheodore** [comment]
Is `$(STRIP)` and env var or a qmake var?

`QMAKE_STRIP` seems to be in the mkspecs of other platforms, maybe it needs to referenced as `$$QMAKE_STRIP` or `$${QMAKE_STRIP}`? (I'm not familiar enough with qmake syntax)
