### ISSUE TITLE
openSUSe Qt / Qt-everywhere-4.8.7 fail

### ISSUE THREAD

**Issue by DevDorrejo** [mxe/mxe#2464]
When building Qt fail because Qt-everywhere-4.8.7, and this same package when is building fail, i do a fresh build and exclude Qt-everywhere-4.8.7, but Qt still call this old version of Qt and i only need 5.14.1.

make EXCLUDE_PKGS='qt-everywhere-opensource-src-4.8.7' **Is not working**

[qt_i686-w64-mingw32.static.log](https://github.com/mxe/mxe/files/4269728/qt_i686-w64-mingw32.static.log)

**Comment by tonytheodore** [comment]
There are issues with recent versions of gcc and Qt4 (along with ocaml), to exclude them, only use package names:
```
make EXCLUDE_PKGS='qt ocaml%'
```
but you're probably better off simply listing the packages you do want, e.g.:
```
make qt5 foo bar
```

**Comment by DevDorrejo** [comment]
ok, thank you, that help, but can't get qtwebengine, some idea?

**Comment by tonytheodore** [comment]
> but can't get qtwebengine, some idea?

see #2515
