### ISSUE TITLE
error when running a 64bit application on Windows7

### ISSUE THREAD

**Issue by dbluelle** [mxe/mxe#2465]
When building lightspark (https://github.com/lightspark) with mxe target x86_64-w64-mingw32.static
the resulting binary produces the error 
"The procedure entry point ScriptIsComplex could not be located in the dynamic link library GDI32.dll"
on startup when running on 64bit Windows7.
The same exe runs without problems on Windows10.
When building with target i686-w64-mingw32.static, the resulting binary works on Windows7.

**Comment by tonytheodore** [comment]
See https://github.com/lightspark/lightspark/issues/454#issuecomment-639236047
