### ISSUE TITLE
qt5-based application fails to start

### ISSUE THREAD

**Issue by ivansmm** [mxe/mxe#2466]
When trying to run qt5 application built using mxe, the following error occurs:

`Could not find the Qt platform plugin "windows" in ""`

This happens both when executable is run in wine and in real windows 10 system. I tried both static and shared i686-w64-mingw32 builds. I also tried with QTDIR assigned to <MXETOP>/usr/i686-w64-mingw32.static/qt5 but this did not make any difference.

**Comment by jonaski** [comment]
With shared builds this is because it can't find or open qwindows.dll
It needs to be copied to a sub directory called platforms under the application directory before you run the copy dependencies script.
Something is wrong with your static compilation.

**Comment by ivansmm** [comment]
YES!!!!
It runs now, huge thanks! I was already going crazy.
With ststic compilation I did completely straightforward thing: 1) Ran make MXE_TARGETS+i686-w64-mingw32.static qtbase, then assigned QTDIR to ..../...mingw32.static/qt5, added ...../....mingw32.static/bin to PATH and compiled my application (using proper prefix for development tools). It was still complaining about missing plugin.

Thanks again!

**Comment by tonytheodore** [comment]
I think you can set the `QT_QPA_PLATFORM_PLUGIN_PATH` env var, or create a [`qt.conf` file](https://doc.qt.io/qt-5/qt-conf.html) with the following:
```
[Paths]
Prefix = ..
```

**Comment by ivansmm** [comment]
I have tested static version again: plugin is still not reported to be found with it. In same environment shared version works.

**Comment by jonaski** [comment]
You need to share more details of how you build static. Do you use cmake or qmake? How do you set up the toolchain file?

**Comment by jonaski** [comment]
If you use CMake you can look at this project: https://github.com/jonaski/sqlrestore
Look at the instructions in the README and the toolchain files.

**Comment by ivansmm** [comment]
I have installed mxe sources under `/usr/local/mxe` and built mxe using `make MXE_TARGETS=i686-w64-mingw32.static qtbase`. After that I changed to my project sources, set up the environment as follows:
`export PATH=/usr/local/mxe/usr/bin:$PATH`
`export QTDIR=/usr/local/mxe/usr/i686-w64-mingw32.static/qt5`
and used `make` to build the project. I verified, that g++, ranlib and ar are prefixed with `i686-w64-mingw32.static-` and that moc was used from `/usr/local/mxe/usr/i686-w64-mingw32.static/qt5/bin`. To link the executable g++ was used, prefixed accordingly.

**Comment by tonytheodore** [comment]
> If you use CMake you can look at this project: https://github.com/jonaski/sqlrestore

Pay attention to `Q_IMPORT_PLUGIN` and `Q_INIT_RESOURCE` in https://github.com/jonaski/sqlrestore/blob/master/src/main.cpp

If you're using qmake:
https://doc.qt.io/qt-5/plugins-howto.html#details-of-linking-static-plugins
