### ISSUE TITLE
[qtbase-opensource-src-5.7.1.tar.xz] Download failed or wrong checksum of package qtbase!

### ISSUE THREAD

**Issue by hman20** [mxe/mxe#2467]
Hi,

I am trying to cross-compile [sigrok](https://sigrok.org/) and its dependencies for MinGW-w64/Windows systems. 

I am following this readme file for this process - link (https://sigrok.org/gitweb/?p=sigrok-util.git;a=blob_plain;f=cross-compile/mingw/README;hb=HEAD)

However, while running the following make command:

```
sudo make MXE_TARGETS=x86_64-w64-mingw32.static.posix MXE_PLUGIN_DIRS=plugins/examples/qt5-freeze qtbase qtbase_CONFIGURE_OPTS='-no-sql-mysql'
```

I am seeing the following error :
```
[check reqs]
[download]    qtbase-opensource-src-5.7.1.tar.xz
MXE Warning! Downloading qtbase from backup.

Download failed or wrong checksum of package qtbase!

--2020-03-10 23:27:10--  http://d1yihgixbnrglp.cloudfront.net/qtbase%2Dopensource%2Dsrc%2D5%2E7%2E1%2Etar%2Exz_edcdf549d94d98aff08e201dcb3ca25bc3628a37b1309e320d5f556b6b66557e
2020-03-10 23:27:11 ERROR 404: Not Found.
Download failed!

[log]      /home/testuser/Desktop/libsigrok/mxe-git/log/qtbase-download

Makefile:680: recipe for target 'download-only-qtbase-opensource-src-5.7.1.tar.xz' failed
make: *** [download-only-qtbase-opensource-src-5.7.1.tar.xz] Error 1
```

I saw that the qtbase-opensource-src-5.7.1.tar.xz is not present at the queried location. Please guide on how to proceed.

Thanks,
hman

**Comment by tonytheodore** [comment]
The checksum-suffixed archives only go back to Nov 17, try downloading the file manually from either:
```
wget https://mxe-pkg.s3.amazonaws.com/qtbase-opensource-src-5.7.1.tar.xz
# or
wget http://d1yihgixbnrglp.cloudfront.net/qtbase-opensource-src-5.7.1.tar.xz
```
and placing it in the `pkg` directory.

**Comment by hman20** [comment]
Thank you. That works.
