### ISSUE TITLE
python34_$TARGET.dll not found in http://www.sigrok.org/tmp/

### ISSUE THREAD

**Issue by hman20** [mxe/mxe#2471]
I am trying to cross compiling sigrok for MinGW-w64/Windows systems by running the script: ./sigrok-cross-mingw (found @ https://sigrok.org/gitweb/?p=sigrok-util.git;a=tree;f=cross-compile/mingw;h=33f825add9fb5e74b05ff6019319ff6d27b4a586;hb=HEAD)

While the script is being executed I get the error:
```
./sigrok-cross-mingw: 143: ./sigrok-cross-mingw: /home/testuser/mxe-git/usr/x86_64-w64-mingw32.static.posix/bin/gendef: not found
```

Looking into it, I found that it is unable to fetch python34_$TARGET.dll and python34_$TARGET.zip from http://www.sigrok.org/tmp/

I tried tried to run wget alone to fetch the files, with the below result:
```
sudo wget http://www.sigrok.org/tmp/python34_$TARGET.dll -O $P
REFIX/python34.dll
--2020-03-14 15:05:53--  http://www.sigrok.org/tmp/python34_.dll
Proxy request sent, awaiting response... 301 Moved Permanently
Location: https://sigrok.org/tmp/python34_.dll [following]
--2020-03-14 15:05:53--  https://sigrok.org/tmp/python34_.dll
Proxy request sent, awaiting response... 404 Not Found
2020-03-14 15:05:54 ERROR 404: Not Found.
```

Please let me know where to get those files to proceed.

**Comment by tonytheodore** [comment]
> I tried tried to run wget alone to fetch the files

Ensure you set the $TARGET variable, `https://sigrok.org/tmp/python34_.dll` isn't likely to exist.

You'll have to ask the sigrok project, but if you read the latest version of that script https://sigrok.org/gitweb/?p=sigrok-util.git;a=blob;f=cross-compile/mingw/sigrok-cross-mingw;h=bda4d921240d6f6cacf130dc6bd9e47c9e493e01;hb=HEAD#l99, you'll see the files now have a different extension.
