### ISSUE TITLE
How to add QT5 x11extras and serialport

### ISSUE THREAD

**Issue by tesseract-solutions** [mxe/mxe#2472]
Hello everyone,

My question is simple. 

I try to compile my app to windows. 

Qmake return "unknow x11extras and serialport" it's normal because mxe install only qtbase. 

So I want to know how to install libqt5x11extras and libqt5serialport ?

Thanks

**Comment by lotharsm** [comment]
You could try installing the packages `qtserialport` and `qtwinextras`.
