### ISSUE TITLE
How do I build using gcc 7.3.0?

### ISSUE THREAD

**Issue by cculianu** [mxe/mxe#2473]
I noticed this thing uses gcc 5.x.

I need gcc 7.3.0 because:

1. It's the preferred gcc for Windows mingw builds for newer Qt
2. It has C++17 support which I need in my project.

So.. how do I hack up the .mk file to do this?  Or do I need to do something special to switch gcc's? 

Thanks in advance.

**Comment by cculianu** [comment]
I noticed the plugin system -- is it enough to just do:

`echo 'override MXE_PLUGIN_DIRS += plugins/gcc7' >> settings.mk`

??

Sorry for the nub question. :)

**Comment by tonytheodore** [comment]
Yes, that's the current way to enable gcc7, but it will be 7.5.0 - you may be better off starting with gcc9.

**Comment by cculianu** [comment]
Awesome.  Actually I got it working and it built qt 5.14.1 static! W000!

Why do you recommend gcc9?

I'm inclined  to use gcc-7.5.0 for now because that's what I have been devving against and testing on Windows anyway (it's the closest to gcc 7.3.0 which is what the Windows Qt ships with) -- I want to introduce as few variables as possible in my initial testing of this as a build alternative.

But -- why gcc9?  Is it way better?  Should I just use that? :D

I'm closing this issue since you helped me and it's working.  Awesome!
