### ISSUE TITLE
luajit compile error

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2476]
luajit compile error
[luajit_i686-w64-mingw32.zip](https://github.com/mxe/mxe/files/4432788/luajit_i686-w64-mingw32.zip)

**Comment by tonytheodore** [comment]
Strange, I'm seeing a different error though nothing has changed recently.

**Comment by tonytheodore** [comment]
Building on Ubuntu 16.04 still succeeds.

**Comment by dbyoung720** [comment]
I compile on wsl , retry three time, error.

**Comment by gitfxt** [comment]
I got the same error on wsl ubuntu 18044.
Is the OS problem?

**Comment by ZachBacon** [comment]
I'm definitely experiencing the same issue on ubuntu 20.04 wsl, the log seems to be erroring out after building minilua, seems it's trying to build something with it that caused a syntax error. https://gist.github.com/ZachBacon/f85c092e0f1bf06dc22d2e3aaca9c7e8

**Comment by tonytheodore** [comment]
I've recently upgraded pkg.mxe.cc to 20.04 and it's working there.

There are [some env vars](https://repo.or.cz/luajit-2.0.git/blob/0bf80b07b0672ce874feedcc777afe1b791ccb5a:/src/Makefile#l159) that might be causing an issue on WSL.

**Comment by tonytheodore** [comment]
Also look at https://mxe.cc/#requirements-wsl, it may or may not be related.

**Comment by ZachBacon** [comment]
Don't think so, everything is setup under /home/username, as for the temp. Perhaps, but I doubt it.

**Comment by tonytheodore** [comment]
I'll try installing WSL and see if I can replicate it.

**Comment by ZachBacon** [comment]
It's a weird and a unique one, I'm not really looking so much as a solution since I generally prefer a linux box over wsl2, but I still find it handy from time to time.

**Comment by tonytheodore** [comment]
```
/usr/include/limits.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
 #include <bits/libc-header-start.h>
```
Bizarrely, there is no `/usr/include/bits` directory on WSL, on a standard install it's a symlink:
```
$ ll /usr/include/bits
lrwxrwxrwx 1 root root 21 Aug 28  2014 /usr/include/bits -> x86_64-linux-gnu/bits/
```

**Comment by tonytheodore** [comment]
Now I get it:
```
$ dpkg -S include/bits
libc6-dev-i386: /usr/include/bits
```
I skipped the multilib packages - now I can see the syntax error.

**Comment by ZachBacon** [comment]
So this is a multilib issue? Didn't think much of it since I had installed the recommended multilib packages on the info html page included with the git checkout and on mxe.cc

**Comment by tonytheodore** [comment]
> So this is a multilib issue?

Sort of, since the x86_64-w64-mingw32.static target builds successfully. 

WSL doesn't support 32-bit code, [but WSL2 apparently can](https://superuser.com/a/1407818).

**Comment by ZachBacon** [comment]
Except I should be using wsl2, I'll have to double check, but I'm pretty sure I've set wsl2 to be my default wsl.

**Comment by ZachBacon** [comment]
yeah apparently despite me setting wsl2 as default on a new windows install before installing ubuntu 20.04, it apparently didn't make it wsl2, I'm in the process of getting it upgraded, I'll report back when the upgrade is completed.

**Comment by ZachBacon** [comment]
yeah wsl2 built just fine luajit. So seems even if you set the default wsl2 profile and then install your "distro" you still need to double check if it's wsl2 before compiling with mxe

**Comment by tonytheodore** [comment]
Have you some steps/links I can add to the docs?

**Comment by ZachBacon** [comment]
Not really, just follow the instructions here https://docs.microsoft.com/en-us/windows/wsl/install-win10 and if you install a wsl distro just make sure it is properly set to wsl2 by running wsl --set-version <distribution name> 2 (and by distribution name... For example 20.04 is ubuntu-20.04) and wait a few moments to make sure the conversion is done.

**Comment by revelator** [comment]
Hmm im getting a different error

`host/minilua ../dynasm/dynasm.lua   -D JIT -D FFI -D FPU -D HFABI -D VER= -D WIN -o host/buildvm_arch.h vm_x86.dasc
host/minilua: 1: Syntax error: Unterminated quoted string`

**Comment by tonytheodore** [comment]
That is basically the same error after I switched to a verbose build.

**Comment by revelator** [comment]
well i got wsl2 and it is default, still i get the same error ?. Im using ubuntu 20.04 with wsl if this might be the cause.

**Comment by revelator** [comment]
Btw im using wsl from mobaxterm, does this have any negative impact on building ?.

**Comment by revelator** [comment]
oh heh you need to do wsl --set-version Ubuntu-20.04 2 mine was still running version 1

**Comment by revelator** [comment]
Works now though network in wsl2 is extremely unstable.
