### ISSUE TITLE
ocaml-core build error

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2477]
Error log:
  [ocaml-core_i686-w64-mingw32.zip](https://github.com/mxe/mxe/files/4435230/ocaml-core_i686-w64-mingw32.zip)

**Comment by dbyoung720** [comment]
wsl and ubuntu also error

**Comment by dbyoung720** [comment]
I'm curious, there are so many bugs that haven't been revised, why update the code urgently. Should n’t the bug fix be the most important thing?

**Comment by tonytheodore** [comment]
Some bugs, yes. 

The ocaml suite of packages is [very hard to update](https://github.com/mxe/mxe/pull/787), and at some point, fixing build errors on older versions becomes less important than [reviewing them from scratch](https://github.com/mxe/mxe/pull/2512).

In the mean time, you can build the rest of mxe with:
```
make EXCLUDE_PKGS='ocaml%'
```
