### ISSUE TITLE
Qt 5.7.1 downloads fail

### ISSUE THREAD

**Issue by uwehermann** [mxe/mxe#2483]
Hi, it seems Qt has moved around the location of their tarballs ***again***.

The last working location was https://download.qt.io/archive/qt/, but they have dropped a few tarballs from there.

Apparently the MXE alternative download mirrors don't have the packages either, though:

```
$ make download-only-qtbase MXE_PLUGIN_DIRS=plugins/examples/qt5-freeze
[download]    qtbase-opensource-src-5.7.1.tar.xz
MXE Warning! Downloading qtbase from backup.

Download failed or wrong checksum of package qtbase!
------------------------------------------------------------
--2020-04-13 17:47:06--  http://d1yihgixbnrglp.cloudfront.net/qtbase%2Dopensource%2Dsrc%2D5%2E7%2E1%2Etar%2Exz_edcdf549d94d98aff08e201dcb3ca25bc3628a37b1309e320d5f556b6b66557e
Resolving d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)... 13.225.78.140, 13.225.78.31, 13.225.78.217, ...
Connecting to d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)|13.225.78.140|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-13 17:47:07 ERROR 404: Not Found.
Download failed!
```

The same applies for the other Qt subpackages, like qtimageformats, qtsvg, qttranslations etc. etc.

I've tried setting other MIRROR_SITES, same result.

Would it be possible to put the Qt 5.7.1 tarballs up on the MXE mirrors to fix this? And/or point the script to another location where Qt 5.7.1 can still be downloaded? This is the last Qt release that supports Windows XP, so it would be great to keep it around for those who need/want XP support.

Thanks!

**Comment by tonytheodore** [comment]
Some packages are here http://distfiles.macports.org/qt5/.

If you find a site with all of them, I'm happy to add them to our mirrors.

**Comment by tonytheodore** [comment]
Actually, the unsuffixed versions were already on the mirrors - I've created suffixed versions now so you should be good to go.

Note you need to do:
```
make download-qt5 MXE_PLUGIN_DIRS=plugins/examples/qt5-freeze
```
as a simple `make download` will incorrectly make it look like later packages (e.g. qtnetworkauth) are missing. These weren't part of the 5.7 series.

**Comment by uwehermann** [comment]
Did a full build of MXE + Qt 5.7.x, works fine now, thanks a lot!

**Comment by uwehermann** [comment]
Hm, turns out the URL has indeed changed again, most of the stuff is now in a "new_archive" directory...

Sent a PR for this (#2487).
