### ISSUE TITLE
m4 fails to build

### ISSUE THREAD

**Issue by alex-tee** [mxe/mxe#2484]
https://paste.debian.net/1140432/

**Comment by alex-tee** [comment]
i don't know what exactly i'm doing but this fixed it:

```patch
diff --git a/plugins/native/m4-1-fixes.patch b/plugins/native/m4-1-fixes.patch
index 367d08e0..122df73e 100644
--- a/plugins/native/m4-1-fixes.patch
+++ b/plugins/native/m4-1-fixes.patch
@@ -23,3 +23,41 @@ index 1111111..2222222 100644
                  fbp[1] = '%';
                  fbp[2] = 'n';
                  fbp[3] = '\0';
+
+--- a/lib/freadahead.c
++++ b/lib/freadahead.c
+@@ -25,7 +25,7 @@
+ size_t
+ freadahead (FILE *fp)
+ {
+-#if defined _IO_ftrylockfile || __GNU_LIBRARY__ == 1 /* GNU libc, BeOS, Haiku, Linux libc5 */
++#if defined _IO_EOF_SEEN || __GNU_LIBRARY__ == 1 /* GNU libc, BeOS, Haiku, Linux libc5 */
+   if (fp->_IO_write_ptr > fp->_IO_write_base)
+     return 0;
+   return (fp->_IO_read_end - fp->_IO_read_ptr)
+
+--- a/lib/fseeko.c
++++ b/lib/fseeko.c
+@@ -47,7 +47,7 @@
+ #endif
+ 
+   /* These tests are based on fpurge.c.  */
+-#if defined _IO_ftrylockfile || __GNU_LIBRARY__ == 1 /* GNU libc, BeOS, Haiku, Linux libc5 */
++#if defined _IO_EOF_SEEN || __GNU_LIBRARY__ == 1 /* GNU libc, BeOS, Haiku, Linux libc5 */
+   if (fp->_IO_read_end == fp->_IO_read_ptr
+       && fp->_IO_write_ptr == fp->_IO_write_base
+       && fp->_IO_save_base == NULL)
+
+--- a/lib/stdio-impl.h
++++ b/lib/stdio-impl.h
+@@ -18,6 +18,12 @@
+    the same implementation of stdio extension API, except that some fields
+    have different naming conventions, or their access requires some casts.  */
+ 
++/* Glibc 2.28 made _IO_IN_BACKUP private.  For now, work around this
++   problem by defining it ourselves.  FIXME: Do not rely on glibc
++   internals.  */
++#if !defined _IO_IN_BACKUP && defined _IO_EOF_SEEN
++# define _IO_IN_BACKUP 0x100
++#endif
+ 
```

I tried things mentioned here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915150

**Comment by alex-tee** [comment]
I'm trying on ubuntu 18.04 and it seems to work there without changes. So I guess 19.10 is too new or not supported. feel free to close this if you think it is irrelevant.

**Comment by tonytheodore** [comment]
Very strange, that native m4 should only be built on the following systems with problematic autotools versions:
```
darwin
jessie
trusty
wheezy
```
trusty is ubuntu 14.04 and certainly shouldn't be included.

What is the output of the following commands:
```
lsb_release -sc
# and from mxe dir
make gmsl-print-OS_SHORT_NAME
```

**Comment by andredsm** [comment]
The same problem happens to me.
I'm using Ubuntu 20.04 with gcc 9.3.0

My settings.mk

```
# This is a template of configuration file for MXE. See
# docs/index.html for more extensive documentations.

# This variable controls the number of compilation processes
# within one package ("intra-package parallelism").
JOBS := 8 

# This variable controls where intermediate files are created
# this is necessary when compiling inside a virtualbox shared
# directory. Some commands like strip fail in there with Protocol error
# default is the current directory
#MXE_TMP := /tmp

# This variable controls the targets that will build.
MXE_TARGETS := x86_64-w64-mingw32.static
#MXE_TARGETS := i686-w64-mingw32.static i686-w64-mingw32.shared x86_64-w64-mingw32.static x86_64-w64-mingw32.shared

# This variable controls which plugins are in use.
# See plugins/README.md for further information.
override MXE_PLUGIN_DIRS += plugins/apps plugins/native plugins/gcc9

# This variable controls the download mirror for SourceForge,
# when it is used. Enabling the value below means auto.
#SOURCEFORGE_MIRROR := downloads.sourceforge.net

# The three lines below makes `make` build these "local
# packages" instead of all packages.
#LOCAL_PKG_LIST := boost curl file flac lzo pthreads vorbis wxwidgets
#.DEFAULT_GOAL  := local-pkg-list
#local-pkg-list: $(LOCAL_PKG_LIST)
```
Then I run make cc and got the following error on my log file:

> /opt/mxe/tmp-m4-x86_64-pc-linux-gnu/m4-1.4.18/lib/fseeko.c: In function 'rpl_fseeko':
> /opt/mxe/tmp-m4-x86_64-pc-linux-gnu/m4-1.4.18/lib/fseeko.c:110:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
>   110 |   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
>       |    ^~~~~
> make[5]: *** [Makefile:1910: fseeko.o] Error 1
> make[5]: *** Waiting for unfinished jobs....
> /opt/mxe/tmp-m4-x86_64-pc-linux-gnu/m4-1.4.18/lib/freadahead.c: In function 'freadahead':
> /opt/mxe/tmp-m4-x86_64-pc-linux-gnu/m4-1.4.18/lib/freadahead.c:92:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
>    92 |  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
>       |   ^~~~~
> make[5]: *** [Makefile:1910: freadahead.o] Error 1
> make[5]: Leaving directory '/opt/mxe/tmp-m4-x86_64-pc-linux-gnu/m4-1.4.18.build_/lib'
> make[4]: *** [Makefile:1674: all] Error 2
> make[4]: Leaving directory '/opt/mxe/tmp-m4-x86_64-pc-linux-gnu/m4-1.4.18.build_/lib'
> make[3]: *** [Makefile:1572: all-recursive] Error 1
> make[3]: Leaving directory '/opt/mxe/tmp-m4-x86_64-pc-linux-gnu/m4-1.4.18.build_'
> make[2]: *** [Makefile:1528: all] Error 2
> make[2]: Leaving directory '/opt/mxe/tmp-m4-x86_64-pc-linux-gnu/m4-1.4.18.build_'
> make[1]: *** [Makefile:846: build-only-m4_x86_64-pc-linux-gnu] Error 2
> make[1]: Leaving directory '/opt/mxe'
>

**Comment by tonytheodore** [comment]
> override MXE_PLUGIN_DIRS += plugins/apps plugins/native plugins/gcc9

Don't add `plugins/native` unless you really know you need to, the tools there are designed to be stable and conservative for problematic systems.

**Comment by andredsm** [comment]
Thanks very much. This solved my problem. I believed that using plugins/natives would only be used when necessary, even if I told it to do so.

**Comment by tonytheodore** [comment]
We'll eventually get to feature tests instead of platform/version checks, but that's a way off yet.
