### ISSUE TITLE
Failed to build vidstab

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2489]
x86_64-w64-mingw32.static/5.5.0/libgomp.a(target.o):(.text+0x37f): undefined reference to `dlerror'
x86_64-w64-mingw32.static/5.5.0/libgomp.a(target.o):(.text+0x389): undefined reference to `dlopen'
x86_64-w64-mingw32.static/5.5.0/libgomp.a(target.o):(.text+0x3a4): undefined reference to `dlsym'

**Comment by tonytheodore** [comment]
I can't replicate this - if it's still an issue, can you raise a new ticket and upload the entire log file to:
    https://gist.github.com/
    or your pastebin of choice
and put the link in the ticket.
