### ISSUE TITLE
Difficulties building ffmpeg with desired options

### ISSUE THREAD

**Issue by pcarroll36** [mxe/mxe#2501]
First off, my apologies if this is ‘dumb user’ error rather than a legitimate issue, but I’m seeing strange build results using the latest MXE, following steps that I have done in the past.  I’m not sure where else to turn.

I’m attempting to cross-compile ffmpeg, but using a modified build option in my ffmpeg.mk – but it would appear that my modified build options are being ignored, and it uses a set of ‘default’ options instead.  More specifically, here is what I’m doing….

`git clone https://github.com/mxe/mxe.git`
Modify ~/mxe/src/ffmpeg.mk, changing ‘define $(PKG)_BUILD’ to choose the options I want.  For example, I changed the options to instead --enable_pthreads --disable-w32threads.
`make MXE_TARGETS='x86_64-w64-mingw32.shared' ffmpeg MXE_USE_CCACHE=`

The build completes successfully, however, when I look at the log file, I see the following:

_cd '/home/pcarroll/mxe/tmp-ffmpeg-i686-w64-mingw32.shared/ffmpeg-4.2.2'
cd '/home/pcarroll/mxe/tmp-ffmpeg-i686-w64-mingw32.shared/ffmpeg-4.2.2.build_' && '/home/pcarroll/mxe/tmp-ffmpeg-i686-w64-mingw32.shared/ffmpeg-4.2.2/configure' --cross-prefix='i686-w64-mingw32.shared'- --enable-cross-compile --arch=i686 --target-os=mingw32 --prefix='/home/pcarroll/mxe/usr/i686-w64-mingw32.shared'  --disable-static --enable-shared  --yasmexe='i686-w64-mingw32.shared-yasm' --disable-debug --disable-pthreads --enable-w32threads --disable-doc --enable-avresample --enable-gpl --enable-version3 --extra-libs='-mconsole' --enable-avisynth --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid_ 

Which are not the options that I had specified??

I tired it on a couple of Ununtu 20.04 installs, and a Ubuntu 18.04 install – same result.

Any assistance is appreciated.

/Paul

**Comment by tonytheodore** [comment]
Strange, maybe some git operation reverted the file on disk - do you have those in a separate branch?

The recommended way to specify options is:
```
make \
    MXE_TARGETS='x86_64-w64-mingw32.shared' \
    MXE_USE_CCACHE= \
    ffmpeg \
    ffmpeg_CONFIGURE_OPTS='--enable_pthreads --disable-w32threads'
```
That should avoid any surprises and having to modify local files.

**Comment by pcarroll36** [comment]
Tony, thanks for the response
> 
> 
> Strange, maybe some git operation reverted the file on disk - do you have those in a separate branch?

No branch.  I just cloned the repo with the cited command, resulting with the 'master' branch.
> 
> The recommended way to specify options is:
> 
> ```
> make \
>     MXE_TARGETS='x86_64-w64-mingw32.shared' \
>     MXE_USE_CCACHE= \
>     ffmpeg \
>     ffmpeg_CONFIGURE_OPTS='--enable_pthreads --disable-w32threads'
> ```
Doing the above DOES add the requested CONFIGURE_OPTS.  However, it just adds the requested options after all of the other 'default' options.  This does not give me enough control on the options.  Indeed, using the two options above results in both pthreads and w32threads both being enabled and disabled.  As in
 ```
cd '/home/pcarroll/mxe/tmp-ffmpeg-x86_64-w64-mingw32.shared/ffmpeg-4.2.2.build_' && '/home/pcarroll/mxe/tmp-ffmpeg-x86_64-w64-mingw32.shared/ffmpeg-4.2.2/configure' --cross-prefix='x86_64-w64-mingw32.shared'- --enable-cross-compile --arch=x86_64 --target-os=mingw32 --prefix='/home/pcarroll/mxe/usr/x86_64-w64-mingw32.shared'  --disable-static --enable-shared  --yasmexe='x86_64-w64-mingw32.shared-yasm' --disable-debug --disable-pthreads --enable-w32threads --disable-doc --enable-avresample --enable-gpl --enable-version3 --extra-libs='-mconsole' --enable-avisynth --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-pthreads --disable-w32threads
 ```

Thanks

**Comment by tonytheodore** [comment]
In almost any program I've seen, later options on the command line override previous ones. Even though you see them twice, the final ones prevail.

Review the options summary in the ffmpeg log to see if it has done the right thing.

**Comment by tonytheodore** [comment]
If you want more control, have a look at [plugins](https://github.com/mxe/mxe/tree/master/plugins), especially the [minimal qt example](https://github.com/mxe/mxe/blob/master/plugins/examples/custom-qt-min/overrides.mk).

Essentially, you can create a file in a directory outside of mxe and set the minimal `_DEPS` and `_BUILD` you need.

ffmpeg is also built out-of-source, so you can also specify a `_SOURCE_TREE` that points to a local repo. You could also add fdk-aac or openssl support which we disable due to [licence ambiguity/incompatibility](https://mxe.cc/#potential-legal-issues).
