### ISSUE TITLE
Failed to build glib_x86_64-apple-darwin19.3.0

### ISSUE THREAD

**Issue by alitrack** [mxe/mxe#2505]
I use brew and the master version of mxe,

```
git clone https://github.com/mxe/mxe
``` 

when compile glib, failed, and the full log is here,

https://gist.github.com/alitrack/d19132acf7b7a538748d4489925e808e

**Comment by eliezedeck** [comment]
I'm also having this exact problem. At this point, it has become blocking. The minor different is that mine is `x86_64-apple-darwin19.4.0`.

**Comment by tonytheodore** [comment]
Does https://github.com/mxe/mxe/commit/1f0ba2d3ff8891efd0be93aac6b642ed188f0e6a fix it?

**Comment by alitrack** [comment]
Yes!
