### ISSUE TITLE
jack

### ISSUE THREAD

**Issue by dblanchemain** [mxe/mxe#2508]
make jack MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static' failed

**Comment by tonytheodore** [comment]
jack and aubio are know to fail on darwin (and possibly any system without python2). They use the `waf` build system which I'm not familiar enough with to update.

**Comment by tonytheodore** [comment]
Can you check if https://github.com/mxe/mxe/commit/dcc6131619a37d8e4c2e9ba6cea700c61a9c71d6 fixes it?
