### ISSUE TITLE
gcc 5.5 fails to build qtbase 5.15

### ISSUE THREAD

**Issue by maxwell130631** [mxe/mxe#2509]
Hi,
I tried to compile mxe (cloned today) with the following command:
make cc qt5 qtquickcontrols2  qtsvg -j8 MXE_TARGETS=x86_64-w64-mingw32.shared.posix

and end up with an error in qtbase (version 5.15):
```

/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/bin/moc -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_NO_
LINKED_LIST -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_USING_NAMESPACE -DQT_NO_FOREACH -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_CORE_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_U
SE_MATH_DEFINES -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQ
T_NO_DEBUG -DQ_USE_SYBASE --include /opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/corelib/.moc/release/moc_predefs.h -I/opt/mxe/tmp-qtbase-x86_64-w64-
mingw32.shared.posix/qtbase-everywhere-src-5.15.0/mkspecs/win32-g++ -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/corelib -I/opt/mxe/tmp-qtbase-x86_
64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/corelib/global -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/3rdparty/md5 -I/opt/mxe/tm
p-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/3rdparty/md4 -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/3rdparty/sha3 -
I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/3rdparty -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/3rdpart
y/double-conversion/include -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/3rdparty/harfbuzz/src -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posi
x/qtbase-everywhere-src-5.15.0/src/3rdparty/tinycbor/src -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/corelib/.rcc/release -I/opt/mxe/tmp-qtbase-x8
6_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/include -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/include/QtCore -I/opt/mxe/tmp-qtbase-x8
6_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/include/QtCore/5.15.0 -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/include/QtCore/5.15.0/QtC
ore -I/opt/mxe/tmp-qtbase-x86_64-w64-mingw32.shared.posix/qtbase-everywhere-src-5.15.0/src/corelib/tmp -I/opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.shared.posix/5.5.0/include/c++ -I/opt/mxe/us
r/lib/gcc/x86_64-w64-mingw32.shared.posix/5.5.0/include/c++/x86_64-w64-mingw32.shared.posix -I/opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.shared.posix/5.5.0/include/c++/backward -I/opt/mxe/usr/
lib/gcc/x86_64-w64-mingw32.shared.posix/5.5.0/include -I/opt/mxe/usr/lib/gcc/x86_64-w64-mingw32.shared.posix/5.5.0/include-fixed -I/opt/mxe/usr/x86_64-w64-mingw32.shared.posix/include --out
put-json animation/qpauseanimation.h -o .moc/release/moc_qpauseanimation.cpp
In file included from kernel/qeventdispatcher_win.cpp:48:0:
kernel/qsocketnotifier.h:113:33: error: enclosing class of constexpr non-static member function 'void* QSocketDescriptor::winHandle() const' is not a literal type
     Q_DECL_CONSTEXPR Qt::HANDLE winHandle() const noexcept { return sockfd; }
                                 ^
kernel/qsocketnotifier.h:94:7: note: 'QSocketDescriptor' is not literal because:
 class QSocketDescriptor
       ^
kernel/qsocketnotifier.h:94:7: note:   'QSocketDescriptor' is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move cons
tructor
kernel/qsocketnotifier.h:115:22: error: enclosing class of constexpr non-static member function 'QSocketDescriptor::operator QSocketDescriptor::DescriptorType() const' is not a literal type
     Q_DECL_CONSTEXPR operator DescriptorType() const noexcept { return sockfd; }
                      ^
make[5]: *** [Makefile.Release:47489: .obj/release/qeventdispatcher_win.o] Error 1
make[5]: *** Waiting for unfinished jobs....


```

**Comment by maxwell130631** [comment]
Is this related to the following?
https://stackoverflow.com/questions/36489369/constexpr-non-static-member-function-with-non-constexpr-constructor-gcc-clang-d

**Comment by Te-M** [comment]
Don't mean to muddy things but I've oddly also seen qtbase fail to build recently (like within the last week or so?) on my non-clean Debain VM w/ x86_64-w64-mingw32.static.

`[build]       qtbase                 x86_64-w64-mingw32.static

Failed to build package qtbase for target x86_64-w64-mingw32.static!
------------------------------------------------------------
make[3]: *** [Makefile:202: sub-corelib-make_first] Error 2
make[3]: Leaving directory '/home/osboxes/mxe/tmp-qtbase-x86_64-w64-mingw32.static/qtbase-everywhere-src-5.15.0/src'
make[2]: *** [Makefile:54: sub-src-make_first] Error 2
make[2]: Leaving directory '/home/osboxes/mxe/tmp-qtbase-x86_64-w64-mingw32.static/qtbase-everywhere-src-5.15.0'
make[1]: *** [Makefile:846: build-only-qtbase_x86_64-w64-mingw32.static] Error 2
make[1]: Leaving directory '/home/osboxes/mxe'
real	1m18.853s
user	1m0.427s
sys	0m11.142s
------------------------------------------------------------
[log]      /home/osboxes/mxe/log/qtbase_x86_64-w64-mingw32.static

make: *** [Makefile:834: /home/osboxes/mxe/usr/x86_64-w64-mingw32.static/installed/qtbase] Error 1`

**Comment by mabrand** [comment]
Build succeeds reliably for me running on Ubuntu 20.04, using these settings:
- MXE_TARGETS := x86_64-w64-mingw32.static x86_64-w64-mingw32.shared
- MXE_PLUGIN_DIRS := plugins/gcc10

Pretty sure it works with gcc9 too.

Have you tried it with a more recent gcc?

I'll see if I can reproduce the problem for target x86_64-w64-mingw32.shared.posix and/or default gcc 5.5.

**Comment by maxwell130631** [comment]
I also used Ubuntu 20.04, but I was  not using the plugins/gcc10 options. Thanks for making me aware of that, I thought only 5.5 is available. I will try to compile using 5.5

**Comment by mabrand** [comment]
In the meantime, I have confirmed the build failure with gcc 5.5. Very unlikely that this is specific to .posix target. Please try building with a newer gcc version using a command something like this:

    make qtquickcontrols2 JOBS=8 -j8 MXE_TARGETS=x86_64-w64-mingw32.shared.posix MXE_PLUGIN_DIRS=plugins/gcc10

If you have problems with some packages on gcc10, try gcc9.

Note that it's enough to specify qtquickcontrols2. The dependencies will be built automatically.

**Comment by mabrand** [comment]
@tonytheodore What's your thinking about updating the default gcc version?

**Comment by tonytheodore** [comment]
@mabrand, I'll try back-porting that to gcc5, but I think we shouldn't have a "default" gcc going forward.

Time to coalesce my ideas and close out #1205

**Comment by Te-M** [comment]
Just a late update, the plugin addition (on clean) worked for me as well.  I also didn't even know the plugins were a thing or which version gcc was defaulting to!

**Comment by maxwell130631** [comment]
I also was possible to compile without problems using gcc 10
