### ISSUE TITLE
Revisit qtwebengine

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#2515]
qtwebengine was [removed some time ago](https://github.com/mxe/mxe/pull/1513) since it [required MSVC at the time](https://github.com/mxe/mxe/issues/747#issuecomment-129187387). Also #1509 #1512

@mabrand, looking at https://download.qt.io/official_releases/qt/5.15/5.15.0/submodules, it looks we can revisit:

webengine
webglplugin

**Comment by mabrand** [comment]
Do you see something in https://download.qt.io/official_releases/qt/5.15/5.15.0/submodules that suggests qtwebengine no longer requires MSVC?

**Comment by tonytheodore** [comment]
[MSVC is still required:](https://doc.qt.io/qt-5/qtwebengine-platform-notes.html#windows)

> On Windows, the following additional tools are required:

>Visual Studio 2017 version 15.8 or later
>Active Template Library (ATL), usually included in the Visual Studio installation
>Windows 10 SDK version 10.0.18362 or later
