### ISSUE TITLE
[PATCH] Qt 5.15 fails to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by mbunkus** [mxe/mxe#2517]
I've just filed [QTBUG-84792](https://bugreports.qt.io/browse/QTBUG-84792) but thought it would be good to have here, too:

Qt 5.15 fails to build on Ubuntu 18.04 due to `zstd` being too old. The build process uses the option `--single-thread` when invoking `zstd`, and the version coming with Ubuntu 18.04 simply doesn't support that one yet.

It affects all architectures, both static & dynamic versions. My MXE is at f5fe0a81. I'm using the gcc 10 overlay, though that should be of no consequence to the failure in question.

Relevant error message is:

```
perl /opt/mxe/tmp-qtbase-x86_64-w64-mingw32.static/qtbase-everywhere-src-5.15.0/src/corelib/mimetypes/mime/generate.pl --zstd mimetypes/mime/packages/freedesktop.org.xml > .rcc/release/qmimeprovider_database.cpp
Incorrect parameters
Failed to run zstd -cq19 --single-thread < mimetypes/mime/packages/freedesktop.org.xml at /opt/mxe/tmp-qtbase-x86_64-w64-mingw32.static/qtbase-everywhere-src-5.15.0/src/corelib/mimetypes/mime/generate.pl line 82.
```

I'm now using [this small additional patch](https://gist.github.com/mbunkus/529f6799b7e13ad57fc82211bcb2a980) which simply patches the option out.

**Comment by tonytheodore** [comment]
I wonder if we should simply build the native zstd binary, the [lib is now used by gcc10](https://gcc.gnu.org/install/prerequisites.html) so it will generally be available. It also has a Makefile so doesn't really require cmake for the native build.

**Comment by tonytheodore** [comment]
@mbunkus, see #2520.

You can avoid a full rebuild with:
```
make -t qtbase
touch src/zstd.mk
make qtbase
```

**Comment by mbunkus** [comment]
Thanks, I'll give it a try once #2522 has been resolved.

**Comment by mbunkus** [comment]
#2520 fixed the issue for me. Thanks!
