### ISSUE TITLE
failed to build gtk3 x86_64-w64-mingw32.static under WSL

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2519]
[gtk3_x86_64-w64-mingw32.zip](https://github.com/mxe/mxe/files/4750467/gtk3_x86_64-w64-mingw32.zip)

failed to build gtk3 x86_64-w64-mingw32.static under WSL

**Comment by tonytheodore** [comment]
> /bin/bash: line 1: gdbus-codegen: command not found

Did you install `libgdk-pixbuf2.0-dev`? It should depend on `libglib2.0-dev` which depends on `libglib2.0-dev-bin` which in turn includes the missing `gdbus-codegen`

**Comment by dbyoung720** [comment]
![aaa](https://user-images.githubusercontent.com/11304997/84209986-251dca80-aaea-11ea-9405-9ac6b3342baf.png)

**Comment by tonytheodore** [comment]
So where is `gdbus-codegen`?

**Comment by dbyoung720** [comment]
ok pass
