### ISSUE TITLE
failing to use latest MXE master to build libbson out of tree

### ISSUE THREAD

**Issue by lunixbochs** [mxe/mxe#2521]
A recent MXE update is breaking libbson builds for me (cross compiling from Ubuntu Linux -> Windows), I think it's due to defining `__USE_MINGW_ANSI_STDIO=0` in 56a46e8796556438bef7b0e3664dd03a52af98ba as I'm now getting this error:
```
mongo-c-driver-1.10.2/src/libbson/src/bson/bson-compat.h:30:2: error: #error "__USE_MINGW_ANSI_STDIO > 0 is required for correct PRI* macros"
 #error "__USE_MINGW_ANSI_STDIO > 0 is required for correct PRI* macros"```

**Comment by tonytheodore** [comment]
The remaining patch for gettext is already applied upstream and it simply adds those sections twice - it should be removed.

It was also there in the previous version and the `__USE_MINGW_ANSI_STDIO` should only apply to the gettext build, it shouldn't affect downstream packages.

**Comment by lunixbochs** [comment]
Ok, I might work on bisecting this, as reverting to the commit before this did fix it.

**Comment by tonytheodore** [comment]
I suspect it could be the [mingw-w64 v7 update](https://github.com/mxe/mxe/pull/2478):
```
$ echo "#include <windows.h>" | i686-w64-mingw32.static-cpp -E -dD | grep _MINGW_ANSI
#define __USE_MINGW_ANSI_STDIO 0
```
I'll test the default def prior to that.

**Comment by tonytheodore** [comment]
Previously, it was undefined by default.

You can simply add the def to cflags during the build of libbson.

**Comment by lunixbochs** [comment]
Thanks! My bisect confirmed it was the v7 update as well. Not an MXE issue then, closing.
