### ISSUE TITLE
fails to build cmake 3.17.3 due to not finding OpenSSL

### ISSUE THREAD

**Issue by mbunkus** [mxe/mxe#2522]
Since updating cmake to 3.17.3 building fails on Ubuntu 18.04 for both x86_64 and i686. Excerpt from the build logs:

```
…
-- Looking for gethostname
-- Looking for gethostname - found
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
CMake Error at Utilities/cmcurl/CMakeLists.txt:454 (message):
  Could not find OpenSSL.  Install an OpenSSL development package or
  configure CMake with -DCMAKE_USE_OPENSSL=OFF to build without OpenSSL.
```

Full build log is [here](https://gist.github.com/mbunkus/cdbd552ad36d26e2bc344f6b4d474024).

MXE is at 32f34925078b49c3b0490d5a54d68601e8915d75.

**Comment by tonytheodore** [comment]
Can you see if #2523 fixes it? 

Otherwise an [approach using system curl](https://github.com/tonytheodore/mxe/commit/3e52e35b6b2ec4f8c95e1072f34d8c0eb6b1260c) may be required.

**Comment by mbunkus** [comment]
Thanks for your quick reaction. Your PR does not fix the issue for me; the error message is the following:

```
…
-- Looking for gethostname
-- Looking for gethostname - found
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
CMake Error at Utilities/cmcurl/CMakeLists.txt:454 (message):
  Could not find OpenSSL.  Install an OpenSSL development package or
  configure CMake with -DCMAKE_USE_OPENSSL=OFF to build without OpenSSL.
```

**Comment by tonytheodore** [comment]
If `libssl-dev` is installed (should be since it worked with previous version), can you try adding:
```
cmake_CONFIGURE_OPTS='--system-curl'
```
to your make invocation. If that works, I'll add it to plugins/native/bionic so it gets picked up automatically.

**Comment by mbunkus** [comment]
I don't have `libssl-dev` installed, and MXE used to compile just fine on this machine (packages `gettext libiconv zlib boost file flac lzo ogg pthreads vorbis cmark libdvdread qtbase qttranslations qtwinextras`).

After installing `libssl-dev`, I've done some more tests by running `make MXE_TARGETS=x86_64-w64-mingw32.static cmake` Each run was done with an empty `usr`.

1. without 2523 applied, without setting `cmake_CONFIGURE_OPTS`: works ✓
2. without 2523 applied, but with setting `cmake_CONFIGURE_OPTS`: fails ✗ (see below)
3. with 2523 applied but without setting `cmake_CONFIGURE_OPTS`: works ✓
4. with 2523 applied and with `cmake_CONFIGURE_OPTS`: fails ✗ (see below)
 
Relevant log messages for cases 2 & 4 (identical for both cases):

```
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
CMake Error at CMakeLists.txt:442 (message):
  CMAKE_USE_SYSTEM_CURL is ON but a curl is not found!
Call Stack (most recent call first):
  CMakeLists.txt:710 (CMAKE_BUILD_UTILITIES)
```

**Comment by tonytheodore** [comment]
> I don't have libssl-dev installed, 

It's been in the requirements [for a long time](https://github.com/mxe/mxe/commit/7736ddb896914093f4e0d214ed8fd63e75194b58) ;)

> and MXE used to compile just fine on this machine

It looks like this is [now a deliberate error to avoid inadvertently building curl without openssl](https://gitlab.kitware.com/cmake/cmake/-/commit/dd3e4767863dfe1307d4dccd2445e5312b55473e).

I've just upgraded pkg.mxe.cc from Ubuntu 16.04 to 18.04 and can confirm scenarios 1 & 2, 2/3/4 were just guesses. With 1 being the path of least resistance, I think this can be closed.

P.S. the upgrade was so seamless I'm going to bump it to 20.04. I've been putting it off for years - this was a nice prompt!

**Comment by mbunkus** [comment]
> It's been in the requirements for a long time ;)

Huh… would you look at that. I hadn't realized. Sorry for the confusion :)

I just happened to never need that package, and unlike the required binaries the build system doesn't actually yell at me loudly when I don't have it installed :)
