### ISSUE TITLE
support bison/flex/gimp/vlc/mpv

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2524]
Great job.
Hope to add compilation of bison/flex/gimp/vlc/mpv

**Comment by tonytheodore** [comment]
Those are a little out of scope, but you can look at:

https://github.com/mxe/mxe/tree/master/plugins
https://github.com/mxe/mxe/tree/master/plugins/examples/host-toolchain
https://github.com/mxe/mxe/tree/master/plugins/apps

for various ways to achieve the goal yourself.
