### ISSUE TITLE
failed to build vidstab x86_64-w64-mingw32.static under WSL

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2526]
../x86_64-w64-mingw32.static/5.5.0/libgomp.a(target.o):(.text+0x37f): undefined reference to `dlerror'
../x86_64-w64-mingw32.static/5.5.0/libgomp.a(target.o):(.text+0x389): undefined reference to `dlopen'
../x86_64-w64-mingw32.static/5.5.0/libgomp.a(target.o):(.text+0x3a4): undefined reference to `dlsym'
[vidstab_x86_64-w64-mingw32.zip](https://github.com/mxe/mxe/files/4801576/vidstab_x86_64-w64-mingw32.zip)

**Comment by tonytheodore** [comment]
Interesting, if gcc is rebuilt after dlfcn-win32, then it detects and uses the dl* functions.
