### ISSUE TITLE
failed to build ocaml-cairo i686-w64-mingw32.static under ubuntu 

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2527]
[log.zip](https://github.com/mxe/mxe/files/4803118/log.zip)

**Comment by tonytheodore** [comment]
This is mostly expected and [the ocaml suite is being removed from the default build](https://github.com/mxe/mxe/pull/2512).

In the mean time, you can run:
```
make EXCLUDE_PKGS='ocaml%' ...
```

**Comment by dbyoung720** [comment]
luajit also error
How to exclude two pgks? ocaml% and juajit?

**Comment by tonytheodore** [comment]
```
make EXCLUDE_PKGS='luajit ocaml%' ...
```
See also https://github.com/mxe/mxe/commit/82815094423ea04fc1aef6cf850adabc0cae9846, WSL1 doesn't support 32-bit execution.
