### ISSUE TITLE
SDL2_mixer no MP3 support

### ISSUE THREAD

**Issue by maavelar5** [mxe/mxe#2538]
I'd been stuck with the "**No MP3 support**" error while calling `Mix_Init` from SDL2_mixer. I tried looking for a solution but I couldn't find anything. After going through the logs I noticed this:

```
...
checking for mpg123.h... yes
checking for mpg123_replace_reader_handle in -lmpg123... no
configure: WARNING: *** Unable to find mpg123 library (https://www.mpg123.de)
configure: WARNING: mpg123 support disabled
configure: WARNING: MP3 support disabled
...
```

I managed to work around it by adding `-lshlwapi` to the `LIBS` section of `sdl2_mixer.mk`. I'm not sure if this is a proper fix but I wanted to let you guys know of the problem, I'm happy to provide more details if needed.

**Comment by tonytheodore** [comment]
See https://github.com/mxe/mxe/commit/c0327469677e8f82ca99692efcf3b8f200c2c515
```
checking mpg123.h usability... yes
checking mpg123.h presence... yes
checking for mpg123.h... yes
checking for mpg123_replace_reader_handle in -lmpg123... yes
```

**Comment by maavelar5** [comment]
Thanks @tonytheodore this fixes the issue. I'll close this ticket.
