### ISSUE TITLE
qtbase debug-and-release build fail

### ISSUE THREAD

**Issue by breitc** [mxe/mxe#2539]
mxe build failed for me when running
```make qtbase_CONFIGURE_OPTS=-debug-and-release MXE_TARGETS="x86_64-w64-mingw32.shared" qtbase qtdeclarative qtgraphicaleffects qtimageformats qtlocation qtmultimedia qtquickcontrols qtquickcontrols2 qtsensors qtservice qtsvg qttranslations qtwinextras qtxmlpatterns qttools```

build log: https://gist.github.com/breitc/52770d148cb5da76f5d14edee4bc3099

This is my first issue report, so I don't know the best way to provide information, but the fix that worked for me was:

```diff --git a/src/qtbase.mk b/src/qtbase.mk
index d13c5be1..d9ac501f 100644
--- a/src/qtbase.mk
+++ b/src/qtbase.mk
@@ -76,7 +76,7 @@ define $(PKG)_BUILD
 
     mkdir            '$(1)/test-qt'
     cd               '$(1)/test-qt' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' '$(PWD)/src/qt-test.pro'
-    $(MAKE)       -C '$(1)/test-qt' -j '$(JOBS)'
+    $(MAKE)       -C '$(1)/test-qt' '$(BUILD_TYPE)' -j '$(JOBS)'
     $(INSTALL) -m755 '$(1)/test-qt/$(BUILD_TYPE)/test-qt5.exe' '$(PREFIX)/$(TARGET)/bin/'
 
     # build test the manual way```

**Comment by tonytheodore** [comment]
Thanks!
