### ISSUE TITLE
GCC v8.4.0 build fails due patching rejection

### ISSUE THREAD

**Issue by FyreDemonyte** [mxe/mxe#2540]
```c
[download]    gcc-8.4.0.tar.gz
[build]       gcc                    i686-w64-mingw32.static

Failed to build package gcc for target i686-w64-mingw32.static!
------------------------------------------------------------
patching file gcc/cp/constexpr.c
Hunk #1 FAILED at 219.
1 out of 1 hunk FAILED -- saving rejects to file gcc/cp/constexpr.c.rej
Makefile:827: recipe for target 'build-only-gcc_i686-w64-mingw32.static' failed
make[1]: *** [build-only-gcc_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory '/home/demon/dev/mxe'
real	0m16.122s
user	0m14.816s
sys	0m3.757s
------------------------------------------------------------
[log]      /home/demon/dev/mxe/log/gcc_i686-w64-mingw32.static

Makefile:827: recipe for target '/home/demon/dev/mxe/usr/i686-w64-mingw32.static/installed/gcc' failed
make: *** [/home/demon/dev/mxe/usr/i686-w64-mingw32.static/installed/gcc] Error 1
```
### Log file:
[gcc_i686-w64-mingw32.static](https://gist.github.com/FyreDemonyte/4c03b0596d7861bffa1fda356ac0cb13)

This also occurs with version 10.1.0 as well.

**Comment by tonytheodore** [comment]
Try using the gcc plugins with version-specific patches:
```
make MXE_PLUGIN_DIRS=plugins/gcc8
```

**Comment by FyreDemonyte** [comment]
Thank you! Silly me I forgot about the plugins. 

Also since gcc7 is Ubuntu 18's default compiler. I installed gcc-8. Since I think it wouldn't make sense to build gcc8 with gcc7 possibly to due symbol differences, optimizations, etc ?

`/usr/lib/gcc/x86_64-linux-gnu/7/cc1plus`
`/usr/lib/gcc/x86_64-linux-gnu/8/cc1plus`

**Comment by tonytheodore** [comment]
> Since I think it wouldn't make sense to build gcc8 with gcc7 possibly due to symbol differences, optimizations, etc ?

For most of mxe, the system compiler doesn't make much of a difference. `gcc` can bootstrap itself with almost any c++ compiler, and the handful of native builds have a bigger issues with `libc` and other libraries than they do with the compiler per se.

At some point, gcc8 had to be buildable with gcc7, gcc7 with gcc6, and on and on.
