### ISSUE TITLE
difference in new version

### ISSUE THREAD

**Issue by anzyelay** [mxe/mxe#2543]
https://github.com/mxe/mxe/blob/885a03134121f7564bd49313a70e3d372a546192/src/binutils-1-fixes.patch#L31

**Comment by tonytheodore** [comment]
Could you explain the issue a little more?

**Comment by anzyelay** [comment]
the context in remark  /*  */ has changed in the new version file，when I build mxe  last time，it report patch  failure here.  but  yesterday I clean the build environment and rebuild it ，it is perfect right. nothing wrong!
