### ISSUE TITLE
devil compile error

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2547]
../../DentonW-DevIL-cba359b/DevIL/src-IL/src/il_jp2.cpp:357:1: error: invalid conversion from 'int (*)(jas_stream_obj_t*, char*, int) {aka int (*)(void*, char*, int)}' to 'int (*)(jas_stream_obj_t*, char*, unsigned int) {aka int (*)(void*, char*, unsigned int)}' [-fpermissive]

**Comment by Tostis** [comment]
Same problem here on Ubuntu 20.04.1 LTS Focal Fossa

**Comment by mabrand** [comment]
I reproduced the problem building with gcc 10. Not sure why this error was not reported earlier, but using the -fpermissive option seems to work around the problem.
