### ISSUE TITLE
problems in crosscompiling with qt5

### ISSUE THREAD

**Issue by aquiles2k** [mxe/mxe#2562]
Hi,
i have problems using cross-compiled qt5 qmake (on mac) to build my applications.

I compiled the i686-w64-mingw32.shared.dw2 toolchain and created my projects Makefile with

```
/Users/holgermacmini/dev/mxe_5.15.0/usr/i686-w64-mingw32.shared.dw2/qt5/bin/qmake /Users/holgermacmini/dev/sources/osc/quazip/quazip.pro
```

When calling make i get the following error:
```
/Users/holgermacmini/dev/mxe_5.15.0/usr/bin/i686-w64-mingw32.shared.dw2-g++ -c -pipe -O2 -g -std=gnu++11  -arch x86_64 -isysroot /Applications/Xcode11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC -DRELEASE_BUILD -DQUAZIP_BUILD -DQT_NO_DEBUG -DQT_CORE_LIB -I../../../../sources/osc/quazip -I. -I../../../../sources/osc/quazip -I../../../../mxe_5.15.0/usr/i686-w64-mingw32.shared.dw2/qt5/include -I../../../../mxe_5.15.0/usr/i686-w64-mingw32.shared.dw2/qt5/include/QtCore -I.moc -I../../../../mxe_5.15.0/usr/i686-w64-mingw32.shared.dw2/qt5/mkspecs/macx-g++ -o .obj/qioapi.o ../../../../sources/osc/quazip/qioapi.cpp
i686-w64-mingw32.shared.dw2-g++: error: x86_64: No such file or directory
i686-w64-mingw32.shared.dw2-g++: error: unrecognized command line option '-arch'
i686-w64-mingw32.shared.dw2-g++: error: unrecognized command line option '-mmacosx-version-min=10.13'
make: *** [.obj/qioapi.o] Error 1
```

It seems as if hes trying to build for mac but i dont have any clue why so. Any hints on what i might be doing wrong?

**Comment by tonytheodore** [comment]
Looks bizarre, are flags like '-arch' and '-mmacosx-version-min=10.13' in the generated Makefile or are they coming from env vars?

**Comment by tonytheodore** [comment]
Actually, I think quazip.pro is fairly broken - look at the [mxe package](https://github.com/mxe/mxe/blob/master/src/quazip.mk) and [it's been removed upstream](https://github.com/stachenov/quazip/commit/1cf777c97705bf932e95dda6c2c8824b12f994e8)

**Comment by aquiles2k** [comment]
No, they are in the generated Makefile:
```
CXXFLAGS      = -pipe -O2 -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)

...

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
```

As far as i can see these come from:
```
mkspecs/features/mac/default_post.prf

device|!simulator: VALID_DEVICE_ARCHS = $$QMAKE_APPLE_DEVICE_ARCHS
simulator: VALID_SIMULATOR_ARCHS = $$QMAKE_APPLE_SIMULATOR_ARCHS
VALID_ARCHS = $$VALID_DEVICE_ARCHS $$VALID_SIMULATOR_ARCHS
```
and
```
mkspecs/common/macx.conf

QMAKE_APPLE_DEVICE_ARCHS = x86_64
```

To me it looks like that the qt installation is not configured for cross compilation? But i know too little about qt compilation/configuration to know where to look for.

Can anybody check on their mac what they are supposed to look like?

I tried to look at my old qt11.2 mxe install but it seems to much has changed since then and these variables aren't used there at all.

I can post the qt build log if that helps.

Oh and i wanted to try with current master but am running into #2561.

**Comment by aquiles2k** [comment]
I have no clue what went wrong back then, but my current setup now works, so im closing this.
