### ISSUE TITLE
Failed to build package qtbase for target i686-w64-mingw32.static!

### ISSUE THREAD

**Issue by icolcoin** [mxe/mxe#2568]
hello i am using linux ubuntu 14.04 server **64Bit**
when running this command
make MXE_TARGETS="i686-w64-mingw32.static" qttools

Error:
[download]    qtbase-everywhere-src-5.15.1.tar.xz
[build]       qtbase                 i686-w64-mingw32.static

Failed to build package qtbase for target i686-w64-mingw32.static!
------------------------------------------------------------
       , _copyIter(IteratorOwner<typename T::const_iterator>::assign)
                                                                    ^
make[2]: *** [main.o] Error 1
make[2]: se sale del directorio «/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmake»
make[1]: *** [build-only-qtbase_i686-w64-mingw32.static] Error 2
make[1]: se sale del directorio «/root/mnt/mxe»
real    0m7.016s
user    0m5.120s
sys     0m0.644s
------------------------------------------------------------
[log]      /root/mnt/mxe/log/qtbase_i686-w64-mingw32.static

make: *** [/root/mnt/mxe/usr/i686-w64-mingw32.static/installed/qtbase] Error 1

**Comment by icolcoin** [comment]
now i send them but i was investigating i found this:
Due to The Qt Company offering changes, open source offline installers are not available any more since Qt 5.15. Read more about offering changes in the https://www.qt.io/blog/qt-offering-changes-2020 blog.

If you need offline installers, please consider our new Qt for Small Business offering: https://www.qt.io/blog/available-now-qt-for-small-businesses

**Comment by icolcoin** [comment]
https://github.com/mxe/mxe/blob/master/src/qtbase.mk
the link I found was dead:
line 17     $(WGET) -q -O- https://download.qt.io/official_releases/qt/5.8/ | \

**Comment by icolcoin** [comment]
make[1]: se ingresa al directorio Â«/root/mnt/mxeÂ»
uname -a
Linux ubuntu 4.4.0-142-generic #168~14.04.1-Ubuntu SMP Sat Jan 19 11:26:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
git log --pretty=tformat:"%H - %s [%ar] [%d]" -1
2260aa80f9f6621b862b867d1fd386d53c3b4ed9 - opencv: fix build with latest jasper [hace 2 dÃ­as] [ (HEAD, origin/master, origin/HEAD, master)]
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty
autoconf --version 2>/dev/null | head -1
autoconf (GNU Autoconf) 2.69
automake --version 2>/dev/null | head -1
automake (GNU automake) 1.16.1
gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

python --version
Python 2.7.6
perl --version 2>&1 | head -3

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 55 registered patches, see perl -V for more detail)
rm -rf   '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static'
mkdir -p '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static'
mkdir -p '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1'
mkdir -p '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1.build_'
# disable wine with readonly directory
# see https://github.com/mxe/mxe/issues/841
mkdir -p '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/readonly'
chmod 0555 '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/readonly'
cd '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static' &&          xz -dc '/root/mnt/mxe/pkg/qtbase-everywhere-src-5.15.1.tar.xz' | tar xf -
cd '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1'
(cd '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1' && patch -p1 -u) < /root/mnt/mxe/src/qtbase-1-fixes.patch
patching file mkspecs/features/data/cmake/Qt5BasicConfig.cmake.in
patching file src/gui/configure.json
# ICU is buggy. See #653. TODO: reenable it some time in the future.
cd '/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1' && OPENSSL_LIBS="`'i686-w64-mingw32.static-pkg-config' --libs-only-l openssl`" PSQL_LIBS="-lpq -lsecur32 `'i686-w64-mingw32.static-pkg-config' --libs-only-l openssl pthreads` -lws2_32" SYBASE_LIBS="-lsybdb `'i686-w64-mingw32.static-pkg-config' --libs-only-l openssl` -liconv -lws2_32" PKG_CONFIG="i686-w64-mingw32.static-pkg-config" PKG_CONFIG_SYSROOT_DIR="/" PKG_CONFIG_LIBDIR="/root/mnt/mxe/usr/i686-w64-mingw32.static/lib/pkgconfig" MAKE=make ./configure -opensource -confirm-license -xplatform win32-g++ -device-option CROSS_COMPILE=i686-w64-mingw32.static- -device-option PKG_CONFIG='i686-w64-mingw32.static-pkg-config' -pkg-config -force-pkg-config -no-use-gold-linker -release  -static -prefix '/root/mnt/mxe/usr/i686-w64-mingw32.static/qt5' -no-icu -opengl dynamic -no-glib -accessibility -nomake examples -nomake tests -plugin-sql-mysql -mysql_config /root/mnt/mxe/usr/i686-w64-mingw32.static/bin/mysql_config -plugin-sql-sqlite -plugin-sql-odbc -plugin-sql-psql -plugin-sql-tds -D Q_USE_SYBASE -system-zlib -system-libpng -system-libjpeg -system-sqlite -fontconfig -system-freetype -system-harfbuzz -system-pcre -openssl-linked -dbus-linked -no-pch -v 
Creating qmake...
make[2]: se ingresa al directorio Â«/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmakeÂ»
g++ -c -o main.o   -std=c++11 -ffunction-sections -fdata-sections -g -g  -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmake -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmake/library -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmake/generators -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/src/3rdparty/tinycbor/src -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmake/generators/unix -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmake/generators/win32 -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmake/generators/mac -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/include -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/include/QtCore -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/include/QtCore/5.15.1 -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/include/QtCore/5.15.1/QtCore -I../src/corelib/global -I/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/mkspecs/linux-g++ -DQT_VERSION_STR=\"5.15.1\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=15 -DQT_VERSION_PATCH=1 -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH /root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmake/main.cpp
In file included from ../include/QtCore/qmetatype.h:1:0,
                 from ../include/QtCore/../../src/corelib/kernel/qvariant.h:46,
                 from ../include/QtCore/qvariant.h:1,
                 from ../include/QtCore/../../src/corelib/text/qlocale.h:43,
                 from ../include/QtCore/qlocale.h:1,
                 from ../include/QtCore/../../src/corelib/serialization/qtextstream.h:46,
                 from ../include/QtCore/qtextstream.h:1,
                 from ../include/QtCore/../../src/corelib/io/qdebug.h:49,
                 from ../include/QtCore/qdebug.h:1,
                 from library/proitems.h:34,
                 from library/qmakeparser.h:34,
                 from library/qmakeevaluator.h:36,
                 from project.h:32,
                 from main.cpp:30:
../include/QtCore/../../src/corelib/kernel/qmetatype.h: In instantiation of â€˜QtMetaTypePrivate::QSequentialIterableImpl::QSequentialIterableImpl(const T*) [with T = QList<QVariant>]â€™:
../include/QtCore/../../src/corelib/kernel/qvariant.h:772:139:   required from here
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1160:135: error: ambiguous class template instantiation for â€˜struct QtMetaTypePrivate::ContainerCapabilitiesImpl<QList<QVariant>, void>â€™
       , _iteratorCapabilities(ContainerAPI<T>::IteratorCapabilities | (1 << 4) | (ContainerCapabilitiesImpl<T>::ContainerCapabilities << (4+3)))
                                                                                                                                       ^
In file included from ../include/QtCore/qmetatype.h:1:0,
                 from ../include/QtCore/../../src/corelib/kernel/qvariant.h:46,
                 from ../include/QtCore/qvariant.h:1,
                 from ../include/QtCore/../../src/corelib/text/qlocale.h:43,
                 from ../include/QtCore/qlocale.h:1,
                 from ../include/QtCore/../../src/corelib/serialization/qtextstream.h:46,
                 from ../include/QtCore/qtextstream.h:1,
                 from ../include/QtCore/../../src/corelib/io/qdebug.h:49,
                 from ../include/QtCore/qdebug.h:1,
                 from library/proitems.h:34,
                 from library/qmakeparser.h:34,
                 from library/qmakeevaluator.h:36,
                 from project.h:32,
                 from main.cpp:30:
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1007:8: error: candidates are: struct QtMetaTypePrivate::ContainerCapabilitiesImpl<Container, decltype (declval<Container>().push_back(declval<typename Container::value_type>()))>
 struct ContainerCapabilitiesImpl<Container, decltype(std::declval<Container>().push_back(std::declval<typename Container::value_type>()))>
        ^
In file included from ../include/QtCore/qmetatype.h:1:0,
                 from ../include/QtCore/../../src/corelib/kernel/qvariant.h:46,
                 from ../include/QtCore/qvariant.h:1,
                 from ../include/QtCore/../../src/corelib/text/qlocale.h:43,
                 from ../include/QtCore/qlocale.h:1,
                 from ../include/QtCore/../../src/corelib/serialization/qtextstream.h:46,
                 from ../include/QtCore/qtextstream.h:1,
                 from ../include/QtCore/../../src/corelib/io/qdebug.h:49,
                 from ../include/QtCore/qdebug.h:1,
                 from library/proitems.h:34,
                 from library/qmakeparser.h:34,
                 from library/qmakeevaluator.h:36,
                 from project.h:32,
                 from main.cpp:30:
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1025:8: error:                 struct QtMetaTypePrivate::ContainerCapabilitiesImpl<Container, void>
 struct ContainerCapabilitiesImpl<Container, QtPrivate::ContainerCapabilitiesMetaProgrammingHelper::void_t<decltype(std::declval<Container>().insert(std::declval<typename Container::value_type>())), decltype(std::declval<typename Container::value_type>() == std::declval<typename Container::value_type>())>>
        ^
In file included from ../include/QtCore/qmetatype.h:1:0,
                 from ../include/QtCore/../../src/corelib/kernel/qvariant.h:46,
                 from ../include/QtCore/qvariant.h:1,
                 from ../include/QtCore/../../src/corelib/text/qlocale.h:43,
                 from ../include/QtCore/qlocale.h:1,
                 from ../include/QtCore/../../src/corelib/serialization/qtextstream.h:46,
                 from ../include/QtCore/qtextstream.h:1,
                 from ../include/QtCore/../../src/corelib/io/qdebug.h:49,
                 from ../include/QtCore/qdebug.h:1,
                 from library/proitems.h:34,
                 from library/qmakeparser.h:34,
                 from library/qmakeevaluator.h:36,
                 from project.h:32,
                 from main.cpp:30:
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1160:135: error: incomplete type â€˜QtMetaTypePrivate::ContainerCapabilitiesImpl<QList<QVariant>, void>â€™ used in nested name specifier
       , _iteratorCapabilities(ContainerAPI<T>::IteratorCapabilities | (1 << 4) | (ContainerCapabilitiesImpl<T>::ContainerCapabilities << (4+3)))
                                                                                                                                       ^
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1169:68: error: incomplete type â€˜QtMetaTypePrivate::ContainerCapabilitiesImpl<QList<QVariant>, void>â€™ used in nested name specifier
       , _copyIter(IteratorOwner<typename T::const_iterator>::assign)
                                                                    ^
../include/QtCore/../../src/corelib/kernel/qmetatype.h: In instantiation of â€˜QtMetaTypePrivate::QSequentialIterableImpl::QSequentialIterableImpl(const T*) [with T = QStringList]â€™:
../include/QtCore/../../src/corelib/kernel/qvariant.h:775:138:   required from here
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1160:135: error: ambiguous class template instantiation for â€˜struct QtMetaTypePrivate::ContainerCapabilitiesImpl<QStringList, void>â€™
       , _iteratorCapabilities(ContainerAPI<T>::IteratorCapabilities | (1 << 4) | (ContainerCapabilitiesImpl<T>::ContainerCapabilities << (4+3)))
                                                                                                                                       ^
In file included from ../include/QtCore/qmetatype.h:1:0,
                 from ../include/QtCore/../../src/corelib/kernel/qvariant.h:46,
                 from ../include/QtCore/qvariant.h:1,
                 from ../include/QtCore/../../src/corelib/text/qlocale.h:43,
                 from ../include/QtCore/qlocale.h:1,
                 from ../include/QtCore/../../src/corelib/serialization/qtextstream.h:46,
                 from ../include/QtCore/qtextstream.h:1,
                 from ../include/QtCore/../../src/corelib/io/qdebug.h:49,
                 from ../include/QtCore/qdebug.h:1,
                 from library/proitems.h:34,
                 from library/qmakeparser.h:34,
                 from library/qmakeevaluator.h:36,
                 from project.h:32,
                 from main.cpp:30:
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1007:8: error: candidates are: struct QtMetaTypePrivate::ContainerCapabilitiesImpl<Container, decltype (declval<Container>().push_back(declval<typename Container::value_type>()))>
 struct ContainerCapabilitiesImpl<Container, decltype(std::declval<Container>().push_back(std::declval<typename Container::value_type>()))>
        ^
In file included from ../include/QtCore/qmetatype.h:1:0,
                 from ../include/QtCore/../../src/corelib/kernel/qvariant.h:46,
                 from ../include/QtCore/qvariant.h:1,
                 from ../include/QtCore/../../src/corelib/text/qlocale.h:43,
                 from ../include/QtCore/qlocale.h:1,
                 from ../include/QtCore/../../src/corelib/serialization/qtextstream.h:46,
                 from ../include/QtCore/qtextstream.h:1,
                 from ../include/QtCore/../../src/corelib/io/qdebug.h:49,
                 from ../include/QtCore/qdebug.h:1,
                 from library/proitems.h:34,
                 from library/qmakeparser.h:34,
                 from library/qmakeevaluator.h:36,
                 from project.h:32,
                 from main.cpp:30:
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1025:8: error:                 struct QtMetaTypePrivate::ContainerCapabilitiesImpl<Container, void>
 struct ContainerCapabilitiesImpl<Container, QtPrivate::ContainerCapabilitiesMetaProgrammingHelper::void_t<decltype(std::declval<Container>().insert(std::declval<typename Container::value_type>())), decltype(std::declval<typename Container::value_type>() == std::declval<typename Container::value_type>())>>
        ^
In file included from ../include/QtCore/qmetatype.h:1:0,
                 from ../include/QtCore/../../src/corelib/kernel/qvariant.h:46,
                 from ../include/QtCore/qvariant.h:1,
                 from ../include/QtCore/../../src/corelib/text/qlocale.h:43,
                 from ../include/QtCore/qlocale.h:1,
                 from ../include/QtCore/../../src/corelib/serialization/qtextstream.h:46,
                 from ../include/QtCore/qtextstream.h:1,
                 from ../include/QtCore/../../src/corelib/io/qdebug.h:49,
                 from ../include/QtCore/qdebug.h:1,
                 from library/proitems.h:34,
                 from library/qmakeparser.h:34,
                 from library/qmakeevaluator.h:36,
                 from project.h:32,
                 from main.cpp:30:
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1160:135: error: incomplete type â€˜QtMetaTypePrivate::ContainerCapabilitiesImpl<QStringList, void>â€™ used in nested name specifier
       , _iteratorCapabilities(ContainerAPI<T>::IteratorCapabilities | (1 << 4) | (ContainerCapabilitiesImpl<T>::ContainerCapabilities << (4+3)))
                                                                                                                                       ^
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1169:68: error: incomplete type â€˜QtMetaTypePrivate::ContainerCapabilitiesImpl<QStringList, void>â€™ used in nested name specifier
       , _copyIter(IteratorOwner<typename T::const_iterator>::assign)
                                                                    ^
make[2]: *** [main.o] Error 1
make[2]: se sale del directorio Â«/root/mnt/mxe/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.1/qmakeÂ»
make[1]: *** [build-only-qtbase_i686-w64-mingw32.static] Error 2
make[1]: se sale del directorio Â«/root/mnt/mxeÂ»

real	0m7.807s
user	0m5.184s
sys	0m0.796s

**Comment by jonaski** [comment]
MXE isn't using the installer. You need to share the log, otherwise it isn't possible to help.

**Comment by icolcoin** [comment]
en este link lo monte https://github.com/icolcoin/icolcoin/releases/download/Wallet/qtbase_i686-w64-mingw32.static.txt

**Comment by mabrand** [comment]
Part of the qtbase build uses the gcc of your distribution. You are using gcc 4.8.4, which is too old. 

    gcc --version
    gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4

Qt 5.15.1 requires at least gcc 5 (in ubuntu 18.04).

https://doc.qt.io/qt-5/supported-platforms.html
