### ISSUE TITLE
Ghostscript  build failing

### ISSUE THREAD

**Issue by RynoAlberts** [mxe/mxe#2571]
I'm trying to build mxe with `make MXE_TARGETS='x86_64-w64-mingw32.static' `

The build is failing when it gets to ghostscript, log file is here [Ghostscript Build Log](https://gist.github.com/RynoAlberts/6fad434e534c28c04d2af69904f64bba)

![GS-Fail](https://user-images.githubusercontent.com/20489820/96446106-dbb45900-1208-11eb-994b-a656ebbdacfc.PNG)

Any ideas to fix this?

**Comment by tonytheodore** [comment]
Fixed in https://github.com/mxe/mxe/commit/d4834fc18632e84fa90dfd130b2851be8e18d90d
