### ISSUE TITLE
libomemo 0.7.0 (with 12-byte IVs patch included)

### ISSUE THREAD

**Issue by Neustradamus** [mxe/mxe#2589]
UPDATE: There is a 0.7.0 build with 12-byte IVs patch included.

------------

Hello guys,

Can you update libomemo?

There is currently 0.6.1 instead of 0.6.2:
- https://github.com/mxe/mxe/blob/master/docs/packages.json#L226
- https://github.com/mxe/mxe/blob/master/docs/build-matrix.html#L2281

And the missing 12-byte IVs patch:
- https://github.com/gkdr/libomemo/pull/27

Explanation:
- https://github.com/gkdr/libomemo/issues/24

Thanks in advance.

**Comment by Neustradamus** [comment]
There is now a 0.7.0 with the fix:
- https://github.com/gkdr/libomemo/releases
- https://github.com/gkdr/libomemo/releases/tag/v0.7.0

**Comment by tonytheodore** [comment]
See #2597
