### ISSUE TITLE
ffmpeg snapshot

### ISSUE THREAD

**Issue by bladem2003** [mxe/mxe#2614]
how can i build the last snapshot of ffmpeg?

**Comment by tonytheodore** [comment]
First update to set _VERSION and _CHECKSUM:
```
make update-package-ffmpeg ffmpeg_UPDATE='echo snapshot'
```
Subsequent updates to change _CHECKSUM:
```
make update-checksum-ffmpeg
```

**Comment by bladem2003** [comment]
thank you.

i get this error.



[build]       ffmpeg                  i686-w64-mingw32.static

Failed to build package ffmpeg for target i686-w64-mingw32.static!
------------------------------------------------------------
                MXE_SILENT_NO_NETWORK= make ...
cd '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot'
cd '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot.build_' && '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot/configure' --cross-prefix='i686-w64-mingw32.static'- --enable-cross-compile --arch=i686 --target-os=mingw32 --prefix='/opt/mxe/usr/i686-w64-mingw32.static'  --enable-static --disable-shared  --yasmexe='i686-w64-mingw32.static-yasm' --disable-debug --disable-pthreads --enable-w32threads --disable-doc --enable-avresample --enable-gpl --enable-version3 --extra-libs='-mconsole' --enable-avisynth --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid 
bash: /opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot/configure: No such file or directory
make[1]: *** [Makefile:870: build-only-ffmpeg_i686-w64-mingw32.static] Error 127
make[1]: Leaving directory '/opt/mxe'
real    0m3.678s
user    0m2.787s
sys     0m1.375s
------------------------------------------------------------
[log]      /opt/mxe/log/ffmpeg_i686-w64-mingw32.static

make: *** [Makefile:858: /opt/mxe/usr/i686-w64-mingw32.static/installed/ffmpeg] Error 1




log
make[1]: Entering directory '/opt/mxe'
uname -a
Linux george-vmwarevirtualplatform 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
git log --pretty=tformat:"%H - %s [%ar] [%d]" -1
07692588dfe0895fc48df4fdddc02ce62262dd50 - Update packages.json & build-matrix.html [3 days ago] [ (HEAD -> master, origin/master, origin/HEAD)]
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
autoconf --version 2>/dev/null | head -1
autoconf (GNU Autoconf) 2.69
automake --version 2>/dev/null | head -1
automake (GNU automake) 1.16.2
gcc --version
gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version
g++ (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

python --version
Python 2.7.18
perl --version 2>&1 | head -3

This is perl 5, version 30, subversion 3 (v5.30.3) built for x86_64-linux-gnu-thread-multi
(with 50 registered patches, see perl -V for more detail)
rm -rf   '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static'
mkdir -p '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static'
mkdir -p '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot'
mkdir -p '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot.build_'
# disable wine with readonly directory
# see https://github.com/mxe/mxe/issues/841
mkdir -p '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/readonly'
chmod 0555 '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/readonly'
cd '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static' &&      tar xjf '/opt/mxe/pkg/ffmpeg-snapshot.tar.bz2'

Don't use network from MXE build rules!
	Silent mode for scripts reading stderr into variables:
		MXE_SILENT_NO_NETWORK= make ...

Don't use network from MXE build rules!
	Silent mode for scripts reading stderr into variables:
		MXE_SILENT_NO_NETWORK= make ...
cd '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot'
cd '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot.build_' && '/opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot/configure' --cross-prefix='i686-w64-mingw32.static'- --enable-cross-compile --arch=i686 --target-os=mingw32 --prefix='/opt/mxe/usr/i686-w64-mingw32.static'  --enable-static --disable-shared  --yasmexe='i686-w64-mingw32.static-yasm' --disable-debug --disable-pthreads --enable-w32threads --disable-doc --enable-avresample --enable-gpl --enable-version3 --extra-libs='-mconsole' --enable-avisynth --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid 
bash: /opt/mxe/tmp-ffmpeg-i686-w64-mingw32.static/ffmpeg-snapshot/configure: No such file or directory
make[1]: *** [Makefile:870: build-only-ffmpeg_i686-w64-mingw32.static] Error 127
make[1]: Leaving directory '/opt/mxe'

real	0m3.678s
user	0m2.787s
sys	0m1.375s

**Comment by tonytheodore** [comment]
Try:
```
make ffmpeg ffmpeg_SUBDIR=ffmpeg
```

**Comment by tonytheodore** [comment]
Looks like avisynth has been removed:
```
make \
    ffmpeg \
    ffmpeg_SUBDIR=ffmpeg \
    ffmpeg_CONFIGURE_OPTS='--disable-avisynth'
```

**Comment by bladem2003** [comment]
that works, thank you so much
