### ISSUE TITLE
using Qt 5.15.2

### ISSUE THREAD

**Issue by alip990** [mxe/mxe#2616]
hi 
I want to make exe of [qgroundcontrol](https://github.com/mavlink/qgroundcontrol) in ubuntu host .it needs the qt version higher than 5.11 . 
I try to use mxe and qt5-freeze plugin but those qt version's aren't higher than 5.11(qt5-freeze version is 5.7)
Is any other way to change qt version in mxe?

**Comment by bugwelle** [comment]
Hi,

if you build MXE yourself, you will get Qt 5.15.2. I think you refer to the Debian repository?

(I don't know what qt5-freeze is, so I'm just guessing) :)
