### ISSUE TITLE
Segmentation fault when building under alpine linux.

### ISSUE THREAD

**Issue by Animeshz** [mxe/mxe#2621]
Hi, I was trying to build and pack the image under the alpine linux (though worked pretty well under debian) it fails under alpine.

The following is the build script:

```bash
apk add \
    autoconf \
    automake \
    bash \
    bison \
    bzip2 \
    flex \
    g++ \
    gdk-pixbuf \
    gettext \
    gperf \
    openssl \
    git \
    binutils \
    make \
    intltool \
    libtool \
    lzip \
    openssl-dev \
    p7zip \
    patch \
    perl \
    python3 \
    ruby \
    unzip \
    wget \
    xz \
    zlib && \
ln -s /usr/bin/python3 /usr/bin/python && \
git clone https://github.com/mxe/mxe.git && \
cd mxe && \
echo "MXE_TARGETS := x86_64-w64-mingw32.shared" > settings.mk && \
echo "MXE_USE_CCACHE :="                    >> settings.mk && \
echo "MXE_PLUGIN_DIRS := plugins/gcc10"     >> settings.mk && \
echo "LOCAL_PKG_LIST := cc cmake"           >> settings.mk && \
echo ".DEFAULT local-pkg-list:"             >> settings.mk && \
echo "local-pkg-list: \$(LOCAL_PKG_LIST)"   >> settings.mk && \
make JOBS=$(nproc)
```
The build fails within build of `gcc` saying that there was a Segmentation fault after about ~15 minutes from start.

![Screenshot 2021-02-26 211226](https://user-images.githubusercontent.com/26714676/109376696-49c20880-78ec-11eb-8afb-d6a2039bfc98.png)

Unfortunately the logs were too large ~2MB so I couldn't post the full logs, but here are the most lines which are connected with the problem: https://pastecord.com/idapupimuj.sh

Did I missed something (like dependencies) or is there something wrong in gcc or mxe is not fully ready to build under alpine linux or some of the other (not-so popular) distros?

Sorry for my bad english in advance 😅.

**Comment by tonytheodore** [comment]
Possibly related question in #2479, I'll see if I can try Alpine in docker to replicate.

**Comment by tonytheodore** [comment]
Updating to [latest binutils](https://github.com/mxe/mxe/commit/e187a1adcb3d1ec3ba08ce3a12f6f58232bf6d59) fixes the gcc build, for cmake you'll have to also install the `linux-headers` package.

**Comment by Animeshz** [comment]
Oh nice! Tysm for the quick fix :)

**Comment by tonytheodore** [comment]
I've added [alpine to the docs](https://github.com/mxe/mxe/commit/fae28ef1a35f7fe3898f0751428e31ec78572f51).
