### ISSUE TITLE
cmake: missing dependency on `openssl`

### ISSUE THREAD

**Issue by lemzwerg** [mxe/mxe#2623]
[mxe 59247f916  Feb 27 2021]

I've just done
```
make download-harfbuzz download-qt5
```
followed by
```
make harfbuzz qt5
```
This fails while building 'cmake'; in the log file you can find
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (mi
CMake Error at Utilities/cmcurl/CMakeLists.txt:505 (message):
  Could not find OpenSSL.  Install an OpenSSL development package or
  configure CMake with -DCMAKE_USE_OPENSSL=OFF to build without OpenSSL.
```
And indeed, the 'libopenssl-devel' package wasn't installed on my openSUSE 15.2 box.  After installing it, the build of 'cmake' succeeded.

Is this expected?  Wouldn't it be better if the devel files for 'openssl' were part of the prerequisites?

**Comment by tonytheodore** [comment]
`libopenssl-devel` is listed in the [openSUSE requirements](https://mxe.cc/#requirements-opensuse)

**Comment by lemzwerg** [comment]
Ah, perfect, thanks!  My mistake then.  Closing.
