### ISSUE TITLE
libgcrypt-i686-w64-mingw32.static libgcrypt-1.9.2 build error under WSL

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2633]
/mxe/tmp-libgpg_error-i686-w64-mingw32.static/libgpg-error-1.42.build_/src/../../libgpg-error-1.42/src/logging.c:458: undefined reference to `_imp__closesocket@4'

/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.5.0/../../../../i686-w64-mingw32.static/lib/../lib/libgpg-error.a(libgpg_error_la-logging.o): In function `writen':

/mxe/tmp-libgpg_error-i686-w64-mingw32.static/libgpg-error-1.42.build_/src/../../libgpg-error-1.42/src/logging.c:169: undefined reference to `_imp__send@16'

/mxe/usr/lib/gcc/i686-w64-mingw32.static/5.5.0/../../../../i686-w64-mingw32.static/lib/../lib/libgpg-error.a(libgpg_error_la-logging.o): In function `fun_writer':

/mxe/tmp-libgpg_error-i686-w64-mingw32.static/libgpg-error-1.42.build_/src/../../libgpg-error-1.42/src/logging.c:443: undefined reference to `_imp__closesocket@4'

/mxe/tmp-libgpg_error-i686-w64-mingw32.static/libgpg-error-1.42.build_/src/../../libgpg-error-1.42/src/logging.c:342: undefined reference to `_imp__htons@4'

/mxe/tmp-libgpg_error-i686-w64-mingw32.static/libgpg-error-1.42.build_/src/../../libgpg-error-1.42/src/logging.c:361: undefined reference to `_imp__inet_addr@4'

/mxe/tmp-libgpg_error-i686-w64-mingw32.static/libgpg-error-1.42.build_/src/../../libgpg-error-1.42/src/logging.c:370: undefined reference to `_imp__socket@12'

/mxe/tmp-libgpg_error-i686-w64-mingw32.static/libgpg-error-1.42.build_/src/../../libgpg-error-1.42/src/logging.c:381: undefined reference to `_imp__connect@12'

/mxe/tmp-libgpg_error-i686-w64-mingw32.static/libgpg-error-1.42.build_/src/../../libgpg-error-1.42/src/logging.c:387: undefined reference to `_imp__closesocket@4'

**Comment by jonaski** [comment]
Add: `-lws2_32`

**Comment by Jan200101** [comment]
error is also present outside of WSL and is fixed by the same PR
