### ISSUE TITLE
luajit-i686-w64-mingw32.static LuaJIT-2.0.5 build error under WSL

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2634]
host/minilua ../dynasm/dynasm.lua   -D JIT -D FFI -D FPU -D HFABI -D VER= -D WIN -o host/buildvm_arch.h vm_x86.dasc
host/minilua: 1: Syntax error: Unterminated quoted string
make[3]: *** [Makefile:610: host/buildvm_arch.h] Error 2

**Comment by tonytheodore** [comment]
It's most likely [WSL1 which doesn't support 32bit execution](https://mxe.cc/#requirements-wsl) and the docs haven't yet been updated.

Try:
```
make EXCLUDE_PKGS='ocaml% luajit' ...
```
