### ISSUE TITLE
gettext build (configure) failure --- patch (pull request) available

### ISSUE THREAD

**Issue by janvdijk** [mxe/mxe#2639]
Buiilding gettext (win64, shared) fails with a vanilla git HEAD in the configure stage, the build log says
```
configure.ac:25: installing '../build-aux/missing'
configure.ac:25: error: AC_INIT should be called with package and version arguments
: gl_AM_INIT_AUTOMAKE is expanded from...
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:25: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
```
A quick google search reveals that this is a known issue. I confirmed that this is fixed by a patch that is available upstream, see https://savannah.gnu.org/bugs/?59929. For more details I refer to pull request #2632 that adds this patch to mxe-gettext.

**Comment by tonytheodore** [comment]
Fixed in https://github.com/mxe/mxe/commit/9cae21c297a836aea6e80037238fbdb097ba4e74
