### ISSUE TITLE
cmake wrapper doesn't work reliably with -E option when used in qtcreator

### ISSUE THREAD

**Issue by oe1rsa** [mxe/mxe#2641]
Using the mxe cmake wrapper from qtcreator interferes with the json parser of qtcreator, since the output of
``cmake -E capabilities``
no longer is a valid json string.
Similar issues may arise with other uses of -E flag since the usual output will be altered.
I suggest not to echo any added messages when NO_MXE_TOOLCHAN is set to 1.

**Comment by tonytheodore** [comment]
Nice suggestion - thanks.
