### ISSUE TITLE
unable to build MXE on macos host

### ISSUE THREAD

**Issue by markghayden** [mxe/mxe#2649]
On MacOS host, python-markupsafe and gcc fail to build.  Log files attached.  Please let me know if any further information is needed.

[gcc_x86_64-w64-mingw32.shared.log](https://github.com/mxe/mxe/files/6449353/gcc_x86_64-w64-mingw32.shared.log)
[python-markupsafe_x86_64-apple-darwin20.4.0.log](https://github.com/mxe/mxe/files/6449354/python-markupsafe_x86_64-apple-darwin20.4.0.log)

**Comment by tonytheodore** [comment]
There's nothing obvious in the gcc log, but python-markupsafe has this suspicious path:
```
-L/System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.Internal.sdk/usr/local/libressl/lib
```
Can you figure out where that comes from? It looks like some Xcode build artefact that's getting picked up somehow.

You can try:
```
make gmsl-print-ENV_WHITELIST
```
to get a list of env vars we allow and see if it's in any of those.

**Comment by markghayden** [comment]
> On May 10, 2021, at 5:38 AM, Tony Theodore ***@***.***> wrote:
> 
> 
> There's nothing obvious in the gcc log, but python-markupsafe has this suspicious path:
> 
> 

Hi Tony,

Thanks for the quick response.

I thought the gcc issue might have been caused by these errors in the log.

/Users/mhayden/plotter/proj/mxe/version/5.15.2.fresh/mxe/tmp-gcc-x86_64-w64-mingw32.shared/gcc-5.5.0/libcpp/lex.c:1505:3: error: must use 'enum' tag to refer to type 'raw_str_phase'
  raw_str_phase phase = RAW_STR_PREFIX;
  ^
  enum 


/Users/mhayden/plotter/proj/mxe/version/5.15.2.fresh/mxe/tmp-gcc-x86_64-w64-mingw32.shared/gcc-5.5.0/libcpp/macro.c:456:13: error: must use 'struct' tag to refer to type 'line_map'
      const line_map * map =
            ^
            struct 


> -L/System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.Internal.sdk/usr/local/libressl/lib
> Can you figure out where that comes from? It looks like some Xcode build artefact that's getting picked up somehow.
> 
> You can try:
> 
> make gmsl-print-ENV_WHITELIST
> to get a list of env vars we allow and see if it's in any of those.
> 
> 

Below is the result of the make statement you give above, as well as ‘printenv’ in my tcsh shell.  I don’t see a reference to the path you are concerned about.  

sakhalin% make gmsl-print-ENV_WHITELIST
[warning]     **gettext-0.20.1**
ENV_WHITELIST = EDITOR HOME LANG LC_% PATH %PROXY %proxy PS1 TERM MAKE% MXE% LD_PRELOAD DYLD_FORCE_FLAT_NAMESPACE DYLD_INSERT_LIBRARIES WINEPREFIX ACLOCAL_PATH LD_LIBRARY_PATH
sakhalin% printenv
PWD=/Users/mhayden/plotter/proj/mxe/version/5.15.2.fresh/mxe
DISPLAY=/private/tmp/com.apple.launchd.pYQltf7tY2/org.xquartz:0
TERM=dumb
TERMCAP=
COLUMNS=179
INSIDE_EMACS=27.1,comint
ANDROID_HOME=/Users/mhayden/Library/Android/sdk
AXISHOME=/home/mhayden/vmware/axis-1_2_1
VNI_LICENSE_DISABLE=
VALGRIND_OPTS=--num-callers=12
LHN_LEVEL=P112
CVS_SERVER=/usr/local/bin/cvs
CVS_RSH=ssh
SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass
NF_BANNER_DISABLE=X
PKG_PATH=ftp://ftp.netbsd.org/pub/NetBSD/packages/1.6.2/i386/All
GS_FONTPATH=
KDEDIR=/opt/kde
WWWHOMEDIR=/home/hayden/www/localinstall
MAILCAPS=/Users/mhayden/.mailcap:/usr/local/etc/mailcap:/usr/etc/mailcap:/etc/mailcap:/etc/mail/mailcap:/usr/public/lib/mailcap
PURIFYOPTIONS=-cache-dir=/usr/u/hayden/.purify_cache -best-effort
CVSEDITOR=emacs -nw
CVSROOT=/Users/mhayden/cvs
ENS_PATH=/Users/mhayden/hayden/ensemble
CPU=Darwin
ELECTRA_HOME=/Users/mhayden/electra
CLASSPATH=.:/Users/mhayden/proj:/usr/java/jdk1.3.1_04/jre/lib/rt.jar:/usr/java/jre1.3.1/lib/rt.jar:/Users/mhayden/java/kiwi.jar
IFC_HOME=/usr/local/pkg/ifc111
MOZILLA_HOME=/usr/local/lib/netscape
NETSCAPE_HOME=/usr/local/lib/netscape
PRINTER=lp
KERNEL_INCLUDE=-I/home/mhayden/proj/linux/include
CENSEMBLE_ADDL_WARNINGS_HARDCORE=-Wunused -Wundef -Wmissing-declarations
CENSEMBLE_ADDL_WARNINGS=-Wall -Wwrite-strings -Wstrict-prototypes -Werror
NF_BUILD_ADDL=dbd_test dbd_store_journal_test dbd_global_test dbd_store_test dbd_ctrl rpc_test tpc_test tpc_log_test dlm_test
CENS_ROOT=/home/mhayden/censemble
ENS_LIB_DIR=/Users/mhayden/ensemble/def/obj/x86_64-darwin
ENS_OUTBOARD=/Users/mhayden/ensemble/demo/outboard
ENS_OPTIONAL=socket
ENS_LOG_PORT=6754
ENS_LOG_HOST=gulag
ENS_PROTOS_HOSTS=rostov:asolz:sakhalin
ENS_PROTOS_PORT=6898
ENS_GROUPD_HOSTS=rostov:asolz:sakhalin
ENS_GROUPD_PORT=6897
ENS_GOSSIP_HOSTS=rostov:asolz:sakhalin
ENS_GOSSIP_PORT=6890
ENS_MODES=DEERING
ENS_DEERING_PORT=6885
ENS_ID=mhayden
ENS_LIBDIR=/home/mhayden/ensemble/def/obj/x86_64-darwin
ENSROOT=/home/mhayden/ensemble
ECAMLCHACK=hayden
SHORTHOST=sakhalin
XTERM_SHELL=/bin/tcsh
XTERM_LOCALE=C
XTERM_VERSION=XTerm(363)
WINDOWID=23068684
_=/usr/X11R6/bin/xterm
X11_PREFS_DOMAIN=org.xquartz.X11
LOGNAME=mhayden
MACHTYPE=x86_64
VENDOR=apple
OSTYPE=darwin
SHLVL=4
HOME=/Users/mhayden
XPC_SERVICE_NAME=0
XPC_FLAGS=0x0
EDITOR=vi
__CFBundleIdentifier=org.xquartz.X11
FACEPATH=/udir/hayden/lib/faces:/proj/generic/lib/facedir
PATH=/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/mhayden/plotter/proj/mxe/version/5.10.1/mxe/usr/bin:/opt/local/bin:/opt/local/sbin:/Users/mhayden/bin:/usr/local/bin:/Users/mhayden/bin:/usr/bin:/Developer/usr/bin:/bin:/usr/local/Acrobat3/bin:/usr/local/bin:/usr/local/sbin:/usr/games:/usr/bin/X11:/usr/X11R6/bin:/usr/X11/bin:.:/usr/sbin:/sbin:/Users/mhayden/plotter/proj/android/ndk-standalone-16/bin:/Users/mhayden/plotter/proj/android/ndk-standalone-arm64-21/bin
PAGER=less
__CF_USER_TEXT_ENCODING=0x1F8:0x0:0x0
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.wRf58QeuSw/Listeners
HOSTTYPE=amd
COMMAND_MODE=unix2003
CALENDAR=/Users/mhayden/doc/ical-calendar
USER=mhayden
GROUP=staff
SVN_EDITOR=emacs -nw
ENSCRIPT=-2rG
TMPDIR=/var/folders/_y/hs32vk6j43b4v_t1qjmh0dzc0000gr/T/
PGPPATH=/Users/mhayden/.pgp
SHELL=/bin/tcsh
HOST=sakhalin
LD_LIBRARY_PATH=/Users/mhayden/Library/Android/sdk/tools/lib64

The log for the python-markupsafe seemed to indicate a problem finding a download:

creating 'dist/MarkupSafe-1.1.1-py2.7-macosx-11.3-x86_64.egg' and adding 'build/bdist.macosx-11.3-x86_64/egg' to it
removing 'build/bdist.macosx-11.3-x86_64/egg' (and everything under it)
Processing MarkupSafe-1.1.1-py2.7-macosx-11.3-x86_64.egg
Removing /Users/mhayden/plotter/proj/mxe/version/5.15.2.fresh/mxe/usr/x86_64-apple-darwin20.4.0/lib/python2.7/site-packages/MarkupSafe-1.1.1-py2.7-macosx-11.3-x86_64.egg
Copying MarkupSafe-1.1.1-py2.7-macosx-11.3-x86_64.egg to /Users/mhayden/plotter/proj/mxe/version/5.15.2.fresh/mxe/usr/x86_64-apple-darwin20.4.0/lib/python2.7/site-packages
MarkupSafe 1.1.1 is already the active version in easy-install.pth

Installed /Users/mhayden/plotter/proj/mxe/version/5.15.2.fresh/mxe/usr/x86_64-apple-darwin20.4.0/lib/python2.7/site-packages/MarkupSafe-1.1.1-py2.7-macosx-11.3-x86_64.egg
Processing dependencies for MarkupSafe==1.1.1
Searching for MarkupSafe==1.1.1
Reading https://pypi.org/simple/MarkupSafe/
Download error on https://pypi.org/simple/MarkupSafe/: [Errno 60] Operation timed out -- Some packages may not be found!
Couldn't find index page for 'MarkupSafe' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno 60] Operation timed out -- Some packages may not be found!
No local packages or working download links found for MarkupSafe==1.1.1
error: Could not find suitable distribution for Requirement.parse('MarkupSafe==1.1.1')
make[1]: *** [build-only-python-markupsafe_x86_64-apple-darwin20.4.0] Error 1


best, Mark

**Comment by osum4est** [comment]
Are there any updates on this? I have the exact same issue

**Comment by markghayden** [comment]
There are no updates on this.  As far as I can tell the MacOS MXE build has been broken for a long time.

**Comment by markghayden** [comment]
I updated to a new M1 Macbook and suddenly MXE builds started working.  My suspicion is that there was something about my installation preventing the MXE build from working.
