### ISSUE TITLE
Building cc with alternative exception implementation docs could be better

### ISSUE THREAD

**Issue by mosolovsa** [mxe/mxe#2663]
It's not so obvious how building GCC with dwarf exceptions (mentioned in the readme.md) could be achieved.

After expecting Makefile looks like this does what I want:
`make cc GCC_EXCEPTIONS=dw2`

However, I didn't found any info on that neither in the repo readme.md, nor mxe.cc website.
I could send a PR to readme.md, with some guidance I think I can document other options (Threading model? Any others?)

**Comment by aquiles2k** [comment]
Well i don't know if we are talking about the same thing but the readme clearly talks about the toolchains.

So depending on what you want you'll have to use

* i686-w64-mingw32.static.dw2
* i686-w64-mingw32.shared.dw2
etc.

Just add it as MXE_TARGET in your settings.mk

e.g. `echo "MXE_TARGETS := i686-w64-mingw32.shared.dw2" >> settings.mk`

**Comment by mosolovsa** [comment]
Thanks for the clarification! Misunderstood that.
