### ISSUE TITLE
[patch] fix VTK dll import/export for gcc11

### ISSUE THREAD

**Issue by janvdijk** [mxe/mxe#2675]
This bug report is accompanied by pull request #2674 

When compiling VTK with the gcc11 plugin, I encountered a number of errors, related to importing/exporting symbols from `vtkInformation.h` (numerous 'error: function definition XXX is marked dllimport' related to (only) code in `vtkInformation.h`). For example:

```
In file included from ../../../VTK-8.2.0/Common/DataModel/vtkHierarchicalBoxDataSet.cxx:16:
../../../VTK-8.2.0/Common/Core/vtkInformation.h:512:24: error: function 'vtkInformation::vtkInformation(const vtkInformation&)' definition is marked dllimport
  512 |   VTKCOMMONCORE_EXPORT vtkInformation(const vtkInformation&) = delete;
```

A patch that is consistent with one that has been merged in the upstream VTK git repo fixes this problem, and is the subject of this pull request. See the commit log for details.

I am too much an MSW-novice to understand why this problem manifests itself with the gcc11 plugin, but not with the stock gcc or the gcc10 plugin. I checked that the modified sources compile fine with all gcc versions that are offered by MXE (shared builds).

**Comment by janvdijk** [comment]
@tonytheodore since you added the gcc11 plugin (thanks!), would you mind to take a look at this report and the associated pull request? Is there anything else I can do to help resolve this issue? Thank you very much.

**Comment by mabrand** [comment]
merged
