### ISSUE TITLE
update Qt 5.15 LTS using KDE patch compilation repository

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2685]
Hi MXE team,

with the digiKam AppImage bundling, i started to use the KDE compilation patch repository in place of Qt 5.15.2 opensource, which is the last one tarball official published by Qt team for the open source community.

I will no to rewrite here the story, as all the details can be found here: 

https://linuxreviews.org/KDE_Is_Now_Offering_A_Qt_5.15_LTS_Branch_Patch-set_For_The_Free_Software_Community

The details about the git repository is given here:

https://community.kde.org/Qt5PatchCollection

Typically, you must considerate this compilation patches at least for the security issues fixed.

The git repository is here:

https://invent.kde.org/qt/qt/qt5/-/tree/kde/5.15

Note the branch to use is "kde/5.15" for the root repo and all the submodules.

Under My Linux AppImage compilation workflow, the code compile fine. See the rules in my cmake and bash code here: 

https://invent.kde.org/graphics/digikam/-/tree/master/project/bundles/3rdparty/ext_qt/5.15-LTS

Best regards

Gilles Caulier

**Comment by cgilles** [comment]
Hi,

In digiKam project i used successfully this KDE Qt5 LTS compilation patches repository to compile the official Linux AppImage bundle. This allow to fix plenty of bugs in application due to UPSTREAM Qt bugs (as for ex. a compatibility with Mariadb >= 10.6 with Qt Mysql plugin).

The bug for digiKam relevant of this improvement is this one :

​https://bugs.kde.org/show_bug.cgi?id=114417

The script used to checkout the KDE repository with AppImage Bundle compilation is here :

​https://invent.kde.org/graphics/digikam/-/blob/master/project/bundles/3rdparty/ext_qt/5.15-LTS/kde-qt5-lts.sh

I highly recommend to use the KDE qt 5.15 LTS repository to maintain the qt5 port in MXE.

Best 

Gilles Caulier

Note : In digiKam AppImage bundle, the Qt5 version reported by the library is 5.15.3 as you can see in this screenshot: 

https://i.imgur.com/R7o2xoj.png

**Comment by mabrand** [comment]
I'm thinking about just using all the kde/5.15 patches for qtbase. What do you think about that?

**Comment by cgilles** [comment]
Well, it can be a first step, but to be honest i don't know the side effects to mix "qtbase 5.15.3" with all the rest in 5.15.2.

Also i seen that the .git directories are required to compile. Sound like a dependencies is written somewhere to adjust all components together.

In fact with my bash script, you take a total copy of a snapshot for complete "Qt5.15.3" tarball as rolling release.

Note: I create a MANIFEST.txt file including all git revisions for each qt components. Like this we know exactly the right version of qt code is compiled. To know if a patch is included inside, just consult the git log available online. I think this point is very important for a client application, to know if a qt bug is present or no.

**Comment by cgilles** [comment]
Hi,

Good news. Qt 5.15.3 have been just released in open source, one year later 5.15.2.

https://lists.qt-project.org/pipermail/development/2022-March/042262.html

Note: the current Qt5 release is 5.15.8, only available for Qt company customer. The Qt patch compilation from KDE project will continue to provide a LTS solution with most recent and important fixes for the LTS support.

Best

Gilles Caulier
