### ISSUE TITLE
gdal compile error under ubuntu 20.4

### ISSUE THREAD

**Issue by dbyoung720** [mxe/mxe#2691]
Failed to build package gdal for target i686-w64-mingw32.static!
------------------------------------------------------------
 libs="-L/home/dbyoung/Desktop/mxe/usr/i686-w64-mingw32.static/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lpthread -lz -lm -lcurl", includedir="/home/dbyoung/Desktop/mxe/usr/i686-w64-mingw32.static/include"
checking for nc_open in -lnetcdf... no
configure: JasPer (JPEG2000) support disabled.
configure: error: openjpeg.h not found in /home/dbyoung/Desktop/mxe/usr/i686-w64-mingw32.static/include/openjpeg-2.0 or /home/dbyoung/Desktop/mxe/usr/i686-w64-mingw32.static/include/openjpeg-2.1 or /home/dbyoung/Desktop/mxe/usr/i686-w64-mingw32.static/include/openjpeg-2.2 or /home/dbyoung/Desktop/mxe/usr/i686-w64-mingw32.static/include/openjpeg-2.3
make[1]: *** [Makefile:874: build-only-gdal_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory '/home/dbyoung/Desktop/mxe'

**Comment by mabrand** [comment]
Should be fixed by eb7df8f39184da38c47c69e9345f7bf091e165c1 and c2cdd3a06bf9b0e596974d70b241c06889ba16f8.
