### ISSUE TITLE
C++20 is unsupported?

### ISSUE THREAD

**Issue by danger89** [mxe/mxe#2703]
I'm trying to build my C++ code (using C++ 20 standard) using `x86_64-w64-mingw32.static-cmake`.

For some reason `x86_64-w64-mingw32.static-c++` or `x86_64-w64-mingw32.static-g++` are unable to build C++ 20 code??  ;(

```sh
-- Configuring done
CMake Error in src/CMakeLists.txt:
  Target "my-secret-target" requires the language dialect "CXX20" , but CMake
  does not know the compile flags to use to enable it.
```

Regards,
Melroy

**Comment by jonaski** [comment]
Use a newer GCC version from the plugins dir.

**Comment by danger89** [comment]
I'm actually using the prebuild packages. Please, I hope there is just an easy way to get a newer gcc version from https://pkg.mxe.cc/repos/apt/ ?

**Comment by danger89** [comment]
Brain-fart; maybe I can try to use the mingw compiler (eg . `/usr/bin/x86_64-w64-mingw32-gcc`) from my distribution as a drop-in replacement of `/usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-gcc` in the meanwhile..

**Comment by danger89** [comment]
Is it true you are using the win32 API instead of the Posix for MXE packaged compilers? Since that is a bit unclear for me. I do need Posix implementation due to threading in my C++ code.
