### ISSUE TITLE
Make GCC 11 the default

### ISSUE THREAD

**Issue by danger89** [mxe/mxe#2705]
Currently the Debian packages you are providing are coming with gcc/g++ compiler v5.5, which is very outdated. So out-dated I can't even compile some C++20 code, related: #2703. Like std::filesystem.

Anyway, that is why I think MXE should bring ~~GCC9 or GCC10~~ GCC11 as the [default gcc/g++ compiler package](https://pkg.mxe.cc/repos/apt/dists/). So people do not manually need to compile the whole Qt or GTK libraries manually using the [plugins](https://github.com/mxe/mxe/tree/master/plugins/gcc10) on their computer to just (cross-)compile their C++20 project.

Thank you for understanding! 

Regards,
Melroy van den berg

**Comment by danger89** [comment]
Maybe even GCC11 should be the default. I don't care, just update it!

**Comment by mabrand** [comment]
I agree. Making gcc11 the default compiler will do more good than harm. Would you be willing to make a pull request that creates a plugin for gcc5 and upgrades the default gcc to 11?

**Comment by danger89** [comment]
Sure. I will!

**Comment by danger89** [comment]
@mabrand What should I do with those extra compiler flags:

```
libssh_EXTRA_WARNINGS = -Wno-error=implicit-fallthrough
gtkimageview_EXTRA_WARNINGS = -Wno-error=misleading-indentation
guile_EXTRA_WARNINGS = -Wno-error=misleading-indentation
gtkmm2_EXTRA_WARNINGS = -Wno-error=cast-function-type
gtkmm3_EXTRA_WARNINGS = -Wno-error=cast-function-type
gtkglextmm_EXTRA_WARNINGS = -Wno-error=cast-function-type
```

I noticed that other gccx-overlay.mk files in the plugins directory have this at the bottom each file.

**Comment by mabrand** [comment]
Those are to suppress known errors building certain packages with the newer (usually stricter) gcc. Use 'git grep EXTRA_WARNINGS' to see where and how they are used.
One idea is just to add the needed -Wno-error options in the .mk files that need them. I'm not sure if they would break builds with older gcc versions, which we wouldn't want. Maybe you have a good idea?

**Comment by danger89** [comment]
<-- Well you noticed my PR I think.

In my other branch I'm upgrading the whole GTK stack. So those suppression options are maybe not needed anymore in the future (for **Gtkmm** at least):

https://github.com/danger89/mxe/pull/1

**Comment by danger89** [comment]
Very nice indeed!

**Comment by fiesh** [comment]
It seems to me this has now moved the same problem to a few years from now, when GCC 11 is horribly outdated and MXE should make its GCC 17 plugin the default.

In the absence of another policy for MXE's packages, shouldn't the latest stable GCC (or any other package really) always be the default and anything else a plugin?

If updating GCC leads to a package breaking, I think the responsibility should also be inverted and it should be the package's job to fix its issues, for it's almost always an issue with the package and not with GCC.  The same holds true for other packages as well, boost comes to mind.
