### ISSUE TITLE
Out-dated GTK/GTKMM (+Introducing Meson builds to MXE)

### ISSUE THREAD

**Issue by danger89** [mxe/mxe#2706]
The GTK & GTKMM version that are being used and build in MXE are very out-dated. And does not even contain the [GtkModelButton](https://docs.gtk.org/gtk3/class.ModelButton.html) (modelbutton.h). I need an up to date GTK3 version to cross-compile my own GTK3 app, [LibreWeb](https://gitlab.melroy.org/libreweb/browser/-/issues/25).

I think it's wise to update mk files. Like version `3.24.5` for [Gtkmm](https://download.gnome.org/sources/gtkmm/3.24/) and `3.24.30` [GTK3/+](https://download.gnome.org/sources/gtk+/3.24/). Please?

I'm also trying to upgrade pango(mm), cairo(mm) as well as glib(mm). Let's see about those patch files etc. etc.. ..

**Update:** `atk-1-DllMain.patch` is not needed anymore, if we upgrade to atk-2.36.0 that is... 

**UPDATE 2:** However,...  newer versions of ATK/ATKMM/Glib/.. (most likely more), switch from `./configure` autotools to meson builds.. Do you allow meson builds?? For now the only package I really need to upgrade to a newer version that only supports meson builds are ATK. So Let's try to build atk first via meson, let's see about the remaining GTK dependencies packages.

```sh
-- Checking for module 'gtkmm-3.0'
--   Found gtkmm-3.0, version 3.14.0
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0017
    CMAKE_POLICY_DEFAULT_CMP0020

-- Build files have been written to: /media/melroy/Data/Projects/browser/build_prod_win
[38/55] Building CXX object src/CMakeFiles/libreweb-browser.dir/main.cc.obj
FAILED: src/CMakeFiles/libreweb-browser.dir/main.cc.obj 
/opt/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static.posix-g++ -DEPOXY_STATIC -DPCRE_STATIC -Isrc -I../src -Ilib/commonmarker/src -Ilib/commonmarker/extensions -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/gtkmm-3.0 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/lib/gtkmm-3.0/include -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/atkmm-1.6 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/gdkmm-3.0 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/lib/gdkmm-3.0/include -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/giomm-2.4 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/lib/giomm-2.4/include -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/pangomm-1.4 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/lib/pangomm-1.4/include -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/glibmm-2.4 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/lib/glibmm-2.4/include -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/gtk-3.0 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/harfbuzz -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/pango-1.0 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/atk-1.0 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/cairomm-1.0 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/lib/cairomm-1.0/include -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/cairo -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/pixman-1 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/freetype2 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/sigc++-2.0 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/lib/sigc++-2.0/include -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/gdk-pixbuf-2.0 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/glib-2.0 -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/lib/glib-2.0/include -I/opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/libpng16 -I../lib/commonmarker/src -I../lib/commonmarker/extensions -I../lib/ipfs-http-client/include -I_deps/json-src/include -I../lib/whereami -Wall -Wextra -O3 -DNDEBUG -O3 -DNDEBUG   -mms-bitfields -std=c++2a -MD -MT src/CMakeFiles/libreweb-browser.dir/main.cc.obj -MF src/CMakeFiles/libreweb-browser.dir/main.cc.obj.d -o src/CMakeFiles/libreweb-browser.dir/main.cc.obj -c ../src/main.cc
In file included from ../src/main.cc:1:
../src/mainwindow.h:20:10: fatal error: gtkmm/modelbutton.h: No such file or directory
   20 | #include <gtkmm/modelbutton.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
```

Regards,
Melroy

**Comment by danger89** [comment]
Again, just to highlight. Meson builds are required. For example `atk` v2.32.0 which is required by `gtk` v3.24 can only be build via Meson.

See also: https://wiki.gnome.org/Initiatives/GnomeGoals/MesonPorting

And: https://mesonbuild.com/Porting-from-autotools.html

Meaning we need to also change the `MXE_CONFIGURE_OPTS` to make it work in Meson. Please I could use some help from a person who is an expert in MXE. I already started in this branch: https://github.com/danger89/mxe/tree/update_gtk

**Comment by v1993** [comment]
I'd like to say that I'm very interested in this. Composite templates are pretty much a must in Vala GUI apps and they require at least GTK 3.24 to work. Programs compile successfully, but ultimately fail to show interface when executed.

> And: mesonbuild.com/Porting-from-autotools.html

This is not an autotools project, it's custom makefile collection.

This actually makes it a lot *easier*, since all makefiles do (case in point, https://github.com/mxe/mxe/blob/master/src/gtk3.mk) is calling package's own build routines. This means that all you need to do is to replace those `/configure` and `$(MAKE)` calls with corresponding `meson` and `ninja` for relevant projects (and make MXE depend on meson/ninja, which only have to be done once).

**Comment by danger89** [comment]
I know. Did you check my work in progress branch on my account?

https://github.com/danger89/mxe/tree/update_gtk

It's not as easy as you think. Since it'd not just gtk that needs to be updated. Gtk is depended on a whole lot of packages which also required to be updated as well!!

**Comment by danger89** [comment]
> This means that all you need to do is to replace those `/configure` and `$(MAKE)` calls with corresponding `meson` and `ninja` for relevant project

Hehe, it's always a bit more difficult than you initially think. 😄 But we are getting there!

**Comment by danger89** [comment]
Heads-up the `update_gtk` branch is almost ready for a PR/to be merged: https://github.com/danger89/mxe/tree/update_gtk

**Comment by danger89** [comment]
PR ready to be merged: https://github.com/mxe/mxe/pull/2788

**Comment by melroy89** [comment]
Now it's 2026 and people also look forward for support of gtk4 as well now.
