### ISSUE TITLE
building issue(i have assimp )

### ISSUE THREAD

**Issue by 4k1v** [mxe/mxe#2735]
make[5]: *** [Makefile:2484: .obj/ZipArchiveIOSystem.o] Error 1
make[5]: Leaving directory '/home/user/git/qt-everywhere-src-5.15.2/qtquick3d/src/plugins/assetimporters/assimp'
make[4]: *** [Makefile:85: sub-assimp-install_subtargets] Error 2
make[4]: Leaving directory '/home/user/git/qt-everywhere-src-5.15.2/qtquick3d/src/plugins/assetimporters'
make[3]: *** [Makefile:59: sub-assetimporters-install_subtargets] Error 2
make[3]: Leaving directory '/home/user/git/qt-everywhere-src-5.15.2/qtquick3d/src/plugins'
make[2]: *** [Makefile:206: sub-plugins-install_subtargets-ordered] Error 2
make[2]: Leaving directory '/home/user/git/qt-everywhere-src-5.15.2/qtquick3d/src'
make[1]: *** [Makefile:62: sub-src-install_subtargets] Error 2
make[1]: Leaving directory '/home/user/git/qt-everywhere-src-5.15.2/qtquick3d'
make: *** [Makefile:377: module-qtquick3d-install_subtargets] Error 2

**Comment by MarcoBorrini99** [comment]
Some more detail? The full log at least?

**Comment by 4k1v** [comment]
https://lfs.koddos.net/blfs/view/stable/x/qt5.html  i have used this guide ( i use gentoo multilib); and make install(with root) returned this lo
[log.txt](https://github.com/mxe/mxe/files/7714527/log.txt)
g

**Comment by MarcoBorrini99** [comment]
> https://lfs.koddos.net/blfs/view/stable/x/qt5.html i have used this guide ( i use gentoo multilib); and make install(with root) returned this lo [log.txt](https://github.com/mxe/mxe/files/7714527/log.txt) g

I think you've written to the wrong mailing list. MXE has nothing to share with (B)LFS.... you're comparing apples (cross compile to windows) with oranges (build a complete os from scratch)

**Comment by 4k1v** [comment]
ok
