### ISSUE TITLE
poppler 21.12.0 fails to build

### ISSUE THREAD

**Issue by stloeffler** [mxe/mxe#2746]
As noted in the comments of 392f620 (the commit that updated the poppler package from 21.06.1 to 21.12.0), poppler requires C++17 support from 21.12.0 on (as documented in the [release notes](https://poppler.freedesktop.org/releases.html)). The default GCC 5.5.0 doesn't seem to include this support (fully).
As poppler is not likely to revert to C++11, and other packages are likely to follow the same path (adopting newer C++ standards as time passes), this is a relatively fundamental issue for which I can think of three possible solutions off the top of my head:
* freeze this package (and presumably others in the future) to the last buildable version (presumably poppler 21.11.0 in the present case, though I haven't tested this)
* update gcc (as suggested in the comments of 392f620)
* provide several versions of a package and a mechanism to dynamically choose which one to build based on, e.g., the selected plugins

FWIW, here's the [full log of the failed build](https://gist.github.com/stloeffler/c05353b8f4adec92c173f6c9ef9f68ef)

**Comment by mabrand** [comment]
Also see comments https://github.com/mxe/mxe/commit/d6189ff60d9096326a567963318fe0ef50eab6c0#commitcomment-63089393. Harfbuzz also requires an up-to-date gcc.

**Comment by stloeffler** [comment]
For reference, other issues related to this: #1205, #2629, #2705

**Comment by Fijxu** [comment]
I have the same problem, I need a major version of GCC because the program I need to build needs c++17
+1

**Comment by mabrand** [comment]
341e0bcc0d06f1f134a5a32a9d073d4c007e903c should fix this
