### ISSUE TITLE
Upgrade libgphoto2 from 2.5.27 to 2.5.28 

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2756]
Hi all,

digiKam use now under Windows the libgphoto2 shared library to support Gphoto2 camera devices.

Currently, the libgphoto2 in MXE is the 2.5.27.

Under MacOS, digiKam using 2.5.27 do not list the camera drivers. Just upgrading libgphoto2 to 2.5.28 fix the problem:

digiKam under MacOS with libgphoto2 2.5.27 : https://i.imgur.com/JG5hV7g.png
digiKam under MacOS with libgphoto2 2.5.28 : https://i.imgur.com/elfzIcG.png

Under Windows using libgphoto2 2.5.27, we have exactly the same problem than under MacOS. The list of camera driver is empty:

https://i.imgur.com/vVLZFDf.png

So i suspect a bug fixed in libgphoto2. 

Please, can you upgrade libgphoto2 to last stable 2.5.28:

https://github.com/gphoto/libgphoto2/releases/tag/v2.5.28

Thanks in advance

Gilles Caulier

**Comment by mabrand** [comment]
A tested pull request would be welcome!

**Comment by cgilles** [comment]
Just for info, i also tested the libgphoto2 commit in MXE for the libusb detection. I

https://github.com/mxe/mxe/commit/5e2f623d08b02cc4604a68dfa75df4b0d79b789b

upgraded MXE, recompiled the Windows installer, but the result still the same : list of Gphoto2 camera drivers still empty.

Gilles Caulier

**Comment by yarda** [comment]
I created PR for the rebase  to 2.5.28. I haven't tested whether it resolves the original problem.
