### ISSUE TITLE
MXE compilation - Ubuntu 21.10 - fail at alure package step

### ISSUE THREAD

**Issue by megautier** [mxe/mxe#2764]
Hi,

I reinstalled my computer and I chose to use the last ubuntu version 21.10. As there is no MXE default package available, I need to compile the full project with qt included.

`git clone https://github.com/mxe/mxe.git`
`make MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static x86_64-w64-mingw32.shared i686-w64-mingw32.shared'`

Here the error display message that I got

```
[download]    alure-1.2.tar.bz2
MXE Warning! Downloading alure from backup.
[build]       alure                   x86_64-w64-mingw32.static

Failed to build package alure for target x86_64-w64-mingw32.static
------------------------------------------------------------
make[3]: *** [CMakeFiles/Makefile2:83: CMakeFiles/ALURE32-static.dir/all] Error 2
make[3]: Leaving directory '/media/melaine/sharedDrive/coding/mxe/tmp-alure-x86_64-w64-mingw32.static/alure-1.2.build_'
make[2]: *** [Makefile:136: all] Error 2
make[2]: Leaving directory '/media/melaine/sharedDrive/coding/mxe/tmp-alure-x86_64-w64-mingw32.static/alure-1.2.build_'
make[1]: *** [Makefile:881: build-only-alure_x86_64-w64-mingw32.static] Error 2
make[1]: Leaving directory '/media/melaine/sharedDrive/coding/mxe'
real	0m36,072s
user	0m35,945s
sys	0m5,661s
------------------------------------------------------------
[log]      /media/melaine/sharedDrive/coding/mxe/log/alure_x86_64-w64-mingw32.static

make: *** [Makefile:869: /media/melaine/sharedDrive/coding/mxe/usr/x86_64-w64-mingw32.static/installed/alure] Error 1
```

Here is the gist link for the [log](https://gist.githubusercontent.com/megautier/d4019e34774ef52f812c19e0dc50628d/raw/4b734369661c558c78f9b6d1bc0747fdd87e741e/alure_x86_64-w64-mingw32.static.log)
But to make it short, the error line 402 :
```
/media/melaine/sharedDrive/coding/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static-g++ -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_WIN32 @CMakeFiles/ALURE32-static.dir/includes_CXX.rsp -O3 -DNDEBUG   -Wextra -Wall -funswitch-loops -DAL_LIBTYPE_STATIC -DALURE_STATIC_LIBRARY -I/media/melaine/sharedDrive/coding/mxe/usr/x86_64-w64-mingw32.static/include;-I/media/melaine/sharedDrive/coding/mxe/usr/x86_64-w64-mingw32.static/include/opus -MD -MT CMakeFiles/ALURE32-static.dir/src/codec_sndfile.obj -MF CMakeFiles/ALURE32-static.dir/src/codec_sndfile.obj.d -o CMakeFiles/ALURE32-static.dir/src/codec_sndfile.obj -c /media/melaine/sharedDrive/coding/mxe/tmp-alure-x86_64-w64-mingw32.static/alure-1.2/src/codec_sndfile.cpp
x86_64-w64-mingw32.static-g++: fatal error: no input files
compilation terminated.
/bin/sh: 1: -I/media/melaine/sharedDrive/coding/mxe/usr/x86_64-w64-mingw32.static/include/opus: not found
make[4]: *** [CMakeFiles/ALURE32-static.dir/build.make:197: CMakeFiles/ALURE32-static.dir/src/codec_sndfile.obj] Error 127
```

Thanks in advance for all the help you can provide.

Best regards,
Melaine

**Comment by mabrand** [comment]
You probably don't need to build every single package in MXE. Just specify the ones you need on when you call 'make'.

**Comment by mabrand** [comment]
Alure should build again now, but I'm not sure if that was your goal or not. 
`make MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static x86_64-w64-mingw32.shared i686-w64-mingw32.shared'`
This builds every single package (except the broken ones), but almost no one wants every single package.

**Comment by megautier** [comment]
Yes, you're right I certainly don't need everything but as I'm not sure of the package required, I tried the general compilation.
What I really need is to compile with qt5 libraries as I have a project using qt and qml.

I'm compiling with the current command line 
`make cc qt5 MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static x86_64-w64-mingw32.shared i686-w64-mingw32.shared'`

And I hope that it'll work good.
Thank you for your time and your help
