### ISSUE TITLE
jasper 3.0.2 build failure: linker cannot find GetPhysicallyInstalledSystemMemory in winapi

### ISSUE THREAD

**Issue by colinbourassa** [mxe/mxe#2771]
JasPer 3.0.2 will not build successfully for the i686-w64-mingw32.shared target. The linker fails to find the Windows API function `GetPhysicallyInstalledSystemMemory`.

Log: https://gist.github.com/colinbourassa/32c940fb112b0f0cc46b5b8ce93689d8

To reproduce:
* Set `MXE_TARGETS := i686-w64-mingw32.shared` in `settings.mk`
* Run `make jasper`

**Comment by MarcoBorrini99** [comment]
Only way is to revert jasper to v2.0.33
