### ISSUE TITLE
Can't build x86_64-w64-mingw32.static.posix-gdb

### ISSUE THREAD

**Issue by sccoouut** [mxe/mxe#2784]
Hey, I can't build the **x86_64-w64-mingw32.static.posix-gdb** packaged.
The reason is missing include `<srchilite/sourcehighlight.h>`. Although, my system has this include in /usr/include:
![image](https://user-images.githubusercontent.com/88430645/156609133-d86cb16b-9ebd-4135-86d4-06ad062aba9e.png)

Distro I'm using is Arch Linux, and I have installed all required packages. Also, I have tried to reinstall source-highlight package using pacman, but it has not helped.

Full log:
https://gist.github.com/sccoouut/ed72b19989f9c2ada931a9e42910d24a

Thanks in advance.

**Comment by danger89** [comment]
You are not the first person: https://stackoverflow.com/questions/68944617/cant-cross-compile-gdb-with-mingw

**Comment by danger89** [comment]
PR created for you 👍🏽 https://github.com/mxe/mxe/pull/2787

**Comment by sccoouut** [comment]
Thanks, I has also found this solution, but didn't know is it good enough.
Thank you anyway.
