### ISSUE TITLE
qt6-qtbase fails to build

### ISSUE THREAD

**Issue by stloeffler** [mxe/mxe#2794]
Building the host version (x86_64-pc-linux-gnu) fails at configuring, complaining about failing OpenGL tests on my Ubuntu focal chroot environment. Installing `libgl-dev` (using apt-get) fixes the issue, so this should be added to the build dependencies documentation.

**Comment by mabrand** [comment]
Looks like https://github.com/mxe/mxe/pull/2768
Could you try adding -DFEATURE_{eventfd,glib,icu,openssl,gui}=OFF to the host build (i.e., "build build") to see if this solves the problem?

**Comment by stloeffler** [comment]
Down the rabbit hole we go...
Disabling `gui` (the rest is already disabled in [qt6-qtbase l77](https://github.com/mxe/mxe/blob/563fadc031c6b4738e9839b4721c8a40d3fe7e6f/src/qt/qt6/qt6-qtbase.mk#L77) "fixes" the host build and allows qt6-qtbase to build (both host and i686-w64-mingw32.static).
However, doing so now breaks the qt6-qtshadertools (required by qt6-qtdeclarative, in turn now required by qt6-qttools). The qt6-qtshadertools host package is (gracefully) not built at all with the message `Skipping the build as the condition "TARGET Qt::Gui" is not met`. Then the target build (i686-w64-mingw32.static) fails during configuration with the error `The tool "Qt6::qsb" was not found in the Qt6ShaderToolsTools package`. [qsb](https://doc.qt.io/qt-6/qtshadertools-qsb.html) seems to be a tool for compiling (OpenGL) shaders and should be built for the host (but never is).

**Comment by stloeffler** [comment]
I commented on this at the original issue #2768 to try and keep the discussion in one place.
