### ISSUE TITLE
Problem cross-compiling Qt6 with CMake

### ISSUE THREAD

**Issue by ju3** [mxe/mxe#2799]
Hi,

I'm trying to cross-build (x86_64-w64-mingw32.shared) a Qt6 binary with CMake in a Docker container. But when calling the MXE CMake wrapper script, the configuration fails due to missing Qt6WidgetsTools (```-- Could NOT find Qt6WidgetsTools (missing: Qt6WidgetsTools_DIR```).

I've uploaded Dockerfile, CMakeLists.txt and build outputs here: https://gist.github.com/ju3/6b6212f24718770f3e89e6b385c9ccd5

Doing the same with a Qt5 project (and the corresponding qt5.mk build) works fine.

Thank you for your help.

**Comment by stloeffler** [comment]
One thing I did that might help here is to set `-DQT_HOST_PATH="/opt/mxe/usr/x86_64-pc-linux-gnu/qt6"` when invoking cmake to tell it where to find native qt tools (such as moc, uic, rcc, ...) - see also the discussion at #2768.

**Comment by ju3** [comment]
Thank you very much, it worked!

Adding the file `/opt/mxe/usr/x86_64-w64-mingw32.shared/share/cmake/mxe-conf.d/qt6.cmake` with content `set(QT_HOST_PATH "/opt/mxe/usr/x86_64-pc-linux-gnu/qt6")` makes CMake work out of the box.

**Comment by ju3** [comment]
I've created pull request #2802.
