### ISSUE TITLE
QtWebkit do not compile for x86_64-w64-mingw32.shared With GCC11

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2814]
From git revision 8f8a9f5807b217c585b3167ce717eb708e425246
```
[build]       qtbase                 x86_64-w64-mingw32.shared
[done]        qtbase                 x86_64-w64-mingw32.shared                              730988 KiB     14m2.171s
[download]    qtactiveqt-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtactiveqt             x86_64-w64-mingw32.shared
[done]        qtactiveqt             x86_64-w64-mingw32.shared                              7868 KiB       0m57.111s
[download]    libmng-2.0.3.tar.xz
[build]       libmng                 x86_64-w64-mingw32.shared
[done]        libmng                 x86_64-w64-mingw32.shared                              13272 KiB      0m12.868s
[download]    qtimageformats-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtimageformats         x86_64-w64-mingw32.shared
[done]        qtimageformats         x86_64-w64-mingw32.shared                              13280 KiB      0m18.818s
[download]    qtsvg-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtsvg                  x86_64-w64-mingw32.shared
[done]        qtsvg                  x86_64-w64-mingw32.shared                              18656 KiB      0m25.300s
[download]    qtxmlpatterns-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtxmlpatterns          x86_64-w64-mingw32.shared
[done]        qtxmlpatterns          x86_64-w64-mingw32.shared                              345040 KiB     5m9.529s
[download]    qtdeclarative-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtdeclarative          x86_64-w64-mingw32.shared
[done]        qtdeclarative          x86_64-w64-mingw32.shared                              430444 KiB     22m30.402s
[download]    qttools-everywhere-opensource-src-5.15.3.tar.xz
[build]       qttools                x86_64-w64-mingw32.shared
[done]        qttools                x86_64-w64-mingw32.shared                              82856 KiB      1m46.680s
[download]    qttranslations-everywhere-opensource-src-5.15.3.tar.xz
[build]       qttranslations         x86_64-w64-mingw32.shared
[done]        qttranslations         x86_64-w64-mingw32.shared                              39060 KiB      0m8.402s
make: Nothing to be done for 'qtimageformats'.
make: Nothing to be done for 'qttools'.
[download]    qtmultimedia-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtmultimedia           x86_64-w64-mingw32.shared
[done]        qtmultimedia           x86_64-w64-mingw32.shared                              61072 KiB      4m59.438s
[download]    qtwinextras-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtwinextras            x86_64-w64-mingw32.shared
[done]        qtwinextras            x86_64-w64-mingw32.shared                              6516 KiB       0m45.510s
[download]    qtscript-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtscript               x86_64-w64-mingw32.shared
[done]        qtscript               x86_64-w64-mingw32.shared                              53176 KiB      5m31.468s
[download]    qtquickcontrols-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtquickcontrols        x86_64-w64-mingw32.shared
[done]        qtquickcontrols        x86_64-w64-mingw32.shared                              33108 KiB      3m2.939s
[download]    qtsensors-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtsensors              x86_64-w64-mingw32.shared
[done]        qtsensors              x86_64-w64-mingw32.shared                              18404 KiB      1m30.516s
[download]    qtwebsockets-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtwebsockets           x86_64-w64-mingw32.shared
[done]        qtwebsockets           x86_64-w64-mingw32.shared                              6588 KiB       0m24.509s
[download]    qtwebchannel-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtwebchannel           x86_64-w64-mingw32.shared
[done]        qtwebchannel           x86_64-w64-mingw32.shared                              5300 KiB       0m12.787s
[download]    qtwebkit-opensource-src-5.212.tar.xz
[build]       qtwebkit               x86_64-w64-mingw32.shared

Failed to build package qtwebkit for target x86_64-w64-mingw32.shared!
------------------------------------------------------------
[ 95%] Built target WebKit2
make[3]: Leaving directory '/home/gilles/Documents/7.x/project/bundles/mxe/build.win64/tmp-qtwebkit-x86_64-w64-mingw32.shared/qtwebkit-opensource-src-5.212.build_'
make[2]: *** [Makefile:166: all] Error 2
make[2]: Leaving directory '/home/gilles/Documents/7.x/project/bundles/mxe/build.win64/tmp-qtwebkit-x86_64-w64-mingw32.shared/qtwebkit-opensource-src-5.212.build_'
make[1]: *** [Makefile:896: build-only-qtwebkit_x86_64-w64-mingw32.shared] Error 2
make[1]: Leaving directory '/home/gilles/Documents/7.x/project/bundles/mxe/build.win64'
real    111m42.132s
user    388m12.805s
sys     51m4.577s
------------------------------------------------------------
[log]      /home/gilles/Documents/7.x/project/bundles/mxe/build.win64/log/qtwebkit_x86_64-w64-mingw32.shared

make: *** [Makefile:884: /home/gilles/Documents/7.x/project/bundles/mxe/build.win64/usr/x86_64-w64-mingw32.shared/installed/qtwebkit] Error 1
FAILED COMMAND: make MXE_TARGETS=$MXE_BUILD_TARGETS openssl cmake yasm gettext freeglut libxml2 libxslt libjpeg-turbo libpng djvulibre tiff boost expat lcms liblqr-1 eigen jasper zlib bzip2 mman-win32 pthreads libgphoto2 icu4c qtbase qtbase_CONFIGURE_OPTS=-icu qttranslations qtimageformats qttools qtwinextras qtscript qtwebkit fdk-aac x264 x265 xvidcore libvpx theora vorbis opencore-amr librtmp opus speex lame freetype libass openal libical fftw libltdl openexr

```

**Comment by MarcoBorrini99** [comment]
> [qtwebkit_x86_64-w64-mingw32.shared.txt](https://github.com/mxe/mxe/files/8465342/qtwebkit_x86_64-w64-mingw32.shared.txt)

It seems to be a side effect of the upgraded binutils, il you use the previuos one the linking stage doesn't fail.

**Comment by cgilles** [comment]
Hi Marco,

Yes, previous revision of MXE work well. To be more precise, the log come from digiKam Windows build. The current Windows production is based on Qt 5.15.2 and we must switch to Qt 5.15.3 for bug with recent Mysql/Mariadb release in Qtsql module. So i started to recompile all with MXE master.

This is the [git MXE revision used previously](https://invent.kde.org/graphics/digikam/-/blob/master/project/bundles/mxe/config.sh#L44)

Later this revision i faced plenty of broken compilations, as now this last one.

Best 

Gilles Caulier

**Comment by MarcoBorrini99** [comment]
> Hi all,
> 
> What's about this file ? Do i need to patch locally MXE code to use an older revision of binutils as Marco described previously ?
> 
> Thanks in advance
> 
> Gilles Caulier

I'd suggest to stick with a well known working commit!

**Comment by cgilles** [comment]
I cannot. For security and bug-fix reasons, i need to get Qt5.15.3, especially for the QtMysql plugin which do not work as expected with recent releases of mysql/mariadb. So i need to use master revision as possible...

**Comment by tonytheodore** [comment]
Can you test if the latest binutils 2.38 fixes it?
```
make update-package-binutils
make clean
make qtwebkit
```
otherwise I'll revert back to 2.36.1

**Comment by cgilles** [comment]
right. I will do it today...

Gilles

**Comment by cgilles** [comment]
Compilation of MXE from scratch using git master is under progress :

'''
---------- Continue aborted previous installation in /mnt/data/7.x/project/bundles/mxe/build.win64


---------- Updating MXE
Already up to date.
[download]    libiconv-1.16.tar.gz
[build]       libiconv               x86_64-w64-mingw32.shared
[done]        libiconv               x86_64-w64-mingw32.shared                              25840 KiB      0m25.155s
[build]       libiconv               x86_64-pc-linux-gnu
[done]        libiconv               x86_64-pc-linux-gnu                                    31380 KiB      0m23.575s
[download]    gettext-0.21.tar.lz
[build]       gettext                x86_64-pc-linux-gnu
[done]        gettext                x86_64-pc-linux-gnu                                    305992 KiB     4m44.964s
[build]       gettext                x86_64-w64-mingw32.shared
[done]        gettext                x86_64-w64-mingw32.shared                              136796 KiB     0m45.981s
[download]    freeglut-3.2.1.tar.gz
[build]       freeglut               x86_64-w64-mingw32.shared
[done]        freeglut               x86_64-w64-mingw32.shared                              8524 KiB       0m23.285s
[download]    xz-5.2.5.tar.gz
[build]       xz                     x86_64-w64-mingw32.shared
[done]        xz                     x86_64-w64-mingw32.shared                              11896 KiB      0m43.468s
[download]    libxml2-2.9.12.tar.gz
[build]       libxml2                x86_64-w64-mingw32.shared
[done]        libxml2                x86_64-w64-mingw32.shared                              71184 KiB      0m54.888s
[download]    libgpg-error-1.45.tar.bz2
[build]       libgpg_error           x86_64-w64-mingw32.shared
[done]        libgpg_error           x86_64-w64-mingw32.shared                              12612 KiB      0m47.000s
[download]    libgcrypt-1.10.1.tar.bz2
[build]       libgcrypt              x86_64-w64-mingw32.shared
[done]        libgcrypt              x86_64-w64-mingw32.shared                              42956 KiB      0m55.462s
[download]    libxslt-1.1.35.tar.xz
[build]       libxslt                x86_64-w64-mingw32.shared
[done]        libxslt                x86_64-w64-mingw32.shared                              37196 KiB      0m30.392s
[download]    libjpeg-turbo-2.1.3.tar.gz
[build]       libjpeg-turbo          x86_64-w64-mingw32.shared
[done]        libjpeg-turbo          x86_64-w64-mingw32.shared                              34348 KiB      2m44.961s
[download]    libpng-1.6.37.tar.xz
[build]       libpng                 x86_64-w64-mingw32.shared
[done]        libpng                 x86_64-w64-mingw32.shared                              16480 KiB      3m25.896s
[download]    jpegsrc.v9e.tar.gz
[build]       jpeg                   x86_64-w64-mingw32.shared
[done]        jpeg                   x86_64-w64-mingw32.shared                              8884 KiB       1m29.023s
[download]    libwebp-1.2.2.tar.gz
[build]       libwebp                x86_64-w64-mingw32.shared
[done]        libwebp                x86_64-w64-mingw32.shared                              35212 KiB      2m35.754s
[download]    tiff-4.3.0.tar.gz
[build]       tiff                   x86_64-w64-mingw32.shared
[done]        tiff                   x86_64-w64-mingw32.shared                              17336 KiB      3m31.936s
[download]    djvulibre-3.5.27.tar.gz
[build]       djvulibre              x86_64-w64-mingw32.shared
[done]        djvulibre              x86_64-w64-mingw32.shared                              74952 KiB      2m27.596s
make: Nothing to be done for 'tiff'.
[download]    bzip2-1.0.8.tar.gz
[build]       bzip2                  x86_64-w64-mingw32.shared
[done]        bzip2                  x86_64-w64-mingw32.shared                              3668 KiB       0m5.562s
[download]    expat-2.4.8.tar.bz2
[build]       expat                  x86_64-w64-mingw32.shared
[done]        expat                  x86_64-w64-mingw32.shared                              8800 KiB       0m38.219s
[download]    boost_1_78_0.tar.bz2
[build]       boost                  x86_64-w64-mingw32.shared
[done]        boost                  x86_64-w64-mingw32.shared                              931292 KiB     9m52.622s
make: Nothing to be done for 'expat'.
[download]    lcms2-2.13.tar.gz
[build]       lcms                   x86_64-w64-mingw32.shared
[done]        lcms                   x86_64-w64-mingw32.shared                              19084 KiB      0m23.906s
[download]    ninja-v1.10.2.tar.gz
[build]       ninja                  x86_64-pc-linux-gnu
[done]        ninja                  x86_64-pc-linux-gnu                                    6808 KiB       0m11.539s
[download]    meson-0.61.2.tar.gz
[build]       meson                  x86_64-pc-linux-gnu
[done]        meson                  x86_64-pc-linux-gnu                                    25760 KiB      0m4.210s
[build]       meson-wrapper          x86_64-pc-linux-gnu
[done]        meson-wrapper          x86_64-pc-linux-gnu                                    12 KiB         0m3.684s
[build]       meson-wrapper          x86_64-w64-mingw32.shared
[done]        meson-wrapper          x86_64-w64-mingw32.shared                              12 KiB         0m3.710s
[download]    dbus-1.13.22.tar.xz
[build]       dbus                   x86_64-w64-mingw32.shared
[done]        dbus                   x86_64-w64-mingw32.shared                              22700 KiB      1m20.870s
[download]    libffi-3.2.1.tar.gz
[build]       libffi                 x86_64-w64-mingw32.shared
[done]        libffi                 x86_64-w64-mingw32.shared                              6580 KiB       0m12.943s
[download]    pcre-8.45.tar.bz2
[build]       pcre                   x86_64-w64-mingw32.shared
[done]        pcre                   x86_64-w64-mingw32.shared                              16336 KiB      0m24.001s
[meta]        cc                     x86_64-pc-linux-gnu
[build]       libffi                 x86_64-pc-linux-gnu
[done]        libffi                 x86_64-pc-linux-gnu                                    6488 KiB       0m10.216s
[build]       zlib                   x86_64-pc-linux-gnu
[done]        zlib                   x86_64-pc-linux-gnu                                    5096 KiB       0m4.870s
[download]    glib-2.70.2.tar.xz
[build]       glib                   x86_64-pc-linux-gnu
[done]        glib                   x86_64-pc-linux-gnu                                    139084 KiB     1m15.316s
[build]       glib                   x86_64-w64-mingw32.shared
[done]        glib                   x86_64-w64-mingw32.shared                              90848 KiB      2m49.031s
[download]    liblqr-1-0.4.2.tar.bz2
[disabled]    liblqr-1               x86_64-w64-mingw32.shared
[download]    eigen-3.4.0.tar.bz2
[build]       eigen                  x86_64-w64-mingw32.shared
[done]        eigen                  x86_64-w64-mingw32.shared                              49604 KiB      0m10.924s
[download]    jasper-version-3.0.3.tar.gz
[build]       jasper                 x86_64-w64-mingw32.shared
[done]        jasper                 x86_64-w64-mingw32.shared                              10336 KiB      0m14.914s
make: Nothing to be done for 'zlib'.
make: Nothing to be done for 'bzip2'.
[download]    mman-win32-9f115ad.tar.gz
MXE Warning! Downloading mman-win32 from backup.
[build]       mman-win32             x86_64-w64-mingw32.shared
[done]        mman-win32             x86_64-w64-mingw32.shared                              876 KiB        0m5.578s
[build]       pthreads               x86_64-w64-mingw32.shared
[done]        pthreads               x86_64-w64-mingw32.shared                              1168 KiB       0m4.499s
[download]    libunistring-0.9.10.tar.xz
[build]       libunistring           x86_64-w64-mingw32.shared
[done]        libunistring           x86_64-w64-mingw32.shared                              49608 KiB      2m16.618s
[download]    libidn2-2.3.0.tar.lz
[build]       libidn2                x86_64-w64-mingw32.shared
[done]        libidn2                x86_64-w64-mingw32.shared                              20576 KiB      0m33.012s
[download]    libssh2-1.10.0.tar.gz
[build]       libssh2                x86_64-w64-mingw32.shared
[done]        libssh2                x86_64-w64-mingw32.shared                              8368 KiB       0m24.072s
[download]    curl-7.83.0.tar.xz
[build]       curl                   x86_64-w64-mingw32.shared
[done]        curl                   x86_64-w64-mingw32.shared                              148216 KiB     4m5.218s
[download]    dlfcn-win32-v1.3.0.tar.gz
[build]       dlfcn-win32            x86_64-w64-mingw32.shared
[done]        dlfcn-win32            x86_64-w64-mingw32.shared                              908 KiB        0m6.368s
[build]       libltdl                x86_64-w64-mingw32.shared
[done]        libltdl                x86_64-w64-mingw32.shared                              10464 KiB      0m10.141s
[download]    libusb-1.0.26.tar.bz2
[build]       libusb1                x86_64-w64-mingw32.shared
[done]        libusb1                x86_64-w64-mingw32.shared                              7284 KiB       0m17.707s
[download]    libexif-0.6.22-release.tar.gz
MXE Warning! Downloading libexif from second URL.
[build]       libexif                x86_64-w64-mingw32.shared
[done]        libexif                x86_64-w64-mingw32.shared                              22140 KiB      0m21.636s
[download]    libgphoto2-v2.5.28.tar.gz
[build]       libgphoto2             x86_64-w64-mingw32.shared
[done]        libgphoto2             x86_64-w64-mingw32.shared                              81584 KiB      2m14.898s
[download]    icu4c-release-66.1.tar.gz
[build]       icu4c                  x86_64-pc-linux-gnu
^[[B[done]        icu4c                  x86_64-pc-linux-gnu                                    104384 KiB     2m53.989s
[build]       icu4c                  x86_64-w64-mingw32.shared
[done]        icu4c                  x86_64-w64-mingw32.shared                              357408 KiB     3m10.366s
[download]    freetype-2.12.1.tar.xz
[build]       freetype-bootstrap     x86_64-w64-mingw32.shared
[done]        freetype-bootstrap     x86_64-w64-mingw32.shared                              29120 KiB      0m23.948s
[download]    fontconfig-2.14.0.tar.xz
[build]       fontconfig             x86_64-w64-mingw32.shared
[done]        fontconfig             x86_64-w64-mingw32.shared                              17840 KiB      0m41.502s
[download]    freetds-1.3.10.tar.bz2
[build]       freetds                x86_64-w64-mingw32.shared
[done]        freetds                x86_64-w64-mingw32.shared                              56584 KiB      2m19.323s
[download]    lzo-2.10.tar.gz
[build]       lzo                    x86_64-w64-mingw32.shared
[done]        lzo                    x86_64-w64-mingw32.shared                              7108 KiB       0m38.342s
[download]    pixman-0.33.6.tar.gz
[build]       pixman                 x86_64-w64-mingw32.shared
[done]        pixman                 x86_64-w64-mingw32.shared                              24372 KiB      0m33.086s
[download]    cairo-1.16.0.tar.xz
[build]       cairo                  x86_64-w64-mingw32.shared
[done]        cairo                  x86_64-w64-mingw32.shared                              106456 KiB     1m29.702s
[download]    harfbuzz-4.2.1.tar.gz
MXE Warning! Downloading harfbuzz from second URL.
[build]       harfbuzz               x86_64-w64-mingw32.shared
[done]        harfbuzz               x86_64-w64-mingw32.shared                              102544 KiB     2m35.688s
[build]       freetype               x86_64-w64-mingw32.shared
[done]        freetype               x86_64-w64-mingw32.shared                              29168 KiB      0m21.128s
[download]    mysql-connector-c-6.1.6-src.tar.gz
[build]       libmysqlclient         x86_64-w64-mingw32.shared
[done]        libmysqlclient         x86_64-w64-mingw32.shared                              215468 KiB     2m6.979s
[download]    zstd-v1.5.2.tar.gz
[build]       zstd                   x86_64-w64-mingw32.shared
[done]        zstd                   x86_64-w64-mingw32.shared                              13628 KiB      0m17.704s
[download]    mesa-22.0.2.tar.xz
[build]       mesa                   x86_64-w64-mingw32.shared
[done]        mesa                   x86_64-w64-mingw32.shared                              264500 KiB     6m37.473s
[download]    pcre2-10.37.tar.bz2
MXE Warning! Downloading pcre2 from second URL.
[build]       pcre2                  x86_64-w64-mingw32.shared
[done]        pcre2                  x86_64-w64-mingw32.shared                              15840 KiB      0m21.098s
[download]    postgresql-13.6.tar.bz2
[build]       postgresql             x86_64-w64-mingw32.shared
[done]        postgresql             x86_64-w64-mingw32.shared                              315172 KiB     4m24.268s
[download]    sqlite-autoconf-3380300.tar.gz
[build]       sqlite                 x86_64-w64-mingw32.shared
[done]        sqlite                 x86_64-w64-mingw32.shared                              17776 KiB      1m12.484s
[build]       zstd                   x86_64-pc-linux-gnu
[done]        zstd                   x86_64-pc-linux-gnu                                    16020 KiB      0m26.548s
[download]    qtbase-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtbase                 x86_64-w64-mingw32.shared
[done]        qtbase                 x86_64-w64-mingw32.shared                              730916 KiB     33m37.932s
[download]    qtactiveqt-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtactiveqt             x86_64-w64-mingw32.shared
[done]        qtactiveqt             x86_64-w64-mingw32.shared                              7860 KiB       0m57.434s
[download]    libmng-2.0.3.tar.xz
[build]       libmng                 x86_64-w64-mingw32.shared
[done]        libmng                 x86_64-w64-mingw32.shared                              13272 KiB      0m13.023s
[download]    qtimageformats-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtimageformats         x86_64-w64-mingw32.shared
[done]        qtimageformats         x86_64-w64-mingw32.shared                              13276 KiB      0m16.265s
[download]    qtsvg-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtsvg                  x86_64-w64-mingw32.shared
[done]        qtsvg                  x86_64-w64-mingw32.shared                              18636 KiB      0m23.888s
[download]    qtxmlpatterns-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtxmlpatterns          x86_64-w64-mingw32.shared
[done]        qtxmlpatterns          x86_64-w64-mingw32.shared                              344932 KiB     4m22.929s
[download]    qtdeclarative-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtdeclarative          x86_64-w64-mingw32.shared
[done]        qtdeclarative          x86_64-w64-mingw32.shared                              429684 KiB     19m57.167s
[download]    qttools-everywhere-opensource-src-5.15.3.tar.xz
[build]       qttools                x86_64-w64-mingw32.shared
[done]        qttools                x86_64-w64-mingw32.shared                              82792 KiB      1m33.181s
[download]    qttranslations-everywhere-opensource-src-5.15.3.tar.xz
[build]       qttranslations         x86_64-w64-mingw32.shared
[done]        qttranslations         x86_64-w64-mingw32.shared                              39056 KiB      0m8.493s
make: Nothing to be done for 'qtimageformats'.
make: Nothing to be done for 'qttools'.
[download]    qtmultimedia-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtmultimedia           x86_64-w64-mingw32.shared
[done]        qtmultimedia           x86_64-w64-mingw32.shared                              60928 KiB      4m42.709s
[download]    qtwinextras-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtwinextras            x86_64-w64-mingw32.shared
[done]        qtwinextras            x86_64-w64-mingw32.shared                              6488 KiB       0m45.435s
[download]    qtscript-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtscript               x86_64-w64-mingw32.shared
[done]        qtscript               x86_64-w64-mingw32.shared                              53092 KiB      5m2.521s
[download]    qtquickcontrols-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtquickcontrols        x86_64-w64-mingw32.shared
[done]        qtquickcontrols        x86_64-w64-mingw32.shared                              33028 KiB      2m42.968s
[download]    qtsensors-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtsensors              x86_64-w64-mingw32.shared
[done]        qtsensors              x86_64-w64-mingw32.shared                              18344 KiB      1m19.998s
[download]    qtwebsockets-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtwebsockets           x86_64-w64-mingw32.shared
[done]        qtwebsockets           x86_64-w64-mingw32.shared                              6576 KiB       0m24.908s
[download]    qtwebchannel-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtwebchannel           x86_64-w64-mingw32.shared
[done]        qtwebchannel           x86_64-w64-mingw32.shared                              5284 KiB       0m13.181s
[download]    qtwebkit-opensource-src-5.212.tar.xz
[build]       qtwebkit               x86_64-w64-mingw32.shared
'''

**Comment by cgilles** [comment]
We will see if qtwebkit pass or not...

Gilles Caulier

**Comment by cgilles** [comment]
hum now the error is clear :

[ 81%] Building CXX object Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSInternalSettings.cpp.obj
cd /mnt/data/7.x.mxe-master/project/bundles/mxe/build.win64/tmp-qtwebkit-x86_64-w64-mingw32.shared/qtwebkit-opensource-src-5.212.build_/Source/WebCore && /mnt/data/7.x.mxe-master/project/bundles/mxe/build.win64/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.shared-g++ -DBUILDING_QT__=1 -DBUILDING_WITH_CMAKE=1 -DHAVE_CONFIG_H=1 -DNOMINMAX -DQT_ASCII_CAST_WARNINGS -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DYNAMIC_CAST -DQT_NO_EXCEPTIONS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_SENSORS_LIB -DQT_USE_QSTRINGBUILDER -DSTATICALLY_LINKED_WITH_JavaScriptCore -DSTATICALLY_LINKED_WITH_WTF -DUNICODE -D_UNICODE -D_WINDOWS -D__USE_MINGW_ANSI_STDIO=1 @CMakeFiles/WebCoreTestSupport.dir/includes_CXX.rsp -fpermissive -fno-exceptions -fno-strict-aliasing -fno-rtti -std=c++11 -mno-ms-bitfields -Wno-unknown-pragmas -Wno-expansion-to-defined -fno-keep-inline-dllexport -O3 -DNDEBUG -Wall -Wextra -Wcast-align -Wformat-security -Wmissing-format-attribute -Wpointer-arith -Wundef -Wwrite-strings  -include testing/js/WebCoreTestSupportPrefix.h -MD -MT Source/WebCore/CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSInternalSettings.cpp.obj -MF CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSInternalSettings.cpp.obj.d -o CMakeFiles/WebCoreTestSupport.dir/__/__/DerivedSources/WebCore/JSInternalSettings.cpp.obj -c /mnt/data/7.x.mxe-master/project/bundles/mxe/build.win64/tmp-qtwebkit-x86_64-w64-mingw32.shared/qtwebkit-opensource-src-5.212.build_/DerivedSources/WebCore/JSInternalSettings.cpp
/mnt/data/7.x.mxe-master/project/bundles/mxe/build.win64/usr/bin/x86_64-w64-mingw32.shared-ld: ../../lib/libWebCore.a: error adding symbols: malformed archive
collect2: error: ld returned 1 exit status
make[4]: *** [Tools/TestWebKitAPI/CMakeFiles/TestWebCore.dir/build.make:247: bin/TestWebKitAPI/WebCore/TestWebCore.exe] Error 1
make[4]: Leaving directory '/mnt/data/7.x.mxe-master/project/bundles/mxe/build.win64/tmp-qtwebkit-x86_64-w64-mingw32.shared/qtwebkit-opensource-src-5.212.build_'
make[3]: *** [CMakeFiles/Makefile2:2201: Tools/TestWebKitAPI/CMakeFiles/TestWebCore.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....

**Comment by tonytheodore** [comment]
Did you [update `binutils`](https://github.com/mxe/mxe/issues/2814#issuecomment-1116878793)? i686-w64-mingw32.shared is working for me, testing x86_64 now.

**Comment by cgilles** [comment]
well i delete all previous build are recompile all frpm scratch to be sure. all is up to date using git master

Gilles

**Comment by tonytheodore** [comment]
I can confirm it works on both shared targets with binutils 2.38

**Comment by cgilles** [comment]
Great, it pass now :

[download]    qtmultimedia-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtmultimedia           x86_64-w64-mingw32.shared
[done]        qtmultimedia           x86_64-w64-mingw32.shared                              61000 KiB      4m34.922s
[download]    qtwinextras-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtwinextras            x86_64-w64-mingw32.shared
[done]        qtwinextras            x86_64-w64-mingw32.shared                              6496 KiB       0m45.547s
[download]    qtscript-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtscript               x86_64-w64-mingw32.shared
[done]        qtscript               x86_64-w64-mingw32.shared                              53104 KiB      5m1.067s
[download]    qtquickcontrols-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtquickcontrols        x86_64-w64-mingw32.shared
[done]        qtquickcontrols        x86_64-w64-mingw32.shared                              33028 KiB      2m47.447s
[download]    qtsensors-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtsensors              x86_64-w64-mingw32.shared
[done]        qtsensors              x86_64-w64-mingw32.shared                              18364 KiB      1m21.207s
[download]    qtwebsockets-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtwebsockets           x86_64-w64-mingw32.shared
[done]        qtwebsockets           x86_64-w64-mingw32.shared                              6584 KiB       0m24.977s
[download]    qtwebchannel-everywhere-opensource-src-5.15.3.tar.xz
[build]       qtwebchannel           x86_64-w64-mingw32.shared
[done]        qtwebchannel           x86_64-w64-mingw32.shared                              5288 KiB       0m12.840s
[download]    qtwebkit-opensource-src-5.212.tar.xz
[build]       qtwebkit               x86_64-w64-mingw32.shared
[done]        qtwebkit               x86_64-w64-mingw32.shared                              1391300 KiB    120m35.385s

^^^^^^^^
...
[download]    fdk-aac-2.0.0.tar.gz
[build]       fdk-aac                x86_64-w64-mingw32.shared
[done]        fdk-aac                x86_64-w64-mingw32.shared                              20648 KiB      0m49.548s
[download]    liblsmash-v2.14.5.tar.gz
[build]       liblsmash              x86_64-w64-mingw32.shared
[done]        liblsmash              x86_64-w64-mingw32.shared                              5936 KiB       0m12.017s
[download]    nasm-2.14.02.tar.xz
[build]       nasm                   x86_64-pc-linux-gnu
[done]        nasm                   x86_64-pc-linux-gnu                                    34504 KiB      0m18.713s
[download]    x264-snapshot-20180806-2245.tar.bz2
[build]       x264                   x86_64-w64-mingw32.shared
[done]        x264                   x86_64-w64-mingw32.shared                              20024 KiB      1m48.868s
[download]    x265_2.4.tar.gz

Gilles
