### ISSUE TITLE
mesa fails to build due to not finding `stdlib.h`

### ISSUE THREAD

**Issue by mbunkus** [mxe/mxe#2831]
mesa fails to build both for `x86_64-w64-mingw32.static` at the moment. Given the error message I'm confident it fails with `i686-w64-mingw32.static`, though I haven't tried that.

[Here](https://gist.github.com/mbunkus/a4ee575955eee522465a20e17f8fcd6a) is the build log. This is on a clean checkout of master at 27cf734072cde1c2f96aaf6ea97f5e52497ab44a with an empty `settings.mk`, built with `make MXE_TARGETS=x86_64-w64-mingw32.static mesa`

The gist (no pun intended) of it is:

```
/opt/mxe/usr-tmp/lib/gcc/x86_64-w64-mingw32.static/11.3.0/include/c++/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
   75 | #include_next <stdlib.h>
```

Compilation is fine on 3b61050dabf8b3fb0fae9e373ebb88205758ced0. c48dd7cd4d1e4d1d3d1cb19833240bc2b82517c3 is the first failing commit.

**Comment by mabrand** [comment]
My log:

> Found CMake: /home/brand/dev/mxe/usr/bin/x86_64-w64-mingw32.static-cmake (3.22.2)
Run-time dependency libdrm found: NO (tried pkgconfig and cmake)
Run-time dependency libudev found: NO (tried pkgconfig and cmake)
llvm-config found: NO need ['>= 3.9.0']
Run-time dependency LLVM found: NO (tried cmake and config-tool)

Your log:

> Found CMake: /opt/mxe/usr/bin/x86_64-w64-mingw32.static-cmake (3.22.2)
Run-time dependency libdrm found: NO (tried pkgconfig and cmake)
Run-time dependency libudev found: NO (tried pkgconfig and cmake)
WARNING: CMake: Dependency rt for LLVM was not found
WARNING: CMake: Dependency dl for LLVM was not found
WARNING: CMake: Dependency m for LLVM was not found

Maybe llvm detection has to be disabled for meson.

**Comment by tonytheodore** [comment]
Alternate approach in #2826 to enable llvm.

**Comment by mabrand** [comment]
I overlooked that, but it sounds like a more robust solution. Of course, llvm is not a particularly light dependency. Would MXE benefit from mesa with llvm support?
