### ISSUE TITLE
Can't Build libzmq

### ISSUE THREAD

**Issue by Keno98** [mxe/mxe#2832]
I am not able to build libzmq which I need for my Project. 
Either of those two commands try to build libzmq, which both fail with the following error.

![Console_Make_libzmq](https://user-images.githubusercontent.com/74984089/166476616-18c47fc3-e68e-4792-9599-01cf97b9ad96.png)

The Log output is as following:
[libzmq_i686-w64-mingw32.static.txt](https://github.com/mxe/mxe/files/8611325/libzmq_i686-w64-mingw32.static.txt)

I am pretty new, and that is why I am confused about the following error
    sys/socket.h: No such file or directory
poping up even though I can find the file under: 
   usr/include/sys/socket.h
   
I hope somebody can help me.

**Comment by tonytheodore** [comment]
See #2827
