### ISSUE TITLE
make can be specified QT version Well？

### ISSUE THREAD

**Issue by SanTaiZi-NeZha** [mxe/mxe#2845]
make can be specified QT 5.14.1 Well？

**Comment by mabrand** [comment]
What are you trying to do?

**Comment by SanTaiZi-NeZha** [comment]
I want to install qmake 5.14.1 but the qt5 package of master is 5.15.x

**Comment by mabrand** [comment]
Do you mean Qt 5.14.1? Or are you really focused on qmake for some reason?

Do you have the source packages for v5.14.1? They are no longer available from https://download.qt.io/official_releases/qt/, so MXE cannot download them.

You can revert MXE commits to get back to Qt 5.14.1. This will give you a list to choose from:

`git log --oneline  fe34c8f8^..origin/master -- src/qtbase.mk src/qtbase-1-fixes.patch`

There will probably be conflicts to resolve for some of the commits you want to revert.

A different way, maybe easier, could be something like this, where the Qt 5 file are set back to the state they were in before the upgrade to 5.14.2:

```
git checkout -b branch_qt_14.1
git diff fe34c8f8^ -- src/qt*.* | git apply --reverse
# restore non-Qt5 files
git checkout src/qt.mk src/qt-*.* src/qtservice.mk
git add -i
git commit -m 'set Qt5 back to v5.14.1'
```
There will probably be problems to fix. You might have to cherry-pick some commits made after fe34c8f8.

**Comment by SanTaiZi-NeZha** [comment]
Thanks!

Qt 5.12.12 Can this be done too?

**Comment by mabrand** [comment]
The last 5.12 version in MXE was 5.12.4. So maybe you could go back to 5.12.4 and then change the version in qtbase.mk to 5.12.12. Then update the CHECKSUM in all the qt*.mk file you need to build.

**Comment by SanTaiZi-NeZha** [comment]
thanks!
