### ISSUE TITLE
binutils fails to build if makeinfo binary is missing

### ISSUE THREAD

**Issue by mbunkus** [mxe/mxe#2853]
Using revision 4a0cd34c67749aa6e16a36b1c235992082a0d2cc on Ubuntu 20.04. `binutils` currently fails to build of the `makeinfo` binary is missing. Installing the `texinfo` package which includes `makeinfo` suffices to let `binutils` compile again.

[Here](https://gist.github.com/mbunkus/77a3bc1effa9589e783cd2390a847911) is the build log. Note that the log is somewhat unclear what the actual error is as it seems that the missing `makeinfo` is solely a warning emitted by `configure`. However, re-running `make` inside the still-existing build directory `tmp-binutils-x86_64-w64-mingw32.static/binutils-2.38.build_` yields [this output](https://gist.github.com/mbunkus/852f6622da1208efc69e975b08272a4a) which is much clearer as it contains both the `makeinfo` invocation and the resulting error message.

I'd say this is a bug in the upstream `binutils` package as `configure`'s output seems to indicate that having `makeinfo` should be optional. That being said, as `binutils` is such a central package to MXE I'd suggest either extending the requirements or carrying a build system fix for the time being.

**Comment by mbunkus** [comment]
Aaaaaaand a look at the `binutils` bug tracker shows that I'm certainly not the only one to notice:

* [Bug 28909](https://sourceware.org/bugzilla/show_bug.cgi?id=28909) - 2.38 tarball (once again) requires makeinfo
* [Bug 28925](https://sourceware.org/bugzilla/show_bug.cgi?id=28925) - Compilation error if set MAKEINFO=missing

**Comment by m-akc** [comment]
yes, same problem.

/home/akc/mxe/tmp-binutils-x86_64-w64-mingw32.static/binutils-2.38/missing: 81: makeinfo: not found
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <http://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <http://www.gnu.org/software/make/>
make[6]: *** [Makefile:1466: doc/as.info] Error 127
make[6]: *** Waiting for unfinished jobs....
