### ISSUE TITLE
LTS Qt5.6.3 support

### ISSUE THREAD

**Issue by lindyang** [mxe/mxe#2857]
To suppoet XP, I choose LTS Qt5.6.3.
after reading [specified QT version](https://github.com/mxe/mxe/issues/2845) and [qt5.12.8](https://github.com/mxe/mxe/issues/2850), I ran
```
git checkout -b branch_qt_5.6.3
git diff 341bca52^ -- src/qt*.* | git apply --reverse
# restore non-Qt5 files
git checkout src/qt.mk src/qt-*.* src/qtservice.mk
git add -i
git commit -m 'set Qt5 to v5.6.0'
```

after that, I almost fixed all the 
src/qt*.*'s `$(PKG)_CHECKSUM`(dowload one by one, and sha256 them) 
and `$(PKG)_URL`,
but I don't know how to fix `src/qt*.patch`, how to use `tools/patch-tool-mxe`?

Sine qt5.6.3 is the LTS that supoort xp, why not make a new branch for Qt5.6.3.
here I post a patch if you need it(checksum and url fixing)

[qt5.6.3_checksum_and_url_fixing.patch.txt](https://github.com/mxe/mxe/files/8915347/qt5.6.3_checksum_and_url_fixing.patch.txt)

**Comment by mabrand** [comment]
You might want to consider using the plug/overlay feature to MXE to do this, rather than a git branch. Look in the "plugins" directory for examples.

**Comment by lindyang** [comment]
I'd read qt-freeze before, but it is based on Qt5.7.1
As you said in [Qt512.8](https://github.com/mxe/mxe/issues/2850)
```
I assume you're starting with the qtbase-1-fixes.patch intended for qtbase 5.12.4, since that was the last 5.12 version built by MXE. Now you need to rebase these patches onto version 5.12.8 if that is what you want to build. tools/patch-tool-mxe might help you.
```
For Qt5.6, the last version is Qt5.6.0(1be3717e), one commit before `upgrade to Qt 5.7.0`,
If I want to update to Qt to 5.6.3 base on 5.6.0, how can I get the correct`qt*.patch`?
Is there some ways I can follow?

**Comment by mabrand** [comment]
If the patches in qtbase-1-fixes.patch for qtbase 5.6.0 don't apply to qtbase 5.6.3 as-is, then you will need to remove obsolete patches and/or rebase the patches onto 5.6.3.

The tool patch-tool-mxe can make this a less tedious. Something like this:

```
# create a temporary git repo from the source tarball
./tools/patch-tool-mxe init qtbase
# apply patches from file as commits in the repository
./tools/patch-tool-mxe import-all qtbase
# if patches did not apply, continue manually
pushd gits/qtbase-opensource-src-5.6.3
git am --show-current-patch | patch -p1 --merge
# manually resolve conflicts if necessary
git add -u
git am --continue
popd
# overwrite the patch file with the commits from the repository
./tools/patch-tool-mxe export
````
