### ISSUE TITLE
qt6-qtmultimedia fails to build for i686-w64-mingw32.shared

### ISSUE THREAD

**Issue by jonaski** [mxe/mxe#2888]
```
/home/jonas/Projects/jonaski-mxe/usr/lib/gcc/i686-w64-mingw32.shared/11.3.0/include/xmmintrin.h:925:1: error: inlining failed in call to 'always_inline' '__m128 _mm_load_ps(const float*)': target specific option mismatch
  925 | _mm_load_ps (float const *__P)
```

https://gist.github.com/jonaski/d1dee7d781778b48df2209d3a0f9ec3c

**Comment by mabrand** [comment]
Any idea if qtmultimedia is even supposed to support 32-bit systems? Maybe this package should just be explicitly excluded for i686 targets. What do you think?

**Comment by mabrand** [comment]
Probably okay now.
See also https://github.com/mxe/mxe/issues/3038
