### ISSUE TITLE
Failed to build package binutils for target i686-w64-mingw32.static!

### ISSUE THREAD

**Issue by efa** [mxe/mxe#2891]
https://gist.github.com/efa/ec2312942f8f9fad05d39b0194455ac5#file-gistfile1-txt
seems happen for all packages, but:
`$ sudo make update`
work updating what is already installed

**Comment by mabrand** [comment]
I doubt you really want "sudo make update". First of all, "sudo" should not be necessary.

"make update" checks for newer versions of packages and updates the version and checksum in the .mk files. There is no magic to reconcile patches to the newer version. The situation you are in is that the current patch in MXE for binutils does not apply to the newer version of binutils.

"make update" is a tool intended for maintainers of MXE. It's pretty much guaranteed to create a lot of follow-up work. If you are interested in updating specific packages, you can use the PKGS variable, for example:
    `make update PKGS="libpng openssl"`

**Comment by efa** [comment]
I opened this Issue is for the following command:
```
/opt/mxe$ sudo make gtk3
[build]       binutils                i686-w64-mingw32.static

Failed to build package binutils for target i686-w64-mingw32.static!
```
while `make update` is only an additional info of what work.

Seems installation of gtk3 (but some other packages try to rebuid and patch binutils in advance) now fail.

And fail also:
`$ sudo make MXE_TARGETS='x86_64-w64-mingw32.static x86_64-w64-mingw32.shared i686-w64-mingw32.static i686-w64-mingw32.shared' gtk3`
What I have to do to install `gtk3` package in all variants (32/64, static/shared)?

What is the last working version of package 'binutils' with current MXE patch?
Is there a command to force package 'binutils' back to the last working with current MXE patch?

Note: when mxe is installed in /opt sudo is necessary as all files are owned by root

**Comment by jonaski** [comment]
If you touch any of the core packages that gcc depends on (binutils, mingw-w64, gmp, isl, mpc, mpfr), you need to re-build everything, so do `make clean` first.
If you want to revert an update, you can do for example: `git checkout src/binutils.mk`.

**Comment by efa** [comment]
so I shouldn't have used `make update` (nor `git pull` used in the past), because it probably damaged the `binutils` package. Now it's best to do a clean and rebuild all, thanks.
BTW: I saw `make update` check all installed packages, and when found a local one older than upstream, it download it and rebuild. Surely I used 2 or 3 times in my current MXE installation history, and in my experience worked well, was only last time I got this trouble.
I just need one way to extract the list of currently installed packages before the clean, to reinstall them, and also to pass to the `make update command PKGS = "pkg1 pkg2 ..."`. Is there such command?

**Comment by efa** [comment]
For the next time, is there a method to update all the installed packages, but exclude the core one?
Does work:
$ make EXCLUDE_PKGS='binutils mingw-w64 gmp isl mpfr mpc gcc' MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static x86_64-w64-mingw32.shared i686-w64-mingw32.shared' update
?
