### ISSUE TITLE
sox: `configure: error: cannot find sndfile`

### ISSUE THREAD

**Issue by jonaski** [mxe/mxe#2904]
Full log: https://gist.github.com/jonaski/983bb89ccdf4bbb5f992cddc244a3cd4

**Comment by mabrand** [comment]
Cannot reproduce since 308e21fd3f1b834a412ea9ae10e0befbefa5f0d7. Suspect this was related to #2903.

**Comment by jonaski** [comment]
Yeah it works now :+1:
