### ISSUE TITLE
Cross compiling under Linux aarm64 for Windows x86_64 is expected to work ? 

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2910]
Hi,

It's more a technical question than a bug. If i install MXE under Linux aarm64 (aka Ubuntu server or Kali) to cross-compile for Windows x86_64, I will be faced to technical problems or not ?

Typically, i plan to buy the new Macbook Pro M2, and run an UTM VM with Linux aarm64. I would to know if the cross compile will be fine or not. Or perhaps it will be better to install MXE on the Mac M2 directly instead Linux.

All guidance will be welcome, and thanks for your efforts to this fantastic project.

Best regards

Gilles Caulier

**Comment by tonytheodore** [comment]
A little while back, I had some success with this `settings.mk`:
```
MXE_USE_CCACHE=no
CC_VER := gcc12
MXE_TARGETS :=  $(addsuffix .$(CC_VER),$(MXE_TARGET_LIST))
MXE_PLUGIN_DIRS = plugins/$(CC_VER)
```
building these pkgs:
```
time make JOBS=6 -j2 -k \
    qt5 qt6 qtwebkit gtkmm3 wxwidgets \
    gst-libav gst-plugins-{good,bad,ugly} \
    sdl2_{gfx,image,mixer,net,ttf} sdl_rwhttp smpeg2 \
    DONT_CHECK_REQUIREMENTS=1 \
    openblas_BUILD_i686-w64-mingw32=
```
and toggling between `make` and `gmake`.

The new release last week (`aarch64-apple-darwin22.1.0`) has broken nearly all of those and has very strange behaviour on the laptop where there is simply no way to keep a build running. There's some strange power management nonsense where it tries to pause the parent `make` process and ends up with detached zombie child processes that never complete. The M1 iMac can at least run builds overnight.

Overall I'd say arm64 shouldn't be a problem per-se, but supporting Darwin gets harder and harder.

Linux in a VM has a good chance working.

**Comment by cgilles** [comment]
Thanks for the feedback. I will buy a new MacBook pro M2 when it will available in few weeks and give a feedback.

My best 

Gilles Caulier

**Comment by tonytheodore** [comment]
UTM could be reasonable, gcc build times on same machine:
```
Ubuntu QEMU ARM 4GB/4CPU gcc11: 7m40.041s
Ubuntu QEMU ARM 4GB/4CPU gcc12: 7m52.616s
Darwin M1 iMac 16GB/8CPU gcc12: 6m41.874s
```

**Comment by cgilles** [comment]
yes i have already experienced UTM on a macbook air M1 and installing Linux Kali arm with excellent results.

I really surprised by the macbook air M1, without a fan, it"s hot but a rock. I recompiled whole digiKam from scratch in 20 minutes where my macbook pro intel i7 with virtual box take around 15 minutes.

definitively, the ARM is the future.

Gilles Caulier

**Comment by tonytheodore** [comment]
It may be worth revisiting `ccache`, it seems to work better on linux:
```
Ubuntu QEMU ARM 4GB/4CPU gcc11 build 1: 7m36.100s
Ubuntu QEMU ARM 4GB/4CPU gcc11 build 2: 3m7.804s
Ubuntu QEMU ARM 4GB/8CPU gcc11 build 3: 2m46.538s
```
