### ISSUE TITLE
Can't find mxe-conf.cmake

### ISSUE THREAD

**Issue by arielm** [mxe/mxe#2911]
It used to be under `/usr/i686-w64-mingw32.static/share/` the last time I worked with MXE on mac a few years ago.

**Comment by tonytheodore** [comment]
If you did `make cc`, the cmake config will not be generated any longer. You need to `make cmake` (or any package that requires it).

**Comment by arielm** [comment]
Thanks. I can see `mxe-conf.cmake` now
