### ISSUE TITLE
Kunbutu 22.04: Curl package do not compile.

### ISSUE THREAD

**Issue by cgilles** [mxe/mxe#2913]
Hi, 

Rebuild from scratch MXE today, curl package do not compile undr Kubuntu 22.04 with all last update done previously. Same error come with another computer using Magiea 7. Log from Kubuntu is attached.

Thanks for your support

Best regards

Gilles Caulier

[curl_x86_64-w64-mingw32.shared.tar.gz](https://github.com/mxe/mxe/files/9900415/curl_x86_64-w64-mingw32.shared.tar.gz)

**Comment by tonytheodore** [comment]
That attachment is a symlink, but I pushed a [fix earlier today](https://github.com/mxe/mxe/commit/50083e19a75a184d30abf4cdcfb7de446921b7ce).

**Comment by cgilles** [comment]
yes it's fixed now... Thanks
Gilles
