### ISSUE TITLE
make cmake fail

### ISSUE THREAD

**Issue by w1hkj** [mxe/mxe#2927]
Please ensure all terminal or log output is correctly enclosed with
triple back-ticks. See the github markdown guide for more details:
    https://guides.github.com/features/mastering-markdown/

If a package fails to build, please upload the entire log file to:
    https://gist.github.com/
    or your pastebin of choice
and put the link here.

**Comment by w1hkj** [comment]
[build]       cmake                   x86_64-pc-linux-gnu

Failed to build package cmake for target x86_64-pc-linux-gnu!
------------------------------------------------------------
---------------------------------------------
Error when bootstrapping CMake:
Problem while running initial CMake
---------------------------------------------
make[1]: *** [Makefile:901: build-only-cmake_x86_64-pc-linux-gnu] Error 11
make[1]: Leaving directory '/home/dave/mxe'
real	0m10.598s
user	0m11.186s
sys	0m2.568s
------------------------------------------------------------
[log]      /home/dave/mxe/log/cmake_x86_64-pc-linux-gnu

make: *** [Makefile:889: /home/dave/mxe/usr/x86_64-pc-linux-gnu/installed/cmake] Error 1

**Comment by mabrand** [comment]
The file log/cmake_x86_64-pc-linux-gnu probably contains some clues about what went wrong.

**Comment by darealshinji** [comment]
cmake failed for me too. Log file said OpenSSL is missing, installing libssl-dev on Ubuntu fixed it for me.
