### ISSUE TITLE
DevIL project dead with replacement available

### ISSUE THREAD

**Issue by TimothyGu** [mxe/mxe#295]
The DevIL package is [dead](http://openil.sourceforge.net/). The project maintainer advises users to use a successor called [ResIL](http://sf.net/p/resil), on the website. However, [ResIL](http://sourceforge.net/p/resil/tickets/) [seems](http://sourceforge.net/p/resil/tickets/1/) [to have](http://sourceforge.net/p/resil/tickets/2/) [lots of](http://sourceforge.net/p/resil/tickets/3/) [packaging errors](http://sourceforge.net/p/resil/tickets/6/), some of them [MinGW-related](http://sourceforge.net/p/resil/tickets/4/).

So, this ticket serves as a reminder for me (or anyone else) to package it.

**Comment by abma** [comment]
version 1.8.0 of DevIL was released!

http://openil.sourceforge.net/
