### ISSUE TITLE
Problem with the path to the libwebp libs

### ISSUE THREAD

**Issue by MarikBohdan** [mxe/mxe#2963]
##  When compiling a project through Qt Creator. Path errors occur libwebp.

> 86_64-w64-mingw32.static/lib/../lib/libwebp.a(libwebpencode_la-picture_csp_enc.o): in function `ImportYUVAFromRGBA':
/media/bohdan/Linux/mxe/tmp-libwebp-x86_64-w64-mingw32.static/libwebp-1.3.0/src/enc/picture_csp_enc.c:508: undefined reference to `SharpYuvInit'

> /media/bohdan/Linux/mxe/usr/bin/x86_64-w64-mingw32.static-ld: /media/bohdan/Linux/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.3.0/../../../../x86_64-w64-mingw32.static/lib/../lib/libwebp.a(libwebpencode_la-picture_csp_enc.o): in function `PreprocessARGB':

> /media/bohdan/Linux/mxe/tmp-libwebp-x86_64-w64-mingw32.static/libwebp-1.3.0/src/enc/picture_csp_enc.c:180: undefined reference to `SharpYuvGetConversionMatrix'

>/media/bohdan/Linux/mxe/usr/bin/x86_64-w64-mingw32.static-ld: /media/bohdan/Linux/mxe/tmp-libwebp-x86_64-w64-mingw32.static/libwebp-1.3.0/src/enc/picture_csp_enc.c:180: undefined reference to `SharpYuvConvert'

> collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.Debug:74: debug/GRWIND.exe] Error 1
make[1]: Leaving directory '/home/bohdan/Programs/GRWIND/build-GRWIND-DesktopWindowsQT-Debug'
make: *** [Makefile:45: debug] Error 2
14:05:30: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project GRWIND (kit: DesktopWindowsQT)
The kit DesktopWindowsQT has configuration issues which might be the root cause for this problem.
When executing step "Make" 

Function "ImportYUVAFromRGBA","PreprocessARGB","SharpYuvGetConversionMatrix" : Searches the temporary folder (tmp-libwebp-x86_64-w64-mingw32.static).

# Help fix it.

**Comment by MarikBohdan** [comment]
Everything works. Thank you

**Comment by poltpolt** [comment]
I got similar error with current version

/mnt/os0home/polrus/dev/mxe/usr/bin/i686-w64-mingw32.static-ld: /home/polrus/dev/mxe/usr/i686-w64-mingw32.static/lib/libwebp.a(libwebpencode_la-picture_csp_enc.o): in function `ImportYUVAFromRGBA':
/mnt/os0home/polrus/dev/mxe/tmp-libwebp-i686-w64-mingw32.static/libwebp-1.4.0/src/enc/picture_csp_enc.c:509: undefined reference to `SharpYuvInit'
/mnt/os0home/polrus/dev/mxe/usr/bin/i686-w64-mingw32.static-ld: /home/polrus/dev/mxe/usr/i686-w64-mingw32.static/lib/libwebp.a(libwebpencode_la-picture_csp_enc.o): in function `PreprocessARGB':
/mnt/os0home/polrus/dev/mxe/tmp-libwebp-i686-w64-mingw32.static/libwebp-1.4.0/src/enc/picture_csp_enc.c:181: undefined reference to `SharpYuvGetConversionMatrix'
/mnt/os0home/polrus/dev/mxe/usr/bin/i686-w64-mingw32.static-ld: /mnt/os0home/polrus/dev/mxe/tmp-libwebp-i686-w64-mingw32.static/libwebp-1.4.0/src/enc/picture_csp_enc.c:181: undefined reference to `SharpYuvConvert'
/mnt/os0home/polrus/dev/mxe/usr/bin/i686-w64-mingw32.static-ld: /home/polrus/dev/mxe/usr/i686-w64-mingw32.static/lib/libfreetype.a(sfnt.o): in function `woff2_decompress':
/mnt/os0home/polrus/dev/mxe/tmp-freetype-i686-w64-mingw32.static/freetype-2.13.3/src/sfnt/sfwoff2.c:319: undefined reference to `BrotliDecoderDecompress'
