### ISSUE TITLE
Qt6 supported image formats not as in docs

### ISSUE THREAD

**Issue by martinwag** [mxe/mxe#2972]
According to Qt6 doc, a standard package should support a defined set of image formats (https://doc.qt.io/qt-6.4/qimagereader.html#supportedImageFormats). When compiling a binary with mxe, and printing the list from 
`QImageReader::supportedImageFormats();`
I get "bmp, pbm, pgm, png, ppm, xbm, xpm" (essentially missing jpg, gif and svg formats). I've had a look at the Qt docs and the mxe Qt6 Makefiles, but can't find where the supported formats are set up.

Thanks for your help!

**Comment by martinwag** [comment]
Found the solution. For the missing image formats, one needs extra dll files. When using CMake for installer packaging, those dlls are missing in the install(FILES $<TARGET_FILE:Qt6::Core> ... ) package command. 
Unfortunately, the missing dlls (and their sub-dependencies) are not reported as missing when the program starts, they are either there and in the correct folders or just plain ignored.
- jpg: you need "libjpeg-9.dll" in your search path. Add qjpeg.dll in subfolder "plugins\imageformats" to your search path. This needs to be in the subfolder or it is ignored.
- gif:  Add qgif.dll in subfolder "plugins\imageformats" to your search path.

**Comment by mabrand** [comment]
Yes, you have to make sure the plugins are available at runtime so they can  loaded. For static builds, the plugins have to be linked statically by the way.
