### ISSUE TITLE
error compiling poppler-qt6

### ISSUE THREAD

**Issue by txeyen** [mxe/mxe#2977]
I just tried to compile poppler-qt6 in a new mxe installation.

First i make qt6 (without problems)
I compiled some independent qt software with it.
But i need poppler now and i got an errror.
I just make a fresh mxe install. First i did:
make qt6
and then:
make poppler-qt6

This is the error:

Make Error at /samba/projects/compilar/mxe/usr/i686-w64-mingw32.static/qt6/lib/cmake/Qt6Gui/Qt6QICNSPluginTargets.cmake:61 (set_target_properties):
  The link interface of target "Qt6::QICNSPlugin" contains:

    Qt::Core

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

**Comment by txeyen** [comment]
I already used poppler-qt5 without problems.
And i tried it and works fine.

**Comment by darealshinji** [comment]
I think this is the issue you're running into: https://github.com/mxe/mxe/pull/2975

A quick one-liner fix:
``` sh
for fmt in ICNS Jp2 Mng Tga Tiff Wbmp Webp ; do sed -i 's|LINK_ONLY:Qt::|LINK_ONLY:Qt6::|g' /samba/projects/compilar/mxe/usr/i686-w64-mingw32.static/qt6/lib/cmake/Qt6Gui/Qt6Q${fmt}PluginTargets.cmake; done
```

**Comment by txeyen** [comment]
Solved.
Thanks
