### ISSUE TITLE
failure building aubio

### ISSUE THREAD

**Issue by lopippo** [mxe/mxe#2997]
Greetings,

I did a git clone today and the proceeded with 

`make MXE_TARGETS='x86_64-w64-mingw32.shared'`

After a long while, the build fails with the following error:

[build]       aubio                   x86_64-w64-mingw32.shared

Failed to build package aubio for target x86_64-w64-mingw32.shared!
------------------------------------------------------------
  File "/home/rusconi/devel/mxe/tmp-aubio-x86_64-w64-mingw32.shared/aubio-0.4.2.build_/waf-1.8.17/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Utils.py", line 87, in readf
    f=open(fname,m)
      ^^^^^^^^^^^^^
ValueError: invalid mode: 'rUb'
make[1]: *** [Makefile:901: build-only-aubio_x86_64-w64-mingw32.shared] Error 2
make[1]: Leaving directory '/home/rusconi/devel/mxe'

The full log is here:

https://paste.debian.net/1283663/

Since I am new to MXE, I wanted to check the file and put some debugging trace code. So I opened the Utils.py file from the path provided above. I put some print()-based debug statements in the relevant function and ran make again. But only to discover that the directory was overwritten anew probably from the pkg/waf-1.8.17.tar.bz2 archive.

So, I unpackacked that archive in a tmp dir, edited the file, saved it, make a new tar.bz2 archive, copied it to pkg/, computed the shasum for it and edited src/waf.mk accordingly. Then I ran make again. But that did not work.

So, my question is "how should one proceed with debugging software in this kind of situation?".

Thank you for your enlightening comments !
Sincerely,
Filippo

**Comment by lopippo** [comment]
One comment on my post above:

I understand that the waf package is unpacked in real build time of the aubio package. What I cannot understand is where that waf package comes from. I have modified the waf package as detailed above, but upon building the aubio package it seems that the new waf package I made is not used...

**Comment by lopippo** [comment]
Ah ah, now starting to get it: the src/aubio.mk file has these lines:

define $(PKG)_UPDATE
    $(WGET) -q -O- 'https://www.aubio.org/download' | \
    $(SED) -n 's,.*aubio-\([0-9][^>]*\)\.tar.*,\1,p' | \
    head -1
endef

and also this line:

$(PKG)_DEPS     := cc ffmpeg fftw jack libsamplerate libsndfile $(BUILD)~waf

So it is like the package is downloaded real time by the aubio package ? 
Is that correct ?

**Comment by lopippo** [comment]
After much research, I now understand where the .waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a comes from: waf itself, which is a build system (which I did not know). Apparently, waf in the setup of aubio is downloaded from the net and unpacks itself in this hidden directory. 

From there, I am stuck...

**Comment by revelator** [comment]
seems waf uses python2 after changing the default python i can build it,

**Comment by lopippo** [comment]
Thank you, revelator. I resolved not building it (it took me to understand how to skip packages from the main build) and I could go along and beautifully create cross-builds of complex scientific software ! Cheers
