### ISSUE TITLE
zlib maintainers dgaf about non-bleeding-edge versions

### ISSUE THREAD

**Issue by fiesh** [mxe/mxe#3006]
As of today, it seems `zlib` is no longer supplying their version `1.2.13` in favor of `1.3`, which was released 4 days ago.  This means building MXE's `zlib` package which is still on `1.2.13` fails as all downloads 404 out.

I'd therefore request setting

```
$(PKG)_URL_2    := https://github.com/madler/zlib/releases/download/v$($(PKG)_VERSION)/$($(PKG)_FILE)
```

in `src/zlib.mk`.  At least this made things work again for us.

Or maybe allow setting `_URL_n` for any value of `n`, so that arbitrarily many fallback servers are supported, and make this `_URL_3`?

**Comment by fatduckling** [comment]
Thanks so much for posting this!

I was seeing lot of errors in the zlib logs so I'm glad you found a workaround to this!

```
2023-08-22 23:51:21 ERROR 404: Not Found.
--2023-08-22 23:51:21--  http://d1yihgixbnrglp.cloudfront.net/zlib%2D1%2E2%2E13%2Etar%2Exz_d14c38e313afc35a9a8760dadf26042f51ea0f5d154b0630a31da0540107fb98
Reusing existing connection to d1yihgixbnrglp.cloudfront.net:80.
HTTP request sent, awaiting response... 404 Not Found
2023-08-22 23:51:22 ERROR 404: Not Found.
Download failed!
```

**Comment by magesep** [comment]
Thanks so much!!!I was wondering why I kept returning 404, it turned out to be because of this...

**Comment by fatduckling** [comment]
Should we create a PR to help other people having the same issue?

**Comment by fiesh** [comment]
> Should we create a PR to help other people having the same issue?

Sounds like a good idea, given how this quickly garnered some responses.  Will you go ahead?

**Comment by fatduckling** [comment]
Ok I just created a PR, take a look https://github.com/mxe/mxe/pull/3007
Thanks

**Comment by tonytheodore** [comment]
> Or maybe allow setting _URL_n for any value of n, so that arbitrarily many fallback servers are supported, and make this _URL_3?

This is an evergreen issue, we have two main urls and three mirrors. We don't really want to add more manually-specified fallbacks.

I'm not sure why the checksum-suffixed version wasn't on the mirrors, but it will now try the [unsuffixed version also](https://github.com/mxe/mxe/commit/30296d9c913549063490e8c67e78449dc94e3800).

**Comment by tonytheodore** [comment]
> I'm not sure why the checksum-suffixed version wasn't on the mirrors

Some combination of:
  - timing on full weekly refresh of https://mirror.mxe.cc/pkg
  - new (ish, 2022-04-24) de-dupe [based on checksum](https://github.com/mxe/mxe/commit/fddb7c15e887cf23645879359b51f7225e203ed4)
