### ISSUE TITLE
Meson fails to build

### ISSUE THREAD

**Issue by nschlia** [mxe/mxe#3009]
The previous builds all failed with...

> 
> Failed to build package glib for target x86_64-pc-linux-gnu!
> ------------------------------------------------------------
> tmp-glib-x86_64-pc-linux-gnu/glib-2.70.2/meson.build:2002:9: ERROR: could not get https://sourceforge.net/projects/pcre/files/pcre/8.37/pcre-8.37.tar.bz2 is the internet available?
> WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
> make[1]: *** [Makefile:903: build-only-glib_x86_64-pc-linux-gnu] Fehler 1
> 

The URL is incorrect; it should be https://kumisystems.dl.sourceforge.net/project/pcre/pcre/8.37/pcre-8.37.tar.bz2

See [meson-log.txt](https://github.com/mxe/mxe/files/12568584/meson-log.txt)

**Comment by tonytheodore** [comment]
> is the internet available?

Networking is disabled during the build phase to ensure reproducible builds.

Native `pcre` is usually installed as part of the prerequisites, try this:
```diff
diff --git a/src/glib.mk b/src/glib.mk
index db09f764..d296c791 100644
--- a/src/glib.mk
+++ b/src/glib.mk
@@ -11,7 +11,7 @@ $(PKG)_FILE     := glib-$($(PKG)_VERSION).tar.xz
 $(PKG)_URL      := https://download.gnome.org/sources/glib/$(call SHORT_PKG_VERSION,$(PKG))/$($(PKG)_FILE)
 $(PKG)_DEPS     := cc meson-wrapper dbus gettext libffi libiconv pcre zlib $(BUILD)~$(PKG)
 $(PKG)_TARGETS  := $(BUILD) $(MXE_TARGETS)
-$(PKG)_DEPS_$(BUILD) := cc meson-wrapper gettext libffi libiconv zlib
+$(PKG)_DEPS_$(BUILD) := cc meson-wrapper gettext libffi libiconv pcre zlib

 define $(PKG)_UPDATE
     $(WGET) -q -O- 'https://gitlab.gnome.org/GNOME/glib/tags' | \
```

**Comment by e2002e** [comment]
This worked for me, but I had to install pcre from apt
