### ISSUE TITLE
Allow -debug targets

### ISSUE THREAD

**Issue by djandruczyk** [mxe/mxe#301]
It would be valuable to be able to define a "debug" target.in settings.mk i.e. x86_64-w64-mingw32.shared-debug alongside a normal non-debug target x86_64-w64-mingw32.shared i686-w64-mingw32.static.  Ideally the debug target would add "-g" to cflags, and "--enable-debug" to packages that have that option.   This make things a bit more useful for debugging on the windows side if the symbols are available to GDB for cases where stuff breaks on windows (esp 64 bit).

**Comment by tonytheodore** [comment]
There's almost no generic way to achieve this
