### ISSUE TITLE
Building GTK3 Fails

### ISSUE THREAD

**Issue by ken3b** [mxe/mxe#3011]
Hi, I was attempting to build all on wsl ubuntu when I encountered this error when building gtk3 for i686-w64-mingw32

https://pastebin.com/fejZ75gh

It seems to not be able to find python properly. But I do not know how to point it to the proper location as the file it is failing on seems to be auto generated.

**Comment by tonytheodore** [comment]
This looks suspicious:
```
/usr/bin/env: ‘python3\r’: No such file or directory
```
I'm guessing it has something to do with line endings on WSL, especially the [use of `/mnt`](https://mxe.cc/#requirements-wsl).

**Comment by ken3b** [comment]
I did not see that subsection when looking over the requirements. Thanks!
