### ISSUE TITLE
qt4 build fails

### ISSUE THREAD

**Issue by walterschneider** [mxe/mxe#3034]
Building qt4 fails.

`make MXE_TARGETS=x86_64-w64-mingw32.static qt`

```
kernel/qapplication_win.cpp:2638:13: error: 'GESTUREINFO' was not declared in this scope
 2638 |             GESTUREINFO gi;
      |             ^~~~~~~~~~~
kernel/qapplication_win.cpp:2639:21: error: 'gi' was not declared in this scope
 2639 |             memset(&gi, 0, sizeof(GESTUREINFO));
 ```

Tested with current master (81fcf6ee8962b4721406ab0f850c74d1febe9873) as well as build-2022-04-09.

Full log:
https://gist.github.com/walterschneider/d852c09a77581dd28d3228aec8214907

**Comment by jakint0sh** [comment]
Yay, it isn't just me for once!  I have the exact same error.  Is there a fix?

**Comment by mabrand** [comment]
should be fixed now
