### ISSUE TITLE
Incorrectly named icu4c libraries: Failed to build package icu4c for target i686-w64-mingw32.static

### ISSUE THREAD

**Issue by nolimbsdotdev** [mxe/mxe#3050]
Doing make qtbase fails at:

```
[build]       icu4c                   i686-w64-mingw32.static
Failed to build package icu4c for target i686-w64-mingw32.static!
```

Assuming mxe is in ```/build/mxe```...

The log reveals that it can't find libs 

```
/build/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -licuio: No such file or directory
/build/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -licuin: No such file or directory
/build/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -licuuc: No such file or directory
/build/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -licudt: No such file or directory
```

but looking in ```/build/mxe/tmp-icu4c-i686-w64-mingw32.static/icu.build_/lib/``` and ```/build/mxe/tmp-icu4c-i686-w64-mingw32.static/icu.build_/stubdata/``` reveals that the libs are actually named libsicuio.a, libsicuin.a, libsicuuc.a, libsicudt.a (notice the extra "s" ).

I was able to get icu4c to compile by running a script that used rsync to create copies with the expected name. A copy of the libs also has to go in ```/build/mxe/usr/lib/gcc/i686-w64-mingw32.static/11.4.0 ```in order to progress.

**Comment by sinetek** [comment]
I am also running into this issue.

```
$ ls tmp-icu4c-i686-w64-mingw32.static/icu.build_/lib
libsicuin.a  libsicuio.a  libsicutu.a  libsicuuc.a
```

**Comment by yurkis** [comment]
Confirm. Faced the same issue.

**Comment by mabrand** [comment]
That seems to fix it. Please reopen if necessary.
