### ISSUE TITLE
How to use lib compiled by msvc?

### ISSUE THREAD

**Issue by Ucag** [mxe/mxe#3051]
hi, thanks a lot for creating MXE. I'm now using it to develop a media player on ubuntu for windows. However, when dealing with some dependences, I encountered some problems.

In my project, I need to use `onnxruntime`  which is a lib can only be compiled on windows. Here comes the problem, I can get the lib compiled by windows, but how can I include it in my project and build it for windows? More specifically, how can I use the `.lib` and the `.dll` files of `onnxruntime` ?

Thanks a lot for help.

**Comment by mabrand** [comment]
See https://sourceforge.net/p/mingw-w64/wiki2/gendef/
In MXE, you can build gendef with "make gendef".
