### ISSUE TITLE
Failed to build package librsvg for target x86_64-w64-mingw32.static

### ISSUE THREAD

**Issue by 3813127458** [mxe/mxe#3061]
Failed to build package **librsvg** for target x86_64-w64-mingw32.static

Error Log:

[librsvg_x86_64-w64-mingw32.static.zip](https://github.com/mxe/mxe/files/15040549/librsvg_x86_64-w64-mingw32.static.zip)

/home/werner/Downloads/mxe/usr/bin/x86_64-w64-mingw32.static-ld: /home/werner/Downloads/mxe/usr/x86_64-w64-mingw32.static/lib/../lib/libcairo.a(win32_cairo-dwrite-font.cpp.obj):cairo-dwrite-font.cpp:(.rdata$_ZTI8IUnknown[_ZTI8IUnknown]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/home/werner/Downloads/mxe/usr/bin/x86_64-w64-mingw32.static-ld: /home/werner/Downloads/mxe/usr/x86_64-w64-mingw32.static/lib/../lib/libcairo.a(win32_cairo-dwrite-font.cpp.obj):cairo-dwrite-font.cpp:(.rdata$_ZTI27ID2D1SimplifiedGeometrySink[_ZTI27ID2D1SimplifiedGeometrySink]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/home/werner/Downloads/mxe/usr/bin/x86_64-w64-mingw32.static-ld: /home/werner/Downloads/mxe/usr/x86_64-w64-mingw32.static/lib/../lib/libcairo.a(win32_cairo-dwrite-font.cpp.obj):cairo-dwrite-font.cpp:(.rdata$_ZTI16GeometryRecorder[_ZTI16GeometryRecorder]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:903: build-only-librsvg_x86_64-w64-mingw32.static] Error 1
make[1]: Leaving directory '/home/werner/Downloads/mxe'
real    0m20,199s
user    0m36,529s
sys     0m5,832s

[log]      /home/werner/Downloads/mxe/log/librsvg_x86_64-w64-mingw32.static

System Info:

Operating System: openSUSE Tumbleweed 20240417
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.6-1-default (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i7-4600U CPU @ 2.10GHz
Memory: 15,3 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4400

**Comment by mabrand** [comment]
Thanks for the report. That fixes it for me.
