### ISSUE TITLE
Unable to Cross-Compile Using MXE on Ubuntu 24.04 

### ISSUE THREAD

**Issue by SiddaramMavinamar** [mxe/mxe#3080]
please check below issue
mportant Information
mpv version: v0.38.0
Platform version: Ubuntu 24.04
Meson version: 1.3.2
Reproduction Steps
git clone https://github.com/mxe/mxe.git
cd mxe
echo "JOBS := 4" >> settings.mk
echo "MXE_TARGETS := x86_64-w64-mingw32.static" >> settings.mk
make gcc ffmpeg libass jpeg lua luajit
export PATH=/mxe/usr/bin:$PATH
git clone https://github.com/mpv-player/mpv.git
cd mpv
meson setup build --cross-file crossfile.txt -Dlibmpv=true

Expected Behavior
The build process should complete successfully with all dependencies properly resolved and compiled, resulting in a functional cross-compiled version of MPV.

Actual Behavior
The build process fails with the error indicating that the libplacebo dependency is not found. Attempts to use pkg-config and cmake to resolve this dependency have been unsuccessful.

Observed that MXE does not have a makefile for libplacebo.
Tried to link libplacebo manually but encountered the same error.

https://github.com/mpv-player/mpv/issues/14259

**Comment by mabrand** [comment]
A pull request for libplacebo would be welcome.
For general help, please use discussions.

**Comment by SiddaramMavinamar** [comment]
> A pull request for libplacebo would be welcome. For general help, please use discussions.

I have done full request of liblacebo but mxe don't have make file in source what is the way to link it with mxe, I have  already liblacebo library in my root

**Comment by mabrand** [comment]
Not a "full request", but a "pull request". In other words, you can propose your libplacebo.mk for merging into MXE.

**Comment by SiddaramMavinamar** [comment]
> Not a "full request", but a "pull request". In other words, you can propose your libplacebo.mk for merging into MXE.

Thank you for you suggestion
I have tried all possible way and shared here 
And i created Libplacebo.mk I have set a rule and placed it into /mxe/source 

Please don't mind if you have any libplacebo.mk, could you pls share it would be helpful and appreciated

My libplacebo.mk might have error

**Comment by SiddaramMavinamar** [comment]
@mabrand
can you please share the make file for libplacebo
