### ISSUE TITLE
Update ffmpeg to 7.0.2 please

### ISSUE THREAD

**Issue by oomek** [mxe/mxe#3098]
I was trying to make a ffmpeg 7.0.2 package myself but there is one missing dependency
`mxe-x86-64-w64-mingw32.static-brotli` which is not accessible with apt-get
I need deb packages to build my app with MXE on Github CI, otherwise it takes hours instead of minutes.

**Comment by mabrand** [comment]
https://github.com/mxe/mxe/pull/3092
