### ISSUE TITLE
can't build static qt5: "Library not found: atomic"

### ISSUE THREAD

**Issue by trufanov-nok** [mxe/mxe#3099]
Hi,
I'm executing:
```
cd ./mxe

make qt5   MXE_TARGETS=x86_64-w64-mingw32.shared -j8
make eigen MXE_TARGETS=x86_64-w64-mingw32.shared -j8
make proj  MXE_TARGETS=x86_64-w64-mingw32.shared -j8

make qt5   MXE_TARGETS=x86_64-w64-mingw32.static -j8
make eigen MXE_TARGETS=x86_64-w64-mingw32.static -j8
make proj  MXE_TARGETS=x86_64-w64-mingw32.static -j8
```

shared build is fine. static fails at 
`make qt5   MXE_TARGETS=x86_64-w64-mingw32.static -j8` with the following:

```
cd '/home/user/project/mxe/tmp-qtbase-x86_64-w64-mingw32.static/qtbase-everywhere-src-5.15.15.build_.test-cmake' && 'x86_64-w64-mingw32.static-cmake' -DPKG=qtbase -DPKG_VERSION=5.15.15 '/home/user/project/mxe/src/cmake/test'
== Using MXE wrapper: /home/user/project/mxe/usr/bin/x86_64-w64-mingw32.static-cmake
     - cmake version 3.30.3
     - warnings for unused CMAKE_POLICY_DEFAULT variables can be ignored
== Using MXE toolchain: /home/user/project/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
== Using MXE runresult: /home/user/project/mxe/usr/share/cmake/modules/TryRunResults.cmake
== Adding "-DCMAKE_BUILD_TYPE=Release"
loading initial cache file /home/user/project/mxe/usr/share/cmake/modules/TryRunResults.cmake
[0mCMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

[0m
-- The C compiler identification is GNU 11.5.0
-- The CXX compiler identification is GNU 11.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/user/project/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/user/project/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
[31mCMake Error at /home/user/project/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:91 (message):
  Library not found: atomic
Call Stack (most recent call first):
  /home/user/project/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:271 (_qt5_Gui_process_prl_file)
  /home/user/project/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:225 (find_package)
  /home/user/project/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /home/user/project/mxe/src/qtbase-test.cmake:14 (find_package)
  CMakeLists.txt:18 (include)

[0m
-- Configuring incomplete, errors occurred!
make[1]: *** [Makefile:903: build-only-qtbase_x86_64-w64-mingw32.static] Error 1
make[1]: Leaving directory '/home/user/project/mxe'
```

and I couldn't find any way to workaround it.
Any ideas?

The mxe is current master branch
System is:
```
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-41-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3632QM CPU @ 2.20GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4000
Manufacturer: LENOVO
Product Name: Lenovo G780
System Version: Lenovo G780
```

I tested it with one more debian-based system with same result.

Didn't check if it's compillation order dependant yet.

**Comment by t0mmy742** [comment]
Hi,
Build of Qt5 failed since GLib released version 2.81.0.
Seems related to libatomic linked with it ?

**Comment by trufanov-nok** [comment]
Hm, it seems libatomic is a part of gcc and successfully built at 
./usr/lib/gcc/x86_64-w64-mingw32.static/11.5.0/libatomic.a

It even succesfullty tested and used by qt5base. But then it can't be found by QtWidgets...

**Comment by MennoSaey** [comment]
checking out the previous commit is a workaround that worked for me.

**Comment by mabrand** [comment]
> checking out the previous commit is a workaround that worked for me.

Which commits works?

**Comment by MennoSaey** [comment]
> > checking out the previous commit is a workaround that worked for me.
> 
> Which commits works?

i used commit with hash 2a58daf6

**Comment by jpsdr** [comment]
Hi.
I have the same issue, even with the 5.15.15 commit, as you can see.
`# setup cmake toolchain and test
echo 'set(CMAKE_SYSTEM_PREFIX_PATH "/home/jpsdr/MKVToolNixQT5/mxe/usr/x86_64-w64-mingw32.static/qt5" )' > '/home/jpsdr/MKVToolNixQT5/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.d/qtbase.cmake'
# test cmake
mkdir '/home/jpsdr/MKVToolNixQT5/mxe/tmp-qtbase-x86_64-w64-mingw32.static/qtbase-everywhere-src-5.15.15.build_.test-cmake'
cd '/home/jpsdr/MKVToolNixQT5/mxe/tmp-qtbase-x86_64-w64-mingw32.static/qtbase-everywhere-src-5.15.15.build_.test-cmake' && 'x86_64-w64-mingw32.static-cmake' -DPKG=qtbase -DPKG_VERSION=5.15.15 '/home/jpsdr/MKVToolNixQT5/mxe/src/cmake/test'
== Using MXE wrapper: /home/jpsdr/MKVToolNixQT5/mxe/usr/bin/x86_64-w64-mingw32.static-cmake
     - cmake version 3.30.4
     - warnings for unused CMAKE_POLICY_DEFAULT variables can be ignored
== Using MXE toolchain: /home/jpsdr/MKVToolNixQT5/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
== Using MXE runresult: /home/jpsdr/MKVToolNixQT5/mxe/usr/share/cmake/modules/TryRunResults.cmake
== Adding "-DCMAKE_BUILD_TYPE=Release"
loading initial cache file /home/jpsdr/MKVToolNixQT5/mxe/usr/share/cmake/modules/TryRunResults.cmake
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 13.3.0
-- The CXX compiler identification is GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/jpsdr/MKVToolNixQT5/mxe/usr/bin/x86_64-w64-mingw32.static-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/jpsdr/MKVToolNixQT5/mxe/usr/bin/x86_64-w64-mingw32.static-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /home/jpsdr/MKVToolNixQT5/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:91 (message):
  Library not found: atomic
Call Stack (most recent call first):
  /home/jpsdr/MKVToolNixQT5/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:271 (_qt5_Gui_process_prl_file)
  /home/jpsdr/MKVToolNixQT5/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:225 (find_package)
  /home/jpsdr/MKVToolNixQT5/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /home/jpsdr/MKVToolNixQT5/mxe/src/qtbase-test.cmake:14 (find_package)
  CMakeLists.txt:18 (include)


-- Configuring incomplete, errors occurred!
make[1]: *** [Makefile:903 : build-only-qtbase_x86_64-w64-mingw32.static] Erreur 1
make[1] : on quitte le répertoire « /home/jpsdr/MKVToolNixQT5/mxe »

real	17m15,188s
user	146m29,356s
sys	9m1,167s
`

**Comment by Tomblarom** [comment]
I have exactly the same issue. I'm compiling on WSL2 Ubuntu. mxe is located in `/opt/mxe`, so not on the NTFS windows partition `/mnt/c/...`.

```
# setup cmake toolchain and test
echo 'set(CMAKE_SYSTEM_PREFIX_PATH "/opt/mxe2/usr/i686-w64-mingw32.static/qt5" )' > '/opt/mxe2/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.d/qtbase.cmake'
# test cmake
mkdir '/opt/mxe2/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.15.build_.test-cmake'
cd '/opt/mxe2/tmp-qtbase-i686-w64-mingw32.static/qtbase-everywhere-src-5.15.15.build_.test-cmake' && 'i686-w64-mingw32.static-cmake' -DPKG=qtbase -DPKG_VERSION=5.15.15 '/opt/mxe2/src/cmake/test'
== Using MXE wrapper: /opt/mxe2/usr/bin/i686-w64-mingw32.static-cmake
     - cmake version 3.30.5
     - warnings for unused CMAKE_POLICY_DEFAULT variables can be ignored
== Using MXE toolchain: /opt/mxe2/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.cmake
== Using MXE runresult: /opt/mxe2/usr/share/cmake/modules/TryRunResults.cmake
== Adding "-DCMAKE_BUILD_TYPE=Release"
loading initial cache file /opt/mxe2/usr/share/cmake/modules/TryRunResults.cmake
[0mCMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

[0m
-- The C compiler identification is GNU 11.5.0
-- The CXX compiler identification is GNU 11.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/mxe2/usr/x86_64-pc-linux-gnu/bin/i686-w64-mingw32.static-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/mxe2/usr/x86_64-pc-linux-gnu/bin/i686-w64-mingw32.static-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
[31mCMake Error at /opt/mxe2/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:91 (message):
  Library not found: atomic
Call Stack (most recent call first):
  /opt/mxe2/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:271 (_qt5_Gui_process_prl_file)
  /opt/mxe2/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:225 (find_package)
  /opt/mxe2/usr/i686-w64-mingw32.static/qt5/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /opt/mxe2/src/qtbase-test.cmake:14 (find_package)
  CMakeLists.txt:18 (include)

[0m
-- Configuring incomplete, errors occurred!
make[1]: *** [Makefile:903: build-only-qtbase_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory '/opt/mxe2'

real	25m22.348s
user	120m45.179s
sys	9m13.452s
```

**Comment by mabrand** [comment]
The failure happened when testing building with cmake. dc30c014a3bdb02043dc4e261ff53b85c37b7a86 fixes it for me.
