### ISSUE TITLE
qt5 build fails

### ISSUE THREAD

**Issue by jomajm** [mxe/mxe#3112]
on commit a31368b037221d56bcfcfd8c546b89adffe9ea04

command 
`make DEFAULT_MAX_JOBS=16 MXE_TARGETS=x86_64-w64-mingw32.static MXE_PLUGIN_DIRS=plugins/gcc14 cmake libmysqlclient libssh2 libusb1 qt5`

fails with:
**Library not found: atomic**

**Comment by mabrand** [comment]
That's not much to go on. Please check the package-specific output file in the logs directory for more detail about the error.

**Comment by mabrand** [comment]
Looks like a duplicate of https://github.com/mxe/mxe/issues/3099. Please continue the discussion there.
