### ISSUE TITLE
Build fails for package luabind on Ubuntu 24.04 (patch included)

### ISSUE THREAD

**Issue by BastyCDGS** [mxe/mxe#3127]
When I try to build luabind on Ubuntu 24.04, it fails with a compile error. Log file is in gist:
https://gist.github.com/BastyCDGS/00548fa33cdf4430dd8da5c364d777d1

I have attached a fix which solves the problem for me:
[luabind-8-fixes.patch.zip](https://github.com/user-attachments/files/17646357/luabind-8-fixes.patch.zip)

**Comment by koppi** [comment]
@mabrand can you please review this patch and add it to mxe/master ?
