### ISSUE TITLE
DLL files in wrong location

### ISSUE THREAD

**Issue by gcoco** [mxe/mxe#393]
## Introduction

In MXE, shared DLLs are supposed to be installed to bin/ directory, while the import libraries (.dll.a) are supposed to be installed to regular lib/ directory. This is automatically done for autotools projects using libtool; however some projects do not follow this scheme.

Two classes of problematic packages exist: packages whose import libraries are built and installed, and packages only whose DLL's are installed. The first one is easy to fix: you can just use a "hack" that moves the DLL's into bin/.

The second one is harder to fix, because you have to first get import libraries to be built and installed too, and that requires additional patching. Of course, you can say, “Why don't we just _copy_ the DLL to bin/ so that the linker can find the library to link too?” And for that, I really don't have an answer to right now.

## List of issues
(checked -> fixed)

### Import libs are installed
- [x] ICU libs
- [x] Assimp
- [x] Boost libs (See #375)
- [x] gcc libs

### Import libs are not installed
- [x] OpenBLAS
- [x] PortMIDI
- [x] PostgreSQL
- [ ] Rubberband
- [ ] Vamp SDK libs
- ~~[ ]XML-RPC~~ See 58f0234a56612b209e8df858a38c14e0d0a96e6f

## Original Description
When doing shared builds, there are multiple dll files being installed into the {mxe}/usr/{triplet}.shared/lib directory and not into the {mxe}/usr/{triplet}.shared/bin directory. I see what looks to be the PostgreSQL (libpq.dll) as well as a large number of files that look like they are from ICU.
There are also DLL's from the gcc build (4.9.0) that are not moved {mxe}/lib/gcc/{triplet}.shared/4.9.0/ into the {mxe}/usr/{triplet}.shared/bin directory. For me I needed the libstdc++-6.dll file for my application.

After a full x86_64-w64-mingw32.shared build, the DLLs incorrectly installed to lib/ are:

```
timothy_gu@ubuntu-lenovo:~/mxe/usr/x86_64-w64-mingw32.shared/lib$ ls | grep '\.dll' | grep -v '\.a'
icudt52.dll
icudt.dll
icuin52.dll
icuin.dll
icuio52.dll
icuio.dll
icule52.dll
icule.dll
iculx52.dll
iculx.dll
icutest52.dll
icutest.dll
icutu52.dll
icutu.dll
icuuc52.dll
icuuc.dll
libassimp.dll
libboost_atomic-mt-d.dll
libboost_atomic-mt.dll
libboost_chrono-mt-d.dll
libboost_chrono-mt.dll
libboost_date_time-mt-d.dll
libboost_date_time-mt.dll
libboost_filesystem-mt-d.dll
libboost_filesystem-mt.dll
libboost_graph-mt-d.dll
libboost_graph-mt.dll
libboost_iostreams-mt-d.dll
libboost_iostreams-mt.dll
libboost_locale-mt-d.dll
libboost_locale-mt.dll
libboost_math_c99f-mt-d.dll
libboost_math_c99f-mt.dll
libboost_math_c99l-mt-d.dll
libboost_math_c99l-mt.dll
libboost_math_c99-mt-d.dll
libboost_math_c99-mt.dll
libboost_math_tr1f-mt-d.dll
libboost_math_tr1f-mt.dll
libboost_math_tr1l-mt-d.dll
libboost_math_tr1l-mt.dll
libboost_math_tr1-mt-d.dll
libboost_math_tr1-mt.dll
libboost_prg_exec_monitor-mt-d.dll
libboost_prg_exec_monitor-mt.dll
libboost_program_options-mt-d.dll
libboost_program_options-mt.dll
libboost_random-mt-d.dll
libboost_random-mt.dll
libboost_regex-mt-d.dll
libboost_regex-mt.dll
libboost_serialization-mt-d.dll
libboost_serialization-mt.dll
libboost_signals-mt-d.dll
libboost_signals-mt.dll
libboost_system-mt-d.dll
libboost_system-mt.dll
libboost_thread_win32-mt-d.dll
libboost_thread_win32-mt.dll
libboost_timer-mt-d.dll
libboost_timer-mt.dll
libboost_unit_test_framework-mt-d.dll
libboost_unit_test_framework-mt.dll
libboost_wave-mt-d.dll
libboost_wave-mt.dll
libboost_wserialization-mt-d.dll
libboost_wserialization-mt.dll
libopenblas.dll
libportmidi.dll
libpq.dll
librubberband.dll
libvamp-hostsdk.dll
libvamp-sdk.dll
libxmlrpc_client.dll
libxmlrpc_client++.dll
libxmlrpc_cpp.dll
libxmlrpc.dll
libxmlrpc++.dll
libxmlrpc_packetsocket.dll
libxmlrpc_server_cgi++.dll
libxmlrpc_server.dll
libxmlrpc_server++.dll
libxmlrpc_server_pstream++.dll
libxmlrpc_util.dll
libxmlrpc_xmlparse.dll
libxmlrpc_xmltok.dll
```

**Comment by tonytheodore** [comment]
`build-pkg` is now a continuous report on this, along with checks for no *.dll at all. We'll pick these up [as we go](https://github.com/mxe/mxe/compare/df3e43f7...a59294b1d).

**Comment by TimothyGu** [comment]
Wow MXE has really changed a lot since I last took a look at it…
