### ISSUE TITLE
autoconf 2.68b not recognized

### ISSUE THREAD

**Issue by Seanster** [mxe/mxe#413]
The regex in Makefile doesn't recognize the latest 2.68b autoconf. Maybe it's intentional to disallow use of the alpha versions but I don't see why you'd need to be that picky.

**Comment by tonytheodore** [comment]
Historically, the `autotools` are probably our single largest class of problems. We try to do the right thing and patch in a way that can be proposed upstream...

We are moving towards [feature detection](https://github.com/mxe/mxe/commit/989f09ca99a56cdb68f5f4b2dc65e9390b29289f) as versions don't really matter. As a user of alpha versions, I imagine this is no longer an issue for you.

In the mean time, you can always do:
```
make DONT_CHECK_REQUIREMENTS=true ...
```
to skip the version checks - especially if you are building a known subset of packages.
