### ISSUE TITLE
GCC C++11 threads support

### ISSUE THREAD

**Issue by Tyler-Hardin** [mxe/mxe#431]
Does MXE have the infrastructure to support a 2 stage compilation of GCC? If it does, you may want to consider making these modifications standard: http://blog.worldofcoding.com/2014_05_01_archive.html#windows.

**Comment by tm604** [comment]
Note that the performance concerns mentioned apply to thread startup/shutdown: once threads are running, there is no difference in speed between Posix and Win32. This is obviously not ideal for programs which regularly start/stop threads, but for some common cases such as setting up a thread pool on startup then POSIX threads tend to work fine.

**Comment by tonytheodore** [comment]
See #958 for optional c++11 treading support. Testing would be welcome.
