### ISSUE TITLE
parallel build question

### ISSUE THREAD

**Issue by uwehermann** [mxe/mxe#488]
In some .mk files you see the pattern of calling `make all` with `-j $(JOBS)` and calling `make install` in a second step, and using `-j 1`. Is there a technical reason for this?

Some other packages only use one invocation of `make install` (which implicitly does `make all` as well), and both targets are done with `-j '$(JOBS)`.
```
-    $(MAKE) -C '$(1).build' -j '$(JOBS)'
-    $(MAKE) -C '$(1).build' -j 1 install
+    $(MAKE) -C '$(1).build' -j '$(JOBS)' install
```

I've tested the above change on some packages and it seems to build fine for me, but not sure if there are any tricky things to be careful about here. Yes, I know that for *some* packages parallel builds in general do not work (upstream), but for those where it does - is there a reason to split the `all` and `install` steps into two lines?

Having them on one line is both shorter and allows to only add things like `$(MXE_DISABLE_CRUFT)` etc. once instead of twice.

**Comment by tonytheodore** [comment]
There's also the hypothetical DESTDIR option we might have used, but a git based approach seems solid.
