### ISSUE TITLE
Add mechanism for depending on build system packages

### ISSUE THREAD

**Issue by TimothyGu** [mxe/mxe#516]
Right now, packages that depend on libraries on build system are done in a very inefficient manner. For example, `gcc` depends on gcc-cloog, etc. This means that these packages that are shared across targets are rebuilt when a new target is specified.

One way to make it more efficient is using the `build-requirements` mechanism, and enable native build for regular cloog package. Then, implement a dependency system where something like this is possible:

``` make
$(PKG)_DEPS := cloog_$(BUILD)
```

**Comment by tonytheodore** [comment]
> `$(PKG)_DEPS := cloog_$(BUILD)`

Down the track we may add a mechanism for explicit inter-target deps for packages, but at the moment deps at a target level seem sufficient (#925).

**Comment by tonytheodore** [comment]
Target deps aren't sufficient as they cause rebuilds for unrelated packages and may cause unnecessary packages to be built.

**Comment by tonytheodore** [comment]
Also, `make download-foo` doesn't traverse target deps:
http://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-12/msg00005.html

**Comment by tonytheodore** [comment]
Implemented in #1990
