### ISSUE TITLE
Legality of include config.guess in the source

### ISSUE THREAD

**Issue by TimothyGu** [mxe/mxe#520]
The GNU config.guess script is licensed under GPLv3 with a special permission:

```sh
# As a special exception to the GNU General Public License, if you
# distribute this file as part of a program that contains a
# configuration script generated by Autoconf, you may include it under
# the same distribution terms that you use for the rest of that
# program.  This Exception is an additional permission under section 7
# of the GNU General Public License, version 3 ("GPLv3").
```

MXE is not using GNU Autoconf in any way, so is it legal to distribute it under the MIT license?

**Comment by tonytheodore** [comment]
> so is it legal to distribute it under the MIT license?

Hard question, the simple answer is probably "no". We should update our licence to reflect the fact that files under `ext` carry their own licence.

**Comment by tonytheodore** [comment]
Ughh, I can never write this stuff. The best I can think of is:

> Third Party Software

>This project includes third party software that is independently licensed by the respective owners of that software. Please see the relevant file headers in the `ext` directory.


The full CYA version is something like:

> 12. Third Party Acknowledgements.

>A. Portions of the Apple Software utilize or include third party software and other copyrighted material. Acknowledgements, licensing terms and disclaimers for such material are contained in the “online” electronic documentation for the Apple Software, and your use of such material is governed by their respective terms.

> B. The Apple Software includes certain software owned by the Free Software Foundation, Inc. (”FSF”) and licensed by Apple. You may obtain a complete machine-readable copy of the source code for the FSF Software under the terms of the GNU General Public License, without charge except for the cost of media, shipping, and handling, upon written request to Apple. The FSF Software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. A copy of the GNU General Public License is included with the Apple Software.

**Comment by tonytheodore** [comment]
This looks like a good template: https://github.com/JuliaLang/julia/blob/master/LICENSE.md
