### ISSUE TITLE
guile 1.8.7 doesn't build

### ISSUE THREAD

**Issue by rrthomas** [mxe/mxe#537]
I get the following in my `log`:

    ./gh.texi:1000: must be after `@deftypefun' to use `@deftypefunx'
    ./fdl.texi:411: raising the section level of @appendixsubsec which is too low
    ./api-utility.texi:566: warning: node `C Hooks' is next for `Hook Reference' in menu but not in sectioning
    ./api-utility.texi:674: warning: node `Hook Reference' is prev for `C Hooks' in menu but not in sectioning
    ./api-options.texi:510: warning: node next `Printing options' in menu `Debugger options' and in sectioning `Evaluator options' differ
    ./api-options.texi:533: warning: node prev `Evaluator options' in menu `Debugger options' and in sectioning `Printing options' differ
    ./api-options.texi:544: warning: node next `Evaluator trap options' in menu `Examples of option use' and in sectioning `Debugger options' differ
    ./api-options.texi:625: warning: node next `Debugger options' in menu `Evaluator options' and in sectioning `Examples of option use' differ
    ./api-options.texi:625: warning: node prev `Debugger options' in menu `Printing options' and in sectioning `Evaluator trap options' differ
    ./api-options.texi:681: warning: node prev `Examples of option use' in menu `Evaluator trap options' and in sectioning `Debugger options' differ
    make[4]: *** [guile.info] Error 1
    make[4]: Leaving directory `/usr/local/var/home/rrt/repo/mxe/tmp-guile/guile-1.8.7/doc/ref'

**Comment by luckyhacky** [comment]
did a test on master 745eb5365e16fddf90c4492bea98726838688f71
i can verify the correct build as @TimothyGu mentioned.
can you retry @rrthomas

**Comment by rrthomas** [comment]
I tried, unfortunately with current master head the gcc build fails:

    i686-w64-mingw32.static-gcc -E -x c /home/rrt/.local/var/repo/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.1.0/mingw-w64-v4.0.2/mingw-w64-crt/lib32/msvcrt.def.in -Wp,-w -I/home/rrt/.local/var/repo/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.1.0/mingw-w64-v4.0.2/mingw-w64-crt/def-include | /bin/sed 's/^#/;/' >lib32/msvcrt.def
    /bin/bash: lib32/msvcrt.def: No such file or directory
    make[3]: *** [lib32/msvcrt.def] Error 1
    make[3]: Leaving directory `/home/rrt/.local/var/repo/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.1.0.crt-build'
    make[2]: *** [all] Error 2

**Comment by TimothyGu** [comment]
@rrthomas okay now that's a different error…

**Comment by rrthomas** [comment]
@TimothyGu sure, I just mentioned it because it prevented me from retesting this issue.

**Comment by tonytheodore** [comment]
@rrthomas can you try again with the latest master and open a new issue if there's a problem?

**Comment by rrthomas** [comment]
I still can't get gcc to build, so no luck testing this, sorry.

**Comment by tonytheodore** [comment]
Could you open a new ticket with the full gcc log and note if you're using any hardened extensions?

**Comment by rrthomas** [comment]
Turns out there's some weirdness going on which isn't necessarily mxe-related; I'll investigate.

**Comment by rrthomas** [comment]
Once I subtract the weirdness (I shall analyse further and file another issue if I have time) both gcc and guile build fine.
