### ISSUE TITLE
Add wclang support

### ISSUE THREAD

**Issue by TimothyGu** [mxe/mxe#558]
See tpoechtrager/wclang.

In the short term I do not see a need to add new targets for clang as the compiler, but I do see that it is beneficial for MXE to have a clang package for people who want to use clang to compile their own projects.

But nevertheless, this should probably wait until the release is done.

**Comment by starius** [comment]
The toolchain [was updated](https://github.com/mxe/mxe/pull/925).
Is it possible to use wclang now?

**Comment by tonytheodore** [comment]
That is a very broad question. `wclang` is a wrapper that we could have used previously, though we now have a better way to provide the base `clang`.

Are you after `wclang` support or an `llvm`-based toolchain?

**Comment by starius** [comment]
I wonder if MXE can be built with clang instead of gcc. Clang would provide 4 new targets. By the way, how to assign triplets to such targets?

wclang seems to be usable for it. Can you share the better way?

**Comment by tonytheodore** [comment]
New targets I envisioned in the future were along the lines of:

```
i686-w64-mingw32.static.posix.sjlj
x86_64-w64-mingw32.shared.win32.seh
```

where the last two segements act largely as directory separators and shortcuts to `MXE_GCC_THREADS=` etc. `clang` is a little different as it can happily co-exist with `gcc` in any target and be enabled by changing `$(TARGET)-gcc` references to `$(TARGET_CC)`. If we were going to build entirely separate toolchains, I'd probably refer to them as:

```
i686-w64-mingw32.static.gnu
x86_64-w64-mingw32.shared.llvm
```

First step in either case is to get the base `clang` and wrappers (our own or `wclang`) built and see how best to roll it out.

**Comment by tehnick** [comment]
Hmm, this issue looks very interesting. Any progress in it or any additional thoughts?

**Comment by PsychoXIVI** [comment]
I just left it here: https://github.com/martell/mingw-w64-clang

**Comment by tonytheodore** [comment]
perennial issue
