### ISSUE TITLE
mxe-conf.cmake needs set(Boost_THREADAPI "win32")

### ISSUE THREAD

**Issue by karolherbst** [mxe/mxe#560]
otherwise cmake won't find boost while crosscompiling

**Comment by bilke** [comment]
Is there anything special I have to do when searching for Boost from CMake while cross compiling?

I ask because I cannot find it:

```cmake
find_package(Boost 1.46.0 COMPONENTS date_time filesystem system REQUIRED)
```

Strangely it finds `date_time` but not `filesystem` and `system`. The corresponding libs are there in `usr/i686-.../lib`. Can you help me?
