### ISSUE TITLE
mxe-conf.cmake: Hardcodes QT_QMAKE_EXECUTABLE to Qt4 qmake

### ISSUE THREAD

**Issue by uwehermann** [mxe/mxe#567]
From usr/i686-w64-mingw32.static/share/cmake/mxe-conf.cmake:

```
set(QT_QMAKE_EXECUTABLE /home/uwe/mxe-git/usr/i686-w64-mingw32.static/qt/bin/qmake)
```

This unconditionally hardcodes the qmake executable to the Qt4 version, regardless of whether the user built Qt4 or Qt5 or both or neither.

Not sure if there's a good solution to always have it point to the correct executable (?) Not sure what to do if both Qt4 and Qt5 are built/installed.

**Comment by tonytheodore** [comment]
also see #852

**Comment by tonytheodore** [comment]
Now that I know a little more about qt and cmake, this isn't an issue since the qt5 cmake modules don't use qmake to determine paths.
