### ISSUE TITLE
Consider "hardening" compiler flags

### ISSUE THREAD

**Issue by TobiX** [mxe/mxe#569]
As a "service" to users of MXE we should consider using every security measure available that doesn't impact users. See https://developer.pidgin.im/ticket/15290 for a similar effort in Pidgin's Win32 package.

**Comment by TobiX** [comment]
First step: Enable --enable-default-ssp on gcc build (as discussed on the list)

**Comment by tonytheodore** [comment]
This can be done with:
```
make ... gcc_CONFIGURE_OPTS='--enable-foo --disable-bar=true'
```
I'm leaning heavily away from any sort of defaults in the toolchain.
