### ISSUE TITLE
file failed to build x86_64.shared

### ISSUE THREAD

**Issue by TheDrifter363** [mxe/mxe#586]
I wanted to report this package failed to build on Debian Wheezy 7.0. In the log file, it stated that it required aclocal 1.14 where as I have aclocal 1.11. I believe it was file 5.20.

**Comment by TobiX** [comment]
This seems fixed with d19c724cbc2b005d0940facb3a10f2a58c674678 - @TheDrifter363, can you confirm?

**Comment by tonytheodore** [comment]
Debian stable has since been updated and no longer has this issue.
