### ISSUE TITLE
[Suggestion]: qt4-static, qt4-shared, qt5-static and qt5-shared targets

### ISSUE THREAD

**Issue by gyunaev** [mxe/mxe#591]
I propose to add the different Qt targets, such as:

- qt4-static installed n $PREFIX/qt/qt4-static
- qt4-shared installed n $PREFIX/qt/qt4-shared

and same with qt5. This would allow using the same toolchain for many different Qt versions, which otherwise overwrite each other when built.

qt#-shared target is very useful for applications which use Webkit, since static build Qt doesn't support Webkit. I can create a patch if needed, but the change seem to be rather straightforward.

**Comment by TobiX** [comment]
How is that a hassle with ffmpeg? Just copy all DLLs (we even now have a tool for this: https://github.com/mxe/mxe/blob/master/tools/copydlldeps.py) and be done with it... Works fine for Performous (you can even strip the DLLs to get a smaller install size for release builds).

**Comment by tonytheodore** [comment]
> I would definitely prefer, if possible, the option to mix shared and static libraries.

That would be very hard to implement from a build infrastructure point of view and I suspect it would cause a lot of complexity and problems down the track.

I'm pretty sure the new Qt WebEngine builds statically so you may not have to mix libs at all.
