### ISSUE TITLE
"Missing requirement: libtool" on Debian

### ISSUE THREAD

**Issue by ghost** [mxe/mxe#593]
On Debian 32 bit (unstable), with a fresh MXE checkout:

```
$ make gcc 
[check requirements]
Missing requirement: libtool

Please have a look at "index.html" to ensure
that your system meets all requirements.
```

I followed the instructions here: http://mxe.cc/#requirements-debian

I'm probably missing something obvious.

**Comment by danwalmsley** [comment]
instructions still need updating, I too just had this problem.

**Comment by starius** [comment]
@danwalmsley, have you installed `apt-get install libtool-bin`? It is needed for Debian Jessie (8) or Ubuntu Utopic (14.10) or later, as [the requirements page](http://mxe.cc/#requirements-debian) says. Probably we should include `libtool-bin` into main requirements list and instead add a note that it is not needed on older Debian releases.

**Comment by thejoshwolfe** [comment]
This is still a problem in Ubuntu 16.04. Why was this issue ever closed? The #requirements-debian instructions are wrong.

**Comment by tonytheodore** [comment]
@thejoshwolfe, see #1801 `libtool-bin` was a note for later releases and can now be moved to the main section.
