### ISSUE TITLE
QWebHistory is missing

### ISSUE THREAD

**Issue by benapetr** [mxe/mxe#599]
I did make qt in mxe and it seems that some parts of Qt are missing, when I start compiling the program I get:

```
i686-w64-mingw32.static-g++ -c -pipe -fno-keep-inline-dllexport -std=c++11 -O2 -frtti -fexceptions -mthreads -Wall -Wextra -DUNICODE -DQT_USE_QSTRINGBUILDER -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_THREAD_SUPPORT -I'../../qt/mxe/usr/i686-w64-mingw32.static/qt/include/QtCore' -I'../../qt/mxe/usr/i686-w64-mingw32.static/qt/include/QtNetwork' -I'../../qt/mxe/usr/i686-w64-mingw32.static/qt/include/QtGui' -I'../../qt/mxe/usr/i686-w64-mingw32.static/qt/include/QtXml' -I'/home/builder/qt/mxe/usr/i686-w64-mingw32.static/qt/include/QtWebKit' -I'../../qt/mxe/usr/i686-w64-mingw32.static/qt/include' -I'c:/python33/include' -I'c:/OpenSSL-Win32/include' -I'../../qt/mxe/usr/i686-w64-mingw32.static/qt/include/ActiveQt' -I'release' -I'.' -I'../../qt/mxe/usr/i686-w64-mingw32.static/qt/mkspecs/win32-g++-4.6' -o release/mainwindow.o mainwindow.cpp
In file included from mainwindow.cpp:42:0:
huggleweb.hpp:17:23: fatal error: QWebHistory: No such file or directory
 #include <QWebHistory>
```

This is not a first cpp file that required Qt headers, so some headers are there, it just looks like some are missing.

**Comment by benapetr** [comment]
this header is part of standard qt, for example by default in linux version at /usr/include/qt4/QtWebKit/QWebHistory

**Comment by benapetr** [comment]
in addition when trying to make qtwebkit with mxe I get this error:

```
Unpacking /home/builder/qt/mxe/tmp-icu4c-i686-w64-mingw32.static/icu/source/data/in/icudt54l.dat and generating out/tmp/icudata.lst (list of data files) 
LD_LIBRARY_PATH=../lib:../stubdata:../tools/ctestfw:$LD_LIBRARY_PATH  ../bin/icupkg -d ./out/build/icudt54l --list -x \* /home/builder/qt/mxe/tmp-icu4c-i686-w64-mingw32.static/icu/source/data/
in/icudt54l.dat -o out/tmp/icudata.lst 
../bin/icupkg: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../lib/libicutu.so.54) 
../bin/icupkg: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../lib/libicui18n.so.54) 
../bin/icupkg: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../lib/libicuuc.so.54)
```

**Comment by TobiX** [comment]
qtwebkit is not supported in static builds AFAIK. Build with MXE_TARGETS='i686-w64-mingw32.shared' to get a shared build.

(See the source https://github.com/mxe/mxe/blob/master/src/qtwebkit.mk or the build-matrix https://rss.23.gs/mxe/)

**Comment by benapetr** [comment]
How do I do that? just set the variable and rebuild mxe? or put it as parameter to make?

**Comment by benapetr** [comment]
also, I see qt5 is not supported in that matrix, is that true? I was able to build it and use it.

**Comment by TobiX** [comment]
You could either set the variables on the make command line or in settings.mk, see the tutorial, step 3: http://mxe.cc/#tutorial

And regarding your other question: Qt5 and newer is split into different components, so you build qtbase, qtmultimedia, qtwebkit, etc.

**Comment by TimothyGu** [comment]
@benapetr `qt5` is one of the so-called "virtual" packages. It depends on all components of Qt 5 to offer a shortcut to build all components in one step, and does not have a build recipe by itself. Usually you do not need to `make qt5` but `make qtcore` should be enough.

**Comment by tonytheodore** [comment]
@benapetr qtwebkit is now deprecated and was the only component that was missing from the static build vs shared.
