### ISSUE TITLE
gnutls build failure on Archlinux : recreate aclocal.m4 with macros from libtool 2.4.2 Debian-2.4.2-1.2

### ISSUE THREAD

**Issue by vrdhn** [mxe/mxe#602]
make gnutls give this error:

```
libtool: Version mismatch error.  This is libtool 2.4.2 Debian-2.4.2-1.2, but the
libtool: definition of this LT_INIT comes from libtool 2.4.4.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2 Debian-2.4.2-1.2
libtool: and run autoconf again.
```

Versions:

```
[user@first gnutls-3.2.1]$ pacman -Q | grep -e auto -e tool
autoconf 2.69-2
automake 1.14.1-1
intltool 0.50.2-2
libtool 2.4.4-2
```

**Comment by nathanhourt** [comment]
I'm getting this error as well. Any fixes or workarounds?

**Comment by TobiX** [comment]
Strange. Since we are using "autoreconf -fi" in src/gnutls.mk, this should not happen... Ah, there seems to be a stray ltmain.sh in the package... Could you try https://github.com/TobiX/mxe/tree/gnutls-libtool-conflict ?

**Comment by nathanhourt** [comment]
I was able to successfully build gnutls on that branch.

**Comment by TimothyGu** [comment]
@TobiX seems like a packaging issue.

**Comment by TimothyGu** [comment]
@TobiX just merged your branch. Hopefully will fully fix this issue.

**Comment by danriegsecker** [comment]
I'm still getting this error on the current stable branch. Does anyone have any suggestions? The link above is no longer available.

**Comment by TimothyGu** [comment]
@danriegsecker Use the master branch. We plan to retire the stable branch soon.

**Comment by danriegsecker** [comment]
@TimothyGu Thanks, will do.

**Comment by tonytheodore** [comment]
Autotools issues are evergreen...

Please reopen or open a new issue if this is still a problem.
