### ISSUE TITLE
Imagemagick not usable with libtiff, missing lzma dependency

### ISSUE THREAD

**Issue by sysbite** [mxe/mxe#603]
Hello,

I tried to use imagemagick together with the libtiff library, even though building it works fine, the libtiff tests of imagemagick fail and show a couple of undefined references:

> libtiff.a(tif_lzma.o): In function LZMASetupEncode:
> libtiff/tif_lzma.c:236: undefined reference to lzma_end

> libtiff.a(tif_lzma.o): In function LZMASetupDecode:
> libtiff/tif_lzma.c:118: undefined reference to lzma_end

> libtiff.a(tif_lzma.o): In function LZMACleanup:
> libtiff/tif_lzma.c:353: undefined reference to lzma_end

> libtiff.a(tif_lzma.o): In function `LZMAEncode':
> libtiff/tif_lzma.c:289: undefined reference to lzma_code

As a workaround, inside of tiff.mk, --disable-lzma should be added.
It will disable the lzma compression but at least will allow imagemagick to support the tiff format
until lzma is properly added as a dependency.

The configuration line should look like the following:
> define $(PKG)_BUILD
>    cd '$(1)' && ./configure \
>        $(MXE_CONFIGURE_OPTS) \
>        --without-x \
>    	--disable-lzma
>    $(MAKE) -C '$(1)' -j '$(JOBS)' install $(MXE_DISABLE_CRUFT)
> endef

**Comment by TimothyGu** [comment]
> even though building it works fine

Okay, so it's not really a bug.

> the libtiff tests of imagemagick fail and show a couple of undefined references:

Try doing something like `make LIBS=`i686-w64-mingw32.static-pkg-config libtiff-4 --libs --cflags`.
