### ISSUE TITLE
Failed to build package on ARM

### ISSUE THREAD

**Issue by svost** [mxe/mxe#604]
Hi!
I'm unable to compile gcc because it fails at gcc-gmp build for some reason.  Platform details are attached below.
http://www.hardkernel.com/main/products/prdt_info.php?g_code=G138745696275&tab_idx=2

processor       : 3
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 3394.86
Features        : swp half thumb fastmult vfp edsp thumbee neon vfpv3 tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0
Hardware        : ODROID-U2/U3 
Revision        : 0000
Serial          : 0000000000000000
novacoin@nvcnode:~/mxe$ uname -a
Linux nvcnode 3.8.13.27 #1 SMP PREEMPT Thu Aug 21 01:38:41 UTC 2014 armv7l armv7l armv7l GNU/Linux

novacoin@nvcnode:~/mxe$ make gcc zlib
[using autodetected 4 job(s)]
[target]   i686-w64-mingw32.static with 2 goals from command line
[build]    gcc-gmp

Failed to build package gcc-gmp!
------------------------------------------------------------
configure: error: /bin/bash /mnt/nvcvol/home/novacoin/mxe/tmp-gcc-gmp-i686-w64-mingw32.static/gmp-6.0.0/config.sub neon
neon
neon
neon-unknown-linux-gnueabihf failed
make[1]: *** [build-only-gcc-gmp_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory `/mnt/nvcvol/home/novacoin/mxe'
real    0m10.385s
user    0m9.355s
sys     0m0.845s
------------------------------------------------------------
[log]      /mnt/nvcvol/home/novacoin/mxe/log/gcc-gmp

make: *** [/mnt/nvcvol/home/novacoin/mxe/usr/i686-w64-mingw32.static/installed/gcc-gmp] Error 1
novacoin@nvcnode:~/mxe$

**Comment by svost** [comment]
novacoin@nvcnode:~/src/mxe/ext$ ./config.guess
armv7l-unknown-linux-gnueabihf
novacoin@nvcnode:~/src/mxe/tmp-gcc-gmp-i686-w64-mingw32.static/gmp-6.0.0$ ./config.guess
neon
neon
neon
neon-unknown-linux-gnueabihf
novacoin@nvcnode:~/src/mxe/tmp-gcc-gmp-i686-w64-mingw32.static/gmp-6.0.0$ ./config.sub armv7l-unknown-linux-gnueabihf
armv7l-unknown-linux-gnueabihf
novacoin@nvcnode:~/src/mxe/tmp-gcc-gmp-i686-w64-mingw32.static/gmp-6.0.0$ ./config.sub neon
Invalid configuration `neon': machine `neon' not recognized
(GNU MP wrapped config.sub, testing "neon")
novacoin@nvcnode:~/src/mxe/tmp-gcc-gmp-i686-w64-mingw32.static/gmp-6.0.0$

**Comment by TimothyGu** [comment]
It'll be hard for us to support ARM, simply because not many of us have ARM machines.

**Comment by svost** [comment]
Thanks for a response. And last attempt. This command is ok ./configure --prefix=/mnt/nvcvol/home/novacoin/src/mxe/usr --disable-shared --build=armv7l
. How to transfer this parameter (--build=armv7l) for assembly of gmp?

**Comment by TimothyGu** [comment]
We don't support ARM, and it would be extra work to support multiple archs, etc. without hardware to test it. So, I'm closing this issue.
