### ISSUE TITLE
build prerequements on mac failed

### ISSUE THREAD

**Issue by newnon** [mxe/mxe#615]
```
./ext/config.guess: line 1286: 54177 Trace/BPT trap: 5       exit
[using autodetected 6 job(s)]
uname -a
Darwin macbook-pro-vim 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin
git show-branch --list --reflog=1
  [refs/heads/master@{0}] (45 minutes ago) pull origin master: Fast-forward
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F34
rm -rf   '/Users/sergey/Documents/Projects/mxe/tmp-gcc-x86_64-apple-darwin13.4.0'
dyld: lazy symbol binding failed: Symbol not found: _unlinkat
  Referenced from: /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/bin/rm
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _unlinkat
  Referenced from: /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/bin/rm
  Expected in: /usr/lib/libSystem.B.dylib

make[2]: *** [build-only-gcc_x86_64-apple-darwin13.4.0] Trace/BPT trap: 5

real	0m3.034s
user	0m2.171s
sys	0m0.161s
```

**Comment by newnon** [comment]
I have latest xcode

**Comment by TimothyGu** [comment]
Seems to me that this is your system's fault. Can you try `rm` on a regular file or directory in the shell?

**Comment by newnon** [comment]
I've checked it on other mac with same result 
./ext/config.guess: line 1286: 45909 Trace/BPT trap: 5       exit
[using autodetected 6 job(s)]
uname -a
Darwin MacBook-Pro-Sergey.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin
git show-branch --list --reflog=1
  [refs/heads/master@{0}] (3 minutes ago) pull origin master: Fast-forward
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F34
rm -rf   '/Users/sergey/Documents/Projects/mxe/tmp-gcc-x86_64-apple-darwin13.4.0'
dyld: lazy symbol binding failed: Symbol not found: _unlinkat
  Referenced from: /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/bin/rm
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _unlinkat
  Referenced from: /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/bin/rm
  Expected in: /usr/lib/libSystem.B.dylib

make[2]: *** [build-only-gcc_x86_64-apple-darwin13.4.0] Trace/BPT trap: 5

real	0m2.688s
user	0m2.195s
sys	0m0.126s

**Comment by newnon** [comment]
and why it autodetected 6 jobs?

**Comment by newnon** [comment]
I've tried on 3-rd mac and looks like everything ok, but on 2 mac pro retina i've got same error.

**Comment by newnon** [comment]
After some experiments i totally removed all installed in system libraries from step 1 and reinstall everything one more. Looks like it is some bug of mac os may be after update some of libs was broken.

**Comment by newnon** [comment]
one more same bug
Making install in .
 /Users/sergey/Documents/Projects/mxe/tmp-coreutils-x86_64-apple-darwin13.4.0/coreutils-8.23/build-aux/install-sh -c -d '/Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/bin'
  src/ginstall src/ginstall '/Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/bin/./install'
  src/ginstall src/chroot src/hostid src/nice src/who src/users src/pinky src/uptime src/stty src/df src/stdbuf src/[ src/base64 src/basename src/cat src/chcon src/chgrp src/chmod src/chown src/cksum src/comm src/cp src/csplit src/cut src/date src/dd src/dir src/dircolors src/dirname src/du src/echo src/env src/expand src/expr src/factor src/false src/fmt src/fold src/groups src/head src/id src/join src/kill src/link src/ln src/logname src/ls src/md5sum src/mkdir src/mkfifo src/mknod src/mktemp src/mv src/nl src/nproc src/nohup src/numfmt src/od src/paste src/pathchk src/pr src/printenv src/printf src/ptx src/pwd src/readlink src/realpath src/rm src/rmdir src/runcon src/seq src/sha1sum src/sha224sum src/sha256sum src/sha384sum src/sha512sum src/shred src/shuf src/sleep src/sort src/split src/stat src/sum src/sync src/tac src/tail src/tee src/test src/timeout src/touch src/tr src/true src/truncate src/tsort src/tty src/uname src/unexpand src/uniq src/unlink src/vdir src/wc src/whoami src/yes '/Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/bin'
if test no = no; then \
	  case 'darwin13.4.0' in \
	    darwin[56]*) \
	      need_charset_alias=true ;; \
	    darwin* | cygwin* | mingw* | pw32* | cegcc*) \
	      need_charset_alias=false ;; \
	    *) \
	      need_charset_alias=true ;; \
	  esac ; \
	else \
	  need_charset_alias=false ; \
	fi ; \
	if $need_charset_alias; then \
	  /bin/sh /Users/sergey/Documents/Projects/mxe/tmp-coreutils-x86_64-apple-darwin13.4.0/coreutils-8.23/build-aux/install-sh -d /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib ; \
	fi ; \
	if test -f /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.alias; then \
	  sed -f lib/ref-add.sed /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.alias > /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.tmp ; \
	  /usr/bin/install -c -m 644 /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.tmp /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.alias ; \
	  rm -f /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.tmp ; \
	else \
	  if $need_charset_alias; then \
	    sed -f lib/ref-add.sed lib/charset.alias > /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.tmp ; \
	    /usr/bin/install -c -m 644 /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.tmp /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.alias ; \
	    rm -f /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.tmp ; \
	  fi ; \
	fi
dyld: lazy symbol binding failed: Symbol not found: _unlinkat
  Referenced from: /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/bin/rm
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _unlinkat
  Referenced from: /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/bin/rm
  Expected in: /usr/lib/libSystem.B.dylib

/bin/sh: line 1: 71090 Trace/BPT trap: 5       rm -f /Users/sergey/Documents/Projects/mxe/usr/x86_64-apple-darwin13.4.0/lib/charset.tmp
make[6]: *** [install-exec-localcharset] Error 133
make[5]: *** [install-am] Error 2
make[4]: *** [install-recursive] Error 1
make[3]: *** [install] Error 2
make[2]: *** [build-only-coreutils_x86_64-apple-darwin13.4.0] Error 2

real	0m59.901s
user	0m59.711s
sys	0m29.326s

**Comment by newnon** [comment]
rm work normaly

**Comment by TimothyGu** [comment]
@newnon because you are *building coreutils*

**Comment by newnon** [comment]
i've just write make build-requirements

**Comment by newnon** [comment]
i don't now why it build coreutils

**Comment by TimothyGu** [comment]
@newnon build-requirements just builds everything, including coreutils. (BSD vs GNU stuff)

**Comment by newnon** [comment]
Still no any idea?

**Comment by newnon** [comment]
After many attempts to fix finally found solution: remove usr folder from root of my mac hd, and then reinstall Mac Os from flash drive.
