### ISSUE TITLE
SDL2 keeps producing a broken SDL_revision.h

### ISSUE THREAD

**Issue by pouar** [mxe/mxe#620]
when compiling it produces a broken SDL_revision.h that looks like this
```C
#define SDL_REVISION "1
hg-0:baadf00d"
#define SDL_REVISION_NUMBER 1 0
```

**Comment by tonytheodore** [comment]
Very strange. No processing is done on this file at all, it gets installed the way it's unpacked. I can't think of much other some strange bug in `tar`.

Is it still happening?

**Comment by pouar** [comment]
Might be a bug in Perl

**Comment by tonytheodore** [comment]
Are you using the latest mxe version and could you post the full log?

**Comment by pouar** [comment]
well it seems to be working now
