### ISSUE TITLE
configure fails to detect libcurl/mxe provides unusable libcurl

### ISSUE THREAD

**Issue by xpbcreator** [mxe/mxe#621]
I'm attempting to cross-compile pebbleminer for windows 64-bit.  There is an issue with libcurl though.

I installed mxe stable in /home/ubuntu/mxe as follows:

    ~$ git clone -b stable https://github.com/mxe/mxe.git
    ~$ sudo apt-get install autoconf automake bash bison bzip2 \
    >                     cmake flex gettext git g++ intltool \
    >                     libffi-dev libtool libltdl-dev libssl-dev \
    >                     libxml-parser-perl make openssl patch perl \
    >                     pkg-config scons sed unzip wget xz-utils
    ~$ cd mxe
    ~/mxe$ make MXE_TARGETS='x86_64-w64-mingw32' -j10 gcc openssl binutils gettext mingw-utils mingw-w64 mingwrt pthreads pthreads-w32 w32api wget winpthreads zlib libssh2 curl
    ... everything succeeds ...

Then I edited .bashrc to add:

    export PATH=/home/ubuntu/mxe/usr/bin:$PATH

And re-logged in.

Then:

    ~$ git clone https://github.com/xpbcreator/pebbleminer.git
    ~$ cd pebbleminer
    ~/pebbleminer$ ./autogen.sh
    Makefile.am:12: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
    configure.ac:126: error: possibly undefined macro: AC_MSG_ERROR
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.    

To explain: this is the error you get for configuring on a system that doesn't have libcurl (I uninstalled it for the purpose of this).  Usually you install libcurl and continue.  In this case the system doesn't have libcurl and I wouldn't want to configure it to use the system's libcurl anyway.  Even so, running ./autogen.sh twice squashes the error, so:

    ~/pebbleminer$ ./configure --host=x86_64-w64-mingw32
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-w64-mingw32
    checking target system type... x86_64-w64-mingw32
    checking for a BSD-compatible install... /usr/bin/install -c
    ...
    ...
    ./configure: line 5672: syntax error near unexpected token `,'
    ./configure: line 5672: `LIBCURL_CHECK_CONFIG(, 7.15.2, ,'    

If I install libcurl on the system then it does appear to detect mxe's libcurl.  However, it doesn't appear to work:

    ~/pebbleminer$ sudo apt-get install libcurl4-openssl-dev
    ~/pebbleminer$ cd ..
    ~$ rm -rf pebbleminer
    ~$ git clone https://github.com/xpbcreator/pebbleminer.git
    ~$ cd pebbleminer
    ~/pebbleminer$ /autogen.sh
    Makefile.am:12: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
    ~/pebbleminer$ ./configure --host=x86_64-w64-mingw32
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-w64-mingw32
    checking target system type... x86_64-w64-mingw32
    ...
    ...
    checking for libcurl >= version 7.15.2... yes
    checking whether libcurl is usable... no
    configure: error: Missing required libcurl >= 7.15.2    

I know it found mxe's libcurl because if I do a regular configure, it succeeds:

    ~/pebbleminer$ ./configure
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    ...
    ...
    checking for the version of libcurl... 7.35.0
    checking for libcurl >= version 7.15.2... yes
    checking whether libcurl is usable... yes
    checking for curl_free... yes    
    ...
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating compat/Makefile
    config.status: creating compat/jansson/Makefile
    config.status: creating cpuminer-config.h
    config.status: executing depfiles commands

1) Is there a special way to run autoconf when using mxe?
2) If that doesn't matter in particular, why might mxe's libcurl be deemed unusable?

**Comment by TimothyGu** [comment]
When you do `autoconf`, m4 looks for included files on the **host system**. MXE does not provide macros like `LIBCURL_CHECK_CONFIG`. Now, you have three choices:

1. Stop using this macro and use more generic macros like `PKG_CHECK_MODULES`.
2. Install libcurl-dev.
3. Embed a version of `libcurl.m4` and put it in your `m4/` directory.

For the second error, I have no idea why it fails; but only by looking at a random version of `libcurl.m4` found on the internet it seems that the script uses `AC_PATH_PROG` to look for `curl-config`. This is bad, because on a correctly-setup system `curl-config` would return information of libcurl on the *host* system, not the MXE system. And of course when you are trying to link the host/Linux libcurl with Windows programs it will fail.

The correct way to fix this is by changing `AC_PATH_PROG` to `AC_PATH_TOOL` in the `libcurl.m4` file, which when searching the program first searches for `<targetname>-curl-config`. That leaves the only possible option to options 1 and 3.

If you just need a quick and dirty hack, two options might work:

1. Use `--with-libcurl=/dir/to/mxe/usr/<your target>` when configuring (try this first)
2. Use `_libcurl_config=<your target>-curl-config ./configure ...`

**Comment by xpbcreator** [comment]
Thanks for the quick reply!  Definitely some things to go on.  

I tried the first ditry hack and it didn't work.  In the process of doing the second dirty hack, I realized that I don't have a x864_64-w64-mingw32-curl-config file:

    ~/mxe$ find . | grep curl-config
    ./usr/x86_64-w64-mingw32/share/man/man1/curl-config.1
    ./usr/x86_64-w64-mingw32/bin/curl-config

I only have these prefixed files:

    ~/mxe$ find . | grep bin/x86_64-w64-mingw32-
    ./usr/bin/x86_64-w64-mingw32-ranlib
    ./usr/bin/x86_64-w64-mingw32-libgcrypt-config
    ./usr/bin/x86_64-w64-mingw32-ld.bfd
    ./usr/bin/x86_64-w64-mingw32-size
    ./usr/bin/x86_64-w64-mingw32-strip
    ./usr/bin/x86_64-w64-mingw32-c++filt
    ./usr/bin/x86_64-w64-mingw32-windmc
    ./usr/bin/x86_64-w64-mingw32-gcc-ar
    ./usr/bin/x86_64-w64-mingw32-windres
    ./usr/bin/x86_64-w64-mingw32-as
    ./usr/bin/x86_64-w64-mingw32-objcopy
    ./usr/bin/x86_64-w64-mingw32-elfedit
    ./usr/bin/x86_64-w64-mingw32-objdump
    ./usr/bin/x86_64-w64-mingw32-gcc-4.8.1
    ./usr/bin/x86_64-w64-mingw32-c++
    ./usr/bin/x86_64-w64-mingw32-ld
    ./usr/bin/x86_64-w64-mingw32-strings
    ./usr/bin/x86_64-w64-mingw32-ar
    ./usr/bin/x86_64-w64-mingw32-gcc
    ./usr/bin/x86_64-w64-mingw32-readelf
    ./usr/bin/x86_64-w64-mingw32-nm
    ./usr/bin/x86_64-w64-mingw32-g++
    ./usr/bin/x86_64-w64-mingw32-addr2line
    ./usr/bin/x86_64-w64-mingw32-dlltool
    ./usr/bin/x86_64-w64-mingw32-dllwrap
    ./usr/bin/x86_64-w64-mingw32-gcc-ranlib
    ./usr/bin/x86_64-w64-mingw32-gprof
    ./usr/bin/x86_64-w64-mingw32-cpp
    ./usr/bin/x86_64-w64-mingw32-gfortran
    ./usr/bin/x86_64-w64-mingw32-gcc-nm
    ./usr/bin/x86_64-w64-mingw32-pkg-config
    ./usr/bin/x86_64-w64-mingw32-gcov

Should I have one?  Does that give you any more hints?

**Comment by TimothyGu** [comment]
You are using the stable branch right now. Master branch has a fix for this: https://github.com/mxe/mxe/commit/dd83d630e28b02a0bbe84220ed9c49133396afa4

**Comment by xpbcreator** [comment]
It worked!  The solution was:

1. Make a local `m4` directory and copy `libcurl.m4` into it.
2. Place `AC_CONFIG_MACRO_DIRS([m4])` at the top of `configure.ac`.
3. Make the `~/mxe/usr/bin/x86_64-w64-mingw32-curl-config` soft link.
4. Change `AC_PATH_PROG` to `AC_PATH_TOOL` in the local `m4/libcurl.m4`.
5. `./autogen.sh`, `./configure --host=x86_64-w64-mingw32`, `make` and it worked.

Thanks again for the prompt help!

**Comment by TimothyGu** [comment]
Great to hear that :smile:
