### ISSUE TITLE
Linux-to-Windows cross-compilation fails due to missing sfml package

### ISSUE THREAD

**Issue by digitalhobbit** [mxe/mxe#625]
I'm trying to cross-compile from Linux to Windows (64 bit), following the instructions in Compile.md.

I built a full MXE setup, including sfml. I then tried to build attract with the following command:

```make WINDOWS_STATIC=1 CROSS=x86_64-w64-mingw32-```

During compilation, I receive the error message below multiple times:

```
Package sfml was not found in the pkg-config search path.
Perhaps you should add the directory containing `sfml.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sfml' found
```

At the end, the linker fails with many undefined sfml references such as this one:

```
obj/fe_input.o:fe_input.cpp:(.text+0x8da): undefined reference to `sf::Joystick::isButtonPressed(unsigned int, unsigned int)'
```

Even though sfml is installed with MXE, I can't find a sfml.pc file anywhere. Not sure if this is expected or a problem with the sfml MXE package.

I found a few references to sfml / MXE requiring some special settings, but it looks like your Makefile already addresses this.

Any pointers?

I haven't tried building the 32-bit version yet (which would entail another lengthy MXE build first...), but that's the next thing I'm planning to try.

Thanks,

-Mirko

**Comment by TimothyGu** [comment]
what package are you trying to cross-compile?

**Comment by digitalhobbit** [comment]
Oops, this is embarrassing... I meant to post this in github.com/attract, not github.com/mxe. Wrong browser tab...

Closing this issue.
