### ISSUE TITLE
git pull and make

### ISSUE THREAD

**Issue by 0xACE** [mxe/mxe#652]
Hello. This is not a bug report, it's a question:

I ran

    git clone https://github.com/mxe/mxe
    #resulted in commit 61d5384ce40e53eff199fc94231796bb21301809 currently 5 days old
    cd mxe
    echo "MXE_TARGETS := i686-w64-mingw32.static" > settings.mk
    echo "JOBS := 4" >> settings.mk
    make --keep-going

A few days later I ran

    git pull
    make --keep-going

Instead of just rebuilding the packages that changed, it would start rebuilding __all__ packages.

Am I using this wrong? Is it not possible to just compile what has been changed rather than rebuilding everything?

This makes it hard to keep the entire library up-to-date.

------
If you're curious of which packages which wouldn't compile: `opencsg openscenegraph pcl vcdimage xine-lib sfml wt` (I had to manually deal with `aubio` see #647)

One of them had issues with winsock2 being included before/after windows.h or something, few of them failed with something when ld tried to run something, and some of them were dependent on one of the packages which failed. I haven't looked close into it yet.

**Comment by 0xACE** [comment]
If this behaviour is expected.

Could anyone familiar with the current system describe what's needed to get this functionality working? So that I may implement it myself.

I'm guessing this is the basic procedure needed:

1. When successfully building a package it should write down the version it has installed.
2. If a package doesn't match the installed version rebuild the package and its installed dependencies.

**Comment by TimothyGu** [comment]
We depend on GNU Make's dependency tracking to cache installed version. This means that if the recipe or the recipe(s) of depended package changed, that package is considered to be out of date. A version-based approach is not considered because if one fixes a bug in the recipe (a subtle one that does not affect compilation) but does not update the package then users will not be able to benefit from the bug fix.

**Comment by TimothyGu** [comment]
> If you're curious of which packages which wouldn't compile: opencsg openscenegraph pcl vcdimage xine-lib sfml wt (I had to manually deal with aubio see #647)

Could you please open tickets for each (or +1 on the existing ticket)? Thanks.

**Comment by 0xACE** [comment]
I tried to `git pull && make --keep-going` again and it seemed like it would only compile the relevant changes. Maybe I did something wrong when I first tried it. I'll try to rebuild the entire package once more just to verify that it works.

>Could you please open tickets for each (or +1 on the existing ticket)? Thanks.

Yes, but first I have to confirm that the error isn't my machine being misconfigured.

__Another question:__ is it possible to run some way to run `make all --keep-going --ignore package1,package2,package3,etc` ?

The reason I ask is because two of the failling packages are pcl and wt, together they try to compile for a total of 40 minutes until they run into an error.

Currently I just stash a edited version of `index.html` to not list the failing packages.

**Comment by TimothyGu** [comment]
Yes, you can use `EXCLUDE_PKGS` with delimiter being a space <code>&nbsp;</code>.

**Comment by 0xACE** [comment]
Alright. I made a new clone (13th of march) of the entire mxe repo (`master`) and built all packages from scratch.

I waited a few days and ran `git pull`. 3 more commits came into `master` which modified: `mingw-w64`, `glew`, `glfw`.

I ran `make --keep-going` and went afk, this is the result:

    [target]   i686-w64-mingw32.static with 368 goals from src/*.mk
    [download] mingw-w64
    [build]    mingw-w64
    [done]     mingw-w64
    [build]    gcc
    [done]     gcc
    [build]    a52dec
    [done]     a52dec
    [build]    bzip2
    [done]     bzip2
    [build]    libiconv
    [done]     libiconv
    [build]    gettext
    [done]     gettext
    [build]    pcre
    [done]     pcre
    [build]    zlib
    [done]     zlib
    [build]    libffi
    [done]     libffi
    [build]    expat
    [done]     expat
    [build]    dbus
    [done]     dbus
    [build]    glib
    [done]     glib
    [build]    libpng
    [done]     libpng
    [build]    freetype-bootstrap
    [done]     freetype-bootstrap
    [build]    fontconfig
    [done]     fontconfig
    [build]    lzo
    [done]     lzo
    [build]    pixman
    [done]     pixman
    [build]    cairo
    [done]     cairo
    [build]    icu4c
    [done]     icu4c
    [build]    harfbuzz
    [done]     harfbuzz
    [build]    freetype
    [done]     freetype
    [build]    sdl
    [done]     sdl
    [build]    agg
    [done]     agg
    [build]    portaudio
    [done]     portaudio
    [build]    openal #errored out
    [build]    ogg
    [done]     ogg
    [build]    flac
    [done]     flac
    [build]    vorbis
    [done]     vorbis
    [build]    libsndfile
    [done]     libsndfile
    [build]    apr
    [done]     apr
    [build]    apr-util
    [done]     apr-util
    [build]    boost #I canceled this as I came back

I came back to the pc and realised it would continue compiling other packages. Is this really expected? should I manually keep track of what changes in the future and just explicitly build them 1 by 1 like so: `make --keep-going mingw-w64 glew glfw3`

**Comment by TimothyGu** [comment]
Yes. If you only need those packages, don't build all the other ones. In this case, all packages in MXE depends on mingw-w64, and because that was changed, everything needed to be rebuilt.

**Comment by 0xACE** [comment]
>In this case, all packages in MXE depends on mingw-w64

Fair enough. I'll let everything recompile then I guess.
