### ISSUE TITLE
nsis fails to build on OS X using Xcode 6.2 (clang-600.0.57)

### ISSUE THREAD

**Issue by kintel** [mxe/mxe#658]
Error message while building makensis (which is a native binary, not a cross-compiled binary):
```
ld: warning: option -s is obsolete and being ignored
ld: internal error: atom not found in symbolIndex(__ZN16SortedStringListI6defineED2Ev) for architecture x86_64
```

My theory is that smth. broke after Apple deprecated the ```-s``` linker option to g++.
g++ on OS X is actually just running clang in g++ compatibility mode.
 
I believe this should be fixable if nsis was build using native clang rather than g++, but it might be a larger task to make nsis do that.

PS. I haven't tried to build using older versions of Xcode/clang, so I cannot tell when this last worked, but I'm pretty certain it used to work.

**Comment by TimothyGu** [comment]
This is a bug in clang++. Note that the `-s` thing is just a warning. The real fatal error is internal.
