### ISSUE TITLE
Unable to build fontforge

### ISSUE THREAD

**Issue by hermesramos** [mxe/mxe#662]
Hi!

I am trying to build fontforge, but no luck so far. I tried setting the host and prefix in cofigure, but I keed getting an Error 1 on libfontforge_la-encondig.lo.

If you guys dont mind, could you help me, please?

Thanks

**Comment by tonytheodore** [comment]
Can you test again with the latest version of mxe? If you're seeing similar errors, please open a new issue and provide the build logs for investigation.
