### ISSUE TITLE
libbluray (and ffmpeg) and libdvdcss got broken - mingw-w64 update?

### ISSUE THREAD

**Issue by avih** [mxe/mxe#664]
`libbluray` built fine on March-21st (bf8126d353632ad03f0f68a71004dad2b69bde93), but no longer builds now (and as a result also `ffmpeg` which is configured to depend on it), I'm guessing due to the recent `mingw-w64` update, with the following error:

```
Failed to build package libbluray!
------------------------------------------------------------
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/user/dev/mxe/tmp-libbluray-i686-w64-mingw32.static/libbluray-0.6.2'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/user/dev/mxe/tmp-libbluray-i686-w64-mingw32.static/libbluray-0.6.2'
make[1]: *** [build-only-libbluray_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory `/home/user/dev/mxe'
real   0m9.630s
user   0m21.740s
sys    0m6.341s
------------------------------------------------------------
[log]      /home/user/dev/mxe/log/libbluray

make: *** [/home/user/dev/mxe/usr/i686-w64-mingw32.static/installed/libbluray] Error 1
```

I then tried to build specifically only `libbluray`:
```
$ cd tmp-libbluray-i686-w64-mingw32.static/libbluray-0.6.2
$ ./configure host=i686-w64-mingw32.static
...
  Summary:
  --------
  BD-J support:                  no
  Font support (freetype2):      yes
  Metadata support (libxml2):    yes
  Build examples:                yes


$ make
...
libbluray/.libs/bluray.o: In function `_update_stream_psr_by_lang':
/home/user/dev/mxe/tmp-libbluray-i686-w64-mingw32.static/libbluray-0.6.2/src/libbluray/bluray.c:293: undefined reference to `str_to_uint32'
/home/user/dev/mxe/tmp-libbluray-i686-w64-mingw32.static/libbluray-0.6.2/src/libbluray/bluray.c:301: undefined reference to `debug_mask'
/usr/bin/ld: libbluray/.libs/bluray.o: relocation R_X86_64_PC32 against undefined hidden symbol `debug_mask' can not beused when making a shared object
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libbluray.la] Error 1
make[2]: Leaving directory `/home/user/dev/mxe/tmp-libbluray-i686-w64-mingw32.static/libbluray-0.6.2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/dev/mxe/tmp-libbluray-i686-w64-mingw32.static/libbluray-0.6.2'
make: *** [all] Error 2
```

**Comment by avih** [comment]
Just noticed that `libdvdcss` also got broken, I'm guessing for the same reason that `libbluray` did. From the log:
```
In file included from src/libdvdcss.c:123:0:
/home/user/dev/mxe/usr/i686-w64-mingw32.static/include/shlobj.h:37:3: error: unknown type name 'EXTERN_C'
   SHFOLDERAPI SHGetFolderPathW (HWND hwnd, int csidl, HANDLE hToken, DWORD dwFlags, LPWSTR pszPath);
   ^
/home/user/dev/mxe/usr/i686-w64-mingw32.static/include/shlobj.h:37:3: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'HRESULT'
   SHFOLDERAPI SHGetFolderPathW (HWND hwnd, int csidl, HANDLE hToken, DWORD dwFlags, LPWSTR pszPath);
   ^
/home/user/dev/mxe/usr/i686-w64-mingw32.static/include/shlobj.h:37:3: error: unknown type name 'HRESULT'
```

and also there are also few warnings on `lseek` redifinitions.

**Comment by mabrand** [comment]
Fixed in commits leading up to 0905be2c93e70eebbad614fe3220527e046cc00c.

**Comment by avih** [comment]
Thanks for the fixes. Does it seem like a mingw issue? or libbluray/libdvdcss issue?

If it's the former, is the MXE policy to stick to latest mingw and fix everything else which is not compatible with it out of the box?

**Comment by mabrand** [comment]
It *seems* to me that windows.h should have been included before the other header in both cases. If that's right, then it was just good luck that libbluray and libdvdcs built as-is prior to mingw-w64 4.0.1.

I'm not sure MXE has a stated policy about this. Ideally, we'd ensure that everything always builds after updating anything in master branch. In practice, sometimes other priorities prevail.

**Comment by avih** [comment]
Seeing that also other MXE packages got broken from this mingw update (and probably also other projects which MXE is capable of building), did you try discussing it with the mingw guys? if it does turn out to be a mingw issue, then I'd think it's better to revert to 4.0 and wait for upstream mingw fixes.

**Comment by mabrand** [comment]
As of 182394008e63b1a977b5f6edd3d8c129fe2dce34, I think all packages build. To tell you the truth, I was too optimistic about the impact of the minor update to mingw-w64 4.0.1 because no problems were reported after the change to 4.0.0.

I cherry-picked a commit from the mingw-w64 master branch to fix the undefined EXTERN_C problem when including shlobj.h without windows.h. This makes it unnecessary to "fix" several packages where this situation exists.

Running a fresh rebuild just to be sure.

**Comment by avih** [comment]
Even if all the packages build cleanly now, MXE is also used as a cross-compiling system to build other projects, and if it's a mingw issue, then these other projects might also fail to build.

I have not encountered such "external" failures following the mingw update (I've built `mpv`, `the_silver_searcher` and `source-highlight` apparently without issues except for the `libbluray` and `libdvdcss` which you fixed), but it could happen if the fault is with mingw.
