### ISSUE TITLE
Compilation problem.

### ISSUE THREAD

**Issue by MathieuDutSik** [mxe/mxe#671]
Hi,

I had a compilation problem with ubuntu. I solved it, but what should be done
is add "autopoint" among the required libraries for ubuntu.

Thanks,

  Mathieu

**Comment by hamzaalloush** [comment]
same here, needs to be added into the requirements section for debian.

**Comment by ardnew** [comment]
also had this problem on Linux Mint 17 Cinnamon 64-bit. fixed with `apt-get install autopoint`. note this issue is already tracked (here: https://github.com/mxe/mxe/issues/437)

**Comment by TimothyGu** [comment]
It is already added to the master branch. We will retire the stable branch soon, so closing this bug.
