### ISSUE TITLE
wrong checksum for gsoap_2.8.22.zip

### ISSUE THREAD

**Issue by hamzaalloush** [mxe/mxe#675]
the correct checksum for the new package is e66bbdeaa6b5bdcb11de5141e1f17343a023c5c4

Thanks

--2015-05-02 13:50:40--  http://downloads.sourceforge.net/project/gsoap2/gSOAP/gsoap_2.8.22.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.34.181.59
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://liquidtelecom.dl.sourceforge.net/project/gsoap2/gSOAP/gsoap_2.8.22.zip [following]
--2015-05-02 13:50:40--  http://liquidtelecom.dl.sourceforge.net/project/gsoap2/gSOAP/gsoap_2.8.22.zip
Resolving liquidtelecom.dl.sourceforge.net (liquidtelecom.dl.sourceforge.net)... 197.155.77.8
Connecting to liquidtelecom.dl.sourceforge.net (liquidtelecom.dl.sourceforge.net)|197.155.77.8|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20948352 (20M) [application/octet-stream]
Saving to: ‘STDOUT’
...
2015-05-02 13:54:20 (93.6 KB/s) - written to stdout [20948352/20948352]

[download] gsoap

Download failed or wrong checksum of package gsoap!
------------------------------------------------------------
 20150K .......... .......... .......... .......... .......... 98% 82.2K 3s
 20200K .......... .......... .......... .......... .......... 98%  100K 2s
 20250K .......... .......... .......... .......... .......... 99%  110K 2s
 20300K .......... .......... .......... .......... .......... 99% 99.9K 1s
 20350K .......... .......... .......... .......... .......... 99%  101K 1s
 20400K .......... .......... .......... .......... .......... 99% 45.0K 0s
 20450K .......                                               100% 40.8M=3m38s
2015-05-02 13:54:20 (93.6 KB/s) - written to stdout [20948352/20948352]
------------------------------------------------------------
[log]      /home/hamza/build/mxe/log/gsoap-download

make: *** [download-only-gsoap] Error 1

**Comment by kamakazikamikaze** [comment]
I have also encountered this issue. Same output as above.

**Comment by mabrand** [comment]
It's not nice when checksums of packages change. It's been updated in MXE now.
