### ISSUE TITLE
Unable to build libgpg_error

### ISSUE THREAD

**Issue by danriegsecker** [mxe/mxe#677]
Building libgpg_error fails with errors...
```
/Users/dan/mxe/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src/init.c:79: undefined reference to `bindtextdomain'
.libs/libgpg_error_la-strsource.o: In function `gpg_strsource':
/Users/dan/mxe/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src/strsource.c:36: undefined reference to `dgettext'
.libs/libgpg_error_la-strerror.o: In function `gpg_strerror':
/Users/dan/mxe/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src/strerror.c:50: undefined reference to `dgettext'
.libs/libgpg_error_la-strerror.o: In function `gpg_strerror_r':
/Users/dan/mxe/tmp-libgpg_error-i686-w64-mingw32.shared/libgpg-error-1.19/src/strerror.c:161: undefined reference to `dgettext'
```

Using...
```
make MXE_TARGETS='i686-w64-mingw32.shared' libgpg_error
```

**Comment by danriegsecker** [comment]
From what I have found, libgpg-error will not properly build for shared or static. In the make process for libgpg-error an application is built and then run called mkheader. This application has a strcmp for mingw32 in the host_os variable which fails to be true when host_os contains mingw32.shared or mingw32.static. The failure of this test keeps w32-add.h from being added to gpg-error.h, hence causing the above undefined reference errors. After running the configure script, changing host_os from mingw32.shared to mingw32 in src/Makefile allows for a successful build. 

Can someone check me on this? What is the best method for fixing this in MXE?

Thanks, Dan

**Comment by mabrand** [comment]
Hi Dan,
My commit at af473838da7dae93e013f96a933ed2bd1a5b29aa added some symbolic links for similar reasons, but that wasn't enough apparently.

**Comment by danriegsecker** [comment]
@mabrand That's correct. I tried the shared build straight out of the master branch and it failed. That's when I added my change.

**Comment by mabrand** [comment]
Dan, I just pushed your fix to the master branch. cdbe8f2abf992cf9878c9d91f059dc69d3159b4f.
