### ISSUE TITLE
Requirements missing libtool-bin package for Debian distros

### ISSUE THREAD

**Issue by noscript** [mxe/mxe#680]
Error:
```
Missing requirement: libtool

Please have a look at "index.html" to ensure
that your system meets all requirements.

Makefile:265: recipe for target '~/mxe.git/usr/installed/check-requirements' failed
```

Debian and derivatives in addition to `intltool` also require `libtool-bin` package, due to this check in `Makefile`:
```
LIBTOOL    := $(shell glibtool --help >/dev/null 2>&1 && echo g)libtool
```
`glibtool` belongs to `libtool-bin` package. Please update `index.html`.

**Comment by starius** [comment]
:+1:

**Comment by starius** [comment]
Debian Wheezy (oldstable) [has](https://packages.debian.org/wheezy/all/libtool/filelist) `libtool` binary in package `libtool`.

Debian Jessie (stable) [has](https://packages.debian.org/jessie/all/libtool-bin/filelist) `libtool` binary in package `libtool-bin`.
