### ISSUE TITLE
OpenCV CMake modules

### ISSUE THREAD

**Issue by asarnow** [mxe/mxe#682]
Right now there seems to be a minor bug with the CMake modules for OpenCV.  My apologies if I have missed something obvious.
- `mxe/usr/<target>/OpenCVConfig.cmake` and `mxe/usr/<target>/OpenCVConfig-version.cmake` seem to be wrong versions, which don't work.
- `mxe/usr/<target>/lib/OpenCV*.cmake` files work, but:
  - CMake module search path includes `<target>`, but not `<target>/lib`
  - OpenCV import prefix is set to parent directory of the `.cmake` file which is used.
  - OpenCV libraries are found in `<target>/lib`

My temporary work around is to copy the `.cmake` files from `<target>/lib` to `<target>`, and then manually modify the `CMakeCache.txt` so `OpenCV_DIR` and `OpenCV_CONFIG_PATH` point to `<target>/lib`.

I think the old module files should be removed, and the find package module should search in `<target>/lib` for `OpenCVConfig.cmake`, `OpenCVModules.cmake` and `OpenCVModules-release.cmake`, or the new files should be moved up one directory and "/lib" added after every `_IMPORT_PREFIX` reference.

**Comment by tonytheodore** [comment]
Looks related to #598. There's a major version update to opencv waiting, lets see what happens after that.
