### ISSUE TITLE
qtwebkit fail to build in x86_64-w64-mingw32.shared target

### ISSUE THREAD

**Issue by lsaavedr** [mxe/mxe#684]
That is bug related to g++ 5:

"A non-inline template needs to be explicitly instantiated if used
outside the object where it is declared.Patch suggested by Khem Raj.
Task-number: 
QTBUG-44829
Change-Id: Ib0adbd9273bd1cef01e5863bc8aaa9c373022792
Reviewed-by: Andras Becsi <andras.becsi@theqtcompany.com>"

to see a patch:
https://codereview.qt-project.org/#/c/107921

**Comment by andrey-str** [comment]
I can confirm that this patch allows to successfully compile qwebkit with MXE.shared

**Comment by tonytheodore** [comment]
Unfortunately, qtwebkit has since [been deprecated in 5.5](https://github.com/mxe/mxe/commit/325f1070341482c7c8b45c857371f49fd85a6e21)
