### ISSUE TITLE
makefile autogenerated by qmake is buggy on CLEAN

### ISSUE THREAD

**Issue by JazzMaster** [mxe/mxe#685]
I found this on a make clean error I encountered:
(disastrous)

```make
	-$(DEL_FILE) cd
	-$(DEL_FILE) /home/me/Desktop/code/Feathercoin/src/leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) $(MAKE)
	-$(DEL_FILE) clean
```

It attempts to remove the rm, make and clean files, clean file being non-existant, the others being binaries needed for building executables. RM the rm command and you get a broken Linux system.This is a big no no.Why are my source files being targeted for deletion? leveldb is a SOURCE file.

**Comment by tonytheodore** [comment]
I'm assuming this is no longer an issue? It looks to me like there was some escaping problem and you want to see something like:
```
cd /home/me/Desktop/code/Feathercoin/src/leveldb;
$(MAKE) clean
```

Otherwise, can you send the commands you used and re-open the issue?
