### ISSUE TITLE
mingw-w64 bug in stable and master branch

### ISSUE THREAD

**Issue by lsaavedr** [mxe/mxe#688]
Hello, I worked to find this bug but I can not yet find where is, to see the symptoms may do the following:
```bash
$ make MXE_TARGETS="i686-pc-mingw32 i686-w64-mingw32" postgresql
```
and then
```bash
$ wine ./usr/i686-w64-mingw32/bin/psql.exe -h 190.82.92.53 -U mxeuser mxedb
$ wine ./usr/i686-pc-mingw32/bin/psql.exe -h 190.82.92.53 -U mxeuser mxedb
```
psql.exe only work in i686-pc-mingw32 toolchain,

regards,
Luis

**Comment by TimothyGu** [comment]
Does the binary crash? Or what is it like?

**Comment by lsaavedr** [comment]
no, can you make that to see the differences, the problem is the same as in the #690, with i686-pc-mingw32 the problem is not present, thanks!!!

**Comment by tonytheodore** [comment]
Both the stable branch and `*-pc-*` targets are discontinued - please move discussion to #690
