### ISSUE TITLE
crash on fortran call to open for existing file

### ISSUE THREAD

**Issue by ajmay81** [mxe/mxe#689]
When trying to use Fortran (gfortran) open even the most trivial program seg faults. MXE built with:

    make gcc MXE_TARGETS="i686-w64-mingw32.static"

a simple Fortran file, test.f90:

    program test
    implicit none
    integer i
    i=77
    open(file='data.txt',unit=i)
    end

compiled with:

    i686-w64-mingw32.static-gfortran test.f90

and then when run:

    a.exe

works if data.txt does not exists, but does not work if data.txt exists (if data.txt does not exist running this program creates it, i.e. this program will definitely fail if run twice):

    Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

I have an older install of mxe where gcc is 4.8.1 and it works, so it's perhaps it related to some change in gcc 5.1 (the program compiles and runs fine natively on Linux or OSX with gcc 5.1).

**Comment by tonytheodore** [comment]
> perhaps it related to some change in gcc 5.1

Seems likely, gcc has since been updated to 5.2 and I can't replicate the error here.

Can you check again with the latest version and confirm if it's been fixed?

**Comment by ajmay81** [comment]
You're right, whatever the issue was it's fixed with GCC 5.2. Thanks for taking the time to try and reproduce.

**Comment by Gjacquenot** [comment]
I am doing cross compilation with gfortran 5.4.0 `x86_64-w64-mingw32.static-gfortran` and I get the same kind of error. I don't know if it is related to a file reading. C++ programs work fine. When running program with wine, I got no error messages. However  on Windows, I got these nasty messages

    my_program.exe

    Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

    Backtrace for this error:
    #0  ffffffffffffffff
    #1  ffffffffffffffff
    ...
    #22  ffffffffffffffff
    #23  ffffffffffffffff

    gdb my_program.exe
    GNU gdb (GDB) 7.8.1
    Copyright (C) 2014 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-w64-mingw32".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from my_program.exe...done.
    (gdb) r
    Starting program: D:\my_program.exe
    [New Thread 13264.0x3278]
    warning: Could not load shared library symbols for C:\windows\system32\kernel64.dll.
    Do you need "set solib-search-path" or "set sysroot"?

    Program received signal SIGSEGV, Segmentation fault.
    0x0000000077add148 in ntdll!RtlEnterCriticalSection () from C:\windows\SYSTEM32\ntdll.dll
    (gdb) bt
    #0  0x0000000077add148 in ntdll!RtlEnterCriticalSection () from C:\windows\SYSTEM32\ntdll.dll
    Backtrace stopped: previous frame identical to this frame (corrupt stack?)
    (gdb)

**Comment by ajmay81** [comment]
This particular issue has not been occurring since at least GCC 5.2. The next stage of my journey to get running was reporting a bug in GCC:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70684

which was fixed and released into GCC 5.4.0. Since then everything has been working fine for me using the Fortran cross compiler, I used 5.4.0 up until last summer, and updated to the gcc7 plugin since then.

That error message is very generic, and unless you see it with exactly the same cut-down as I made in the OP then I would suggest it's a different problem, probably best reported as a separate issue.

Perhaps you can try to make a cut down of your problem. It was a long time ago since I reported that issue, I seem to recall gdb was not very helpful and I simply inserted write statements in the code until I managed to find where it was crashing.
