### ISSUE TITLE
Postgres connection failed.

### ISSUE THREAD

**Issue by Vladimirek** [mxe/mxe#690]
QT5 program compilled with MXE failed to connect Postgresql database with message:
could not connect to server: Operation would block (0x00002733/10035)
The problem is known: https://bugzilla.redhat.com/show_bug.cgi?id=996529 
The working and tested solution for me is add postgresql-mingw-errno.patch (renamed to postgresql-3-mingw-errno.patch) to src directory and rebuild postgresql and qt5 too.

Patch is downloaded from:
http://arm.koji.fedoraproject.org//packages/mingw-postgresql/9.2.4/2.fc19/src/mingw-postgresql-9.2.4-2.fc19.src.rpm  or pasted single file here: http://pastebin.com/tEGAwd6m

-vladimirek-

**Comment by lsaavedr** [comment]
related with #688
