### ISSUE TITLE
FFmpeg VP9 Encoding Support

### ISSUE THREAD

**Issue by CoolOppo** [mxe/mxe#696]
I have tried a ton of different things, but I can not get MXE to compile a version of FFmpeg that actually supports encoding in VP9. I don't know what else to try; I've done about everything there is to do. I have edited [the libvpx.mk file](https://github.com/mxe/mxe/blob/6947d3245f9c76d9124a4c4f3c164154a75f3f62/src/libvpx.mk#L27) by inserting the line `--enable-vp9`, but for some reason, the resultant FFmpeg binaries never support encoding in VP9!

Any help would be appreciated, but please actually try out the suggestions you make before saying them because believe me, I've tried quite a bit of things, and I don't need any help brute-forcing a crappy solution into place - I've already attempted that.

**Comment by TimothyGu** [comment]
First, try to update libvpx to 1.4.0.

Second, you shouldn't need to mess with the settings in libvpx. Build ffmpeg manually, and after configuration paste the config.log in ffmpeg/ onto a gist and I'll take a look at it.

**Comment by TimothyGu** [comment]
Both libvpx and ffmpeg updated.
