### ISSUE TITLE
gsoap error when build: checksum incorrect

### ISSUE THREAD

**Issue by JazzMaster** [mxe/mxe#704]
I do a make all (now on fedora vice debian) and I get past the DeViL issue with the emailed patch(needs inclusion in the downloaded sources) but now I get another error. gsoap seems to download correctly but has the wrong checksum and fails.Did we checksum an older file?

**Comment by mabrand** [comment]
The checksum was recently updated in MXE master branch. It still seems to be right. Do you have the latest version?

**Comment by luckyhacky** [comment]
Did a test on master 745eb5365e16fddf90c4492bea98726838688f71

>> gsoap.mk:
$(PKG)_VERSION  := 2.8.22
$(PKG)_CHECKSUM := e66bbdeaa6b5bdcb11de5141e1f17343a023c5c4

Everything runs fine and gsoap compiles

**Comment by JazzMaster** [comment]
probably not. Do I git pull or push?

**Comment by mabrand** [comment]
pull

**Comment by luckyhacky** [comment]
do a "git pull"
if it still doesnt worl, provide "git show" or "git log -n 3" so we can see your current status.

**Comment by JazzMaster** [comment]
no, I pulled but now qt wont build. It built before.

Konsole output
Failed to build package qt!
------------------------------------------------------------
Turn on verbose messaging (-v) to ./configure to see the final report.
If you believe this message is in error you may use the continue
switch (-continue) to ./configure to continue.
Makefile:437: recipe for target 'build-only-qt_i686-w64-mingw32.static' f
ailed
make[1]: *** [build-only-qt_i686-w64-mingw32.static] Error 101
make[1]: Leaving directory '/home/me/mxe'

**Comment by mabrand** [comment]
The gnutls update yesterday broke the gsoap build unfortunately. But now it should work again. The same goes for freetds, on which qt and qtbase depend.

**Comment by mabrand** [comment]
Just fixed a freetds problem that caused build failure on qt and qtbase.
