### ISSUE TITLE
CMake cannot find Boost

### ISSUE THREAD

**Issue by bilke** [mxe/mxe#705]
I build boost with MXE without a problem. Now I like to cross-compile my own project which uses CMake. Is there anything special I have to do when searching for Boost from CMake while cross compiling?

I ask because I cannot find it:

```cmake
find_package(Boost 1.46.0 COMPONENTS date_time filesystem system REQUIRED)
```

Strangely it finds `date_time` but not `filesystem` and `system`. The corresponding libs are there in `usr/i686-.../lib`. Can you help me?

**Comment by sysbite** [comment]
Hey there,

Are you using the cmake toolchain file when trying to build your project?
It would help if you show how you attempt to build it.
Usually the above line should be enough, given that you do the right steps.

The toolchain is located under yourmxepath/usr/i686-.../share/cmake/mxe-conf.cmake

**Comment by tonytheodore** [comment]
It should just find it if you're using the toolchain file or the (new) prefixed cmake e.g `i686-w64-mingw32.static-cmake`. I've [added a test to boost](https://github.com/mxe/mxe/commit/8a2cbf2c289b46e2f3458d895f021ea79ac04d37) to make sure it does work.

**Comment by tonytheodore** [comment]
Can you try again and reopen if it's still an issue. We [now bundle `cmake`](https://github.com/mxe/mxe/commit/9bd2349eebe5489a4712bb0678cdf4eb4a42f276) so problems should be easier to replicate. Make sure you use the appropriate prefixed wrapper to pick up the bundled `cmake` version e.g.:
```
i686-w64-mingw32.static-cmake
```
