### ISSUE TITLE
"make qtbase" fails to build gcc-mpc if "make gcc" wasn't executed before that

### ISSUE THREAD

**Issue by Soukyuu** [mxe/mxe#706]
It says that it's building dependencies first, but after getting to gcc-mpc it just fails with:
```
Failed to build package gcc-mpc!
------------------------------------------------------------
Makefile:298: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/azure/mxe/tmp-gcc-mpc-i686-w64-mingw32.static/mpc-1.0.2.build'
Makefile:437: recipe for target 'build-only-gcc-mpc_i686-w64-mingw32.static' failed
make[1]: *** [build-only-gcc-mpc_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory '/home/azure/mxe'
real    0m7.995s
user    0m9.165s
sys     0m1.211s
```

This is on a cleanly cloned git master. The log got overwritten when I ran make gcc, but I can re-run it in a clean dir afterwards if needed.

**Comment by saiarcot895** [comment]
Note that logs are stored in a timestamped directory, so you should be able to go back and get the log.

**Comment by tonytheodore** [comment]
Assuming this is no longer an issue. Please re-open with full log if it is.
