### ISSUE TITLE
Add "wdmks" support for PortAudio

### ISSUE THREAD

**Issue by mgeier** [mxe/mxe#716]
This is very similar to #715, but instead of "wasapi", I'm trying to add support for "wdmks".

I tried changing the `--with-winapi` option in `src/portaudio.mk` from

    --with-winapi=wmme,directx

to

    --with-winapi=wdmks

But afterwards, this doesn't work anymore:

    $ make portaudio MXE_TARGETS=i686-w64-mingw32.static

In `log/portaudio` there is a warning:

```
src/hostapi/wdmks/pa_win_wdmks.c:66:0: warning: "_WIN32_WINNT" redefined
 #define _WIN32_WINNT 0x0501
 ^
In file included from .../usr/i686-w64-mingw32.static/include/crtdefs.h:10:0,
                 from .../usr/i686-w64-mingw32.static/include/stdio.h:9,
                 from src/hostapi/wdmks/pa_win_wdmks.c:53:
.../usr/i686-w64-mingw32.static/include/_mingw.h:225:0: note: this is the location of the previous definition
 #define _WIN32_WINNT 0x502
 ^
```

And a bit further down, there are some errors:

```
In file included from .../usr/i686-w64-mingw32.static/include/combaseapi.h:156:0,
                 from .../usr/i686-w64-mingw32.static/include/objbase.h:14,
                 from .../usr/i686-w64-mingw32.static/include/ole2.h:17,
                 from .../usr/i686-w64-mingw32.static/include/wtypes.h:12,
                 from .../usr/i686-w64-mingw32.static/include/winscard.h:10,
                 from .../usr/i686-w64-mingw32.static/include/windows.h:97,
                 from ./include/pa_win_wdmks.h:49,
                 from src/hostapi/wdmks/pa_win_wdmks.c:87:
.../usr/i686-w64-mingw32.static/include/winioctl.h:12:1: error: redefinition of 'GUID_DEVINTERFACE_DISK'
 DEFINE_GUID(GUID_DEVINTERFACE_DISK,0x53f56307,0xb6bf,0x11d0,0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b);
 ^
.../usr/i686-w64-mingw32.static/include/winioctl.h:12:1: note: previous definition of 'GUID_DEVINTERFACE_DISK' was here
 DEFINE_GUID(GUID_DEVINTERFACE_DISK,0x53f56307,0xb6bf,0x11d0,0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b);
 ^
.../usr/i686-w64-mingw32.static/include/winioctl.h:13:1: error: redefinition of 'GUID_DEVINTERFACE_CDROM'
 DEFINE_GUID(GUID_DEVINTERFACE_CDROM,0x53f56308,0xb6bf,0x11d0,0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b);
 ^
.../usr/i686-w64-mingw32.static/include/winioctl.h:13:1: note: previous definition of 'GUID_DEVINTERFACE_CDROM' was here
 DEFINE_GUID(GUID_DEVINTERFACE_CDROM,0x53f56308,0xb6bf,0x11d0,0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b);
 ^
.../usr/i686-w64-mingw32.static/include/winioctl.h:14:1: error: redefinition of 'GUID_DEVINTERFACE_PARTITION'
 DEFINE_GUID(GUID_DEVINTERFACE_PARTITION,0x53f5630a,0xb6bf,0x11d0,0x94,0xf2,0x00,0xa0,0xc9,0x1e,0xfb,0x8b);
```

There are quite a few very similar errors after that.

Any ideas what's the problem here and how I could fix it?

**Comment by TimothyGu** [comment]
For the warning, you can just ignore it for now. Pulseaudio is trying to support XP, while mingw-w64 the toolchain dropped support for XP and is targeting Windows Server 2003 and up.

For the errors, basically I think winioctl.h in mingw-w64 is probably missing some multiple inclusion guards. All other parts of the header are protected by `_WINIOCTL_` macro, but ll. 12-36 are not.

I believe mingw-w64 has its reasons for omitting the guard, so the best solution I think is to remove the `#include <winioctl.h>` line in pulseaudio/src/hostapi/wdmks/pa_win_wdmks.c, if it fixes the problem.

**Comment by mgeier** [comment]
@TimothyGu, you're my man!
You nailed it, when I remove the include line you mentioned, it compiles fine.

To do that, I created a little patch file `src/portaudio-2-wdmks.patch`:

```diff
--- portaudio/src/hostapi/wdmks/pa_win_wdmks.c	2012-12-28 17:54:25.000000000 +0100
+++ portaudio-patched/src/hostapi/wdmks/pa_win_wdmks.c	2015-06-17 14:29:23.695735572 +0200
@@ -87,7 +87,6 @@
 #include "pa_win_wdmks.h"
 
 #include <windows.h>
-#include <winioctl.h>
 #include <process.h>
 
 #include <math.h>
```

For my use case that's all I need, but it would be nice to somehow push this upstream, right?

How should I proceed with that?
You mentioned that you think the mingw stuff is on purpose, so should I send this to the PortAudio people?
I suppose they cannot just remove the line because it would break other (non-MinGW) builds, right?

**Comment by TimothyGu** [comment]
> For my use case that's all I need, but it would be nice to somehow push this upstream, right?

Yes.

> You mentioned that you think the mingw stuff is on purpose, so should I send this to the PortAudio people?

Yes

> I suppose they cannot just remove the line because it would break other (non-MinGW) builds, right?

TBH, I am kind of convinced that this is a MinGW-w64 bug for not allowing including that header multiple times. There are [MSDN articles](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363147(v=vs.85).aspx) that show `windows.h` and `winioctl.h` included at the same time, and IMO it is MinGW-w64's job to allow that syntax.

But anyway, I'm sure PortAudio would welcome this workaround. There is no "other builds" to worry about, since [another MSDN page](https://msdn.microsoft.com/en-us/library/windows/desktop/hh706683(v=vs.85).aspx) says that it should be sufficient to include `Windows.h` for `WinIoCtl.h`.

**Comment by mgeier** [comment]
Thanks a lot!

I sent this to the PortAudio mailing list: http://music.columbia.edu/pipermail/portaudio/2015-June/016833.html
