### ISSUE TITLE
gnutls fails to build under cygwin+mingw-w64

### ISSUE THREAD

**Issue by rr-** [mxe/mxe#718]
I get error: **`libtoolize: $pkgltdldir is not a directory: "/mingw/share/libtool"`**

Mingw version:

    rr-@work:~/src/mxe$ i686-w64-mingw32-g++ --version
    i686-w64-mingw32-g++ (GCC) 4.9.2

Cygwin version:

    rr-@work:~/src/mxe$ uname -a
    CYGWIN_NT-6.2-WOW work 2.0.2(0.287/5/3) 2015-05-08 17:03 i686 Cygwin

Output:

    rr-@work:~/src/mxe$ make gnutls MXE_VERBOSE=1
    [using autodetected 6 job(s)]
    [target]   i686-w64-mingw32.static with 1 goal from command line
    [build]    gnutls
    
    Failed to build package gnutls!
    ------------------------------------------------------------
    make[1]: Entering directory '/cygdrive/z/src/mxe'
    [using autodetected 6 job(s)]
    uname -a
    CYGWIN_NT-6.2-WOW work 2.0.2(0.287/5/3) 2015-05-08 17:03 i686 Cygwin
    git show-branch --list --reflog=1
      [refs/heads/master@{0}] (56 minutes ago) (none)
    lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
    rm -rf   '/cygdrive/z/src/mxe/tmp-gnutls-i686-w64-mingw32.static'
    mkdir -p '/cygdrive/z/src/mxe/tmp-gnutls-i686-w64-mingw32.static'
    cd '/cygdrive/z/src/mxe/tmp-gnutls-i686-w64-mingw32.static' &&       xz -dc '/cygdrive/z/src/mxe/pkg/gnutls-3.3.15.tar.xz' | tar xf -
    cd '/cygdrive/z/src/mxe/tmp-gnutls-i686-w64-mingw32.static/gnutls-3.3.15'
    (cd '/cygdrive/z/src/mxe/tmp-gnutls-i686-w64-mingw32.static/gnutls-3.3.15' && patch -p1 -u) < ./src/gnutls-1-fixes.patch
    patching file configure.ac
    patching file configure.ac
    patching file lib/gnutls.pc.in
    patching file configure.ac
    patching file lib/x509/output.c
    sed -i 's, sed , sed ,g' '/cygdrive/z/src/mxe/tmp-gnutls-i686-w64-mingw32.static/gnutls-3.3.15/gl/tests/Makefile.am'
    rm '/cygdrive/z/src/mxe/tmp-gnutls-i686-w64-mingw32.static/gnutls-3.3.15/ltmain.sh'
    cd '/cygdrive/z/src/mxe/tmp-gnutls-i686-w64-mingw32.static/gnutls-3.3.15' && autoreconf -fi -I m4 -I gl/m4 -I src/libopts/m4
    Copying file build-aux/config.rpath
    Copying file m4/codeset.m4
    Copying file m4/glibc2.m4
    Copying file m4/glibc21.m4
    Copying file m4/intdiv0.m4
    Copying file m4/intl.m4
    Copying file m4/intldir.m4
    Copying file m4/intmax.m4
    Copying file m4/lcmessage.m4
    Copying file m4/lock.m4
    Copying file m4/printf-posix.m4
    Copying file m4/threadlib.m4
    Copying file m4/uintmax_t.m4
    Copying file m4/visibility.m4
    Copying file po/Makevars.template
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:158: LIBOPTS_WITHLIB_REGEX is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:260: LIBOPTS_RUN_PATHFIND is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:303: LIBOPTS_RUN_REALPATH is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:330: LIBOPTS_RUN_STRFTIME is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:363: LIBOPTS_RUN_FOPEN_BINARY is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:386: LIBOPTS_RUN_FOPEN_TEXT is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:158: LIBOPTS_WITHLIB_REGEX is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:260: LIBOPTS_RUN_PATHFIND is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:303: LIBOPTS_RUN_REALPATH is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:330: LIBOPTS_RUN_STRFTIME is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:363: LIBOPTS_RUN_FOPEN_BINARY is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:386: LIBOPTS_RUN_FOPEN_TEXT is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:158: LIBOPTS_WITHLIB_REGEX is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:260: LIBOPTS_RUN_PATHFIND is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:303: LIBOPTS_RUN_REALPATH is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:330: LIBOPTS_RUN_STRFTIME is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:363: LIBOPTS_RUN_FOPEN_BINARY is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    configure.ac:469: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
    /usr/src/ports/autoconf2.5/autoconf2.5-2.69-3.noarch/src/autoconf-2.69/lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
    src/libopts/m4/libopts.m4:386: LIBOPTS_RUN_FOPEN_TEXT is expanded from...
    src/libopts/m4/libopts.m4:425: INVOKE_LIBOPTS_MACROS is expanded from...
    src/libopts/m4/libopts.m4:560: AM_COND_IF is expanded from...
    src/libopts/m4/libopts.m4:581: LIBOPTS_CHECK is expanded from...
    configure.ac:469: the top level
    libtoolize: $pkgltdldir is not a directory: `/mingw/share/libtool'
    autoreconf-2.69: libtoolize failed with exit status: 1
    Makefile:437: recipe for target 'build-only-gnutls_i686-w64-mingw32.static' failed
    make[1]: *** [build-only-gnutls_i686-w64-mingw32.static] Error 1
    make[1]: Leaving directory '/cygdrive/z/src/mxe'
    real    0m28.566s
    user    0m21.382s
    sys     0m5.541s
    ------------------------------------------------------------
    [log]      /cygdrive/z/src/mxe/log/gnutls
    
    Makefile:437: recipe for target '/cygdrive/z/src/mxe/usr/i686-w64-mingw32.static/installed/gnutls' failed
    make: *** [/cygdrive/z/src/mxe/usr/i686-w64-mingw32.static/installed/gnutls] Error 1

**Comment by rr-** [comment]
Turns out I had broken environment.

- I had directory `C:\MinGW` (rather than `C:\mingw`) - this might be worth looking into
- this was not a part of mingw-w64 tool chain, i.e. it contained `bin\g++` rather than `bin\i686-w64-mingw32-g++`.

Renaming it to something else and installing `libtool` with `apt-cyg` seems to have resolved the issue.

**Comment by TimothyGu** [comment]
And, we don't support Cygwin officially :)
