### ISSUE TITLE
broken package boost (shared targets)

### ISSUE THREAD

**Issue by starius** [mxe/mxe#724]
Commit 465131a2b67fd712724fd7.
Boost fails to build under shared targets:
[i686-w64-mingw32.shared](http://redjohn.tk/files/boost_i686-w64-mingw32.shared)
[x86_64-w64-mingw32.shared](http://redjohn.tk/files/boost_x86_64-w64-mingw32.shared)

**Comment by phamhieu** [comment]
Apply this fix https://github.com/mxe/mxe/commit/29f8a035095f9cba529c5bfe061e0bb725007715 then you can build.

**Comment by TimothyGu** [comment]
Okay then.
