### ISSUE TITLE
[no-build] Package libzdb and Flex

### ISSUE THREAD

**Issue by phamhieu** [mxe/mxe#738]
Hi, I'm working a SeaFile server cross-build for Windows. I tried to add a new package "Libzdb" to MXE.

1. I create "libzdb.mk" to pull and build the source from http://www.tildeslash.com/libzdb/dist. However, the result is always [no-build].  
2. I get the example .mk file from flex.mk [https://github.com/mxe/mxe/blob/master/src/flex.mk]
However, it seems that Flex.mk not work also.  

I'm just know about MXE last weekend. Hope that someone can give me an idea why this won't work. 

Many Thanks.

FYI: i'm working on Ubuntu 14.04. 
       MXE: i686-w64-mingw32.shared

```
# This file is part of MXE.
# See index.html for further information.

PKG             := libzdb
$(PKG)_IGNORE   :=
$(PKG)_VERSION  := 3.0
$(PKG)_CHECKSUM := bcf14c11cfcd0c05ecc8740f43cd0d6170406dc1
$(PKG)_SUBDIR   := libzdb-$($(PKG)_VERSION)
$(PKG)_FILE     := libzdb-$($(PKG)_VERSION).tar.gz
$(PKG)_URL      := http://www.tildeslash.com/libzdb/dist/$($(PKG)_FILE)
$(PKG)_DEPS     := gcc

define $(PKG)_BUILD_$(BUILD)
    mkdir '$(1).build'
    cd    '$(1).build' && '$(1)/configure' \
        --prefix='$(PREFIX)/$(TARGET)' \
    $(MAKE) -C '$(1).build' -j '$(JOBS)'
    $(MAKE) -C '$(1).build' -j 1 install
endef
```

**Comment by TimothyGu** [comment]
Don't adapt from flex.mk. Flex is a special kind of package called "host package." That means that it is not supposed to be run on Windows, but instead on the build system.

Try adapting from a library like say opus.mk.
