### ISSUE TITLE
Adding flags in QT

### ISSUE THREAD

**Issue by bielpiero** [mxe/mxe#739]
Hi,

I'm trying to add this flag in a QT (5.4) project:

$(pkg_config --cflags --libs libola)

which QMAKE flag can I use so that when I compile and make the project with MXE it could be recognized, and it doesn't thow an error?

thank you so much for your help

**Comment by mabrand** [comment]
Qmake can call pkg-config for you. Normally you put something like this in your .pro file:

    CONFIG += link_pkgconfig
    PKGCONFIG += libola

You can find some examples of this in the qtbase sources and patches.

**Comment by bielpiero** [comment]
I've tryed out that and it's fails on executing:
~/mxe/usr/i686-w64-mingw32.static/qt/bin/qmake

throws: package libola not found.

the thing is that I need to add the flags: --cflags and --libs to work..

in a normal Makefile, it works, now I need this to work in QT and compile it with mxe/qmake.

thanks for your help.

**Comment by TimothyGu** [comment]
libola is not in MXE.
