### ISSUE TITLE
x86_64-linux-gnu/libsqlite3.so: file not recognized

### ISSUE THREAD

**Issue by phamhieu** [mxe/mxe#740]
I installed sqilte3 for MXE. The sqlite3.pc exists at "/opt/mxe/usr/i686-w64-mingw32.shared/lib/pkgconfig"

However, when i compile with MXE, the system libsqlite3.so is used.
```
... -L/opt/mxe/usr/i686-w64-mingw32.shared/lib -L/opt/mxe/usr/i686-w64-mingw32.shared/lib/../lib -L/usr/lib/x86_64-linux-gnu

/usr/lib/x86_64-linux-gnu/libsqlite3.so: file not recognized: File format not recognized
```

My PATHs settings:
```
export MXE_PATH=/opt/mxe
export PREFIX=$MXE_PATH/usr/i686-w64-mingw32.shared
export PKG_CONFIG_PATH=/usr/lib/pkgconfig/
export PKG_CONFIG_PATH_i686_w64_mingw32_shared=$PREFIX/lib/pkgconfig/
export PATH=$MXE_PATH/usr/bin:$PREFIX/bin:$PATH
export PKG_CONFIG_BIN_i686_w64_mingw32_shared=i686-w64-mingw32.shared-pkg-config
```
 Are there anything I can do to force it uses the MXE sqlite3 lib instead? Thank you.

**Comment by TimothyGu** [comment]
Your configuration is a little bit off:

> ```sh
export PKG_CONFIG_PATH=/usr/lib/pkgconfig/
export PKG_CONFIG_PATH_i686_w64_mingw32_shared=$PREFIX/lib/pkgconfig/
```

You don't need these two, and they might cause troubles.

> ```sh
export PATH=$MXE_PATH/usr/bin:$PREFIX/bin:$PATH
```

This is the wrongest part. You are not supposed to add `$PREFIX/bin` to your `$PATH`. It confuses configure scripts. Do this:

 ```sh
export PATH=$MXE_PATH/usr/bin:$PATH
```

(This is also written on the website if you look carefully enough :)

> ```sh
export PKG_CONFIG_BIN_i686_w64_mingw32_shared=i686-w64-mingw32.shared-pkg-config
```

This shouldn't be needed either.
