### ISSUE TITLE
Update Qt to 5.5.0

### ISSUE THREAD

**Issue by tru** [mxe/mxe#747]
Qt5.5.0 was just released and it contains quite a bit of improvements. It would be nice to have MXE support this. I just tried a simple update switching 5.4 to 5.5 in the makefile and building, but the patches doesn't fit (expected) and there might be additional differences since Qt5.5 doesn't build OpenGL desktop specific versions anymore just dynamic ones, so support for ANGLE needs to be in there as well.

**Comment by TimothyGu** [comment]
@mabrand, would be cool if you can take a look at this :)

**Comment by mabrand** [comment]
Yeah, I've been working on that. I haven't run into the opengl problem reported above, but I have some minor issues with other modules to sort out.

**Comment by TimothyGu** [comment]
Take your time!

**Comment by mbunkus** [comment]
Any progress on this? I've tried to update to 5.5.0 myself but haven't had much luck. I've manually re-created qtbase-1.diff by manually applying the intended changes in the 5.5.0 source tree, adjusted qtbase.mk to change the 5.4 directory 5.5, called `make update-package-qtbase`. So far, so good. Now, however, I get linker errors when compiling qtbase, something like this:

    /home/mosu/prog/video/mingw/cross/tmp-harfbuzz-x86_64-w64-mingw32.static/harfbuzz-1.0.1/src/hb-glib.cc:180: undefined reference to `g_unicode_script_from_iso15924'
    /home/mosu/prog/video/mingw/cross/usr-master-20150802-gcc492/bin/../lib/gcc/x86_64-w64-mingw32.static/4.9.2/../../../../x86_64-w64-mingw32.static/lib/../lib/libharfbuzz.a(libharfbuzz_la-hb-glib.o):hb-glib.cc:(.rdata$.refptr.g_bytes_unref[.refptr.g_bytes_unref]+0x0): undefined reference to `g_bytes_unref'

That's where I'm stuck in my experiments for the moments.

**Comment by mabrand** [comment]
I just pushed a new qt-5.5.0 branch. https://github.com/mxe/mxe/tree/qt-5.5.0 This still uses opengl, not ANGLE.

Everything builds except qtwebkit, which is deprecated anyway. If anybody wants to try to get it working, please do.

Let me know what you think of this.

**Comment by mbunkus** [comment]
Thanks for your work. The compilation of both MXE itself and my application succeeds without problems. The application itself works just fine, too.

**Comment by mabrand** [comment]
Thanks for trying it out.

Would anybody object to removing or disabling qtwebkit, since the build fails and it's deprecated in Qt 5.5. I'm not sure why it fails. Possibly it requires ANGLE support, which we don't have.

The configure script for qtbase (as opposed to configure.exe) doesn't support ANGLE or the "dynamic" option. These features could be added (ported from  configure.exe)  without too much trouble. I don't personally know if our mingw-w64 supplies the necessary SDK. Does anybody know about this or want to research it?

**Comment by tru** [comment]
Well does the replacement webengine build? If not that might be a problem.

**Comment by mabrand** [comment]
Yes it does. Please try it if you can. All modules build except qtwebkit.

**Comment by tru** [comment]
We checked it out. WebEnigne does not build:

```
Qt WebEngine can currently only be built for Linux (GCC), Windows (MSVC 2013), O
S X (XCode 5.1+) or Qt for Device Creation.
QtWebEngine will not be built.
```

I don't think WebKit can be removed if that is not addressed.
