### ISSUE TITLE
portaudio patch gets rejected

### ISSUE THREAD

**Issue by DevSolar** [mxe/mxe#748]
Problem:
The portaudio-1-fixes.patch gets rejected.

Analysis:
The troublesome hunk is for the source file src/hostapi/wasapi/pa_win_wasapi.c. Cause for the rejection is a difference in line endings. (pa_win_wasapi.c has CR/LF endings, the patch file only LF.)

Fix:
Add carriage return (0x0d) to the relevant lines of the patchfile.
Alternatively patch could be run with  -l  or  --ignore-whitespace, but that would be quite intrusive and might break other packages.

**Comment by TimothyGu** [comment]
Fixed in #746.
