### ISSUE TITLE
build-pkg: add libtool-bin to dependencies of mxe-requirements Debian package (Jessie+)

### ISSUE THREAD

**Issue by starius** [mxe/mxe#754]
see #680

**Comment by starius** [comment]
I think, we should provide packages for Debian Wheezy too. Many systems still use Debian Wheezy (or corresponding Ubuntu version), for example Travis CI. I propose to build two variants of package `mxe-requirements`: for Debian <= Wheezy and for Debian >= Jessie.

**Comment by TimothyGu** [comment]
@starius we don't support Debian Wheezy, but I agree with your comment on Ubuntu.
