### ISSUE TITLE
disable push in Travis on pull requests

### ISSUE THREAD

**Issue by starius** [mxe/mxe#760]
Some commands from `.travis.yml` require admin access to main MXE repo. When Travis builds pull requests, it disables all dangerous variables. (Otherwise anybody can steal their values by making a pull request with code which just prints these variables to Travis log.) Therefore with current `.travis.yml` any pull request is marked by Travis as failing. Example: #759 and [build](https://travis-ci.org/mxe/mxe/builds/70342680).

There are 2 resolutions:
 * Disable these commands if a pull request is built. [Check](http://docs.travis-ci.com/user/environment-variables) environment variable `TRAVIS_PULL_REQUEST` (The pull request number if the current job is a pull request, “false” if it’s not a pull request.)
 * Do not build pull requests. Switch off "Build pull requests" in [settings of the repo](https://travis-ci.org/mxe/mxe/settings).

**Comment by TimothyGu** [comment]
"Build pull requests" in settings switched off. Thanks for the reminder!
