### ISSUE TITLE
libtool-bin required when building for Ubuntu

### ISSUE THREAD

**Issue by nathan-osman** [mxe/mxe#761]
I tried to build the `gcc` target on an Ubuntu machine after installing the Debian packages listed under the "Requirements" section. I immediately received the following error:

    Missing requirement: libtool
    
    Please have a look at "index.html" to ensure
    that your system meets all requirements.

I installed the `libtool-bin` package and was then able to begin compilation. This package should probably be added to the list of packages required for building.

**Comment by TimothyGu** [comment]
Fixed in 26ac245ffa69856248e519fde184c162f89b2f63.
