### ISSUE TITLE
why does yasm built natively?

### ISSUE THREAD

**Issue by starius** [mxe/mxe#763]
Hello,

package `yasm` [produces](https://gist.github.com/starius/59625347cd68a21d9cc9#file-dups-txt-L62) same files for all targets:
```
usr/include/libyasm/*.h
usr/lib/libyasm.a
```

YASM build rule is as follows:
```
    # native build of yasm - will the same for all targets
    # but we don't want to conflict with an un-prefixed version
    mkdir '$(1).native'
    cd '$(1).native' && '$(1)/configure' \
        --prefix='$(PREFIX)' \
        --program-prefix='$(TARGET)-' \
        --disable-nls \
        --disable-python
    $(MAKE) -C '$(1).native' -j '$(JOBS)' install

    # yasm is always static
    cd '$(1)' && '$(1)/configure' \
        --host='$(TARGET)' \
        --build="`config.guess`" \
        --prefix='$(PREFIX)/$(TARGET)' \
        --disable-nls
    $(MAKE) -C '$(1)' -j '$(JOBS)' install
```

As I understand, first section of the rule results in generating same files for all targets.

So my question is: why does yasm built natively? Where are these files used?

**Comment by TimothyGu** [comment]
> why does yasm built natively?

yasm is an assembler, and is considered part of the toolchain like gcc. But, it is an architecture-independent package, so it produces the same files.

> Where are these files used?

Nowhere AFAIK.
