### ISSUE TITLE
Sourceforge down == MXE down

### ISSUE THREAD

**Issue by rr-** [mxe/mxe#765]
Apparently Sourceforge experiences some serious problems:

- https://twitter.com/sfnet_ops?lang=en
- This log:

     >     rr-@tornado:~/src/ext/mxe$ wget 'http://downloads.sourceforge.net/#!/project/mingw-w64/mingw-w64/mingw-w64-release/mingw-w64-v4.0.2.tar.bz2' -qO-
    >     <html><head>
    >     <title>SourceForge</title>
    >     
    >     <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    >     <script src="//sourceforge.net/js/mirrors.js"></script>
    >     <script src="/js/sf.js"></script>
    >     <script>
    >     var DR_loc = DR_parse_hash_url();
    >     if (DR_loc) {
    >         DR_sf_main(DR_loc);
    >     } else {
    >         window.location.href = 'http://sourceforge.net/home.html';
    >     }
    >     </script>
    >     </head><body>
    >     <noscript>
    >     We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
    >     the use of javascript to function.  Please check back later.
    >     </noscript>
    >     </body></html>

The result? Can't compile half of the packages:

    rr-@tornado:~/src/ext/mxe$ make libpng -j4 JOBS=4
    [download]  mingw-w64                                                                                      
    [download]  libpng                                                                                         
    [build]     gcc-mpc              i686-w64-mingw32.static                                                   
    
    Download failed or wrong checksum of package libpng!
    ------------------------------------------------------------
    --2015-07-17 21:17:36--  http://downloads.sourceforge.net/
    Reusing existing connection to downloads.sourceforge.net:80.
    HTTP request sent, awaiting response... 200 OK
    Length: 639 [text/html]
    Saving to: ‘STDOUT’
         0K                                                       100%  505M=0s
    2015-07-17 21:17:36 (505 MB/s) - written to stdout [639/639]
    ------------------------------------------------------------
    [log]      /home/rr-/src/ext/mxe/log/libpng-download
    
    Makefile:349: recipe for target 'download-only-libpng' failed
    make: *** [download-only-libpng] Error 1
    make: *** Waiting for unfinished jobs....
    
    Download failed or wrong checksum of package mingw-w64!
    ------------------------------------------------------------
    --2015-07-17 21:17:36--  http://downloads.sourceforge.net/
    Reusing existing connection to downloads.sourceforge.net:80.
    HTTP request sent, awaiting response... 200 OK
    Length: 639 [text/html]
    Saving to: ‘STDOUT’
         0K                                                       100%  452M=0s
    2015-07-17 21:17:36 (452 MB/s) - written to stdout [639/639]
    ------------------------------------------------------------
    [log]      /home/rr-/src/ext/mxe/log/mingw-w64-download
    
    Makefile:349: recipe for target 'download-only-mingw-w64' failed
    make: *** [download-only-mingw-w64] Error 1
    [done]      gcc-mpc              i686-w64-mingw32.static                                    5504 KiB       0m3.843s

It would be a good idea to protect against such scenario in the future by adding a hardcoded list of fallback mirrors for each package (especially the essential ones such as mingw-w64).

Also looking at their Twitter account, this is hardly the first time something like this happens.

**Comment by TimothyGu** [comment]
We do have a mirror for all the source files, but we currently only fallback on it if the **downloading** fails, not if the checksum fails. I'll work on it in the coming week.

**Comment by tonytheodore** [comment]
This is very tricky - if the checksum fails, we should stop. The real problem is the "200" response - we can't even check the headers in that case.

**Comment by tonytheodore** [comment]
I can't see a solution to this (short of parsing the response body, but then what?). We already set `--user-agent` to avoid a "browser" response.

We have to respect the "200" response and fail on checksum errors as the "corrected" file may not have propagated yet. Yes, people should never do that, but they do.

**Comment by tonytheodore** [comment]
The only workaround I can think of is:
```
$ make download SOURCEFORGE_MIRROR=example.com
[download]  mingw-w64
MXE Warning! Downloading mingw-w64 from backup.
```
