### ISSUE TITLE
bad checksum and file corrupted for curl

### ISSUE THREAD

**Issue by lidiriel** [mxe/mxe#769]
Hi, thank you for your mxe framework.

I think there is a small error with the sha1 checksum of curl and lzma archiv. I think the fiel is corrupted.

Failed to build package curl for target x86_64-w64-mingw32.static!
------------------------------------------------------------
tar: Fin prématurée rencontrée dans l'archive. 
tar: Fin prématurée rencontrée dans l'archive.
tar: Error is not recoverable: exiting now
Makefile:412: recipe for target '/mxe/usr/x86_64-w64-mingw32.static/installed/curl' failed
make: *** [/mxe/usr/x86_64-w64-mingw32.static/installed/curl] Error 1

for working i have changed the src/curl.mk  checksum and file 

$(PKG)_CHECKSUM := 0214cb7174c505476f1fb0521ec7d987347cb748
$(PKG)_FILE     := curl-$($(PKG)_VERSION).tar.gz

and all is ok.

Regards

**Comment by TobiX** [comment]
The file isn't corrupted on the server. This seems to be a download error on your end...

**Comment by TimothyGu** [comment]
Can't reproduce it here.
