### ISSUE TITLE
freetds fails to download/build

### ISSUE THREAD

**Issue by uwehermann** [mxe/mxe#770]
```
Download failed or wrong checksum of package freetds!
------------------------------------------------------------
--2015-07-24 19:01:14--  http://d1yihgixbnrglp.cloudfront.net/freetds%2D0%2E95%2E8%2Etar%2Ebz2
Resolving d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)... 54.192.47.47, 54.192.44.201, 54.230.46.49, ...
Connecting to d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)|54.192.47.47|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-24 19:01:14 ERROR 404: Not Found.
Download failed!
------------------------------------------------------------
```

Logfile:

```
--2015-07-24 19:01:12--  http://ftp.mirrorservice.org/sites/distfiles.finkmirrors.net/sha1/085ced804cd07b8a588098822483b827138f88e0/freetds-0.95.8.tar.bz2
Resolving ftp.mirrorservice.org (ftp.mirrorservice.org)... 212.219.56.184
Connecting to ftp.mirrorservice.org (ftp.mirrorservice.org)|212.219.56.184|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-24 19:01:13 ERROR 404: Not Found.

--2015-07-24 19:01:13--  ftp://ftp.freetds.org/pub/freetds/stable/freetds-0.95.8.tar.bz2
           => ‘-’
Resolving ftp.freetds.org (ftp.freetds.org)... 38.117.134.18
Connecting to ftp.freetds.org (ftp.freetds.org)|38.117.134.18|:21... failed: Connection refused.
--2015-07-24 19:01:13--  http://s3.amazonaws.com/mxe-pkg/freetds%2D0%2E95%2E8%2Etar%2Ebz2
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.1.216
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.1.216|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-24 19:01:14 ERROR 404: Not Found.

--2015-07-24 19:01:14--  http://d1yihgixbnrglp.cloudfront.net/freetds%2D0%2E95%2E8%2Etar%2Ebz2
Resolving d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)... 54.192.47.47, 54.192.44.201, 54.230.46.49, ...
Connecting to d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)|54.192.47.47|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-24 19:01:14 ERROR 404: Not Found.


Download failed!
```

**Comment by TobiX** [comment]
The 0.95.x tarballs of FreeTDS seem to be quite volatile and are just git snapshots anyways...
(See Homebrew/homebrew#41100 and Homebrew/homebrew#41900)
How about pulling the source directly from github instead?

**Comment by RandomReaper** [comment]
freetds gone again

**Comment by peakay** [comment]
i concur, nothing appears to have changed

**Comment by iamcare** [comment]
Nothing changed yet

**Comment by uwehermann** [comment]
I personally need this for qt, so I used this workaround for the time being (dropping freetds support in qt):

```
--- a/src/qt.mk
+++ b/src/qt.mk
@@ -8,7 +8,7 @@ $(PKG)_CHECKSUM := 76aef40335c0701e5be7bb3a9101df5d22fe3666
 $(PKG)_SUBDIR   := $(PKG)-everywhere-opensource-src-$($(PKG)_VERSION)
 $(PKG)_FILE     := $(PKG)-everywhere-opensource-src-$($(PKG)_VERSION).tar.gz
 $(PKG)_URL      := http://download.qt.io/official_releases/qt/4.8/$($(PKG)_VERSION)/$($(PKG)_FILE)
-$(PKG)_DEPS     := gcc postgresql freetds openssl zlib libpng jpeg libmng tiff sqlite dbus
+$(PKG)_DEPS     := gcc postgresql openssl zlib libpng jpeg libmng tiff sqlite dbus
 
 define $(PKG)_UPDATE
     $(WGET) -q -O- http://download.qt-project.org/official_releases/qt/4.8/ | \
@@ -56,7 +56,6 @@ define $(PKG)_BUILD
         -qt-sql-odbc \
         -qt-sql-psql \
         -no-sql-mysql \
-        -qt-sql-tds -D Q_USE_SYBASE \
         -system-zlib \ 
         -system-libpng \
         -system-libjpeg \
```

**Comment by TobiX** [comment]
@iamcare Those are all ancient. There is currently no reliable download for the 0.95 series, which is why I suggested using snapshots from git directly...

**Comment by iamcare** [comment]
@TobiX I attempted that with the md5 it kept saying that it wasnt valid checksum

**Comment by uwehermann** [comment]
@iamcare MXE uses SHA-1 for the checksums btw., MD5 will not match either way.

**Comment by iamcare** [comment]
I am new to all this, can someone fix it? I have no clue.

**Comment by tonytheodore** [comment]
> Connecting to d1yihgixbnrglp.cloudfront.net ...

This is very strange, it looks like everything in our S3 bucket was deleted at some stage and reloaded on the 27th July. I've [removed the outdated mirror](https://github.com/mxe/mxe/commit/d3e48dc0b12006c638324e0c0fd99b7b9a6f908a) so now it should simply fall back to S3.

@TobiX wrote:
> suggested using snapshots from git directly...

If there's any more problems in the future, we'll look at switching over.

**Comment by tonytheodore** [comment]
Our S3 mirrors seem to be working again, based on anecdata of three versions of harfbuzz available at http://s3.amazonaws.com/mxe-pkg

There's no way of knowing what happened late July, so I'm closing this for now.

**Comment by tonytheodore** [comment]
>> suggested using snapshots from git directly...

> If there's any more problems in the future, we'll look at switching over.

Not download problems, but it hasn't had an update macro for a long time https://github.com/mxe/mxe/commit/746f4700152cc8a5aa945db8a3649a3d465d992a. Now added https://github.com/mxe/mxe/commit/cf5fb10422ddc6be4c9717fc08ccc98a093aaa8b based on what they release as "stable" tarballs. I'm testing the update from 0.95.8 --> 0.95.73 and will push it tomorrow.

@uwehermann not sure how multiple mirrors could fail simultaneously - just one for the statisticians. Our S3 (and CDN) have archives back to late July so you should be right to drop the workaround.
