### ISSUE TITLE
jsoncpp lib

### ISSUE THREAD

**Issue by nieknooijens** [mxe/mxe#772]
Hi there

I'd like to create a package for https://github.com/open-source-parsers/jsoncpp
but creating packages is pretty undocumented. it does compile and install normally using cmake and the provided toolchain file, so it shouldn't be hard to add it to mxe.

[edit]
something like this would probably work:

```make
PKG             := jsoncpp
$(PKG)_IGNORE   := 
$(PKG)_VERSION  := 1.6.5
$(PKG)_CHECKSUM := a8354732489a4e3bf95ba801a300032e731b5aa8
$(PKG)_SUBDIR   := $(PKG)-$($(PKG)_VERSION)
$(PKG)_FILE     := $(PKG)-$($(PKG)_VERSION).tar.gz
$(PKG)_URL      := https://github.com/open-source-parsers/jsoncpp/archive/$($(PKG)_VERSION).tar.gz
$(PKG)_DEPS     := gcc

define $(PKG)_BUILD
 	mkdir '$(1)/build'
	cd '$(1)/build' && cmake ..
	$(MAKE) -C '$(1)/cross_build' -j 1 install VERBOSE=1
endef


$(PKG)_BUILD_i686-pc-mingw32    = $(subst @special-target@, x86-win32-gcc,    $($(PKG)_BUILD))
$(PKG)_BUILD_i686-w64-mingw32   = $(subst @special-target@, x86-win32-gcc,    $($(PKG)_BUILD))
$(PKG)_BUILD_x86_64-w64-mingw32 = $(subst @special-target@, x86_64-win64-gcc, $($(PKG)_BUILD))
```

but I haven't got it compiling yet.

**Comment by TobiX** [comment]
There is at least http://mxe.cc/#creating-packages for creating packages, but better documentation is always appreciated ;)

**Comment by pavelvat** [comment]
#785

**Comment by TimothyGu** [comment]
Done by @pavelvat in #785.

**Comment by nieknooijens** [comment]
ok many many thanks! I'll try it immediately.
