### ISSUE TITLE
dll libharfbuzz

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#786]
libharfbuzz-0.dll  -->  libharfbuzz-1.dll

**Comment by TimothyGu** [comment]
No I don't think so. https://github.com/behdad/harfbuzz/blob/master/NEWS#L28 says that SONAME was NOT bumped in 1.0.0.

**Comment by pavelvat** [comment]
My Qt application don't launch and says:  libharfbuzz-1.dll was not found.

**Comment by TimothyGu** [comment]
I think it is a problem with your Qt build system, although I can't say for sure right now.
