### ISSUE TITLE
How to create .lib files without Windows and MSVC?

### ISSUE THREAD

**Issue by andrewrk** [mxe/mxe#793]
One can use mingw to generate .def files like this:

```
-Wl,--output-def,libsoundio.def
```

Then one can copy the files to Windows with MSVC installed and use lib.exe like this:

```
lib.exe /machine:X64 /def:libsoundio.def
```

This will create libsoundio.lib. 

Is there a way to do this without leaving the environment where mxe is installed? Ideally coming up with .lib files would not require booting Windows.

**Comment by TimothyGu** [comment]
It doesn't seem possible. Reading `.lib` is supported by binutils/gcc, but writing is not, because there is no need for it. I believe using the `.dll.a` files in MSVC should work just fine.

**Comment by andrewrk** [comment]
I just tested, MSVC indeed accepts .dll.a in addition to .lib. I did not know that before. Thank you for the tip and apologies for the noise.

**Comment by TimothyGu** [comment]
Great to hear that it worked. We are all here to learn to no worries.
