### ISSUE TITLE
Crash on starting a QT5 static program

### ISSUE THREAD

**Issue by Gloorf** [mxe/mxe#811]
When i start the .exe (using wine or on a win7 computer), i have the following error : 
> This application failed to start because it could not find or load the Qt platform plugin "windows".

The qt build has been done like this : 
```shell
git clone https://github.com/mxe/mxe.git
cd mxe 
make JOBS=4 MXE_TARGETS=i686-w64-mingw32.static qt5
```

Compilation as follows : 
```shell
export PATH=/home/glorf/bin/mxe/usr/bin:$PATH
cd ~/bin/code/project
i686-w64-mingw32.static-qmake-qt5 -o ~/bin/build-project
cd ~/bin/build-project
make release
```
The [.pro](https://github.com/Gloorf/kustom/blob/master/kustom-sheet-creator/kustom-sheet-creator.pro) for my project (nothing special here). I'm running a debian sid 64 bits with a 4.1 kernel.

**Comment by tonytheodore** [comment]
Are you sure you're doing a static build? I just tried and ended up with a 15MB .exe that launches fine.

I've only really seen that error with shared builds and you need to either set the env var  `QT_QPA_PLATFORM_PLUGIN_PATH` or make sure the plugins directory is in the right place relative to the .exe.

**Comment by Gloorf** [comment]
Yes, i have a 14.3MB .exe at the end of the compilation. This worked before (couple of months ago, so an older version of mxe) with the same code, so i never bothered with the `QT_QPA_PLATFORM_PLUGIN_PATH` (don't know what this is, to be honest). I've followed [this guide](http://stackoverflow.com/questions/14170590/building-qt-5-on-linux-for-windows/14170591#14170591) for QT cross compilation

**Comment by tonytheodore** [comment]
> so i never bothered with the QT_QPA_PLATFORM_PLUGIN_PATH

It should make no difference for static builds. All I did was (nothing special):
```
git clone https://github.com/Gloorf/kustom
cd kustom
mkdir 32
i686-w64-mingw32.static-qmake-qt5 -o ./32/
cd 32
make release
```
and ended up with a working .exe. Afraid I can't be of much help.

**Comment by Gloorf** [comment]
Oh god, thanks :)
It's completely stupid, but i was invoking qmake-qt5 in ~/code/kustom/kustom-sheet-creator/ for some reason ... Calling qmake-qt5 in  ~/code/kustom/ worked, thanks again !
