### ISSUE TITLE
many packages change usr/<target>/share/cmake/mxe-conf.cmake

### ISSUE THREAD

**Issue by starius** [mxe/mxe#823]
Following packages create/append to file `usr/<target>/share/cmake/mxe-conf.cmake`:
  * pkgconf
  * boost
  * hdf5
  * qt
  * qtbase

This makes Debian packaging of MXE packages hard.
I propose to create a subdirectory and include all the files from `mxe-conf.cmake`:

```cmake
file(GLOB mxe_cmake_files
    "/path/to/mxe/usr/<target>/share/cmake/mxe-conf.d/*.cmake"
)
foreach(mxe_cmake_file ${mxe_cmake_files})
    include(${mxe_cmake_file})
endforeach()
```

Package pkgconf creates main file `mxe-conf.cmake` including all cmake files from directory `mxe-conf.d`. Other packages (boost, qt, ...) create a file in directory `mxe-conf.d`.

**Comment by tonytheodore** [comment]
That sounds like a good proposal, I'll have a look at implementing it. I'll probably create an `mxe-conf` package that takes care of these types of things and move them out of `pkgconf`.

What do you think about a prefixed cmake wrapper script that knows where to find the toolchain file?

**Comment by starius** [comment]
> What do you think about a prefixed cmake wrapper script that knows where to find the toolchain file?

Sounds good. If implemented, it should be applied in MXE packages using cmake to build. One note: please do not break current approach `cmake -DCMAKE_TOOLCHAIN_FILE=...`. It should be preserved for backward compatibility.

**Comment by tonytheodore** [comment]
The current approach will always work - the wrapper script will simply be a shorthand way.

**Comment by tonytheodore** [comment]
Haven't done the wrapper script yet, but #836 seems to be working with quick testing of cmake packages that use boost (armadillo assimp).
