### ISSUE TITLE
some packages run wine

### ISSUE THREAD

**Issue by starius** [mxe/mxe#841]
Many packages include `configure` step, which can run `wine` (from gtkimageview's log):

```
configure:2945: checking for C compiler default output file name
configure:2967: i686-w64-mingw32.static-gcc    conftest.c  >&5
configure:2971: $? = 0
configure:3009: result: a.exe
configure:3026: checking whether the C compiler works
configure:3036: ./a.exe
configure:3040: $? = 0
configure:3057: result: yes
configure:3064: checking whether we are cross compiling
configure:3066: result: no
```

On other machine (without wine):

```
configure:2945: checking for C compiler default output file name
configure:2967: i686-w64-mingw32.static-gcc    conftest.c  >&5
configure:2971: $? = 0
configure:3009: result: a.exe
configure:3026: checking whether the C compiler works
configure:3036: ./a.exe
./configure: line 3038: ./a.exe: cannot execute binary file: Exec format error
configure:3040: $? = 126
configure:3057: result: yes
configure:3064: checking whether we are cross compiling
configure:3066: result: yes
```

Existence of `wine` affects the value of `whether we are cross compiling`.

I know that MXE doesn't use wine. Can we force this policy by disabling wine even if it exists when building?

**Comment by tonytheodore** [comment]
> Can we force this policy by disabling wine even if it exists when building?

AFAIK no. Something about the way wine is installed means you can't easily disable it for a single session or invocation. In the past, explicitly setting `ac_cv_build` and `--build` bypassed the detection but maybe something has changed in more recent autotools.

**Comment by tonytheodore** [comment]
Can you post the full logs of both to see if there's any real change in what is detected?

**Comment by starius** [comment]
[With wine](http://redjohn.tk/mxe/0d8f76e8586e408e7067211ace94ea1586a37175/log/gtkimageview_i686-w64-mingw32.static)

[Without wine](http://elric.ga/mxe/e0fadbb696d8eca564f62531ad1db463da51f359/log/gtkimageview_i686-w64-mingw32.static)

[Backup](https://gist.github.com/starius/196698d95a702164e505)

**Comment by tonytheodore** [comment]
> It was created by gtkimageview configure 1.6.4, which was
generated by GNU Autoconf 2.62.

It think re-creating `configure` with a recent autoconf will fix the message (and I'm pretty sure it's only a harmless message).

**Comment by starius** [comment]
Using WINEPREFIX=/ breaks wine for non-root users.

```
$ ./usr/i686-w64-mingw32.static/bin/test-lua.exe
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
$ echo $?
0

$ WINEPREFIX=/ ./usr/i686-w64-mingw32.static/bin/test-lua.exe
wine: / is not owned by you
$ echo $?
1
```

See http://wiki.winehq.org/FAQ#wineprefix

Maybe we should set WINEPREFIX=/ for build tasks.

**Comment by tonytheodore** [comment]
> Maybe we should set WINEPREFIX=/ for build tasks.

That would be ideal. Can you check if setting it in the Makefile is sufficient or if it needs to be done individually for packages?

**Comment by starius** [comment]
I'm checking the build with the following patch:
```diff
diff --git a/Makefile b/Makefile
index b0acd09..80c2def 100644
--- a/Makefile
+++ b/Makefile
@@ -48,6 +48,7 @@ PKGS       := $(call set_create,\
     $(shell $(SED) -n 's/^.* class="package">\([^<]*\)<.*$$/\1/p' '$(TOP_DIR)/index.html'))
 BUILD      := $(shell '$(EXT_DIR)/config.guess')
 PATH       := $(PREFIX)/$(BUILD)/bin:$(PREFIX)/bin:$(PATH)
+WINEPREFIX := /
 
 # All pkgs have (implied) order-only dependencies on MXE_CONF_PKGS.
 # These aren't meaningful to the pkg list in index.html so
@@ -130,7 +131,7 @@ define MXE_GET_GITHUB_SHA
 endef
 
 # use a minimal whitelist of safe environment variables
-ENV_WHITELIST := PATH LANG MAKE% MXE% %PROXY %proxy LD_LIBRARY_PATH ACLOCAL_PATH
+ENV_WHITELIST := PATH LANG MAKE% MXE% %PROXY %proxy LD_LIBRARY_PATH ACLOCAL_PATH WINEPREFIX
 unexport $(filter-out $(ENV_WHITELIST),$(shell env | cut -d '=' -f1))
 
 SHORT_PKG_VERSION = \
```

Is it the right place to add environment variables?

**Comment by tonytheodore** [comment]
> Is it the right place to add environment variables?

I'd probably add `export WINEPREFIX := ...` under the `unexport` line and not add it to the whitelist.

> Path / may be writable for the user. I think, setting path to . is more reliable.

Can something like `/dev/null` work? Should fail for everyone.

**Comment by starius** [comment]
`WINEPREFIX=.` doesn't work. Wine is executed somehow...

```
configure:2945: checking for C compiler default output file name
configure:2967: i686-w64-mingw32.static-gcc    conftest.c  >&5
configure:2971: $? = 0
configure:3009: result: a.exe
configure:3026: checking whether the C compiler works
configure:3036: ./a.exe
configure:3040: $? = 0
configure:3057: result: yes
configure:3064: checking whether we are cross compiling
configure:3066: result: no
configure:3069: checking for suffix of executables
configure:3076: i686-w64-mingw32.static-gcc -o conftest.exe    conftest.c  >&5
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
```

**Comment by tonytheodore** [comment]
Does something like this [readonly directory](https://github.com/tonytheodore/mxe/commit/2ab1d382c4a61f394d730e0645c6e703c731a2ca) work?

**Comment by tonytheodore** [comment]
Actually `$(INSTALL) -m444 -d "$$WINEPREFIX"` is better to ensure we have the shell variable.

**Comment by starius** [comment]
UPD. My first commit doesn't work, but this commit does work for some packages:
```diff
diff --git a/Makefile b/Makefile
index b0acd09..173cdf5 100644
--- a/Makefile
+++ b/Makefile
@@ -132,6 +132,8 @@ endef
 # use a minimal whitelist of safe environment variables
 ENV_WHITELIST := PATH LANG MAKE% MXE% %PROXY %proxy LD_LIBRARY_PATH ACLOCAL_PATH
 unexport $(filter-out $(ENV_WHITELIST),$(shell env | cut -d '=' -f1))
+# disable wine, see https://github.com/mxe/mxe/issues/841
+export WINEPREFIX := /dev/null
 
 SHORT_PKG_VERSION = \
     $(word 1,$(subst ., ,$($(1)_VERSION))).$(word 2,$(subst ., ,$($(1)_VERSION)))
```

Log:

```
configure:3103: ./a.exe
wine: /dev/null is not a directory
configure:3107: $? = 1
configure:3122: result: yes
configure:3129: checking whether we are cross compiling
configure:3131: result: yes
```

I am waiting for gtkimageview (because initial tests were on that package) and then switch to testing your commit with read-only dir and `$(INSTALL) -m444 -d "$$WINEPREFIX"`.

**Comment by starius** [comment]
Works for gtkimageview. Testing your patch...

**Comment by starius** [comment]
It works!
