### ISSUE TITLE
build-pkg: pre-download all packages

### ISSUE THREAD

**Issue by starius** [mxe/mxe#855]
Sometimes download fails in the middle of `build-pkg` progress. It worth detecting (and fixing) failed download earlier not to rebuilt half of packages one more time.

**Comment by ooxi** [comment]
Have you tried `make download`?

**Comment by starius** [comment]
Maybe `build-pkg` should start from `make download`.

**Comment by tonytheodore** [comment]
> Maybe build-pkg should start from make download.

That's a good idea for more automated builds. Using `-jx -k` is also helpful so unrelated downloads proceed and save time after the failed download has been fixed.
