### ISSUE TITLE
How to build x86_64 executable?

### ISSUE THREAD

**Issue by ooxi** [mxe/mxe#861]
I followed the [instructions](http://mxe.cc/#tutorial-5b) on the mxe website and [my project](https://github.com/ooxi/violetland) compiled without any problems (kudos for that!).

But the resulting binary was a x86 executable. How can a generate a x86_64 executable? The host system was debian 8 x86_64

**Comment by pavelvat** [comment]
cmake ... -DCMAKE_TOOLCHAIN_FILE=/where MXE is installed/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake

**Comment by starius** [comment]
Select 64-bit target.

MXE has the following targets:
  * i686-w64-mingw32.static
  * i686-w64-mingw32.shared
  * x86_64-w64-mingw32.static
  * x86_64-w64-mingw32.shared

You can change targets of interest in `settings.mk`. By default, only `i686-w64-mingw32.static` is built.

To compile your project against 64-bit static MXE, use the following command:
```bash
$ cmake ... -DCMAKE_TOOLCHAIN_FILE=/where MXE is installed/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
```

I have replaced `i686` with `x86_64` in [the official tutorial](http://mxe.cc/#tutorial-5b).

By the way, commit 93eaa16faeac34042813fbbdc254594f6fadf126 allows to use prefixed cmake wrapper:

```bash
$ /where MXE is installed/usr/bin/x86_64-w64-mingw32.static-cmake
```

**Comment by ooxi** [comment]
Thanks I'll report back if any problems occur!
