### ISSUE TITLE
switch from sha1 tarball checksum to sha256 checksum

### ISSUE THREAD

**Issue by starius** [mxe/mxe#871]
Attacks against sha1 proved to be not only theoretical. The algorithm sha1 is considered weak. To assess the scale of the disaster:

> The news is that SHA1, a very popular hashing function, is on the way out. Strictly speaking, this development is not new. The first signs of weaknesses in SHA1 appeared (almost) ten years ago. In 2012, some calculations showed how breaking SHA1 is becoming feasible for those who can afford it. In November 2013, Microsoft announced that they wouldn't be accepting SHA1 certificates after 2016.

   (from [community.qualys.com](https://community.qualys.com/blogs/securitylabs/2014/09/09/sha1-deprecation-what-you-need-to-know))

As sha1 is considered non-suitable for SSL certificates, it should not be used for tarball checksums. I think it worth switching from weak hash algorithm to strong one.

Switching from sha1 to sha256 seems to be quite simple procedure for MXE:
  * download all packages and check their checksums
  * change code to use sha256 instead of sha1
  * calculate new checksums with `make update`

Alternatively, sha1 and sha256 can be used simultaneously for some period of time to ease the transition.

**Comment by tonytheodore** [comment]
Sounds like a good idea, a little snippet added to settings.mk will do the trick:
```make
update-all-checksums:
	$(foreach PKG,$(PKGS), \
	    $(if $(value $(PKG)_FILE), \
	        $(SED) -i 's/^\([^ ]*_CHECKSUM *:=\).*/\1 '"`$(call PKG_CHECKSUM,$(PKG))`"'/' '$(TOP_DIR)/src/$(PKG).mk'; \
	    ))
```
only problem is that it will cause a rebuild for everyone so we'll keep it on hold for the time being. I'm updating `pkgconf` in the next few days and will do it then.

**Comment by tonytheodore** [comment]
Actually, there's never a "good" time to do such things and I've wanted to [re-order deps](https://github.com/mxe/mxe/commit/ac7344aaef2b074ee5d58a1bbfee9c43f54b6999) for a while.
