### ISSUE TITLE
Has somebody tried to get Ogre3d cross compiled

### ISSUE THREAD

**Issue by ooxi** [mxe/mxe#878]
I wonder if somebody tried it before or it there are fundamental problems.

**Comment by tonytheodore** [comment]
I haven't tried it, though I don't see fundamental problems. It has both Windows and cross-compilation support (Android etc. mobile platforms), so it "should" be "just" a matter of setting some config options. 

Those aren't nicely defined overlapping sets, but you'll be able to get help from either project if you try.

**Comment by ooxi** [comment]
Thanks for the input!
