### ISSUE TITLE
Building handy tools and applications

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#881]
Following on from #808, #812, and #813 it is indeed very handy to have a source for tools that are outside the scope of mxe. As an example, I've always turned a blind eye to `ffmpeg.exe` that we build since it's great to have a static and recent version on hand.

Some sort of sibling or downstream project (mxe-exe?) could be more liberal in what packages it accepts, and would allow the core mxe to be stricter about focussing on libs and headers. We could also possibly use it as place to gather build recipes and examples.

Any thoughts?

**Comment by starius** [comment]
Maybe name `mxe-apps` is better than `mxe-exe`?

Sister project `mxe-exe` is fine, though for me it is more convenient to have all packages in one place. Having some packages in other repo some kind of synchronization between them is required. Maybe adding executable packages to MXE in disabled state is better. Without `BUILD_APPS` option enabled, these packages do not present. Or something like this.

Technical issue: how to use MXE from mxe-exe? I like the idea of Makefile and xxx.mk per package. Can it be used in mxe-exe without copy-paste from MXE? Ideally, it should work transparently as if mxe-exe's packages are MXE packages. Dependencies should work. For example, building qbittorrent in mxe-exe should cause building qt in MXE.

Another proposal. Add "plugins" for MXE. It would work as follows: a user sets MXE variable `MXE_PLUGINS` to "/path/to/mxe-exe;/path/to/other/plugin" and has all packages from those paths as a part of MXE.

PS. #813 has two libs (lzma and ucl) and one executable (upx), which can be considered as a part of a compiler chain. Many people apply it after stripping a binary to make it even smaller.

PS 2. I have one more candidate package keepassx: 6c561c5f3307944d7b6d7ec3de732b25bf69ed00

**Comment by tonytheodore** [comment]
> Maybe name mxe-apps is better than mxe-exe?

Agreed, apps is a pretty universal term these days and it conveys the idea well.

> it is more convenient to have all packages in one place. 

Indeed, but I'd like to convey the idea that these aren't particularly supported. Maybe having them in a separate place will actually cause more work (issue tracker, repo, etc.) but it's hard to say. 

> Technical issue: how to use MXE from mxe-exe?

It's the old library vs framework debate - does one include MXE from their code and execute it, or does MXE include your code and execute it? I was mostly thinking of the former with some sort of git submodule approach to keep things synced, however ...

> Another proposal. Add "plugins" for MXE.

I really like this idea, I do something similar in my `settings.mk`. It covers almost everything I can imagine about customising or extending MXE for normal users and we don't have to pre-empt use cases very much. I might implement my optional native tools this way to see how it works.

Maybe something like an `opt` directory at the top level, under that we can have `apps`, `native` etc. The *.mk files in here should be self-contained with their website metadata and package maintainer field (either gh user or email) and not have an entry in index.html. Updates can be made directory aware with `$(PKG)_MAKEFILE := $(lastword $(MAKEFILE_LIST))` - I can see this working.
