### ISSUE TITLE
Missing requirements: gcc, g++ on FreeBSD

### ISSUE THREAD

**Issue by starius** [mxe/mxe#900]
MXE complaints about missing gcc/g++:
```
Missing requirement: gcc
Missing requirement: g++
```

FreeBSD doesn't provide `gcc` and `g++` commands anymore. Only versioned names like `gcc48`.

The only method to pass this MXE check on FreeBSD I know is creating symlinks `gcc` and `g++` which is not clean. Can MXE use environment variables `CC` and `CPP` to get native compilers' names?

**Comment by tonytheodore** [comment]
We could also move the check to an `AC_PROG_CC` test in `mxe-conf`. I'm not sure if `gcc` is actually required or if `clang` will suffice.

**Comment by tonytheodore** [comment]
Probably simpler for the time being to use normal portability variables and stay away from env vars. `clang` will be used if found and you can always `make CC_BUILD=gcc48` if necessary.

**Comment by tonytheodore** [comment]
Actually, [`BUILD_CC` is a better name](https://github.com/mxe/mxe/commit/8a6a33a48c647030398221b7c7b3ab33d2be4ef3).
