### ISSUE TITLE
Package libdnet is broken on FreeBSD

### ISSUE THREAD

**Issue by starius** [mxe/mxe#902]
Commit 4cafbd6bed322ea79867c8f923af6ff830d1b7fb
[Log](https://gist.githubusercontent.com/starius/cb967599a661584a6142/raw/690dc111a5c299621ccac860c09ac8a0be6fde07/libdnet_i686-w64-mingw32.static)

**Comment by tonytheodore** [comment]
Can you try it as an unprivileged user? There's a check for `/dev/tun0` which is never going to be relevant to cross-compiling.

**Comment by starius** [comment]
libdnet build on FreeBSD is [broken](https://gist.githubusercontent.com/starius/fcdb45b3af154bb3c665/raw/7cc50ad272bbd2a3c088d894775b0c6a7682556d/libdnet_i686-w64-mingw32.static), unprivileged user

**Comment by tonytheodore** [comment]
Did https://github.com/mxe/mxe/commit/24caa5819a19652c05162169e1ccfd4a459fe0e1 work?

**Comment by tonytheodore** [comment]
Fixed https://gist.github.com/tonytheodore/458450f16a4cad00aaaf

**Comment by starius** [comment]
Works for me at 9537e5c9d2f83fe11b8c328e5e142aa1
