### ISSUE TITLE
Package luajit is broken on FreeBSD 

### ISSUE THREAD

**Issue by starius** [mxe/mxe#903]
[Log](https://gist.githubusercontent.com/starius/d8d4cee1ab1a16a3725c/raw/c0ae1df44e0906ae70c6866e79eb7d45269ab177/luajit_i686-w64-mingw32.static)
Commit: 4cafbd6bed322ea79867c8f923af6ff830d1b7fb

**Comment by tonytheodore** [comment]
That's going to be tricky if you've installed a non-multi-lib `gcc` from ports and we're sending `-m32` to an `amd64` system. Very interesting...

**Comment by tonytheodore** [comment]
From https://github.com/mxe/mxe/blob/master/src/luajit.mk#L24:

```makefile
# gcc -m64 is only available on 64-bit machines
ifeq (,$(findstring 64,$(BUILD)))
    $(PKG)_BUILD_x86_64-w64-mingw32 =
endif
```

Probably this check should be a runtime test for `-m32 | -m64`.

**Comment by tonytheodore** [comment]
Works using `clang` instead of `gcc`: https://gist.github.com/tonytheodore/52e71e76ef8851277a45

```
vagrant@:~ % clang -v
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.2
Thread model: posix
Selected GCC installation:
```
