### ISSUE TITLE
Several packages are broken on Wheezy because of cmake version

### ISSUE THREAD

**Issue by starius** [mxe/mxe#909]
The following packages:
  * winpthreads
  * sdl

are broken when building commit 16e417f9d9729b06c3e19ac0439b215740da60d4 on Wheezy. Error message is:
```
CMake 2.8.11 or higher is required.  You are running version 2.8.9
```
It is likely to be caused by 1dd126b160ef3ec80fee9b2c5d0563486815cbe6 and ee5db756fa617c9d5ba6ffb1c9f19cf256a880e3:
```
echo 'cmake_minimum_required(VERSION 2.8.11)'; \
```
Can this version be decreased from 2.8.11 to 2.8.9 (Wheezy)? Package `qhttpengine` does so in patch `src/qhttpengine-1-decrease-required-cmake-ver.patch`.

Is it a side-effect of [moving to MXE version of cmake](https://github.com/mxe/mxe/issues/852#issuecomment-140430207)? MXE cmake version is going to be >= 2.8.11, so it will satisfy this check.

**Comment by tonytheodore** [comment]
> Can this version be decreased from 2.8.11 to 2.8.9 (Wheezy)?

Sure, they have a common header in `src/cmake/test/CMakeLists.txt`, just change it there. 2.8.11 isn't based on anything other than my reading of the qt docs - it could be 2.6 for all I know but I couldn't test on anything earlier than 2.8.12.

> Is it a side-effect of moving to MXE version of cmake?

Indirectly, but that's still some time away, after the toolchain re-org.

**Comment by tonytheodore** [comment]
Actually, it might be better to just disable the tests instead of spending time fixing for older versions?

**Comment by starius** [comment]
Agreed. I'll comment out `cmake_policy(SET CMP0020 NEW)` on Wheezy and test build. If it works, this issue can wait until switching to MXE's `cmake`.

**Comment by starius** [comment]
Without `cmake_policy(SET CMP0020 NEW)` all packages (except `openscenegraph`, but it is [other issue](https://github.com/mxe/mxe/issues/913)) are built successfully. Close this issue when MXE's `cmake` is implemented.
