### ISSUE TITLE
lua installs lua53.dll instead of liblua53.dll

### ISSUE THREAD

**Issue by starius** [mxe/mxe#910]
Is there any reason for it to be `lua53.dll` (not `liblua53.dll`)? Most of libraries in bin/ have `lib` prefix.

**Comment by tonytheodore** [comment]
What's the general convention in the lua community? It's better to match that so feel free to change it rather than modify any downstream build rules.

**Comment by starius** [comment]
[LuaDist](http://luadist.org/) distributes `bin/liblua.dll`.
Cygwin [installs ](https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Flua%2Flua-5.1.5-1&grep=dll) `cyglua-5.1.dll` and `liblua5.1.dll.a`.

**Comment by TimothyGu** [comment]
It's probably better to change it to liblua5.3.dll, just to be compatible with Cygwin and Linux (on Ubuntu it's `liblua5.3.so`)

**Comment by starius** [comment]
+1 for `liblua5.3.dll`
