### ISSUE TITLE
qtwebkit no build

### ISSUE THREAD

**Issue by uralbash** [mxe/mxe#915]
I'm trying to build qtwebkit but I get the following output:

```
$ make qtwebkit
[using autodetected 4 job(s)]
[check requirements]
...
[no-build]  qtwebkit             i686-w64-mingw32.static
```
What does ``[no-build]`` mean and how to build it?

**Comment by tonytheodore** [comment]
`[no-build]` means the package is disabled for a target. In the case of qtwebkit, static builds have long been disabled, and it has been deprecated altogether since Qt 5.5.

You'll have to use the shared version of Qt4: 
```
make qt MXE_TARGETS=i686-w64-mingw32.shared
```

**Comment by uralbash** [comment]
Thank you. It solved my problem.
