### ISSUE TITLE
Toolchain re-org

### ISSUE THREAD

**Issue by tonytheodore** [mxe/mxe#919]
See:
 - http://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-09/msg00026.html
 - http://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-09/msg00019.html
 - #852
 - #898
 - #918

**Comment by ooxi** [comment]
I'll be glad to give you a helping hand, is there anything I can do to support this issue? :)

**Comment by starius** [comment]
Can `src/cmake/modules` path (or it's installed copy in `usr/`) be included in the package `mxe-conf`?

**Comment by tonytheodore** [comment]
It could be installed by `mxe-conf`, it would work and even `git` wouldn't notice that we installed it multiple times. This may be the best short-term solution to #918 though we still need do get the rest right.

As an aside, I'd lean towards including all mxe sources for reference (and possibly as a legal requirement of changes made).

**Comment by ooxi** [comment]
I strongly agree with installing the mxe sources from which the binary packages were build. This would also eliminate possible incompatibilities between new commits and existing binary packages.

**Comment by starius** [comment]
I'm going to add new common package `mxe-src` to `build-pkg`, which includes `src` directory. All other packages depend on `mxe-src` as well as on `mxe-requirements`.

> possibly as a legal requirement of changes made

I have overlooked this issue. GPL'ed packages require distributing source along with binary packages. Is it worth adding package `mxe-pkg` with directory `pkg`?

**Comment by tonytheodore** [comment]
> GPL'ed packages require distributing source along with binary packages

IANAL, but I believe you only need to make the sources available on request. Otherwise, no modern OS could ship on (say) a CD.

> Is it worth adding package mxe-pkg with directory pkg?

I would say no, especially not as a requirement. Maybe as a `recommends` package, but no other normal debian packages do that.

**Comment by starius** [comment]
AFAIK `deb-src` is what binary packages are built from. You can say `apt-get source mxe && cd mxe* && debuild` and it build all binary packages for you.

**Comment by tonytheodore** [comment]
> Can src/cmake/modules path (or it's installed copy in usr/) be included in the package mxe-conf?

@starius, indeed, having the native mxe-conf install these modules in usr/ is a very good idea that I've included in the pull request. (Installing the mxe sources is mostly orthogonal to this).

> I'll be glad to give you a helping hand, is there anything I can do to support this issue? :)

@ooxi, test out #925 and see if it behaves as expected.

**Comment by ooxi** [comment]
> @ooxi, test out #925 and see if it behaves as expected.

By running make with your patches?

**Comment by tonytheodore** [comment]
Yes, though it takes a looong time to build. Probably better to keep testing the apt packages unless you have lots of cycles to spare.

**Comment by ooxi** [comment]
How much disk space does `make` require? I've run out of disk with a 10 GiB image (now retrying with 50 GB).

**Comment by starius** [comment]
I build with build-pkg.lua and get the following sizes:
```
9.1G    usr/.git/
39G     usr/
2.1G    pkg/
1.2G    log/
55G     .
```

Top directory is about 13G because of tarballs and Debian packages.

If you build with `make`, you could get about 35G.

**Comment by ooxi** [comment]
make 03a941bfc4111b7f3880ff9f0828950a8c77105b succeeded :)
