### ISSUE TITLE
qtbase log is broken

### ISSUE THREAD

**Issue by starius** [mxe/mxe#938]
It can be viewed with `less` but can't be opened in a text editor. A text editor shows only beginning of the file, before first zero byte.

With `less`:
```
DEFAULT_INCDIRS="/home/mxe/mxe-toolchain-reorg/usr/lib/gcc/i686-w64-mingw32.static/5.2.0/include/c++
/home/mxe/mxe-toolchain-reorg/usr/lib/gcc/i686-w64-mingw32.static/5.2.0/include/c++/i686-w64-mingw32.static
/home/mxe/mxe-toolchain-reorg/usr/lib/gcc/i686-w64-mingw32.static/5.2.0/include/c++/backward
/home/mxe/mxe-toolchain-reorg/usr/lib/gcc/i686-w64-mingw32.static/5.2.0/include
/home/mxe/mxe-toolchain-reorg/usr/lib/gcc/i686-w64-mingw32.static/5.2.0/include-fixed
/home/mxe/mxe-toolchain-reorg/usr/i686-w64-mingw32.static/include
"
DEFAULT_LIBDIRS="/home/mxe/mxe-toolchain-reorg/usr/lib/gcc/i686-w64-mingw32.static/5.2.0
/home/mxe/mxe-toolchain-reorg/usr/i686-w64-mingw32.static/lib
"
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
....
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Creating qmake...
make[2]: Entering directory `/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/qmake'
g++ -c -o project.o -pipe -ffunction-sections -g  -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/qmake -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/qmake/library -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/qmake/generators -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/qmake/generators/unix -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/qmake/generators/win32 -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/qmake/generators/mac -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/qmake/generators/integrity -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/include -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/include/QtCore -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/include/QtCore/5.5.0 -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/include/QtCore/5.5.0/QtCore -I../src/corelib/global -DHAVE_QCONFIG_CPP -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/mkspecs/linux-g++ -I/home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/tools/shared -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_TEXTCODEC -DQT_NO_UNICODETABLES -DQT_NO_COMPONENT -DQT_NO_COMPRESS -DQT_NO_THREAD -DQT_NO_QOBJECT -DQT_NO_GEOM_VARIANT -DQT_NO_DATASTREAM -DQT_CRYPTOGRAPHICHASH_ONLY_SHA1 -DQT_JSON_READONLY -DQT_NO_STANDARDPATHS /home/mxe/mxe-toolchain-reorg/tmp-qtbase-i686-w64-mingw32.static/qtbase-opensource-src-5.5.0/qmake/project.cpp
...
```

**Comment by tonytheodore** [comment]
I can't replicate this here - does it happen consistently? I have noticed sometimes that my editor will use a different icon for a log file, but it doesn't seem to affect anything.

**Comment by starius** [comment]
It happens consistently on my Debian Wheezy machine, but not on another machine with Debian Jessie. See [logs of MXE builds on mxe.redjohn.tk](http://mxe.redjohn.tk/repos/log/d95da7e22a24ab477f29ae95f4e2573a0792a5df/log/qtbase_i686-w64-mingw32.static).

**Comment by TimothyGu** [comment]
I remember seeing this issue as well some time in the past.

**Comment by starius** [comment]
@tonytheodore, the log is broken on all my systems and probably not only my. Normal beginning of MXE log is wiped out and the log begins with `DEFAULT_INCDIRS=...` (see above). Zeros bug is optional (only on Wheezy). Pull request #943 fixes both problems. [Fixed log](https://gist.github.com/starius/7fe888e52fabf22ba184):
```
[using autodetected 6 job(s)]
make[1]: Entering directory `/home/mxe/mxe-qtbase-fix-log-corruption'
uname -a
Linux sd-68075 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux
git show-branch --list --reflog=1
  [refs/heads/qtbase-fix-log-corruption@{0}] (31 minutes ago) clone: from https://github.com/LuaAndC/mxe
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy
autoconf --version 2>/dev/null | head -1
autoconf (GNU Autoconf) 2.69
automake --version 2>/dev/null | head -1
automake (GNU automake) 1.11.6
...
```

I still don't know why `tee`ing to stderr causes log corruption. Can somebody explain this?

**Comment by tonytheodore** [comment]
Could be that the shell running in the context of `make` is not a `tty` and/or already has redirections that might confuse it.

**Comment by starius** [comment]
@tonytheodore can you reproduce this error outside of MXE, please?
I have tried `./configure -opensource -confirm-license &> log` in `dev` branch of `qtbase` and it doesn't break the log file.

**Comment by tonytheodore** [comment]
Make sure you use the `-v` option - I can confirm that the log is truncated with that.

**Comment by tonytheodore** [comment]
Changing to `tee -a` stops the log truncation, but then it doesn't print `DEFAULT_INCDIRS=...` etc.

**Comment by starius** [comment]
Thank you!

**Comment by tonytheodore** [comment]
I can't figure it out, running with `bash` instead of `sh` and newer versions of `tee` all have the same behaviour. The closest I can get is following `/dev/stderr`:

Debian Wheezy:
```
$ ls -al /proc/self/fd/1
lrwx------ 1 vagrant vagrant 64 Oct 20 11:24 /proc/self/fd/1 -> /dev/pts/0
$ ls -al /proc/self/fd/2
lrwx------ 1 vagrant vagrant 64 Oct 20 11:24 /proc/self/fd/2 -> /dev/pts/0
```

and on OSX:

```
$ ls -al /dev/fd/1
crw--w----  1 tonyt  tty   16,   0 20 Oct 22:31 /dev/fd/1
$ ls -al /dev/fd/2
crw--w----  1 tonyt  tty   16,   0 20 Oct 22:31 /dev/fd/2
```

but Wheezy breaks my understanding of how any redirection would ever work.

There's a tool in coreutils called `stdbuf` - I imagine if you used this to fully flush `stdout` then the truncation by `tee` wouldn't matter, but it's not portable and I'm losing my mind.

**Comment by tonytheodore** [comment]
Forgot to say, you can observe the truncation with `tail -f` - it makes no sense.

**Comment by starius** [comment]
Qt guys want to know an explanation of why it happens:

> Thanks for the details, but we don't need steps to reproduce in the commit message. We need an explanation of why it happens and how your change makes sure it won't happen again.

> That is, we need a little more investigation of why the steps above cause a problem in the first place.

My answer:

> My own understanding is as follows. A child process (tee) opens the output file (stderr) which is already opened by the process running "./configure ... &> log". So it overwrites this file. If I am correct, then the commit does fix the problem, because it avoids writing to stderr.

https://codereview.qt-project.org/#/c/138224/

**Comment by tonytheodore** [comment]
Are you running this in a VM? I am, it could be something to do with the ssh tty setup.

**Comment by tonytheodore** [comment]
Another thing that doesn't make sense is `tee`ing to stderr:
```
date | tee /dev/stderr
```
is just going to duplicate the output. I wonder what the original intent was.

**Comment by tonytheodore** [comment]
> I wonder what the original intent was.

I get it now, the output is meant to be `eval`ed and it's `tee`ing to stderr as a means of echoing. Much simpler to just use a variable to `eval` and `echo`:

```diff
diff --git a/configure b/configure
index cea62fb..fe7ed5d 100755
--- a/configure
+++ b/configure
@@ -3571,10 +3571,9 @@ END {
         print "DEFAULT_LIBDIRS=\"/lib\n/usr/lib\"\n";
 }'

-unset tty
-[ "$OPT_VERBOSE" = "yes" ] && tty=/dev/stderr
-eval "`LC_ALL=C $TEST_COMPILER $SYSROOT_FLAG $TEST_COMPILER_CXXFLAGS -xc++ -E -v - < /dev/null 2>&1 > /dev/null | $AWK "$awkprog" | tee $tty`"
-unset tty
+awkprog_result="`LC_ALL=C $TEST_COMPILER $SYSROOT_FLAG $TEST_COMPILER_CXXFLAGS -xc++ -E -v - < /dev/null 2>&1 > /dev/null | $AWK "$awkprog"`"
+eval "$awkprog_result"
+[ "$OPT_VERBOSE" = "yes" ] && echo "$awkprog_result"

 #setup the build parts
 if [ -z "$CFG_BUILD_PARTS" ]; then
```

**Comment by tonytheodore** [comment]
Last thing, this affects systems where `/dev/std*` ends up pointing to the same character file (probably most Linux systems).

FreeBSD is okay:
```
% ls -al /dev/fd/*
crw-rw-rw-  1 root  wheel  0x12 Oct 21 03:49 /dev/fd/0
crw-rw-rw-  1 root  wheel  0x14 Oct 21 03:49 /dev/fd/1
crw-rw-rw-  1 root  wheel  0x16 Oct 21 03:49 /dev/fd/2
```
Fedora not:
```
# ls -l /proc/self/fd/1 /proc/self/fd/2 /dev/pts/0
crw--w--w-. 1 root tty  136, 0 Oct 21 03:54 /dev/pts/0
lrwx------. 1 root root     64 Oct 21 03:54 /proc/self/fd/1 -> /dev/pts/0
lrwx------. 1 root root     64 Oct 21 03:54 /proc/self/fd/2 -> /dev/pts/0
```

**Comment by starius** [comment]
The commit was merged: https://github.com/qtproject/qtbase/commit/45fe3f1cde1e516d1ddccddb5e33ea4316497c36
Thanks!

**Comment by tonytheodore** [comment]
Good one!

`tee -a` is probably a race condition where the unbuffered `stderr` is written before the buffered `stdout` (which is empty after being consumed by `eval`) and before the write is flushed (assuming `tee` as a whole is atomic). Hard to say.
