### ISSUE TITLE
build-pkg should install mxe sources

### ISSUE THREAD

**Issue by starius** [mxe/mxe#946]
see #918
see https://github.com/mxe/mxe/issues/919#issuecomment-147727375

**Comment by tonytheodore** [comment]
I wonder if we should create corresponding git tags for every packaging release?

**Comment by starius** [comment]
> I wonder if we should create corresponding git tags for every packaging release?

Good idea. Maybe even Github releases to have a place where to upload log and maybe some other information about a release.
