### ISSUE TITLE
Qt 5.5 OpenGL dynamic

### ISSUE THREAD

**Issue by Komet** [mxe/mxe#947]
As mentioned in #747 qtbase is still build with `-opengl desktop`. This leads to a black application window when starting a Qt application (which uses QtQuick/QML) over a RDP connection to Windows.
I know the configure script doesn't support `-opengl dynamic` or `-angle` builds but has somebody experimented with porting the relevant parts from configure.exe to the configure script?

btw: there are several bug reports on the Qt bug tracker regarding RDP connections and a black application window. Most of them closed (or marked as invalid) with the statement that it will work when using a `-opengl dynamic` build.

**Comment by saiarcot895** [comment]
You would need to have the DirectX runtime installed to be able to use either of those two options.

**Comment by tonytheodore** [comment]
Stumbled across this:

https://github.com/shinchiro/mpv-winbuild-cmake/tree/more_changes/extras

It isn't the way we would do it but may be useful as an initial test to see what needs to be done.

**Comment by raoulh** [comment]
I actually did it in my branch and with Qt5.7:
https://github.com/raoulh/mxe/tree/devs/rhe/qt5

detailed commit: https://github.com/raoulh/mxe/commit/9ae32be951f3a7ec2ff91bd88e6c7b4d65306828

qtbase is patched to allow the build of Angle.
