### ISSUE TITLE
extra documentation is installed on Jessie

### ISSUE THREAD

**Issue by starius** [mxe/mxe#952]
I have compared lists of file names on Wheezy and on Jessie (with #925 applied) and found that the following files present on Jessie but not on Wheezy:
https://gist.github.com/starius/20c45b87c18e842fb1a5
All of them are documentation. Maybe documentation elimination doesn't work on Jessie.

**Comment by tonytheodore** [comment]
Looks like `doxygen` in installed on Jessie and it's building the (optional) docs. In the case of `aubio` I can't see any way to disable the docs and may have to remove the directory post-build.

**Comment by TimothyGu** [comment]
@tonytheodore for aubio I believe we can manually `unset` `DOXYGEN` and `TXT2MAN` envvar: https://github.com/aubio/aubio/blob/master/wscript#L278-L305

**Comment by tonytheodore** [comment]
They should already unset by the whitelist in the `Makefile`. It looks like there's a check for the executables that sets those vars internally.
