### ISSUE TITLE
need some help getting mxe building on ubuntu vagrant

### ISSUE THREAD

**Issue by andrewfenn** [mxe/mxe#955]
My goal is to get win32 builds being made in Travis. Travis has a new Ubuntu Trusty beta VM that they use for building code which you can see from the link: http://docs.travis-ci.com/user/trusty-ci-environment/

My first goal is to get MXE working on vagrant in an Ubuntu Trusty image similar to the Travis one. I use the following commands to get my VM up and running.

```
vagrant init ubuntu/trusty64; vagrant up --provider virtualbox
vagrant ssh
```

I then install the dependencies that MXE needs as per the documentation and then attempt to make it.

```
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install \
    autoconf automake autopoint bash bison bzip2 cmake flex \
    gettext git g++ gperf intltool libffi-dev libgdk-pixbuf2.0-dev \
    libtool libltdl-dev libssl-dev libxml-parser-perl make openssl \
    p7zip-full patch perl pkg-config python ruby scons sed \
    unzip wget xz-utils
sudo apt-get install g++-multilib libc6-dev-i386
git clone https://github.com/mxe/mxe.git
cd mxe
make
```

When I do these steps I get "Failed to build package gcc for target i686-w64-mingw32.static!"

The last couple of lines in the error log look like this..

```
-o build/genattrtab.o /home/vagrant/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.2.0/gcc/genattrtab.c
g++   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -DGENERATOR_FILE -static-libstdc++ -static-libgcc  -o build/genattrtab \
            build/genattrtab.o build/rtl.o build/read-rtl.o build/ggc-none.o build/vec.o build/min-insn-modes.o build/gensupport.o build/print-rtl.o build/read-md.o build/errors.o ../build-x86_64-unknown-linux-gnu/libiberty/libiberty.a
build/genattrtab /home/vagrant/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.2.0/gcc/common.md /home/vagrant/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.2.0/gcc/config/i386/i386.md insn-conditions.md \
                -Atmp-attrtab.c -Dtmp-dfatab.c -Ltmp-latencytab.c
make[3]: *** [s-attrtab] Killed
make[3]: Leaving directory `/home/vagrant/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.2.0.build/gcc'
make[2]: *** [all-gcc] Error 2
make[2]: Leaving directory `/home/vagrant/mxe/tmp-gcc-i686-w64-mingw32.static/gcc-5.2.0.build'
make[1]: *** [build-only-gcc_i686-w64-mingw32.static] Error 2
make[1]: Leaving directory `/home/vagrant/mxe'
```

I get this error regardless of what version of ubuntu I use it seems to me.

Does anyone know how to get mxe building correctly on ubuntu?

**Comment by andrewfenn** [comment]
I noticed the following setting in "settings.mk" and have tried it with multiple ubuntu releases but I still get the same result in terms of build failures.

```
# This variable controls where intermediate files are created
# this is necessary when compiling inside a virtualbox shared
# directory. Some commands like strip fail in there with Protocol error
# default is the current directory
MXE_TMP := /tmp
```

**Comment by tonytheodore** [comment]
> make[3]: *** [s-attrtab] Killed

It's most likely a lack of RAM in the VM, you'll need at least 2GB, but use 4 to be on the safe side.

**Comment by andrewfenn** [comment]
That was the problem. It's still all building but it looks like it's going to be successful now. Thank you for the advice.

**Comment by tonytheodore** [comment]
Good to hear.

Note that you typically don't need to build all of mxe unless you're working on mxe itself. Compiling a subset of packages is probably the way to go, especially if you eventually want to use Travis. The time-limit will affect you in one way or another and the [binary packages](http://mxe.redjohn.tk/) are likely the best option.
