### ISSUE TITLE
Build gcc once

### ISSUE THREAD

**Issue by starius** [mxe/mxe#961]
See https://github.com/mxe/mxe/pull/925#issuecomment-147992049

**Comment by tonytheodore** [comment]
Agreed, this is the right time to implement such a change. If we want to do threading and exception variants, we'll end up building gcc sixteen times when large parts are common.

The implementation I see is based around multi-lib compilers, wrapper scripts, and spec files. The spec files may also provide an entry point for customisation.

**Comment by tonytheodore** [comment]
The multi-lib configuration ends up being fairly complicated and reduces flexibility of varying threading/exception between architectures. It also doesn't really save much in the way of build time, only a third is common, the rest is built twice.

Spec files may still be useful, though again the extra complexity seems to outweigh the benefits. I think these should only be used for minor tweaks.

**Comment by tonytheodore** [comment]
See also #1133, arch-independent files should be disabled or configured to install correctly.

**Comment by tonytheodore** [comment]
See also https://github.com/mxe/mxe/pull/1165#issuecomment-177636523, `nsis` should also be built once and possibly linked across i686 and x86_64 targets (until it can be built for x86_64).
