### ISSUE TITLE
gcc doesn't build if PREFIX is changed in settings.mk

### ISSUE THREAD

**Issue by gyunaev** [mxe/mxe#967]
If the destination directory changed (by specifying a different PREFIX in _settings.mk_), gcc configure cannot find binutils binaries, and therefore fails to build.

This could be fixed by adding _$PREFIX/bin_ into PATH before running _make gcc_.

**Comment by starius** [comment]
`settings.mk` generated by MXE doesn't have `PREFIX` variable. I am not sure that it is supposed to be changed in `settings.mk`.

**Comment by gyunaev** [comment]
You can overwrite PREFIX in Makefile with the same result.

**Comment by tonytheodore** [comment]
> You can overwrite PREFIX in Makefile with the same result.

The Makefile sets the path after PREFIX is defined but before settings.mk is read. I'm not sure why changing Makefile wouldn't work, but we should probably make this and the log directory configurable.

**Comment by starius** [comment]
By the way, the following commands builds gcc: `mkdir -p /tmp/fff && make gcc PREFIX=/tmp/fff`. Now I have gcc executable in ` /tmp/fff/bin/i686-w64-mingw32.static-gcc`.

**Comment by tonytheodore** [comment]
> make gcc PREFIX=/tmp/fff

That makes sense, specified as a command line option, it will override the Makefile and be defined when PATH is set.

**Comment by gyunaev** [comment]
Right, I confirm that it works with makefile like that. But it would also be nice to be able to specify it in settings, to have a single source for all the settings.

**Comment by tonytheodore** [comment]
Anything else (apart from prefix and log) that should also be configurable?

**Comment by gyunaev** [comment]
That's good enough for me, anything else I use such as shared Qt4 build (w/webkit) on x86_64-w64-mingw32.static is not really configurable easy anyway.

**Comment by starius** [comment]
> A few settings I'd really like, but unsure settings.mk is a proper place, is individual package configuration. For example, I always build Qt without any SQL drivers and without accessibility, is there a way to integrate those changes instead of patching the src/*.mk files manually?

Maybe [MXE plugins](https://github.com/mxe/mxe/pull/935) are the right place for that.

**Comment by tonytheodore** [comment]
With plugins you can do either [a fully explicit rule override](https://github.com/tonytheodore/mxe/blob/3f0cbd596fa091bf3249e58a58e4194e39c19f7e/plugins/custom-qt-min/overrides.mk) or something like:
```
qt_DEPS := gcc dbus jpeg libmng libpng openssl tiff zlib

qt_BUILD := \
    $(subst -accessibility ,-no-accessibility ,\
    $(subst -qt-sql-,-no-sql-,\
    $(qt_BUILD)))

qt_BUILD_SHARED := \
    $(subst -static ,-shared ,\
    $(subst -no-webkit ,-webkit ,\
    $(qt_BUILD)))

```

**Comment by gyunaev** [comment]
Got it. Thank you Tony!
