### ISSUE TITLE
disable WGET in builds

### ISSUE THREAD

**Issue by starius** [mxe/mxe#969]
Set `WGET=false` while building to prevent occasional downloads, which are not verified with checksums. Better solution is to switch off all networking for the building process (as we [did](https://github.com/mxe/mxe/commit/8e2d0e85c5dcdecbe858ffbca391dcc5ca0c3527) for wine) but I don't know how.

**Comment by tonytheodore** [comment]
> Set WGET=false while building to prevent occasional downloads, which are not verified with checksums. 

What downloads are these? I can't say I've noticed them.

**Comment by starius** [comment]
> What downloads are these?

I [used](https://github.com/mxe/mxe/pull/812/files#diff-f14c34aab0433118ea71788dfc3d5223R21) this approach to download GeoIP.dat.gz needed for qbittorrent (rejected pull request #812). I think that breaking network access for build commands helps to prevent such errors in future.

BTW what would be the right solution for GeoIP.dat.gz file? Normal file could be downloaded as a package, but this file is updating frequently.

**Comment by tonytheodore** [comment]
Creating a package for GeoIP data seems reasonable, the license is suitable and monthly updates aren't an issue. It may also be useful to other packages.

**Comment by starius** [comment]
Another source of unattended downloads are smart package building tools. Some of them could detect missing dependency and download it (instead of failing the build). For example. `luarocks` downloads and installs missing dependencies of the rock being built. It is easy to oversee such a problem, if the new version of the rock being built gets a new dependency.

**Comment by tonytheodore** [comment]
I'm not sure I fully understand the problem, unattended downloads sound like a feature. Is the issue that these downloads don't have checksums? Would dropping a `tar` wrapper script in `usr/bin` (first in PATH) be better than disabling networking?

**Comment by starius** [comment]
> unattended downloads sound like a feature

These downloads may be non-verified (e.g., `luarocks` doesn't verify downloads generally), so the build result (success of fail) is unpredictable. For example, luarocks rock `foo` depends on luarocks rock `bar`. If `foo` is a part of MXE, than foo's sources are verified, but bar's sources are not. The source of bar is just downloaded from latest version of bar on the luarocks server. So installing `foo` causes implicit installation of **latest published version** of bar. If the source is not frozen, than the build result is unpredictable. This situation may be the result of updating foo, if previous version of foo had no dependency of bar and it was overseen when updating.

**Comment by starius** [comment]
> Would dropping a tar wrapper script in usr/bin (first in PATH) be better than disabling networking?

Disabling `tar` is not ideal:

  * `tar` is used to extract sources of ucl and lzma when `upx` is built. It is predictable, as sources of ucl and lzma are checksumed;
  * downloaded file can be packaged with other tool. E.g., downloading and extracting GeoIP.dat.gz doesn't need tar. Most `luarocks` rocks are packed with `zip`, not with `tar`.

**Comment by tonytheodore** [comment]
> Disabling tar is not ideal:

I meant creating a "validating tar" (`xz`, `7za`, `unzip` etc.) that takes a checksum as an argument and validates it before extracting. It would be tricky to make it work with pipes though.

**Comment by starius** [comment]
> takes a checksum as an argument

This change would require a lot of patching for all code which runs an extractor. E.g. patching of `luarocks` which executes `tar`. And it doesn't help against downloading non-compressed files.

The approach with verifying extractors can be improved by using drop-in replacements for tar, unzip, etc which would verify the checksum of its argument against all checksums of all packages. This requires a lot of coding as well, but doesn't solve the problem of downloading non-compressed files and breaks extraction of non-package files. E.g. tool `waf` used to build and install `jack` unpacks itself using tar from python file.
