### ISSUE TITLE
set cmake_policy in mxe-conf.cmake

### ISSUE THREAD

**Issue by starius** [mxe/mxe#971]
Currently `cmake_policy` is set in `src/cmake/test/CMakeLists.txt` which is included by some cmake-based builds. I think, it worth moving them to `mxe-conf.cmake` as they are applicable to all cmake-based builds related to MXE.

**Comment by starius** [comment]
CMake warning from `log/llvm_i686-w64-mingw32.static` (Wheezy, not Jessie):

```
CMake Warning (dev) at /usr/share/cmake-2.8/Modules/CMakeExpandImportedTargets.cmake:33 (include):
  File /usr/share/cmake-2.8/Modules/CMakeExpandImportedTargets.cmake includes
  /home/mxe/mxe-before-threads/usr/share/cmake/modules/CMakeParseArguments.cmake
  (found via CMAKE_MODULE_PATH) which shadows
  /usr/share/cmake-2.8/Modules/CMakeParseArguments.cmake.  This may cause
  errors later on .

  Policy CMP0017 is not set: Prefer files from the CMake module directory
  when including from there.  Run "cmake --help-policy CMP0017" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/CheckFunctionExists.cmake:30 (INCLUDE)
  cmake/config-ix.cmake:10 (include)
  CMakeLists.txt:264 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by tonytheodore** [comment]
Does setting it in the toolchain file work? I won't have a chance to check till tomorrow, but I know there are some settings that have to be in a `CMakeLists.txt` file.

As an aside, we should enable the native `cmake` build soon (even if we don't have the patches yet) to provide a common point of reference.

**Comment by tonytheodore** [comment]
See https://github.com/mxe/mxe/pull/1116/files#r48677984 and https://gist.github.com/starius/20b64c4141921b8f25dc#file-libechonest_i686-w64-mingw32-static-L46, our own modules shouldn't cause shadowing issues.
