### ISSUE TITLE
Several requirements versions in wiki are wrong

### ISSUE THREAD

**Issue by zhurikhin** [mxe/mxe#978]
Hello.  I've recently been using MXE on an ancient machine to build GCC and found out there are several requirements that have wrong versions:
* Openssl needs to be at least 1.0.1 (otherwise there is no sha256 support and MXE fails to verify any package)
* Autoconf has to be at least 2.68 (otherwise pkg-config building fails with "error: Autoconf version 2.68 or higher is required")
* Binutils by default needs zlib of at least 1.2.0 version (otherwise compilation fails with error about "binutils-2.25.1/bfd/compress.c:100: undefined reference to `compressBound'")

**Comment by tonytheodore** [comment]
Thanks!
