### ISSUE TITLE
some patches are not git am'able

### ISSUE THREAD

**Issue by starius** [mxe/mxe#983]
Example:

```
$ git am ../../src/libmysqlclient-1-fixes.patch
Patch format detection failed.

# remove header ...

$ git am ../../src/libmysqlclient-1-fixes.patch
Patch does not have a valid e-mail address.

$ sed 's/From: MXE/From: MXE@MXE/' -i ../../src/libmysqlclient-1-fixes.patch

$ git am ../../src/libmysqlclient-1-fixes.patch
OK
```
- [ ] make all patches `git am`able
- [ ] `git am && make-patch` should not change the original patch

**Comment by TimothyGu** [comment]
It can be fixed through a simple regex as you can see. These files are created with the [patch-tool-mxe](https://github.com/mxe/mxe/blob/master/tools/patch-tool-mxe#L104).

**Comment by starius** [comment]
Why not to store patches in a format accepted by `git am`?

I think we can start with an output of `git format-patch -p --stdout --no-numbered`.
Lines like `From f33262c29c253608f57e91af0e96bdb7bfa3cc00 Mon Sep 17 00:00:00 2001` should be removed or commit ID unified. `From:` should keep original author to know who can help with this patch. I think that replacing it with `From: MXE` is a bad idea as author information is lost and `git am` doesn't accept this string. `Signed-off-by:` can be removed. Final strings like `--` and `1.9.1` can be removed or unified. Finally MXE copyright header should be added in such a form that doesn't break `git am`.

**Comment by starius** [comment]
How I patch package `foo`:

  * `make download-foo`
  * create an empty directory `foo`
  * unpack tar file from pkg
  * create new GIT repo in `foo/foo-1.2.3`
  * commit all files of `foo`
  * apply existing patches with `git am`
  * add / remove / modify commits to fix something [*]
  * create new patch file with `git format-patch` and copy it to `src/foo-1-fixes.patch`
  * `make foo`

I think all of them except [*] can be automated:

  * `make edit-patch-foo`
  * `cd patched-foo`
  * [*]
  * `make save-patch-foo`

**Comment by TimothyGu** [comment]
I actually have an ancient branch a long time ago doing something like that. Then I found out about patch-tool-mxe which works pretty well.

**Comment by starius** [comment]
`patch-tool-mxe` doesn't work with some patches.

```
$ ./tools/patch-tool-mxe init luabind
$ ./tools/patch-tool-mxe import luabind 2-elif
Imported /mxe-patch-tool/src/luabind-2-elif.patch
$ cd gits/luabind-0.9.1/
$ git log
commit d4558f93498c66fdff16110f5efff52e519c07e5
Author: Boris Nagaev <bnagaev@gmail.com>
Date:   Mon Nov 16 00:36:42 2015 +0100

    init
mxe@sd-68075:~/mxe-patch-tool/gits/luabind-0.9.1$ git status 
# On branch master
nothing to commit (working directory clean)
```

Patches are applied with `patch -p1 -u`.
Can we use `git am` instead?
Git is already one of MXE requirements.

Also I would like to unify and consolidate all patches and replace patch-tool-mxe tool with Makefile targets.

**Comment by tonytheodore** [comment]
> and replace patch-tool-mxe tool with Makefile targets.

+1, it was always the intention to integrate it fully.
