### ISSUE TITLE
Option to strip (native) binaries

### ISSUE THREAD

**Issue by darealshinji** [mxe/mxe#985]
Is it possible to automatically strip binaries before or after they were installed? Especially the gcc binaries in the libexec directories are very huge and I personally don't need the debugging symbols. Maybe an option in settings.mk like `STRIP_INSTALL := yes`?

**Comment by starius** [comment]
+1

**Comment by saiarcot895** [comment]
Alternatively, couldn't the binaries be built in release mode, so that there are no symbols in the first place, rather than running `strip` afterwards?

**Comment by starius** [comment]
CMake based packages are built in release mode:
https://github.com/mxe/mxe/blob/656d5c5/src/mxe-conf.mk#L34

**Comment by darealshinji** [comment]
You could add a strip target like this to the Makefile:
``` make
STRIP_BINARIES := \
	$(PREFIX)/*-apple-darwin*/bin/* \
	$(PREFIX)/*-linux-gnu/bin/* \
	$(PREFIX)/*/qt5/bin/* \
	$(PREFIX)/bin/* \
	$(PREFIX)/libexec/gcc/*/*/* \
	$(PREFIX)/libexec/gcc/*/*/*/*

STRIP_STATIC_LIBS := \
	$(PREFIX)/*-apple-darwin*/lib/*.a \
	$(PREFIX)/*-linux-gnu/lib/*.a \
	$(PREFIX)/lib/gcc/*/*/*.a

.PHONY: strip
strip:
	@$(STRIP) --strip-all $(STRIP_BINARIES) 2>/dev/null || true
	@$(STRIP) --strip-debug $(STRIP_STATIC_LIBS) 2>/dev/null || true
```
GNU strip will issue warnings on unknown input files and eventually exit 1, but all non-native binaries or other unknown files will be left intact. So using wildcards like this should be safe enough.

After building qt5 (x86_64-w64-mingw32.static) my MXE prefix directory had a size of 2.0 GiB. After running `make strip` it was 1.4 GiB.

Otherwise adding `-s`/`-Wl,-s` to `LDFLAGS` or using `make install-strip`/`make strip-install` on the native builds should probably do it. On gcc the Makefile targets `install-strip` and `maybe-install-strip-gcc` can be used (since IIRC it'll ignore custom `LDFLAGS`).

**Comment by starius** [comment]
> GNU strip will issue warnings on unknown input files and eventually exit 1, but all non-native binaries or other unknown files will be left intact. So using wildcards like this should be safe enough.

Here GNU `strip` on Linux strips Windows exe files as well.

**Comment by darealshinji** [comment]
Interresting. Does it corrupt the files? Maybe a check could be added then, something like this:
``` shell
native_bins="ELF"
for f in usr/bin/* ; do
    if [ "$(file -b $f | cut -d' ' -f1)" = "$native_bins" ]; then
        strip -s $f
    fi
done
```

**Comment by starius** [comment]
> Does it corrupt the files?

It doesn't corrupt. Files are functional and their size is significantly lower.

I think we should not choose files for stripping automatically. Instead, we should find 20% of files which spend 80% of disk-space and strip them. I think, it would be gcc and Qt tools (qmake, rcc, etc). Some tests are also large. For example, `test-gtkmm3.exe` is 134M. It becomes 18M after stripping.

List of all MXE files in `usr/` with sizes (commit cc95f885fae8473d802f6ba0160b49a4c96a659b):
https://gist.github.com/158805cd0383a8d702a4

**Comment by TimothyGu** [comment]
> Here GNU `strip` on Linux strips Windows exe files as well.

It is *your* binutils configuration that allows that, not a general "`strip` on Linux." In fact, by your logic `ld` on Linux works with Windows as well.

We build our own binutils for a reason. If *every* single copy of binutils works with PE binaries then we don't even need to have the binutils package.

**Comment by starius** [comment]
>> Here GNU strip on Linux strips Windows exe files as well.

> It is your binutils configuration that allows that, not a general "strip on Linux." In fact, by your logic ld on Linux works with Windows as well.

@TimothyGu, I didn't mean that any strip on any Linux does it, but that strip sometimes does it (e.g., on my system), so we can't rely on "all non-native binaries or other unknown files will be left intact".

Please take a look at the list of files with sizes. I think, it worth adding `strip` to targets producing large files.

**Comment by pavelvat** [comment]
Strip can lead to some problems, for example:
https://github.com/clementine-player/Dependencies/commit/98856df268348efb87ac8de4542d432db6a37f4d
https://github.com/clementine-player/Dependencies/commit/6b82f18ae1155b3877c5b098547adcaa0ff07fa3
https://github.com/clementine-player/Dependencies/commit/b36938ab0913a1b8a62b06b875a6fe7db708c9a1
https://github.com/clementine-player/Dependencies/commit/355dad1a34eb3b29d320c1d1ba110d134cf7b1c5


So, need to add exception mechanism, like this:
https://github.com/clementine-player/Dependencies/blob/master/windows/Makefile#L133-L137
https://github.com/clementine-player/Dependencies/blob/master/windows/Makefile#L197-L199

**Comment by darealshinji** [comment]
I've changed the title as this mostly affects native binaries. Like starius said, it's probably a good idea to add `strip` (or use `make install-strip`) to some packages that produce large binaries.

**Comment by tonytheodore** [comment]
Oddly, the native gcc binaries created by clang (on OS X) are only slightly bigger. `install-strip` is a good choice for `binutils` and `gcc`.
