### ISSUE TITLE
option to download from repo

### ISSUE THREAD

**Issue by starius** [mxe/mxe#987]
See https://github.com/mxe/mxe/pull/977#issuecomment-156690066

Options:
- specify a commit/tag
- repos: git, svn, hg, bzr

**Comment by tonytheodore** [comment]
Apparently, this is already possible, see discussion:
http://lists.nongnu.org/archive/html/mingw-cross-env-list/2010-11/msg00066.html
and sample *.mk file:
http://lists.nongnu.org/archive/html/mingw-cross-env-list/2010-11/txtBbwAN7P0V1.txt
