### ISSUE TITLE
libaspell-15.dll don't build after commit 05380b4

### ISSUE THREAD

**Issue by pavelvat** [mxe/mxe#989]
For aspell.mk shared libs don't build after 05380b4.

**Comment by starius** [comment]
We should compare lists of files for all packages to detect similar cases.

**Comment by starius** [comment]
MXE commits before (0ad42f9aa49c118b34fdd324a471df38d389e6c3) and after (96ca43cdbca6c1c34a7aff9d16f7b4a49e2be763) #958 were built.

Lists of files were compared. The following files exist inly in one of builds:
```
< i686-w64-mingw32.shared/bin/test-libgomp.exe
> i686-w64-mingw32.shared/bin/test-pthreads-cmake.exe
> i686-w64-mingw32.shared/bin/test-pthreads.exe
> i686-w64-mingw32.shared/bin/test-pthreads-libgomp.exe
< i686-w64-mingw32.shared/bin/test-winpthreads-cmake.exe
< i686-w64-mingw32.shared/bin/test-winpthreads.exe
< i686-w64-mingw32.shared/installed/libgomp
< i686-w64-mingw32.shared/installed/winpthreads
< i686-w64-mingw32.shared/lib/libgomp.la
> i686-w64-mingw32.shared/lib/libgomp-plugin-host_nonshm.dll.a
< i686-w64-mingw32.static/bin/test-libgomp.exe
> i686-w64-mingw32.static/bin/test-pthreads-cmake.exe
> i686-w64-mingw32.static/bin/test-pthreads.exe
> i686-w64-mingw32.static/bin/test-pthreads-libgomp.exe
< i686-w64-mingw32.static/bin/test-winpthreads-cmake.exe
< i686-w64-mingw32.static/bin/test-winpthreads.exe
< i686-w64-mingw32.static/installed/libgomp
< i686-w64-mingw32.static/installed/winpthreads
> lib/gcc/i686-w64-mingw32.shared/5.2.0/libgomp.a
> lib/gcc/x86_64-w64-mingw32.shared/5.2.0/libgomp.a
< x86_64-w64-mingw32.shared/bin/test-libgomp.exe
> x86_64-w64-mingw32.shared/bin/test-pthreads-cmake.exe
> x86_64-w64-mingw32.shared/bin/test-pthreads.exe
> x86_64-w64-mingw32.shared/bin/test-pthreads-libgomp.exe
< x86_64-w64-mingw32.shared/bin/test-winpthreads-cmake.exe
< x86_64-w64-mingw32.shared/bin/test-winpthreads.exe
< x86_64-w64-mingw32.shared/installed/libgomp
< x86_64-w64-mingw32.shared/installed/winpthreads
< x86_64-w64-mingw32.shared/lib/libgomp.la
> x86_64-w64-mingw32.shared/lib/libgomp-plugin-host_nonshm.dll.a
< x86_64-w64-mingw32.static/bin/test-libgomp.exe
> x86_64-w64-mingw32.static/bin/test-pthreads-cmake.exe
> x86_64-w64-mingw32.static/bin/test-pthreads.exe
> x86_64-w64-mingw32.static/bin/test-pthreads-libgomp.exe
< x86_64-w64-mingw32.static/bin/test-winpthreads-cmake.exe
< x86_64-w64-mingw32.static/bin/test-winpthreads.exe
< x86_64-w64-mingw32.static/installed/libgomp
< x86_64-w64-mingw32.static/installed/winpthreads
```

This list was build from [filelists](https://gist.github.com/starius/c074d396fdd112f3e27a) with the following command:

```
diff before-threads-all-files-sorted.txt after-threads-all-files-sorted.txt | egrep '[<>]' | egrep -v 'html|doc' > diff
```

Note that `libaspell` hed not build DLL even before #958.

```
$ grep libaspell before-threads-all-files-sorted.txt after-threads-all-files-sorted.txt                                     
before-threads-all-files-sorted.txt:i686-w64-mingw32.shared/lib/libaspell.a
before-threads-all-files-sorted.txt:i686-w64-mingw32.shared/lib/libaspell.la
before-threads-all-files-sorted.txt:i686-w64-mingw32.static/lib/libaspell.a
before-threads-all-files-sorted.txt:i686-w64-mingw32.static/lib/libaspell.la
before-threads-all-files-sorted.txt:x86_64-w64-mingw32.shared/lib/libaspell.a
before-threads-all-files-sorted.txt:x86_64-w64-mingw32.shared/lib/libaspell.la
before-threads-all-files-sorted.txt:x86_64-w64-mingw32.static/lib/libaspell.a
before-threads-all-files-sorted.txt:x86_64-w64-mingw32.static/lib/libaspell.la
after-threads-all-files-sorted.txt:i686-w64-mingw32.shared/lib/libaspell.a
after-threads-all-files-sorted.txt:i686-w64-mingw32.shared/lib/libaspell.la
after-threads-all-files-sorted.txt:i686-w64-mingw32.static/lib/libaspell.a
after-threads-all-files-sorted.txt:i686-w64-mingw32.static/lib/libaspell.la
after-threads-all-files-sorted.txt:x86_64-w64-mingw32.shared/lib/libaspell.a
after-threads-all-files-sorted.txt:x86_64-w64-mingw32.shared/lib/libaspell.la
after-threads-all-files-sorted.txt:x86_64-w64-mingw32.static/lib/libaspell.a
after-threads-all-files-sorted.txt:x86_64-w64-mingw32.static/lib/libaspell.la
```

**Comment by pavelvat** [comment]
```cd tmpdir```
```git clone https://github.com/mxe/mxe.git```
```cd mxe```
```git checkout 0ad42f9```
```make MXE_TARGETS='i686-w64-mingw32.shared' aspell```
In result ```tmpdir/mxe/usr/i686-w64-mingw32.shared/bin/libaspell-15.dll``` is present.

```git checkout 05380b4```
```make MXE_TARGETS='i686-w64-mingw32.shared' aspell```
In result ```tmpdir/mxe/usr/i686-w64-mingw32.shared/bin/libaspell-15.dll``` is no present (present old build).

**Comment by starius** [comment]
> cd tmpdir
git clone https://github.com/mxe/mxe.git
cd mxe
git checkout 0ad42f9
make MXE_TARGETS='i686-w64-mingw32.shared' aspell
In result tmpdir/mxe/usr/i686-w64-mingw32.shared/bin/libaspell-15.dll is present.

Confirmed on Jessie machine. See [the log](https://gist.github.com/starius/c4ac9d85d3cb468736d9).
In [my first answer](https://github.com/mxe/mxe/issues/989#issuecomment-156868100) commit 0ad42f9 was built on Wheezy machine with `build-pkg`. See [the log](https://gist.github.com/starius/db1c065a3c6ef93b5af4).

Probably the difference is caused by Wheezy/Jessie. I'm building commit 0ad42f9 again on Wheezy machine without `build-pkg` to confirm this.

**Comment by starius** [comment]
On Wheezy without `build-pkg` the DLL file exists.

Probably building of libaspell depends on whether some package is built (same to #731).

**Comment by tonytheodore** [comment]
Not building on OSX either - [log](https://gist.github.com/tonytheodore/c507b32d431fe133500e).

**Comment by tonytheodore** [comment]
> Probably building of libaspell depends on whether some package is built

Appears that `-lpthreads` is the culprit - previously it wouldn't be built with `make aspell` (or some similar subset), but now it's always present and detected. [`ncurses` had a similar impact](https://github.com/mxe/mxe/commit/3f96743b43ce2897c053c509cdcad72581d3409d) (discovered via #957), but there is no option for threading.

This may be similar to https://github.com/mxe/mxe/pull/966#issuecomment-154062712. `autoreconf -fi` to get the latest `libtool` features fixes it, but it's not a solution.

**Comment by starius** [comment]
The message about `-lpthread`:

```
*** Warning: linker path does not have real file for library -lpthread.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libpthread and none of the candidates passed a file format test
*** using a file magic. Last file checked: /Users/tonyt/dev/mxe/usr/lib/gcc/i686-w64-mingw32.shared/5.2.0/../../../../i686-w64-mingw32.shared/lib//libpthread.dll.a
*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.

*** Since this library must not contain undefined symbols,
*** because either the platform does not support them or
*** it was explicitly requested with -no-undefined,
*** libtool will only create a static version of it.
```

This error message relates to option `-no-undefined`. Can you explain it in more details, please? Have you tried it?

> autoreconf -fi to get the latest libtool features fixes it, but it's not a solution.

I think we should built native libtool (and co) as well as cmake instead of looking for a workaround for a particular package.

**Comment by tonytheodore** [comment]
> This error message relates to option -no-undefined

I thought `-no-undefined` meant something like "ignore undefined symbols since they'll be resolved at runtime". The wording of the error seems to be the opposite. Also, I'm not sure if it's one or two dashes.

Building with [posix threads allows the dll to build](https://gist.github.com/tonytheodore/a3981f21f05eb9feefef) - I'll investigate further.

**Comment by tonytheodore** [comment]
> *** Warning: linker path does not have real file for library -lpthread.

This is misleading, `libtool` doesn't recognise the "rea"` library, but copying `libwinpthread.la` to `libpthread.la` succeeds.

The other thing that works is modifying the script to put `-lpthread` earlier in the dep chain after `./configure` has run:
```
cd '$(1)' && ./configure \
...
$(SED) -i 's,^postdeps="-,postdeps="-lpthread -,g' '$(1)/libtool'
$(MAKE) ...
```

The posix thread build works as `gcc` links pthread internally and doesn't rely on libtool.

**Comment by tonytheodore** [comment]
> I think we should built native libtool (and co) as well as cmake instead of looking for a workaround for a particular package.

That ends up creating it's own set of problems - cmake is a single build with good forward and backward compatibility, libtool (and co) are not so straightforward.

I haven't looked at all the packages in #975, but they don't seem to be related to copying `libpthread.la`. This looks more like the `coin` issue where `libtool` is missing some deps in `postdeps` so I've pushed a similar change.
