### ISSUE TITLE
Requirements for OS X El Capitan

### ISSUE THREAD

**Issue by stjosh** [mxe/mxe#990]
The requirements installation instructions in index.html did not work for me on OS X El Capitan. I chose to install the requirement via MacPorts. In addition to the packages already mentioned (gdk-pixbuf2 glib2 intltool p5-xml-parser p7zip gpatch scons wget xz), I had to install `cmake` and `gsed` via MacPorts. 

Additionally, I could not make the 'build-requirements' target - it always failed with `make[1]: *** No rule to make target 'autoconf'.  Stop.` However, this did not seem to be necessary anyway - cross compiling works fine without the `make build-requirements` step.

I'm not sure whether this is specific to my setup or whether the installation is generally different on El Capitan, so that's why I did not choose to create a patch / pull request on index.html right away.

**Comment by aquiles2k** [comment]
I'm still on Yosemite and can confirm both issues on a clean cloned repo using macports.
- cmake and gsed missing
- build-requirements failing as stated above

**Comment by stjosh** [comment]
additionally, the documentation talks about installing Xcode5, however, the current version is Xcode7.

**Comment by starius** [comment]
Native CMake build and build-requirements are discussed here: https://github.com/mxe/mxe/issues/824#issuecomment-137521898

**Comment by starius** [comment]
@stjosh can you fix `index.html` and create a pull request, please?

**Comment by stjosh** [comment]
Created pull-request #992

**Comment by tonytheodore** [comment]
Fixed in https://github.com/mxe/mxe/commit/cdb7e99dd692025819f4b6cd63791e52f09d1db7
