### ISSUE TITLE
dlfcn-win32 finds wine

### ISSUE THREAD

**Issue by starius** [mxe/mxe#995]
`dlfcn-win32` detects `wine` with the following command:
```
$ wine --version
```
This command succeeds even if WINEPREFIX is set to an empty or read-only directory:

```
$ WINEPREFIX=/ wine --version
wine-1.6.2
```

I think we should create shell script `wine` returning exit code 1 and add it to `PATH`.

**Comment by tonytheodore** [comment]
> I think we should create shell script wine returning exit code 1 and add it to PATH.

+1, `$(PREFIX)/$(BUILD)/bin` is the ideal place for such things.
